LLVM: AArch64MCTargetDesc.cpp File Reference
LLVM API Documentation
AArch64MCTargetDesc.cpp File Reference
#include "AArch64MCTargetDesc.h"
#include "AArch64ELFStreamer.h"
#include "AArch64MCAsmInfo.h"
#include "InstPrinter/AArch64InstPrinter.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "AArch64GenInstrInfo.inc"
#include "AArch64GenSubtargetInfo.inc"
#include "AArch64GenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createAArch64MCInstrInfo ()
static MCSubtargetInfo * createAArch64MCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
static MCRegisterInfo * createAArch64MCRegisterInfo (StringRef Triple)
static MCAsmInfo * createAArch64MCAsmInfo (const MCRegisterInfo &MRI, StringRef TT)
static MCCodeGenInfo * createAArch64MCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCInstPrinter * createAArch64MCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
static MCStreamer * createMCStreamer (const Target &T, StringRef TT, MCContext &Ctx, MCAsmBackend &TAB, raw_ostream &OS, MCCodeEmitter *Emitter, const MCSubtargetInfo &STI, bool RelaxAll)
void LLVMInitializeAArch64TargetMC ()
Macro Definition Documentation
#define GET_INSTRINFO_MC_DESC
Definition at line 28 of file AArch64MCTargetDesc.cpp.
#define GET_REGINFO_MC_DESC
Definition at line 34 of file AArch64MCTargetDesc.cpp.
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 31 of file AArch64MCTargetDesc.cpp.
Function Documentation
static MCAsmInfo* createAArch64MCAsmInfo (const MCRegisterInfo & MRI, StringRef TT) static
Definition at line 60 of file AArch64MCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), assert(), llvm::MCCFIInstruction::createDefCfa(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::Triple::isOSBinFormatELF(), and llvm::Triple::isOSDarwin().
Referenced by LLVMInitializeAArch64TargetMC().
static MCCodeGenInfo* createAArch64MCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 80 of file AArch64MCTargetDesc.cpp.
References assert(), llvm::Reloc::Default, llvm::CodeModel::Default, llvm::Reloc::DynamicNoPIC, llvm::MCCodeGenInfo::InitMCCodeGenInfo(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSDarwin(), llvm::CodeModel::JITDefault, llvm::CodeModel::Large, llvm::Reloc::PIC_, llvm::report_fatal_error(), llvm::CodeModel::Small, llvm::Reloc::Static, and llvm::X.
Referenced by LLVMInitializeAArch64TargetMC().
static MCInstPrinter* createAArch64MCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 112 of file AArch64MCTargetDesc.cpp.
Referenced by LLVMInitializeAArch64TargetMC().
static MCInstrInfo* createAArch64MCInstrInfo () static
Definition at line 37 of file AArch64MCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeAArch64TargetMC().
static MCRegisterInfo* createAArch64MCRegisterInfo (StringRef Triple) static
Definition at line 54 of file AArch64MCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeAArch64TargetMC().
static MCSubtargetInfo* createAArch64MCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS) static
Definition at line 44 of file AArch64MCTargetDesc.cpp.
References llvm::StringRef::empty(), and llvm::X.
Referenced by LLVMInitializeAArch64TargetMC().
static MCStreamer* createMCStreamer (const Target & T, StringRef TT, MCContext & Ctx, MCAsmBackend & TAB, raw_ostream & OS, MCCodeEmitter * Emitter, const MCSubtargetInfo & STI, bool RelaxAll) static
Definition at line 126 of file AArch64MCTargetDesc.cpp.
References llvm::createAArch64ELFStreamer(), llvm::createMachOStreamer(), and llvm::Triple::isOSDarwin().
Referenced by LLVMInitializeAArch64TargetMC().
void LLVMInitializeAArch64TargetMC ()
Definition at line 140 of file AArch64MCTargetDesc.cpp.
References llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), llvm::createAArch64MCAsmStreamer(), llvm::createAArch64MCCodeEmitter(), createAArch64MCCodeGenInfo(), createAArch64MCInstPrinter(), createAArch64MCInstrInfo(), createAArch64MCRegisterInfo(), createAArch64MCSubtargetInfo(), createMCStreamer(), llvm::TargetRegistry::RegisterAsmStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TheAArch64beTarget, llvm::TheAArch64leTarget, llvm::TheARM64Target, llvm::X, and Y.