LLVM: AArch64RegisterInfo.cpp File Reference
LLVM API Documentation
AArch64RegisterInfo.cpp File Reference
#include "AArch64RegisterInfo.h"
#include "AArch64FrameLowering.h"
#include "AArch64InstrInfo.h"
#include "AArch64Subtarget.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetOptions.h"
#include "AArch64GenRegisterInfo.inc"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define GET_REGINFO_TARGET_DESC
Variables
static cl::opt< bool > ReserveX18 ("aarch64-reserve-x18", cl::Hidden, cl::desc("Reserve X18, making it unavailable as GPR"))
Macro Definition Documentation
#define GET_REGINFO_TARGET_DESC
Definition at line 33 of file AArch64RegisterInfo.cpp.
Variable Documentation
cl::opt<bool> ReserveX18("aarch64-reserve-x18", cl::Hidden, cl::desc("Reserve X18, making it unavailable as GPR")) static
Referenced by llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getReservedRegs(), and llvm::AArch64RegisterInfo::isReservedReg().