LLVM: AArch64A53Fix835769.cpp File Reference
LLVM API Documentation
AArch64A53Fix835769.cpp File Reference
#include "AArch64.h"
#include "AArch64InstrInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "aarch64-fix-cortex-a53-835769"
Functions
STATISTIC (NumNopsAdded,"Number of Nops added to work around erratum 835769")
static bool isFirstInstructionInSequence (MachineInstr *MI)
static bool isSecondInstructionInSequence (MachineInstr *MI)
static MachineBasicBlock * getBBFallenThrough (MachineBasicBlock *MBB, const TargetInstrInfo *TII)
static MachineInstr * getLastNonPseudo (MachineBasicBlock &MBB, const TargetInstrInfo *TII)
static void insertNopBeforeInstruction (MachineBasicBlock &MBB, MachineInstr *MI, const TargetInstrInfo *TII)
Macro Definition Documentation
#define DEBUG_TYPE "aarch64-fix-cortex-a53-835769"
Definition at line 32 of file AArch64A53Fix835769.cpp.
Function Documentation
static MachineBasicBlock* getBBFallenThrough (MachineBasicBlock * MBB, const TargetInstrInfo * TII) static
Definition at line 126 of file AArch64A53Fix835769.cpp.
References llvm::TargetInstrInfo::AnalyzeBranch(), llvm::MachineFunction::begin(), llvm::MachineBasicBlock::getParent(), and llvm::MachineBasicBlock::predecessors().
Referenced by getLastNonPseudo().
static MachineInstr* getLastNonPseudo (MachineBasicBlock & MBB, const TargetInstrInfo * TII) static
Definition at line 151 of file AArch64A53Fix835769.cpp.
References getBBFallenThrough(), I, llvm::MachineBasicBlock::rbegin(), and llvm::MachineBasicBlock::rend().
Referenced by insertNopBeforeInstruction().
static void insertNopBeforeInstruction (MachineBasicBlock & MBB, MachineInstr * MI, const TargetInstrInfo * TII) static
Definition at line 168 of file AArch64A53Fix835769.cpp.
References assert(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::front(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), getLastNonPseudo(), llvm::MachineInstr::getParent(), and I.
static bool isFirstInstructionInSequence (MachineInstr * MI) static
Definition at line 41 of file AArch64A53Fix835769.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::mayLoad(), and llvm::MachineInstr::mayStore().
static bool isSecondInstructionInSequence (MachineInstr * MI) static
Definition at line 57 of file AArch64A53Fix835769.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
STATISTIC (NumNopsAdded , "Number of Nops added to work around erratum 835769")