LLVM: AMDGPUAsmPrinter.cpp File Reference
LLVM API Documentation
AMDGPUAsmPrinter.cpp File Reference
#include "AMDGPUAsmPrinter.h"
#include "AMDGPU.h"
#include "AMDKernelCodeT.h"
#include "AMDGPUSubtarget.h"
#include "R600Defines.h"
#include "R600MachineFunctionInfo.h"
#include "R600RegisterInfo.h"
#include "SIDefines.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Functions
static uint32_t getFPMode (const MachineFunction &F)
static AsmPrinter * createAMDGPUAsmPrinterPass (TargetMachine &tm, MCStreamer &Streamer)
void LLVMInitializeR600AsmPrinter ()
static unsigned getRsrcReg (unsigned ShaderType)
Detailed Description
The AMDGPUAsmPrinter is used to print both assembly string and also binary code. When passed an MCAsmStreamer it prints assembly and when passed an MCObjectStreamer it outputs binary code.
Definition in file AMDGPUAsmPrinter.cpp.
Function Documentation
static AsmPrinter* createAMDGPUAsmPrinterPass (TargetMachine & tm, MCStreamer & Streamer) static
Definition at line 76 of file AMDGPUAsmPrinter.cpp.
Referenced by LLVMInitializeR600AsmPrinter().
static uint32_t getFPMode (const MachineFunction & F) static
Definition at line 60 of file AMDGPUAsmPrinter.cpp.
References FP_DENORM_FLUSH_IN_FLUSH_OUT, FP_DENORM_FLUSH_NONE, FP_DENORM_MODE_DP, FP_DENORM_MODE_SP, FP_ROUND_MODE_DP, FP_ROUND_MODE_SP, FP_ROUND_ROUND_TO_NEAREST, llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::AMDGPUSubtarget::hasFP32Denormals(), llvm::AMDGPUSubtarget::hasFP64Denormals(), and llvm::AArch64DB::ST.
static unsigned getRsrcReg (unsigned ShaderType) static
Definition at line 411 of file AMDGPUAsmPrinter.cpp.
References ShaderType::COMPUTE, ShaderType::GEOMETRY, ShaderType::PIXEL, R_00B028_SPI_SHADER_PGM_RSRC1_PS, R_00B128_SPI_SHADER_PGM_RSRC1_VS, R_00B228_SPI_SHADER_PGM_RSRC1_GS, R_00B848_COMPUTE_PGM_RSRC1, and ShaderType::VERTEX.
void LLVMInitializeR600AsmPrinter ()
Definition at line 81 of file AMDGPUAsmPrinter.cpp.
References createAMDGPUAsmPrinterPass(), llvm::TargetRegistry::RegisterAsmPrinter(), llvm::TheAMDGPUTarget, and llvm::TheGCNTarget.