LLVM: AMDGPUMCTargetDesc.cpp File Reference
LLVM API Documentation
AMDGPUMCTargetDesc.cpp File Reference
This file provides AMDGPU specific target descriptions.
#include "AMDGPUMCTargetDesc.h"
#include "AMDGPUMCAsmInfo.h"
#include "InstPrinter/AMDGPUInstPrinter.h"
#include "SIDefines.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "AMDGPUGenInstrInfo.inc"
#include "AMDGPUGenSubtargetInfo.inc"
#include "AMDGPUGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createAMDGPUMCInstrInfo ()
static MCRegisterInfo * createAMDGPUMCRegisterInfo (StringRef TT)
static MCSubtargetInfo * createAMDGPUMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
static MCCodeGenInfo * createAMDGPUMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCInstPrinter * createAMDGPUMCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
static MCCodeEmitter * createAMDGPUMCCodeEmitter (const MCInstrInfo &MCII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI, MCContext &Ctx)
static MCStreamer * createMCStreamer (const Target &T, StringRef TT, MCContext &Ctx, MCAsmBackend &MAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, const MCSubtargetInfo &STI, bool RelaxAll)
void LLVMInitializeR600TargetMC ()
Detailed Description
This file provides AMDGPU specific target descriptions.
Definition in file AMDGPUMCTargetDesc.cpp.
Macro Definition Documentation
#define GET_INSTRINFO_MC_DESC
Definition at line 30 of file AMDGPUMCTargetDesc.cpp.
#define GET_REGINFO_MC_DESC
Definition at line 36 of file AMDGPUMCTargetDesc.cpp.
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 33 of file AMDGPUMCTargetDesc.cpp.
Function Documentation
static MCCodeEmitter* createAMDGPUMCCodeEmitter (const MCInstrInfo & MCII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 75 of file AMDGPUMCTargetDesc.cpp.
References llvm::createR600MCCodeEmitter(), llvm::createSIMCCodeEmitter(), and llvm::MCSubtargetInfo::getFeatureBits().
Referenced by LLVMInitializeR600TargetMC().
static MCCodeGenInfo* createAMDGPUMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 58 of file AMDGPUMCTargetDesc.cpp.
References llvm::MCCodeGenInfo::InitMCCodeGenInfo(), and llvm::X.
Referenced by LLVMInitializeR600TargetMC().
static MCInstPrinter* createAMDGPUMCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 66 of file AMDGPUMCTargetDesc.cpp.
Referenced by LLVMInitializeR600TargetMC().
static MCInstrInfo* createAMDGPUMCInstrInfo () static
Definition at line 39 of file AMDGPUMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeR600TargetMC().
static MCRegisterInfo* createAMDGPUMCRegisterInfo (StringRef TT) static
Definition at line 45 of file AMDGPUMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeR600TargetMC().
static MCSubtargetInfo* createAMDGPUMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS) static
Definition at line 51 of file AMDGPUMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeR600TargetMC().
static MCStreamer* createMCStreamer (const Target & T, StringRef TT, MCContext & Ctx, MCAsmBackend & MAB, raw_ostream & _OS, MCCodeEmitter * _Emitter, const MCSubtargetInfo & STI, bool RelaxAll) static
Definition at line 86 of file AMDGPUMCTargetDesc.cpp.
References llvm::createELFStreamer().
Referenced by LLVMInitializeR600TargetMC().
void LLVMInitializeR600TargetMC ()
Definition at line 93 of file AMDGPUMCTargetDesc.cpp.
References llvm::createAMDGPUAsmBackend(), createAMDGPUMCCodeEmitter(), createAMDGPUMCCodeGenInfo(), createAMDGPUMCInstPrinter(), createAMDGPUMCInstrInfo(), createAMDGPUMCRegisterInfo(), createAMDGPUMCSubtargetInfo(), createMCStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TheAMDGPUTarget, llvm::TheGCNTarget, and Y.