LLVM: ARMInstPrinter.cpp File Reference
LLVM API Documentation
ARMInstPrinter.cpp File Reference
#include "ARMInstPrinter.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/raw_ostream.h"
#include "ARMGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static unsigned translateShiftImm (unsigned imm)
static void printRegImmShift (raw_ostream &O, ARM_AM::ShiftOpc ShOpc, unsigned ShImm, bool UseMarkup)
Prints the shift value with an immediate value.
Macro Definition Documentation
#define DEBUG_TYPE "asm-printer"
Definition at line 25 of file ARMInstPrinter.cpp.
Function Documentation
static void printRegImmShift (raw_ostream & O, ARM_AM::ShiftOpc ShOpc, unsigned ShImm, bool UseMarkup) static
Prints the shift value with an immediate value.
Definition at line 42 of file ARMInstPrinter.cpp.
References assert(), llvm::ARM_AM::getShiftOpcStr(), llvm::ARM_AM::lsl, llvm::ARM_AM::no_shift, llvm::ARM_AM::ror, llvm::ARM_AM::rrx, and translateShiftImm().
Referenced by llvm::ARMInstPrinter::printAddrMode2OffsetOperand(), llvm::ARMInstPrinter::printAM2PreOrOffsetIndexOp(), llvm::ARMInstPrinter::printSORegImmOperand(), and llvm::ARMInstPrinter::printT2SOOperand().
static unsigned translateShiftImm (unsigned imm) static
translateShiftImm - Convert shift immediate from 0-31 to 1-32 for printing.
getSORegOffset returns an integer from 0-31, representing '32' as 0.
Definition at line 32 of file ARMInstPrinter.cpp.
References assert().
Referenced by llvm::ARMInstPrinter::printInst(), and printRegImmShift().