LLVM: ARMOptimizeBarriersPass.cpp File Reference
LLVM API Documentation
ARMOptimizeBarriersPass.cpp File Reference
#include "ARM.h"
#include "ARMInstrInfo.h"
#include "ARMMachineFunctionInfo.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
Macros
#define DEBUG_TYPE "double barriers"
Functions
STATISTIC (NumDMBsRemoved,"Number of DMBs removed")
static bool CanMovePastDMB (const MachineInstr *MI)
Macro Definition Documentation
#define DEBUG_TYPE "double barriers"
Definition at line 18 of file ARMOptimizeBarriersPass.cpp.
Function Documentation
static bool CanMovePastDMB (const MachineInstr * MI) static
Definition at line 42 of file ARMOptimizeBarriersPass.cpp.
References llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isReturn(), llvm::MachineInstr::mayLoad(), and llvm::MachineInstr::mayStore().
STATISTIC (NumDMBsRemoved , "Number of DMBs removed")