LLVM: ARMTargetMachine.cpp File Reference
LLVM API Documentation
ARMTargetMachine.cpp File Reference
#include "ARM.h"
#include "ARMFrameLowering.h"
#include "ARMTargetMachine.h"
#include "ARMTargetObjectFile.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/Scalar.h"
Functions
void LLVMInitializeARMTarget ()
static std::unique_ptr
< TargetLoweringObjectFile > createTLOF (const Triple &TT)
static ARMBaseTargetMachine::ARMABI computeTargetABI (const Triple &TT, StringRef CPU, const TargetOptions &Options)
Variables
static cl::opt< bool > DisableA15SDOptimization ("disable-a15-sd-optimization", cl::Hidden, cl::desc("Inhibit optimization of S->D register accesses on A15"), cl::init(false))
static cl::opt< bool > EnableAtomicTidy ("arm-atomic-cfg-tidy", cl::Hidden, cl::desc("Run SimplifyCFG after expanding atomic operations"" to make use of cmpxchg flow-based information"), cl::init(true))
Function Documentation
static ARMBaseTargetMachine::ARMABI computeTargetABI (const Triple & TT, StringRef CPU, const TargetOptions & Options) static
Definition at line 56 of file ARMTargetMachine.cpp.
References llvm::Triple::Android, llvm::ARMBaseTargetMachine::ARM_ABI_AAPCS, llvm::ARMBaseTargetMachine::ARM_ABI_APCS, llvm::ARMBaseTargetMachine::ARM_ABI_UNKNOWN, assert(), llvm::Triple::EABI, llvm::Triple::EABIHF, llvm::StringRef::empty(), llvm::MCTargetOptions::getABIName(), llvm::Triple::getEnvironment(), llvm::Triple::getObjectFormat(), llvm::Triple::getOS(), llvm::Triple::GNU, llvm::Triple::GNUEABI, llvm::Triple::GNUEABIHF, llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSWindows(), llvm::Triple::MachO, llvm::TargetOptions::MCOptions, llvm::Triple::NetBSD, llvm::StringRef::startswith(), and llvm::Triple::UnknownOS.
static std::unique_ptr<TargetLoweringObjectFile> createTLOF (const Triple & TT) static
Definition at line 47 of file ARMTargetMachine.cpp.
References llvm::Triple::isOSBinFormatMachO(), and llvm::Triple::isOSWindows().
void LLVMInitializeARMTarget ()
Definition at line 39 of file ARMTargetMachine.cpp.
References llvm::ARM_PROC::A, llvm::TheARMBETarget, llvm::TheARMLETarget, llvm::TheThumbBETarget, llvm::TheThumbLETarget, llvm::X, and Y.
Variable Documentation
cl::opt<bool> DisableA15SDOptimization("disable-a15-sd-optimization", cl::Hidden, cl::desc("Inhibit optimization of S->D register accesses on A15"), cl::init(false)) static
cl::opt<bool> EnableAtomicTidy("arm-atomic-cfg-tidy", cl::Hidden, cl::desc("Run SimplifyCFG after expanding atomic operations"" to make use of cmpxchg flow-based information"), cl::init(true)) static