LLVM: AsmWriter.cpp File Reference
LLVM API Documentation
AsmWriter.cpp File Reference
#include "AsmWriter.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/AssemblyAnnotationWriter.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/TypeFinder.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/MathExtras.h"
#include <algorithm>
#include <cctype>
#include "llvm/IR/Metadata.def"
Classes
class llvm::SlotTracker
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define ST_DEBUG(X)
#define HANDLE_UNIQUABLE_LEAF(CLASS)
Enumerations
enum PrefixType {
GlobalPrefix, ComdatPrefix, LabelPrefix, LocalPrefix,
NoPrefix
}
Functions
static void orderValue (const Value *V, OrderMap &OM)
static OrderMap orderModule (const Module *M)
static void predictValueUseListOrderImpl (const Value *V, const Function *F, unsigned ID, const OrderMap &OM, UseListOrderStack &Stack)
static void predictValueUseListOrder (const Value *V, const Function *F, OrderMap &OM, UseListOrderStack &Stack)
static UseListOrderStack predictUseListOrder (const Module *M)
static const Module * getModuleFromVal (const Value *V)
static void PrintCallingConv (unsigned cc, raw_ostream &Out)
static void PrintEscapedString (StringRef Name, raw_ostream &Out)
static void PrintLLVMName (raw_ostream &OS, StringRef Name, PrefixType Prefix)
static void PrintLLVMName (raw_ostream &OS, const Value *V)
SlotTracker * llvm::createSlotTracker (const Module *M)
Create a new SlotTracker for a Module.
static SlotTracker * llvm::createSlotTracker (const Value *V)
static void llvm::WriteAsOperandInternal (raw_ostream &Out, const Value *V, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void llvm::WriteAsOperandInternal (raw_ostream &Out, const Metadata *MD, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context, bool FromValue=false)
static const char * llvm::getPredicateText (unsigned predicate)
static void llvm::writeAtomicRMWOperation (raw_ostream &Out, AtomicRMWInst::BinOp Op)
static void llvm::WriteOptimizationInfo (raw_ostream &Out, const User *U)
static void llvm::WriteConstantInternal (raw_ostream &Out, const Constant *CV, TypePrinting &TypePrinter, SlotTracker *Machine, const Module *Context)
static void llvm::writeMDTuple (raw_ostream &Out, const MDTuple *Node, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void llvm::writeMDLocation (raw_ostream &Out, const MDLocation *DL, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void llvm::WriteMDNodeBodyInternal (raw_ostream &Out, const MDNode *Node, TypePrinting *TypePrinter, SlotTracker *Machine, const Module *Context)
static void llvm::PrintLinkage (GlobalValue::LinkageTypes LT, formatted_raw_ostream &Out)
static void llvm::PrintVisibility (GlobalValue::VisibilityTypes Vis, formatted_raw_ostream &Out)
static void llvm::PrintDLLStorageClass (GlobalValue::DLLStorageClassTypes SCT, formatted_raw_ostream &Out)
static void llvm::PrintThreadLocalModel (GlobalVariable::ThreadLocalMode TLM, formatted_raw_ostream &Out)
static void llvm::maybePrintComdat (formatted_raw_ostream &Out, const GlobalObject &GO)
static void llvm::WriteMDNodeComment (const MDNode *Node, formatted_raw_ostream &Out)
Macro Definition Documentation
#define HANDLE_UNIQUABLE_LEAF (CLASS)
Value:
case Metadata::CLASS##Kind:                                                  \
    write##CLASS(Out, cast<CLASS>(Uniquable), TypePrinter, Machine, Context);  \
    break;
#define ST_DEBUG (X)
Definition at line 643 of file AsmWriter.cpp.
Referenced by llvm::SlotTracker::purgeFunction().
Enumeration Type Documentation
enum PrefixType
Enumerator
GlobalPrefix
ComdatPrefix
LabelPrefix
LocalPrefix
NoPrefix
Definition at line 321 of file AsmWriter.cpp.
Function Documentation
static const Module* getModuleFromVal (const Value * V) static
Definition at line 264 of file AsmWriter.cpp.
References llvm::GlobalValue::getParent(), and I.
Referenced by llvm::Value::print(), and llvm::Value::printAsOperand().
static OrderMap orderModule (const Module * M) static
Definition at line 84 of file AsmWriter.cpp.
References llvm::ARM_PROC::A, llvm::Module::aliases(), F(), G, llvm::Module::globals(), I, and orderValue().
Referenced by predictUseListOrder().
static void orderValue (const Value * V, OrderMap & OM) static
Definition at line 69 of file AsmWriter.cpp.
References llvm::CallingConv::C.
Referenced by orderModule().
static UseListOrderStack predictUseListOrder (const Module * M) static
Definition at line 214 of file AsmWriter.cpp.
References llvm::ARM_PROC::A, F(), G, llvm::Module::globals(), I, llvm::GlobalValue::isDeclaration(), orderModule(), predictValueUseListOrder(), llvm::Module::rbegin(), and llvm::Module::rend().
Referenced by llvm::AssemblyWriter::printModule().
static void predictValueUseListOrder (const Value * V, const Function * F, OrderMap & OM, UseListOrderStack & Stack) static
Definition at line 193 of file AsmWriter.cpp.
References assert(), llvm::CallingConv::C, predictValueUseListOrderImpl(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
Referenced by predictUseListOrder().
static void predictValueUseListOrderImpl (const Value * V, const Function * F, unsigned ID, const OrderMap & OM, UseListOrderStack & Stack) static
Definition at line 130 of file AsmWriter.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), I, llvm::tgtok::List, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::Value::uses().
Referenced by predictValueUseListOrder().
static void PrintCallingConv (unsigned cc, raw_ostream & Out) static
Definition at line 281 of file AsmWriter.cpp.
References llvm::CallingConv::AnyReg, llvm::CallingConv::ARM_AAPCS, llvm::CallingConv::ARM_AAPCS_VFP, llvm::CallingConv::ARM_APCS, llvm::CallingConv::Cold, llvm::CallingConv::Fast, llvm::CallingConv::GHC, llvm::CallingConv::Intel_OCL_BI, llvm::CallingConv::MSP430_INTR, llvm::CallingConv::PreserveAll, llvm::CallingConv::PreserveMost, llvm::CallingConv::PTX_Device, llvm::CallingConv::PTX_Kernel, llvm::CallingConv::SPIR_FUNC, llvm::CallingConv::SPIR_KERNEL, llvm::CallingConv::WebKit_JS, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_64_Win64, llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_StdCall, llvm::CallingConv::X86_ThisCall, and llvm::CallingConv::X86_VectorCall.
Referenced by llvm::AssemblyWriter::printFunction(), and llvm::AssemblyWriter::printInstruction().
static void PrintEscapedString (StringRef Name, raw_ostream & Out) static
Definition at line 311 of file AsmWriter.cpp.
References llvm::CallingConv::C, llvm::hexdigit(), and llvm::StringRef::size().
Referenced by llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), PrintLLVMName(), llvm::AssemblyWriter::printModule(), llvm::WriteAsOperandInternal(), and llvm::WriteConstantInternal().
static void PrintLLVMName (raw_ostream & OS, StringRef Name, PrefixType Prefix) static
PrintLLVMName - Turn the specified name into an 'LLVM name', which is either prefixed with % (if the string only contains simple characters) or is surrounded with ""'s (if it has special chars in it). Print it out.
Definition at line 332 of file AsmWriter.cpp.
References assert(), llvm::CallingConv::C, ComdatPrefix, llvm::StringRef::empty(), GlobalPrefix, llvm::LibFunc::isdigit, LabelPrefix, LocalPrefix, Name, NoPrefix, PrintEscapedString(), and llvm::StringRef::size().
Referenced by llvm::maybePrintComdat(), llvm::Comdat::print(), llvm::TypePrinting::print(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printArgument(), llvm::AssemblyWriter::printBasicBlock(), llvm::AssemblyWriter::printInstruction(), PrintLLVMName(), and llvm::AssemblyWriter::printTypeIdentities().
static void PrintLLVMName (raw_ostream & OS, const Value * V) static
PrintLLVMName - Turn the specified name into an 'LLVM name', which is either prefixed with % (if the string only contains simple characters) or is surrounded with ""'s (if it has special chars in it). Print it out.
Definition at line 375 of file AsmWriter.cpp.
References llvm::Value::getName(), GlobalPrefix, LocalPrefix, and PrintLLVMName().
Variable Documentation
bool Skip
Definition at line 1277 of file AsmWriter.cpp.
Referenced by llvm::StringRef::find().