LLVM: AutoUpgrade.cpp File Reference
LLVM API Documentation
AutoUpgrade.cpp File Reference
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/ErrorHandling.h"
#include <cstring>
Functions
static bool UpgradeSSE41Function (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool UpgradeX86IntrinsicsWith8BitMask (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool UpgradeIntrinsicFunction1 (Function *F, Function *&NewFn)
static MDNode * getNodeField (const MDNode *DbgNode, unsigned Elt)
static MetadataAsValue * getExpression (Value *VarOperand, Function *F)
Function Documentation
static MetadataAsValue* getExpression (Value * VarOperand, Function * F) static
Definition at line 263 of file AutoUpgrade.cpp.
References llvm::MetadataAsValue::get(), llvm::Function::getContext(), getNodeField(), and llvm::GlobalValue::getParent().
Referenced by llvm::UpgradeIntrinsicCall().
static MDNode* getNodeField (const MDNode * DbgNode, unsigned Elt) static
Definition at line 257 of file AutoUpgrade.cpp.
References llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
Referenced by getExpression().
static bool UpgradeIntrinsicFunction1 (Function * F, Function *& NewFn) static
Definition at line 63 of file AutoUpgrade.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_size(), assert(), llvm::Function::Create(), llvm::Intrinsic::ctlz, llvm::Intrinsic::ctpop, llvm::Intrinsic::cttz, llvm::Intrinsic::dbg_declare, llvm::Intrinsic::dbg_value, F(), llvm::FunctionType::get(), llvm::Function::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt1Ty(), llvm::GlobalValue::getLinkage(), llvm::Intrinsic::getName(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::Function::getReturnType(), Name, llvm::Intrinsic::objectsize, llvm::Value::setName(), llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::StringRef::substr(), UpgradeSSE41Function(), UpgradeX86IntrinsicsWith8BitMask(), llvm::Intrinsic::x86_avx2_mpsadbw, llvm::Intrinsic::x86_avx2_pblendd_128, llvm::Intrinsic::x86_avx2_pblendd_256, llvm::Intrinsic::x86_avx2_pblendw, llvm::Intrinsic::x86_avx_blend_pd_256, llvm::Intrinsic::x86_avx_blend_ps_256, llvm::Intrinsic::x86_avx_dp_ps_256, llvm::Intrinsic::x86_sse41_blendpd, llvm::Intrinsic::x86_sse41_blendps, llvm::Intrinsic::x86_sse41_dppd, llvm::Intrinsic::x86_sse41_dpps, llvm::Intrinsic::x86_sse41_insertps, llvm::Intrinsic::x86_sse41_mpsadbw, llvm::Intrinsic::x86_sse41_pblendw, llvm::Intrinsic::x86_sse41_ptestc, llvm::Intrinsic::x86_sse41_ptestnzc, llvm::Intrinsic::x86_sse41_ptestz, llvm::Intrinsic::x86_xop_vfrcz_sd, and llvm::Intrinsic::x86_xop_vfrcz_ss.
Referenced by llvm::UpgradeIntrinsicFunction().
static bool UpgradeSSE41Function (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 33 of file AutoUpgrade.cpp.
References llvm::VectorType::get(), llvm::Function::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getFloatTy(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::FunctionType::getParamType(), llvm::GlobalValue::getParent(), and llvm::Value::setName().
Referenced by UpgradeIntrinsicFunction1().
static bool UpgradeX86IntrinsicsWith8BitMask (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 49 of file AutoUpgrade.cpp.
References llvm::Intrinsic::getDeclaration(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::GlobalValue::getParent(), llvm::Type::isIntegerTy(), and llvm::Value::setName().
Referenced by UpgradeIntrinsicFunction1().