LLVM: BitcodeReader.cpp File Reference
LLVM API Documentation
BitcodeReader.cpp File Reference
#include "llvm/Bitcode/ReaderWriter.h"
#include "BitcodeReader.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Bitcode/LLVMBitCodes.h"
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/OperandTraits.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/DataStream.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct llvm::OperandTraits< ConstantPlaceHolder >
Namespaces
llvm
List of target independent CodeGen pass IDs.
Enumerations
enum { SWITCH_INST_MAGIC = 0x4B5 }
Functions
static std::error_code Error (DiagnosticHandlerFunction DiagnosticHandler, std::error_code EC, const Twine &Message)
static std::error_code Error (DiagnosticHandlerFunction DiagnosticHandler, std::error_code EC)
static DiagnosticHandlerFunction getDiagHandler (DiagnosticHandlerFunction F, LLVMContext &C)
template<typename StrTy >
static bool ConvertToString (ArrayRef< uint64_t > Record, unsigned Idx, StrTy &Result)
static GlobalValue::LinkageTypes getDecodedLinkage (unsigned Val)
static GlobalValue::VisibilityTypes GetDecodedVisibility (unsigned Val)
static
GlobalValue::DLLStorageClassTypes GetDecodedDLLStorageClass (unsigned Val)
static
GlobalVariable::ThreadLocalMode GetDecodedThreadLocalMode (unsigned Val)
static int GetDecodedCastOpcode (unsigned Val)
static int GetDecodedBinaryOpcode (unsigned Val, Type *Ty)
static AtomicRMWInst::BinOp GetDecodedRMWOperation (unsigned Val)
static AtomicOrdering GetDecodedOrdering (unsigned Val)
static SynchronizationScope GetDecodedSynchScope (unsigned Val)
static Comdat::SelectionKind getDecodedComdatSelectionKind (unsigned Val)
static void UpgradeDLLImportExportLinkage (llvm::GlobalValue *GV, unsigned Val)
static void decodeLLVMAttributesForBitcode (AttrBuilder &B, uint64_t EncodedAttrs)
This fills an AttrBuilder object with the LLVM attributes that have been decoded from the given integer. This function must stay in sync with 'encodeLLVMAttributesForBitcode'.
static Attribute::AttrKind GetAttrFromCode (uint64_t Code)
static APInt ReadWideAPInt (ArrayRef< uint64_t > Vals, unsigned TypeBits)
static ErrorOr< Module * > getLazyBitcodeModuleImpl (std::unique_ptr< MemoryBuffer > &&Buffer, LLVMContext &Context, bool WillMaterializeAll, DiagnosticHandlerFunction DiagnosticHandler)
Get a lazy one-at-time loading module from bitcode.
Variables
static ManagedStatic
< BitcodeErrorCategoryType > ErrorCategory
Enumeration Type Documentation
anonymous enum
Enumerator
SWITCH_INST_MAGIC
Definition at line 33 of file BitcodeReader.cpp.
Function Documentation
template<typename StrTy > static bool ConvertToString (ArrayRef< uint64_t > Record, unsigned Idx, StrTy & Result) static
ConvertToString - Convert a string from a record into an std::string, return true on failure.
Definition at line 149 of file BitcodeReader.cpp.
References llvm::ArrayRef< T >::size().
static void decodeLLVMAttributesForBitcode (AttrBuilder & B, uint64_t EncodedAttrs) static
This fills an AttrBuilder object with the LLVM attributes that have been decoded from the given integer. This function must stay in sync with 'encodeLLVMAttributesForBitcode'.
Definition at line 613 of file BitcodeReader.cpp.
References llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addRawValue(), assert(), and llvm::isPowerOf2_32().
static std::error_code Error (DiagnosticHandlerFunction DiagnosticHandler, std::error_code EC, const Twine & Message) static
Definition at line 44 of file BitcodeReader.cpp.
References llvm::DS_Error.
Referenced by Error(), and llvm::BitcodeReader::Error().
static std::error_code Error (DiagnosticHandlerFunction DiagnosticHandler, std::error_code EC) static
Definition at line 51 of file BitcodeReader.cpp.
References Error().
static Attribute::AttrKind GetAttrFromCode (uint64_t Code) static
Definition at line 688 of file BitcodeReader.cpp.
References llvm::Attribute::Alignment, llvm::Attribute::AlwaysInline, llvm::bitc::ATTR_KIND_ALIGNMENT, llvm::bitc::ATTR_KIND_ALWAYS_INLINE, llvm::bitc::ATTR_KIND_BUILTIN, llvm::bitc::ATTR_KIND_BY_VAL, llvm::bitc::ATTR_KIND_COLD, llvm::bitc::ATTR_KIND_DEREFERENCEABLE, llvm::bitc::ATTR_KIND_IN_ALLOCA, llvm::bitc::ATTR_KIND_IN_REG, llvm::bitc::ATTR_KIND_INLINE_HINT, llvm::bitc::ATTR_KIND_JUMP_TABLE, llvm::bitc::ATTR_KIND_MIN_SIZE, llvm::bitc::ATTR_KIND_NAKED, llvm::bitc::ATTR_KIND_NEST, llvm::bitc::ATTR_KIND_NO_ALIAS, llvm::bitc::ATTR_KIND_NO_BUILTIN, llvm::bitc::ATTR_KIND_NO_CAPTURE, llvm::bitc::ATTR_KIND_NO_DUPLICATE, llvm::bitc::ATTR_KIND_NO_IMPLICIT_FLOAT, llvm::bitc::ATTR_KIND_NO_INLINE, llvm::bitc::ATTR_KIND_NO_RED_ZONE, llvm::bitc::ATTR_KIND_NO_RETURN, llvm::bitc::ATTR_KIND_NO_UNWIND, llvm::bitc::ATTR_KIND_NON_LAZY_BIND, llvm::bitc::ATTR_KIND_NON_NULL, llvm::bitc::ATTR_KIND_OPTIMIZE_FOR_SIZE, llvm::bitc::ATTR_KIND_OPTIMIZE_NONE, llvm::bitc::ATTR_KIND_READ_NONE, llvm::bitc::ATTR_KIND_READ_ONLY, llvm::bitc::ATTR_KIND_RETURNED, llvm::bitc::ATTR_KIND_RETURNS_TWICE, llvm::bitc::ATTR_KIND_S_EXT, llvm::bitc::ATTR_KIND_SANITIZE_ADDRESS, llvm::bitc::ATTR_KIND_SANITIZE_MEMORY, llvm::bitc::ATTR_KIND_SANITIZE_THREAD, llvm::bitc::ATTR_KIND_STACK_ALIGNMENT, llvm::bitc::ATTR_KIND_STACK_PROTECT, llvm::bitc::ATTR_KIND_STACK_PROTECT_REQ, llvm::bitc::ATTR_KIND_STACK_PROTECT_STRONG, llvm::bitc::ATTR_KIND_STRUCT_RET, llvm::bitc::ATTR_KIND_UW_TABLE, llvm::bitc::ATTR_KIND_Z_EXT, llvm::Attribute::Builtin, llvm::Attribute::ByVal, llvm::Attribute::Cold, llvm::Attribute::Dereferenceable, llvm::Attribute::InAlloca, llvm::Attribute::InlineHint, llvm::Attribute::InReg, llvm::Attribute::JumpTable, llvm::Attribute::MinSize, llvm::Attribute::Naked, llvm::Attribute::Nest, llvm::Attribute::NoAlias, llvm::Attribute::NoBuiltin, llvm::Attribute::NoCapture, llvm::Attribute::NoDuplicate, llvm::Attribute::NoImplicitFloat, llvm::Attribute::NoInline, llvm::Attribute::None, llvm::Attribute::NonLazyBind, llvm::Attribute::NonNull, llvm::Attribute::NoRedZone, llvm::Attribute::NoReturn, llvm::Attribute::NoUnwind, llvm::Attribute::OptimizeForSize, llvm::Attribute::OptimizeNone, llvm::Attribute::ReadNone, llvm::Attribute::ReadOnly, llvm::Attribute::Returned, llvm::Attribute::ReturnsTwice, llvm::Attribute::SanitizeAddress, llvm::Attribute::SanitizeMemory, llvm::Attribute::SanitizeThread, llvm::Attribute::SExt, llvm::Attribute::StackAlignment, llvm::Attribute::StackProtect, llvm::Attribute::StackProtectReq, llvm::Attribute::StackProtectStrong, llvm::Attribute::StructRet, llvm::Attribute::UWTable, and llvm::Attribute::ZExt.
static int GetDecodedBinaryOpcode (unsigned Val, Type * Ty) static
Definition at line 245 of file BitcodeReader.cpp.
References llvm::Add, llvm::APIntOps::And(), llvm::bitc::BINOP_ADD, llvm::bitc::BINOP_AND, llvm::bitc::BINOP_ASHR, llvm::bitc::BINOP_LSHR, llvm::bitc::BINOP_MUL, llvm::bitc::BINOP_OR, llvm::bitc::BINOP_SDIV, llvm::bitc::BINOP_SHL, llvm::bitc::BINOP_SREM, llvm::bitc::BINOP_SUB, llvm::bitc::BINOP_UDIV, llvm::bitc::BINOP_UREM, llvm::bitc::BINOP_XOR, llvm::Type::isFPOrFPVectorTy(), llvm::APIntOps::Or(), llvm::Sub, and llvm::APIntOps::Xor().
static int GetDecodedCastOpcode (unsigned Val) static
Definition at line 227 of file BitcodeReader.cpp.
References llvm::bitc::CAST_ADDRSPACECAST, llvm::bitc::CAST_BITCAST, llvm::bitc::CAST_FPEXT, llvm::bitc::CAST_FPTOSI, llvm::bitc::CAST_FPTOUI, llvm::bitc::CAST_FPTRUNC, llvm::bitc::CAST_INTTOPTR, llvm::bitc::CAST_PTRTOINT, llvm::bitc::CAST_SEXT, llvm::bitc::CAST_SITOFP, llvm::bitc::CAST_TRUNC, llvm::bitc::CAST_UITOFP, and llvm::bitc::CAST_ZEXT.
static Comdat::SelectionKind getDecodedComdatSelectionKind (unsigned Val) static
Definition at line 307 of file BitcodeReader.cpp.
References llvm::Comdat::Any, llvm::bitc::COMDAT_SELECTION_KIND_ANY, llvm::bitc::COMDAT_SELECTION_KIND_EXACT_MATCH, llvm::bitc::COMDAT_SELECTION_KIND_LARGEST, llvm::bitc::COMDAT_SELECTION_KIND_NO_DUPLICATES, llvm::bitc::COMDAT_SELECTION_KIND_SAME_SIZE, llvm::Comdat::ExactMatch, llvm::Comdat::Largest, llvm::Comdat::NoDuplicates, and llvm::Comdat::SameSize.
static GlobalValue::DLLStorageClassTypes GetDecodedDLLStorageClass (unsigned Val) static
Definition at line 207 of file BitcodeReader.cpp.
References llvm::GlobalValue::DefaultStorageClass, llvm::GlobalValue::DLLExportStorageClass, and llvm::GlobalValue::DLLImportStorageClass.
static GlobalValue::LinkageTypes getDecodedLinkage (unsigned Val) static
Definition at line 159 of file BitcodeReader.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
static AtomicOrdering GetDecodedOrdering (unsigned Val) static
Definition at line 286 of file BitcodeReader.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::Monotonic, llvm::NotAtomic, llvm::bitc::ORDERING_ACQREL, llvm::bitc::ORDERING_ACQUIRE, llvm::bitc::ORDERING_MONOTONIC, llvm::bitc::ORDERING_NOTATOMIC, llvm::bitc::ORDERING_RELEASE, llvm::bitc::ORDERING_SEQCST, llvm::bitc::ORDERING_UNORDERED, llvm::Release, llvm::SequentiallyConsistent, and llvm::Unordered.
static AtomicRMWInst::BinOp GetDecodedRMWOperation (unsigned Val) static
Definition at line 269 of file BitcodeReader.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::AtomicRMWInst::BAD_BINOP, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::bitc::RMW_ADD, llvm::bitc::RMW_AND, llvm::bitc::RMW_MAX, llvm::bitc::RMW_MIN, llvm::bitc::RMW_NAND, llvm::bitc::RMW_OR, llvm::bitc::RMW_SUB, llvm::bitc::RMW_UMAX, llvm::bitc::RMW_UMIN, llvm::bitc::RMW_XCHG, llvm::bitc::RMW_XOR, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
static SynchronizationScope GetDecodedSynchScope (unsigned Val) static
Definition at line 299 of file BitcodeReader.cpp.
References llvm::CrossThread, llvm::SingleThread, llvm::bitc::SYNCHSCOPE_CROSSTHREAD, and llvm::bitc::SYNCHSCOPE_SINGLETHREAD.
static GlobalVariable::ThreadLocalMode GetDecodedThreadLocalMode (unsigned Val) static
Definition at line 216 of file BitcodeReader.cpp.
References llvm::GlobalValue::GeneralDynamicTLSModel, llvm::GlobalValue::InitialExecTLSModel, llvm::GlobalValue::LocalDynamicTLSModel, llvm::GlobalValue::LocalExecTLSModel, and llvm::GlobalValue::NotThreadLocal.
static GlobalValue::VisibilityTypes GetDecodedVisibility (unsigned Val) static
Definition at line 197 of file BitcodeReader.cpp.
References llvm::GlobalValue::DefaultVisibility, llvm::GlobalValue::HiddenVisibility, and llvm::GlobalValue::ProtectedVisibility.
static DiagnosticHandlerFunction getDiagHandler (DiagnosticHandlerFunction F, LLVMContext & C) static
Definition at line 69 of file BitcodeReader.cpp.
References llvm::CallingConv::C, llvm::LLVMContext::diagnose(), and F().
static ErrorOr<Module *> getLazyBitcodeModuleImpl (std::unique_ptr< MemoryBuffer > && Buffer, LLVMContext & Context, bool WillMaterializeAll, DiagnosticHandlerFunction DiagnosticHandler) static
Get a lazy one-at-time loading module from bitcode.
This isn't always used in a lazy context. In particular, it's also used by parseBitcodeFile(). If this is truly lazy, then we need to eagerly pull in forward-referenced functions from block address references.
Parameters
[in] WillMaterializeAll Set to true if the caller promises to materialize everything – in particular, if this isn't truly lazy.
Definition at line 3691 of file BitcodeReader.cpp.
References llvm::Module::setMaterializer().
Referenced by llvm::getLazyBitcodeModule(), and llvm::parseBitcodeFile().
static APInt ReadWideAPInt (ArrayRef< uint64_t > Vals, unsigned TypeBits) static
Definition at line 1399 of file BitcodeReader.cpp.
References llvm::ArrayRef< T >::begin(), llvm::BitcodeReader::decodeSignRotatedValue(), llvm::ArrayRef< T >::end(), and llvm::ArrayRef< T >::size().
static void UpgradeDLLImportExportLinkage (llvm::GlobalValue * GV, unsigned Val) static
Definition at line 323 of file BitcodeReader.cpp.
References llvm::GlobalValue::DLLExportStorageClass, llvm::GlobalValue::DLLImportStorageClass, and llvm::GlobalValue::setDLLStorageClass().
Variable Documentation
ManagedStatic<BitcodeErrorCategoryType> ErrorCategory static
Definition at line 3672 of file BitcodeReader.cpp.
Referenced by llvm::BitcodeErrorCategory().