LLVM: BranchProbability.cpp File Reference
LLVM API Documentation
BranchProbability.cpp File Reference
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
Functions
static uint64_t scale (uint64_t Num, uint32_t N, uint32_t D)
Function Documentation
static uint64_t scale (uint64_t Num, uint32_t N, uint32_t D) static
Definition at line 28 of file BranchProbability.cpp.
References assert().
Referenced by llvm::ARMInstPrinter::printAdrLabelOperand(), llvm::BranchProbability::scale(), llvm::ScaledNumber< DigitsT >::scale(), and llvm::BranchProbability::scaleByInverse().