LLVM: BuildLibCalls.cpp File Reference
LLVM API Documentation
BuildLibCalls.cpp File Reference
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Target/TargetLibraryInfo.h"
Functions
static void AppendTypeSuffix (Value *Op, StringRef &Name, SmallString< 20 > &NameBuffer)
Append a suffix to the function name according to the type of 'Op'.
Function Documentation
static void AppendTypeSuffix (Value * Op, StringRef & Name, SmallString< 20 > & NameBuffer) static
Append a suffix to the function name according to the type of 'Op'.
Definition at line 285 of file BuildLibCalls.cpp.
References llvm::Value::getType(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), and Name.
Referenced by llvm::EmitBinaryFloatFnCall(), and llvm::EmitUnaryFloatFnCall().