LLVM: IRReader.h File Reference
LLVM API Documentation
c/IRReader.h File Reference
#include "llvm-c/Core.h"
Functions
LLVMBool LLVMParseIRInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
Function Documentation
LLVMBool LLVMParseIRInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Read LLVM IR from a memory buffer and convert it into an in-memory Module object. Returns 0 on success. Optionally returns a human-readable description of any errors that occurred during parsing IR. OutMessage must be disposed with LLVMDisposeMessage.
See Also
llvm::ParseIR()
Definition at line 99 of file IRReader.cpp.
References llvm::raw_ostream::flush(), llvm::parseIR(), llvm::SMDiagnostic::print(), llvm::LibFunc::strdup, llvm::unwrap(), and llvm::wrap().