LLVM: llvm::BlockAddress Class Reference
LLVM API Documentation
llvm::BlockAddress Class Reference
#include <Constants.h>
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Function * getFunction () const
BasicBlock * getBasicBlock () const
void destroyConstant () override
void replaceUsesOfWithOnConstant (Value *From, Value *To, Use *U) override
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isOneValue () const
Returns true if the value is one.
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
void removeDeadConstantUsers () const
Constant * stripPointerCasts ()
const Constant * stripPointerCasts () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range
< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range
< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Static Public Member Functions
static BlockAddress * get (Function *F, BasicBlock *BB)
get - Return a BlockAddress for the specified function and basic block.
static BlockAddress * get (BasicBlock *BB)
static BlockAddress * lookup (const BasicBlock *BB)
Lookup an existing BlockAddress constant for the given BasicBlock.
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Additional Inherited Members
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0, LocalRelocation = 1, GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range
< op_iterator > op_range
typedef iterator_range
< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MetadataAsValueVal, InlineAsmVal, InstructionVal,
ConstantFirstVal = FunctionVal, ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl
< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl
< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
void replaceUsesOfWithOnConstantImpl (Constant *Replacement)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
BlockAddress - The address of a basic block.
Definition at line 758 of file Constants.h.
Member Function Documentation
static bool llvm::BlockAddress::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 786 of file Constants.h.
References llvm::Value::BlockAddressVal, and llvm::Value::getValueID().
llvm::BlockAddress::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
void BlockAddress::destroyConstant () override virtual
destroyConstant - Called if some element of this constant is no longer valid. At this point only other constants may be on the use_list for this constant. Any constants on our Use list must also be destroy'd. The implementation must be sure to remove the constant from the list of available cached constants. Implementations should call destroyConstantImpl as the last thing they do, to destroy all users and delete this.
Reimplemented from llvm::Constant.
Definition at line 1502 of file Constants.cpp.
References llvm::LLVMContextImpl::BlockAddresses, llvm::Constant::destroyConstantImpl(), getBasicBlock(), llvm::Type::getContext(), getFunction(), llvm::GlobalValue::getType(), and llvm::LLVMContext::pImpl.
Referenced by llvm::MergeBasicBlockIntoOnlyPred(), and llvm::BasicBlock::~BasicBlock().
BlockAddress * BlockAddress::get (Function * F, BasicBlock * BB) static
get - Return a BlockAddress for the specified function and basic block.
Definition at line 1470 of file Constants.cpp.
References assert(), llvm::LLVMContextImpl::BlockAddresses, llvm::Function::getContext(), getFunction(), and llvm::LLVMContext::pImpl.
Referenced by llvm::CloneFunctionInto(), hasAddressTakenAndUsed(), LLVMBlockAddress(), llvm::HexagonTargetLowering::LowerBR_JT(), llvm::MapValue(), and llvm::MergeBasicBlockIntoOnlyPred().
BlockAddress * BlockAddress::get (BasicBlock * BB) static
get - Return a BlockAddress for the specified basic block. The basic block must be embedded into a function.
Definition at line 1465 of file Constants.cpp.
References assert(), and llvm::BasicBlock::getParent().
BasicBlock* llvm::BlockAddress::getBasicBlock () const inline
Definition at line 780 of file Constants.h.
Referenced by destroyConstant(), llvm::AsmPrinter::GetBlockAddressSymbol(), replaceUsesOfWithOnConstant(), and SimplifyIndirectBrOnSelect().
Function* llvm::BlockAddress::getFunction () const inline
Definition at line 779 of file Constants.h.
Referenced by destroyConstant(), get(), and replaceUsesOfWithOnConstant().
BlockAddress * BlockAddress::lookup (const BasicBlock * BB) static
Lookup an existing BlockAddress constant for the given BasicBlock.
Returns
0 if !BB->hasAddressTaken(), otherwise the BlockAddress.
Definition at line 1488 of file Constants.cpp.
References assert(), llvm::LLVMContextImpl::BlockAddresses, llvm::Function::getContext(), llvm::BasicBlock::getParent(), llvm::BasicBlock::hasAddressTaken(), and llvm::LLVMContext::pImpl.
void BlockAddress::replaceUsesOfWithOnConstant (Value * , Value * , Use *) override virtual
replaceUsesOfWithOnConstant - This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants. Basically this method goes through the trouble of building a new constant that is equivalent to the current one, with all uses of From replaced with uses of To. After this construction is completed, all of the users of 'this' are replaced to use the new constant, and then 'this' is deleted. In general, you should not call this method, instead, use Value::replaceAllUsesWith, which automatically dispatches to this method as needed.
Reimplemented from llvm::Constant.
Definition at line 1509 of file Constants.cpp.
References llvm::LLVMContextImpl::BlockAddresses, getBasicBlock(), llvm::Value::getContext(), getFunction(), llvm::LLVMContext::pImpl, llvm::Constant::replaceUsesOfWithOnConstantImpl(), llvm::User::setOperand(), and llvm::Value::stripPointerCasts().
The documentation for this class was generated from the following files:
Constants.h
Constants.cpp