LLVM: llvm::yaml::basic_collection_iterator< BaseT, ValueT > Class Template Reference
LLVM API Documentation
llvm::yaml::basic_collection_iterator< BaseT, ValueT > Class Template Reference
This is an iterator abstraction over YAML collections shared by both sequences and maps.
#include <YAMLParser.h>
Public Member Functions
basic_collection_iterator ()
basic_collection_iterator (BaseT *B)
ValueT * operator-> () const
ValueT & operator* () const
operator ValueT * () const
bool operator!= (const basic_collection_iterator &Other) const
basic_collection_iterator & operator++ ()
Detailed Description
template<class BaseT, class ValueT>
class llvm::yaml::basic_collection_iterator< BaseT, ValueT >
This is an iterator abstraction over YAML collections shared by both sequences and maps.
BaseT must have a ValueT* member named CurrentEntry and a member function increment() which must set CurrentEntry to 0 to create an end iterator.
Definition at line 275 of file YAMLParser.h.
Constructor & Destructor Documentation
template<class BaseT , class ValueT > llvm::yaml::basic_collection_iterator< BaseT, ValueT >::basic_collection_iterator () inline
Definition at line 278 of file YAMLParser.h.
template<class BaseT , class ValueT > llvm::yaml::basic_collection_iterator< BaseT, ValueT >::basic_collection_iterator (BaseT * B) inline
Definition at line 279 of file YAMLParser.h.
Member Function Documentation
template<class BaseT , class ValueT > llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator ValueT * () const inline
Definition at line 292 of file YAMLParser.h.
References assert().
template<class BaseT , class ValueT > bool llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator!= (const basic_collection_iterator< BaseT, ValueT > & Other) const inline
Definition at line 297 of file YAMLParser.h.
template<class BaseT , class ValueT > ValueT& llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator* () const inline
Definition at line 286 of file YAMLParser.h.
References assert().
template<class BaseT , class ValueT > basic_collection_iterator& llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator++ () inline
Definition at line 304 of file YAMLParser.h.
References assert().
template<class BaseT , class ValueT > ValueT* llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator-> () const inline
Definition at line 281 of file YAMLParser.h.
References assert().
The documentation for this class was generated from the following file:
YAMLParser.h