LLVM: llvm::PooledStringPtr Class Reference
LLVM API Documentation
llvm::PooledStringPtr Class Reference
#include <StringPool.h>
Public Member Functions
PooledStringPtr ()
PooledStringPtr (entry_t *E)
PooledStringPtr (const PooledStringPtr &That)
PooledStringPtr & operator= (const PooledStringPtr &That)
void clear ()
~PooledStringPtr ()
const char * begin () const
const char * end () const
unsigned size () const
const char * operator* () const
LLVM_EXPLICIT operator bool () const
bool operator== (const PooledStringPtr &That) const
bool operator!= (const PooledStringPtr &That) const
Detailed Description
PooledStringPtr - A pointer to an interned string. Use operator bool to test whether the pointer is valid, and operator * to get the string if so. This is a lightweight value class with storage requirements equivalent to a single pointer, but it does have reference-counting overhead when copied.
Definition at line 80 of file StringPool.h.
Constructor & Destructor Documentation
llvm::PooledStringPtr::PooledStringPtr () inline
Definition at line 85 of file StringPool.h.
llvm::PooledStringPtr::PooledStringPtr (entry_t * E) inline explicit
Definition at line 87 of file StringPool.h.
References llvm::StringMapEntry< ValueTy >::getValue().
llvm::PooledStringPtr::PooledStringPtr (const PooledStringPtr & That) inline
Definition at line 91 of file StringPool.h.
References llvm::StringMapEntry< ValueTy >::getValue().
llvm::PooledStringPtr::~PooledStringPtr () inline
Definition at line 114 of file StringPool.h.
References clear().
Member Function Documentation
const char* llvm::PooledStringPtr::begin () const inline
Definition at line 116 of file StringPool.h.
References assert(), and llvm::StringMapEntry< ValueTy >::getKeyData().
Referenced by operator*().
void llvm::PooledStringPtr::clear () inline
Definition at line 104 of file StringPool.h.
References llvm::StringMapEntry< ValueTy >::Destroy(), and llvm::StringMapEntry< ValueTy >::getValue().
Referenced by operator=(), and ~PooledStringPtr().
const char* llvm::PooledStringPtr::end () const inline
Definition at line 121 of file StringPool.h.
References assert(), llvm::StringMapEntry< ValueTy >::getKeyData(), and llvm::StringMapEntryBase::getKeyLength().
LLVM_EXPLICIT llvm::PooledStringPtr::operator bool () const inline
Definition at line 132 of file StringPool.h.
bool llvm::PooledStringPtr::operator!= (const PooledStringPtr & That) const inline
Definition at line 135 of file StringPool.h.
const char* llvm::PooledStringPtr::operator* () const inline
Definition at line 131 of file StringPool.h.
References begin().
PooledStringPtr& llvm::PooledStringPtr::operator= (const PooledStringPtr & That) inline
Definition at line 95 of file StringPool.h.
References clear(), and llvm::StringMapEntry< ValueTy >::getValue().
bool llvm::PooledStringPtr::operator== (const PooledStringPtr & That) const inline
Definition at line 134 of file StringPool.h.
unsigned llvm::PooledStringPtr::size () const inline
Definition at line 126 of file StringPool.h.
References assert(), and llvm::StringMapEntryBase::getKeyLength().
The documentation for this class was generated from the following file:
StringPool.h