LLVM: llvm::DIRef< T > Class Template Reference
LLVM API Documentation
llvm::DIRef< T > Class Template Reference
Represents reference to a DIDescriptor.
#include <DebugInfo.h>
Public Member Functions
T resolve (const DITypeIdentifierMap &Map) const
StringRef getName () const
operator Metadata * () const
Friends
class DIType
template<typename DescTy >
DescTy DIDescriptor::getFieldAs (unsigned Elt) const
DIScopeRef DIScope::getContext () const
DIScopeRef DIScope::getRef () const
Detailed Description
template<typename T>
class llvm::DIRef< T >
Represents reference to a DIDescriptor.
Abstracts over direct and identifier-based metadata references.
Definition at line 285 of file DebugInfo.h.
Member Function Documentation
template<typename T > StringRef llvm::DIRef< T >::getName () const
Definition at line 364 of file DebugInfo.h.
References llvm::MDString::getString(), and T.
template<typename T> llvm::DIRef< T >::operator Metadata * () const inline
Definition at line 344 of file DebugInfo.h.
template<typename T > T llvm::DIRef< T >::resolve (const DITypeIdentifierMap & Map) const
Definition at line 348 of file DebugInfo.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::DIDescriptor::isType(), and T.
Referenced by llvm::DIBuilder::createFunction(), llvm::DIVariable::getSizeInBits(), llvm::DbgVariable::getType(), llvm::DebugInfoFinder::processModule(), and llvm::DwarfDebug::resolve().
Friends And Related Function Documentation
template<typename T> template<typename DescTy > DescTy DIDescriptor::getFieldAs (unsigned Elt) const friend
template<typename T> DIScopeRef DIScope::getContext () const friend
template<typename T> DIScopeRef DIScope::getRef () const friend
template<typename T> friend class DIType friend
Definition at line 333 of file DebugInfo.h.
The documentation for this class was generated from the following file:
DebugInfo.h