LLVM: llvm::Win64EH::UnwindEmitter Class Reference
LLVM API Documentation
llvm::Win64EH::UnwindEmitter Class Reference
#include <MCWin64EH.h>
Public Member Functions
void Emit (MCStreamer &Streamer) const override
void EmitUnwindInfo (MCStreamer &Streamer, WinEH::FrameInfo *FI) const override
Public Member Functions inherited from llvm::WinEH::UnwindEmitter
virtual ~UnwindEmitter ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::WinEH::UnwindEmitter
static const MCSection * getPDataSection (const MCSymbol *Function, MCContext &Context)
static const MCSection * getXDataSection (const MCSymbol *Function, MCContext &Context)
Detailed Description
Definition at line 55 of file MCWin64EH.h.
Member Function Documentation
void llvm::Win64EH::UnwindEmitter::Emit (MCStreamer & Streamer) const override virtual
Implements llvm::WinEH::UnwindEmitter.
Definition at line 222 of file MCWin64EH.cpp.
References llvm::EmitRuntimeFunction(), EmitUnwindInfo(), llvm::MCStreamer::getContext(), llvm::WinEH::UnwindEmitter::getPDataSection(), llvm::MCStreamer::getWinFrameInfos(), llvm::WinEH::UnwindEmitter::getXDataSection(), and llvm::MCStreamer::SwitchSection().
void llvm::Win64EH::UnwindEmitter::EmitUnwindInfo (MCStreamer & Streamer, WinEH::FrameInfo * FI) const override virtual
Implements llvm::WinEH::UnwindEmitter.
Definition at line 242 of file MCWin64EH.cpp.
References llvm::EmitUnwindInfo(), llvm::WinEH::FrameInfo::Function, llvm::MCStreamer::getContext(), llvm::WinEH::UnwindEmitter::getXDataSection(), and llvm::MCStreamer::SwitchSection().
Referenced by Emit().
The documentation for this class was generated from the following files:
MCWin64EH.h
MCWin64EH.cpp