LLVM: llvm::DIScope Class Reference
LLVM API Documentation
llvm::DIScope Class Reference
A base class for various scopes.
#include <DebugInfo.h>
Public Member Functions
DIScope (const MDNode *N=nullptr)
DIScopeRef getContext () const
Get the parent scope.
StringRef getName () const
Get the scope name.
StringRef getFilename () const
StringRef getDirectory () const
DIScopeRef getRef () const
Generate a reference to this DIScope.
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T >
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Protected Member Functions
void printInternal (raw_ostream &OS) const
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy >
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Friends
class DIDescriptor
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagAccessibility = 1 << 0 | 1 << 1, FlagPrivate = 1, FlagProtected = 2, FlagPublic = 3,
FlagFwdDecl = 1 << 2, FlagAppleBlock = 1 << 3, FlagBlockByrefStruct = 1 << 4, FlagVirtual = 1 << 5,
FlagArtificial = 1 << 6, FlagExplicit = 1 << 7, FlagPrototyped = 1 << 8, FlagObjcClassComplete = 1 << 9,
FlagObjectPointer = 1 << 10, FlagVector = 1 << 11, FlagStaticMember = 1 << 12, FlagIndirectVariable = 1 << 13,
FlagLValueReference = 1 << 14, FlagRValueReference = 1 << 15
}
Accessibility flags.
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
A base class for various scopes.
Although, implementation-wise, DIScope is the parent class of most other DIxxx classes, including DIType and its descendants, most of DIScope's descendants are not a substitutable subtype of DIScope. The DIDescriptor::isScope() method only is true for DIScopes that are scopes in the strict lexical scope sense (DICompileUnit, DISubprogram, etc.), but not for, e.g., a DIType.
Definition at line 298 of file DebugInfo.h.
Constructor & Destructor Documentation
llvm::DIScope::DIScope (const MDNode * N = nullptr) inline explicit
Definition at line 304 of file DebugInfo.h.
Member Function Documentation
DIScopeRef DIScope::getContext () const
Get the parent scope.
Gets the parent scope for this scope node or returns a default constructed scope.
Definition at line 734 of file DebugInfo.cpp.
References assert(), llvm::DIType::getContext(), and llvm::dwarf::isType().
Referenced by AddOperand(), and llvm::DwarfUnit::getParentContextString().
StringRef DIScope::getDirectory () const
Definition at line 774 of file DebugInfo.cpp.
References getNodeField(), and getStringField().
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DILocation::getDirectory(), and llvm::jitprofiling::FilenameCache::getFullPath().
StringRef DIScope::getFilename () const
Definition at line 768 of file DebugInfo.cpp.
References getNodeField(), and getStringField().
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::jitprofiling::FilenameCache::getFilename(), llvm::DILocation::getFilename(), llvm::jitprofiling::FilenameCache::getFullPath(), llvm::DebugLoc::print(), and printDebugLoc().
StringRef DIScope::getName () const
Get the scope name.
If the scope node has a name, return that, else return an empty string.
Definition at line 755 of file DebugInfo.cpp.
References assert(), llvm::DIType::getName(), llvm::DISubprogram::getName(), llvm::DINameSpace::getName(), and llvm::dwarf::isType().
Referenced by llvm::DwarfUnit::getParentContextString().
DIScopeRef DIScope::getRef () const
Generate a reference to this DIScope.
Uses the type identifier instead of the actual MDNode if possible, to help type uniquing.
Definition at line 686 of file DebugInfo.cpp.
References llvm::DICompositeType::getIdentifier().
Referenced by llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createFriend(), createFunctionHelper(), llvm::DIBuilder::createImportedDeclaration(), llvm::DIBuilder::createInheritance(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createPointerType(), llvm::DIBuilder::createQualifiedType(), llvm::DIBuilder::createReferenceType(), llvm::DIBuilder::createReplaceableForwardDecl(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createVectorType(), llvm::DwarfUnit::getOrCreateTypeDIE(), and llvm::DIType::operator DITypeRef().
void DIScope::printInternal (raw_ostream & OS) const protected
Definition at line 1238 of file DebugInfo.cpp.
Referenced by llvm::DIDescriptor::print().
Friends And Related Function Documentation
friend class DIDescriptor friend
Definition at line 300 of file DebugInfo.h.
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp