LLVM: llvm::StringTableBuilder Class Reference
LLVM API Documentation
llvm::StringTableBuilder Class Reference
Utility for building string tables with deduplicated suffixes.
#include <StringTableBuilder.h>
Public Types
enum Kind { ELF, WinCOFF, MachO }
Public Member Functions
StringRef add (StringRef s)
Add a string to the builder. Returns a StringRef to the internal copy of s. Can only be used before the table is finalized.
void finalize (Kind kind)
Analyze the strings and build the final table. No more strings can be added after this point.
StringRef data ()
Retrieve the string table data. Can only be used after the table is finalized.
size_t getOffset (StringRef s)
Get the offest of a string in the string table. Can only be used after the table is finalized.
void clear ()
Detailed Description
Utility for building string tables with deduplicated suffixes.
Definition at line 20 of file StringTableBuilder.h.
Member Enumeration Documentation
enum llvm::StringTableBuilder::Kind
Enumerator
ELF
WinCOFF
MachO
Definition at line 32 of file StringTableBuilder.h.
Member Function Documentation
StringRef llvm::StringTableBuilder::add (StringRef s) inline
Add a string to the builder. Returns a StringRef to the internal copy of s. Can only be used before the table is finalized.
Definition at line 27 of file StringTableBuilder.h.
References assert(), and llvm::StringMap< ValueTy, AllocatorTy >::insert().
Referenced by llvm::MachObjectWriter::ComputeSymbolTable().
void StringTableBuilder::clear ()
Definition at line 85 of file StringTableBuilder.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::clear(), and llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::MachObjectWriter::reset().
StringRef llvm::StringTableBuilder::data () inline
Retrieve the string table data. Can only be used after the table is finalized.
Definition at line 44 of file StringTableBuilder.h.
References assert().
Referenced by llvm::MachObjectWriter::WriteObject().
void StringTableBuilder::finalize (Kind kind)
Analyze the strings and build the final table. No more strings can be added after this point.
Definition at line 30 of file StringTableBuilder.cpp.
References llvm::SmallString< InternalLen >::append(), assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::StringMap< ValueTy, AllocatorTy >::begin(), compareBySuffix(), llvm::SmallVectorTemplateCommon< T, typename >::data(), ELF, llvm::SmallVectorTemplateCommon< T >::end(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringRef::endswith(), MachO, llvm::COFF::NameSize, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::StringMapImpl::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and WinCOFF.
Referenced by llvm::MachObjectWriter::ComputeSymbolTable().
size_t llvm::StringTableBuilder::getOffset (StringRef s) inline
Get the offest of a string in the string table. Can only be used after the table is finalized.
Definition at line 51 of file StringTableBuilder.h.
References assert(), and llvm::StringMap< ValueTy, AllocatorTy >::count().
Referenced by llvm::MachObjectWriter::ComputeSymbolTable().
The documentation for this class was generated from the following files:
StringTableBuilder.h
StringTableBuilder.cpp