LLVM: llvm::NVPTXTargetMachine Class Reference
LLVM API Documentation
llvm::NVPTXTargetMachine Class Reference
#include <NVPTXTargetMachine.h>
Public Member Functions
NVPTXTargetMachine (const Target &T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OP, bool is64bit)
~NVPTXTargetMachine () override
const NVPTXSubtarget * getSubtargetImpl () const override
ManagedStringPool * getManagedStrPool () const
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
bool addPassesToEmitMC (PassManagerBase &, MCContext *&, raw_ostream &, bool=true) override
TargetLoweringObjectFile * getObjFileLowering () const override
void addAnalysisPasses (PassManagerBase &PM) override
Register NVPTX analysis passes with a pass manager.
Public Member Functions inherited from llvm::LLVMTargetMachine
bool addPassesToEmitFile (PassManagerBase &PM, formatted_raw_ostream &Out, CodeGenFileType FileType, bool DisableVerify=true, AnalysisID StartAfter=nullptr, AnalysisID StopAfter=nullptr) override
Public Member Functions inherited from llvm::TargetMachine
virtual ~TargetMachine ()
const Target & getTarget () const
StringRef getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
virtual const TargetSubtargetInfo * getSubtargetImpl (const Function &) const
template<typename STC >
const STC & getSubtarget () const
template<typename STC >
const STC & getSubtarget (const Function *) const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
bool getAsmVerbosityDefault () const
void setAsmVerbosityDefault (bool)
bool getDataSections () const
bool getFunctionSections () const
void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
void setFunctionSections (bool)
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV, Mangler &Mang) const
Additional Inherited Members
Public Types inherited from llvm::TargetMachine
enum CodeGenFileType { CGFT_AssemblyFile, CGFT_ObjectFile, CGFT_Null }
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned RequireStructuredCFG: 1
Detailed Description
NVPTXTargetMachine
Definition at line 27 of file NVPTXTargetMachine.h.
Constructor & Destructor Documentation
NVPTXTargetMachine::NVPTXTargetMachine (const Target & T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OP, bool is64bit)
Definition at line 72 of file NVPTXTargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo().
NVPTXTargetMachine::~NVPTXTargetMachine () override
Definition at line 83 of file NVPTXTargetMachine.cpp.
Member Function Documentation
void NVPTXTargetMachine::addAnalysisPasses (PassManagerBase & PM) override virtual
Register NVPTX analysis passes with a pass manager.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 127 of file NVPTXTargetMachine.cpp.
References llvm::createBasicTargetTransformInfoPass(), and llvm::createNVPTXTargetTransformInfoPass().
bool llvm::NVPTXTargetMachine::addPassesToEmitMC (PassManagerBase & PM, MCContext *& Ctx, raw_ostream & Out, bool DisableVerify = true) inline override virtual
addPassesToEmitMC - Add passes to the specified pass manager to get machine code emitted with the MCJIT. This method returns true if machine code is not supported. It fills the MCContext Ctx pointer which can be used to build custom MCStreamer.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 50 of file NVPTXTargetMachine.h.
TargetPassConfig * NVPTXTargetMachine::createPassConfig (PassManagerBase & PM) override virtual
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 122 of file NVPTXTargetMachine.cpp.
ManagedStringPool* llvm::NVPTXTargetMachine::getManagedStrPool () const inline
Definition at line 43 of file NVPTXTargetMachine.h.
Referenced by llvm::NVPTXTargetLowering::LowerCall().
TargetLoweringObjectFile* llvm::NVPTXTargetMachine::getObjFileLowering () const inline override virtual
Reimplemented from llvm::TargetMachine.
Definition at line 54 of file NVPTXTargetMachine.h.
const NVPTXSubtarget* llvm::NVPTXTargetMachine::getSubtargetImpl () const inline override virtual
getSubtargetImpl - virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 41 of file NVPTXTargetMachine.h.
Referenced by llvm::NVPTXTargetLowering::LowerCall().
The documentation for this class was generated from the following files:
NVPTXTargetMachine.h
NVPTXTargetMachine.cpp