LLVM: llvm::DebugLocDwarfExpression Class Reference
LLVM API Documentation
llvm::DebugLocDwarfExpression Class Reference
DwarfExpression implementation for .debug_loc entries.
#include <DwarfExpression.h>
Public Member Functions
DebugLocDwarfExpression (const AsmPrinter &AP, ByteStreamer &BS)
void EmitOp (uint8_t Op, const char *Comment=nullptr) override
Output a dwarf operand and an optional assembler comment.
void EmitSigned (int Value) override
Emit a raw signed value.
void EmitUnsigned (unsigned Value) override
Emit a raw unsigned value.
bool isFrameRegister (unsigned MachineReg) override
Public Member Functions inherited from llvm::DwarfExpression
DwarfExpression (const AsmPrinter &AP)
virtual ~DwarfExpression ()
void AddReg (int DwarfReg, const char *Comment=nullptr)
Emit a dwarf register operation.
void AddRegIndirect (int DwarfReg, int Offset, bool Deref=false)
Emit an (double-)indirect dwarf register operation.
void AddOpPiece (unsigned SizeInBits, unsigned OffsetInBits=0)
void AddShr (unsigned ShiftBy)
Emit a shift-right dwarf expression.
bool AddMachineRegIndirect (unsigned MachineReg, int Offset=0)
bool AddMachineRegPiece (unsigned MachineReg, unsigned PieceSizeInBits=0, unsigned PieceOffsetInBits=0)
Emit a partial DWARF register operation.
void AddSignedConstant (int Value)
Emit a signed constant.
void AddUnsignedConstant (unsigned Value)
Emit an unsigned constant.
bool AddMachineRegExpression (DIExpression Expr, unsigned MachineReg, unsigned PieceOffsetInBits=0)
void AddExpression (DIExpression Expr, unsigned PieceOffsetInBits=0, unsigned I=0)
Additional Inherited Members
Protected Member Functions inherited from llvm::DwarfExpression
const TargetRegisterInfo * getTRI () const
unsigned getDwarfVersion () const
Protected Attributes inherited from llvm::DwarfExpression
const AsmPrinter & AP
Detailed Description
DwarfExpression implementation for .debug_loc entries.
Definition at line 104 of file DwarfExpression.h.
Constructor & Destructor Documentation
llvm::DebugLocDwarfExpression::DebugLocDwarfExpression (const AsmPrinter & AP, ByteStreamer & BS) inline
Definition at line 108 of file DwarfExpression.h.
Member Function Documentation
void DebugLocDwarfExpression::EmitOp (uint8_t Op, const char * Comment = nullptr) override virtual
Output a dwarf operand and an optional assembler comment.
Implements llvm::DwarfExpression.
Definition at line 35 of file AsmPrinterDwarf.cpp.
References llvm::ByteStreamer::EmitInt8(), and llvm::dwarf::OperationEncodingString().
Referenced by llvm::DwarfDebug::emitDebugLocValue(), and llvm::AsmPrinter::EmitDwarfRegOp().
void DebugLocDwarfExpression::EmitSigned (int Value) override virtual
Emit a raw signed value.
Implements llvm::DwarfExpression.
Definition at line 41 of file AsmPrinterDwarf.cpp.
References llvm::ByteStreamer::EmitSLEB128().
void DebugLocDwarfExpression::EmitUnsigned (unsigned Value) override virtual
Emit a raw unsigned value.
Implements llvm::DwarfExpression.
Definition at line 45 of file AsmPrinterDwarf.cpp.
References llvm::ByteStreamer::EmitULEB128().
bool DebugLocDwarfExpression::isFrameRegister (unsigned MachineReg) override virtual
Return whether the given machine register is the frame register in the current function.
Implements llvm::DwarfExpression.
Definition at line 49 of file AsmPrinterDwarf.cpp.
The documentation for this class was generated from the following files:
DwarfExpression.h
AsmPrinterDwarf.cpp