LLVM: llvm::MachineBlockFrequencyInfo Class Reference
LLVM API Documentation
llvm::MachineBlockFrequencyInfo Class Reference
#include <MachineBlockFrequencyInfo.h>
Public Member Functions
MachineBlockFrequencyInfo ()
~MachineBlockFrequencyInfo ()
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnMachineFunction (MachineFunction &F) override
void releaseMemory () override
BlockFrequency getBlockFreq (const MachineBasicBlock *MBB) const
const MachineFunction * getFunction () const
void view () const
raw_ostream & printBlockFreq (raw_ostream &OS, const BlockFrequency Freq) const
raw_ostream & printBlockFreq (raw_ostream &OS, const MachineBasicBlock *MBB) const
uint64_t getEntryFreq () const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
MachineBlockFrequencyInfo pass uses BlockFrequencyInfoImpl implementation to estimate machine basic block frequencies.
Definition at line 29 of file MachineBlockFrequencyInfo.h.
Constructor & Destructor Documentation
MachineBlockFrequencyInfo::MachineBlockFrequencyInfo ()
Definition at line 127 of file MachineBlockFrequencyInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineBlockFrequencyInfoPass().
MachineBlockFrequencyInfo::~MachineBlockFrequencyInfo ()
Definition at line 131 of file MachineBlockFrequencyInfo.cpp.
Member Function Documentation
void MachineBlockFrequencyInfo::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 133 of file MachineBlockFrequencyInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
BlockFrequency MachineBlockFrequencyInfo::getBlockFreq (const MachineBasicBlock * MBB) const
getblockFreq - Return block frequency. Return 0 if we don't have the information. Please note that initial frequency is equal to 1024. It means that we should not rely on the value itself, but only on the comparison to the other block frequencies. We do this to avoid using of floating points.
Definition at line 171 of file MachineBlockFrequencyInfo.cpp.
Referenced by llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeLabel(), and llvm::LiveIntervals::getSpillWeight().
uint64_t MachineBlockFrequencyInfo::getEntryFreq () const
Definition at line 191 of file MachineBlockFrequencyInfo.cpp.
Referenced by llvm::LiveIntervals::getSpillWeight().
const MachineFunction * MachineBlockFrequencyInfo::getFunction () const
Definition at line 175 of file MachineBlockFrequencyInfo.cpp.
Referenced by llvm::GraphTraits< MachineBlockFrequencyInfo * >::getEntryNode(), llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getGraphName(), llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_begin(), and llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_end().
raw_ostream & MachineBlockFrequencyInfo::printBlockFreq (raw_ostream & OS, const BlockFrequency Freq) const
Definition at line 180 of file MachineBlockFrequencyInfo.cpp.
Referenced by llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeLabel().
raw_ostream & MachineBlockFrequencyInfo::printBlockFreq (raw_ostream & OS, const MachineBasicBlock * MBB) const
Definition at line 186 of file MachineBlockFrequencyInfo.cpp.
void MachineBlockFrequencyInfo::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 155 of file MachineBlockFrequencyInfo.cpp.
bool MachineBlockFrequencyInfo::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 140 of file MachineBlockFrequencyInfo.cpp.
References GVDT_None, view(), and ViewMachineBlockFreqPropagationDAG.
void MachineBlockFrequencyInfo::view () const
Pop up a ghostview window with the current block frequency propagation rendered using dot.
Definition at line 159 of file MachineBlockFrequencyInfo.cpp.
References llvm::errs(), and llvm::ViewGraph().
Referenced by runOnMachineFunction().
Member Data Documentation
machine block Machine Block Frequency true char MachineBlockFrequencyInfo::ID = 0 static
Definition at line 34 of file MachineBlockFrequencyInfo.h.
The documentation for this class was generated from the following files:
MachineBlockFrequencyInfo.h
MachineBlockFrequencyInfo.cpp