LLVM: llvm::ValueMapIterator< DenseMapT, KeyT > Class Template Reference
LLVM API Documentation
llvm::ValueMapIterator< DenseMapT, KeyT > Class Template Reference
#include <ValueMap.h>
Classes
struct ValueTypeProxy
Public Member Functions
ValueMapIterator ()
ValueMapIterator (BaseT I)
BaseT base () const
ValueTypeProxy operator* () const
ValueTypeProxy operator-> () const
bool operator== (const ValueMapIterator &RHS) const
bool operator!= (const ValueMapIterator &RHS) const
ValueMapIterator & operator++ ()
ValueMapIterator operator++ (int)
Detailed Description
template<typename DenseMapT, typename KeyT>
class llvm::ValueMapIterator< DenseMapT, KeyT >
Definition at line 44 of file ValueMap.h.
Constructor & Destructor Documentation
template<typename DenseMapT , typename KeyT > llvm::ValueMapIterator< DenseMapT, KeyT >::ValueMapIterator () inline
Definition at line 303 of file ValueMap.h.
template<typename DenseMapT , typename KeyT > llvm::ValueMapIterator< DenseMapT, KeyT >::ValueMapIterator (BaseT I) inline
Definition at line 305 of file ValueMap.h.
Member Function Documentation
template<typename DenseMapT , typename KeyT > BaseT llvm::ValueMapIterator< DenseMapT, KeyT >::base () const inline
Definition at line 307 of file ValueMap.h.
Referenced by llvm::ValueMap< const GlobalValue *, void *, AddressMapConfig >::erase().
template<typename DenseMapT , typename KeyT > bool llvm::ValueMapIterator< DenseMapT, KeyT >::operator!= (const ValueMapIterator< DenseMapT, KeyT > & RHS) const inline
Definition at line 330 of file ValueMap.h.
template<typename DenseMapT , typename KeyT > ValueTypeProxy llvm::ValueMapIterator< DenseMapT, KeyT >::operator* () const inline
Definition at line 318 of file ValueMap.h.
Referenced by llvm::ValueMapIterator< DenseMapT, KeyT >::operator->().
template<typename DenseMapT , typename KeyT > ValueMapIterator& llvm::ValueMapIterator< DenseMapT, KeyT >::operator++ () inline
Definition at line 334 of file ValueMap.h.
template<typename DenseMapT , typename KeyT > ValueMapIterator llvm::ValueMapIterator< DenseMapT, KeyT >::operator++ (int) inline
Definition at line 338 of file ValueMap.h.
template<typename DenseMapT , typename KeyT > ValueTypeProxy llvm::ValueMapIterator< DenseMapT, KeyT >::operator-> () const inline
Definition at line 323 of file ValueMap.h.
References llvm::ValueMapIterator< DenseMapT, KeyT >::operator*().
template<typename DenseMapT , typename KeyT > bool llvm::ValueMapIterator< DenseMapT, KeyT >::operator== (const ValueMapIterator< DenseMapT, KeyT > & RHS) const inline
Definition at line 327 of file ValueMap.h.
The documentation for this class was generated from the following file:
ValueMap.h