LLVM: llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT > Class Template Reference
LLVM API Documentation
llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT > Class Template Reference
Iterate over constant sized entities.
#include <ELF.h>
Public Types
typedef ptrdiff_t difference_type
typedef EntT value_type
typedef std::forward_iterator_tag iterator_category
typedef value_type & reference
typedef value_type * pointer
Public Member Functions
ELFEntityIterator ()
Default construct iterator.
ELFEntityIterator (uintX_t EntSize, const char *Start)
reference operator* ()
pointer operator-> ()
bool operator== (const ELFEntityIterator &Other)
bool operator!= (const ELFEntityIterator &Other)
ELFEntityIterator & operator++ ()
ELFEntityIterator operator++ (int)
ELFEntityIterator & operator= (const ELFEntityIterator &Other)
difference_type operator- (const ELFEntityIterator &Other) const
const char * get () const
uintX_t getEntSize () const
Detailed Description
template<class ELFT>
template<class EntT>
class llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >
Iterate over constant sized entities.
Definition at line 60 of file Object/ELF.h.
Member Typedef Documentation
template<class ELFT> template<class EntT > typedef ptrdiff_t llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::difference_type
Definition at line 62 of file Object/ELF.h.
template<class ELFT> template<class EntT > typedef std::forward_iterator_tag llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::iterator_category
Definition at line 64 of file Object/ELF.h.
template<class ELFT> template<class EntT > typedef value_type* llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::pointer
Definition at line 66 of file Object/ELF.h.
template<class ELFT> template<class EntT > typedef value_type& llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::reference
Definition at line 65 of file Object/ELF.h.
template<class ELFT> template<class EntT > typedef EntT llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::value_type
Definition at line 63 of file Object/ELF.h.
Constructor & Destructor Documentation
template<class ELFT> template<class EntT > llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::ELFEntityIterator () inline
Default construct iterator.
Definition at line 69 of file Object/ELF.h.
template<class ELFT> template<class EntT > llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::ELFEntityIterator (uintX_t EntSize, const char * Start) inline
Definition at line 70 of file Object/ELF.h.
Member Function Documentation
template<class ELFT> template<class EntT > const char* llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::get () const inline
Definition at line 115 of file Object/ELF.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::toDRI().
template<class ELFT> template<class EntT > uintX_t llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::getEntSize () const inline
Definition at line 117 of file Object/ELF.h.
template<class ELFT> template<class EntT > bool llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator!= (const ELFEntityIterator< EntT > & Other) inline
Definition at line 87 of file Object/ELF.h.
References Other.
template<class ELFT> template<class EntT > reference llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator* () inline
Definition at line 73 of file Object/ELF.h.
References assert().
template<class ELFT> template<class EntT > ELFEntityIterator& llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator++ () inline
Definition at line 91 of file Object/ELF.h.
References assert().
template<class ELFT> template<class EntT > ELFEntityIterator llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator++ (int) inline
Definition at line 97 of file Object/ELF.h.
template<class ELFT> template<class EntT > difference_type llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator- (const ELFEntityIterator< EntT > & Other) const inline
Definition at line 109 of file Object/ELF.h.
References assert().
template<class ELFT> template<class EntT > pointer llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator-> () inline
Definition at line 78 of file Object/ELF.h.
References assert().
template<class ELFT> template<class EntT > ELFEntityIterator& llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator= (const ELFEntityIterator< EntT > & Other) inline
Definition at line 103 of file Object/ELF.h.
template<class ELFT> template<class EntT > bool llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator== (const ELFEntityIterator< EntT > & Other) inline
Definition at line 83 of file Object/ELF.h.
The documentation for this class was generated from the following file:
Object/ELF.h