LLVM: llvm::MCContext Class Reference
LLVM API Documentation
llvm::MCContext Class Reference
#include <MCContext.h>
Public Types
typedef StringMap< MCSymbol
*, BumpPtrAllocator & > SymbolTable
Public Member Functions
MCContext (const MCAsmInfo *MAI, const MCRegisterInfo *MRI, const MCObjectFileInfo *MOFI, const SourceMgr *Mgr=nullptr, bool DoAutoReset=true)
~MCContext ()
const SourceMgr * getSourceManager () const
const MCAsmInfo * getAsmInfo () const
const MCRegisterInfo * getRegisterInfo () const
const MCObjectFileInfo * getObjectFileInfo () const
void setAllowTemporaryLabels (bool Value)
char * getSecureLogFile ()
raw_ostream * getSecureLog ()
bool getSecureLogUsed ()
void setSecureLog (raw_ostream *Value)
void setSecureLogUsed (bool Value)
void * Allocate (unsigned Size, unsigned Align=8)
void Deallocate (void *Ptr)
LLVM_ATTRIBUTE_NORETURN void FatalError (SMLoc L, const Twine &Msg) const
Module Lifetime Management
void reset ()
Symbol Management
MCSymbol * CreateLinkerPrivateTempSymbol ()
MCSymbol * CreateTempSymbol ()
unsigned getUniqueSymbolID ()
MCSymbol * CreateDirectionalLocalSymbol (unsigned LocalLabelVal)
MCSymbol * GetDirectionalLocalSymbol (unsigned LocalLabelVal, bool Before)
MCSymbol * GetOrCreateSymbol (StringRef Name)
MCSymbol * GetOrCreateSymbol (const Twine &Name)
MCSymbol * getOrCreateSectionSymbol (const MCSectionELF &Section)
MCSymbol * getOrCreateFrameAllocSymbol (StringRef FuncName)
MCSymbol * LookupSymbol (StringRef Name) const
LookupSymbol - Get the symbol for Name, or null.
MCSymbol * LookupSymbol (const Twine &Name) const
const SymbolTable & getSymbols () const
Section Management
const MCSectionMachO * getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, unsigned Reserved2, SectionKind K)
const MCSectionMachO * getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, SectionKind K)
const MCSectionELF * getELFSection (StringRef Section, unsigned Type, unsigned Flags, SectionKind Kind)
const MCSectionELF * getELFSection (StringRef Section, unsigned Type, unsigned Flags, SectionKind Kind, unsigned EntrySize, StringRef Group)
void renameELFSection (const MCSectionELF *Section, StringRef Name)
const MCSectionELF * CreateELFGroupSection ()
const MCSectionCOFF * getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, StringRef COMDATSymName, int Selection)
const MCSectionCOFF * getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind)
const MCSectionCOFF * getCOFFSection (StringRef Section)
const MCSectionCOFF * getAssociativeCOFFSection (const MCSectionCOFF *Sec, const MCSymbol *KeySym)
Dwarf Management
StringRef getCompilationDir () const
Get the compilation directory for DW_AT_comp_dir This can be overridden by clients which want to control the reported compilation directory and have it be something other than the current working directory. Returns an empty string if the current directory cannot be determined.
void setCompilationDir (StringRef S)
Set the compilation directory for DW_AT_comp_dir Override the default (CWD) compilation directory.
const std::string & getMainFileName () const
Get the main file name for use in error messages and debug info. This can be set to ensure we've got the correct file name after preprocessing or for -save-temps.
void setMainFileName (StringRef S)
Set the main file name and override the default.
unsigned GetDwarfFile (StringRef Directory, StringRef FileName, unsigned FileNumber, unsigned CUID)
GetDwarfFile - creates an entry in the dwarf file and directory tables.
bool isValidDwarfFileNumber (unsigned FileNumber, unsigned CUID=0)
const std::map< unsigned,
MCDwarfLineTable > & getMCDwarfLineTables () const
MCDwarfLineTable & getMCDwarfLineTable (unsigned CUID)
const MCDwarfLineTable & getMCDwarfLineTable (unsigned CUID) const
const SmallVectorImpl
< MCDwarfFile > & getMCDwarfFiles (unsigned CUID=0)
const SmallVectorImpl
< std::string > & getMCDwarfDirs (unsigned CUID=0)
bool hasMCLineSections () const
unsigned getDwarfCompileUnitID ()
void setDwarfCompileUnitID (unsigned CUIndex)
void setMCLineTableCompilationDir (unsigned CUID, StringRef CompilationDir)
void setCurrentDwarfLoc (unsigned FileNum, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator)
void ClearDwarfLocSeen ()
bool getDwarfLocSeen ()
const MCDwarfLoc & getCurrentDwarfLoc ()
bool getGenDwarfForAssembly ()
void setGenDwarfForAssembly (bool Value)
unsigned getGenDwarfFileNumber ()
void setGenDwarfFileNumber (unsigned FileNumber)
MapVector< const MCSection
*, std::pair< MCSymbol
*, MCSymbol * > > & getGenDwarfSectionSyms ()
std::pair< MapVector< const
MCSection *, std::pair
< MCSymbol *, MCSymbol * >
>::iterator, bool > addGenDwarfSection (const MCSection *Sec)
void finalizeDwarfSections (MCStreamer &MCOS)
const std::vector
< MCGenDwarfLabelEntry > & getMCGenDwarfLabelEntries () const
void addMCGenDwarfLabelEntry (const MCGenDwarfLabelEntry &E)
void setDwarfDebugFlags (StringRef S)
StringRef getDwarfDebugFlags ()
void setDwarfDebugProducer (StringRef S)
StringRef getDwarfDebugProducer ()
void setDwarfVersion (uint16_t v)
uint16_t getDwarfVersion () const
Detailed Description
MCContext - Context object for machine code objects. This class owns all of the sections that it creates.
Definition at line 49 of file MCContext.h.
Member Typedef Documentation
typedef StringMap<MCSymbol*, BumpPtrAllocator&> llvm::MCContext::SymbolTable
Definition at line 53 of file MCContext.h.
Constructor & Destructor Documentation
MCContext::MCContext (const MCAsmInfo * MAI, const MCRegisterInfo * MRI, const MCObjectFileInfo * MOFI, const SourceMgr * Mgr = nullptr, bool DoAutoReset = true) explicit
Definition at line 32 of file MCContext.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::sys::fs::current_path(), llvm::LibFunc::getenv, llvm::SourceMgr::getMainFileID(), llvm::SourceMgr::getMemoryBuffer(), and llvm::SourceMgr::getNumBuffers().
MCContext::~MCContext ()
Definition at line 55 of file MCContext.cpp.
References reset().
Member Function Documentation
std::pair<MapVector<const MCSection *, std::pair<MCSymbol *, MCSymbol *> >::iterator, bool> llvm::MCContext::addGenDwarfSection (const MCSection * Sec) inline
Definition at line 402 of file MCContext.h.
void llvm::MCContext::addMCGenDwarfLabelEntry (const MCGenDwarfLabelEntry & E) inline
Definition at line 410 of file MCContext.h.
Referenced by llvm::MCGenDwarfLabelEntry::Make().
void* llvm::MCContext::Allocate (unsigned Size, unsigned Align = 8) inline
Definition at line 435 of file MCContext.h.
References Align(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate().
void llvm::MCContext::ClearDwarfLocSeen () inline
Definition at line 384 of file MCContext.h.
Referenced by llvm::MCLineEntry::Make().
MCSymbol * MCContext::CreateDirectionalLocalSymbol (unsigned LocalLabelVal)
Create the definition of a directional local symbol for numbered label (used for "1:" definitions).
Definition at line 204 of file MCContext.cpp.
const MCSectionELF * MCContext::CreateELFGroupSection ()
Definition at line 299 of file MCContext.cpp.
References llvm::SectionKind::getReadOnly(), and llvm::ELF::SHT_GROUP.
MCSymbol * MCContext::CreateLinkerPrivateTempSymbol ()
CreateLinkerPrivateTempSymbol - Create and return a new linker temporary symbol with a unique but unspecified name.
Definition at line 168 of file MCContext.cpp.
References llvm::MCAsmInfo::getLinkerPrivateGlobalPrefix().
MCSymbol * MCContext::CreateTempSymbol ()
CreateTempSymbol - Create and return a new assembler temporary symbol with a unique but unspecified name.
Definition at line 175 of file MCContext.cpp.
References llvm::MCAsmInfo::getPrivateGlobalPrefix().
Referenced by llvm::ConstantPool::addEntry(), llvm::MachineModuleInfo::addLandingPad(), llvm::DwarfCFIException::beginFunction(), llvm::DwarfDebug::beginInstruction(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), EmitDwarfLineTable(), llvm::AsmPrinter::EmitFunctionBody(), EmitGenDwarfInfo(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), emitLabelOffsetDifference(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::EmitUnwindInfo(), llvm::MCObjectStreamer::EmitValueToOffset(), llvm::MCStreamer::EmitWinCFIAllocStack(), llvm::MCStreamer::EmitWinCFIEndChained(), llvm::MCStreamer::EmitWinCFIEndProc(), llvm::MCStreamer::EmitWinCFIEndProlog(), llvm::MCStreamer::EmitWinCFIPushFrame(), llvm::MCStreamer::EmitWinCFIPushReg(), llvm::MCStreamer::EmitWinCFISaveReg(), llvm::MCStreamer::EmitWinCFISaveXMM(), llvm::MCStreamer::EmitWinCFISetFrame(), llvm::MCStreamer::EmitWinCFIStartChained(), llvm::MCStreamer::EmitWinCFIStartProc(), llvm::WinCodeViewLineTables::endFunction(), llvm::DwarfDebug::endInstruction(), finalizeDwarfSections(), forceExpAbs(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::MCLineEntry::Make(), and llvm::MCGenDwarfLabelEntry::Make().
void llvm::MCContext::Deallocate (void * Ptr) inline
Definition at line 438 of file MCContext.h.
void MCContext::FatalError (SMLoc L, const Twine & Msg) const
Definition at line 408 of file MCContext.cpp.
References llvm::SourceMgr::DK_Error, llvm::SourceMgr::PrintMessage(), llvm::report_fatal_error(), and llvm::sys::RunInterruptHandlers().
Referenced by adjustFixupValue(), and llvm::MCAsmLayout::getBaseSymbol().
void MCContext::finalizeDwarfSections (MCStreamer & MCOS)
finalizeDwarfSections - Emit end symbols for each non-empty code section. Also remove empty sections from SectionStartEndSyms, to avoid generating useless debug info for them.
Definition at line 388 of file MCContext.cpp.
References assert(), CreateTempSymbol(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::getContext(), llvm::MCStreamer::mayHaveInstructions(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCGenDwarfInfo::Emit().
const MCAsmInfo* llvm::MCContext::getAsmInfo () const inline
Definition at line 190 of file MCContext.h.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::MCStreamer::EmitCFIStartProc(), EmitDwarfLineTable(), emitFDESymbol(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::MCStreamer::EmitIntValue(), EmitPersonality(), forceExpAbs(), llvm::MCAssembler::getAtom(), getDataAlignmentFactor(), llvm::MCStreamer::getDwarfLineTableSymbol(), getSizeForEncoding(), llvm::MachineBasicBlock::getSymbol(), llvm::MCELFStreamer::InitSections(), and ScaleAddrDelta().
const MCSectionCOFF * MCContext::getAssociativeCOFFSection (const MCSectionCOFF * Sec, const MCSymbol * KeySym)
Gets or creates a section equivalent to Sec that is associated with the section containing KeySym. For example, to create a debug info section associated with an inline function, pass the normal debug info section as Sec and the function symbol as KeySym.
Definition at line 346 of file MCContext.cpp.
References Characteristics, llvm::MCSectionCOFF::getCharacteristics(), getCOFFSection(), llvm::MCSection::getKind(), llvm::MCSymbol::getName(), llvm::MCSectionCOFF::getSectionName(), llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, and llvm::COFF::IMAGE_SCN_LNK_COMDAT.
Referenced by llvm::WinEH::getUnwindInfoSection().
const MCSectionCOFF * MCContext::getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, StringRef COMDATSymName, int Selection)
Definition at line 306 of file MCContext.cpp.
References llvm::StringRef::empty(), GetOrCreateSymbol(), and T.
Referenced by getAssociativeCOFFSection(), getCOFFSection(), and llvm::WinEH::getUnwindInfoSection().
const MCSectionCOFF * MCContext::getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind)
Definition at line 332 of file MCContext.cpp.
References getCOFFSection().
const MCSectionCOFF * MCContext::getCOFFSection (StringRef Section)
Definition at line 337 of file MCContext.cpp.
References T.
StringRef llvm::MCContext::getCompilationDir () const inline
Get the compilation directory for DW_AT_comp_dir This can be overridden by clients which want to control the reported compilation directory and have it be something other than the current working directory. Returns an empty string if the current directory cannot be determined.
Definition at line 312 of file MCContext.h.
Referenced by EmitGenDwarfAbbrev(), and EmitGenDwarfInfo().
const MCDwarfLoc& llvm::MCContext::getCurrentDwarfLoc () inline
Definition at line 387 of file MCContext.h.
Referenced by llvm::MCLineEntry::Make().
MCSymbol * MCContext::GetDirectionalLocalSymbol (unsigned LocalLabelVal, bool Before)
Create and return a directional local symbol for numbered label (used for "1b" or 1f" references).
Definition at line 209 of file MCContext.cpp.
unsigned llvm::MCContext::getDwarfCompileUnitID () inline
Definition at line 359 of file MCContext.h.
Referenced by llvm::MCLineEntry::Make().
StringRef llvm::MCContext::getDwarfDebugFlags () inline
Definition at line 415 of file MCContext.h.
Referenced by EmitGenDwarfAbbrev(), and EmitGenDwarfInfo().
StringRef llvm::MCContext::getDwarfDebugProducer () inline
Definition at line 418 of file MCContext.h.
Referenced by EmitGenDwarfInfo().
unsigned MCContext::GetDwarfFile (StringRef Directory, StringRef FileName, unsigned FileNumber, unsigned CUID)
GetDwarfFile - creates an entry in the dwarf file and directory tables.
GetDwarfFile - takes a file name an number to place in the dwarf file and directory tables. If the file number has already been allocated it is an error and zero is returned and the client reports the error, else the allocated file number is returned. The file numbers may be in any order.
Definition at line 369 of file MCContext.cpp.
References llvm::MCDwarfLineTable::getFile().
Referenced by llvm::MCStreamer::EmitDwarfFileDirective().
bool llvm::MCContext::getDwarfLocSeen () inline
Definition at line 386 of file MCContext.h.
Referenced by llvm::MCLineEntry::Make().
uint16_t llvm::MCContext::getDwarfVersion () const inline
Definition at line 421 of file MCContext.h.
Referenced by llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfAbbrev(), and EmitGenDwarfInfo().
const MCSectionELF * MCContext::getELFSection (StringRef Section, unsigned Type, unsigned Flags, SectionKind Kind)
Definition at line 256 of file MCContext.cpp.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MCELFStreamer::EmitIdent(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::MCObjectFileInfo::getDwarfTypesSection(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), getStaticStructorSection(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::XCoreTargetObjectFile::Initialize(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
const MCSectionELF * MCContext::getELFSection (StringRef Section, unsigned Type, unsigned Flags, SectionKind Kind, unsigned EntrySize, StringRef Group)
Definition at line 275 of file MCContext.cpp.
References llvm::MCSectionELF::DetermineEntrySize(), llvm::StringRef::empty(), and GetOrCreateSymbol().
unsigned llvm::MCContext::getGenDwarfFileNumber () inline
Definition at line 391 of file MCContext.h.
Referenced by llvm::MCGenDwarfLabelEntry::Make().
bool llvm::MCContext::getGenDwarfForAssembly () inline
Definition at line 389 of file MCContext.h.
MapVector<const MCSection *, std::pair<MCSymbol *, MCSymbol *> >& llvm::MCContext::getGenDwarfSectionSyms () inline
Definition at line 396 of file MCContext.h.
Referenced by llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), and llvm::MCGenDwarfLabelEntry::Make().
const MCSectionMachO * MCContext::getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, unsigned Reserved2, SectionKind K)
getMachOSection - Return the MCSection for the specified mach-o section. This requires the operands to be valid.
Definition at line 232 of file MCContext.cpp.
References Name, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ARMBuildAttrs::Section, and llvm::SmallString< InternalLen >::str().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), and getMachOSection().
const MCSectionMachO* llvm::MCContext::getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, SectionKind K) inline
Definition at line 266 of file MCContext.h.
References getMachOSection().
const std::string& llvm::MCContext::getMainFileName () const inline
Get the main file name for use in error messages and debug info. This can be set to ensure we've got the correct file name after preprocessing or for -save-temps.
Definition at line 321 of file MCContext.h.
const SmallVectorImpl<std::string>& llvm::MCContext::getMCDwarfDirs (unsigned CUID = 0) inline
Definition at line 349 of file MCContext.h.
References llvm::MCDwarfLineTable::getMCDwarfDirs(), and getMCDwarfLineTable().
Referenced by EmitGenDwarfInfo().
const SmallVectorImpl<MCDwarfFile>& llvm::MCContext::getMCDwarfFiles (unsigned CUID = 0) inline
Definition at line 346 of file MCContext.h.
References llvm::MCDwarfLineTable::getMCDwarfFiles(), and getMCDwarfLineTable().
Referenced by EmitGenDwarfInfo(), and isValidDwarfFileNumber().
MCDwarfLineTable& llvm::MCContext::getMCDwarfLineTable (unsigned CUID) inline
Definition at line 336 of file MCContext.h.
Referenced by llvm::MCStreamer::getDwarfLineTableSymbol(), getMCDwarfDirs(), getMCDwarfFiles(), llvm::MCLineEntry::Make(), and setMCLineTableCompilationDir().
const MCDwarfLineTable& llvm::MCContext::getMCDwarfLineTable (unsigned CUID) const inline
Definition at line 340 of file MCContext.h.
References assert(), and I.
const std::map<unsigned, MCDwarfLineTable>& llvm::MCContext::getMCDwarfLineTables () const inline
Definition at line 332 of file MCContext.h.
Referenced by llvm::MCDwarfLineTable::Emit().
const std::vector<MCGenDwarfLabelEntry>& llvm::MCContext::getMCGenDwarfLabelEntries () const inline
Definition at line 407 of file MCContext.h.
Referenced by EmitGenDwarfInfo().
const MCObjectFileInfo* llvm::MCContext::getObjectFileInfo () const inline
Definition at line 194 of file MCContext.h.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::MCDwarfLineTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), EmitDwarfLineTable(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MipsTargetELFStreamer::finish(), llvm::WinEH::UnwindEmitter::getPDataSection(), llvm::WinEH::UnwindEmitter::getXDataSection(), llvm::MCELFStreamer::InitSections(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), and llvm::StackMaps::serializeToStackMapSection().
MCSymbol * MCContext::getOrCreateFrameAllocSymbol (StringRef FuncName)
Definition at line 133 of file MCContext.cpp.
References GetOrCreateSymbol(), and llvm::MCAsmInfo::getPrivateGlobalPrefix().
MCSymbol * MCContext::getOrCreateSectionSymbol (const MCSectionELF & Section)
Definition at line 111 of file MCContext.cpp.
References llvm::MCSectionELF::getSectionName(), llvm::MCSymbol::isUndefined(), Name, and llvm::ARMBuildAttrs::Section.
Referenced by llvm::MCELFStreamer::ChangeSection().
MCSymbol * MCContext::GetOrCreateSymbol (StringRef Name)
GetOrCreateSymbol - Lookup the symbol inside with the specified Name. If it exists, return it. If not, create a forward reference and return it.
Parameters
Name - The symbol name, which must be unique across all symbols.
Definition at line 100 of file MCContext.cpp.
References assert(), llvm::StringRef::empty(), and Name.
Referenced by llvm::AsmPrinter::doFinalization(), EmitCamlGlobal(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::AMDGPUAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), GetAnonSym(), getCOFFSection(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::MCStreamer::getDwarfLineTableSymbol(), getELFSection(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineFunction::getJTISymbol(), llvm::AsmPrinter::GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), GetLazyPtr(), getOrCreateFrameAllocSymbol(), GetOrCreateSymbol(), llvm::MachineFunction::getPICBaseSymbol(), getPICLabel(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::TargetMachine::getSymbol(), llvm::MachineBasicBlock::getSymbol(), GetSymbolFromOperand(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::AsmPrinter::GetTempSymbol(), llvm::AMDGPUMCInstLower::lower(), printSymbolOperand(), llvm::StackMaps::serializeToStackMapSection(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::MCExternalSymbolizer::tryAddingSymbolicOperand().
MCSymbol * MCContext::GetOrCreateSymbol (const Twine & Name)
Definition at line 163 of file MCContext.cpp.
References GetOrCreateSymbol(), and llvm::Twine::toStringRef().
const MCRegisterInfo* llvm::MCContext::getRegisterInfo () const inline
Definition at line 192 of file MCContext.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::MipsTargetELFStreamer::emitFrame(), llvm::MipsELFStreamer::EmitInstruction(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86AsmInstrumentation::GetFrameRegGeneric(), llvm::HexagonMCCodeEmitter::getMachineOpValue(), llvm::MipsRegInfoRecord::MipsRegInfoRecord(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
raw_ostream* llvm::MCContext::getSecureLog () inline
Definition at line 426 of file MCContext.h.
char* llvm::MCContext::getSecureLogFile () inline
Definition at line 425 of file MCContext.h.
bool llvm::MCContext::getSecureLogUsed () inline
Definition at line 427 of file MCContext.h.
const SourceMgr* llvm::MCContext::getSourceManager () const inline
Definition at line 188 of file MCContext.h.
const SymbolTable& llvm::MCContext::getSymbols () const inline
getSymbols - Get a reference for the symbol table for clients that want to, for example, iterate over all symbols. 'const' because we still want any modifications to the table itself to use the MCContext APIs.
Definition at line 250 of file MCContext.h.
unsigned llvm::MCContext::getUniqueSymbolID () inline
getUniqueSymbolID() - Return a unique identifier for use in constructing symbol names.
Definition at line 220 of file MCContext.h.
bool llvm::MCContext::hasMCLineSections () const inline
Definition at line 353 of file MCContext.h.
bool MCContext::isValidDwarfFileNumber (unsigned FileNumber, unsigned CUID = 0)
isValidDwarfFileNumber - takes a dwarf file number and returns true if it currently is assigned and false otherwise.
Definition at line 377 of file MCContext.cpp.
References llvm::SmallVectorBase::empty(), getMCDwarfFiles(), and llvm::SmallVectorTemplateCommon< T >::size().
MCSymbol * MCContext::LookupSymbol (StringRef Name) const
LookupSymbol - Get the symbol for Name, or null.
Definition at line 217 of file MCContext.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::lookup().
Referenced by LookupSymbol().
MCSymbol * MCContext::LookupSymbol (const Twine & Name) const
Definition at line 221 of file MCContext.cpp.
References LookupSymbol(), llvm::SmallString< InternalLen >::str(), and llvm::Twine::toVector().
void MCContext::renameELFSection (const MCSectionELF * Section, StringRef Name)
Definition at line 261 of file MCContext.cpp.
References llvm::MCSectionELF::getGroup(), llvm::MCSectionELF::getSectionName(), I, and llvm::ARMBuildAttrs::Section.
Referenced by CompressDebugSection().
void MCContext::reset ()
reset - return object to right after construction state to prepare to process a new module
Definition at line 71 of file MCContext.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::clear(), llvm::SmallVectorImpl< T >::clear(), DWARF2_FLAG_IS_STMT, and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Reset().
Referenced by llvm::MachineModuleInfo::doFinalization(), and ~MCContext().
void llvm::MCContext::setAllowTemporaryLabels (bool Value) inline
Definition at line 196 of file MCContext.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
void llvm::MCContext::setCompilationDir (StringRef S) inline
Set the compilation directory for DW_AT_comp_dir Override the default (CWD) compilation directory.
Definition at line 316 of file MCContext.h.
References llvm::StringRef::str().
void llvm::MCContext::setCurrentDwarfLoc (unsigned FileNum, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator) inline
setCurrentDwarfLoc - saves the information from the currently parsed dwarf .loc directive and sets DwarfLocSeen. When the next instruction is assembled an entry in the line number table with this information and the address of the instruction will be created.
Definition at line 373 of file MCContext.h.
References llvm::MCDwarfLoc::setColumn(), llvm::MCDwarfLoc::setDiscriminator(), llvm::MCDwarfLoc::setFileNum(), llvm::MCDwarfLoc::setFlags(), llvm::MCDwarfLoc::setIsa(), and llvm::MCDwarfLoc::setLine().
Referenced by llvm::MCStreamer::EmitDwarfLocDirective().
void llvm::MCContext::setDwarfCompileUnitID (unsigned CUIndex) inline
Definition at line 362 of file MCContext.h.
void llvm::MCContext::setDwarfDebugFlags (StringRef S) inline
Definition at line 414 of file MCContext.h.
void llvm::MCContext::setDwarfDebugProducer (StringRef S) inline
Definition at line 417 of file MCContext.h.
void llvm::MCContext::setDwarfVersion (uint16_t v) inline
Definition at line 420 of file MCContext.h.
Referenced by llvm::DwarfDebug::DwarfDebug().
void llvm::MCContext::setGenDwarfFileNumber (unsigned FileNumber) inline
Definition at line 392 of file MCContext.h.
void llvm::MCContext::setGenDwarfForAssembly (bool Value) inline
Definition at line 390 of file MCContext.h.
void llvm::MCContext::setMainFileName (StringRef S) inline
Set the main file name and override the default.
Definition at line 324 of file MCContext.h.
void llvm::MCContext::setMCLineTableCompilationDir (unsigned CUID, StringRef CompilationDir) inline
Definition at line 365 of file MCContext.h.
References getMCDwarfLineTable(), and llvm::MCDwarfLineTable::setCompilationDir().
void llvm::MCContext::setSecureLog (raw_ostream * Value) inline
Definition at line 428 of file MCContext.h.
void llvm::MCContext::setSecureLogUsed (bool Value) inline
Definition at line 431 of file MCContext.h.
The documentation for this class was generated from the following files:
MCContext.h
MCContext.cpp