LLVM: llvm::MachineDominatorTree Class Reference
LLVM API Documentation
llvm::MachineDominatorTree Class Reference
#include <MachineDominators.h>
Public Member Functions
MachineDominatorTree ()
~MachineDominatorTree ()
DominatorTreeBase
< MachineBasicBlock > & getBase ()
void getAnalysisUsage (AnalysisUsage &AU) const override
const std::vector
< MachineBasicBlock * > & getRoots () const
MachineBasicBlock * getRoot () const
MachineDomTreeNode * getRootNode () const
bool runOnMachineFunction (MachineFunction &F) override
bool dominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool dominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
bool dominates (const MachineInstr *A, const MachineInstr *B) const
bool properlyDominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool properlyDominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
MachineBasicBlock * findNearestCommonDominator (MachineBasicBlock *A, MachineBasicBlock *B)
MachineDomTreeNode * operator[] (MachineBasicBlock *BB) const
MachineDomTreeNode * getNode (MachineBasicBlock *BB) const
MachineDomTreeNode * addNewBlock (MachineBasicBlock *BB, MachineBasicBlock *DomBB)
void changeImmediateDominator (MachineBasicBlock *N, MachineBasicBlock *NewIDom)
void changeImmediateDominator (MachineDomTreeNode *N, MachineDomTreeNode *NewIDom)
void eraseNode (MachineBasicBlock *BB)
void splitBlock (MachineBasicBlock *NewBB)
bool isReachableFromEntry (const MachineBasicBlock *A)
void releaseMemory () override
void print (raw_ostream &OS, const Module *) const override
void recordSplitCriticalEdge (MachineBasicBlock *FromBB, MachineBasicBlock *ToBB, MachineBasicBlock *NewBB)
Record that the critical edge (FromBB, ToBB) has been split with NewBB. This is best to use this method instead of directly update the underlying information, because this helps mitigating the number of time the DT information is invalidated.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Attributes
DominatorTreeBase
< MachineBasicBlock > * DT
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
DominatorTree Class - Concrete subclass of DominatorTreeBase that is used to compute a normal dominator tree.
Definition at line 41 of file MachineDominators.h.
Constructor & Destructor Documentation
MachineDominatorTree::MachineDominatorTree ()
Definition at line 45 of file MachineDominators.cpp.
References DT, llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineDominatorTreePass().
MachineDominatorTree::~MachineDominatorTree ()
Definition at line 51 of file MachineDominators.cpp.
References DT.
Member Function Documentation
MachineDomTreeNode* llvm::MachineDominatorTree::addNewBlock (MachineBasicBlock * BB, MachineBasicBlock * DomBB) inline
addNewBlock - Add a new node to the dominator tree information. This creates a new node as a child of DomBB dominator node,linking it into the children list of the immediate dominator.
Definition at line 244 of file MachineDominators.h.
References DT.
void llvm::MachineDominatorTree::changeImmediateDominator (MachineBasicBlock * N, MachineBasicBlock * NewIDom) inline
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
Definition at line 253 of file MachineDominators.h.
References DT.
void llvm::MachineDominatorTree::changeImmediateDominator (MachineDomTreeNode * N, MachineDomTreeNode * NewIDom) inline
Definition at line 259 of file MachineDominators.h.
References DT.
bool llvm::MachineDominatorTree::dominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 175 of file MachineDominators.h.
References DT.
Referenced by computeADRP(), and isCandidate().
bool llvm::MachineDominatorTree::dominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 181 of file MachineDominators.h.
References DT.
bool llvm::MachineDominatorTree::dominates (const MachineInstr * A, const MachineInstr * B) const inline
Definition at line 189 of file MachineDominators.h.
References llvm::ARM_PROC::A, llvm::MachineBasicBlock::begin(), DT, llvm::MachineInstr::getParent(), and I.
void llvm::MachineDominatorTree::eraseNode (MachineBasicBlock * BB) inline
eraseNode - Removes a node from the dominator tree. Block must not dominate any other blocks. Removes node from its immediate dominator's children list. Deletes dominator node associated with basic block BB.
Definition at line 268 of file MachineDominators.h.
References DT.
MachineBasicBlock* llvm::MachineDominatorTree::findNearestCommonDominator (MachineBasicBlock * A, MachineBasicBlock * B) inline
findNearestCommonDominator - Find nearest common dominator basic block for basic block A and B. If there is no such block then return NULL.
Definition at line 222 of file MachineDominators.h.
References DT.
void llvm::MachineDominatorTree::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
DominatorTreeBase<MachineBasicBlock>& llvm::MachineDominatorTree::getBase () inline
Definition at line 147 of file MachineDominators.h.
References DT.
MachineDomTreeNode* llvm::MachineDominatorTree::getNode (MachineBasicBlock * BB) const inline
getNode - return the (Post)DominatorTree node for the specified basic block. This is the same as using operator[] on this class.
Definition at line 236 of file MachineDominators.h.
References DT.
MachineBasicBlock* llvm::MachineDominatorTree::getRoot () const inline
Definition at line 163 of file MachineDominators.h.
References DT.
MachineDomTreeNode* llvm::MachineDominatorTree::getRootNode () const inline
Definition at line 168 of file MachineDominators.h.
References DT.
Referenced by llvm::GraphTraits< MachineDominatorTree * >::getEntryNode().
const std::vector<MachineBasicBlock*>& llvm::MachineDominatorTree::getRoots () const inline
getRoots - Return the root blocks of the current CFG. This may include multiple blocks if we are computing post dominators. For forward dominators, this will always be a single block (the entry node).
Definition at line 158 of file MachineDominators.h.
References DT.
bool llvm::MachineDominatorTree::isReachableFromEntry (const MachineBasicBlock * A) inline
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
Definition at line 282 of file MachineDominators.h.
References DT.
MachineDomTreeNode* llvm::MachineDominatorTree::operator[] (MachineBasicBlock * BB) const inline
Definition at line 228 of file MachineDominators.h.
References DT.
void MachineDominatorTree::print (raw_ostream & O, const Module * M) const override virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 59 of file MachineDominators.cpp.
References DT.
bool llvm::MachineDominatorTree::properlyDominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 208 of file MachineDominators.h.
References DT.
bool llvm::MachineDominatorTree::properlyDominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 214 of file MachineDominators.h.
References DT.
void llvm::MachineDominatorTree::recordSplitCriticalEdge (MachineBasicBlock * FromBB, MachineBasicBlock * ToBB, MachineBasicBlock * NewBB) inline
Record that the critical edge (FromBB, ToBB) has been split with NewBB. This is best to use this method instead of directly update the underlying information, because this helps mitigating the number of time the DT information is invalidated.
Note
Do not use this method with regular edges.
To benefit from the compile time improvement incurred by this method, the users of this method have to limit the queries to the DT interface between two edges splitting. In other words, they have to pack the splitting of critical edges as much as possible.
Definition at line 303 of file MachineDominators.h.
References assert(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void MachineDominatorTree::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 55 of file MachineDominators.cpp.
References DT.
bool MachineDominatorTree::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 37 of file MachineDominators.cpp.
References llvm::SmallVectorImpl< T >::clear(), and DT.
void llvm::MachineDominatorTree::splitBlock (MachineBasicBlock * NewBB) inline
splitBlock - BB is split and now it has one successor. Update dominator tree to reflect this change.
Definition at line 275 of file MachineDominators.h.
References DT.
Member Data Documentation
DominatorTreeBase<MachineBasicBlock>* llvm::MachineDominatorTree::DT
Definition at line 141 of file MachineDominators.h.
Referenced by addNewBlock(), changeImmediateDominator(), dominates(), eraseNode(), findNearestCommonDominator(), getBase(), getNode(), getRoot(), getRootNode(), getRoots(), isReachableFromEntry(), MachineDominatorTree(), operator[](), print(), properlyDominates(), releaseMemory(), runOnMachineFunction(), splitBlock(), and ~MachineDominatorTree().
char MachineDominatorTree::ID = 0 static
Definition at line 140 of file MachineDominators.h.
The documentation for this class was generated from the following files:
MachineDominators.h
MachineDominators.cpp