LLVM: llvm::TinyPtrVector< EltTy > Class Template Reference
LLVM API Documentation
llvm::TinyPtrVector< EltTy > Class Template Reference
#include <TinyPtrVector.h>
Public Types
typedef llvm::SmallVector
< EltTy, 4 > VecTy
typedef VecTy::value_type value_type
typedef const EltTy * const_iterator
typedef EltTy * iterator
Public Member Functions
TinyPtrVector ()
~TinyPtrVector ()
TinyPtrVector (const TinyPtrVector &RHS)
TinyPtrVector & operator= (const TinyPtrVector &RHS)
TinyPtrVector (TinyPtrVector &&RHS)
TinyPtrVector & operator= (TinyPtrVector &&RHS)
TinyPtrVector (EltTy Elt)
Constructor from a single element.
TinyPtrVector (ArrayRef< EltTy > Elts)
Constructor from an ArrayRef.
operator ArrayRef< EltTy > () const
bool empty () const
unsigned size () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
EltTy operator[] (unsigned i) const
EltTy front () const
EltTy back () const
void push_back (EltTy NewVal)
void pop_back ()
void clear ()
iterator erase (iterator I)
iterator erase (iterator S, iterator E)
iterator insert (iterator I, const EltTy &Elt)
template<typename ItTy >
iterator insert (iterator I, ItTy From, ItTy To)
Public Attributes
llvm::PointerUnion< EltTy,
VecTy * > Val
Detailed Description
template<typename EltTy>
class llvm::TinyPtrVector< EltTy >
TinyPtrVector - This class is specialized for cases where there are normally 0 or 1 element in a vector, but is general enough to go beyond that when required.
NOTE: This container doesn't allow you to store a null pointer into it.
Definition at line 26 of file TinyPtrVector.h.
Member Typedef Documentation
template<typename EltTy> typedef const EltTy* llvm::TinyPtrVector< EltTy >::const_iterator
Definition at line 132 of file TinyPtrVector.h.
template<typename EltTy> typedef EltTy* llvm::TinyPtrVector< EltTy >::iterator
Definition at line 133 of file TinyPtrVector.h.
template<typename EltTy> typedef VecTy::value_type llvm::TinyPtrVector< EltTy >::value_type
Definition at line 29 of file TinyPtrVector.h.
template<typename EltTy> typedef llvm::SmallVector<EltTy, 4> llvm::TinyPtrVector< EltTy >::VecTy
Definition at line 28 of file TinyPtrVector.h.
Constructor & Destructor Documentation
template<typename EltTy> llvm::TinyPtrVector< EltTy >::TinyPtrVector () inline
Definition at line 33 of file TinyPtrVector.h.
template<typename EltTy> llvm::TinyPtrVector< EltTy >::~TinyPtrVector () inline
Definition at line 34 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> llvm::TinyPtrVector< EltTy >::TinyPtrVector (const TinyPtrVector< EltTy > & RHS) inline
Definition at line 39 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> llvm::TinyPtrVector< EltTy >::TinyPtrVector (TinyPtrVector< EltTy > && RHS) inline
Definition at line 71 of file TinyPtrVector.h.
template<typename EltTy> llvm::TinyPtrVector< EltTy >::TinyPtrVector (EltTy Elt) inline explicit
Constructor from a single element.
Definition at line 100 of file TinyPtrVector.h.
template<typename EltTy> llvm::TinyPtrVector< EltTy >::TinyPtrVector (ArrayRef< EltTy > Elts) inline explicit
Constructor from an ArrayRef.
Definition at line 103 of file TinyPtrVector.h.
Member Function Documentation
template<typename EltTy> EltTy llvm::TinyPtrVector< EltTy >::back () const inline
Definition at line 176 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::empty(), and llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> iterator llvm::TinyPtrVector< EltTy >::begin () inline
Definition at line 135 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::Val.
Referenced by llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), llvm::TinyPtrVector< EltTy >::erase(), and llvm::TinyPtrVector< EltTy >::insert().
template<typename EltTy> const_iterator llvm::TinyPtrVector< EltTy >::begin () const inline
Definition at line 149 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::begin().
template<typename EltTy> void llvm::TinyPtrVector< EltTy >::clear () inline
Definition at line 210 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::Val.
Referenced by llvm::TinyPtrVector< EltTy >::operator=(), and llvm::LoadAndStorePromoter::run().
template<typename EltTy> bool llvm::TinyPtrVector< EltTy >::empty () const inline
Definition at line 115 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::Val.
Referenced by llvm::TinyPtrVector< EltTy >::back(), llvm::TinyPtrVector< EltTy >::front(), llvm::TinyPtrVector< EltTy >::operator=(), llvm::LoadAndStorePromoter::run(), and llvm::TinyPtrVector< EltTy >::size().
template<typename EltTy> iterator llvm::TinyPtrVector< EltTy >::end () inline
Definition at line 142 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::begin(), and llvm::TinyPtrVector< EltTy >::Val.
Referenced by llvm::TinyPtrVector< EltTy >::end(), llvm::TinyPtrVector< EltTy >::erase(), and llvm::TinyPtrVector< EltTy >::insert().
template<typename EltTy> const_iterator llvm::TinyPtrVector< EltTy >::end () const inline
Definition at line 153 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::end().
template<typename EltTy> iterator llvm::TinyPtrVector< EltTy >::erase (iterator I) inline
Definition at line 221 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), and llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> iterator llvm::TinyPtrVector< EltTy >::erase (iterator S, iterator E) inline
Definition at line 237 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), and llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> EltTy llvm::TinyPtrVector< EltTy >::front () const inline
Definition at line 169 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::empty(), and llvm::TinyPtrVector< EltTy >::Val.
Referenced by llvm::TinyPtrVector< EltTy >::operator=().
template<typename EltTy> iterator llvm::TinyPtrVector< EltTy >::insert (iterator I, const EltTy & Elt) inline
Definition at line 251 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), llvm::TinyPtrVector< EltTy >::push_back(), and llvm::TinyPtrVector< EltTy >::Val.
Referenced by llvm::TinyPtrVector< EltTy >::insert().
template<typename EltTy> template<typename ItTy > iterator llvm::TinyPtrVector< EltTy >::insert (iterator I, ItTy From, ItTy To) inline
Definition at line 270 of file TinyPtrVector.h.
References assert(), llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::end(), I, llvm::TinyPtrVector< EltTy >::insert(), llvm::TinyPtrVector< EltTy >::push_back(), and llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> llvm::TinyPtrVector< EltTy >::operator ArrayRef< EltTy > () const inline
Definition at line 107 of file TinyPtrVector.h.
References llvm::None, and llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> TinyPtrVector& llvm::TinyPtrVector< EltTy >::operator= (const TinyPtrVector< EltTy > & RHS) inline
Definition at line 43 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::clear(), llvm::TinyPtrVector< EltTy >::empty(), llvm::TinyPtrVector< EltTy >::front(), llvm::TinyPtrVector< EltTy >::push_back(), llvm::TinyPtrVector< EltTy >::size(), and llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> TinyPtrVector& llvm::TinyPtrVector< EltTy >::operator= (TinyPtrVector< EltTy > && RHS) inline
Definition at line 74 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::clear(), and llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> EltTy llvm::TinyPtrVector< EltTy >::operator[] (unsigned i) const inline
Definition at line 157 of file TinyPtrVector.h.
References assert(), and llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> void llvm::TinyPtrVector< EltTy >::pop_back () inline
Definition at line 202 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::Val.
template<typename EltTy> void llvm::TinyPtrVector< EltTy >::push_back (EltTy NewVal) inline
Definition at line 183 of file TinyPtrVector.h.
References assert(), and llvm::TinyPtrVector< EltTy >::Val.
Referenced by llvm::TinyPtrVector< EltTy >::insert(), and llvm::TinyPtrVector< EltTy >::operator=().
template<typename EltTy> unsigned llvm::TinyPtrVector< EltTy >::size () const inline
Definition at line 124 of file TinyPtrVector.h.
References llvm::TinyPtrVector< EltTy >::empty(), and llvm::TinyPtrVector< EltTy >::Val.
Referenced by llvm::TinyPtrVector< EltTy >::operator=(), and llvm::LoadAndStorePromoter::run().
Member Data Documentation
template<typename EltTy> llvm::PointerUnion<EltTy, VecTy*> llvm::TinyPtrVector< EltTy >::Val
Definition at line 31 of file TinyPtrVector.h.
Referenced by llvm::TinyPtrVector< EltTy >::back(), llvm::TinyPtrVector< EltTy >::begin(), llvm::TinyPtrVector< EltTy >::clear(), llvm::TinyPtrVector< EltTy >::empty(), llvm::TinyPtrVector< EltTy >::end(), llvm::TinyPtrVector< EltTy >::erase(), llvm::TinyPtrVector< EltTy >::front(), llvm::TinyPtrVector< EltTy >::insert(), llvm::TinyPtrVector< EltTy >::operator ArrayRef< EltTy >(), llvm::TinyPtrVector< EltTy >::operator=(), llvm::TinyPtrVector< EltTy >::operator[](), llvm::TinyPtrVector< EltTy >::pop_back(), llvm::TinyPtrVector< EltTy >::push_back(), llvm::TinyPtrVector< EltTy >::size(), llvm::TinyPtrVector< EltTy >::TinyPtrVector(), and llvm::TinyPtrVector< EltTy >::~TinyPtrVector().
The documentation for this class was generated from the following file:
TinyPtrVector.h