LLVM: llvm::ImutAVLTreeInOrderIterator< ImutInfo > Class Template Reference
LLVM API Documentation
llvm::ImutAVLTreeInOrderIterator< ImutInfo > Class Template Reference
#include <ImmutableSet.h>
Public Types
typedef ImutAVLTree< ImutInfo > TreeTy
typedef
ImutAVLTreeInOrderIterator
< ImutInfo > _Self
Public Member Functions
ImutAVLTreeInOrderIterator (const TreeTy *Root)
ImutAVLTreeInOrderIterator ()
bool operator== (const _Self &x) const
bool operator!= (const _Self &x) const
TreeTy * operator* () const
TreeTy * operator-> () const
_Self & operator++ ()
_Self & operator-- ()
void skipSubTree ()
Detailed Description
template<typename ImutInfo>
class llvm::ImutAVLTreeInOrderIterator< ImutInfo >
Definition at line 34 of file ImmutableSet.h.
Member Typedef Documentation
template<typename ImutInfo > typedef ImutAVLTreeInOrderIterator<ImutInfo> llvm::ImutAVLTreeInOrderIterator< ImutInfo >::_Self
Definition at line 763 of file ImmutableSet.h.
template<typename ImutInfo > typedef ImutAVLTree<ImutInfo> llvm::ImutAVLTreeInOrderIterator< ImutInfo >::TreeTy
Definition at line 762 of file ImmutableSet.h.
Constructor & Destructor Documentation
template<typename ImutInfo > llvm::ImutAVLTreeInOrderIterator< ImutInfo >::ImutAVLTreeInOrderIterator (const TreeTy * Root) inline
Definition at line 765 of file ImmutableSet.h.
References llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator++().
template<typename ImutInfo > llvm::ImutAVLTreeInOrderIterator< ImutInfo >::ImutAVLTreeInOrderIterator () inline
Definition at line 769 of file ImmutableSet.h.
Member Function Documentation
template<typename ImutInfo > bool llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator!= (const _Self & x) const inline
Definition at line 775 of file ImmutableSet.h.
References llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator==().
template<typename ImutInfo > TreeTy* llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator* () const inline
Definition at line 777 of file ImmutableSet.h.
template<typename ImutInfo > _Self& llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator++ () inline
Definition at line 780 of file ImmutableSet.h.
Referenced by llvm::ImutAVLTreeInOrderIterator< ImutInfo >::ImutAVLTreeInOrderIterator().
template<typename ImutInfo > _Self& llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator-- () inline
Definition at line 788 of file ImmutableSet.h.
template<typename ImutInfo > TreeTy* llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator-> () const inline
Definition at line 778 of file ImmutableSet.h.
template<typename ImutInfo > bool llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator== (const _Self & x) const inline
Definition at line 771 of file ImmutableSet.h.
Referenced by llvm::ImutAVLTreeInOrderIterator< ImutInfo >::operator!=().
template<typename ImutInfo > void llvm::ImutAVLTreeInOrderIterator< ImutInfo >::skipSubTree () inline
Definition at line 796 of file ImmutableSet.h.
Referenced by llvm::ImutAVLTree< ImutInfo >::isEqual().
The documentation for this class was generated from the following file:
ImmutableSet.h