LLVM: llvm::Win64Exception Class Reference
LLVM API Documentation
llvm::Win64Exception Class Reference
#include <Win64Exception.h>
Public Member Functions
Win64Exception (AsmPrinter *A)
virtual ~Win64Exception ()
void endModule () override
Emit all exception information that should come after the content.
void beginFunction (const MachineFunction *MF) override
void endFunction (const MachineFunction *) override
Gather and emit post-function exception information.
Public Member Functions inherited from llvm::EHStreamer
EHStreamer (AsmPrinter *A)
virtual ~EHStreamer ()
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g. common symbols), this tracks that size.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
Additional Inherited Members
Protected Types inherited from llvm::EHStreamer
typedef DenseMap< MCSymbol
*, PadRange > RangeMapType
Protected Member Functions inherited from llvm::EHStreamer
unsigned computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LPs, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
bool callToNoUnwindFunction (const MachineInstr *MI)
void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, const SmallVectorImpl< const LandingPadInfo * > &LPs, const SmallVectorImpl< unsigned > &FirstActions)
void emitExceptionTable ()
virtual void emitTypeInfos (unsigned TTypeEncoding)
Static Protected Member Functions inherited from llvm::EHStreamer
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
Protected Attributes inherited from llvm::EHStreamer
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Detailed Description
Definition at line 22 of file Win64Exception.h.
Constructor & Destructor Documentation
Win64Exception::Win64Exception (AsmPrinter * A)
Definition at line 40 of file Win64Exception.cpp.
Win64Exception::~Win64Exception () virtual
Definition at line 44 of file Win64Exception.cpp.
Member Function Documentation
void Win64Exception::beginFunction (const MachineFunction * MF) override virtual
Gather pre-function exception information. Assumes being emitted immediately after the function entry point.
beginFunction - Gather pre-function exception information. Assumes it's being emitted immediately after the function entry point.
Reimplemented from llvm::EHStreamer.
Definition at line 53 of file Win64Exception.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::CurrentFnSym, llvm::dwarf::DW_EH_PE_omit, llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitWinCFIStartProc(), llvm::MCStreamer::EmitWinEHHandler(), llvm::TargetLoweringObjectFile::getCFIPersonalitySymbol(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineModuleInfo::getLandingPads(), llvm::MCObjectFileInfo::getLSDAEncoding(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineModuleInfo::getPersonalities(), llvm::MCObjectFileInfo::getPersonalityEncoding(), llvm::MachineModuleInfo::getPersonalityIndex(), llvm::AsmPrinter::GetTempSymbol(), llvm::AsmPrinter::Mang, llvm::EHStreamer::MMI, llvm::AsmPrinter::needsSEHMoves(), llvm::AsmPrinter::OutStreamer, and llvm::AsmPrinter::TM.
void Win64Exception::endFunction (const MachineFunction *) override virtual
Gather and emit post-function exception information.
endFunction - Gather and emit post-function exception information.
Reimplemented from llvm::EHStreamer.
Definition at line 90 of file Win64Exception.cpp.
References llvm::EHStreamer::Asm, llvm::EHStreamer::emitExceptionTable(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitWinCFIEndProc(), llvm::MCStreamer::EmitWinEHHandlerData(), llvm::AsmPrinter::getFunctionNumber(), llvm::AsmPrinter::GetTempSymbol(), llvm::EHStreamer::MMI, llvm::AsmPrinter::OutStreamer, llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), and llvm::MachineModuleInfo::TidyLandingPads().
void Win64Exception::endModule () override virtual
Emit all exception information that should come after the content.
endModule - Emit all exception information that should come after the content.
Reimplemented from llvm::EHStreamer.
Definition at line 48 of file Win64Exception.cpp.
The documentation for this class was generated from the following files:
Win64Exception.h
Win64Exception.cpp