LLVM: llvm::MachineRegionInfo Class Reference
LLVM API Documentation
llvm::MachineRegionInfo Class Reference
#include <MachineRegionInfo.h>
Public Member Functions
MachineRegionInfo ()
virtual ~MachineRegionInfo ()
void updateStatistics (MachineRegion *R) final
void recalculate (MachineFunction &F, MachineDominatorTree *DT, MachinePostDominatorTree *PDT, MachineDominanceFrontier *DF)
Public Member Functions inherited from llvm::RegionInfoBase< RegionTraits< MachineFunction > >
void print (raw_ostream &OS) const
void dump () const
void releaseMemory ()
RegionT * getRegionFor (BlockT *BB) const
Get the smallest region that contains a BasicBlock.
void setRegionFor (BlockT *BB, RegionT *R)
Set the smallest region that surrounds a basic block.
RegionT * operator[] (BlockT *BB) const
A shortcut for getRegionFor().
BlockT * getMaxRegionExit (BlockT *BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
RegionT * getCommonRegion (RegionT *A, RegionT *B) const
Find the smallest region that contains two regions.
RegionT * getCommonRegion (BlockT *A, BlockT *B) const
Find the smallest region that contains two basic blocks.
RegionT * getCommonRegion (SmallVectorImpl< RegionT * > &Regions) const
Find the smallest region that contains a set of regions.
RegionT * getCommonRegion (SmallVectorImpl< BlockT * > &BBs) const
Find the smallest region that contains a set of basic blocks.
RegionT * getTopLevelRegion () const
void splitBlock (BlockT *NewBB, BlockT *OldBB)
Update RegionInfo after a basic block was split.
void clearNodeCache ()
Clear the Node Cache for all Regions.
void verifyAnalysis () const
Additional Inherited Members
Static Public Attributes inherited from llvm::RegionInfoBase< RegionTraits< MachineFunction > >
static bool VerifyRegionInfo
static RegionT::PrintStyle printStyle
Detailed Description
Definition at line 79 of file MachineRegionInfo.h.
Constructor & Destructor Documentation
MachineRegionInfo::MachineRegionInfo () explicit
Definition at line 37 of file MachineRegionInfo.cpp.
MachineRegionInfo::~MachineRegionInfo () virtual
Definition at line 42 of file MachineRegionInfo.cpp.
Member Function Documentation
void MachineRegionInfo::recalculate (MachineFunction & F, MachineDominatorTree * DT, MachinePostDominatorTree * PDT, MachineDominanceFrontier * DF)
Definition at line 54 of file MachineRegionInfo.cpp.
References updateStatistics().
Referenced by llvm::MachineRegionInfoPass::runOnMachineFunction().
void MachineRegionInfo::updateStatistics (MachineRegion * R) final
Definition at line 46 of file MachineRegionInfo.cpp.
References llvm::RegionBase< RegionTr >::isSimple().
Referenced by recalculate().
The documentation for this class was generated from the following files:
MachineRegionInfo.h
MachineRegionInfo.cpp