LLVM: llvm::SIInstrInfo Class Reference
LLVM API Documentation
llvm::SIInstrInfo Class Reference
#include <SIInstrInfo.h>
Public Member Functions
SIInstrInfo (const AMDGPUSubtarget &st)
const SIRegisterInfo & getRegisterInfo () const override
bool areLoadsFromSameBasePtr (SDNode *Load1, SDNode *Load2, int64_t &Offset1, int64_t &Offset2) const override
bool getLdStBaseRegImmOfs (MachineInstr *LdSt, unsigned &BaseReg, unsigned &Offset, const TargetRegisterInfo *TRI) const final
bool shouldClusterLoads (MachineInstr *FirstLdSt, MachineInstr *SecondLdSt, unsigned NumLoads) const final
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
unsigned calculateLDSSpillAddress (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, RegScavenger *RS, unsigned TmpReg, unsigned Offset, unsigned Size) const
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
bool expandPostRAPseudo (MachineBasicBlock::iterator MI) const override
unsigned getMovOpcode (const TargetRegisterClass *DstRC) const
unsigned commuteOpcode (unsigned Opcode) const
MachineInstr * commuteInstruction (MachineInstr *MI, bool NewMI=false) const override
bool findCommutedOpIndices (MachineInstr *MI, unsigned &SrcOpIdx1, unsigned &SrcOpIdx2) const override
bool isTriviallyReMaterializable (const MachineInstr *MI, AliasAnalysis *AA=nullptr) const
bool areMemAccessesTriviallyDisjoint (MachineInstr *MIa, MachineInstr *MIb, AliasAnalysis *AA=nullptr) const override
MachineInstr * buildMovInstr (MachineBasicBlock *MBB, MachineBasicBlock::iterator I, unsigned DstReg, unsigned SrcReg) const override
Build a MOV instruction.
bool isMov (unsigned Opcode) const override
bool isSafeToMoveRegClassDefs (const TargetRegisterClass *RC) const override
bool isSALU (uint16_t Opcode) const
bool isVALU (uint16_t Opcode) const
bool isSOP1 (uint16_t Opcode) const
bool isSOP2 (uint16_t Opcode) const
bool isSOPC (uint16_t Opcode) const
bool isSOPK (uint16_t Opcode) const
bool isSOPP (uint16_t Opcode) const
bool isVOP1 (uint16_t Opcode) const
bool isVOP2 (uint16_t Opcode) const
bool isVOP3 (uint16_t Opcode) const
bool isVOPC (uint16_t Opcode) const
bool isMUBUF (uint16_t Opcode) const
bool isMTBUF (uint16_t Opcode) const
bool isSMRD (uint16_t Opcode) const
bool isDS (uint16_t Opcode) const
bool isMIMG (uint16_t Opcode) const
bool isFLAT (uint16_t Opcode) const
bool isInlineConstant (const APInt &Imm) const
bool isInlineConstant (const MachineOperand &MO) const
bool isLiteralConstant (const MachineOperand &MO) const
bool isImmOperandLegal (const MachineInstr *MI, unsigned OpNo, const MachineOperand &MO) const
bool canFoldOffset (unsigned OffsetSize, unsigned AS) const
Return true if the given offset Size in bytes can be folded into the immediate offsets of a memory instruction for the given address space.
bool hasVALU32BitEncoding (unsigned Opcode) const
Return true if this 64-bit VALU instruction has a 32-bit encoding. This function will return false if you pass it a 32-bit instruction.
bool usesConstantBus (const MachineRegisterInfo &MRI, const MachineOperand &MO) const
Returns true if this operand uses the constant bus.
bool hasModifiers (unsigned Opcode) const
Return true if this instruction has any modifiers. e.g. src[012]_mod, omod, clamp.
bool hasModifiersSet (const MachineInstr &MI, unsigned OpName) const
bool verifyInstruction (const MachineInstr *MI, StringRef &ErrInfo) const override
bool isSALUOpSupportedOnVALU (const MachineInstr &MI) const
const TargetRegisterClass * getOpRegClass (const MachineInstr &MI, unsigned OpNo) const
Return the correct register class for OpNo. For target-specific instructions, this will return the register class that has been defined in tablegen. For generic instructions, like REG_SEQUENCE it will return the register class of its machine operand. to infer the correct register class base on the other operands.
bool canReadVGPR (const MachineInstr &MI, unsigned OpNo) const
void legalizeOpWithMove (MachineInstr *MI, unsigned OpIdx) const
Legalize the OpIndex operand of this instruction by inserting a MOV. For example: ADD_I32_e32 VGPR0, 15 to MOV VGPR1, 15 ADD_I32_e32 VGPR0, VGPR1.
bool isOperandLegal (const MachineInstr *MI, unsigned OpIdx, const MachineOperand *MO=nullptr) const
Check if MO is a legal operand if it was the OpIdx Operand for MI.
void legalizeOperands (MachineInstr *MI) const
Legalize all operands in this instruction. This function may create new instruction and insert them before MI.
void splitSMRD (MachineInstr *MI, const TargetRegisterClass *HalfRC, unsigned HalfImmOp, unsigned HalfSGPROp, MachineInstr *&Lo, MachineInstr *&Hi) const
Split an SMRD instruction into two smaller loads of half the.
void moveSMRDToVALU (MachineInstr *MI, MachineRegisterInfo &MRI) const
void moveToVALU (MachineInstr &MI) const
Replace this instruction's opcode with the equivalent VALU opcode. This function will also move the users of MI to the VALU if necessary.
unsigned calculateIndirectAddress (unsigned RegIndex, unsigned Channel) const override
Calculate the "Indirect Address" for the given RegIndex and Channel.
const TargetRegisterClass * getIndirectAddrRegClass () const override
MachineInstrBuilder buildIndirectWrite (MachineBasicBlock *MBB, MachineBasicBlock::iterator I, unsigned ValueReg, unsigned Address, unsigned OffsetReg) const override
Build instruction(s) for an indirect register write.
MachineInstrBuilder buildIndirectRead (MachineBasicBlock *MBB, MachineBasicBlock::iterator I, unsigned ValueReg, unsigned Address, unsigned OffsetReg) const override
Build instruction(s) for an indirect register read.
void reserveIndirectRegisters (BitVector &Reserved, const MachineFunction &MF) const
void LoadM0 (MachineInstr *MoveRel, MachineBasicBlock::iterator I, unsigned SavReg, unsigned IndexReg) const
void insertNOPs (MachineBasicBlock::iterator MI, int Count) const
MachineOperand * getNamedOperand (MachineInstr &MI, unsigned OperandName) const
Returns the operand named Op. If MI does not have an operand named Op, this function returns nullptr.
const MachineOperand * getNamedOperand (const MachineInstr &MI, unsigned OpName) const
uint64_t getDefaultRsrcDataFormat () const
Public Member Functions inherited from llvm::AMDGPUInstrInfo
AMDGPUInstrInfo (const AMDGPUSubtarget &st)
bool isCoalescableExtInstr (const MachineInstr &MI, unsigned &SrcReg, unsigned &DstReg, unsigned &SubIdx) const override
unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const override
unsigned isLoadFromStackSlotPostFE (const MachineInstr *MI, int &FrameIndex) const override
bool hasLoadFromStackSlot (const MachineInstr *MI, const MachineMemOperand *&MMO, int &FrameIndex) const override
unsigned isStoreFromStackSlot (const MachineInstr *MI, int &FrameIndex) const
unsigned isStoreFromStackSlotPostFE (const MachineInstr *MI, int &FrameIndex) const
bool hasStoreFromStackSlot (const MachineInstr *MI, const MachineMemOperand *&MMO, int &FrameIndex) const
MachineInstr * convertToThreeAddress (MachineFunction::iterator &MFI, MachineBasicBlock::iterator &MBBI, LiveVariables *LV) const override
bool expandPostRAPseudo (MachineBasicBlock::iterator MI) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
int getIndirectIndexBegin (const MachineFunction &MF) const
int getIndirectIndexEnd (const MachineFunction &MF) const
bool canFoldMemoryOperand (const MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops) const override
bool unfoldMemoryOperand (MachineFunction &MF, MachineInstr *MI, unsigned Reg, bool UnfoldLoad, bool UnfoldStore, SmallVectorImpl< MachineInstr * > &NewMIs) const override
bool unfoldMemoryOperand (SelectionDAG &DAG, SDNode *N, SmallVectorImpl< SDNode * > &NewNodes) const override
unsigned getOpcodeAfterMemoryUnfold (unsigned Opc, bool UnfoldLoad, bool UnfoldStore, unsigned *LoadRegIndex=nullptr) const override
bool enableClusterLoads () const override
bool shouldScheduleLoadsNear (SDNode *Load1, SDNode *Load2, int64_t Offset1, int64_t Offset2, unsigned NumLoads) const override
bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
void insertNoop (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
bool isPredicated (const MachineInstr *MI) const override
bool SubsumesPredicate (const SmallVectorImpl< MachineOperand > &Pred1, const SmallVectorImpl< MachineOperand > &Pred2) const override
bool DefinesPredicate (MachineInstr *MI, std::vector< MachineOperand > &Pred) const override
bool isPredicable (MachineInstr *MI) const override
bool isSafeToMoveRegClassDefs (const TargetRegisterClass *RC) const override
bool isRegisterStore (const MachineInstr &MI) const
bool isRegisterLoad (const MachineInstr &MI) const
int pseudoToMCOpcode (int Opcode) const
Return a target-specific opcode if Opcode is a pseudo instruction. Return -1 if the target-specific opcode for the pseudo instruction does not exist. If Opcode is not a pseudo instruction, this is identity.
int getMaskedMIMGOp (uint16_t Opcode, unsigned Channels) const
Given a MIMG Opcode that writes all 4 channels, return the equivalent opcode that writes Channels Channels.
Static Public Member Functions
static unsigned getVALUOp (const MachineInstr &MI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AMDGPUInstrInfo
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, int FrameIndex) const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, MachineInstr *LoadMI) const override
Protected Attributes inherited from llvm::AMDGPUInstrInfo
const AMDGPUSubtarget & ST
Detailed Description
Definition at line 25 of file SIInstrInfo.h.
Constructor & Destructor Documentation
SIInstrInfo::SIInstrInfo (const AMDGPUSubtarget & st) explicit
Definition at line 30 of file SIInstrInfo.cpp.
Member Function Documentation
bool SIInstrInfo::areLoadsFromSameBasePtr (SDNode * Load1, SDNode * Load2, int64_t & Offset1, int64_t & Offset2) const override
Definition at line 78 of file SIInstrInfo.cpp.
References assert(), findChainOperand(), llvm::SDNode::getMachineOpcode(), llvm::AMDGPU::getNamedOperandIdx(), getNumOperandsNoGlue(), llvm::SDNode::getOperand(), isDS(), llvm::SDNode::isMachineOpcode(), isMTBUF(), isMUBUF(), isSMRD(), and nodesHaveSameOperandValue().
bool SIInstrInfo::areMemAccessesTriviallyDisjoint (MachineInstr * MIa, MachineInstr * MIb, AliasAnalysis * AA = nullptr) const override
Definition at line 884 of file SIInstrInfo.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), isDS(), isFLAT(), isMTBUF(), isMUBUF(), isSMRD(), llvm::MachineInstr::mayLoad(), and llvm::MachineInstr::mayStore().
MachineInstrBuilder SIInstrInfo::buildIndirectRead (MachineBasicBlock * MBB, MachineBasicBlock::iterator I, unsigned ValueReg, unsigned Address, unsigned OffsetReg) const override virtual
Build instruction(s) for an indirect register read.
Returns
The instruction that performs the indirect register read
Implements llvm::AMDGPUInstrInfo.
Definition at line 2477 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::findDebugLoc(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), and llvm::MachineBasicBlock::getParent().
MachineInstrBuilder SIInstrInfo::buildIndirectWrite (MachineBasicBlock * MBB, MachineBasicBlock::iterator I, unsigned ValueReg, unsigned Address, unsigned OffsetReg) const override virtual
Build instruction(s) for an indirect register write.
Returns
The instruction that performs the indirect register write
Implements llvm::AMDGPUInstrInfo.
Definition at line 2459 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, llvm::MachineBasicBlock::findDebugLoc(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), and llvm::MachineBasicBlock::getParent().
MachineInstr * SIInstrInfo::buildMovInstr (MachineBasicBlock * MBB, MachineBasicBlock::iterator I, unsigned DstReg, unsigned SrcReg) const override virtual
Build a MOV instruction.
Implements llvm::AMDGPUInstrInfo.
Definition at line 820 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), and llvm::MachineBasicBlock::findDebugLoc().
unsigned SIInstrInfo::calculateIndirectAddress (unsigned RegIndex, unsigned Channel) const override virtual
Calculate the "Indirect Address" for the given RegIndex and Channel.
We model indirect addressing using a virtual address space that can be accesed with loads and stores. The "Indirect Address" is the memory address in this virtual address space that maps to the given RegIndex and Channel.
Implements llvm::AMDGPUInstrInfo.
Definition at line 2146 of file SIInstrInfo.cpp.
References assert().
unsigned SIInstrInfo::calculateLDSSpillAddress (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, RegScavenger * RS, unsigned TmpReg, unsigned FrameOffset, unsigned Size) const
Parameters
@Offset Offset in bytes of the FrameIndex being spilled
Definition at line 535 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), ShaderType::COMPUTE, DL, llvm::RegScavenger::enterBasicBlock(), llvm::MachineBasicBlock::findDebugLoc(), llvm::SIRegisterInfo::findUnusedRegister(), llvm::MachineBasicBlock::front(), llvm::MachineFunction::front(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getMaximumWorkGroupSize(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::AMDGPUMachineFunction::getShaderType(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::SIMachineFunctionInfo::getTIDReg(), llvm::SIMachineFunctionInfo::hasCalculatedTID(), llvm::SIRegisterInfo::INPUT_PTR, llvm::MachineBasicBlock::isLiveIn(), llvm::AMDGPUMachineFunction::LDSSize, llvm::SI::KernelInputOffsets::NGROUPS_Y, llvm::SI::KernelInputOffsets::NGROUPS_Z, llvm::RegScavenger::scavengeRegister(), llvm::SIMachineFunctionInfo::setTIDReg(), llvm::AMDGPUInstrInfo::ST, llvm::SIRegisterInfo::TIDIG_X, llvm::SIRegisterInfo::TIDIG_Y, and llvm::SIRegisterInfo::TIDIG_Z.
bool SIInstrInfo::canFoldOffset (unsigned OffsetSize, unsigned AS) const
Return true if the given offset Size in bytes can be folded into the immediate offsets of a memory instruction for the given address space.
Definition at line 1021 of file SIInstrInfo.cpp.
References AMDGPUAS::CONSTANT_ADDRESS, llvm::AMDGPUSubtarget::getGeneration(), AMDGPUAS::GLOBAL_ADDRESS, llvm::isUInt< 16 >(), llvm::isUInt< 8 >(), AMDGPUAS::LOCAL_ADDRESS, AMDGPUAS::PRIVATE_ADDRESS, AMDGPUAS::REGION_ADDRESS, llvm::AMDGPURegisterInfo::ST, and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
bool SIInstrInfo::canReadVGPR (const MachineInstr & MI, unsigned OpNo) const
Returns
true if it is legal for the operand at index OpNo to read a VGPR.
Definition at line 1319 of file SIInstrInfo.cpp.
References llvm::TargetOpcode::COPY, llvm::MachineInstr::getOpcode(), getOpRegClass(), llvm::SIRegisterInfo::hasVGPRs(), llvm::TargetOpcode::INSERT_SUBREG, llvm::TargetOpcode::PHI, and llvm::TargetOpcode::REG_SEQUENCE.
Referenced by moveToVALU().
MachineInstr * SIInstrInfo::commuteInstruction (MachineInstr * MI, bool NewMI = false) const override
Definition at line 709 of file SIInstrInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::TargetInstrInfo::commuteInstruction(), commuteOpcode(), llvm::MachineOperand::getImm(), getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isImm(), isOperandLegal(), llvm::MachineOperand::isReg(), isVOP2(), isVOP3(), llvm_unreachable, llvm::AArch64CC::MI, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), and llvm::MachineOperand::setSubReg().
Referenced by foldImmediates(), legalizeOperands(), and tryAddToFoldList().
unsigned SIInstrInfo::commuteOpcode (unsigned Opcode) const
Definition at line 407 of file SIInstrInfo.cpp.
References llvm::AMDGPU::getCommuteOrig(), and llvm::AMDGPU::getCommuteRev().
Referenced by commuteInstruction().
void SIInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
Definition at line 292 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), llvm::RegState::Define, llvm::getKillRegState(), llvm::RegState::Implicit, and llvm_unreachable.
bool SIInstrInfo::expandPostRAPseudo (MachineBasicBlock::iterator MI) const override
Definition at line 646 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addTargetIndex(), assert(), llvm::BuildMI(), llvm::RegState::Define, DL, llvm::MachineInstr::eraseFromParent(), llvm::AMDGPUInstrInfo::expandPostRAPseudo(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::RegState::Implicit, llvm::MachineOperand::isFPImm(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), and llvm::AMDGPU::TI_CONSTDATA_START.
bool SIInstrInfo::findCommutedOpIndices (MachineInstr * MI, unsigned & SrcOpIdx1, unsigned & SrcOpIdx2) const override
Definition at line 785 of file SIInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), hasModifiersSet(), llvm::MCInstrDesc::isCommutable(), and llvm::MachineOperand::isReg().
Referenced by tryAddToFoldList().
uint64_t SIInstrInfo::getDefaultRsrcDataFormat () const
Definition at line 2532 of file SIInstrInfo.cpp.
References llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::AMDGPU::RSRC_DATA_FORMAT, and llvm::AMDGPUInstrInfo::ST.
Referenced by llvm::SITargetLowering::buildScratchRSRC(), legalizeOperands(), moveSMRDToVALU(), and llvm::SITargetLowering::wrapAddr64Rsrc().
const TargetRegisterClass * SIInstrInfo::getIndirectAddrRegClass () const override virtual
Returns
The register class to be used for loading and storing values from an "Indirect Address" .
Implements llvm::AMDGPUInstrInfo.
Definition at line 2152 of file SIInstrInfo.cpp.
bool SIInstrInfo::getLdStBaseRegImmOfs (MachineInstr * LdSt, unsigned & BaseReg, unsigned & Offset, const TargetRegisterInfo * TRI) const final
Definition at line 182 of file SIInstrInfo.cpp.
References assert(), llvm::MachineOperand::getImm(), getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), getOpRegClass(), llvm::MachineOperand::getReg(), llvm::TargetRegisterClass::getSize(), isDS(), isMTBUF(), isMUBUF(), isSMRD(), isStride64(), llvm::MachineInstr::mayLoad(), and llvm::MachineInstr::mayStore().
unsigned SIInstrInfo::getMovOpcode (const TargetRegisterClass * DstRC) const
Definition at line 421 of file SIInstrInfo.cpp.
References llvm::TargetOpcode::COPY, llvm::TargetRegisterClass::getSize(), and llvm::SIRegisterInfo::isSGPRClass().
MachineOperand * SIInstrInfo::getNamedOperand (MachineInstr & MI, unsigned OperandName) const
Returns the operand named Op. If MI does not have an operand named Op, this function returns nullptr.
Definition at line 2523 of file SIInstrInfo.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::getOperand().
Referenced by canShrink(), commuteInstruction(), llvm::SIRegisterInfo::eliminateFrameIndex(), foldImmediates(), getLdStBaseRegImmOfs(), getNamedOperand(), hasModifiersSet(), legalizeOperands(), and splitSMRD().
const MachineOperand* llvm::SIInstrInfo::getNamedOperand (const MachineInstr & MI, unsigned OpName) const inline
Definition at line 313 of file SIInstrInfo.h.
References getNamedOperand().
const TargetRegisterClass * SIInstrInfo::getOpRegClass (const MachineInstr & MI, unsigned OpNo) const
Return the correct register class for OpNo. For target-specific instructions, this will return the register class that has been defined in tablegen. For generic instructions, like REG_SEQUENCE it will return the register class of its machine operand. to infer the correct register class base on the other operands.
Definition at line 1302 of file SIInstrInfo.cpp.
References llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineInstr::isVariadic(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::MCInstrDesc::OpInfo, and llvm::MCOperandInfo::RegClass.
Referenced by canReadVGPR(), getLdStBaseRegImmOfs(), legalizeOperands(), and moveToVALU().
const SIRegisterInfo& llvm::SIInstrInfo::getRegisterInfo () const inline override virtual
Implements llvm::AMDGPUInstrInfo.
Definition at line 71 of file SIInstrInfo.h.
Referenced by foldImmediates().
unsigned SIInstrInfo::getVALUOp (const MachineInstr & MI) static
Definition at line 1243 of file SIInstrInfo.cpp.
References llvm::TargetOpcode::COPY, llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::TargetOpcode::INSERT_SUBREG, llvm::MachineOperand::isReg(), llvm::TargetOpcode::PHI, and llvm::TargetOpcode::REG_SEQUENCE.
Referenced by isSALUOpSupportedOnVALU(), moveSMRDToVALU(), and moveToVALU().
bool SIInstrInfo::hasModifiers (unsigned Opcode) const
Return true if this instruction has any modifiers. e.g. src[012]_mod, omod, clamp.
Definition at line 1055 of file SIInstrInfo.cpp.
References llvm::AMDGPU::getNamedOperandIdx().
bool SIInstrInfo::hasModifiersSet (const MachineInstr & MI, unsigned OpName) const
Definition at line 1063 of file SIInstrInfo.cpp.
References llvm::MachineOperand::getImm(), and getNamedOperand().
Referenced by canShrink(), and findCommutedOpIndices().
bool SIInstrInfo::hasVALU32BitEncoding (unsigned Opcode) const
Return true if this 64-bit VALU instruction has a 32-bit encoding. This function will return false if you pass it a 32-bit instruction.
Definition at line 1047 of file SIInstrInfo.cpp.
References llvm::AMDGPU::getVOPe32(), and llvm::AMDGPUInstrInfo::pseudoToMCOpcode().
void SIInstrInfo::insertNOPs (MachineBasicBlock::iterator MI, int Count) const
Definition at line 632 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), and llvm::AArch64CC::MI.
Referenced by llvm::SIRegisterInfo::eliminateFrameIndex().
bool llvm::SIInstrInfo::isDS (uint16_t Opcode) const inline
Definition at line 195 of file SIInstrInfo.h.
References SIInstrFlags::DS.
Referenced by areLoadsFromSameBasePtr(), areMemAccessesTriviallyDisjoint(), getLdStBaseRegImmOfs(), and shouldClusterLoads().
bool llvm::SIInstrInfo::isFLAT (uint16_t Opcode) const inline
Definition at line 203 of file SIInstrInfo.h.
References SIInstrFlags::FLAT.
Referenced by areMemAccessesTriviallyDisjoint().
bool SIInstrInfo::isImmOperandLegal (const MachineInstr * MI, unsigned OpNo, const MachineOperand & MO) const
Definition at line 1003 of file SIInstrInfo.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), isLiteralConstant(), llvm::MachineOperand::isTargetIndex(), llvm::SIRegisterInfo::opCanUseInlineConstant(), llvm::SIRegisterInfo::opCanUseLiteralConstant(), llvm::MCOI::OPERAND_IMMEDIATE, llvm::MCOperandInfo::OperandType, and llvm::MCOperandInfo::RegClass.
Referenced by llvm::SIRegisterInfo::eliminateFrameIndex(), and isOperandLegal().
bool SIInstrInfo::isInlineConstant (const APInt & Imm) const
Definition at line 938 of file SIInstrInfo.cpp.
References llvm::DoubleToBits(), llvm::FloatToBits(), llvm::APInt::getBitWidth(), llvm::APInt::getSExtValue(), and llvm::APInt::getZExtValue().
Referenced by llvm::SITargetLowering::analyzeImmediate(), isInlineConstant(), isLiteralConstant(), llvm::SITargetLowering::shouldConvertConstantLoadToIntImm(), and verifyInstruction().
bool SIInstrInfo::isInlineConstant (const MachineOperand & MO) const
Definition at line 977 of file SIInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::isImm(), and isInlineConstant().
bool SIInstrInfo::isLiteralConstant (const MachineOperand & MO) const
Definition at line 984 of file SIInstrInfo.cpp.
References llvm::MachineOperand::isImm(), and isInlineConstant().
Referenced by foldImmediates(), isImmOperandLegal(), legalizeOperands(), usesConstantBus(), and verifyInstruction().
bool llvm::SIInstrInfo::isMIMG (uint16_t Opcode) const inline
Definition at line 199 of file SIInstrInfo.h.
References SIInstrFlags::MIMG.
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), and llvm::SITargetLowering::PostISelFolding().
bool SIInstrInfo::isMov (unsigned Opcode) const override virtual
Implements llvm::AMDGPUInstrInfo.
Definition at line 828 of file SIInstrInfo.cpp.
bool llvm::SIInstrInfo::isMTBUF (uint16_t Opcode) const inline
Definition at line 187 of file SIInstrInfo.h.
References SIInstrFlags::MTBUF.
Referenced by areLoadsFromSameBasePtr(), areMemAccessesTriviallyDisjoint(), getLdStBaseRegImmOfs(), and shouldClusterLoads().
bool llvm::SIInstrInfo::isMUBUF (uint16_t Opcode) const inline
Definition at line 183 of file SIInstrInfo.h.
References SIInstrFlags::MUBUF.
Referenced by areLoadsFromSameBasePtr(), areMemAccessesTriviallyDisjoint(), getLdStBaseRegImmOfs(), and shouldClusterLoads().
bool SIInstrInfo::isOperandLegal (const MachineInstr * MI, unsigned OpIdx, const MachineOperand * MO = nullptr) const
Check if MO is a legal operand if it was the OpIdx Operand for MI.
Definition at line 1446 of file SIInstrInfo.cpp.
References assert(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), isImmOperandLegal(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isTargetIndex(), isVALU(), llvm::MCInstrDesc::Opcode, llvm::MCInstrDesc::OpInfo, llvm::MCOperandInfo::RegClass, and usesConstantBus().
Referenced by commuteInstruction(), legalizeOperands(), and tryAddToFoldList().
bool SIInstrInfo::isSafeToMoveRegClassDefs (const TargetRegisterClass * RC) const override
Definition at line 840 of file SIInstrInfo.cpp.
bool llvm::SIInstrInfo::isSALU (uint16_t Opcode) const inline
Definition at line 139 of file SIInstrInfo.h.
References SIInstrFlags::SALU.
bool SIInstrInfo::isSALUOpSupportedOnVALU (const MachineInstr & MI) const
Definition at line 1298 of file SIInstrInfo.cpp.
References getVALUOp().
bool llvm::SIInstrInfo::isSMRD (uint16_t Opcode) const inline
Definition at line 191 of file SIInstrInfo.h.
References SIInstrFlags::SMRD.
Referenced by areLoadsFromSameBasePtr(), areMemAccessesTriviallyDisjoint(), getLdStBaseRegImmOfs(), moveToVALU(), and shouldClusterLoads().
bool llvm::SIInstrInfo::isSOP1 (uint16_t Opcode) const inline
Definition at line 147 of file SIInstrInfo.h.
References SIInstrFlags::SOP1.
bool llvm::SIInstrInfo::isSOP2 (uint16_t Opcode) const inline
Definition at line 151 of file SIInstrInfo.h.
References SIInstrFlags::SOP2.
bool llvm::SIInstrInfo::isSOPC (uint16_t Opcode) const inline
Definition at line 155 of file SIInstrInfo.h.
References SIInstrFlags::SOPC.
bool llvm::SIInstrInfo::isSOPK (uint16_t Opcode) const inline
Definition at line 159 of file SIInstrInfo.h.
References SIInstrFlags::SOPK.
bool llvm::SIInstrInfo::isSOPP (uint16_t Opcode) const inline
Definition at line 163 of file SIInstrInfo.h.
References SIInstrFlags::SOPP.
bool SIInstrInfo::isTriviallyReMaterializable (const MachineInstr * MI, AliasAnalysis * AA = nullptr) const
Definition at line 845 of file SIInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::isImm().
bool llvm::SIInstrInfo::isVALU (uint16_t Opcode) const inline
Definition at line 143 of file SIInstrInfo.h.
References SIInstrFlags::VALU.
Referenced by isOperandLegal().
bool llvm::SIInstrInfo::isVOP1 (uint16_t Opcode) const inline
Definition at line 167 of file SIInstrInfo.h.
References SIInstrFlags::VOP1.
Referenced by foldImmediates(), and verifyInstruction().
bool llvm::SIInstrInfo::isVOP2 (uint16_t Opcode) const inline
Definition at line 171 of file SIInstrInfo.h.
References SIInstrFlags::VOP2.
Referenced by commuteInstruction(), foldImmediates(), legalizeOperands(), and verifyInstruction().
bool llvm::SIInstrInfo::isVOP3 (uint16_t Opcode) const inline
Definition at line 175 of file SIInstrInfo.h.
References SIInstrFlags::VOP3.
Referenced by commuteInstruction(), legalizeOperands(), and verifyInstruction().
bool llvm::SIInstrInfo::isVOPC (uint16_t Opcode) const inline
Definition at line 179 of file SIInstrInfo.h.
References SIInstrFlags::VOPC.
Referenced by foldImmediates(), and verifyInstruction().
void SIInstrInfo::legalizeOperands (MachineInstr * MI) const
Legalize all operands in this instruction. This function may create new instruction and insert them before MI.
Definition at line 1497 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), commuteInstruction(), llvm::TargetOpcode::COPY, llvm::MachineRegisterInfo::createVirtualRegister(), llvm::AMDGPU::getAddr64Inst(), llvm::MachineInstr::getDebugLoc(), getDefaultRsrcDataFormat(), llvm::SIRegisterInfo::getEquivalentVGPRClass(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), getNamedOperand(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getOpRegClass(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SIRegisterInfo::hasVGPRs(), llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, llvm::TargetOpcode::INSERT_SUBREG, llvm::MachineInstr::isCommutable(), llvm::MachineOperand::isImm(), isLiteralConstant(), isOperandLegal(), llvm::MachineOperand::isReg(), llvm::SIRegisterInfo::isSGPRClass(), llvm::TargetRegisterInfo::isVirtualRegister(), isVOP2(), isVOP3(), legalizeOpWithMove(), llvm::AArch64CC::MI, llvm::TargetOpcode::PHI, llvm::TargetOpcode::REG_SEQUENCE, llvm::MachineInstr::removeFromParent(), and llvm::MachineOperand::setReg().
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), and moveToVALU().
void SIInstrInfo::legalizeOpWithMove (MachineInstr * MI, unsigned OpIdx) const
Legalize the OpIndex operand of this instruction by inserting a MOV. For example: ADD_I32_e32 VGPR0, 15 to MOV VGPR1, 15 ADD_I32_e32 VGPR0, VGPR1.
If the operand being legalized is a register, then a COPY will be used instead of MOV.
Definition at line 1331 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::BuildMI(), llvm::MachineOperand::ChangeToRegister(), llvm::TargetOpcode::COPY, llvm::MachineRegisterInfo::createVirtualRegister(), DL, llvm::MachineBasicBlock::findDebugLoc(), llvm::SIRegisterInfo::getEquivalentVGPRClass(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), I, llvm::MachineOperand::isReg(), llvm::SIRegisterInfo::isSGPRClass(), and llvm::AArch64CC::MI.
Referenced by legalizeOperands().
void llvm::SIInstrInfo::LoadM0 (MachineInstr * MoveRel, MachineBasicBlock::iterator I, unsigned SavReg, unsigned IndexReg) const
void SIInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 487 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::LLVMContext::emitError(), llvm::MachineBasicBlock::findDebugLoc(), llvm::Function::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterClass::getSize(), llvm::SIRegisterInfo::hasVGPRs(), llvm::TargetOpcode::IMPLICIT_DEF, llvm::SIRegisterInfo::isSGPRClass(), llvm::AMDGPUSubtarget::isVGPRSpillingEnabled(), llvm::AMDGPUInstrInfo::ST, and llvm::RegState::Undef.
void SIInstrInfo::moveSMRDToVALU (MachineInstr * MI, MachineRegisterInfo & MRI) const
Definition at line 1854 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineOperand::CreateImm(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), getDefaultRsrcDataFormat(), llvm::AMDGPUSubtarget::getGeneration(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), getVALUOp(), llvm::HexagonISD::Hi, llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::HexagonISD::Lo, llvm::TargetOpcode::REG_SEQUENCE, llvm::MachineRegisterInfo::replaceRegWith(), llvm::AMDGPUSubtarget::SEA_ISLANDS, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), splitSMRD(), and llvm::AMDGPURegisterInfo::ST.
Referenced by moveToVALU().
void SIInstrInfo::moveToVALU (MachineInstr & MI) const
Replace this instruction's opcode with the equivalent VALU opcode. This function will also move the users of MI to the VALU if necessary.
Definition at line 1954 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstr::addOperand(), assert(), llvm::BuildMI(), canReadVGPR(), llvm::TargetOpcode::COPY, llvm::MachineOperand::CreateImm(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SmallVectorBase::empty(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::SIRegisterInfo::getEquivalentVGPRClass(), llvm::AMDGPUSubtarget::getGeneration(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getOpRegClass(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), getVALUOp(), llvm::SIRegisterInfo::hasVGPRs(), I, llvm::TargetOpcode::INSERT_SUBREG, llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), isSMRD(), legalizeOperands(), llvm_unreachable, moveSMRDToVALU(), llvm::TargetOpcode::PHI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::TargetOpcode::REG_SEQUENCE, llvm::MachineInstr::RemoveOperand(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::MachineInstr::setDesc(), llvm::AMDGPUInstrInfo::ST, llvm::MachineRegisterInfo::use_begin(), llvm::MachineRegisterInfo::use_end(), and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
void SIInstrInfo::reserveIndirectRegisters (BitVector & Reserved, const MachineFunction & MF) const
Definition at line 2495 of file SIInstrInfo.cpp.
References llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), and llvm::BitVector::set().
bool SIInstrInfo::shouldClusterLoads (MachineInstr * FirstLdSt, MachineInstr * SecondLdSt, unsigned NumLoads) const final
Definition at line 269 of file SIInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), isDS(), isMTBUF(), isMUBUF(), and isSMRD().
void SIInstrInfo::splitSMRD (MachineInstr * MI, const TargetRegisterClass * HalfRC, unsigned HalfImmOp, unsigned HalfSGPROp, MachineInstr *& Lo, MachineInstr *& Hi) const
Split an SMRD instruction into two smaller loads of half the.
Definition at line 1769 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::getDebugLoc(), llvm::AMDGPUSubtarget::getGeneration(), llvm::MachineOperand::getImm(), getNamedOperand(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterClass::getSize(), llvm::isUInt< 8 >(), llvm_unreachable, llvm::TargetOpcode::REG_SEQUENCE, llvm::AMDGPURegisterInfo::ST, and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
Referenced by moveSMRDToVALU().
void SIInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 433 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::LLVMContext::emitError(), llvm::MachineBasicBlock::findDebugLoc(), llvm::Function::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterClass::getSize(), llvm::SIRegisterInfo::hasVGPRs(), llvm::SIRegisterInfo::isSGPRClass(), llvm::AMDGPUSubtarget::isVGPRSpillingEnabled(), llvm::TargetOpcode::KILL, llvm::SIMachineFunctionInfo::setHasSpilledVGPRs(), llvm::AMDGPUInstrInfo::ST, and llvm::RegState::Undef.
bool SIInstrInfo::usesConstantBus (const MachineRegisterInfo & MRI, const MachineOperand & MO) const
Returns true if this operand uses the constant bus.
Definition at line 1069 of file SIInstrInfo.cpp.
References contains(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::isImplicit(), isLiteralConstant(), llvm::MachineOperand::isReg(), llvm::SIRegisterInfo::isSGPRClass(), llvm::MachineOperand::isUse(), and llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by isOperandLegal(), and verifyInstruction().
bool SIInstrInfo::verifyInstruction (const MachineInstr * MI, StringRef & ErrInfo) const override
Definition at line 1100 of file SIInstrInfo.cpp.
References compareMachineOp(), llvm::TargetRegisterClass::contains(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isFPImm(), llvm::MachineOperand::isImm(), isInlineConstant(), isLiteralConstant(), llvm::MachineOperand::isReg(), llvm::MCInstrDesc::isVariadic(), llvm::TargetRegisterInfo::isVirtualRegister(), isVOP1(), isVOP2(), isVOP3(), isVOPC(), llvm::MCOI::OPERAND_IMMEDIATE, llvm::AMDGPU::OPERAND_REG_IMM32, llvm::AMDGPU::OPERAND_REG_INLINE_C, llvm::MCOI::OPERAND_REGISTER, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, llvm::MCOperandInfo::RegClass, and usesConstantBus().
The documentation for this class was generated from the following files:
SIInstrInfo.h
SIInstrInfo.cpp