LLVM: llvm::GraphWriter< Graph > Class Template Reference
LLVM API Documentation
llvm::GraphWriter< Graph > Class Template Reference
#include <ScheduleDAG.h>
Public Member Functions
GraphWriter (raw_ostream &o, const GraphType &g, bool SN)
void writeGraph (const std::string &Title="")
void writeHeader (const std::string &Title)
void writeFooter ()
void writeNodes ()
bool isNodeHidden (NodeType &Node)
bool isNodeHidden (NodeType *const *Node)
bool isNodeHidden (NodeType *Node)
void writeNode (NodeType &Node)
void writeNode (NodeType *const *Node)
void writeNode (NodeType *Node)
void writeEdge (NodeType *Node, unsigned edgeidx, child_iterator EI)
void emitSimpleNode (const void *ID, const std::string &Attr, const std::string &Label, unsigned NumEdgeSources=0, const std::vector< std::string > *EdgeSourceLabels=nullptr)
emitSimpleNode - Outputs a simple (non-record) node
void emitEdge (const void *SrcNodeID, int SrcNodePort, const void *DestNodeID, int DestNodePort, const std::string &Attrs)
emitEdge - Output an edge from a simple node into the graph...
raw_ostream & getOStream ()
Detailed Description
template<class Graph>
class llvm::GraphWriter< Graph >
Definition at line 41 of file ScheduleDAG.h.
Constructor & Destructor Documentation
template<class Graph> llvm::GraphWriter< Graph >::GraphWriter (raw_ostream & o, const GraphType & g, bool SN) inline
Definition at line 96 of file GraphWriter.h.
Member Function Documentation
template<class Graph> void llvm::GraphWriter< Graph >::emitEdge (const void * SrcNodeID, int SrcNodePort, const void * DestNodeID, int DestNodePort, const std::string & Attrs) inline
emitEdge - Output an edge from a simple node into the graph...
Definition at line 284 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::hasEdgeDestLabels().
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::addCustomGraphFeatures(), llvm::ScheduleDAGSDNodes::getCustomGraphFeatures(), and llvm::GraphWriter< Graph >::writeEdge().
template<class Graph> void llvm::GraphWriter< Graph >::emitSimpleNode (const void * ID, const std::string & Attr, const std::string & Label, unsigned NumEdgeSources = 0, const std::vector< std::string > * EdgeSourceLabels = nullptr) inline
emitSimpleNode - Outputs a simple (non-record) node
Definition at line 261 of file GraphWriter.h.
References llvm::DOT::EscapeString().
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::addCustomGraphFeatures(), and llvm::ScheduleDAGSDNodes::getCustomGraphFeatures().
template<class Graph> raw_ostream& llvm::GraphWriter< Graph >::getOStream () inline
getOStream - Get the raw output stream into the graph file. Useful to write fancy things using addCustomGraphFeatures().
Definition at line 304 of file GraphWriter.h.
Referenced by llvm::DOTGraphTraits< RegionInfoPass * >::addCustomGraphFeatures(), and llvm::DOTGraphTraits< RegionInfoPass * >::printRegionCluster().
template<class Graph> bool llvm::GraphWriter< Graph >::isNodeHidden (NodeType & Node) inline
Definition at line 148 of file GraphWriter.h.
Referenced by llvm::GraphWriter< Graph >::isNodeHidden(), and llvm::GraphWriter< Graph >::writeNodes().
template<class Graph> bool llvm::GraphWriter< Graph >::isNodeHidden (NodeType *const * Node) inline
Definition at line 152 of file GraphWriter.h.
References llvm::GraphWriter< Graph >::isNodeHidden().
template<class Graph> bool llvm::GraphWriter< Graph >::isNodeHidden (NodeType * Node) inline
Definition at line 156 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::isNodeHidden().
template<class Graph> void llvm::GraphWriter< Graph >::writeEdge (NodeType * Node, unsigned edgeidx, child_iterator EI) inline
Definition at line 239 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::edgeTargetsEdgeSource(), llvm::GraphWriter< Graph >::emitEdge(), llvm::DefaultDOTGraphTraits::getEdgeAttributes(), llvm::DefaultDOTGraphTraits::getEdgeSourceLabel(), and llvm::DefaultDOTGraphTraits::getEdgeTarget().
Referenced by llvm::GraphWriter< Graph >::writeNode().
template<class Graph> void llvm::GraphWriter< Graph >::writeFooter () inline
Definition at line 135 of file GraphWriter.h.
Referenced by llvm::GraphWriter< Graph >::writeGraph().
template<class Graph> void llvm::GraphWriter< Graph >::writeGraph (const std::string & Title = "") inline
Definition at line 100 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::addCustomGraphFeatures(), llvm::GraphWriter< Graph >::writeFooter(), llvm::GraphWriter< Graph >::writeHeader(), and llvm::GraphWriter< Graph >::writeNodes().
template<class Graph> void llvm::GraphWriter< Graph >::writeHeader (const std::string & Title) inline
Definition at line 114 of file GraphWriter.h.
References llvm::DOT::EscapeString(), llvm::DefaultDOTGraphTraits::getGraphName(), llvm::DefaultDOTGraphTraits::getGraphProperties(), and llvm::DefaultDOTGraphTraits::renderGraphFromBottomUp().
Referenced by llvm::GraphWriter< Graph >::writeGraph().
template<class Graph> void llvm::GraphWriter< Graph >::writeNode (NodeType & Node) inline
Definition at line 160 of file GraphWriter.h.
Referenced by llvm::GraphWriter< Graph >::writeNode(), and llvm::GraphWriter< Graph >::writeNodes().
template<class Graph> void llvm::GraphWriter< Graph >::writeNode (NodeType *const * Node) inline
Definition at line 164 of file GraphWriter.h.
References llvm::GraphWriter< Graph >::writeNode().
template<class Graph> void llvm::GraphWriter< Graph >::writeNode (NodeType * Node) inline
Definition at line 168 of file GraphWriter.h.
References llvm::DOT::EscapeString(), llvm::DefaultDOTGraphTraits::getEdgeDestLabel(), llvm::DefaultDOTGraphTraits::getNodeAttributes(), llvm::DefaultDOTGraphTraits::getNodeDescription(), llvm::DefaultDOTGraphTraits::getNodeLabel(), llvm::DefaultDOTGraphTraits::hasEdgeDestLabels(), llvm::DefaultDOTGraphTraits::hasNodeAddressLabel(), llvm::DefaultDOTGraphTraits::isNodeHidden(), Node, llvm::DefaultDOTGraphTraits::numEdgeDestLabels(), llvm::DefaultDOTGraphTraits::renderGraphFromBottomUp(), llvm::raw_string_ostream::str(), and llvm::GraphWriter< Graph >::writeEdge().
template<class Graph> void llvm::GraphWriter< Graph >::writeNodes () inline
Definition at line 140 of file GraphWriter.h.
References I, llvm::GraphWriter< Graph >::isNodeHidden(), and llvm::GraphWriter< Graph >::writeNode().
Referenced by llvm::GraphWriter< Graph >::writeGraph().
The documentation for this class was generated from the following files:
ScheduleDAG.h
GraphWriter.h