LLVM: llvm::MCRegUnitIterator Class Reference
LLVM API Documentation
llvm::MCRegUnitIterator Class Reference
#include <MCRegisterInfo.h>
Public Member Functions
MCRegUnitIterator ()
MCRegUnitIterator (unsigned Reg, const MCRegisterInfo *MCRI)
Public Member Functions inherited from llvm::MCRegisterInfo::DiffListIterator
bool isValid () const
isValid - returns true if this iterator is not yet at the end.
unsigned operator* () const
Dereference the iterator to get the value at the current position.
void operator++ ()
Pre-increment to move to the next position.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCRegisterInfo::DiffListIterator
DiffListIterator ()
Create an invalid iterator. Call init() to point to something useful.
void init (MCPhysReg InitVal, const MCPhysReg *DiffList)
unsigned advance ()
Detailed Description
Definition at line 534 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
llvm::MCRegUnitIterator::MCRegUnitIterator () inline
MCRegUnitIterator - Create an iterator that traverses the register units in Reg.
Definition at line 538 of file MCRegisterInfo.h.
llvm::MCRegUnitIterator::MCRegUnitIterator (unsigned Reg, const MCRegisterInfo * MCRI) inline
Definition at line 539 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::advance(), assert(), llvm::MCRegisterInfo::get(), llvm::MCRegisterInfo::DiffListIterator::init(), and llvm::MCRegisterDesc::RegUnits.
The documentation for this class was generated from the following file:
MCRegisterInfo.h