LLVM: llvm::ConstantPoolSDNode Class Reference
LLVM API Documentation
llvm::ConstantPoolSDNode Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
bool isMachineConstantPoolEntry () const
const Constant * getConstVal () const
MachineConstantPoolValue * getMachineCPVal () const
int getOffset () const
unsigned getAlignment () const
unsigned char getTargetFlags () const
Type * getType () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMemIntrinsic () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
iterator_range< use_iterator > uses ()
iterator_range< use_iterator > uses () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSetImpl< const SDNode * > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< SDUse > ops () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=nullptr) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printr (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printrFull (raw_ostream &O, const SelectionDAG *G=nullptr) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=nullptr, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=nullptr) const
void dumprWithDepth (const SelectionDAG *G=nullptr, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
const SDNode * getPrevNode () const
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
const SDNode * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Friends
class SelectionDAG
Additional Inherited Members
Public Types inherited from llvm::SDNode
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Protected Attributes inherited from llvm::SDNode
uint16_t SubclassData: 14
Detailed Description
Definition at line 1512 of file SelectionDAGNodes.h.
Member Function Documentation
static bool llvm::ConstantPoolSDNode::classof (const SDNode * N) inline static
Definition at line 1565 of file SelectionDAGNodes.h.
References llvm::ISD::ConstantPool, llvm::SDNode::getOpcode(), and llvm::ISD::TargetConstantPool.
unsigned llvm::ConstantPoolSDNode::getAlignment () const inline
Definition at line 1560 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), llvm::HexagonTargetLowering::LowerConstantPool(), and LowerConstantPool().
const Constant* llvm::ConstantPoolSDNode::getConstVal () const inline
Definition at line 1544 of file SelectionDAGNodes.h.
References assert().
Referenced by AddNodeIDCustom(), llvm::HexagonTargetLowering::LowerConstantPool(), and LowerConstantPool().
MachineConstantPoolValue* llvm::ConstantPoolSDNode::getMachineCPVal () const inline
Definition at line 1549 of file SelectionDAGNodes.h.
References assert().
Referenced by AddNodeIDCustom(), llvm::HexagonTargetLowering::LowerConstantPool(), and LowerConstantPool().
int llvm::ConstantPoolSDNode::getOffset () const inline
Definition at line 1554 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom().
unsigned char llvm::ConstantPoolSDNode::getTargetFlags () const inline
Definition at line 1561 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom().
Type * ConstantPoolSDNode::getType () const
Definition at line 6683 of file SelectionDAG.cpp.
References isMachineConstantPoolEntry().
bool llvm::ConstantPoolSDNode::isMachineConstantPoolEntry () const inline
Definition at line 1540 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), getType(), llvm::HexagonTargetLowering::LowerConstantPool(), and LowerConstantPool().
Friends And Related Function Documentation
friend class SelectionDAG friend
Definition at line 1520 of file SelectionDAGNodes.h.
Member Data Documentation
const Constant* llvm::ConstantPoolSDNode::ConstVal
Definition at line 1514 of file SelectionDAGNodes.h.
MachineConstantPoolValue* llvm::ConstantPoolSDNode::MachineCPVal
Definition at line 1515 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp