LLVM: llvm::MCLOHDirective Class Reference
LLVM API Documentation
llvm::MCLOHDirective Class Reference
Store Linker Optimization Hint information (LOH).
#include <MCLinkerOptimizationHint.h>
Public Types
typedef SmallVectorImpl
< MCSymbol * > LOHArgs
Public Member Functions
MCLOHDirective (MCLOHType Kind, const LOHArgs &Args)
MCLOHType getKind () const
const LOHArgs & getArgs () const
void Emit (MachObjectWriter &ObjWriter, const MCAsmLayout &Layout) const
uint64_t getEmitSize (const MachObjectWriter &ObjWriter, const MCAsmLayout &Layout) const
Detailed Description
Store Linker Optimization Hint information (LOH).
Definition at line 100 of file MCLinkerOptimizationHint.h.
Member Typedef Documentation
typedef SmallVectorImpl<MCSymbol *> llvm::MCLOHDirective::LOHArgs
Definition at line 113 of file MCLinkerOptimizationHint.h.
Constructor & Destructor Documentation
llvm::MCLOHDirective::MCLOHDirective (MCLOHType Kind, const LOHArgs & Args) inline
Definition at line 115 of file MCLinkerOptimizationHint.h.
References assert(), and llvm::isValidMCLOHType().
Member Function Documentation
void llvm::MCLOHDirective::Emit (MachObjectWriter & ObjWriter, const MCAsmLayout & Layout) const inline
Emit this directive as: <kind, numArgs, addr1, ..., addrN>
Definition at line 126 of file MCLinkerOptimizationHint.h.
References llvm::MCObjectWriter::getStream().
const LOHArgs& llvm::MCLOHDirective::getArgs () const inline
Definition at line 122 of file MCLinkerOptimizationHint.h.
uint64_t llvm::MCLOHDirective::getEmitSize (const MachObjectWriter & ObjWriter, const MCAsmLayout & Layout) const inline
Get the size in bytes of this directive if emitted in ObjWriter with the given Layout.
Definition at line 133 of file MCLinkerOptimizationHint.h.
MCLOHType llvm::MCLOHDirective::getKind () const inline
Definition at line 120 of file MCLinkerOptimizationHint.h.
The documentation for this class was generated from the following files:
MCLinkerOptimizationHint.h
MCLinkerOptimizationHint.cpp