LLVM: llvm::SpillPlacement Class Reference
LLVM API Documentation
llvm::SpillPlacement Class Reference
#include <SpillPlacement.h>
Classes
struct BlockConstraint
BlockConstraint - Entry and exit constraints for a basic block.
struct Node
Public Types
enum BorderConstraint {
DontCare, PrefReg, PrefSpill, PrefBoth,
MustSpill
}
Public Member Functions
SpillPlacement ()
~SpillPlacement ()
void prepare (BitVector &RegBundles)
void addConstraints (ArrayRef< BlockConstraint > LiveBlocks)
void addPrefSpill (ArrayRef< unsigned > Blocks, bool Strong)
addPrefSpill - Same as addConstraints(PrefSpill)
void addLinks (ArrayRef< unsigned > Links)
addLinks - Add transparent blocks with the given numbers.
bool scanActiveBundles ()
void iterate ()
ArrayRef< unsigned > getRecentPositive ()
bool finish ()
BlockFrequency getBlockFrequency (unsigned Number) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 43 of file SpillPlacement.h.
Member Enumeration Documentation
enum llvm::SpillPlacement::BorderConstraint
BorderConstraint - A basic block has separate constraints for entry and exit.
Enumerator
DontCare
Block doesn't care / variable not live.
PrefReg
Block entry/exit prefers a register.
PrefSpill
Block entry/exit prefers a stack slot.
PrefBoth
Block entry prefers both register and stack.
MustSpill
A register is impossible, variable must be spilled.
Definition at line 77 of file SpillPlacement.h.
Constructor & Destructor Documentation
llvm::SpillPlacement::SpillPlacement () inline
Definition at line 72 of file SpillPlacement.h.
llvm::SpillPlacement::~SpillPlacement () inline
Definition at line 73 of file SpillPlacement.h.
Member Function Documentation
void SpillPlacement::addConstraints (ArrayRef< BlockConstraint > LiveBlocks)
addConstraints - Add constraints and biases. This method may be called more than once to accumulate constraints.
Parameters
LiveBlocks Constraints for blocks that have the variable live in or live out.
addConstraints - Compute node biases and weights from a set of constraints. Set a bit in NodeMask for each active node.
Definition at line 242 of file SpillPlacement.cpp.
References llvm::SpillPlacement::Node::addBias(), llvm::ArrayRef< T >::begin(), DontCare, llvm::ArrayRef< T >::end(), llvm::EdgeBundles::getBundle(), I, and llvm::ARM_AM::ib.
void SpillPlacement::addLinks (ArrayRef< unsigned > Links)
addLinks - Add transparent blocks with the given numbers.
Definition at line 279 of file SpillPlacement.cpp.
References llvm::SpillPlacement::Node::addLink(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), llvm::EdgeBundles::getBundle(), I, llvm::ARM_AM::ib, llvm::SpillPlacement::Node::mustSpill(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void SpillPlacement::addPrefSpill (ArrayRef< unsigned > Blocks, bool Strong)
addPrefSpill - Same as addConstraints(PrefSpill)
addPrefSpill - Add PrefSpill constraints to all blocks listed. This is equivalent to calling addConstraint with identical BlockConstraints with Entry = Exit = PrefSpill, and ChangesValue = false.
Parameters
Blocks Array of block numbers that prefer to spill in and out.
Strong When true, double the negative bias for these blocks.
Definition at line 264 of file SpillPlacement.cpp.
References llvm::SpillPlacement::Node::addBias(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::EdgeBundles::getBundle(), I, llvm::ARM_AM::ib, and PrefSpill.
bool SpillPlacement::finish ()
finish - Compute the optimal spill code placement given the constraints. No MustSpill constraints will be violated, and the smallest possible number of PrefX constraints will be violated, weighted by expected execution frequencies. The selected bundles are returned in the bitvector passed to prepare().
Returns
True if a perfect solution was found, allowing the variable to be in a register through all relevant bundles.
Definition at line 379 of file SpillPlacement.cpp.
References assert(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), and llvm::BitVector::reset().
BlockFrequency llvm::SpillPlacement::getBlockFrequency (unsigned Number) const inline
getBlockFrequency - Return the estimated block execution frequency per function invocation.
Definition at line 149 of file SpillPlacement.h.
ArrayRef<unsigned> llvm::SpillPlacement::getRecentPositive () inline
getRecentPositive - Return an array of bundles that became positive during the previous call to scanActiveBundles or iterate.
Definition at line 136 of file SpillPlacement.h.
void SpillPlacement::iterate ()
iterate - Update the network iteratively until convergence, or new bundles are found.
iterate - Repeatedly update the Hopfield nodes until stability or the maximum number of iterations is reached.
Parameters
Linked - Numbers of linked nodes that need updating.
Definition at line 321 of file SpillPlacement.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), llvm::SmallVectorTemplateCommon< T, typename >::rend(), and llvm::SpillPlacement::Node::update().
void SpillPlacement::prepare (BitVector & RegBundles)
prepare - Reset state and prepare for a new spill placement computation.
Parameters
RegBundles Bit vector to receive the edge bundles where the variable should be kept in a register. Each bit corresponds to an edge bundle, a set bit means the variable should be kept in a register through the bundle. A clear bit means the variable should be spilled. This vector is retained.
Definition at line 369 of file SpillPlacement.cpp.
References llvm::BitVector::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::EdgeBundles::getNumBundles(), and llvm::BitVector::resize().
bool SpillPlacement::scanActiveBundles ()
scanActiveBundles - Perform an initial scan of all bundles activated by addConstraints and addLinks, updating their state. Add all the bundles that now prefer a register to RecentPositive. Prepare internal data structures for iterate. Return true is there are any positive nodes.
Definition at line 301 of file SpillPlacement.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorBase::empty(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SpillPlacement::Node::update().
Member Data Documentation
char SpillPlacement::ID = 0 static
Definition at line 70 of file SpillPlacement.h.
The documentation for this class was generated from the following files:
SpillPlacement.h
SpillPlacement.cpp