LLVM: llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > > Class Template Reference
LLVM API Documentation
llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > > Class Template Reference
#include <PointerIntPair.h>
Public Types
enum { NumLowBitsAvailable = PtrTraits::NumLowBitsAvailable - IntBits }
Static Public Member Functions
static void * getAsVoidPointer (const PointerIntPair< PointerTy, IntBits, IntType > &P)
static PointerIntPair
< PointerTy, IntBits, IntType > getFromVoidPointer (void *P)
static PointerIntPair
< PointerTy, IntBits, IntType > getFromVoidPointer (const void *P)
Detailed Description
template<typename PointerTy, unsigned IntBits, typename IntType, typename PtrTraits>
class llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >
Definition at line 183 of file PointerIntPair.h.
Member Enumeration Documentation
template<typename PointerTy , unsigned IntBits, typename IntType , typename PtrTraits > anonymous enum
Enumerator
NumLowBitsAvailable
Definition at line 198 of file PointerIntPair.h.
Member Function Documentation
template<typename PointerTy , unsigned IntBits, typename IntType , typename PtrTraits > static void* llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >::getAsVoidPointer (const PointerIntPair< PointerTy, IntBits, IntType > & P) inline static
Definition at line 187 of file PointerIntPair.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getOpaqueValue().
template<typename PointerTy , unsigned IntBits, typename IntType , typename PtrTraits > static PointerIntPair<PointerTy, IntBits, IntType> llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >::getFromVoidPointer (void * P) inline static
Definition at line 191 of file PointerIntPair.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getFromOpaqueValue().
template<typename PointerTy , unsigned IntBits, typename IntType , typename PtrTraits > static PointerIntPair<PointerTy, IntBits, IntType> llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >::getFromVoidPointer (const void * P) inline static
Definition at line 195 of file PointerIntPair.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getFromOpaqueValue().
The documentation for this class was generated from the following file:
PointerIntPair.h