LLVM: llvm::MachineInstrBuilder Class Reference
LLVM API Documentation
llvm::MachineInstrBuilder Class Reference
#include <MachineInstrBuilder.h>
Public Member Functions
MachineInstrBuilder ()
MachineInstrBuilder (MachineFunction &F, MachineInstr *I)
operator MachineInstr * () const
MachineInstr * operator-> () const
operator MachineBasicBlock::iterator () const
MachineInstr * getInstr () const
const MachineInstrBuilder & addReg (unsigned RegNo, unsigned flags=0, unsigned SubReg=0) const
const MachineInstrBuilder & addImm (int64_t Val) const
const MachineInstrBuilder & addCImm (const ConstantInt *Val) const
const MachineInstrBuilder & addFPImm (const ConstantFP *Val) const
const MachineInstrBuilder & addMBB (MachineBasicBlock *MBB, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addFrameIndex (int Idx) const
const MachineInstrBuilder & addConstantPoolIndex (unsigned Idx, int Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addTargetIndex (unsigned Idx, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addJumpTableIndex (unsigned Idx, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addGlobalAddress (const GlobalValue *GV, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addExternalSymbol (const char *FnName, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addBlockAddress (const BlockAddress *BA, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addRegMask (const uint32_t *Mask) const
const MachineInstrBuilder & addMemOperand (MachineMemOperand *MMO) const
const MachineInstrBuilder & setMemRefs (MachineInstr::mmo_iterator b, MachineInstr::mmo_iterator e) const
const MachineInstrBuilder & addOperand (const MachineOperand &MO) const
const MachineInstrBuilder & addMetadata (const MDNode *MD) const
const MachineInstrBuilder & addCFIIndex (unsigned CFIIndex) const
const MachineInstrBuilder & addSym (MCSymbol *Sym) const
const MachineInstrBuilder & setMIFlags (unsigned Flags) const
const MachineInstrBuilder & setMIFlag (MachineInstr::MIFlag Flag) const
const MachineInstrBuilder & addDisp (const MachineOperand &Disp, int64_t off, unsigned char TargetFlags=0) const
const MachineInstrBuilder & copyImplicitOps (const MachineInstr *OtherMI)
Copy all the implicit operands from OtherMI onto this one.
Detailed Description
Definition at line 45 of file MachineInstrBuilder.h.
Constructor & Destructor Documentation
llvm::MachineInstrBuilder::MachineInstrBuilder () inline
Definition at line 49 of file MachineInstrBuilder.h.
llvm::MachineInstrBuilder::MachineInstrBuilder (MachineFunction & F, MachineInstr * I) inline
Create a MachineInstrBuilder for manipulating an existing instruction. F must be the machine function that was used to allocate I.
Definition at line 53 of file MachineInstrBuilder.h.
Member Function Documentation
const MachineInstrBuilder& llvm::MachineInstrBuilder::addBlockAddress (const BlockAddress * BA, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 146 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateBA().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addCFIIndex (unsigned CFIIndex) const inline
Definition at line 182 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateCFIIndex().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addCImm (const ConstantInt * Val) const inline
Definition at line 92 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateCImm().
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::FastISel::selectIntrinsicCall().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addConstantPoolIndex (unsigned Idx, int Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 113 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateCPI().
Referenced by llvm::addConstantPoolReference(), llvm::XCoreInstrInfo::loadImmediate(), and llvm::ARMBaseInstrInfo::reMaterialize().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addDisp (const MachineOperand & Disp, int64_t off, unsigned char TargetFlags = 0) const inline
Definition at line 203 of file MachineInstrBuilder.h.
References addGlobalAddress(), addImm(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_GlobalAddress, and llvm::MachineOperand::MO_Immediate.
const MachineInstrBuilder& llvm::MachineInstrBuilder::addExternalSymbol (const char * FnName, unsigned char TargetFlags = 0) const inline
Definition at line 140 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateES().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::emitEpilogue(), emitGPDisp(), llvm::ARMFrameLowering::emitPrologue(), and llvm::ARMFrameLowering::fixTCReturn().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addFPImm (const ConstantFP * Val) const inline
Definition at line 97 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateFPImm().
Referenced by llvm::InstrEmitter::EmitDbgValue(), llvm::FastISel::fastEmitInst_rf(), and llvm::FastISel::selectIntrinsicCall().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addFrameIndex (int Idx) const inline
Definition at line 108 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateFI().
Referenced by llvm::addFrameReference(), llvm::addFullAddress(), llvm::AArch64InstrInfo::emitFrameIndexDebugValue(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), and llvm::ARMBaseInstrInfo::storeRegToStackSlot().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addGlobalAddress (const GlobalValue * GV, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 133 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateGA().
Referenced by addDisp(), llvm::addFullAddress(), llvm::X86FrameLowering::emitEpilogue(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::AArch64InstrInfo::expandPostRAPseudo(), and llvm::ARMFrameLowering::fixTCReturn().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addImm (int64_t Val) const inline
addImm - Add a new immediate operand.
Definition at line 87 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateImm().
Referenced by llvm::addConstantPoolReference(), llvm::AddDefaultPred(), llvm::addDirectMem(), addDisp(), llvm::addFrameReference(), llvm::addFullAddress(), llvm::addOffset(), llvm::addRegReg(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::Mips16InstrInfo::BuildAddiuSpImm(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::SIInstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), llvm::BuildMI(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyToCPSR(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::emitARMRegPlusImmediate(), llvm::InstrEmitter::EmitDbgValue(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AArch64InstrInfo::emitFrameIndexDebugValue(), llvm::emitFrameOffset(), emitIncrement(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostLd(), emitPostSt(), llvm::MSP430FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSPUpdate(), llvm::emitT2RegPlusImmediate(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::SparcTargetLowering::expandAtomicRMW(), expandLoadStackGuard(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_ii(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrii(), llvm::ARMFrameLowering::fixTCReturn(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), HandleVRSaveUpdate(), llvm::SparcInstrInfo::InsertBranch(), llvm::MSP430InstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::SystemZInstrInfo::InsertBranch(), insertDivByZeroTrap(), InsertFPImmInst(), InsertLDR_STR(), llvm::SIInstrInfo::insertNOPs(), llvm::AArch64InstrInfo::insertSelect(), InsertSPImmInst(), llvm::SIInstrInfo::legalizeOperands(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadImmediate(), llvm::XCoreInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::Mips16InstrInfo::makeFrame(), MakeM0Inst(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::moveSMRDToVALU(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::ARMBaseInstrInfo::reMaterialize(), replaceFI(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16InstrInfo::restoreFrame(), llvm::FastISel::selectIntrinsicCall(), llvm::FastISel::selectStackmap(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::SIInstrInfo::splitSMRD(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), tryOrrMovk(), trySequenceOfOnes(), and tryToreplicateChunks().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addJumpTableIndex (unsigned Idx, unsigned char TargetFlags = 0) const inline
Definition at line 127 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateJTI().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMBB (MachineBasicBlock * MBB, unsigned char TargetFlags = 0) const inline
Definition at line 102 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateMBB().
Referenced by llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand(), llvm::SparcInstrInfo::AnalyzeBranch(), llvm::X86InstrInfo::AnalyzeBranch(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::XCoreInstrInfo::InsertBranch(), llvm::MipsInstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::SparcInstrInfo::InsertBranch(), llvm::MSP430InstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::AArch64InstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::SystemZInstrInfo::InsertBranch(), llvm::R600InstrInfo::InsertBranch(), llvm::X86InstrInfo::InsertBranch(), and llvm::AArch64InstrInfo::optimizeCondBranch().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMemOperand (MachineMemOperand * MMO) const inline
Definition at line 158 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addMemOperand().
Referenced by llvm::addFrameReference(), llvm::XCoreFrameLowering::emitPrologue(), expandLoadStackGuard(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), InsertFPConstInst(), InsertFPImmInst(), InsertSPConstInst(), InsertSPImmInst(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), RestoreSpillList(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), and llvm::ARMBaseInstrInfo::storeRegToStackSlot().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMetadata (const MDNode * MD) const inline
Definition at line 175 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), assert(), llvm::MachineOperand::CreateMetadata(), llvm::MachineInstr::getDebugVariable(), llvm::MachineInstr::isDebugValue(), and llvm::DIVariable::Verify().
Referenced by llvm::BuildMI(), llvm::InstrEmitter::EmitDbgValue(), llvm::AArch64InstrInfo::emitFrameIndexDebugValue(), and llvm::FastISel::selectIntrinsicCall().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addOperand (const MachineOperand & MO) const inline
Definition at line 170 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand().
Referenced by llvm::SIInstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), llvm::X86InstrInfo::classifyLEAReg(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::X86FrameLowering::emitEpilogue(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), EmitMonitor(), llvm::TargetLoweringBase::emitPatchPoint(), EmitPCMPSTRI(), EmitPCMPSTRM(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), FuseInst(), FuseTwoAddrInst(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::PPCInstrInfo::InsertBranch(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::X86InstrInfo::loadRegFromAddr(), MakeM0Inst(), llvm::SIInstrInfo::moveToVALU(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::X86InstrInfo::reMaterialize(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), llvm::SIInstrInfo::splitSMRD(), llvm::X86InstrInfo::storeRegToAddr(), transferImpOps(), llvm::tryFoldSPUpdateIntoPushPop(), and llvm::X86InstrInfo::unfoldMemoryOperand().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addReg (unsigned RegNo, unsigned flags = 0, unsigned SubReg = 0) const inline
addReg - Add a new virtual register operand...
Definition at line 68 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), assert(), llvm::MachineOperand::CreateReg(), llvm::RegState::Dead, llvm::RegState::Debug, llvm::RegState::Define, llvm::RegState::EarlyClobber, llvm::RegState::Implicit, llvm::RegState::InternalRead, llvm::RegState::Kill, and llvm::RegState::Undef.
Referenced by llvm::addConstantPoolReference(), llvm::AddDefaultCC(), llvm::AddDefaultPred(), llvm::AddDefaultT1CC(), llvm::addDirectMem(), llvm::ARMBaseInstrInfo::AddDReg(), llvm::addFrameReference(), llvm::addFullAddress(), llvm::AddNoT1CC(), llvm::addOffset(), llvm::addRegOffset(), llvm::addRegReg(), addSavedGPR(), addSaveRestoreRegs(), AddSubReg(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::SIInstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), llvm::BuildMI(), llvm::SIInstrInfo::buildMovInstr(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::X86InstrInfo::classifyLEAReg(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::MSP430InstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyToCPSR(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::InstrEmitter::EmitDbgValue(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), emitPostLd(), emitPostSt(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::emitT2RegPlusImmediate(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), Expand2AddrUndef(), llvm::SparcTargetLowering::expandAtomicRMW(), expandLoadStackGuard(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), llvm::FastISel::fastEmitInst_r(), llvm::FastISel::fastEmitInst_rf(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rr(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrii(), llvm::FastISel::fastEmitInst_rrr(), llvm::ARMFrameLowering::fixTCReturn(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), forceReg(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::XCoreInstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::R600InstrInfo::InsertBranch(), insertDivByZeroTrap(), InsertFPConstInst(), InsertFPImmInst(), InsertLDR_STR(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), InsertSPConstInst(), llvm::SIInstrInfo::legalizeOperands(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadImmediate(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::Mips16InstrInfo::makeFrame(), llvm::SIInstrInfo::moveSMRDToVALU(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), replaceFI(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16InstrInfo::restoreFrame(), llvm::Thumb1RegisterInfo::saveScavengerRegister(), llvm::FastISel::selectIntrinsicCall(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::SIInstrInfo::splitSMRD(), llvm::X86InstrInfo::storeRegToAddr(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), llvm::ScheduleDAGInstrs::toggleKillFlag(), llvm::X86InstrInfo::unfoldMemoryOperand(), and UpdatePredRedefs().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addRegMask (const uint32_t * Mask) const inline
Definition at line 153 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateRegMask().
Referenced by llvm::PPCTargetLowering::emitEHSjLjSetJmp().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addSym (MCSymbol * Sym) const inline
Definition at line 187 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateMCSymbol().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addTargetIndex (unsigned Idx, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 120 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateTargetIndex().
Referenced by llvm::SIInstrInfo::expandPostRAPseudo().
const MachineInstrBuilder& llvm::MachineInstrBuilder::copyImplicitOps (const MachineInstr * OtherMI) inline
Copy all the implicit operands from OtherMI onto this one.
Definition at line 225 of file MachineInstrBuilder.h.
References llvm::MachineInstr::copyImplicitOps().
Referenced by llvm::Thumb1FrameLowering::emitEpilogue(), and llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters().
MachineInstr* llvm::MachineInstrBuilder::getInstr () const inline
If conversion operators fail, use this method to get the MachineInstr explicitly.
Definition at line 63 of file MachineInstrBuilder.h.
Referenced by expandLoadStackGuard(), and llvm::XCoreInstrInfo::loadImmediate().
llvm::MachineInstrBuilder::operator MachineBasicBlock::iterator () const inline
Definition at line 59 of file MachineInstrBuilder.h.
llvm::MachineInstrBuilder::operator MachineInstr * () const inline
Allow automatic conversion to the machine instruction we are working on.
Definition at line 57 of file MachineInstrBuilder.h.
MachineInstr* llvm::MachineInstrBuilder::operator-> () const inline
Definition at line 58 of file MachineInstrBuilder.h.
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMemRefs (MachineInstr::mmo_iterator b, MachineInstr::mmo_iterator e) const inline
Definition at line 163 of file MachineInstrBuilder.h.
References llvm::MachineInstr::setMemRefs().
Referenced by llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::X86InstrInfo::loadRegFromAddr(), and llvm::X86InstrInfo::storeRegToAddr().
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMIFlag (MachineInstr::MIFlag Flag) const inline
Definition at line 197 of file MachineInstrBuilder.h.
References llvm::MachineInstr::setFlag().
Referenced by llvm::emitFrameOffset(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMIFlags (unsigned Flags) const inline
Definition at line 192 of file MachineInstrBuilder.h.
References llvm::MachineInstr::setFlags().
Referenced by llvm::emitARMRegPlusImmediate(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::emitT2RegPlusImmediate(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
The documentation for this class was generated from the following file:
MachineInstrBuilder.h