LLVM: llvm::VarBitInit Class Reference
LLVM API Documentation
llvm::VarBitInit Class Reference
#include <Record.h>
Public Member Functions
Init * convertInitializerTo (RecTy *Ty) const override
Init * getBitVar () const override
unsigned getBitNum () const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
Init * resolveReferences (Record &R, const RecordVal *RV) const override
Init * getBit (unsigned B) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const
virtual Init * convertInitListSlice (const std::vector< unsigned > &Elements) const
virtual RecTy * getFieldType (const std::string &FieldName) const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
Static Public Member Functions
static bool classof (const Init *I)
static VarBitInit * get (TypedInit *T, unsigned B)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit, IK_FirstTypedInit, IK_BitsInit, IK_DagInit,
IK_DefInit, IK_FieldInit, IK_IntInit, IK_ListInit,
IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit, IK_UnOpInit,
IK_LastOpInit, IK_StringInit, IK_VarInit, IK_VarListElementInit,
IK_LastTypedInit, IK_UnsetInit, IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
VarBitInit - Opcode{0} - Represent access to one bit of a variable or field.
Definition at line 1102 of file Record.h.
Member Function Documentation
static bool llvm::VarBitInit::classof (const Init * I) inline static
Definition at line 1118 of file Record.h.
References llvm::Init::getKind(), and llvm::Init::IK_VarBitInit.
Init* llvm::VarBitInit::convertInitializerTo (RecTy * Ty) const inline override virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 1123 of file Record.h.
References llvm::RecTy::convertValue().
VarBitInit * VarBitInit::get (TypedInit * T, unsigned B) static
Definition at line 1412 of file Record.cpp.
References I.
Referenced by llvm::TypedInit::convertInitializerBitRange(), llvm::BitsRecTy::convertValue(), llvm::OpInit::getBit(), llvm::VarInit::getBit(), llvm::VarListElementInit::getBit(), and llvm::FieldInit::getBit().
std::string VarBitInit::getAsString () const override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1425 of file Record.cpp.
References llvm::Init::getAsString(), and llvm::utostr().
Init* llvm::VarBitInit::getBit (unsigned Bit) const inline override virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1133 of file Record.h.
References assert().
unsigned llvm::VarBitInit::getBitNum () const inline override virtual
getBitNum - This method is used to retrieve the bit number of a bit reference. For non-VarBitInit, it simply returns 0.
Reimplemented from llvm::Init.
Definition at line 1128 of file Record.h.
Referenced by resolveReferences().
Init* llvm::VarBitInit::getBitVar () const inline override virtual
getBitVar - This method is used to retrieve the initializer for bit reference. For non-VarBitInit, it simply returns itself.
Reimplemented from llvm::Init.
Definition at line 1127 of file Record.h.
Init * VarBitInit::resolveReferences (Record & R, const RecordVal * RV) const override virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1429 of file Record.cpp.
References llvm::Init::getBit(), getBitNum(), I, and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp