LLVM: llvm::MCBinaryExpr Class Reference
LLVM API Documentation
llvm::MCBinaryExpr Class Reference
MCBinaryExpr - Binary assembler expressions.
#include <MCExpr.h>
Public Types
enum Opcode {
Add, And, Div, EQ,
GT, GTE, LAnd, LOr,
LT, LTE, Mod, Mul,
NE, Or, Shl, Shr,
Sub, Xor
}
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
Accessors
Opcode getOpcode () const
getOpcode - Get the kind of this binary expression.
const MCExpr * getLHS () const
getLHS - Get the left-hand side expression of the binary operator.
const MCExpr * getRHS () const
getRHS - Get the right-hand side expression of the binary operator.
Public Member Functions inherited from llvm::MCExpr
ExprKind getKind () const
void print (raw_ostream &OS) const
void dump () const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
int64_t evaluateKnownAbsolute (const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
bool EvaluateAsValue (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
const MCSection * FindAssociatedSection () const
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const MCBinaryExpr * Create (Opcode Op, const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateAdd (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateAnd (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateDiv (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateEQ (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateGT (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateGTE (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateLAnd (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateLOr (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateLT (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateLTE (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateMod (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateMul (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateNE (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateOr (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateShl (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateShr (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateSub (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
static const MCBinaryExpr * CreateXor (const MCExpr *LHS, const MCExpr *RHS, MCContext &Ctx)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet, bool ForceVarExpansion) const
Detailed Description
MCBinaryExpr - Binary assembler expressions.
Definition at line 396 of file MCExpr.h.
Member Enumeration Documentation
enum llvm::MCBinaryExpr::Opcode
Enumerator
Add
Addition.
And
Bitwise and.
Div
Signed division.
EQ
Equality comparison.
GT
Signed greater than comparison (result is either 0 or some target-specific non-zero value)
GTE
Signed greater than or equal comparison (result is either 0 or some target-specific non-zero value).
LAnd
Logical and.
LOr
Logical or.
LT
Signed less than comparison (result is either 0 or some target-specific non-zero value).
LTE
Signed less than or equal comparison (result is either 0 or some target-specific non-zero value).
Mod
Signed remainder.
Mul
Multiplication.
NE
Inequality comparison.
Or
Bitwise or.
Shl
Shift left.
Shr
Shift right (arithmetic or logical, depending on target)
Sub
Subtraction.
Xor
Bitwise exclusive or.
Definition at line 398 of file MCExpr.h.
Member Function Documentation
static bool llvm::MCBinaryExpr::classof (const MCExpr * E) inline static
Definition at line 524 of file MCExpr.h.
References llvm::MCExpr::Binary, and llvm::MCExpr::getKind().
const MCBinaryExpr * MCBinaryExpr::Create (Opcode Op, const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) static
Definition at line 133 of file MCExpr.cpp.
Referenced by buildSymbolDiff(), CreateAdd(), CreateAnd(), CreateDiv(), CreateEQ(), CreateGT(), CreateGTE(), CreateLAnd(), CreateLOr(), CreateLT(), CreateLTE(), CreateMod(), CreateMul(), CreateNE(), CreateOr(), CreateShl(), CreateShr(), CreateSub(), CreateXor(), llvm::EmitLabelDiff(), llvm::MCObjectStreamer::EmitValueToOffset(), and MakeStartMinusEndExpr().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateAdd (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 436 of file MCExpr.h.
References Add, and Create().
Referenced by createPCXRelExprOp(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJumpTable(), emitLabelOffsetDifference(), llvm::AsmPrinter::EmitLabelPlusOffset(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::EmitSymbolRefWithOfs(), llvm::SystemZMCInstLower::getExpr(), llvm::X86_64MCAsmInfoDarwin::getExprForPersonalitySymbol(), GetSymbolRef(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), llvm::AsmPrinter::lowerConstant(), llvm::MSP430MCInstLower::LowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandDarwin(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::MCExternalSymbolizer::tryAddingSymbolicOperand().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateAnd (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 440 of file MCExpr.h.
References And, and Create().
Referenced by llvm::AsmPrinter::lowerConstant().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateDiv (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 444 of file MCExpr.h.
References Create(), and Div.
Referenced by llvm::ARMAsmPrinter::EmitJump2Table(), and llvm::AsmPrinter::lowerConstant().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateEQ (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 448 of file MCExpr.h.
References Create(), and EQ.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateGT (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 452 of file MCExpr.h.
References Create(), and GT.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateGTE (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 456 of file MCExpr.h.
References Create(), and GTE.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateLAnd (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 460 of file MCExpr.h.
References Create(), and LAnd.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateLOr (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 464 of file MCExpr.h.
References Create(), and LOr.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateLT (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 468 of file MCExpr.h.
References Create(), and LT.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateLTE (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 472 of file MCExpr.h.
References Create(), and LTE.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateMod (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 476 of file MCExpr.h.
References Create(), and Mod.
Referenced by llvm::AsmPrinter::lowerConstant().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateMul (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 480 of file MCExpr.h.
References Create(), and Mul.
Referenced by llvm::AsmPrinter::lowerConstant().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateNE (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 484 of file MCExpr.h.
References Create(), and NE.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateOr (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 488 of file MCExpr.h.
References Create(), and Or.
Referenced by llvm::AsmPrinter::lowerConstant().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateShl (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 492 of file MCExpr.h.
References Create(), and Shl.
Referenced by llvm::AsmPrinter::lowerConstant().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateShr (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 496 of file MCExpr.h.
References Create(), and Shr.
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateSub (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 500 of file MCExpr.h.
References Create(), and Sub.
Referenced by addNegOperand(), createPCXRelExprOp(), llvm::EmitAbsDifference(), llvm::AsmPrinter::EmitFunctionBody(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJump2Table(), llvm::ARMAsmPrinter::EmitJumpTable(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::AsmPrinter::EmitLabelDifference(), emitLabelOffsetDifference(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::EmitSymbolRefWithOfs(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), GetSymbolRef(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::AsmPrinter::lowerConstant(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::MCExternalSymbolizer::tryAddingSymbolicOperand().
static const MCBinaryExpr* llvm::MCBinaryExpr::CreateXor (const MCExpr * LHS, const MCExpr * RHS, MCContext & Ctx) inline static
Definition at line 504 of file MCExpr.h.
References Create(), and Xor.
Referenced by llvm::AsmPrinter::lowerConstant().
const MCExpr* llvm::MCBinaryExpr::getLHS () const inline
getLHS - Get the left-hand side expression of the binary operator.
Definition at line 517 of file MCExpr.h.
Referenced by llvm::MCExpr::EvaluateAsRelocatableImpl(), EvaluateCRExpr(), llvm::MCExpr::FindAssociatedSection(), fixELFSymbolsInTLSFixupsImpl(), hasGOTReference(), llvm::MipsMCExpr::isSupportedBinaryExpr(), isUsedIn(), llvm::MCExpr::print(), StartsWithGlobalOffsetTable(), and llvm::MCStreamer::visitUsedExpr().
Opcode llvm::MCBinaryExpr::getOpcode () const inline
getOpcode - Get the kind of this binary expression.
Definition at line 514 of file MCExpr.h.
Referenced by llvm::MCExpr::EvaluateAsRelocatableImpl(), EvaluateCRExpr(), and llvm::MCExpr::print().
const MCExpr* llvm::MCBinaryExpr::getRHS () const inline
getRHS - Get the right-hand side expression of the binary operator.
Definition at line 520 of file MCExpr.h.
Referenced by llvm::MCExpr::EvaluateAsRelocatableImpl(), EvaluateCRExpr(), llvm::MCExpr::FindAssociatedSection(), fixELFSymbolsInTLSFixupsImpl(), hasGOTReference(), llvm::MipsMCExpr::isSupportedBinaryExpr(), isUsedIn(), llvm::MCExpr::print(), StartsWithGlobalOffsetTable(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
MCExpr.h
MCExpr.cpp