LLVM: llvm::DwarfUnit Class Reference
LLVM API Documentation
llvm::DwarfUnit Class Reference abstract
#include <DwarfUnit.h>
Public Member Functions
virtual ~DwarfUnit ()
~Unit - Destructor for compile unit.
const MCSection * getSection () const
AsmPrinter * getAsmPrinter () const
unsigned getUniqueID () const
uint16_t getLanguage () const
DICompileUnit getCUNode () const
DIE & getUnitDie ()
unsigned getDebugInfoOffset () const
void setDebugInfoOffset (unsigned DbgInfoOff)
bool hasContent () const
hasContent - Return true if this compile unit has something to write out.
std::string getParentContextString (DIScope Context) const
virtual void addGlobalName (StringRef Name, DIE &Die, DIScope Context)
Add a new global name to the compile unit.
virtual void addGlobalType (DIType Ty, const DIE &Die, DIScope Context)
Add a new global type to the compile unit.
void addAccelNamespace (StringRef Name, const DIE &Die)
addAccelNamespace - Add a new name to the namespace accelerator table.
DIE * getDIE (DIDescriptor D) const
DIELoc * getDIELoc ()
getDIELoc - Returns a fresh newly allocated DIELoc.
void insertDIE (DIDescriptor Desc, DIE *D)
void addFlag (DIE &Die, dwarf::Attribute Attribute)
addFlag - Add a flag that is true to the DIE.
void addUInt (DIE &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
addUInt - Add an unsigned integer attribute data and value.
void addUInt (DIE &Block, dwarf::Form Form, uint64_t Integer)
void addSInt (DIE &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
addSInt - Add an signed integer attribute data and value.
void addSInt (DIELoc &Die, Optional< dwarf::Form > Form, int64_t Integer)
void addString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
addString - Add a string attribute data and value.
void addLabel (DIE &Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol *Label)
addLabel - Add a Dwarf label attribute data and value.
void addLabel (DIELoc &Die, dwarf::Form Form, const MCSymbol *Label)
void addSectionOffset (DIE &Die, dwarf::Attribute Attribute, uint64_t Integer)
void addOpAddress (DIELoc &Die, const MCSymbol *Label)
void addLabelDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
addLabelDelta - Add a label delta attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIE &Entry)
addDIEEntry - Add a DIE attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIEEntry *Entry)
addDIEEntry - Add a DIE attribute data and value.
void addDIETypeSignature (DIE &Die, const DwarfTypeUnit &Type)
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIELoc *Block)
addBlock - Add block data.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIEBlock *Block)
addBlock - Add block data.
void addSourceLine (DIE &Die, unsigned Line, StringRef File, StringRef Directory)
void addSourceLine (DIE &Die, DIVariable V)
void addSourceLine (DIE &Die, DIGlobalVariable G)
void addSourceLine (DIE &Die, DISubprogram SP)
void addSourceLine (DIE &Die, DIType Ty)
void addSourceLine (DIE &Die, DINameSpace NS)
void addSourceLine (DIE &Die, DIObjCProperty Ty)
void addConstantValue (DIE &Die, const MachineOperand &MO, DIType Ty)
addConstantValue - Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const ConstantInt *CI, DIType Ty)
addConstantValue - Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const APInt &Val, DIType Ty)
void addConstantValue (DIE &Die, const APInt &Val, bool Unsigned)
void addConstantValue (DIE &Die, bool Unsigned, uint64_t Val)
void addConstantFPValue (DIE &Die, const MachineOperand &MO)
addConstantFPValue - Add constant value entry in variable DIE.
void addConstantFPValue (DIE &Die, const ConstantFP *CFP)
addConstantFPValue - Add constant value entry in variable DIE.
void addTemplateParams (DIE &Buffer, DIArray TParams)
addTemplateParams - Add template parameters in buffer.
bool addRegisterOpPiece (DIELoc &TheDie, unsigned Reg, unsigned SizeInBits=0, unsigned OffsetInBits=0)
Add register operand.
bool addRegisterOffset (DIELoc &TheDie, unsigned Reg, int64_t Offset)
Add register offset.
void addBlockByrefAddress (const DbgVariable &DV, DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
void addType (DIE &Entity, DIType Ty, dwarf::Attribute Attribute=dwarf::DW_AT_type)
addType - Add a new type attribute to the specified entity.
DIE * getOrCreateNameSpace (DINameSpace NS)
getOrCreateNameSpace - Create a DIE for DINameSpace.
DIE * getOrCreateSubprogramDIE (DISubprogram SP, bool Minimal=false)
getOrCreateSubprogramDIE - Create new DIE using SP.
void applySubprogramAttributes (DISubprogram SP, DIE &SPDie, bool Minimal=false)
DIE * getOrCreateTypeDIE (const MDNode *N)
DIE * createTypeDIE (DICompositeType Ty)
getOrCreateContextDIE - Get context owner's DIE.
DIE * getOrCreateContextDIE (DIScope Context)
getOrCreateContextDIE - Get context owner's DIE.
void constructContainingTypeDIEs ()
void constructSubprogramArguments (DIE &Buffer, DITypeArray Args)
constructSubprogramArguments - Construct function argument DIEs.
DIE & createAndAddDIE (unsigned Tag, DIE &Parent, DIDescriptor N=DIDescriptor())
virtual unsigned getHeaderSize () const
virtual void emitHeader (const MCSymbol *ASectionSym) const
Emit the header for this unit, not including the initial length field.
virtual DwarfCompileUnit & getCU ()=0
void constructTypeDIE (DIE &Buffer, DICompositeType CTy)
constructTypeDIE - Construct type DIE from DICompositeType.
Protected Member Functions
DwarfUnit (unsigned UID, dwarf::Tag, DICompileUnit CU, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU)
Unit - Unit constructor.
void initSection (const MCSection *Section)
void addLocalString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
void addIndexedString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
bool applySubprogramDefinitionAttributes (DISubprogram SP, DIE &SPDie)
DIE * getOrCreateStaticMemberDIE (DIDerivedType DT)
getOrCreateStaticMemberDIE - Create new static data member DIE.
virtual unsigned getOrCreateSourceID (StringRef File, StringRef Directory)=0
template<typename T >
T resolve (DIRef< T > Ref) const
Protected Attributes
unsigned UniqueID
UniqueID - a numeric ID unique among all CUs in the module.
DICompileUnit CUNode
Node - MDNode for the compile unit.
DIE UnitDie
Unit debug information entry.
unsigned DebugInfoOffset
Offset of the UnitDie from beginning of debug info section.
AsmPrinter * Asm
Asm - Target of Dwarf emission.
DwarfDebug * DD
DwarfFile * DU
DIE * IndexTyDie
IndexTyDie - An anonymous type for index type. Owned by UnitDie.
DenseMap< const MDNode *, DIE * > MDNodeToDieMap
DenseMap< const MDNode
*, DIEEntry * > MDNodeToDIEEntryMap
std::vector< DIEBlock * > DIEBlocks
DIEBlocks - A list of all the DIEBlocks in use.
std::vector< DIELoc * > DIELocs
DIELocs - A list of all the DIELocs in use.
DenseMap< DIE *, const MDNode * > ContainingTypeMap
BumpPtrAllocator DIEValueAllocator
DIEInteger * DIEIntegerOne
const MCSection * Section
The section this unit will be emitted in.
Detailed Description
Unit - This dwarf writer support class manages information associated with a source file.
Definition at line 68 of file DwarfUnit.h.
Constructor & Destructor Documentation
DwarfUnit::DwarfUnit (unsigned UID, dwarf::Tag UnitTag, DICompileUnit CU, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU) protected
Unit - Unit constructor.
Definition at line 61 of file DwarfUnit.cpp.
References assert(), DIEIntegerOne, DIEValueAllocator, llvm::dwarf::DW_TAG_compile_unit, and llvm::dwarf::DW_TAG_type_unit.
DwarfUnit::~DwarfUnit () virtual
~Unit - Destructor for compile unit.
Definition at line 80 of file DwarfUnit.cpp.
References DIEBlocks, and DIELocs.
Member Function Documentation
void llvm::DwarfUnit::addAccelNamespace (StringRef Name, const DIE & Die)
addAccelNamespace - Add a new name to the namespace accelerator table.
void DwarfUnit::addBlock (DIE & Die, dwarf::Attribute Attribute, DIELoc * Loc)
addBlock - Add block data.
addBlock - Add block data.
Definition at line 338 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), Asm, llvm::DIELoc::BestForm(), llvm::DIELoc::ComputeSize(), DD, DIELocs, and llvm::DwarfDebug::getDwarfVersion().
Referenced by llvm::DwarfCompileUnit::addAddress(), addBlockByrefAddress(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantFPValue(), addConstantValue(), applySubprogramAttributes(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
void DwarfUnit::addBlock (DIE & Die, dwarf::Attribute Attribute, DIEBlock * Block)
addBlock - Add block data.
Definition at line 344 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), Asm, llvm::DIEBlock::BestForm(), llvm::DIEBlock::ComputeSize(), and DIEBlocks.
void DwarfUnit::addBlockByrefAddress (const DbgVariable & DV, DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
addBlockByrefAddress - Start with the address based on the location provided, and generate the DWARF information necessary to find the actual Block variable (navigating the Block struct) based on the starting location. Add the DWARF information to the die. Obsolete, please use addComplexAddress instead.
addBlockByrefAddress - Start with the address based on the location provided, and generate the DWARF information necessary to find the actual Block variable (navigating the Block struct) based on the starting location. Add the DWARF information to the die. For more information, read large comment just above here.
Definition at line 490 of file DwarfUnit.cpp.
References addBlock(), addRegisterOffset(), addRegisterOpPiece(), addUInt(), DIEValueAllocator, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_udata, llvm::dwarf::DW_OP_deref, llvm::dwarf::DW_OP_plus_uconst, llvm::dwarf::DW_TAG_pointer_type, llvm::DITypedArray< T >::getElement(), llvm::DICompositeType::getElements(), llvm::DbgVariable::getName(), llvm::DITypedArray< T >::getNumElements(), llvm::MachineLocation::getOffset(), llvm::DIType::getOffsetInBits(), llvm::MachineLocation::getReg(), llvm::DIDescriptor::getTag(), llvm::DbgVariable::getType(), llvm::DIDerivedType::getTypeDerivedFrom(), llvm::MachineLocation::isReg(), N, and resolve().
Referenced by llvm::DwarfCompileUnit::addVariableAddress().
void DwarfUnit::addConstantFPValue (DIE & Die, const MachineOperand & MO)
addConstantFPValue - Add constant value entry in variable DIE.
Definition at line 645 of file DwarfUnit.cpp.
References addBlock(), addUInt(), Asm, assert(), llvm::APFloat::bitcastToAPInt(), DIEValueAllocator, llvm::dwarf::DW_AT_const_value, llvm::dwarf::DW_FORM_data1, llvm::APInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::MachineOperand::getFPImm(), llvm::APInt::getRawData(), llvm::ConstantFP::getValueAPF(), llvm::MachineOperand::isFPImm(), and llvm::DataLayout::isLittleEndian().
Referenced by getOrCreateStaticMemberDIE().
void DwarfUnit::addConstantFPValue (DIE & Die, const ConstantFP * CFP)
addConstantFPValue - Add constant value entry in variable DIE.
Definition at line 668 of file DwarfUnit.cpp.
References addConstantValue(), llvm::APFloat::bitcastToAPInt(), and llvm::ConstantFP::getValueAPF().
void DwarfUnit::addConstantValue (DIE & Die, const MachineOperand & MO, DIType Ty)
addConstantValue - Add constant value entry in variable DIE.
Definition at line 679 of file DwarfUnit.cpp.
References assert(), DD, llvm::MachineOperand::getImm(), llvm::MachineOperand::isImm(), and isUnsignedDIType().
Referenced by addConstantFPValue(), addConstantValue(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addConstantValue (DIE & Die, const ConstantInt * CI, DIType Ty)
addConstantValue - Add constant value entry in variable DIE.
Definition at line 674 of file DwarfUnit.cpp.
References addConstantValue(), and llvm::ConstantInt::getValue().
void DwarfUnit::addConstantValue (DIE & Die, const APInt & Val, DIType Ty)
Definition at line 693 of file DwarfUnit.cpp.
References addConstantValue(), DD, and isUnsignedDIType().
void DwarfUnit::addConstantValue (DIE & Die, const APInt & Val, bool Unsigned)
Definition at line 698 of file DwarfUnit.cpp.
References addBlock(), addConstantValue(), addUInt(), Asm, DIEValueAllocator, llvm::dwarf::DW_AT_const_value, llvm::dwarf::DW_FORM_data1, llvm::APInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::APInt::getRawData(), llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), and llvm::DataLayout::isLittleEndian().
void DwarfUnit::addConstantValue (DIE & Die, bool Unsigned, uint64_t Val)
Definition at line 686 of file DwarfUnit.cpp.
References addUInt(), llvm::dwarf::DW_AT_const_value, llvm::dwarf::DW_FORM_sdata, and llvm::dwarf::DW_FORM_udata.
void DwarfUnit::addDIEEntry (DIE & Die, dwarf::Attribute Attribute, DIE & Entry)
addDIEEntry - Add a DIE attribute data and value.
addDIEEntry - Add a DIE attribute data and value.
Definition at line 295 of file DwarfUnit.cpp.
Referenced by addType(), applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
void DwarfUnit::addDIEEntry (DIE & Die, dwarf::Attribute Attribute, DIEEntry * Entry)
addDIEEntry - Add a DIE attribute data and value.
Definition at line 310 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), llvm::dwarf::DW_FORM_ref4, llvm::dwarf::DW_FORM_ref_addr, llvm::DIEEntry::getEntry(), getUnitDie(), and llvm::DIE::getUnitOrNull().
void DwarfUnit::addDIETypeSignature (DIE & Die, const DwarfTypeUnit & Type)
Definition at line 299 of file DwarfUnit.cpp.
References addFlag(), llvm::DIE::addValue(), DIEValueAllocator, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_signature, and llvm::dwarf::DW_FORM_ref_sig8.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
void DwarfUnit::addFlag (DIE & Die, dwarf::Attribute Attribute)
addFlag - Add a flag that is true to the DIE.
addFlag - Add a flag that is true.
Definition at line 174 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), DD, DIEIntegerOne, llvm::dwarf::DW_FORM_flag, llvm::dwarf::DW_FORM_flag_present, and llvm::DwarfDebug::getDwarfVersion().
Referenced by addDIETypeSignature(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), constructSubprogramArguments(), constructTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateStaticMemberDIE(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
virtual void llvm::DwarfUnit::addGlobalName (StringRef Name, DIE & Die, DIScope Context) inline virtual
Add a new global name to the compile unit.
Reimplemented in llvm::DwarfCompileUnit.
Definition at line 158 of file DwarfUnit.h.
Referenced by getOrCreateNameSpace().
virtual void llvm::DwarfUnit::addGlobalType (DIType Ty, const DIE & Die, DIScope Context) inline virtual
Add a new global type to the compile unit.
Reimplemented in llvm::DwarfCompileUnit.
Definition at line 161 of file DwarfUnit.h.
void DwarfUnit::addIndexedString (DIE & Die, dwarf::Attribute Attribute, StringRef Str) protected
Definition at line 224 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), Asm, DIEValueAllocator, DU, llvm::dwarf::DW_FORM_GNU_str_index, llvm::DwarfStringPool::getIndex(), and llvm::DwarfFile::getStringPool().
Referenced by addString().
void DwarfUnit::addLabel (DIE & Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol * Label)
addLabel - Add a Dwarf label attribute data and value.
addLabel - Add a Dwarf label attribute data and value.
Definition at line 248 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), and DIEValueAllocator.
Referenced by addLabel(), addOpAddress(), and llvm::DwarfCompileUnit::addSectionLabel().
void DwarfUnit::addLabel (DIELoc & Die, dwarf::Form Form, const MCSymbol * Label)
Definition at line 254 of file DwarfUnit.cpp.
References addLabel().
void DwarfUnit::addLabelDelta (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Hi, const MCSymbol * Lo)
addLabelDelta - Add a label delta attribute data and value.
Definition at line 287 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), DIEValueAllocator, and llvm::dwarf::DW_FORM_data4.
Referenced by llvm::DwarfCompileUnit::attachLowHighPC().
void DwarfUnit::addLocalString (DIE & Die, dwarf::Attribute Attribute, StringRef String) protected
Add a string attribute data and value.
addLocalString - Add a string attribute data and value. This is guaranteed to be in the local string pool instead of indirected.
Definition at line 234 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), Asm, DD, DIEValueAllocator, llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), DU, llvm::dwarf::DW_FORM_strp, llvm::DwarfDebug::getDebugStrSym(), llvm::DwarfFile::getStringPool(), llvm::DwarfStringPool::getSymbol(), and llvm::AsmPrinter::MAI.
Referenced by addString().
void DwarfUnit::addOpAddress (DIELoc & Die, const MCSymbol * Sym)
addOpAddress - Add a dwarf op address data and value using the form given and an op of either DW_FORM_addr or DW_FORM_GNU_addr_index.
Definition at line 276 of file DwarfUnit.cpp.
References addLabel(), addUInt(), DD, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_GNU_addr_index, llvm::dwarf::DW_FORM_udata, llvm::dwarf::DW_OP_addr, llvm::dwarf::DW_OP_GNU_addr_index, llvm::DwarfDebug::getAddressPool(), llvm::AddressPool::getIndex(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
bool DwarfUnit::addRegisterOffset (DIELoc & TheDie, unsigned Reg, int64_t Offset)
Add register offset.
addRegisterOffset - Add register offset.
Returns
false if the register does not exist, e.g., because it was never materialized.
Definition at line 424 of file DwarfUnit.cpp.
References llvm::DwarfExpression::AddMachineRegIndirect(), and Asm.
Referenced by llvm::DwarfCompileUnit::addAddress(), and addBlockByrefAddress().
bool DwarfUnit::addRegisterOpPiece (DIELoc & TheDie, unsigned Reg, unsigned SizeInBits = 0, unsigned OffsetInBits = 0)
Add register operand.
addRegisterOp - Add register operand.
Returns
false if the register does not exist, e.g., because it was never materialized.
Definition at line 416 of file DwarfUnit.cpp.
References llvm::DwarfExpression::AddMachineRegPiece(), and Asm.
Referenced by llvm::DwarfCompileUnit::addAddress(), and addBlockByrefAddress().
void DwarfUnit::addSectionOffset (DIE & Die, dwarf::Attribute Attribute, uint64_t Integer)
addSectionOffset - Add an offset into a section attribute data and value.
Definition at line 260 of file DwarfUnit.cpp.
References addUInt(), DD, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, and llvm::DwarfDebug::getDwarfVersion().
Referenced by llvm::DwarfTypeUnit::DwarfTypeUnit().
void DwarfUnit::addSInt (DIE & Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
addSInt - Add an signed integer attribute data and value.
addSInt - Add an signed integer attribute data and value.
Definition at line 198 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), llvm::DIEInteger::BestForm(), and DIEValueAllocator.
Referenced by addSInt(), and llvm::DIEDwarfExpression::EmitSigned().
void DwarfUnit::addSInt (DIELoc & Die, Optional< dwarf::Form > Form, int64_t Integer)
Definition at line 206 of file DwarfUnit.cpp.
References addSInt().
void DwarfUnit::addSourceLine (DIE & Die, unsigned Line, StringRef File, StringRef Directory)
addSourceLine - Add location information to specified debug information entry.
Definition at line 353 of file DwarfUnit.cpp.
References addUInt(), assert(), llvm::dwarf::DW_AT_decl_file, llvm::dwarf::DW_AT_decl_line, getOrCreateSourceID(), and llvm::None.
Referenced by addSourceLine(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addSourceLine (DIE & Die, DIVariable V)
addSourceLine - Add location information to specified debug information entry.
Definition at line 366 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIVariable::getContext(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::DIVariable::getLineNumber(), and llvm::DIDescriptor::isVariable().
void DwarfUnit::addSourceLine (DIE & Die, DIGlobalVariable G)
addSourceLine - Add location information to specified debug information entry.
Definition at line 375 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIGlobalVariable::getDirectory(), llvm::DIGlobalVariable::getFilename(), llvm::DIGlobalVariable::getLineNumber(), and llvm::DIDescriptor::isGlobalVariable().
void DwarfUnit::addSourceLine (DIE & Die, DISubprogram SP)
addSourceLine - Add location information to specified debug information entry.
Definition at line 383 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::DISubprogram::getLineNumber(), and llvm::DIDescriptor::isSubprogram().
void DwarfUnit::addSourceLine (DIE & Die, DIType Ty)
addSourceLine - Add location information to specified debug information entry.
Definition at line 391 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::DIType::getLineNumber(), and llvm::DIDescriptor::isType().
void DwarfUnit::addSourceLine (DIE & Die, DINameSpace NS)
addSourceLine - Add location information to specified debug information entry.
Definition at line 409 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::DINameSpace::getLineNumber(), and llvm::DINameSpace::Verify().
void DwarfUnit::addSourceLine (DIE & Die, DIObjCProperty Ty)
addSourceLine - Add location information to specified debug information entry.
Definition at line 399 of file DwarfUnit.cpp.
References addSourceLine(), assert(), llvm::ARMBuildAttrs::File, llvm::DIObjCProperty::getFile(), llvm::DIObjCProperty::getLineNumber(), and llvm::DIDescriptor::isObjCProperty().
void DwarfUnit::addString (DIE & Die, dwarf::Attribute Attribute, StringRef String)
addString - Add a string attribute data and value.
addString - Add a string attribute data and value. We always emit a reference to the string pool instead of immediate strings so that DIEs have more predictable sizes. In the case of split dwarf we emit an index into another table which gets us the static offset into the string table.
Definition at line 216 of file DwarfUnit.cpp.
References addIndexedString(), and addLocalString().
Referenced by applySubprogramAttributes(), applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addTemplateParams (DIE & Buffer, DIArray TParams)
addTemplateParams - Add template parameters in buffer.
addTemplateParams - Add template parameters into buffer.
Definition at line 728 of file DwarfUnit.cpp.
References llvm::DITypedArray< T >::getElement(), llvm::DITypedArray< T >::getNumElements(), llvm::DIDescriptor::isTemplateTypeParameter(), and llvm::DIDescriptor::isTemplateValueParameter().
Referenced by applySubprogramDefinitionAttributes(), and constructTypeDIE().
void DwarfUnit::addType (DIE & Entity, DIType Ty, dwarf::Attribute Attribute = dwarf::DW_AT_type)
addType - Add a new type attribute to the specified entity.
addType - Add a new type attribute to the specified entity. This takes and attribute parameter because DW_AT_friend attributes are also type references.
Definition at line 838 of file DwarfUnit.cpp.
References addDIEEntry(), assert(), and getOrCreateTypeDIE().
Referenced by applySubprogramAttributes(), llvm::DwarfCompileUnit::applyVariableAttributes(), constructSubprogramArguments(), constructTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addUInt (DIE & Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
addUInt - Add an unsigned integer attribute data and value.
addUInt - Add an unsigned integer attribute data and value.
Definition at line 183 of file DwarfUnit.cpp.
References llvm::DIE::addValue(), llvm::DIEInteger::BestForm(), DIEIntegerOne, and DIEValueAllocator.
Referenced by llvm::DwarfCompileUnit::addAddress(), addBlockByrefAddress(), addConstantFPValue(), addConstantValue(), addOpAddress(), addSectionOffset(), addSourceLine(), addUInt(), applySubprogramAttributes(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), constructTypeDIE(), llvm::DIEDwarfExpression::EmitOp(), llvm::DIEDwarfExpression::EmitUnsigned(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and getOrCreateStaticMemberDIE().
void DwarfUnit::addUInt (DIE & Block, dwarf::Form Form, uint64_t Integer)
Definition at line 192 of file DwarfUnit.cpp.
References addUInt().
void DwarfUnit::applySubprogramAttributes (DISubprogram SP, DIE & SPDie, bool Minimal = false)
Definition at line 1259 of file DwarfUnit.cpp.
References addBlock(), addFlag(), addSourceLine(), addString(), addType(), addUInt(), applySubprogramDefinitionAttributes(), Asm, assert(), constructSubprogramArguments(), ContainingTypeMap, llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::dwarf::DW_AT_accessibility, llvm::dwarf::DW_AT_APPLE_isa, llvm::dwarf::DW_AT_APPLE_optimized, llvm::dwarf::DW_AT_artificial, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_explicit, llvm::dwarf::DW_AT_external, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_AT_prototyped, llvm::dwarf::DW_AT_reference, llvm::dwarf::DW_AT_rvalue_reference, llvm::dwarf::DW_AT_virtuality, llvm::dwarf::DW_AT_vtable_elem_location, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_flag, llvm::dwarf::DW_FORM_udata, llvm::dwarf::DW_LANG_C89, llvm::dwarf::DW_LANG_C99, llvm::dwarf::DW_LANG_ObjC, llvm::dwarf::DW_OP_constu, llvm::dwarf::DW_TAG_subroutine_type, llvm::StringRef::empty(), llvm::DISubprogram::getContainingType(), getDIELoc(), llvm::AsmPrinter::getISAEncoding(), getLanguage(), llvm::DISubprogram::getName(), llvm::DIDescriptor::getTag(), llvm::DISubprogram::getType(), llvm::DISubroutineType::getTypeArray(), llvm::DISubprogram::getVirtualIndex(), llvm::DISubprogram::getVirtuality(), llvm::isa(), llvm::DISubprogram::isArtificial(), llvm::DISubprogram::isDefinition(), llvm::DISubprogram::isExplicit(), llvm::DISubprogram::isLocalToUnit(), llvm::DISubprogram::isLValueReference(), llvm::DISubprogram::isOptimized(), llvm::DISubprogram::isPrivate(), llvm::DISubprogram::isProtected(), llvm::DISubprogram::isPrototyped(), llvm::DISubprogram::isPublic(), llvm::DISubprogram::isRValueReference(), and resolve().
Referenced by llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), and getOrCreateSubprogramDIE().
bool DwarfUnit::applySubprogramDefinitionAttributes (DISubprogram SP, DIE & SPDie) protected
Definition at line 1226 of file DwarfUnit.cpp.
References addDIEEntry(), addString(), addTemplateParams(), assert(), llvm::dwarf::DW_AT_MIPS_linkage_name, llvm::dwarf::DW_AT_specification, llvm::StringRef::empty(), getDIE(), llvm::DISubprogram::getFunctionDeclaration(), llvm::DISubprogram::getLinkageName(), llvm::GlobalValue::getRealLinkageName(), llvm::DISubprogram::getTemplateParams(), and llvm::LinkageName.
Referenced by applySubprogramAttributes().
void DwarfUnit::constructContainingTypeDIEs ()
constructContainingTypeDIEs - Construct DIEs for types that contain vtables.
Definition at line 1426 of file DwarfUnit.cpp.
References addDIEEntry(), ContainingTypeMap, llvm::dwarf::DW_AT_containing_type, and getDIE().
void DwarfUnit::constructSubprogramArguments (DIE & Buffer, DITypeArray Args)
constructSubprogramArguments - Construct function argument DIEs.
Definition at line 949 of file DwarfUnit.cpp.
References addFlag(), addType(), assert(), createAndAddDIE(), llvm::dwarf::DW_AT_artificial, llvm::dwarf::DW_TAG_formal_parameter, llvm::dwarf::DW_TAG_unspecified_parameters, llvm::DITypedArray< T >::getElement(), llvm::DITypedArray< T >::getNumElements(), llvm::DIType::isArtificial(), N, and resolve().
Referenced by applySubprogramAttributes(), and constructTypeDIE().
void DwarfUnit::constructTypeDIE (DIE & Buffer, DICompositeType CTy)
constructTypeDIE - Construct type DIE from DICompositeType.
Definition at line 965 of file DwarfUnit.cpp.
References addDIEEntry(), addFlag(), addSourceLine(), addString(), addTemplateParams(), addType(), addUInt(), constructSubprogramArguments(), createAndAddDIE(), llvm::dwarf::DW_APPLE_PROPERTY_assign, llvm::dwarf::DW_APPLE_PROPERTY_copy, llvm::dwarf::DW_APPLE_PROPERTY_nonatomic, llvm::dwarf::DW_APPLE_PROPERTY_readonly, llvm::dwarf::DW_APPLE_PROPERTY_readwrite, llvm::dwarf::DW_APPLE_PROPERTY_retain, llvm::dwarf::DW_AT_APPLE_block, llvm::dwarf::DW_AT_APPLE_objc_complete_type, llvm::dwarf::DW_AT_APPLE_property_attribute, llvm::dwarf::DW_AT_APPLE_property_getter, llvm::dwarf::DW_AT_APPLE_property_name, llvm::dwarf::DW_AT_APPLE_property_setter, llvm::dwarf::DW_AT_APPLE_runtime_class, llvm::dwarf::DW_AT_byte_size, llvm::dwarf::DW_AT_containing_type, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_friend, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_AT_prototyped, llvm::dwarf::DW_AT_reference, llvm::dwarf::DW_AT_rvalue_reference, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_LANG_C89, llvm::dwarf::DW_LANG_C99, llvm::dwarf::DW_LANG_ObjC, llvm::dwarf::DW_TAG_array_type, llvm::dwarf::DW_TAG_class_type, llvm::dwarf::DW_TAG_enumeration_type, llvm::dwarf::DW_TAG_friend, llvm::dwarf::DW_TAG_structure_type, llvm::dwarf::DW_TAG_subroutine_type, llvm::dwarf::DW_TAG_union_type, llvm::StringRef::empty(), llvm::DICompositeType::getContainingType(), llvm::DITypedArray< T >::getElement(), llvm::DICompositeType::getElements(), getLanguage(), llvm::DIType::getName(), llvm::DITypedArray< T >::getNumElements(), llvm::DIObjCProperty::getObjCPropertyGetterName(), llvm::DIObjCProperty::getObjCPropertyName(), llvm::DIObjCProperty::getObjCPropertySetterName(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), llvm::DICompositeType::getRunTimeLang(), llvm::DIType::getSizeInBits(), llvm::DIE::getTag(), llvm::DIDescriptor::getTag(), llvm::DICompositeType::getTemplateParams(), llvm::DIObjCProperty::getType(), llvm::DISubroutineType::getTypeArray(), llvm::DIDerivedType::getTypeDerivedFrom(), llvm::DIType::isAppleBlockExtension(), llvm::DIObjCProperty::isAssignObjCProperty(), llvm::DIObjCProperty::isCopyObjCProperty(), llvm::DIDescriptor::isDerivedType(), llvm::DIType::isForwardDecl(), llvm::DIType::isLValueReference(), llvm::DIObjCProperty::isNonAtomicObjCProperty(), llvm::DIType::isObjcClassComplete(), llvm::DIDescriptor::isObjCProperty(), llvm::DIObjCProperty::isReadOnlyObjCProperty(), llvm::DIObjCProperty::isReadWriteObjCProperty(), llvm::DIObjCProperty::isRetainObjCProperty(), llvm::DIType::isRValueReference(), llvm::DIType::isStaticMember(), llvm::DIDescriptor::isSubprogram(), N, llvm::None, and resolve().
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), createTypeDIE(), and getOrCreateTypeDIE().
DIE & DwarfUnit::createAndAddDIE (unsigned Tag, DIE & Parent, DIDescriptor N = DIDescriptor())
Create a DIE with the given Tag, add the DIE to its parent, and call insertDIE if MD is not null.
Definition at line 326 of file DwarfUnit.cpp.
References llvm::DIE::addChild(), assert(), llvm::dwarf::DW_TAG_arg_variable, llvm::dwarf::DW_TAG_auto_variable, llvm::DIE::getChildren(), and insertDIE().
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), constructSubprogramArguments(), constructTypeDIE(), createTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), and getOrCreateTypeDIE().
DIE * DwarfUnit::createTypeDIE (DICompositeType Ty)
getOrCreateContextDIE - Get context owner's DIE.
Definition at line 754 of file DwarfUnit.cpp.
References constructTypeDIE(), createAndAddDIE(), llvm::DIType::getContext(), getDIE(), getOrCreateContextDIE(), llvm::DIDescriptor::getTag(), and resolve().
void DwarfUnit::emitHeader (const MCSymbol * ASectionSym) const virtual
Emit the header for this unit, not including the initial length field.
Reimplemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Definition at line 1574 of file DwarfUnit.cpp.
References llvm::MCStreamer::AddComment(), Asm, DD, llvm::AsmPrinter::EmitInt16(), llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitInt8(), llvm::AsmPrinter::EmitSectionOffset(), llvm::AsmPrinter::getDataLayout(), llvm::DwarfDebug::getDwarfVersion(), getHeaderSize(), llvm::DataLayout::getPointerSize(), llvm::DIE::getSize(), llvm::AsmPrinter::OutStreamer, and UnitDie.
Referenced by llvm::DwarfCompileUnit::emitHeader(), and llvm::DwarfTypeUnit::emitHeader().
AsmPrinter* llvm::DwarfUnit::getAsmPrinter () const inline
Definition at line 141 of file DwarfUnit.h.
References Asm.
virtual DwarfCompileUnit& llvm::DwarfUnit::getCU () pure virtual
Implemented in llvm::DwarfTypeUnit, and llvm::DwarfCompileUnit.
Referenced by getOrCreateTypeDIE().
DICompileUnit llvm::DwarfUnit::getCUNode () const inline
Definition at line 144 of file DwarfUnit.h.
References CUNode.
unsigned llvm::DwarfUnit::getDebugInfoOffset () const inline
Definition at line 147 of file DwarfUnit.h.
References DebugInfoOffset.
DIE * DwarfUnit::getDIE (DIDescriptor D) const
getDIE - Returns the debug information entry map slot for the specified debug variable. We delegate the request to DwarfDebug when the MDNode can be part of the type system, since DIEs for the type system can be shared across CUs and the mappings are kept in DwarfDebug.
getDIE - Returns the debug information entry map slot for the specified debug variable. We delegate the request to DwarfDebug when the DIE for this MDNode can be shared across CUs. The mappings will be kept in DwarfDebug for shareable DIEs.
Definition at line 156 of file DwarfUnit.cpp.
References DU, llvm::DwarfFile::getDIE(), isShareableAcrossCUs(), and MDNodeToDieMap.
Referenced by applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::collectDeadVariables(), constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), createTypeDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), getOrCreateContextDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), and getOrCreateTypeDIE().
DIELoc* llvm::DwarfUnit::getDIELoc () inline
getDIELoc - Returns a fresh newly allocated DIELoc.
Definition at line 174 of file DwarfUnit.h.
References DIEValueAllocator.
Referenced by applySubprogramAttributes().
virtual unsigned llvm::DwarfUnit::getHeaderSize () const inline virtual
Compute the size of a header for this unit, not including the initial length field.
Reimplemented in llvm::DwarfTypeUnit.
Definition at line 317 of file DwarfUnit.h.
Referenced by emitHeader(), llvm::DwarfTypeUnit::getHeaderSize(), and llvm::DwarfCompileUnit::getLength().
uint16_t llvm::DwarfUnit::getLanguage () const inline
Definition at line 143 of file DwarfUnit.h.
References CUNode, and llvm::DICompileUnit::getLanguage().
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), applySubprogramAttributes(), computeIndexValue(), constructTypeDIE(), and getParentContextString().
DIE * DwarfUnit::getOrCreateContextDIE (DIScope Context)
getOrCreateContextDIE - Get context owner's DIE.
Definition at line 742 of file DwarfUnit.cpp.
References getDIE(), getOrCreateNameSpace(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), getUnitDie(), llvm::DIDescriptor::isFile(), llvm::DIDescriptor::isNameSpace(), llvm::DIDescriptor::isSubprogram(), and llvm::DIDescriptor::isType().
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), createTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), and getOrCreateTypeDIE().
DIE * DwarfUnit::getOrCreateNameSpace (DINameSpace NS)
getOrCreateNameSpace - Create a DIE for DINameSpace.
Definition at line 1174 of file DwarfUnit.cpp.
References llvm::DwarfDebug::addAccelNamespace(), addGlobalName(), addSourceLine(), addString(), createAndAddDIE(), DD, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_TAG_namespace, llvm::StringRef::empty(), llvm::DINameSpace::getContext(), getDIE(), llvm::DINameSpace::getName(), and getOrCreateContextDIE().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), and getOrCreateContextDIE().
virtual unsigned llvm::DwarfUnit::getOrCreateSourceID (StringRef File, StringRef Directory) protected pure virtual
Look up the source ID with the given directory and source file names. If none currently exists, create a new ID and insert it in the line table.
Implemented in llvm::DwarfCompileUnit.
Referenced by addSourceLine().
DIE * DwarfUnit::getOrCreateStaticMemberDIE (DIDerivedType DT) protected
getOrCreateStaticMemberDIE - Create new static data member DIE.
getOrCreateStaticMemberDIE - Create new DIE for C++ static member.
Definition at line 1531 of file DwarfUnit.cpp.
References addConstantFPValue(), addConstantValue(), addFlag(), addSourceLine(), addString(), addType(), addUInt(), assert(), createAndAddDIE(), llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::dwarf::DW_AT_accessibility, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_external, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_FORM_data1, llvm::DIDerivedType::getConstant(), llvm::DIType::getContext(), getDIE(), llvm::DIType::getName(), getOrCreateContextDIE(), llvm::DIE::getTag(), llvm::DIDescriptor::getTag(), llvm::DIDerivedType::getTypeDerivedFrom(), llvm::DIType::isPrivate(), llvm::DIType::isProtected(), llvm::DIType::isPublic(), llvm::dwarf::isType(), resolve(), and llvm::DIDerivedType::Verify().
Referenced by constructTypeDIE(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
DIE * DwarfUnit::getOrCreateSubprogramDIE (DISubprogram SP, bool Minimal = false)
getOrCreateSubprogramDIE - Create new DIE using SP.
Definition at line 1195 of file DwarfUnit.cpp.
References applySubprogramAttributes(), createAndAddDIE(), llvm::dwarf::DW_TAG_subprogram, llvm::DISubprogram::getContext(), getDIE(), llvm::DISubprogram::getFunctionDeclaration(), getOrCreateContextDIE(), getUnitDie(), llvm::DISubprogram::isDefinition(), and resolve().
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), getOrCreateContextDIE(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
DIE * DwarfUnit::getOrCreateTypeDIE (const MDNode * TyNode)
getOrCreateTypeDIE - Find existing DIE or create new DIE for the given DIType.
Definition at line 772 of file DwarfUnit.cpp.
References llvm::DwarfDebug::addDwarfTypeUnitType(), assert(), constructTypeDIE(), createAndAddDIE(), DD, llvm::dwarf::DW_TAG_restrict_type, GenerateDwarfTypeUnits, llvm::DIType::getContext(), getCU(), getDIE(), llvm::DwarfDebug::getDwarfVersion(), llvm::DICompositeType::getIdentifier(), getOrCreateContextDIE(), llvm::DIScope::getRef(), llvm::DIDescriptor::getTag(), llvm::DIDescriptor::isBasicType(), llvm::DIDescriptor::isCompositeType(), llvm::DIDescriptor::isDerivedType(), llvm::DIType::isForwardDecl(), llvm::DIDescriptor::isType(), and resolve().
Referenced by addType(), llvm::DwarfDebug::beginModule(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructTypeDIE(), and getOrCreateContextDIE().
std::string DwarfUnit::getParentContextString (DIScope Context) const
getParentContextString - Get a string containing the language specific context for a global name.
getParentContextString - Walks the metadata parent chain in a language specific manner (using the compile unit language) and returns it as a string. This is done at the metadata level because DIEs may not currently have been added to the parent context and walking the DIEs looking for names is more expensive than walking the metadata.
Definition at line 863 of file DwarfUnit.cpp.
References llvm::dwarf::DW_LANG_C_plus_plus, llvm::StringRef::empty(), llvm::DIScope::getContext(), getLanguage(), llvm::DIScope::getName(), I, llvm::DIDescriptor::isCompileUnit(), llvm::DIDescriptor::isNameSpace(), Name, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::rbegin(), llvm::SmallVectorTemplateCommon< T >::rend(), and resolve().
Referenced by llvm::DwarfCompileUnit::addGlobalName(), and llvm::DwarfCompileUnit::addGlobalType().
const MCSection* llvm::DwarfUnit::getSection () const inline
Definition at line 135 of file DwarfUnit.h.
References assert(), and Section.
unsigned llvm::DwarfUnit::getUniqueID () const inline
Definition at line 142 of file DwarfUnit.h.
References UniqueID.
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfCompileUnit::getOrCreateSourceID(), llvm::DwarfCompileUnit::initSection(), and llvm::DwarfCompileUnit::initStmtList().
DIE& llvm::DwarfUnit::getUnitDie () inline
Definition at line 145 of file DwarfUnit.h.
References UnitDie.
Referenced by addDIEEntry(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::DwarfCompileUnit(), getOrCreateContextDIE(), and getOrCreateSubprogramDIE().
bool llvm::DwarfUnit::hasContent () const inline
hasContent - Return true if this compile unit has something to write out.
Definition at line 151 of file DwarfUnit.h.
References llvm::DIE::getChildren(), and UnitDie.
void DwarfUnit::initSection (const MCSection * Section) protected
Definition at line 1594 of file DwarfUnit.cpp.
References assert(), and Section.
Referenced by llvm::DwarfCompileUnit::initSection().
void DwarfUnit::insertDIE (DIDescriptor Desc, DIE * D)
insertDIE - Insert DIE into the map. We delegate the request to DwarfDebug when the MDNode can be part of the type system, since DIEs for the type system can be shared across CUs and the mappings are kept in DwarfDebug.
insertDIE - Insert DIE into the map. We delegate the request to DwarfDebug when the DIE for this MDNode can be shared across CUs. The mappings will be kept in DwarfDebug for shareable DIEs.
Definition at line 165 of file DwarfUnit.cpp.
References DU, llvm::DwarfFile::insertDIE(), isShareableAcrossCUs(), and MDNodeToDieMap.
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), createAndAddDIE(), and llvm::DwarfCompileUnit::DwarfCompileUnit().
template<typename T > T llvm::DwarfUnit::resolve (DIRef< T > Ref) const inline protected
resolve - Look in the DwarfDebug map for the MDNode that corresponds to the reference.
Definition at line 341 of file DwarfUnit.h.
References DD, and llvm::DwarfDebug::resolve().
Referenced by addBlockByrefAddress(), applySubprogramAttributes(), llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), constructSubprogramArguments(), constructTypeDIE(), createTypeDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateStaticMemberDIE(), getOrCreateSubprogramDIE(), getOrCreateTypeDIE(), and getParentContextString().
void llvm::DwarfUnit::setDebugInfoOffset (unsigned DbgInfoOff) inline
Definition at line 148 of file DwarfUnit.h.
References DebugInfoOffset.
Member Data Documentation
AsmPrinter* llvm::DwarfUnit::Asm protected
Asm - Target of Dwarf emission.
Definition at line 83 of file DwarfUnit.h.
Referenced by addBlock(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantFPValue(), addConstantValue(), addIndexedString(), addLocalString(), addRegisterOffset(), addRegisterOpPiece(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::DwarfCompileUnit::addSectionLabel(), applySubprogramAttributes(), llvm::DwarfCompileUnit::emitHeader(), emitHeader(), llvm::DwarfTypeUnit::emitHeader(), getAsmPrinter(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfCompileUnit::getOrCreateSourceID(), llvm::DwarfCompileUnit::initSection(), llvm::DwarfCompileUnit::initStmtList(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
DenseMap<DIE *, const MDNode *> llvm::DwarfUnit::ContainingTypeMap protected
ContainingTypeMap - This map is used to keep track of subprogram DIEs that need DW_AT_containing_type attribute. This attribute points to a DIE that corresponds to the MDNode mapped with the subprogram DIE.
Definition at line 109 of file DwarfUnit.h.
Referenced by applySubprogramAttributes(), and constructContainingTypeDIEs().
DICompileUnit llvm::DwarfUnit::CUNode protected
Node - MDNode for the compile unit.
Definition at line 74 of file DwarfUnit.h.
Referenced by getCUNode(), and getLanguage().
DwarfDebug* llvm::DwarfUnit::DD protected
Definition at line 86 of file DwarfUnit.h.
Referenced by addBlock(), addConstantValue(), addFlag(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocalLabelAddress(), addLocalString(), llvm::DwarfCompileUnit::addLocationList(), addOpAddress(), llvm::DwarfCompileUnit::addRange(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::DwarfCompileUnit::addSectionDelta(), llvm::DwarfCompileUnit::addSectionLabel(), addSectionOffset(), llvm::DwarfCompileUnit::attachLowHighPC(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::DwarfCompileUnit::collectDeadVariables(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructLexicalScopeDIE(), llvm::DwarfCompileUnit::constructScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), emitHeader(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getOrCreateNameSpace(), getOrCreateTypeDIE(), resolve(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
unsigned llvm::DwarfUnit::DebugInfoOffset protected
Offset of the UnitDie from beginning of debug info section.
Definition at line 80 of file DwarfUnit.h.
Referenced by getDebugInfoOffset(), and setDebugInfoOffset().
std::vector<DIEBlock *> llvm::DwarfUnit::DIEBlocks protected
DIEBlocks - A list of all the DIEBlocks in use.
Definition at line 101 of file DwarfUnit.h.
Referenced by addBlock(), and ~DwarfUnit().
DIEInteger* llvm::DwarfUnit::DIEIntegerOne protected
Definition at line 115 of file DwarfUnit.h.
Referenced by addFlag(), addUInt(), and DwarfUnit().
std::vector<DIELoc *> llvm::DwarfUnit::DIELocs protected
DIELocs - A list of all the DIELocs in use.
Definition at line 104 of file DwarfUnit.h.
Referenced by addBlock(), and ~DwarfUnit().
BumpPtrAllocator llvm::DwarfUnit::DIEValueAllocator protected
Definition at line 112 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), addBlockByrefAddress(), llvm::DwarfCompileUnit::addComplexAddress(), addConstantFPValue(), addConstantValue(), addDIETypeSignature(), llvm::DwarfCompileUnit::addExpr(), addIndexedString(), addLabel(), llvm::DwarfCompileUnit::addLabelAddress(), addLabelDelta(), llvm::DwarfCompileUnit::addLocalLabelAddress(), addLocalString(), llvm::DwarfCompileUnit::addLocationList(), llvm::DwarfCompileUnit::addSectionDelta(), addSInt(), addUInt(), DwarfUnit(), getDIELoc(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
DwarfFile* llvm::DwarfUnit::DU protected
Definition at line 87 of file DwarfUnit.h.
Referenced by addIndexedString(), addLocalString(), llvm::DwarfCompileUnit::collectDeadVariables(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::createScopeChildrenDIE(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), getDIE(), and insertDIE().
DIE* llvm::DwarfUnit::IndexTyDie protected
IndexTyDie - An anonymous type for index type. Owned by UnitDie.
Definition at line 90 of file DwarfUnit.h.
DenseMap<const MDNode *, DIEEntry *> llvm::DwarfUnit::MDNodeToDIEEntryMap protected
MDNodeToDIEEntryMap - Tracks the mapping of unit level debug information descriptors to debug information entries using a DIEEntry proxy.
Definition at line 98 of file DwarfUnit.h.
DenseMap<const MDNode *, DIE *> llvm::DwarfUnit::MDNodeToDieMap protected
MDNodeToDieMap - Tracks the mapping of unit level debug information variables to debug information entries.
Definition at line 94 of file DwarfUnit.h.
Referenced by getDIE(), and insertDIE().
const MCSection* llvm::DwarfUnit::Section protected
The section this unit will be emitted in.
Definition at line 118 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::getLabelBegin(), getSection(), llvm::DwarfCompileUnit::getSectionSym(), and initSection().
unsigned llvm::DwarfUnit::UniqueID protected
UniqueID - a numeric ID unique among all CUs in the module.
Definition at line 71 of file DwarfUnit.h.
Referenced by getUniqueID().
DIE llvm::DwarfUnit::UnitDie protected
Unit debug information entry.
Definition at line 77 of file DwarfUnit.h.
Referenced by llvm::DwarfCompileUnit::applyStmtList(), llvm::DwarfTypeUnit::DwarfTypeUnit(), emitHeader(), llvm::DwarfCompileUnit::getLength(), getUnitDie(), hasContent(), and llvm::DwarfCompileUnit::initStmtList().
The documentation for this class was generated from the following files:
DwarfUnit.h
DwarfUnit.cpp