LLVM: llvm::Mangler Class Reference
LLVM API Documentation
llvm::Mangler Class Reference
#include <Mangler.h>
Public Types
enum ManglerPrefixTy { Default, Private, LinkerPrivate }
Public Member Functions
Mangler (const DataLayout *DL)
void getNameWithPrefix (raw_ostream &OS, const GlobalValue *GV, bool CannotUsePrivateLabel) const
void getNameWithPrefix (SmallVectorImpl< char > &OutName, const GlobalValue *GV, bool CannotUsePrivateLabel) const
void getNameWithPrefix (raw_ostream &OS, const Twine &GVName, ManglerPrefixTy PrefixTy=Mangler::Default) const
void getNameWithPrefix (SmallVectorImpl< char > &OutName, const Twine &GVName, ManglerPrefixTy PrefixTy=Mangler::Default) const
Detailed Description
Definition at line 27 of file Mangler.h.
Member Enumeration Documentation
enum llvm::Mangler::ManglerPrefixTy
Enumerator
Default
Emit default string before each symbol.
Private
Emit "private" prefix before each symbol.
LinkerPrivate
Emit "linker private" prefix before each symbol.
Definition at line 29 of file Mangler.h.
Constructor & Destructor Documentation
llvm::Mangler::Mangler (const DataLayout * DL) inline
Definition at line 49 of file Mangler.h.
Member Function Documentation
void Mangler::getNameWithPrefix (raw_ostream & OS, const GlobalValue * GV, bool CannotUsePrivateLabel) const
Print the appropriate prefix and the specified global variable's name. If the global variable doesn't have a name, this fills in a unique name for the global.
Definition at line 93 of file Mangler.cpp.
References addByteCountSuffix(), llvm::CallingConv::C, Default, llvm::dyn_cast(), llvm::Function::getCallingConv(), llvm::Function::getFunctionType(), llvm::DataLayout::getGlobalPrefix(), llvm::Value::getName(), getNameWithPrefixx(), llvm::FunctionType::getNumParams(), hasByteCountSuffix(), llvm::DataLayout::hasMicrosoftFastStdCallMangling(), llvm::Value::hasName(), llvm::GlobalValue::hasPrivateLinkage(), llvm::Function::hasStructRetAttr(), ID, llvm::FunctionType::isVarArg(), LinkerPrivate, Name, llvm::cl::Prefix, Private, llvm::StringRef::startswith(), llvm::CallingConv::X86_FastCall, and llvm::CallingConv::X86_VectorCall.
Referenced by EmitCamlGlobal(), llvm::AsmPrinter::GetExternalSymbolSymbol(), getNameWithPrefix(), llvm::TargetMachine::getNameWithPrefix(), and GetSymbolFromOperand().
void Mangler::getNameWithPrefix (SmallVectorImpl< char > & OutName, const GlobalValue * GV, bool CannotUsePrivateLabel) const
Definition at line 153 of file Mangler.cpp.
References getNameWithPrefix().
void Mangler::getNameWithPrefix (raw_ostream & OS, const Twine & GVName, ManglerPrefixTy PrefixTy = Mangler::Default) const
Print the appropriate prefix and the specified name as the global variable name. GVName must not be empty.
Definition at line 49 of file Mangler.cpp.
References llvm::DataLayout::getGlobalPrefix(), getNameWithPrefixx(), and llvm::cl::Prefix.
void Mangler::getNameWithPrefix (SmallVectorImpl< char > & OutName, const Twine & GVName, ManglerPrefixTy PrefixTy = Mangler::Default) const
Definition at line 55 of file Mangler.cpp.
References getNameWithPrefix().
The documentation for this class was generated from the following files:
Mangler.h
Mangler.cpp