LLVM: llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy > Class Template Reference
LLVM API Documentation
llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy > Class Template Reference
#include <ScopedHashTable.h>
Public Member Functions
ScopedHashTableScope (ScopedHashTable< K, V, KInfo, AllocatorTy > &HT)
~ScopedHashTableScope ()
ScopedHashTableScope * getParentScope ()
const ScopedHashTableScope * getParentScope () const
Friends
class ScopedHashTable< K, V, KInfo, AllocatorTy >
Detailed Description
template<typename K, typename V, typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator>
class llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >
Definition at line 83 of file ScopedHashTable.h.
Constructor & Destructor Documentation
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::ScopedHashTableScope (ScopedHashTable< K, V, KInfo, AllocatorTy > & HT)
template<typename K , typename V , typename KInfo , typename Allocator > llvm::ScopedHashTableScope< K, V, KInfo, Allocator >::~ScopedHashTableScope ()
Definition at line 229 of file ScopedHashTable.h.
References assert(), llvm::ScopedHashTableVal< K, V >::Destroy(), llvm::ScopedHashTableVal< K, V >::getNextForKey(), and llvm::ScopedHashTableVal< K, V >::getNextInScope().
Member Function Documentation
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> ScopedHashTableScope* llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::getParentScope () inline
Definition at line 99 of file ScopedHashTable.h.
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> const ScopedHashTableScope* llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::getParentScope () const inline
Definition at line 100 of file ScopedHashTable.h.
Friends And Related Function Documentation
template<typename K , typename V , typename KInfo = DenseMapInfo<K>, typename AllocatorTy = MallocAllocator> friend class ScopedHashTable< K, V, KInfo, AllocatorTy > friend
Definition at line 103 of file ScopedHashTable.h.
The documentation for this class was generated from the following file:
ScopedHashTable.h