LLVM: llvm::LiveInterval Class Reference
LLVM API Documentation
llvm::LiveInterval Class Reference
#include <LiveInterval.h>
Classes
class SingleLinkedListIterator
class SubRange
Public Types
typedef LiveRange super
typedef
SingleLinkedListIterator
< SubRange > subrange_iterator
typedef
SingleLinkedListIterator
< const SubRange > const_subrange_iterator
Public Types inherited from llvm::LiveRange
typedef SmallVector< Segment, 4 > Segments
typedef SmallVector< VNInfo *, 4 > VNInfoList
typedef Segments::iterator iterator
typedef Segments::const_iterator const_iterator
typedef VNInfoList::iterator vni_iterator
typedef VNInfoList::const_iterator const_vni_iterator
Public Member Functions
LiveInterval (unsigned Reg, float Weight)
subrange_iterator subrange_begin ()
subrange_iterator subrange_end ()
const_subrange_iterator subrange_begin () const
const_subrange_iterator subrange_end () const
iterator_range< subrange_iterator > subranges ()
iterator_range
< const_subrange_iterator > subranges () const
SubRange * createSubRange (BumpPtrAllocator &Allocator, unsigned LaneMask)
SubRange * createSubRangeFrom (BumpPtrAllocator &Allocator, unsigned LaneMask, const LiveRange &CopyFrom)
bool hasSubRanges () const
Returns true if subregister liveness information is available.
void clearSubRanges ()
Removes all subregister liveness information.
void removeEmptySubRanges ()
void constructMainRangeFromSubranges (const SlotIndexes &Indexes, VNInfo::Allocator &VNIAllocator)
Construct main live range by merging the SubRanges of LI.
unsigned getSize () const
bool isSpillable () const
isSpillable - Can this interval be spilled?
void markNotSpillable ()
markNotSpillable - Mark interval as not spillable
bool operator< (const LiveInterval &other) const
void print (raw_ostream &OS) const
void dump () const
void verify (const MachineRegisterInfo *MRI=nullptr) const
Walks the interval and assert if any invariants fail to hold.
Public Member Functions inherited from llvm::LiveRange
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
vni_iterator vni_begin ()
vni_iterator vni_end ()
const_vni_iterator vni_begin () const
const_vni_iterator vni_end () const
LiveRange ()
Constructs a new LiveRange object.
LiveRange (const LiveRange &Other, BumpPtrAllocator &Allocator)
iterator advanceTo (iterator I, SlotIndex Pos)
const_iterator advanceTo (const_iterator I, SlotIndex Pos) const
iterator find (SlotIndex Pos)
const_iterator find (SlotIndex Pos) const
void clear ()
size_t size () const
bool hasAtLeastOneValue () const
bool containsOneValue () const
unsigned getNumValNums () const
VNInfo * getValNumInfo (unsigned ValNo)
const VNInfo * getValNumInfo (unsigned ValNo) const
bool containsValue (const VNInfo *VNI) const
containsValue - Returns true if VNI belongs to this range.
VNInfo * getNextValue (SlotIndex def, VNInfo::Allocator &VNInfoAllocator)
VNInfo * createDeadDef (SlotIndex Def, VNInfo::Allocator &VNInfoAllocator)
VNInfo * createValueCopy (const VNInfo *orig, VNInfo::Allocator &VNInfoAllocator)
void RenumberValues ()
VNInfo * MergeValueNumberInto (VNInfo *V1, VNInfo *V2)
void MergeSegmentsInAsValue (const LiveRange &RHS, VNInfo *LHSValNo)
void MergeValueInAsValue (const LiveRange &RHS, const VNInfo *RHSValNo, VNInfo *LHSValNo)
bool empty () const
SlotIndex beginIndex () const
beginIndex - Return the lowest numbered slot covered.
SlotIndex endIndex () const
bool expiredAt (SlotIndex index) const
bool liveAt (SlotIndex index) const
const Segment * getSegmentContaining (SlotIndex Idx) const
Segment * getSegmentContaining (SlotIndex Idx)
VNInfo * getVNInfoAt (SlotIndex Idx) const
getVNInfoAt - Return the VNInfo that is live at Idx, or NULL.
VNInfo * getVNInfoBefore (SlotIndex Idx) const
iterator FindSegmentContaining (SlotIndex Idx)
const_iterator FindSegmentContaining (SlotIndex Idx) const
bool overlaps (const LiveRange &other) const
bool overlaps (const LiveRange &Other, const CoalescerPair &CP, const SlotIndexes &) const
bool overlaps (SlotIndex Start, SlotIndex End) const
bool overlapsFrom (const LiveRange &Other, const_iterator I) const
bool covers (const LiveRange &Other) const
iterator addSegment (Segment S)
VNInfo * extendInBlock (SlotIndex StartIdx, SlotIndex Kill)
void join (LiveRange &Other, const int *ValNoAssignments, const int *RHSValNoAssignments, SmallVectorImpl< VNInfo * > &NewVNInfo)
bool isLocal (SlotIndex Start, SlotIndex End) const
void removeSegment (SlotIndex Start, SlotIndex End, bool RemoveDeadValNo=false)
void removeSegment (Segment S, bool RemoveDeadValNo=false)
iterator removeSegment (iterator I)
LiveQueryResult Query (SlotIndex Idx) const
void removeValNo (VNInfo *ValNo)
bool isZeroLength (SlotIndexes *Indexes) const
bool operator< (const LiveRange &other) const
void print (raw_ostream &OS) const
void dump () const
void verify () const
Walk the range and assert if any invariants fail to hold.
Public Attributes
const unsigned reg
float weight
Public Attributes inherited from llvm::LiveRange
Segments segments
VNInfoList valnos
Additional Inherited Members
Protected Member Functions inherited from llvm::LiveRange
void append (const LiveRange::Segment S)
Append a segment to the list of segments.
Detailed Description
LiveInterval - This class represents the liveness of a register, or stack slot.
Definition at line 575 of file LiveInterval.h.
Member Typedef Documentation
typedef SingleLinkedListIterator<const SubRange> llvm::LiveInterval::const_subrange_iterator
Definition at line 645 of file LiveInterval.h.
typedef SingleLinkedListIterator<SubRange> llvm::LiveInterval::subrange_iterator
Definition at line 637 of file LiveInterval.h.
typedef LiveRange llvm::LiveInterval::super
Definition at line 577 of file LiveInterval.h.
Constructor & Destructor Documentation
llvm::LiveInterval::LiveInterval (unsigned Reg, float Weight) inline
Definition at line 606 of file LiveInterval.h.
Member Function Documentation
void llvm::LiveInterval::clearSubRanges () inline
Removes all subregister liveness information.
Definition at line 684 of file LiveInterval.h.
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute().
void LiveInterval::constructMainRangeFromSubranges (const SlotIndexes & Indexes, VNInfo::Allocator & VNIAllocator)
Construct main live range by merging the SubRanges of LI.
Definition at line 672 of file LiveInterval.cpp.
References llvm::LiveRange::append(), assert(), determineMissingVNIs(), llvm::SmallVectorBase::empty(), llvm::LiveRange::Segment::end, llvm::LiveRange::end(), llvm::SlotIndexes::getMBBEndIdx(), llvm::SlotIndexes::getMBBFromIndex(), llvm::LiveRange::getNextValue(), llvm::LiveRange::getVNInfoBefore(), hasSubRanges(), I, llvm::SlotIndex::isBlock(), llvm::SlotIndex::isValid(), llvm::LiveInterval::SubRange::LaneMask, llvm::MachineBasicBlock::predecessors(), llvm::LiveRange::segments, llvm::LiveRange::Segment::start, subranges(), llvm::LiveRange::Segment::valno, llvm::LiveRange::valnos, and llvm::LiveRange::verify().
Referenced by llvm::LiveRangeCalc::calculate().
SubRange* llvm::LiveInterval::createSubRange (BumpPtrAllocator & Allocator, unsigned LaneMask) inline
Creates a new empty subregister live range. The range is added at the beginning of the subrange list; subrange iterators stay valid.
Definition at line 663 of file LiveInterval.h.
Referenced by llvm::LiveRangeCalc::calculate().
SubRange* llvm::LiveInterval::createSubRangeFrom (BumpPtrAllocator & Allocator, unsigned LaneMask, const LiveRange & CopyFrom) inline
Like createSubRange() but the new range is filled with a copy of the liveness information in CopyFrom.
Definition at line 671 of file LiveInterval.h.
Referenced by llvm::LiveRangeCalc::calculate().
void LiveInterval::dump () const
Definition at line 884 of file LiveInterval.cpp.
References llvm::dbgs().
unsigned LiveInterval::getSize () const
getSize - Returns the sum of sizes of all the LiveRange's.
Definition at line 823 of file LiveInterval.cpp.
References llvm::LiveRange::segments.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint().
bool llvm::LiveInterval::hasSubRanges () const inline
Returns true if subregister liveness information is available.
Definition at line 679 of file LiveInterval.h.
Referenced by llvm::LiveRangeCalc::calculate(), constructMainRangeFromSubranges(), foreachUnit(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
bool llvm::LiveInterval::isSpillable () const inline
isSpillable - Can this interval be spilled?
Definition at line 701 of file LiveInterval.h.
References llvm::huge_valf, and weight.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint().
void llvm::LiveInterval::markNotSpillable () inline
markNotSpillable - Mark interval as not spillable
Definition at line 706 of file LiveInterval.h.
References llvm::huge_valf, and weight.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint().
bool llvm::LiveInterval::operator< (const LiveInterval & other) const inline
Definition at line 710 of file LiveInterval.h.
References llvm::LiveRange::beginIndex(), and reg.
void LiveInterval::print (raw_ostream & OS) const
Definition at line 870 of file LiveInterval.cpp.
References llvm::format().
Referenced by llvm::operator<<().
void LiveInterval::removeEmptySubRanges ()
Removes all subranges without any segments (subranges without segments are not considered valid and should only exist temporarily).
Definition at line 601 of file LiveInterval.cpp.
References llvm::LiveRange::empty(), I, and llvm::LiveInterval::SubRange::Next.
Referenced by llvm::LiveRangeCalc::calculate().
subrange_iterator llvm::LiveInterval::subrange_begin () inline
Definition at line 638 of file LiveInterval.h.
Referenced by subranges().
const_subrange_iterator llvm::LiveInterval::subrange_begin () const inline
Definition at line 646 of file LiveInterval.h.
subrange_iterator llvm::LiveInterval::subrange_end () inline
Definition at line 641 of file LiveInterval.h.
Referenced by subranges().
const_subrange_iterator llvm::LiveInterval::subrange_end () const inline
Definition at line 649 of file LiveInterval.h.
iterator_range<subrange_iterator> llvm::LiveInterval::subranges () inline
Definition at line 653 of file LiveInterval.h.
References llvm::make_range(), subrange_begin(), and subrange_end().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::LiveRangeCalc::calculate(), constructMainRangeFromSubranges(), foreachUnit(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::LiveIntervals::shrinkToUses(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
iterator_range<const_subrange_iterator> llvm::LiveInterval::subranges () const inline
Definition at line 657 of file LiveInterval.h.
References llvm::make_range(), subrange_begin(), and subrange_end().
void LiveInterval::verify (const MachineRegisterInfo * MRI = nullptr) const
Walks the interval and assert if any invariants fail to hold.
Note that this is a no-op when asserts are disabled.
Definition at line 906 of file LiveInterval.cpp.
References assert(), llvm::LiveRange::covers(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), and verify.
Member Data Documentation
const unsigned llvm::LiveInterval::reg
Definition at line 603 of file LiveInterval.h.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), llvm::LiveRegMatrix::assign(), llvm::LiveRangeCalc::calculate(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), llvm::LiveRegMatrix::checkRegMaskInterference(), llvm::LiveRegMatrix::checkRegUnitInterference(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::LiveRangeEdit::getReg(), llvm::SplitAnalysis::isOriginalEndpoint(), operator<(), llvm::LiveIntervals::shrinkToUses(), and llvm::LiveRegMatrix::unassign().
float llvm::LiveInterval::weight
Definition at line 604 of file LiveInterval.h.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), isSpillable(), markNotSpillable(), and false::IntervalSorter::operator()().
The documentation for this class was generated from the following files:
LiveInterval.h
LiveInterval.cpp