LLVM: llvm::SparcMachineFunctionInfo Class Reference
LLVM API Documentation
llvm::SparcMachineFunctionInfo Class Reference
#include <SparcMachineFunctionInfo.h>
Public Member Functions
SparcMachineFunctionInfo ()
SparcMachineFunctionInfo (MachineFunction &MF)
unsigned getGlobalBaseReg () const
void setGlobalBaseReg (unsigned Reg)
int getVarArgsFrameOffset () const
void setVarArgsFrameOffset (int Offset)
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
void setLeafProc (bool rhs)
bool isLeafProc () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Definition at line 20 of file SparcMachineFunctionInfo.h.
Constructor & Destructor Documentation
llvm::SparcMachineFunctionInfo::SparcMachineFunctionInfo () inline
Definition at line 35 of file SparcMachineFunctionInfo.h.
llvm::SparcMachineFunctionInfo::SparcMachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 38 of file SparcMachineFunctionInfo.h.
Member Function Documentation
unsigned llvm::SparcMachineFunctionInfo::getGlobalBaseReg () const inline
Definition at line 42 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcInstrInfo::getGlobalBaseReg().
unsigned llvm::SparcMachineFunctionInfo::getSRetReturnReg () const inline
Definition at line 48 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::SparcTargetLowering::LowerReturn_32().
int llvm::SparcMachineFunctionInfo::getVarArgsFrameOffset () const inline
Definition at line 45 of file SparcMachineFunctionInfo.h.
Referenced by LowerVASTART().
bool llvm::SparcMachineFunctionInfo::isLeafProc () const inline
Definition at line 52 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SparcFrameLowering::emitEpilogue(), and llvm::SparcFrameLowering::emitPrologue().
void llvm::SparcMachineFunctionInfo::setGlobalBaseReg (unsigned Reg) inline
Definition at line 43 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcInstrInfo::getGlobalBaseReg().
void llvm::SparcMachineFunctionInfo::setLeafProc (bool rhs) inline
Definition at line 51 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcFrameLowering::processFunctionBeforeCalleeSavedScan().
void llvm::SparcMachineFunctionInfo::setSRetReturnReg (unsigned Reg) inline
Definition at line 49 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32().
void llvm::SparcMachineFunctionInfo::setVarArgsFrameOffset (int Offset) inline
Definition at line 46 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::SparcTargetLowering::LowerFormalArguments_64().
The documentation for this class was generated from the following files:
SparcMachineFunctionInfo.h
SparcMachineFunctionInfo.cpp