LLVM: llvm::object::ExportDirectoryEntryRef Class Reference
LLVM API Documentation
llvm::object::ExportDirectoryEntryRef Class Reference
#include <COFF.h>
Public Member Functions
ExportDirectoryEntryRef ()
ExportDirectoryEntryRef (const export_directory_table_entry *Table, uint32_t I, const COFFObjectFile *Owner)
bool operator== (const ExportDirectoryEntryRef &Other) const
void moveNext ()
std::error_code getDllName (StringRef &Result) const
std::error_code getOrdinalBase (uint32_t &Result) const
std::error_code getOrdinal (uint32_t &Result) const
std::error_code getExportRVA (uint32_t &Result) const
std::error_code getSymbolName (StringRef &Result) const
Detailed Description
Definition at line 782 of file Object/COFF.h.
Constructor & Destructor Documentation
llvm::object::ExportDirectoryEntryRef::ExportDirectoryEntryRef () inline
Definition at line 784 of file Object/COFF.h.
llvm::object::ExportDirectoryEntryRef::ExportDirectoryEntryRef (const export_directory_table_entry * Table, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 785 of file Object/COFF.h.
Member Function Documentation
std::error_code ExportDirectoryEntryRef::getDllName (StringRef & Result) const
Definition at line 1334 of file COFFObjectFile.cpp.
References llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::export_directory_table_entry::NameRVA, and llvm::object::success.
std::error_code ExportDirectoryEntryRef::getExportRVA (uint32_t & Result) const
Definition at line 1357 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::ExportAddressTableRVA, llvm::object::export_address_table_entry::ExportRVA, llvm::object::COFFObjectFile::getRvaPtr(), and llvm::object::success.
std::error_code ExportDirectoryEntryRef::getOrdinal (uint32_t & Result) const
Definition at line 1351 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::OrdinalBase, and llvm::object::success.
std::error_code ExportDirectoryEntryRef::getOrdinalBase (uint32_t & Result) const
Definition at line 1345 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::OrdinalBase, and llvm::object::success.
std::error_code ExportDirectoryEntryRef::getSymbolName (StringRef & Result) const
Definition at line 1371 of file COFFObjectFile.cpp.
References llvm::object::COFFObjectFile::getRvaPtr(), I, llvm::object::export_directory_table_entry::NamePointerRVA, llvm::object::export_directory_table_entry::NumberOfNamePointers, llvm::object::export_directory_table_entry::OrdinalTableRVA, and llvm::object::success.
void ExportDirectoryEntryRef::moveNext ()
Definition at line 1328 of file COFFObjectFile.cpp.
bool ExportDirectoryEntryRef::operator== (const ExportDirectoryEntryRef & Other) const
Definition at line 1324 of file COFFObjectFile.cpp.
The documentation for this class was generated from the following files:
Object/COFF.h
COFFObjectFile.cpp