LLVM: llvm::AArch64InstPrinter Class Reference
LLVM API Documentation
llvm::AArch64InstPrinter Class Reference
#include <AArch64InstPrinter.h>
Public Member Functions
AArch64InstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot) override
void printRegName (raw_ostream &OS, unsigned RegNo) const override
printRegName - Print the assembler register name.
virtual void printInstruction (const MCInst *MI, raw_ostream &O)
virtual bool printAliasInstr (const MCInst *MI, raw_ostream &O)
virtual void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &O)
virtual StringRef getRegName (unsigned RegNo) const
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo, unsigned AltIdx=AArch64::NoRegAltName)
Protected Member Functions
bool printSysAlias (const MCInst *MI, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printHexImm (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printPostIncOperand (const MCInst *MI, unsigned OpNo, unsigned Imm, raw_ostream &O)
template<int Amount>
void printPostIncOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printVRegOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSysCROperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printAddSubImm (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printLogicalImm32 (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printLogicalImm64 (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printShifter (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printShiftedRegister (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printExtendedRegister (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printArithExtend (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMemExtend (const MCInst *MI, unsigned OpNum, raw_ostream &O, char SrcRegKind, unsigned Width)
template<char SrcRegKind, unsigned Width>
void printMemExtend (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printCondCode (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printInverseCondCode (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAlignedLabel (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printUImm12Offset (const MCInst *MI, unsigned OpNum, unsigned Scale, raw_ostream &O)
void printAMIndexedWB (const MCInst *MI, unsigned OpNum, unsigned Scale, raw_ostream &O)
template<int Scale>
void printUImm12Offset (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<int BitWidth>
void printAMIndexedWB (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAMNoIndex (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<int Scale>
void printImmScale (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPrefetchOp (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printFPImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorList (const MCInst *MI, unsigned OpNum, raw_ostream &O, StringRef LayoutSuffix)
void printImplicitlyTypedVectorList (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<unsigned NumLanes, char LaneKind>
void printTypedVectorList (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorIndex (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAdrpLabel (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printBarrierOption (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMSRSystemRegister (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMRSSystemRegister (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printSystemPStateField (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printSIMDType10Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Additional Inherited Members
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 26 of file AArch64InstPrinter.h.
Constructor & Destructor Documentation
AArch64InstPrinter::AArch64InstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI)
Definition at line 35 of file AArch64InstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), and llvm::MCInstPrinter::setAvailableFeatures().
Member Function Documentation
static const char* llvm::AArch64InstPrinter::getRegisterName (unsigned RegNo, unsigned AltIdx = AArch64::NoRegAltName) static
Referenced by getRegName(), printAMIndexedWB(), printAMNoIndex(), printExtendedRegister(), printInst(), printOperand(), printPostIncOperand(), printRegName(), printShiftedRegister(), printSysAlias(), printVectorList(), and printVRegOperand().
virtual StringRef llvm::AArch64InstPrinter::getRegName (unsigned RegNo) const inline virtual
Reimplemented in llvm::AArch64AppleInstPrinter.
Definition at line 39 of file AArch64InstPrinter.h.
References getRegisterName().
void AArch64InstPrinter::printAddSubImm (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 939 of file AArch64InstPrinter.cpp.
References assert(), llvm::MCInstPrinter::CommentStream, llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::AArch64_AM::getShiftValue(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and printShifter().
void AArch64InstPrinter::printAdrpLabel (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1243 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isImm().
virtual bool llvm::AArch64InstPrinter::printAliasInstr (const MCInst * MI, raw_ostream & O) virtual
Reimplemented in llvm::AArch64AppleInstPrinter.
Referenced by printInst().
void AArch64InstPrinter::printAlignedLabel (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1219 of file AArch64InstPrinter.cpp.
References llvm::dwarf::syntax::Address, llvm::dyn_cast(), llvm::MCExpr::EvaluateAsAbsolute(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and llvm::raw_ostream::write_hex().
void AArch64InstPrinter::printAMIndexedWB (const MCInst * MI, unsigned OpNum, unsigned Scale, raw_ostream & O) protected
Definition at line 1074 of file AArch64InstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), and llvm::MCOperand::isImm().
Referenced by printAMIndexedWB().
template<int BitWidth> void llvm::AArch64InstPrinter::printAMIndexedWB (const MCInst * MI, unsigned OpNum, raw_ostream & O) inline protected
Definition at line 88 of file AArch64InstPrinter.h.
References printAMIndexedWB().
void AArch64InstPrinter::printAMNoIndex (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1052 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and getRegisterName().
void AArch64InstPrinter::printArithExtend (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 997 of file AArch64InstPrinter.cpp.
References llvm::AArch64_AM::getArithExtendType(), llvm::AArch64_AM::getArithShiftValue(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::AArch64_AM::getShiftExtendName(), llvm::AArch64_AM::UXTW, and llvm::AArch64_AM::UXTX.
Referenced by printExtendedRegister().
void AArch64InstPrinter::printBarrierOption (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1258 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), Name, and llvm::AArch64NamedImmMapper::toString().
void AArch64InstPrinter::printCondCode (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1040 of file AArch64InstPrinter.cpp.
References llvm::AArch64CC::getCondCodeName(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
virtual void llvm::AArch64InstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & O) virtual
Reimplemented in llvm::AArch64AppleInstPrinter.
void AArch64InstPrinter::printExtendedRegister (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 991 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), and printArithExtend().
void AArch64InstPrinter::printFPImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1098 of file AArch64InstPrinter.cpp.
References llvm::format(), llvm::MCOperand::getFPImm(), llvm::AArch64_AM::getFPImmFloat(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isFPImm().
void AArch64InstPrinter::printHexImm (const MCInst * MI, unsigned OpNo, raw_ostream & O) protected
Definition at line 905 of file AArch64InstPrinter.cpp.
References llvm::format(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
template<int Scale> void AArch64InstPrinter::printImmScale (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1058 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void AArch64InstPrinter::printImplicitlyTypedVectorList (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Print a list of vector registers where the type suffix is implicit (i.e. attached to the instruction rather than the registers).
Definition at line 1196 of file AArch64InstPrinter.cpp.
References printVectorList().
void AArch64InstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) override virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Reimplemented in llvm::AArch64AppleInstPrinter.
Definition at line 55 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::getWRegFromXReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), and printSysAlias().
Referenced by llvm::AArch64AppleInstPrinter::printInst().
virtual void llvm::AArch64InstPrinter::printInstruction (const MCInst * MI, raw_ostream & O) virtual
Reimplemented in llvm::AArch64AppleInstPrinter.
Referenced by printInst().
void AArch64InstPrinter::printInverseCondCode (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1046 of file AArch64InstPrinter.cpp.
References llvm::AArch64CC::getCondCodeName(), llvm::MCOperand::getImm(), llvm::AArch64CC::getInvertedCondCode(), and llvm::MCInst::getOperand().
void AArch64InstPrinter::printLogicalImm32 (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 960 of file AArch64InstPrinter.cpp.
References llvm::AArch64_AM::decodeLogicalImmediate(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::raw_ostream::write_hex().
void AArch64InstPrinter::printLogicalImm64 (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 967 of file AArch64InstPrinter.cpp.
References llvm::AArch64_AM::decodeLogicalImmediate(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::raw_ostream::write_hex().
void AArch64InstPrinter::printMemExtend (const MCInst * MI, unsigned OpNum, raw_ostream & O, char SrcRegKind, unsigned Width) protected
Definition at line 1023 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::Log2_32().
Referenced by printMemExtend().
template<char SrcRegKind, unsigned Width> void llvm::AArch64InstPrinter::printMemExtend (const MCInst * MI, unsigned OpNum, raw_ostream & O) inline protected
Definition at line 70 of file AArch64InstPrinter.h.
References printMemExtend().
void AArch64InstPrinter::printMRSSystemRegister (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1275 of file AArch64InstPrinter.cpp.
References llvm::MCInstPrinter::getAvailableFeatures(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), Name, and llvm::StringRef::upper().
void AArch64InstPrinter::printMSRSystemRegister (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1285 of file AArch64InstPrinter.cpp.
References llvm::MCInstPrinter::getAvailableFeatures(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), Name, and llvm::StringRef::upper().
void AArch64InstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) protected
Definition at line 891 of file AArch64InstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and llvm::MCOperand::isReg().
void AArch64InstPrinter::printPostIncOperand (const MCInst * MI, unsigned OpNo, unsigned Imm, raw_ostream & O) protected
Definition at line 911 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isReg(), and llvm_unreachable.
Referenced by printPostIncOperand().
template<int Amount> void llvm::AArch64InstPrinter::printPostIncOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) inline protected
Definition at line 53 of file AArch64InstPrinter.h.
References printPostIncOperand().
void AArch64InstPrinter::printPrefetchOp (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1087 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), Name, and llvm::AArch64NamedImmMapper::toString().
void AArch64InstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
printRegName - Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 50 of file AArch64InstPrinter.cpp.
References getRegisterName().
void AArch64InstPrinter::printShiftedRegister (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 985 of file AArch64InstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), and printShifter().
void AArch64InstPrinter::printShifter (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 974 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::AArch64_AM::getShiftExtendName(), llvm::AArch64_AM::getShiftType(), llvm::AArch64_AM::getShiftValue(), and llvm::AArch64_AM::LSL.
Referenced by printAddSubImm(), and printShiftedRegister().
void AArch64InstPrinter::printSIMDType10Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1307 of file AArch64InstPrinter.cpp.
References llvm::AArch64_AM::decodeAdvSIMDModImmType10(), llvm::format(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
bool AArch64InstPrinter::printSysAlias (const MCInst * MI, raw_ostream & O) protected
Definition at line 668 of file AArch64InstPrinter.cpp.
References llvm::HexStyle::Asm, assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), and llvm::StringRef::npos.
Referenced by printInst().
void AArch64InstPrinter::printSysCROperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) protected
Definition at line 932 of file AArch64InstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isImm().
void AArch64InstPrinter::printSystemPStateField (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1295 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), Name, llvm::StringRef::str(), and llvm::AArch64NamedImmMapper::toString().
template<unsigned NumLanes, char LaneKind> void AArch64InstPrinter::printTypedVectorList (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1203 of file AArch64InstPrinter.cpp.
References llvm::itostr(), and printVectorList().
void AArch64InstPrinter::printUImm12Offset (const MCInst * MI, unsigned OpNum, unsigned Scale, raw_ostream & O) protected
Definition at line 1063 of file AArch64InstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and llvm::MCOperand::isImm().
Referenced by printUImm12Offset().
template<int Scale> void llvm::AArch64InstPrinter::printUImm12Offset (const MCInst * MI, unsigned OpNum, raw_ostream & O) inline protected
Definition at line 83 of file AArch64InstPrinter.h.
References printUImm12Offset().
void AArch64InstPrinter::printVectorIndex (const MCInst * MI, unsigned OpNum, raw_ostream & O) protected
Definition at line 1214 of file AArch64InstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void AArch64InstPrinter::printVectorList (const MCInst * MI, unsigned OpNum, raw_ostream & O, StringRef LayoutSuffix) protected
Definition at line 1153 of file AArch64InstPrinter.cpp.
References llvm::MCRegisterClass::contains(), llvm::MCRegisterInfo::getMatchingSuperReg(), getNextVectorRegister(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), getRegisterName(), llvm::MCRegisterInfo::getSubReg(), and llvm::MCInstPrinter::MRI.
Referenced by printImplicitlyTypedVectorList(), llvm::AArch64AppleInstPrinter::printInst(), and printTypedVectorList().
void AArch64InstPrinter::printVRegOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) protected
Definition at line 924 of file AArch64InstPrinter.cpp.
References assert(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), and llvm::MCOperand::isReg().
The documentation for this class was generated from the following files:
AArch64InstPrinter.h
AArch64InstPrinter.cpp