LLVM: llvm::X86Subtarget Class Reference
LLVM API Documentation
llvm::X86Subtarget Class Reference final
#include <X86Subtarget.h>
Public Member Functions
X86Subtarget (const std::string &TT, const std::string &CPU, const std::string &FS, const X86TargetMachine &TM, unsigned StackAlignOverride)
const X86TargetLowering * getTargetLowering () const override
const X86InstrInfo * getInstrInfo () const override
const DataLayout * getDataLayout () const override
const X86FrameLowering * getFrameLowering () const override
const X86SelectionDAGInfo * getSelectionDAGInfo () const override
const X86RegisterInfo * getRegisterInfo () const override
unsigned getStackAlignment () const
unsigned getMaxInlineSizeThreshold () const
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool is64Bit () const
Is this x86_64? (disregarding specific ABI / programming model)
bool is32Bit () const
bool is16Bit () const
bool isTarget64BitILP32 () const
Is this x86_64 with the ILP32 programming model (x32 ABI)?
bool isTarget64BitLP64 () const
Is this x86_64 with the LP64 programming model (standard AMD64, no x32)?
PICStyles::Style getPICStyle () const
void setPICStyle (PICStyles::Style Style)
bool hasCMov () const
bool hasMMX () const
bool hasSSE1 () const
bool hasSSE2 () const
bool hasSSE3 () const
bool hasSSSE3 () const
bool hasSSE41 () const
bool hasSSE42 () const
bool hasAVX () const
bool hasAVX2 () const
bool hasAVX512 () const
bool hasFp256 () const
bool hasInt256 () const
bool hasSSE4A () const
bool has3DNow () const
bool has3DNowA () const
bool hasPOPCNT () const
bool hasAES () const
bool hasPCLMUL () const
bool hasFMA () const
bool hasFMA4 () const
bool hasXOP () const
bool hasTBM () const
bool hasMOVBE () const
bool hasRDRAND () const
bool hasF16C () const
bool hasFSGSBase () const
bool hasLZCNT () const
bool hasBMI () const
bool hasBMI2 () const
bool hasRTM () const
bool hasHLE () const
bool hasADX () const
bool hasSHA () const
bool hasSGX () const
bool hasPRFCHW () const
bool hasRDSEED () const
bool hasSMAP () const
bool isBTMemSlow () const
bool isSHLDSlow () const
bool isUnalignedMemAccessFast () const
bool isUnalignedMem32Slow () const
bool hasSSEUnalignedMem () const
bool hasCmpxchg16b () const
bool useLeaForSP () const
bool hasSlowDivide32 () const
bool hasSlowDivide64 () const
bool padShortFunctions () const
bool callRegIndirect () const
bool LEAusesAG () const
bool slowLEA () const
bool slowIncDec () const
bool useSqrtEst () const
bool useReciprocalEst () const
bool hasCDI () const
bool hasPFI () const
bool hasERI () const
bool hasDQI () const
bool hasBWI () const
bool hasVLX () const
bool isAtom () const
bool isSLM () const
const Triple & getTargetTriple () const
bool isTargetDarwin () const
bool isTargetFreeBSD () const
bool isTargetDragonFly () const
bool isTargetSolaris () const
bool isTargetELF () const
bool isTargetCOFF () const
bool isTargetMachO () const
bool isTargetLinux () const
bool isTargetNaCl () const
bool isTargetNaCl32 () const
bool isTargetNaCl64 () const
bool isTargetWindowsMSVC () const
bool isTargetKnownWindowsMSVC () const
bool isTargetWindowsCygwin () const
bool isTargetWindowsGNU () const
bool isTargetWindowsItanium () const
bool isTargetCygMing () const
bool isOSWindows () const
bool isTargetWin64 () const
bool isTargetWin32 () const
bool isPICStyleSet () const
bool isPICStyleGOT () const
bool isPICStyleRIPRel () const
bool isPICStyleStubPIC () const
bool isPICStyleStubNoDynamic () const
bool isPICStyleStubAny () const
bool isCallingConvWin64 (CallingConv::ID CC) const
unsigned char ClassifyGlobalReference (const GlobalValue *GV, const TargetMachine &TM) const
unsigned char ClassifyBlockAddressReference () const
bool IsLegalToCallImmediateAddr (const TargetMachine &TM) const
const char * getBZeroEntry () const
bool hasSinCos () const
bool enableMachineScheduler () const override
Enable the MachineScheduler pass for all X86 subtargets.
bool enableEarlyIfConversion () const override
const InstrItineraryData * getInstrItineraryData () const override
AntiDepBreakMode getAntiDepBreakMode () const override
Protected Types
enum X86SSEEnum {
NoMMXSSE, MMX, SSE1, SSE2,
SSE3, SSSE3, SSE41, SSE42,
AVX, AVX2, AVX512F
}
enum X863DNowEnum { NoThreeDNow, ThreeDNow, ThreeDNowA }
enum X86ProcFamilyEnum { Others, IntelAtom, IntelSLM }
Protected Attributes
X86ProcFamilyEnum X86ProcFamily
X86ProcFamily - X86 processor family: Intel Atom, and others.
PICStyles::Style PICStyle
X86SSEEnum X86SSELevel
X863DNowEnum X863DNowLevel
bool HasCMov
bool HasX86_64
bool HasPOPCNT
HasPOPCNT - True if the processor supports POPCNT.
bool HasSSE4A
HasSSE4A - True if the processor supports SSE4A instructions.
bool HasAES
HasAES - Target has AES instructions.
bool HasPCLMUL
HasPCLMUL - Target has carry-less multiplication.
bool HasFMA
HasFMA - Target has 3-operand fused multiply-add.
bool HasFMA4
HasFMA4 - Target has 4-operand fused multiply-add.
bool HasXOP
HasXOP - Target has XOP instructions.
bool HasTBM
HasTBM - Target has TBM instructions.
bool HasMOVBE
HasMOVBE - True if the processor has the MOVBE instruction.
bool HasRDRAND
HasRDRAND - True if the processor has the RDRAND instruction.
bool HasF16C
HasF16C - Processor has 16-bit floating point conversion instructions.
bool HasFSGSBase
HasFSGSBase - Processor has FS/GS base insturctions.
bool HasLZCNT
HasLZCNT - Processor has LZCNT instruction.
bool HasBMI
HasBMI - Processor has BMI1 instructions.
bool HasBMI2
HasBMI2 - Processor has BMI2 instructions.
bool HasRTM
HasRTM - Processor has RTM instructions.
bool HasHLE
HasHLE - Processor has HLE.
bool HasADX
HasADX - Processor has ADX instructions.
bool HasSHA
HasSHA - Processor has SHA instructions.
bool HasSGX
HasSGX - Processor has SGX instructions.
bool HasPRFCHW
HasPRFCHW - Processor has PRFCHW instructions.
bool HasRDSEED
HasRDSEED - Processor has RDSEED instructions.
bool HasSMAP
HasSMAP - Processor has SMAP instructions.
bool IsBTMemSlow
IsBTMemSlow - True if BT (bit test) of memory instructions are slow.
bool IsSHLDSlow
IsSHLDSlow - True if SHLD instructions are slow.
bool IsUAMemFast
IsUAMemFast - True if unaligned memory access is fast.
bool IsUAMem32Slow
True if unaligned 32-byte memory accesses are slow.
bool HasSSEUnalignedMem
bool HasCmpxchg16b
bool UseLeaForSP
bool HasSlowDivide32
bool HasSlowDivide64
bool PadShortFunctions
bool CallRegIndirect
bool LEAUsesAG
bool SlowLEA
SlowLEA - True if the LEA instruction with certain arguments is slow.
bool SlowIncDec
SlowIncDec - True if INC and DEC instructions are slow when writing to flags.
bool UseSqrtEst
bool UseReciprocalEst
bool HasPFI
Processor has AVX-512 PreFetch Instructions.
bool HasERI
Processor has AVX-512 Exponential and Reciprocal Instructions.
bool HasCDI
Processor has AVX-512 Conflict Detection Instructions.
bool HasDQI
Processor has AVX-512 Doubleword and Quadword instructions.
bool HasBWI
Processor has AVX-512 Byte and Word instructions.
bool HasVLX
Processor has AVX-512 Vector Length eXtenstions.
unsigned stackAlignment
unsigned MaxInlineSizeThreshold
Triple TargetTriple
TargetTriple - What processor and OS we're targeting.
InstrItineraryData InstrItins
Instruction itineraries for scheduling.
Detailed Description
Definition at line 46 of file X86Subtarget.h.
Member Enumeration Documentation
enum llvm::X86Subtarget::X863DNowEnum protected
Enumerator
NoThreeDNow
ThreeDNow
ThreeDNowA
Definition at line 53 of file X86Subtarget.h.
enum llvm::X86Subtarget::X86ProcFamilyEnum protected
Enumerator
Others
IntelAtom
IntelSLM
Definition at line 57 of file X86Subtarget.h.
enum llvm::X86Subtarget::X86SSEEnum protected
Enumerator
NoMMXSSE
MMX
SSE1
SSE2
SSE3
SSSE3
SSE41
SSE42
AVX
AVX2
AVX512F
Definition at line 49 of file X86Subtarget.h.
Constructor & Destructor Documentation
X86Subtarget::X86Subtarget (const std::string & TT, const std::string & CPU, const std::string & FS, const X86TargetMachine & TM, unsigned StackAlignOverride)
This constructor initializes the data members to match that of the specified triple.
Definition at line 332 of file X86Subtarget.cpp.
References assert(), llvm::Reloc::DynamicNoPIC, llvm::TargetMachine::getRelocationModel(), llvm::PICStyles::GOT, is64Bit(), isTargetCOFF(), isTargetDarwin(), isTargetELF(), llvm::PICStyles::None, llvm::Reloc::PIC_, llvm::PICStyles::RIPRel, setPICStyle(), llvm::Reloc::Static, llvm::PICStyles::StubDynamicNoPIC, and llvm::PICStyles::StubPIC.
Member Function Documentation
bool llvm::X86Subtarget::callRegIndirect () const inline
Definition at line 387 of file X86Subtarget.h.
References CallRegIndirect.
Referenced by llvm::X86InstrInfo::foldMemoryOperandImpl().
unsigned char X86Subtarget::ClassifyBlockAddressReference () const
ClassifyBlockAddressReference - Classify a blockaddress reference for the current subtarget according to how we should reference it in a non-pcrel context.
Definition at line 50 of file X86Subtarget.cpp.
References isPICStyleGOT(), isPICStyleStubPIC(), llvm::X86II::MO_GOTOFF, llvm::X86II::MO_NO_FLAG, and llvm::X86II::MO_PIC_BASE_OFFSET.
unsigned char X86Subtarget::ClassifyGlobalReference (const GlobalValue * GV, const TargetMachine & TM) const
ClassifyGlobalReference - Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
Definition at line 65 of file X86Subtarget.cpp.
References assert(), llvm::TargetMachine::getCodeModel(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasDefaultVisibility(), llvm::GlobalValue::hasDLLImportStorageClass(), llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::isDeclarationForLinker(), isPICStyleGOT(), isPICStyleRIPRel(), isPICStyleStubNoDynamic(), isPICStyleStubPIC(), isTargetDarwin(), isTargetELF(), isTargetWin64(), llvm::GlobalValue::isWeakForLinker(), llvm::CodeModel::Large, llvm::X86II::MO_DARWIN_HIDDEN_NONLAZY_PIC_BASE, llvm::X86II::MO_DARWIN_NONLAZY, llvm::X86II::MO_DARWIN_NONLAZY_PIC_BASE, llvm::X86II::MO_DLLIMPORT, llvm::X86II::MO_GOT, llvm::X86II::MO_GOTOFF, llvm::X86II::MO_GOTPCREL, llvm::X86II::MO_NO_FLAG, and llvm::X86II::MO_PIC_BASE_OFFSET.
Referenced by llvm::X86TargetLowering::isLegalAddressingMode(), and llvm::X86TargetLowering::LowerAsmOperandForConstraint().
bool X86Subtarget::enableEarlyIfConversion () const override
Definition at line 368 of file X86Subtarget.cpp.
References hasCMov(), and X86EarlyIfConv.
bool llvm::X86Subtarget::enableMachineScheduler () const inline override
Enable the MachineScheduler pass for all X86 subtargets.
Definition at line 499 of file X86Subtarget.h.
AntiDepBreakMode llvm::X86Subtarget::getAntiDepBreakMode () const inline override
Definition at line 509 of file X86Subtarget.h.
References llvm::TargetSubtargetInfo::ANTIDEP_CRITICAL.
const char * X86Subtarget::getBZeroEntry () const
This function returns the name of a function which has an interface like the non-standard bzero function, if such a function exists on the current subtarget and it is considered prefereable over memset with zero passed as the second argument. Otherwise it returns null.
getBZeroEntry - This function returns the name of a function which has an interface like the non-standard bzero function, if such a function exists on the current subtarget and it is considered prefereable over memset with zero passed as the second argument. Otherwise it returns null.
Definition at line 155 of file X86Subtarget.cpp.
References getTargetTriple().
const DataLayout* llvm::X86Subtarget::getDataLayout () const inline override
Definition at line 279 of file X86Subtarget.h.
const X86FrameLowering* llvm::X86Subtarget::getFrameLowering () const inline override
Definition at line 280 of file X86Subtarget.h.
const X86InstrInfo* llvm::X86Subtarget::getInstrInfo () const inline override
Definition at line 278 of file X86Subtarget.h.
Referenced by getRegisterInfo().
const InstrItineraryData* llvm::X86Subtarget::getInstrItineraryData () const inline override
getInstrItins = Return the instruction itineraries based on the subtarget selection.
Definition at line 505 of file X86Subtarget.h.
References InstrItins.
unsigned llvm::X86Subtarget::getMaxInlineSizeThreshold () const inline
getMaxInlineSizeThreshold - Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
Definition at line 297 of file X86Subtarget.h.
References MaxInlineSizeThreshold.
PICStyles::Style llvm::X86Subtarget::getPICStyle () const inline
Definition at line 335 of file X86Subtarget.h.
References PICStyle.
const X86RegisterInfo* llvm::X86Subtarget::getRegisterInfo () const inline override
Definition at line 286 of file X86Subtarget.h.
References getInstrInfo(), and llvm::X86InstrInfo::getRegisterInfo().
const X86SelectionDAGInfo* llvm::X86Subtarget::getSelectionDAGInfo () const inline override
Definition at line 283 of file X86Subtarget.h.
unsigned llvm::X86Subtarget::getStackAlignment () const inline
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 293 of file X86Subtarget.h.
References stackAlignment.
const X86TargetLowering* llvm::X86Subtarget::getTargetLowering () const inline override
Definition at line 275 of file X86Subtarget.h.
const Triple& llvm::X86Subtarget::getTargetTriple () const inline
Definition at line 403 of file X86Subtarget.h.
References TargetTriple.
Referenced by computeBytesPoppedByCallee(), getBZeroEntry(), and hasSinCos().
bool llvm::X86Subtarget::has3DNow () const inline
Definition at line 352 of file X86Subtarget.h.
References ThreeDNow, and X863DNowLevel.
bool llvm::X86Subtarget::has3DNowA () const inline
Definition at line 353 of file X86Subtarget.h.
References ThreeDNowA, and X863DNowLevel.
bool llvm::X86Subtarget::hasADX () const inline
Definition at line 371 of file X86Subtarget.h.
References HasADX.
bool llvm::X86Subtarget::hasAES () const inline
Definition at line 355 of file X86Subtarget.h.
References HasAES.
bool llvm::X86Subtarget::hasAVX () const inline
Definition at line 346 of file X86Subtarget.h.
References AVX, and X86SSELevel.
Referenced by llvm::X86InstrInfo::breakPartialRegDependency(), llvm::X86InstrInfo::copyPhysReg(), CopyToFromAsymmetricReg(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), getLoadStoreRegOpcode(), hasFp256(), lowerV2F64VectorShuffle(), lowerV4F32VectorShuffle(), LowerVectorBroadcast(), lowerVectorShuffleAsBroadcast(), LowerVSETCC(), matchIntegerMINMAX(), PerformBUILD_VECTORCombine(), PerformINTRINSIC_WO_CHAINCombine(), llvm::X86InstrInfo::shouldScheduleAdjacent(), and X86ChooseCmpOpcode().
bool llvm::X86Subtarget::hasAVX2 () const inline
Definition at line 347 of file X86Subtarget.h.
References AVX2, and X86SSELevel.
Referenced by llvm::X86InstrInfo::getExecutionDomain(), hasInt256(), lower256BitVectorShuffle(), lowerV16I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I32VectorShuffle(), LowerVectorBroadcast(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), matchIntegerMINMAX(), PerformBUILD_VECTORCombine(), PerformINTRINSIC_WO_CHAINCombine(), PerformSELECTCombine(), and llvm::X86InstrInfo::setExecutionDomain().
bool llvm::X86Subtarget::hasAVX512 () const inline
Definition at line 348 of file X86Subtarget.h.
References AVX512F, and X86SSELevel.
Referenced by CMPEQCombine(), llvm::X86InstrInfo::copyPhysReg(), CopyToFromAsymmetricReg(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), getLoadStoreRegOpcode(), llvm::X86RegisterInfo::getReservedRegs(), llvm::X86TargetLowering::getSetCCResultType(), isVALIGNMask(), lower512BitVectorShuffle(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShift(), LowerVectorBroadcast(), LowerVSETCC(), matchIntegerMINMAX(), PerformSELECTCombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasBMI () const inline
Definition at line 367 of file X86Subtarget.h.
References HasBMI.
Referenced by llvm::X86TargetLowering::isCheapToSpeculateCttz(), PerformAndCombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasBMI2 () const inline
Definition at line 368 of file X86Subtarget.h.
References HasBMI2.
bool llvm::X86Subtarget::hasBWI () const inline
Definition at line 397 of file X86Subtarget.h.
References HasBWI.
Referenced by llvm::X86TargetLowering::getSetCCResultType(), lower512BitVectorShuffle(), LowerSIGN_EXTEND_AVX512(), lowerV32I16VectorShuffle(), lowerV64I8VectorShuffle(), LowerVSETCC(), matchIntegerMINMAX(), PerformSELECTCombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasCDI () const inline
Definition at line 393 of file X86Subtarget.h.
References HasCDI.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasCMov () const inline
Definition at line 338 of file X86Subtarget.h.
References HasCMov.
Referenced by llvm::X86InstrInfo::canInsertSelect(), enableEarlyIfConversion(), and PerformXorCombine().
bool llvm::X86Subtarget::hasCmpxchg16b () const inline
Definition at line 382 of file X86Subtarget.h.
References HasCmpxchg16b.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasDQI () const inline
Definition at line 396 of file X86Subtarget.h.
References HasDQI.
Referenced by LowerSIGN_EXTEND_AVX512().
bool llvm::X86Subtarget::hasERI () const inline
Definition at line 395 of file X86Subtarget.h.
References HasERI.
bool llvm::X86Subtarget::hasF16C () const inline
Definition at line 364 of file X86Subtarget.h.
References HasF16C.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasFMA () const inline
Definition at line 357 of file X86Subtarget.h.
References HasFMA.
Referenced by llvm::X86TargetLowering::isFMAFasterThanFMulAndFAdd(), PerformFMACombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasFMA4 () const inline
Definition at line 359 of file X86Subtarget.h.
References HasFMA, and HasFMA4.
Referenced by llvm::X86TargetLowering::isFMAFasterThanFMulAndFAdd(), PerformFMACombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasFp256 () const inline
Definition at line 349 of file X86Subtarget.h.
References hasAVX().
Referenced by llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), LowerANY_EXTEND(), LowerEXTRACT_SUBVECTOR(), LowerINSERT_SUBVECTOR(), LowerZERO_EXTEND(), PerformFADDCombine(), PerformFSUBCombine(), PerformSExtCombine(), PerformShuffleCombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasFSGSBase () const inline
Definition at line 365 of file X86Subtarget.h.
References HasFSGSBase.
bool llvm::X86Subtarget::hasHLE () const inline
Definition at line 370 of file X86Subtarget.h.
References HasHLE.
bool llvm::X86Subtarget::hasInt256 () const inline
Definition at line 350 of file X86Subtarget.h.
References hasAVX2().
Referenced by llvm::X86TargetLowering::getOptimalMemOpType(), getZeroVector(), isPALIGNRMask(), llvm::X86TargetLowering::isShuffleMaskLegal(), llvm::X86TargetLowering::isVectorClearMaskLegal(), llvm::X86TargetLowering::isVectorShiftByScalarCheap(), LowerAVXExtend(), LowerExtendedLoad(), LowerMUL(), LowerMUL_LOHI(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShift(), LowerSIGN_EXTEND(), LowerVECTOR_SHUFFLEtoBlend(), LowerVECTOR_SHUFFLEv32i8(), LowerVectorBroadcast(), LowerVectorIntExtend(), lowerVSELECTtoBLENDI(), LowerVSETCC(), PerformAddCombine(), PerformOrCombine(), performShiftToAllZeros(), PerformSIGN_EXTEND_INREGCombine(), PerformSubCombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasLZCNT () const inline
Definition at line 366 of file X86Subtarget.h.
References HasLZCNT.
Referenced by llvm::X86TargetLowering::isCheapToSpeculateCtlz(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasMMX () const inline
Definition at line 339 of file X86Subtarget.h.
References MMX, and X86SSELevel.
Referenced by llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), LowerBITCAST(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasMOVBE () const inline
Definition at line 362 of file X86Subtarget.h.
References HasMOVBE.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasPCLMUL () const inline
Definition at line 356 of file X86Subtarget.h.
References HasPCLMUL.
bool llvm::X86Subtarget::hasPFI () const inline
Definition at line 394 of file X86Subtarget.h.
References HasPFI.
bool llvm::X86Subtarget::hasPOPCNT () const inline
Definition at line 354 of file X86Subtarget.h.
References HasPOPCNT.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasPRFCHW () const inline
Definition at line 374 of file X86Subtarget.h.
References HasPRFCHW.
bool llvm::X86Subtarget::hasRDRAND () const inline
Definition at line 363 of file X86Subtarget.h.
References HasRDRAND.
bool llvm::X86Subtarget::hasRDSEED () const inline
Definition at line 375 of file X86Subtarget.h.
References HasRDSEED.
bool llvm::X86Subtarget::hasRTM () const inline
Definition at line 369 of file X86Subtarget.h.
References HasRTM.
bool llvm::X86Subtarget::hasSGX () const inline
Definition at line 373 of file X86Subtarget.h.
References HasSGX.
bool llvm::X86Subtarget::hasSHA () const inline
Definition at line 372 of file X86Subtarget.h.
References HasSHA.
bool X86Subtarget::hasSinCos () const
This function returns true if the target has sincos() routine in its compiler runtime or math libraries.
Definition at line 164 of file X86Subtarget.cpp.
References getTargetTriple(), is64Bit(), llvm::Triple::isMacOSX(), and llvm::Triple::isMacOSXVersionLT().
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasSlowDivide32 () const inline
Definition at line 384 of file X86Subtarget.h.
References HasSlowDivide32.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasSlowDivide64 () const inline
Definition at line 385 of file X86Subtarget.h.
References HasSlowDivide64.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasSMAP () const inline
Definition at line 376 of file X86Subtarget.h.
References HasSMAP.
bool llvm::X86Subtarget::hasSSE1 () const inline
Definition at line 340 of file X86Subtarget.h.
References SSE1, and X86SSELevel.
Referenced by get64BitArgumentXMMs(), llvm::X86TargetLowering::getByValTypeAlignment(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::LowerXConstraint(), PerformSELECTCombine(), llvm::X86TargetLowering::resetOperationActions(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
bool llvm::X86Subtarget::hasSSE2 () const inline
Definition at line 341 of file X86Subtarget.h.
References SSE2, and X86SSELevel.
Referenced by CMPEQCombine(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), getZeroVector(), hasMFENCE(), LowerBITCAST(), LowerExtendedLoad(), LowerMUL(), LowerMUL_LOHI(), LowerShift(), LowerVECTOR_SHUFFLEv8i16(), LowerVSETCC(), llvm::X86TargetLowering::LowerXConstraint(), matchIntegerMINMAX(), NormalizeVectorShuffle(), PerformSELECTCombine(), PerformSTORECombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::resetOperationActions(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
bool llvm::X86Subtarget::hasSSE3 () const inline
Definition at line 342 of file X86Subtarget.h.
References SSE3, and X86SSELevel.
Referenced by llvm::X86TargetLowering::BuildFILD(), combineX86ShuffleChain(), isMOVSHDUPMask(), isMOVSLDUPMask(), PerformBUILD_VECTORCombine(), PerformFADDCombine(), PerformFSUBCombine(), PerformShuffleCombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasSSE41 () const inline
Definition at line 344 of file X86Subtarget.h.
References SSE41, and X86SSELevel.
Referenced by getTargetVShiftNode(), llvm::X86TargetLowering::isShuffleMaskLegal(), llvm::X86TargetLowering::isVectorClearMaskLegal(), LowerBuildVectorv4x32(), LowerExtendedLoad(), LowerMUL(), LowerMUL_LOHI(), lowerUINT_TO_FP_vXi32(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4I32VectorShuffle(), lowerV8I16VectorShuffle(), LowerVECTOR_SHUFFLEtoBlend(), LowerVectorAllZeroTest(), LowerVectorIntExtend(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsSpecificZeroOrAnyExtend(), lowerVSELECTtoBLENDI(), LowerVSETCC(), matchIntegerMINMAX(), PerformINTRINSIC_WO_CHAINCombine(), PerformOrCombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasSSE42 () const inline
Definition at line 345 of file X86Subtarget.h.
References SSE42, and X86SSELevel.
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter(), and LowerVSETCC().
bool llvm::X86Subtarget::hasSSE4A () const inline
Definition at line 351 of file X86Subtarget.h.
References HasSSE4A.
bool llvm::X86Subtarget::hasSSEUnalignedMem () const inline
Definition at line 381 of file X86Subtarget.h.
References HasSSEUnalignedMem.
bool llvm::X86Subtarget::hasSSSE3 () const inline
Definition at line 343 of file X86Subtarget.h.
References SSSE3, and X86SSELevel.
Referenced by combineX86ShuffleChain(), isPALIGNRMask(), llvm::X86TargetLowering::isShuffleMaskLegal(), lowerV16I8VectorShuffle(), lowerV2I64VectorShuffle(), lowerV4I32VectorShuffle(), LowerVECTOR_SHUFFLEv16i8(), LowerVECTOR_SHUFFLEv8i16(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsSpecificZeroOrAnyExtend(), PerformAddCombine(), PerformBUILD_VECTORCombine(), PerformOrCombine(), and PerformSubCombine().
bool llvm::X86Subtarget::hasTBM () const inline
Definition at line 361 of file X86Subtarget.h.
References HasTBM.
Referenced by PerformAndCombine().
bool llvm::X86Subtarget::hasVLX () const inline
Definition at line 398 of file X86Subtarget.h.
References HasVLX.
Referenced by llvm::X86TargetLowering::getSetCCResultType(), LowerSIGN_EXTEND_AVX512(), LowerVectorBroadcast(), LowerVSETCC(), matchIntegerMINMAX(), PerformSELECTCombine(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::hasXOP () const inline
Definition at line 360 of file X86Subtarget.h.
References HasXOP.
bool llvm::X86Subtarget::is16Bit () const inline
Definition at line 319 of file X86Subtarget.h.
bool llvm::X86Subtarget::is32Bit () const inline
Definition at line 315 of file X86Subtarget.h.
bool llvm::X86Subtarget::is64Bit () const inline
Is this x86_64? (disregarding specific ABI / programming model)
Definition at line 311 of file X86Subtarget.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), CMPEQCombine(), computeBytesPoppedByCallee(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::copyPhysReg(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86AsmPrinter::EmitInstruction(), EmitMonitor(), llvm::X86FrameLowering::emitPrologue(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::X86TargetLowering::findRepresentativeClass(), llvm::X86InstrInfo::foldMemoryOperandImpl(), get64BitArgumentGPRs(), get64BitArgumentXMMs(), llvm::X86TargetLowering::getByValTypeAlignment(), llvm::X86InstrInfo::getGlobalBaseReg(), getLoadStoreRegOpcode(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), llvm::X86RegisterInfo::getPointerRegClass(), getReadPerformanceCounter(), getReadTimeStampCounter(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86RegisterInfo::getRegPressureLimit(), getRetOpcode(), llvm::X86TargetLowering::getStackCookieLocation(), llvm::X86FrameLowering::getStackProbeFunction(), getVZextMovL(), hasMFENCE(), hasSinCos(), llvm::X86InstrInfo::isCoalescableExtInstr(), llvm::X86TargetLowering::isLegalAddressingMode(), llvm::X86TargetLowering::isTargetFTOL(), isTargetNaCl32(), isTargetNaCl64(), llvm::X86TargetLowering::isZExtFree(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerBITCAST(), LowerCMP_SWAP(), LowerFSINCOS(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerVACOPY(), PerformSINT_TO_FPCombine(), PerformSTORECombine(), printAsmMRegister(), llvm::X86TargetLowering::resetOperationActions(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), SimplifyShortMoveForm(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::X86TargetLowering::useLoadStackGuardNode(), llvm::X86RegisterInfo::X86RegisterInfo(), and X86Subtarget().
bool llvm::X86Subtarget::isAtom () const inline
Definition at line 400 of file X86Subtarget.h.
References IntelAtom, and X86ProcFamily.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::isBTMemSlow () const inline
Definition at line 377 of file X86Subtarget.h.
References IsBTMemSlow.
bool llvm::X86Subtarget::isCallingConvWin64 (CallingConv::ID CC) const inline
Definition at line 467 of file X86Subtarget.h.
References isTargetWin64(), llvm::CallingConv::X86_64_SysV, and llvm::CallingConv::X86_64_Win64.
Referenced by get64BitArgumentGPRs(), and get64BitArgumentXMMs().
bool X86Subtarget::IsLegalToCallImmediateAddr (const TargetMachine & TM) const
IsLegalToCallImmediateAddr - Return true if the subtarget allows calls to immediate address.
Definition at line 172 of file X86Subtarget.cpp.
References llvm::TargetMachine::getRelocationModel(), isTargetELF(), isTargetWin32(), and llvm::Reloc::Static.
bool llvm::X86Subtarget::isOSWindows () const inline
Definition at line 441 of file X86Subtarget.h.
References llvm::Triple::isOSWindows(), and TargetTriple.
Referenced by llvm::X86FrameLowering::emitPrologue().
bool llvm::X86Subtarget::isPICStyleGOT () const inline
Definition at line 452 of file X86Subtarget.h.
References llvm::PICStyles::GOT, and PICStyle.
Referenced by ClassifyBlockAddressReference(), ClassifyGlobalReference(), llvm::X86TargetLowering::getJumpTableEncoding(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), and llvm::X86TargetLowering::LowerCustomJumpTableEntry().
bool llvm::X86Subtarget::isPICStyleRIPRel () const inline
Definition at line 453 of file X86Subtarget.h.
References PICStyle, and llvm::PICStyles::RIPRel.
Referenced by ClassifyGlobalReference(), llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr(), and llvm::X86AsmPrinter::PrintAsmOperand().
bool llvm::X86Subtarget::isPICStyleSet () const inline
Definition at line 451 of file X86Subtarget.h.
References llvm::PICStyles::None, and PICStyle.
bool llvm::X86Subtarget::isPICStyleStubAny () const inline
Definition at line 462 of file X86Subtarget.h.
References PICStyle, llvm::PICStyles::StubDynamicNoPIC, and llvm::PICStyles::StubPIC.
bool llvm::X86Subtarget::isPICStyleStubNoDynamic () const inline
Definition at line 459 of file X86Subtarget.h.
References PICStyle, and llvm::PICStyles::StubDynamicNoPIC.
Referenced by ClassifyGlobalReference().
bool llvm::X86Subtarget::isPICStyleStubPIC () const inline
Definition at line 455 of file X86Subtarget.h.
References PICStyle, and llvm::PICStyles::StubPIC.
Referenced by ClassifyBlockAddressReference(), ClassifyGlobalReference(), and llvm::X86TargetLowering::LowerAsmOperandForConstraint().
bool llvm::X86Subtarget::isSHLDSlow () const inline
Definition at line 378 of file X86Subtarget.h.
References IsSHLDSlow.
Referenced by PerformOrCombine().
bool llvm::X86Subtarget::isSLM () const inline
Definition at line 401 of file X86Subtarget.h.
References IntelSLM, and X86ProcFamily.
bool llvm::X86Subtarget::isTarget64BitILP32 () const inline
Is this x86_64 with the ILP32 programming model (x32 ABI)?
Definition at line 324 of file X86Subtarget.h.
References llvm::Triple::getEnvironment(), llvm::Triple::GNUX32, llvm::Triple::isOSNaCl(), and TargetTriple.
Referenced by llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), and llvm::X86RegisterInfo::getPtrSizedFrameRegister().
bool llvm::X86Subtarget::isTarget64BitLP64 () const inline
Is this x86_64 with the LP64 programming model (standard AMD64, no x32)?
Definition at line 330 of file X86Subtarget.h.
References llvm::Triple::getEnvironment(), llvm::Triple::GNUX32, llvm::Triple::isOSNaCl(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::X86RegisterInfo::getPointerRegClass(), and llvm::X86RegisterInfo::X86RegisterInfo().
bool llvm::X86Subtarget::isTargetCOFF () const inline
Definition at line 411 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatCOFF(), and TargetTriple.
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::X86AsmPrinter::runOnMachineFunction(), and X86Subtarget().
bool llvm::X86Subtarget::isTargetCygMing () const inline
Definition at line 439 of file X86Subtarget.h.
References llvm::Triple::isOSCygMing(), and TargetTriple.
Referenced by llvm::X86FrameLowering::getStackProbeFunction(), isTargetWin32(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::isTargetDarwin () const inline
Definition at line 405 of file X86Subtarget.h.
References llvm::Triple::isOSDarwin(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), ClassifyGlobalReference(), LowerFSINCOS(), llvm::X86TargetLowering::resetOperationActions(), and X86Subtarget().
bool llvm::X86Subtarget::isTargetDragonFly () const inline
Definition at line 407 of file X86Subtarget.h.
References llvm::Triple::isOSDragonFly(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
bool llvm::X86Subtarget::isTargetELF () const inline
Definition at line 410 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatELF(), and TargetTriple.
Referenced by ClassifyGlobalReference(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), IsLegalToCallImmediateAddr(), llvm::X86TargetLowering::resetOperationActions(), and X86Subtarget().
bool llvm::X86Subtarget::isTargetFreeBSD () const inline
Definition at line 406 of file X86Subtarget.h.
References llvm::Triple::isOSFreeBSD(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
bool llvm::X86Subtarget::isTargetKnownWindowsMSVC () const inline
Definition at line 423 of file X86Subtarget.h.
References llvm::Triple::isKnownWindowsMSVCEnvironment(), and TargetTriple.
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::GetCPISymbol(), llvm::X86TargetLowering::isTargetFTOL(), isTargetWin32(), and llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::isTargetLinux () const inline
Definition at line 414 of file X86Subtarget.h.
References llvm::Triple::isOSLinux(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), and llvm::X86TargetLowering::getStackCookieLocation().
bool llvm::X86Subtarget::isTargetMachO () const inline
Definition at line 412 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatMachO(), and TargetTriple.
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::X86FrameLowering::emitPrologue(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), and llvm::X86TargetLowering::useLoadStackGuardNode().
bool llvm::X86Subtarget::isTargetNaCl () const inline
Definition at line 415 of file X86Subtarget.h.
References llvm::Triple::isOSNaCl(), and TargetTriple.
Referenced by isTargetNaCl32(), and isTargetNaCl64().
bool llvm::X86Subtarget::isTargetNaCl32 () const inline
Definition at line 416 of file X86Subtarget.h.
References is64Bit(), and isTargetNaCl().
bool llvm::X86Subtarget::isTargetNaCl64 () const inline
Definition at line 417 of file X86Subtarget.h.
References is64Bit(), and isTargetNaCl().
Referenced by llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), and llvm::X86RegisterInfo::X86RegisterInfo().
bool llvm::X86Subtarget::isTargetSolaris () const inline
Definition at line 408 of file X86Subtarget.h.
References llvm::Triple::isOSSolaris(), and TargetTriple.
bool llvm::X86Subtarget::isTargetWin32 () const inline
Definition at line 447 of file X86Subtarget.h.
References isTargetCygMing(), and isTargetKnownWindowsMSVC().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), and IsLegalToCallImmediateAddr().
bool llvm::X86Subtarget::isTargetWin64 () const inline
Definition at line 443 of file X86Subtarget.h.
References llvm::Triple::isOSWindows(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), ClassifyGlobalReference(), llvm::X86FrameLowering::emitPrologue(), llvm::X86RegisterInfo::getPointerRegClass(), isCallingConvWin64(), llvm::X86TargetLowering::resetOperationActions(), llvm::X86RegisterInfo::X86RegisterInfo(), and llvm::X86TargetMachine::X86TargetMachine().
bool llvm::X86Subtarget::isTargetWindowsCygwin () const inline
Definition at line 427 of file X86Subtarget.h.
References llvm::Triple::isWindowsCygwinEnvironment(), and TargetTriple.
bool llvm::X86Subtarget::isTargetWindowsGNU () const inline
Definition at line 431 of file X86Subtarget.h.
References llvm::Triple::isWindowsGNUEnvironment(), and TargetTriple.
Referenced by llvm::X86TargetLowering::resetOperationActions().
bool llvm::X86Subtarget::isTargetWindowsItanium () const inline
Definition at line 435 of file X86Subtarget.h.
References llvm::Triple::isWindowsItaniumEnvironment(), and TargetTriple.
bool llvm::X86Subtarget::isTargetWindowsMSVC () const inline
Definition at line 419 of file X86Subtarget.h.
References llvm::Triple::isWindowsMSVCEnvironment(), and TargetTriple.
bool llvm::X86Subtarget::isUnalignedMem32Slow () const inline
Definition at line 380 of file X86Subtarget.h.
References IsUAMem32Slow.
Referenced by PerformLOADCombine(), and PerformSTORECombine().
bool llvm::X86Subtarget::isUnalignedMemAccessFast () const inline
Definition at line 379 of file X86Subtarget.h.
References IsUAMemFast.
Referenced by llvm::X86TargetLowering::allowsMisalignedMemoryAccesses(), llvm::X86TargetLowering::getOptimalMemOpType(), and llvm::X86InstrInfo::unfoldMemoryOperand().
bool llvm::X86Subtarget::LEAusesAG () const inline
Definition at line 388 of file X86Subtarget.h.
References LEAUsesAG.
bool llvm::X86Subtarget::padShortFunctions () const inline
Definition at line 386 of file X86Subtarget.h.
References PadShortFunctions.
void llvm::X86Subtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
void llvm::X86Subtarget::setPICStyle (PICStyles::Style Style) inline
Definition at line 336 of file X86Subtarget.h.
References PICStyle.
Referenced by X86Subtarget().
bool llvm::X86Subtarget::slowIncDec () const inline
Definition at line 390 of file X86Subtarget.h.
References SlowIncDec.
Referenced by getAtomicLoadArithTargetConstant().
bool llvm::X86Subtarget::slowLEA () const inline
Definition at line 389 of file X86Subtarget.h.
References SlowLEA.
bool llvm::X86Subtarget::useLeaForSP () const inline
Definition at line 383 of file X86Subtarget.h.
References UseLeaForSP.
Referenced by llvm::X86FrameLowering::emitEpilogue(), and llvm::X86FrameLowering::emitPrologue().
bool llvm::X86Subtarget::useReciprocalEst () const inline
Definition at line 392 of file X86Subtarget.h.
References UseReciprocalEst.
bool llvm::X86Subtarget::useSqrtEst () const inline
Definition at line 391 of file X86Subtarget.h.
References UseSqrtEst.
Member Data Documentation
bool llvm::X86Subtarget::CallRegIndirect protected
CallRegIndirect - True if the Calls with memory reference should be converted to a register-based indirect call.
Definition at line 191 of file X86Subtarget.h.
Referenced by callRegIndirect().
bool llvm::X86Subtarget::HasADX protected
HasADX - Processor has ADX instructions.
Definition at line 136 of file X86Subtarget.h.
Referenced by hasADX().
bool llvm::X86Subtarget::HasAES protected
HasAES - Target has AES instructions.
Definition at line 91 of file X86Subtarget.h.
Referenced by hasAES().
bool llvm::X86Subtarget::HasBMI protected
HasBMI - Processor has BMI1 instructions.
Definition at line 124 of file X86Subtarget.h.
Referenced by hasBMI().
bool llvm::X86Subtarget::HasBMI2 protected
HasBMI2 - Processor has BMI2 instructions.
Definition at line 127 of file X86Subtarget.h.
Referenced by hasBMI2().
bool llvm::X86Subtarget::HasBWI protected
Processor has AVX-512 Byte and Word instructions.
Definition at line 225 of file X86Subtarget.h.
Referenced by hasBWI().
bool llvm::X86Subtarget::HasCDI protected
Processor has AVX-512 Conflict Detection Instructions.
Definition at line 219 of file X86Subtarget.h.
Referenced by hasCDI().
bool llvm::X86Subtarget::HasCMov protected
HasCMov - True if this processor has conditional move instructions (generally pentium pro+).
Definition at line 78 of file X86Subtarget.h.
Referenced by hasCMov().
bool llvm::X86Subtarget::HasCmpxchg16b protected
HasCmpxchg16b - True if this processor has the CMPXCHG16B instruction; this is true for most x86-64 chips, but not the first AMD chips.
Definition at line 171 of file X86Subtarget.h.
Referenced by hasCmpxchg16b().
bool llvm::X86Subtarget::HasDQI protected
Processor has AVX-512 Doubleword and Quadword instructions.
Definition at line 222 of file X86Subtarget.h.
Referenced by hasDQI().
bool llvm::X86Subtarget::HasERI protected
Processor has AVX-512 Exponential and Reciprocal Instructions.
Definition at line 216 of file X86Subtarget.h.
Referenced by hasERI().
bool llvm::X86Subtarget::HasF16C protected
HasF16C - Processor has 16-bit floating point conversion instructions.
Definition at line 115 of file X86Subtarget.h.
Referenced by hasF16C().
bool llvm::X86Subtarget::HasFMA protected
HasFMA - Target has 3-operand fused multiply-add.
Definition at line 97 of file X86Subtarget.h.
Referenced by hasFMA(), and hasFMA4().
bool llvm::X86Subtarget::HasFMA4 protected
HasFMA4 - Target has 4-operand fused multiply-add.
Definition at line 100 of file X86Subtarget.h.
Referenced by hasFMA4().
bool llvm::X86Subtarget::HasFSGSBase protected
HasFSGSBase - Processor has FS/GS base insturctions.
Definition at line 118 of file X86Subtarget.h.
Referenced by hasFSGSBase().
bool llvm::X86Subtarget::HasHLE protected
HasHLE - Processor has HLE.
Definition at line 133 of file X86Subtarget.h.
Referenced by hasHLE().
bool llvm::X86Subtarget::HasLZCNT protected
HasLZCNT - Processor has LZCNT instruction.
Definition at line 121 of file X86Subtarget.h.
Referenced by hasLZCNT().
bool llvm::X86Subtarget::HasMOVBE protected
HasMOVBE - True if the processor has the MOVBE instruction.
Definition at line 109 of file X86Subtarget.h.
Referenced by hasMOVBE().
bool llvm::X86Subtarget::HasPCLMUL protected
HasPCLMUL - Target has carry-less multiplication.
Definition at line 94 of file X86Subtarget.h.
Referenced by hasPCLMUL().
bool llvm::X86Subtarget::HasPFI protected
Processor has AVX-512 PreFetch Instructions.
Definition at line 213 of file X86Subtarget.h.
Referenced by hasPFI().
bool llvm::X86Subtarget::HasPOPCNT protected
HasPOPCNT - True if the processor supports POPCNT.
Definition at line 85 of file X86Subtarget.h.
Referenced by hasPOPCNT().
bool llvm::X86Subtarget::HasPRFCHW protected
HasPRFCHW - Processor has PRFCHW instructions.
Definition at line 145 of file X86Subtarget.h.
Referenced by hasPRFCHW().
bool llvm::X86Subtarget::HasRDRAND protected
HasRDRAND - True if the processor has the RDRAND instruction.
Definition at line 112 of file X86Subtarget.h.
Referenced by hasRDRAND().
bool llvm::X86Subtarget::HasRDSEED protected
HasRDSEED - Processor has RDSEED instructions.
Definition at line 148 of file X86Subtarget.h.
Referenced by hasRDSEED().
bool llvm::X86Subtarget::HasRTM protected
HasRTM - Processor has RTM instructions.
Definition at line 130 of file X86Subtarget.h.
Referenced by hasRTM().
bool llvm::X86Subtarget::HasSGX protected
HasSGX - Processor has SGX instructions.
Definition at line 142 of file X86Subtarget.h.
Referenced by hasSGX().
bool llvm::X86Subtarget::HasSHA protected
HasSHA - Processor has SHA instructions.
Definition at line 139 of file X86Subtarget.h.
Referenced by hasSHA().
bool llvm::X86Subtarget::HasSlowDivide32 protected
HasSlowDivide32 - True if 8-bit divisions are significantly faster than 32-bit divisions and should be used when possible.
Definition at line 179 of file X86Subtarget.h.
Referenced by hasSlowDivide32().
bool llvm::X86Subtarget::HasSlowDivide64 protected
HasSlowDivide64 - True if 16-bit divides are significantly faster than 64-bit divisions and should be used when possible.
Definition at line 183 of file X86Subtarget.h.
Referenced by hasSlowDivide64().
bool llvm::X86Subtarget::HasSMAP protected
HasSMAP - Processor has SMAP instructions.
Definition at line 151 of file X86Subtarget.h.
Referenced by hasSMAP().
bool llvm::X86Subtarget::HasSSE4A protected
HasSSE4A - True if the processor supports SSE4A instructions.
Definition at line 88 of file X86Subtarget.h.
Referenced by hasSSE4A().
bool llvm::X86Subtarget::HasSSEUnalignedMem protected
True if SSE operations can have unaligned memory operands. This may require setting a configuration bit in the processor.
Definition at line 167 of file X86Subtarget.h.
Referenced by hasSSEUnalignedMem().
bool llvm::X86Subtarget::HasTBM protected
HasTBM - Target has TBM instructions.
Definition at line 106 of file X86Subtarget.h.
Referenced by hasTBM().
bool llvm::X86Subtarget::HasVLX protected
Processor has AVX-512 Vector Length eXtenstions.
Definition at line 228 of file X86Subtarget.h.
Referenced by hasVLX().
bool llvm::X86Subtarget::HasX86_64 protected
HasX86_64 - True if the processor supports X86-64 instructions.
Definition at line 82 of file X86Subtarget.h.
bool llvm::X86Subtarget::HasXOP protected
HasXOP - Target has XOP instructions.
Definition at line 103 of file X86Subtarget.h.
Referenced by hasXOP().
InstrItineraryData llvm::X86Subtarget::InstrItins protected
Instruction itineraries for scheduling.
Definition at line 242 of file X86Subtarget.h.
Referenced by getInstrItineraryData().
bool llvm::X86Subtarget::IsBTMemSlow protected
IsBTMemSlow - True if BT (bit test) of memory instructions are slow.
Definition at line 154 of file X86Subtarget.h.
Referenced by isBTMemSlow().
bool llvm::X86Subtarget::IsSHLDSlow protected
IsSHLDSlow - True if SHLD instructions are slow.
Definition at line 157 of file X86Subtarget.h.
Referenced by isSHLDSlow().
bool llvm::X86Subtarget::IsUAMem32Slow protected
True if unaligned 32-byte memory accesses are slow.
Definition at line 163 of file X86Subtarget.h.
Referenced by isUnalignedMem32Slow().
bool llvm::X86Subtarget::IsUAMemFast protected
IsUAMemFast - True if unaligned memory access is fast.
Definition at line 160 of file X86Subtarget.h.
Referenced by isUnalignedMemAccessFast().
bool llvm::X86Subtarget::LEAUsesAG protected
LEAUsesAG - True if the LEA instruction inputs have to be ready at address generation (AG) time.
Definition at line 194 of file X86Subtarget.h.
Referenced by LEAusesAG().
unsigned llvm::X86Subtarget::MaxInlineSizeThreshold protected
Max. memset / memcpy size that is turned into rep/movs, rep/stos ops.
Definition at line 236 of file X86Subtarget.h.
Referenced by getMaxInlineSizeThreshold().
bool llvm::X86Subtarget::PadShortFunctions protected
PadShortFunctions - True if the short functions should be padded to prevent a stall when returning too early.
Definition at line 187 of file X86Subtarget.h.
Referenced by padShortFunctions().
PICStyles::Style llvm::X86Subtarget::PICStyle protected
PICStyle - Which PIC style to use
Definition at line 66 of file X86Subtarget.h.
Referenced by getPICStyle(), isPICStyleGOT(), isPICStyleRIPRel(), isPICStyleSet(), isPICStyleStubAny(), isPICStyleStubNoDynamic(), isPICStyleStubPIC(), and setPICStyle().
bool llvm::X86Subtarget::SlowIncDec protected
SlowIncDec - True if INC and DEC instructions are slow when writing to flags.
Definition at line 200 of file X86Subtarget.h.
Referenced by slowIncDec().
bool llvm::X86Subtarget::SlowLEA protected
SlowLEA - True if the LEA instruction with certain arguments is slow.
Definition at line 197 of file X86Subtarget.h.
Referenced by slowLEA().
unsigned llvm::X86Subtarget::stackAlignment protected
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
Definition at line 232 of file X86Subtarget.h.
Referenced by getStackAlignment().
Triple llvm::X86Subtarget::TargetTriple protected
TargetTriple - What processor and OS we're targeting.
Definition at line 239 of file X86Subtarget.h.
Referenced by getTargetTriple(), isOSWindows(), isTarget64BitILP32(), isTarget64BitLP64(), isTargetCOFF(), isTargetCygMing(), isTargetDarwin(), isTargetDragonFly(), isTargetELF(), isTargetFreeBSD(), isTargetKnownWindowsMSVC(), isTargetLinux(), isTargetMachO(), isTargetNaCl(), isTargetSolaris(), isTargetWin64(), isTargetWindowsCygwin(), isTargetWindowsGNU(), isTargetWindowsItanium(), and isTargetWindowsMSVC().
bool llvm::X86Subtarget::UseLeaForSP protected
UseLeaForSP - True if the LEA instruction should be used for adjusting the stack pointer. This is an optimization for Intel Atom processors.
Definition at line 175 of file X86Subtarget.h.
Referenced by useLeaForSP().
bool llvm::X86Subtarget::UseReciprocalEst protected
Use the RCP* instructions to optimize FP division calculations. For this to be profitable, the cost of FDIV must be substantially higher than normal FP ops like FADD and FMUL.
Definition at line 210 of file X86Subtarget.h.
Referenced by useReciprocalEst().
bool llvm::X86Subtarget::UseSqrtEst protected
Use the RSQRT* instructions to optimize square root calculations. For this to be profitable, the cost of FSQRT and FDIV must be substantially higher than normal FP ops like FADD and FMUL.
Definition at line 205 of file X86Subtarget.h.
Referenced by useSqrtEst().
X863DNowEnum llvm::X86Subtarget::X863DNowLevel protected
X863DNowLevel - 3DNow or 3DNow Athlon, or none supported.
Definition at line 74 of file X86Subtarget.h.
Referenced by has3DNow(), and has3DNowA().
X86ProcFamilyEnum llvm::X86Subtarget::X86ProcFamily protected
X86ProcFamily - X86 processor family: Intel Atom, and others.
Definition at line 62 of file X86Subtarget.h.
Referenced by isAtom(), and isSLM().
X86SSEEnum llvm::X86Subtarget::X86SSELevel protected
X86SSELevel - MMX, SSE1, SSE2, SSE3, SSSE3, SSE41, SSE42, or none supported.
Definition at line 70 of file X86Subtarget.h.
Referenced by hasAVX(), hasAVX2(), hasAVX512(), hasMMX(), hasSSE1(), hasSSE2(), hasSSE3(), hasSSE41(), hasSSE42(), and hasSSSE3().
The documentation for this class was generated from the following files:
X86Subtarget.h
X86Subtarget.cpp