LLVM: llvm::StringMapEntryBase Class Reference
LLVM API Documentation
llvm::StringMapEntryBase Class Reference
StringMapEntryBase - Shared base class of StringMapEntry instances.
#include <StringMap.h>
Public Member Functions
StringMapEntryBase (unsigned Len)
unsigned getKeyLength () const
Detailed Description
StringMapEntryBase - Shared base class of StringMapEntry instances.
Definition at line 31 of file StringMap.h.
Constructor & Destructor Documentation
llvm::StringMapEntryBase::StringMapEntryBase (unsigned Len) inline explicit
Definition at line 34 of file StringMap.h.
Member Function Documentation
unsigned llvm::StringMapEntryBase::getKeyLength () const inline
Definition at line 36 of file StringMap.h.
Referenced by llvm::StringMapEntry< llvm::Comdat >::Destroy(), llvm::PooledStringPtr::end(), llvm::StringMapImpl::FindKey(), llvm::StringMapEntry< llvm::Comdat >::first(), llvm::TargetIntrinsicInfo::getIntrinsicID(), llvm::StringMapEntry< llvm::Comdat >::getKey(), llvm::StringMapImpl::LookupBucketFor(), llvm::StringMapImpl::RemoveKey(), llvm::PooledStringPtr::size(), and WriteValueSymbolTable().
The documentation for this class was generated from the following file:
StringMap.h