LLVM: llvm::DIEBlock Class Reference
LLVM API Documentation
llvm::DIEBlock Class Reference
DIEBlock - Represents a block of values.
#include <DIE.h>
Public Member Functions
DIEBlock ()
unsigned ComputeSize (AsmPrinter *AP) const
dwarf::Form BestForm () const
void EmitValue (AsmPrinter *AP, dwarf::Form Form) const override
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
void print (raw_ostream &O) const override
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Public Member Functions inherited from llvm::DIE
DIE (dwarf::Tag Tag)
DIEAbbrev & getAbbrev ()
const DIEAbbrev & getAbbrev () const
unsigned getAbbrevNumber () const
dwarf::Tag getTag () const
unsigned getOffset () const
unsigned getSize () const
const std::vector
< std::unique_ptr< DIE > > & getChildren () const
const SmallVectorImpl
< DIEValue * > & getValues () const
DIE * getParent () const
const DIE * getUnit () const
const DIE * getUnitOrNull () const
void setOffset (unsigned O)
void setSize (unsigned S)
void addValue (dwarf::Attribute Attribute, dwarf::Form Form, DIEValue *Value)
void addChild (std::unique_ptr< DIE > Child)
DIEValue * findAttribute (dwarf::Attribute Attribute) const
void print (raw_ostream &O, unsigned IndentCount=0) const
void dump ()
Static Public Member Functions
static bool classof (const DIEValue *E)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger, isString, isExpr, isLabel,
isDelta, isEntry, isTypeSignature, isBlock,
isLoc, isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Member Functions inherited from llvm::DIE
DIE ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Protected Attributes inherited from llvm::DIE
unsigned Offset
unsigned Size
DIEAbbrev Abbrev
std::vector< std::unique_ptr
< DIE > > Children
DIE * Parent
SmallVector< DIEValue *, 12 > Values
Detailed Description
DIEBlock - Represents a block of values.
Definition at line 518 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEBlock::DIEBlock () inline
Definition at line 521 of file DIE.h.
Member Function Documentation
dwarf::Form llvm::DIEBlock::BestForm () const inline
BestForm - Choose the best form for data.
Definition at line 529 of file DIE.h.
References llvm::dwarf::DW_FORM_block, llvm::dwarf::DW_FORM_block1, llvm::dwarf::DW_FORM_block2, and llvm::dwarf::DW_FORM_block4.
Referenced by llvm::DwarfUnit::addBlock().
static bool llvm::DIEBlock::classof (const DIEValue * E) inline static
Definition at line 548 of file DIE.h.
References llvm::DIEValue::getType(), and llvm::DIEValue::isBlock.
unsigned DIEBlock::ComputeSize (AsmPrinter * AP) const
ComputeSize - Calculate the size of the location expression.
ComputeSize - calculate the size of the block.
Definition at line 518 of file DIE.cpp.
References llvm::DIE::Abbrev, llvm::DIEAbbrev::getData(), N, SizeOf(), and llvm::DIE::Values.
Referenced by llvm::DwarfUnit::addBlock().
void DIEBlock::EmitValue (AsmPrinter * Asm, dwarf::Form Form) const override virtual
EmitValue - Emit location data.
EmitValue - Emit block data.
Implements llvm::DIEValue.
Definition at line 530 of file DIE.cpp.
References llvm::DIE::Abbrev, llvm::dwarf::DW_FORM_block, llvm::dwarf::DW_FORM_block1, llvm::dwarf::DW_FORM_block2, llvm::dwarf::DW_FORM_block4, llvm::AsmPrinter::EmitInt16(), llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitInt8(), llvm::AsmPrinter::EmitULEB128(), EmitValue(), llvm::DIEAbbrev::getData(), llvm_unreachable, N, and llvm::DIE::Values.
Referenced by EmitValue().
void DIEBlock::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 557 of file DIE.cpp.
References llvm::DIE::print().
unsigned DIEBlock::SizeOf (AsmPrinter * AP, dwarf::Form Form) const override virtual
SizeOf - Determine size of location data in bytes.
SizeOf - Determine size of block data in bytes.
Implements llvm::DIEValue.
Definition at line 546 of file DIE.cpp.
References llvm::dwarf::DW_FORM_block, llvm::dwarf::DW_FORM_block1, llvm::dwarf::DW_FORM_block2, llvm::dwarf::DW_FORM_block4, llvm::getULEB128Size(), and llvm_unreachable.
Referenced by ComputeSize().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp