LLVM: llvm::DICompileUnit Class Reference
LLVM API Documentation
llvm::DICompileUnit Class Reference
A wrapper for a compile unit.
#include <DebugInfo.h>
Public Member Functions
DICompileUnit (const MDNode *N=nullptr)
dwarf::SourceLanguage getLanguage () const
StringRef getProducer () const
bool isOptimized () const
StringRef getFlags () const
unsigned getRunTimeVersion () const
DIArray getEnumTypes () const
DIArray getRetainedTypes () const
DIArray getSubprograms () const
DIArray getGlobalVariables () const
DIArray getImportedEntities () const
void replaceSubprograms (DIArray Subprograms)
void replaceGlobalVariables (DIArray GlobalVariables)
StringRef getSplitDebugFilename () const
unsigned getEmissionKind () const
bool Verify () const
Public Member Functions inherited from llvm::DIScope
DIScope (const MDNode *N=nullptr)
DIScopeRef getContext () const
Get the parent scope.
StringRef getName () const
Get the scope name.
StringRef getFilename () const
StringRef getDirectory () const
DIScopeRef getRef () const
Generate a reference to this DIScope.
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T >
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Friends
class DIDescriptor
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagAccessibility = 1 << 0 | 1 << 1, FlagPrivate = 1, FlagProtected = 2, FlagPublic = 3,
FlagFwdDecl = 1 << 2, FlagAppleBlock = 1 << 3, FlagBlockByrefStruct = 1 << 4, FlagVirtual = 1 << 5,
FlagArtificial = 1 << 6, FlagExplicit = 1 << 7, FlagPrototyped = 1 << 8, FlagObjcClassComplete = 1 << 9,
FlagObjectPointer = 1 << 10, FlagVector = 1 << 11, FlagStaticMember = 1 << 12, FlagIndirectVariable = 1 << 13,
FlagLValueReference = 1 << 14, FlagRValueReference = 1 << 15
}
Accessibility flags.
Protected Member Functions inherited from llvm::DIScope
void printInternal (raw_ostream &OS) const
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy >
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
A wrapper for a compile unit.
Definition at line 565 of file DebugInfo.h.
Constructor & Destructor Documentation
llvm::DICompileUnit::DICompileUnit (const MDNode * N = nullptr) inline explicit
Definition at line 570 of file DebugInfo.h.
Member Function Documentation
unsigned llvm::DICompileUnit::getEmissionKind () const inline
Definition at line 591 of file DebugInfo.h.
DIArray DICompileUnit::getEnumTypes () const
Definition at line 780 of file DebugInfo.cpp.
References getNodeField().
Referenced by llvm::DwarfDebug::beginModule().
StringRef llvm::DICompileUnit::getFlags () const inline
Definition at line 578 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
DIArray DICompileUnit::getGlobalVariables () const
Definition at line 801 of file DebugInfo.cpp.
References getNodeField().
Referenced by llvm::DwarfDebug::beginModule().
DIArray DICompileUnit::getImportedEntities () const
Definition at line 808 of file DebugInfo.cpp.
References getNodeField().
Referenced by llvm::DwarfDebug::beginModule().
dwarf::SourceLanguage llvm::DICompileUnit::getLanguage () const inline
Definition at line 572 of file DebugInfo.h.
Referenced by llvm::DwarfUnit::getLanguage().
StringRef llvm::DICompileUnit::getProducer () const inline
Definition at line 575 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
DIArray DICompileUnit::getRetainedTypes () const
Definition at line 787 of file DebugInfo.cpp.
References getNodeField().
Referenced by llvm::DwarfDebug::beginModule().
unsigned llvm::DICompileUnit::getRunTimeVersion () const inline
Definition at line 579 of file DebugInfo.h.
StringRef llvm::DICompileUnit::getSplitDebugFilename () const inline
Definition at line 590 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
DIArray DICompileUnit::getSubprograms () const
Definition at line 794 of file DebugInfo.cpp.
References getNodeField().
Referenced by llvm::DwarfDebug::beginModule(), and llvm::makeSubprogramMap().
bool llvm::DICompileUnit::isOptimized () const inline
Definition at line 577 of file DebugInfo.h.
void DICompileUnit::replaceGlobalVariables (DIArray GlobalVariables)
Definition at line 823 of file DebugInfo.cpp.
References assert(), and Verify.
void DICompileUnit::replaceSubprograms (DIArray Subprograms)
Definition at line 815 of file DebugInfo.cpp.
References assert(), and Verify.
Referenced by AddOperand().
bool DICompileUnit::Verify () const
Definition at line 354 of file DebugInfo.cpp.
Referenced by llvm::DIDescriptor::Verify().
Friends And Related Function Documentation
friend class DIDescriptor friend
Definition at line 566 of file DebugInfo.h.
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp