LLVM: llvm::DIHeaderFieldIterator Class Reference
LLVM API Documentation
llvm::DIHeaderFieldIterator Class Reference
#include <DebugInfo.h>
Public Member Functions
DIHeaderFieldIterator ()
DIHeaderFieldIterator (StringRef Header)
StringRef operator* () const
const StringRef * operator-> () const
DIHeaderFieldIterator & operator++ ()
DIHeaderFieldIterator operator++ (int)
bool operator== (const DIHeaderFieldIterator &X) const
bool operator!= (const DIHeaderFieldIterator &X) const
StringRef getHeader () const
StringRef getCurrent () const
StringRef getPrefix () const
StringRef getSuffix () const
Detailed Description
Definition at line 61 of file DebugInfo.h.
Constructor & Destructor Documentation
llvm::DIHeaderFieldIterator::DIHeaderFieldIterator () inline
Definition at line 68 of file DebugInfo.h.
llvm::DIHeaderFieldIterator::DIHeaderFieldIterator (StringRef Header) inline
Definition at line 69 of file DebugInfo.h.
Member Function Documentation
StringRef llvm::DIHeaderFieldIterator::getCurrent () const inline
Definition at line 90 of file DebugInfo.h.
StringRef llvm::DIHeaderFieldIterator::getHeader () const inline
Definition at line 89 of file DebugInfo.h.
StringRef llvm::DIHeaderFieldIterator::getPrefix () const inline
Definition at line 91 of file DebugInfo.h.
References llvm::StringRef::begin(), and llvm::StringRef::slice().
Referenced by setTypeFlagsInHeader().
StringRef llvm::DIHeaderFieldIterator::getSuffix () const inline
Definition at line 96 of file DebugInfo.h.
References llvm::StringRef::begin(), llvm::StringRef::end(), llvm::StringRef::npos, and llvm::StringRef::slice().
Referenced by setTypeFlagsInHeader().
bool llvm::DIHeaderFieldIterator::operator!= (const DIHeaderFieldIterator & X) const inline
Definition at line 85 of file DebugInfo.h.
References llvm::X.
StringRef llvm::DIHeaderFieldIterator::operator* () const inline
Definition at line 71 of file DebugInfo.h.
DIHeaderFieldIterator& llvm::DIHeaderFieldIterator::operator++ () inline
Definition at line 73 of file DebugInfo.h.
DIHeaderFieldIterator llvm::DIHeaderFieldIterator::operator++ (int) inline
Definition at line 77 of file DebugInfo.h.
References llvm::X.
const StringRef* llvm::DIHeaderFieldIterator::operator-> () const inline
Definition at line 72 of file DebugInfo.h.
bool llvm::DIHeaderFieldIterator::operator== (const DIHeaderFieldIterator & X) const inline
Definition at line 82 of file DebugInfo.h.
References llvm::StringRef::data().
The documentation for this class was generated from the following file:
DebugInfo.h