LLVM: llvm::BitcodeReader Class Reference
LLVM API Documentation
llvm::BitcodeReader Class Reference
#include <BitcodeReader.h>
Public Member Functions
std::error_code Error (BitcodeError E, const Twine &Message)
std::error_code Error (BitcodeError E)
std::error_code Error (const Twine &Message)
BitcodeReader (MemoryBuffer *buffer, LLVMContext &C, DiagnosticHandlerFunction DiagnosticHandler)
BitcodeReader (DataStreamer *streamer, LLVMContext &C, DiagnosticHandlerFunction DiagnosticHandler)
~BitcodeReader ()
std::error_code materializeForwardReferencedFunctions ()
void FreeState ()
void releaseBuffer ()
bool isDematerializable (const GlobalValue *GV) const override
std::error_code materialize (GlobalValue *GV) override
std::error_code MaterializeModule (Module *M) override
std::vector< StructType * > getIdentifiedStructTypes () const override
void Dematerialize (GlobalValue *GV) override
std::error_code ParseBitcodeInto (Module *M)
Main interface to parsing a bitcode buffer.
ErrorOr< std::string > parseTriple ()
Cheap mechanism to just extract module triple.
Public Member Functions inherited from llvm::GVMaterializer
virtual ~GVMaterializer ()
Static Public Member Functions
static uint64_t decodeSignRotatedValue (uint64_t V)
Additional Inherited Members
Protected Member Functions inherited from llvm::GVMaterializer
GVMaterializer ()
Detailed Description
Definition at line 135 of file BitcodeReader.h.
Constructor & Destructor Documentation
BitcodeReader::BitcodeReader (MemoryBuffer * buffer, LLVMContext & C, DiagnosticHandlerFunction DiagnosticHandler) explicit
Definition at line 76 of file BitcodeReader.cpp.
BitcodeReader::BitcodeReader (DataStreamer * streamer, LLVMContext & C, DiagnosticHandlerFunction DiagnosticHandler) explicit
Definition at line 84 of file BitcodeReader.cpp.
llvm::BitcodeReader::~BitcodeReader () inline
Definition at line 224 of file BitcodeReader.h.
References FreeState().
Member Function Documentation
uint64_t BitcodeReader::decodeSignRotatedValue (uint64_t V) static
decodeSignRotatedValue - Decode a signed value stored with the sign bit in the LSB for dense VBR encoding.
Definition at line 1321 of file BitcodeReader.cpp.
Referenced by ReadWideAPInt().
void BitcodeReader::Dematerialize (GlobalValue *) override virtual
If the given GlobalValue is read in, and if the GVMaterializer supports it, release the memory for the GV, and set it up to be materialized lazily. If the Materializer doesn't support this capability, this method is a noop.
Reimplemented from llvm::GVMaterializer.
Definition at line 3536 of file BitcodeReader.cpp.
References assert(), llvm::Function::dropAllReferences(), llvm::dyn_cast(), isDematerializable(), and llvm::Function::setIsMaterializable().
std::error_code BitcodeReader::Error (BitcodeError E, const Twine & Message)
Definition at line 56 of file BitcodeReader.cpp.
References Error(), and llvm::make_error_code().
Referenced by materializeForwardReferencedFunctions(), MaterializeModule(), ParseBitcodeInto(), and parseTriple().
std::error_code BitcodeReader::Error (BitcodeError E)
Definition at line 65 of file BitcodeReader.cpp.
References Error(), and llvm::make_error_code().
std::error_code BitcodeReader::Error (const Twine & Message)
Definition at line 60 of file BitcodeReader.cpp.
References llvm::CorruptedBitcode, Error(), and llvm::make_error_code().
void BitcodeReader::FreeState ()
Definition at line 125 of file BitcodeReader.cpp.
References assert(), llvm::BitcodeReaderValueList::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::BitcodeReaderMDValueList::clear(), and std::swap().
Referenced by ~BitcodeReader().
std::vector< StructType * > BitcodeReader::getIdentifiedStructTypes () const override virtual
Implements llvm::GVMaterializer.
Definition at line 3600 of file BitcodeReader.cpp.
bool BitcodeReader::isDematerializable (const GlobalValue * GV) const override virtual
True if GV has been materialized and can be dematerialized back to whatever backing store this GVMaterializer uses.
Implements llvm::GVMaterializer.
Definition at line 3523 of file BitcodeReader.cpp.
References llvm::dyn_cast(), and llvm::GlobalValue::isDeclaration().
Referenced by Dematerialize().
std::error_code BitcodeReader::materialize (GlobalValue * GV) override virtual
Make sure the given GlobalValue is fully read.
Implements llvm::GVMaterializer.
Definition at line 3485 of file BitcodeReader.cpp.
References assert(), llvm::dyn_cast(), I, llvm::Function::isMaterializable(), llvm::BitstreamCursor::JumpToBit(), materializeForwardReferencedFunctions(), llvm::Function::setIsMaterializable(), and llvm::UpgradeIntrinsicCall().
Referenced by materializeForwardReferencedFunctions(), and MaterializeModule().
std::error_code BitcodeReader::materializeForwardReferencedFunctions ()
Definition at line 92 of file BitcodeReader.cpp.
References assert(), Error(), F(), llvm::Function::isMaterializable(), and materialize().
Referenced by materialize().
std::error_code BitcodeReader::MaterializeModule (Module * M) override virtual
Make sure the entire Module has been completely read.
Implements llvm::GVMaterializer.
Definition at line 3549 of file BitcodeReader.cpp.
References assert(), llvm::Module::begin(), llvm::Module::end(), Error(), F(), I, materialize(), llvm::SmallVectorTemplateCommon< T, typename >::size(), std::swap(), llvm::UpgradeDebugInfo(), llvm::UpgradeInstWithTBAATag(), and llvm::UpgradeIntrinsicCall().
std::error_code BitcodeReader::ParseBitcodeInto (Module * M)
Main interface to parsing a bitcode buffer.
Returns
true if an error occurred.
Definition at line 2324 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamCursor::AF_DontAutoprocessAbbrevs, llvm::BitstreamCursor::AtEndOfStream(), llvm::bitc::BLOCKINFO_BLOCK_ID, llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, Error(), llvm::BitstreamCursor::getAbbrevIDWidth(), llvm::BitstreamEntry::ID, llvm::BitstreamEntry::Kind, llvm::bitc::MODULE_BLOCK_ID, llvm::BitstreamCursor::Read(), llvm::BitstreamCursor::ReadBlockInfoBlock(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), and llvm::BitstreamEntry::SubBlock.
ErrorOr< std::string > BitcodeReader::parseTriple ()
Cheap mechanism to just extract module triple.
Returns
true if an error occurred.
Definition at line 2430 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, Error(), llvm::BitstreamEntry::ID, llvm::BitstreamEntry::Kind, llvm::bitc::MODULE_BLOCK_ID, llvm::BitstreamCursor::Read(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), and llvm::BitstreamEntry::SubBlock.
void BitcodeReader::releaseBuffer ()
Definition at line 3483 of file BitcodeReader.cpp.
The documentation for this class was generated from the following files:
BitcodeReader.h
BitcodeReader.cpp