LLVM: llvm::opt::Option Class Reference
LLVM API Documentation
llvm::opt::Option Class Reference
#include <Option.h>
Public Types
enum OptionClass {
GroupClass = 0, InputClass, UnknownClass, FlagClass,
JoinedClass, SeparateClass, RemainingArgsClass, CommaJoinedClass,
MultiArgClass, JoinedOrSeparateClass, JoinedAndSeparateClass
}
enum RenderStyleKind { RenderCommaJoinedStyle, RenderJoinedStyle, RenderSeparateStyle, RenderValuesStyle }
Public Member Functions
Option (const OptTable::Info *Info, const OptTable *Owner)
~Option ()
bool isValid () const
unsigned getID () const
OptionClass getKind () const
StringRef getName () const
Get the name of this option without any prefix.
const Option getGroup () const
const Option getAlias () const
const char * getAliasArgs () const
Get the alias arguments as a \0 separated list. E.g. ["foo", "bar"] would be returned as "foo\0bar\0".
StringRef getPrefix () const
Get the default prefix for this option.
std::string getPrefixedName () const
Get the name of this option with the default prefix.
unsigned getNumArgs () const
bool hasNoOptAsInput () const
RenderStyleKind getRenderStyle () const
bool hasFlag (unsigned Val) const
Test if this option has the flag Val.
const Option getUnaliasedOption () const
StringRef getRenderName () const
bool matches (OptSpecifier ID) const
Arg * accept (const ArgList &Args, unsigned &Index, unsigned ArgSize) const
void dump () const
Protected Attributes
const OptTable::Info * Info
const OptTable * Owner
Detailed Description
Option - Abstract representation for a single form of driver argument.
An Option class represents a form of option that the driver takes, for example how many arguments the option has and how they can be provided. Individual option instances store additional information about what group the option is a member of (if any), if the option is an alias, and a number of flags. At runtime the driver parses the command line into concrete Arg instances, each of which corresponds to a particular Option instance.
Definition at line 44 of file Option.h.
Member Enumeration Documentation
enum llvm::opt::Option::OptionClass
Enumerator
GroupClass
InputClass
UnknownClass
FlagClass
JoinedClass
SeparateClass
RemainingArgsClass
CommaJoinedClass
MultiArgClass
JoinedOrSeparateClass
JoinedAndSeparateClass
Definition at line 46 of file Option.h.
enum llvm::opt::Option::RenderStyleKind
Enumerator
RenderCommaJoinedStyle
RenderJoinedStyle
RenderSeparateStyle
RenderValuesStyle
Definition at line 60 of file Option.h.
Constructor & Destructor Documentation
Option::Option (const OptTable::Info * Info, const OptTable * Owner)
Definition at line 22 of file Option.cpp.
References assert(), FlagClass, getAlias(), getAliasArgs(), getKind(), Info, and isValid().
Option::~Option ()
Definition at line 38 of file Option.cpp.
Member Function Documentation
Arg * Option::accept (const ArgList & Args, unsigned & Index, unsigned ArgSize) const
accept - Potentially accept the current argument, returning a new Arg instance, or 0 if the option does not accept this argument (or the argument is missing values).
If the option accepts the current argument, accept() sets Index to the position where argument parsing should resume (even if the argument is missing values).
Parameters
ArgSize The number of bytes taken up by the matched Option prefix and name. This is used to determine where joined values start.
Definition at line 103 of file Option.cpp.
References llvm::ARM_PROC::A, CommaJoinedClass, FlagClass, getAliasArgs(), llvm::opt::ArgList::getArgString(), getID(), getKind(), getName(), getNumArgs(), llvm::opt::ArgList::getNumInputArgStrings(), getPrefix(), getUnaliasedOption(), llvm::opt::Arg::getValues(), JoinedAndSeparateClass, JoinedClass, JoinedOrSeparateClass, llvm_unreachable, llvm::opt::ArgList::MakeArgString(), llvm::Intrinsic::memcpy, MultiArgClass, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), RemainingArgsClass, SeparateClass, llvm::opt::Arg::setOwnsValues(), and llvm::LibFunc::strlen.
Referenced by llvm::opt::OptTable::ParseOneArg().
void Option::dump () const
Definition at line 41 of file Option.cpp.
References CommaJoinedClass, dump(), llvm::errs(), FlagClass, getAlias(), getGroup(), getKind(), getName(), getNumArgs(), GroupClass, Info, InputClass, isValid(), JoinedAndSeparateClass, JoinedClass, JoinedOrSeparateClass, MultiArgClass, P, llvm::opt::OptTable::Info::Prefixes, RemainingArgsClass, SeparateClass, and UnknownClass.
Referenced by llvm::opt::Arg::dump(), dump(), and llvm::opt::OptTable::OptTable().
const Option llvm::opt::Option::getAlias () const inline
Definition at line 101 of file Option.h.
References llvm::opt::OptTable::Info::AliasID, assert(), llvm::opt::OptTable::getOption(), Info, and Owner.
Referenced by dump(), getUnaliasedOption(), matches(), and Option().
const char* llvm::opt::Option::getAliasArgs () const inline
Get the alias arguments as a \0 separated list. E.g. ["foo", "bar"] would be returned as "foo\0bar\0".
Definition at line 109 of file Option.h.
References llvm::opt::OptTable::Info::AliasArgs, assert(), and Info.
Referenced by accept(), and Option().
const Option llvm::opt::Option::getGroup () const inline
Definition at line 95 of file Option.h.
References assert(), llvm::opt::OptTable::getOption(), llvm::opt::OptTable::Info::GroupID, Info, and Owner.
Referenced by dump(), and matches().
unsigned llvm::opt::Option::getID () const inline
Definition at line 79 of file Option.h.
References assert(), llvm::opt::OptTable::Info::ID, and Info.
Referenced by accept(), and matches().
OptionClass llvm::opt::Option::getKind () const inline
Definition at line 84 of file Option.h.
References assert(), Info, and llvm::opt::OptTable::Info::Kind.
Referenced by accept(), dump(), getOptionHelpName(), getRenderStyle(), and Option().
StringRef llvm::opt::Option::getName () const inline
Get the name of this option without any prefix.
Definition at line 90 of file Option.h.
References assert(), Info, and llvm::opt::OptTable::Info::Name.
Referenced by accept(), dump(), getPrefixedName(), getRenderName(), llvm::opt::DerivedArgList::MakeFlagArg(), llvm::opt::DerivedArgList::MakeJoinedArg(), llvm::opt::DerivedArgList::MakePositionalArg(), and llvm::opt::DerivedArgList::MakeSeparateArg().
unsigned llvm::opt::Option::getNumArgs () const inline
Definition at line 130 of file Option.h.
References Info, and llvm::opt::OptTable::Info::Param.
Referenced by accept(), dump(), and getOptionHelpName().
StringRef llvm::opt::Option::getPrefix () const inline
Get the default prefix for this option.
Definition at line 118 of file Option.h.
References Info, llvm::cl::Prefix, and llvm::opt::OptTable::Info::Prefixes.
Referenced by accept(), getPrefixedName(), llvm::opt::DerivedArgList::MakeFlagArg(), llvm::opt::DerivedArgList::MakeJoinedArg(), llvm::opt::DerivedArgList::MakePositionalArg(), and llvm::opt::DerivedArgList::MakeSeparateArg().
std::string llvm::opt::Option::getPrefixedName () const inline
Get the name of this option with the default prefix.
Definition at line 124 of file Option.h.
References getName(), getPrefix(), and llvm::MipsISD::Ret.
Referenced by getOptionHelpName().
StringRef llvm::opt::Option::getRenderName () const inline
getRenderName - Return the name to use when rendering this option.
Definition at line 174 of file Option.h.
References getName(), and getUnaliasedOption().
RenderStyleKind llvm::opt::Option::getRenderStyle () const inline
Definition at line 134 of file Option.h.
References CommaJoinedClass, FlagClass, llvm::opt::OptTable::Info::Flags, getKind(), GroupClass, Info, InputClass, JoinedAndSeparateClass, JoinedClass, JoinedOrSeparateClass, llvm_unreachable, MultiArgClass, RemainingArgsClass, RenderCommaJoinedStyle, llvm::opt::RenderJoined, RenderJoinedStyle, llvm::opt::RenderSeparate, RenderSeparateStyle, RenderValuesStyle, SeparateClass, and UnknownClass.
const Option llvm::opt::Option::getUnaliasedOption () const inline
getUnaliasedOption - Return the final option this option aliases (itself, if the option has no alias).
Definition at line 166 of file Option.h.
References getAlias(), getUnaliasedOption(), and isValid().
Referenced by accept(), getRenderName(), and getUnaliasedOption().
bool llvm::opt::Option::hasFlag (unsigned Val) const inline
Test if this option has the flag Val.
Definition at line 160 of file Option.h.
References llvm::opt::OptTable::Info::Flags, and Info.
Referenced by llvm::opt::OptTable::ParseOneArg().
bool llvm::opt::Option::hasNoOptAsInput () const inline
Definition at line 132 of file Option.h.
References llvm::opt::OptTable::Info::Flags, Info, and llvm::opt::RenderAsInput.
bool llvm::opt::Option::isValid () const inline
Definition at line 75 of file Option.h.
References Info.
Referenced by dump(), getUnaliasedOption(), matches(), and Option().
bool Option::matches (OptSpecifier ID) const
matches - Predicate for whether this option is part of the given option (which may be a group).
Note that matches against options which are an alias should never be done – aliases do not participate in matching and so such a query will always be false.
Definition at line 87 of file Option.cpp.
References getAlias(), getGroup(), llvm::opt::OptSpecifier::getID(), getID(), isValid(), and matches().
Referenced by llvm::opt::ArgList::eraseArg(), and matches().
Member Data Documentation
const OptTable::Info* llvm::opt::Option::Info protected
Definition at line 68 of file Option.h.
Referenced by dump(), getAlias(), getAliasArgs(), getGroup(), getID(), getKind(), getName(), getNumArgs(), getPrefix(), getRenderStyle(), hasFlag(), hasNoOptAsInput(), isValid(), and Option().
const OptTable* llvm::opt::Option::Owner protected
Definition at line 69 of file Option.h.
Referenced by getAlias(), and getGroup().
The documentation for this class was generated from the following files:
Option.h
Option.cpp