LLVM: llvm::RegionInfoPass Class Reference
LLVM API Documentation
llvm::RegionInfoPass Class Reference
#include <RegionInfo.h>
Public Member Functions
RegionInfoPass ()
~RegionInfoPass ()
RegionInfo & getRegionInfo ()
const RegionInfo & getRegionInfo () const
FunctionPass interface
bool runOnFunction (Function &F) override
void releaseMemory () override
void verifyAnalysis () const override
void getAnalysisUsage (AnalysisUsage &AU) const override
void print (raw_ostream &OS, const Module *) const override
void dump () const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 854 of file RegionInfo.h.
Constructor & Destructor Documentation
RegionInfoPass::RegionInfoPass () explicit
Definition at line 110 of file RegionInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeRegionInfoPassPass().
RegionInfoPass::~RegionInfoPass ()
Definition at line 114 of file RegionInfo.cpp.
Member Function Documentation
void RegionInfoPass::dump () const
Definition at line 149 of file RegionInfo.cpp.
References llvm::RegionInfoBase< RegionTr >::dump().
void RegionInfoPass::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 137 of file RegionInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::AnalysisUsage::addRequiredTransitive(), and llvm::AnalysisUsage::setPreservesAll().
RegionInfo& llvm::RegionInfoPass::getRegionInfo () inline
Definition at line 863 of file RegionInfo.h.
Referenced by llvm::DOTGraphTraits< RegionInfoPass * >::addCustomGraphFeatures(), llvm::DOTGraphTraits< RegionInfoPass * >::getEdgeAttributes(), llvm::GraphTraits< RegionInfoPass * >::getEntryNode(), llvm::DOTGraphTraits< RegionInfoPass * >::getNodeLabel(), llvm::GraphTraits< RegionInfoPass * >::nodes_begin(), and llvm::GraphTraits< RegionInfoPass * >::nodes_end().
const RegionInfo& llvm::RegionInfoPass::getRegionInfo () const inline
Definition at line 865 of file RegionInfo.h.
void RegionInfoPass::print (raw_ostream & O, const Module * M) const override virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 144 of file RegionInfo.cpp.
References llvm::RegionInfoBase< RegionTr >::print().
void RegionInfoPass::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 129 of file RegionInfo.cpp.
References llvm::RegionInfoBase< RegionTr >::releaseMemory().
Referenced by runOnFunction().
bool RegionInfoPass::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 118 of file RegionInfo.cpp.
References llvm::RegionInfo::recalculate(), and releaseMemory().
void RegionInfoPass::verifyAnalysis () const override virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented from llvm::Pass.
Definition at line 133 of file RegionInfo.cpp.
References llvm::RegionInfoBase< RegionTr >::verifyAnalysis().
Member Data Documentation
char RegionInfoPass::ID = 0 static
Definition at line 858 of file RegionInfo.h.
The documentation for this class was generated from the following files:
RegionInfo.h
RegionInfo.cpp