LLVM: llvm::ExecutionEngineState Class Reference
LLVM API Documentation
llvm::ExecutionEngineState Class Reference
Helper class for helping synchronize access to the global address map table. Access to this class should be serialized under a mutex.
#include <ExecutionEngine.h>
Classes
struct AddressMapConfig
Public Types
typedef ValueMap< const
GlobalValue *, void
*, AddressMapConfig > GlobalAddressMapTy
Public Member Functions
ExecutionEngineState (ExecutionEngine &EE)
GlobalAddressMapTy & getGlobalAddressMap ()
std::map< void *, AssertingVH
< const GlobalValue > > & getGlobalAddressReverseMap ()
void * RemoveMapping (const GlobalValue *ToUnmap)
Erase an entry from the mapping table.
Detailed Description
Helper class for helping synchronize access to the global address map table. Access to this class should be serialized under a mutex.
Definition at line 58 of file ExecutionEngine/ExecutionEngine.h.
Member Typedef Documentation
typedef ValueMap<const GlobalValue *, void *, AddressMapConfig> llvm::ExecutionEngineState::GlobalAddressMapTy
Definition at line 69 of file ExecutionEngine/ExecutionEngine.h.
Constructor & Destructor Documentation
ExecutionEngineState::ExecutionEngineState (ExecutionEngine & EE)
Definition at line 1274 of file ExecutionEngine.cpp.
Member Function Documentation
GlobalAddressMapTy& llvm::ExecutionEngineState::getGlobalAddressMap () inline
Definition at line 87 of file ExecutionEngine/ExecutionEngine.h.
Referenced by llvm::ExecutionEngine::addGlobalMapping(), llvm::ExecutionEngine::clearAllGlobalMappings(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::ExecutionEngine::getPointerToGlobal(), llvm::ExecutionEngine::getPointerToGlobalIfAvailable(), and llvm::ExecutionEngine::updateGlobalMapping().
std::map<void*, AssertingVH<const GlobalValue> >& llvm::ExecutionEngineState::getGlobalAddressReverseMap () inline
Definition at line 92 of file ExecutionEngine/ExecutionEngine.h.
Referenced by llvm::ExecutionEngine::addGlobalMapping(), llvm::ExecutionEngine::clearAllGlobalMappings(), llvm::ExecutionEngine::getGlobalValueAtAddress(), and llvm::ExecutionEngine::updateGlobalMapping().
void * ExecutionEngineState::RemoveMapping (const GlobalValue * ToUnmap)
Erase an entry from the mapping table.
Returns
The address that ToUnmap was happed to.
Definition at line 147 of file ExecutionEngine.cpp.
References llvm::ValueMap< KeyT, ValueT, Config >::end(), llvm::ValueMap< KeyT, ValueT, Config >::erase(), llvm::ValueMap< KeyT, ValueT, Config >::find(), I, and llvm::ValueMapIterator< DenseMapT, KeyT >::ValueTypeProxy::second.
Referenced by llvm::ExecutionEngine::clearGlobalMappingsFromModule(), and llvm::ExecutionEngine::updateGlobalMapping().
The documentation for this class was generated from the following files:
ExecutionEngine/ExecutionEngine.h
ExecutionEngine.cpp