LLVM: llvm::MCELFStreamer Class Reference
LLVM API Documentation
llvm::MCELFStreamer Class Reference
#include <MCELFStreamer.h>
Public Member Functions
MCELFStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &OS, MCCodeEmitter *Emitter)
MCELFStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &OS, MCCodeEmitter *Emitter, MCAssembler *Assembler)
virtual ~MCELFStreamer ()
void reset () override
state management
Public Member Functions inherited from llvm::MCObjectStreamer
void reset () override
state management
bool isIntegratedAssemblerRequired () const override
Object streamers require the integrated assembler.
MCSymbolData & getOrCreateSymbolData (const MCSymbol *Symbol)
void EmitFrames (MCAsmBackend *MAB)
void EmitCFISections (bool EH, bool Debug) override
void visitUsedSymbol (const MCSymbol &Sym) override
MCAssembler & getAssembler ()
void EmitLabel (MCSymbol *Symbol) override
void EmitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
void EmitValueImpl (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc()) override
void EmitULEB128Value (const MCExpr *Value) override
void EmitSLEB128Value (const MCExpr *Value) override
void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
void ChangeSection (const MCSection *Section, const MCExpr *Subsection) override
void EmitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
void EmitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
void EmitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void EmitBundleUnlock () override
Ends a bundle-locked group.
void EmitBytes (StringRef Data) override
void EmitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0) override
void EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit=0) override
bool EmitValueToOffset (const MCExpr *Offset, unsigned char Value) override
void EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override
EmitDwarfLocDirective - This implements the DWARF2.
void EmitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize)
void EmitDwarfAdvanceFrameAddr (const MCSymbol *LastLabel, const MCSymbol *Label)
void EmitGPRel32Value (const MCExpr *Value) override
void EmitGPRel64Value (const MCExpr *Value) override
void EmitFill (uint64_t NumBytes, uint8_t FillValue) override
void EmitZeros (uint64_t NumBytes) override
Emit NumBytes worth of zeros. This function properly handles data in virtual sections.
void FinishImpl () override
FinishImpl - Streamer specific finalization.
bool mayHaveInstructions () const override
Public Member Functions inherited from llvm::MCStreamer
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
MCContext & getContext () const
MCTargetStreamer * getTargetStreamer ()
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
unsigned getNumWinFrameInfos ()
ArrayRef< WinEH::FrameInfo * > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual unsigned EmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, unsigned CUID=0)
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
void EmitCFIStartProc (bool IsSimple)
void EmitCFIEndProc ()
virtual void EmitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void EmitCFIDefCfaOffset (int64_t Offset)
virtual void EmitCFIDefCfaRegister (int64_t Register)
virtual void EmitCFIOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFIRememberState ()
virtual void EmitCFIRestoreState ()
virtual void EmitCFISameValue (int64_t Register)
virtual void EmitCFIRestore (int64_t Register)
virtual void EmitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void EmitCFIEscape (StringRef Values)
virtual void EmitCFISignalFrame ()
virtual void EmitCFIUndefined (int64_t Register)
virtual void EmitCFIRegister (int64_t Register1, int64_t Register2)
virtual void EmitCFIWindowSave ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol)
virtual void EmitWinCFIEndProc ()
virtual void EmitWinCFIStartChained ()
virtual void EmitWinCFIEndChained ()
virtual void EmitWinCFIPushReg (unsigned Register)
virtual void EmitWinCFISetFrame (unsigned Register, unsigned Offset)
virtual void EmitWinCFIAllocStack (unsigned Size)
virtual void EmitWinCFISaveReg (unsigned Register, unsigned Offset)
virtual void EmitWinCFISaveXMM (unsigned Register, unsigned Offset)
virtual void EmitWinCFIPushFrame (bool Code)
virtual void EmitWinCFIEndProlog ()
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except)
virtual void EmitWinEHHandlerData ()
void EmitRawText (const Twine &String)
void Finish ()
Finish - Finish emission of machine code.
virtual bool isVerboseAsm () const
virtual bool hasRawTextSupport () const
virtual void AddComment (const Twine &T)
virtual raw_ostream & GetCommentOS ()
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
MCSectionSubPair getPreviousSection () const
unsigned GetSymbolOrder (const MCSymbol *Sym) const
void PushSection ()
bool PopSection ()
bool SubSection (const MCExpr *Subsection)
virtual void SwitchSection (const MCSection *Section, const MCExpr *Subsection=nullptr)
void SwitchSectionNoChange (const MCSection *Section, const MCExpr *Subsection=nullptr)
void AssignSection (MCSymbol *Symbol, const MCSection *Section)
virtual void EmitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void EmitLinkerOptions (ArrayRef< std::string > Kind)
virtual void EmitDataRegion (MCDataRegionType Kind)
EmitDataRegion - Note in the output the specified region Kind.
virtual void EmitVersionMin (MCVersionMinType, unsigned Major, unsigned Minor, unsigned Update)
EmitVersionMin - Specify the MachO minimum deployment target version.
virtual void EmitCOFFSectionIndex (MCSymbol const *Symbol)
virtual void EmitCOFFSecRel32 (MCSymbol const *Symbol)
virtual void EmitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
void EmitValue (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc())
virtual void EmitIntValue (uint64_t Value, unsigned Size)
void EmitULEB128IntValue (uint64_t Value, unsigned Padding=0)
void EmitSLEB128IntValue (int64_t Value)
void EmitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
MCStreamer Interface
void InitSections (bool NoExecStack) override
Create the default sections and set the initial one.
void ChangeSection (const MCSection *Section, const MCExpr *Subsection) override
void EmitLabel (MCSymbol *Symbol) override
void EmitAssemblerFlag (MCAssemblerFlag Flag) override
EmitAssemblerFlag - Note in the output the specified Flag.
void EmitThumbFunc (MCSymbol *Func) override
void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
bool EmitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute) override
EmitSymbolAttribute - Add the given Attribute to Symbol.
void EmitSymbolDesc (MCSymbol *Symbol, unsigned DescValue) override
void EmitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void BeginCOFFSymbolDef (const MCSymbol *Symbol) override
void EmitCOFFSymbolStorageClass (int StorageClass) override
void EmitCOFFSymbolType (int Type) override
void EndCOFFSymbolDef () override
EndCOFFSymbolDef - Marks the end of the symbol definition.
void EmitELFSize (MCSymbol *Symbol, const MCExpr *Value) override
void EmitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void EmitZerofill (const MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, unsigned ByteAlignment=0) override
void EmitTBSSSymbol (const MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment=0) override
void EmitValueImpl (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc()) override
void EmitFileDirective (StringRef Filename) override
void EmitIdent (StringRef IdentString) override
void EmitValueToAlignment (unsigned, int64_t, unsigned, unsigned) override
void Flush () override
Flush - Causes any cached state to be written out.
void FinishImpl () override
FinishImpl - Streamer specific finalization.
void EmitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
void EmitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void EmitBundleUnlock () override
Ends a bundle-locked group.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCObjectStreamer
MCObjectStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter)
MCObjectStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, MCAssembler *_Assembler)
~MCObjectStreamer ()
MCSectionData * getCurrentSectionData () const
MCFragment * getCurrentFragment () const
void insert (MCFragment *F)
MCDataFragment * getOrCreateDataFragment ()
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables ()
virtual void EmitRawTextImpl (StringRef String)
Detailed Description
Definition at line 30 of file MCELFStreamer.h.
Constructor & Destructor Documentation
llvm::MCELFStreamer::MCELFStreamer (MCContext & Context, MCAsmBackend & TAB, raw_ostream & OS, MCCodeEmitter * Emitter) inline
Definition at line 32 of file MCELFStreamer.h.
llvm::MCELFStreamer::MCELFStreamer (MCContext & Context, MCAsmBackend & TAB, raw_ostream & OS, MCCodeEmitter * Emitter, MCAssembler * Assembler) inline
Definition at line 37 of file MCELFStreamer.h.
MCELFStreamer::~MCELFStreamer () virtual
Definition at line 39 of file MCELFStreamer.cpp.
Member Function Documentation
void MCELFStreamer::BeginCOFFSymbolDef (const MCSymbol * Symbol) override virtual
BeginCOFFSymbolDef - Start emitting COFF symbol definition
Parameters
Symbol - The symbol to have its External & Type fields set.
Reimplemented from llvm::MCStreamer.
Definition at line 578 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::ChangeSection (const MCSection * , const MCExpr *) override virtual
ChangeSection - Update streamer for a new active section.
This is called by PopSection and SwitchSection, if the current section changes.
Reimplemented from llvm::MCStreamer.
Definition at line 90 of file MCELFStreamer.cpp.
References llvm::HexStyle::Asm, llvm::MCObjectStreamer::ChangeSection(), EmitLabel(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCObjectStreamer::getCurrentSectionData(), llvm::MCContext::getOrCreateSectionSymbol(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCAssembler::getSymbolData(), llvm::MCSectionData::isBundleLocked(), llvm::MCSymbol::isUndefined(), llvm::report_fatal_error(), llvm::ARMBuildAttrs::Section, llvm::MCELF::SetType(), and llvm::ELF::STT_SECTION.
void MCELFStreamer::EmitAssemblerFlag (MCAssemblerFlag Flag) override virtual
EmitAssemblerFlag - Note in the output the specified Flag.
Reimplemented from llvm::MCStreamer.
Definition at line 73 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCAsmBackend::handleAssemblerFlag(), llvm_unreachable, llvm::MCAF_Code16, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::MCAF_SubsectionsViaSymbols, llvm::MCAF_SyntaxUnified, and llvm::MCAssembler::setSubsectionsViaSymbols().
void MCELFStreamer::EmitBundleAlignMode (unsigned AlignPow2) override virtual
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
Reimplemented from llvm::MCStreamer.
Definition at line 490 of file MCELFStreamer.cpp.
References assert(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBundleAlignSize(), llvm::report_fatal_error(), and llvm::MCAssembler::setBundleAlignSize().
void MCELFStreamer::EmitBundleLock (bool AlignToEnd) override virtual
The following instructions are a bundle-locked group.
Parameters
AlignToEnd - If true, the bundle-locked group will be aligned to the end of a bundle.
Reimplemented from llvm::MCStreamer.
Definition at line 500 of file MCELFStreamer.cpp.
References llvm::MCSectionData::BundleLocked, llvm::MCSectionData::BundleLockedAlignToEnd, llvm::MCObjectStreamer::getAssembler(), llvm::MCObjectStreamer::getCurrentSectionData(), llvm::MCSectionData::isBundleLocked(), llvm::report_fatal_error(), llvm::MCSectionData::setBundleGroupBeforeFirstInst(), and llvm::MCSectionData::setBundleLockState().
void MCELFStreamer::EmitBundleUnlock () override virtual
Ends a bundle-locked group.
Reimplemented from llvm::MCStreamer.
Definition at line 515 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCObjectStreamer::getCurrentSectionData(), llvm::MCSectionData::isBundleGroupBeforeFirstInst(), llvm::MCSectionData::isBundleLocked(), llvm::MCSectionData::NotBundleLocked, llvm::report_fatal_error(), and llvm::MCSectionData::setBundleLockState().
void MCELFStreamer::EmitCOFFSymbolStorageClass (int StorageClass) override virtual
EmitCOFFSymbolStorageClass - Emit the storage class of the symbol.
Parameters
StorageClass - The storage class the symbol should have.
Reimplemented from llvm::MCStreamer.
Definition at line 582 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitCOFFSymbolType (int Type) override virtual
EmitCOFFSymbolType - Emit the type of the symbol.
Parameters
Type - A COFF type identifier (see COFF::SymbolType in X86COFF.h)
Reimplemented from llvm::MCStreamer.
Definition at line 586 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
EmitCommonSymbol - Emit a common symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol if non-zero. This must be a power of 2.
Implements llvm::MCStreamer.
Definition at line 244 of file MCELFStreamer.cpp.
References llvm::MCStreamer::AssignSection(), llvm::MCConstantExpr::Create(), llvm::ELF_STB_Local, llvm::MCObjectStreamer::getAssembler(), llvm::MCELF::GetBinding(), llvm::SectionKind::getBSS(), llvm::MCStreamer::getContext(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::ARMBuildAttrs::Section, llvm::MCELF::SetBinding(), llvm::MCSymbolData::setCommon(), llvm::MCSymbolData::setExternal(), llvm::MCSymbolData::setSize(), llvm::MCELF::SetType(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_NOBITS, llvm::ELF::STB_GLOBAL, and llvm::ELF::STT_OBJECT.
Referenced by EmitLocalCommonSymbol().
void MCELFStreamer::EmitELFSize (MCSymbol * Symbol, const MCExpr * Value) override virtual
EmitELFSize - Emit an ELF .size directive.
This corresponds to an assembler statement such as: .size symbol, expression
Reimplemented from llvm::MCStreamer.
Definition at line 273 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getOrCreateSymbolData(), and llvm::MCSymbolData::setSize().
void MCELFStreamer::EmitFileDirective (StringRef Filename) override virtual
EmitFileDirective - Switch to a new logical file. This is used to implement the '.file "foo.c"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 309 of file MCELFStreamer.cpp.
References llvm::MCAssembler::addFileName(), and llvm::MCObjectStreamer::getAssembler().
void MCELFStreamer::EmitIdent (StringRef IdentString) override virtual
Emit the "identifiers" directive. This implements the '.ident "version foo"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 313 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitBytes(), llvm::MCStreamer::EmitIntValue(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::SectionKind::getReadOnly(), llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHT_PROGBITS, and llvm::MCStreamer::SwitchSection().
void MCELFStreamer::EmitLabel (MCSymbol * Symbol) override virtual
EmitLabel - Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 61 of file MCELFStreamer.cpp.
References assert(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCObjectStreamer::getAssembler(), llvm::MCSectionELF::getFlags(), llvm::MCSymbol::getSection(), llvm::MCAssembler::getSymbolData(), llvm::MCSymbol::isUndefined(), llvm::ARMBuildAttrs::Section, llvm::MCELF::SetType(), llvm::ELF::SHF_TLS, and llvm::ELF::STT_TLS.
Referenced by ChangeSection(), and llvm::MipsELFStreamer::EmitLabel().
void MCELFStreamer::EmitLocalCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
EmitLocalCommonSymbol - Emit a local common (.lcomm) symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the common symbol in bytes.
Reimplemented from llvm::MCStreamer.
Definition at line 278 of file MCELFStreamer.cpp.
References EmitCommonSymbol(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCELF::SetBinding(), llvm::MCSymbolData::setExternal(), and llvm::ELF::STB_LOCAL.
bool MCELFStreamer::EmitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) override virtual
EmitSymbolAttribute - Add the given Attribute to Symbol.
Implements llvm::MCStreamer.
Definition at line 137 of file MCELFStreamer.cpp.
References CombineSymbolTypes(), llvm::MCObjectStreamer::getAssembler(), llvm::MCObjectStreamer::getCurrentSectionData(), llvm::MCAssembler::getIndirectSymbols(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCELF::GetType(), llvm::MCSA_ELF_TypeCommon, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_ELF_TypeGnuUniqueObject, llvm::MCSA_ELF_TypeIndFunction, llvm::MCSA_ELF_TypeNoType, llvm::MCSA_ELF_TypeObject, llvm::MCSA_ELF_TypeTLS, llvm::MCSA_Global, llvm::MCSA_Hidden, llvm::MCSA_IndirectSymbol, llvm::MCSA_Internal, llvm::MCSA_Invalid, llvm::MCSA_LazyReference, llvm::MCSA_Local, llvm::MCSA_NoDeadStrip, llvm::MCSA_PrivateExtern, llvm::MCSA_Protected, llvm::MCSA_Reference, llvm::MCSA_SymbolResolver, llvm::MCSA_Weak, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, llvm::MCSA_WeakReference, llvm::IndirectSymbolData::SectionData, llvm::MCELF::SetBinding(), llvm::MCSymbolData::setExternal(), llvm::MCELF::SetType(), llvm::MCELF::SetVisibility(), llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_TLS, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, llvm::ELF::STV_PROTECTED, llvm::ARMBuildAttrs::Symbol, and llvm::IndirectSymbolData::Symbol.
void MCELFStreamer::EmitSymbolDesc (MCSymbol * Symbol, unsigned DescValue) override virtual
EmitSymbolDesc - Set the DescValue for the Symbol.
Parameters
Symbol - The symbol to have its n_desc field set.
DescValue - The value to set into the n_desc field.
Reimplemented from llvm::MCStreamer.
Definition at line 574 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitTBSSSymbol (const MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment = 0) override virtual
EmitTBSSSymbol - Emit a thread local bss (.tbss) symbol.
Parameters
Section - The thread local common section.
Symbol - The thread local common symbol to emit.
Size - The size of the symbol.
ByteAlignment - The alignment of the thread local common symbol if non-zero. This must be a power of 2 on some targets.
Reimplemented from llvm::MCStreamer.
Definition at line 599 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitThumbFunc (MCSymbol * Func) override virtual
EmitThumbFunc - Note in the output that the specified Func is a Thumb mode function (ARM target only).
Reimplemented from llvm::MCStreamer.
Definition at line 570 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EmitValueImpl (const MCExpr * Value, unsigned Size, const SMLoc & Loc = SMLoc()) override virtual
EmitValue - Emit the expression Value into the output as a native integer of the given Size bytes.
This is used to implement assembler directives such as .word, .quad, etc.
Parameters
Value - The value to emit.
Size - The size of the integer (in bytes) to emit. This must match a native machine width.
Loc - The location of the expression for error reporting.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 288 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitValueImpl(), llvm::MCObjectStreamer::getCurrentSectionData(), and llvm::report_fatal_error().
Referenced by llvm::MipsELFStreamer::EmitValueImpl().
void MCELFStreamer::EmitValueToAlignment (unsigned ByteAlignment, int64_t Value, unsigned ValueSize, unsigned MaxBytesToEmit) override virtual
EmitValueToAlignment - Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
If the number of bytes need to emit for the alignment is not a multiple of ValueSize, then the contents of the emitted fill bytes is undefined.
This used to implement the .align assembler directive.
Parameters
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
Value - The value to use when filling bytes.
ValueSize - The size of the integer (in bytes) to emit for Value. This must match a native machine width.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented from llvm::MCStreamer.
Definition at line 296 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitValueToAlignment(), llvm::MCObjectStreamer::getCurrentSectionData(), and llvm::report_fatal_error().
void MCELFStreamer::EmitWeakReference (MCSymbol * Alias, const MCSymbol * Symbol) override virtual
EmitWeakReference - Emit an weak reference from Alias to Symbol.
This corresponds to an assembler statement such as: .weakref alias, symbol
Parameters
Alias - The alias that is being created.
Symbol - The symbol being aliased.
Reimplemented from llvm::MCStreamer.
Definition at line 110 of file MCELFStreamer.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCSymbol::setVariableValue(), and llvm::MCSymbolRefExpr::VK_WEAKREF.
void MCELFStreamer::EmitZerofill (const MCSection * Section, MCSymbol * Symbol = nullptr, uint64_t Size = 0, unsigned ByteAlignment = 0) override virtual
EmitZerofill - Emit the zerofill section and an optional symbol.
Parameters
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol if non-zero. This must be a power of 2 on some targets.
Implements llvm::MCStreamer.
Definition at line 594 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::EndCOFFSymbolDef () override virtual
EndCOFFSymbolDef - Marks the end of the symbol definition.
Reimplemented from llvm::MCStreamer.
Definition at line 590 of file MCELFStreamer.cpp.
References llvm_unreachable.
void MCELFStreamer::FinishImpl () override virtual
FinishImpl - Streamer specific finalization.
Reimplemented from llvm::MCStreamer.
Definition at line 553 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitFrames(), llvm::MCObjectStreamer::FinishImpl(), and Flush().
void MCELFStreamer::Flush () override virtual
Flush - Causes any cached state to be written out.
Reimplemented from llvm::MCStreamer.
Definition at line 529 of file MCELFStreamer.cpp.
References llvm::LCOMM::ByteAlignment, llvm::MCSectionData::getAlignment(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getOrCreateSectionData(), llvm::MCSymbol::getSection(), llvm::MCSymbolData::getSymbol(), llvm::ARMBuildAttrs::Section, llvm::MCSectionData::setAlignment(), llvm::MCSymbolData::setFragment(), and llvm::ARMBuildAttrs::Symbol.
Referenced by FinishImpl().
void MCELFStreamer::InitSections (bool NoExecStack) override virtual
Create the default sections and set the initial one.
Reimplemented from llvm::MCStreamer.
Definition at line 42 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitCodeAlignment(), llvm::MCContext::getAsmInfo(), llvm::MCObjectFileInfo::getBSSSection(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDataSection(), llvm::MCAsmInfo::getNonexecutableStackSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getTextSection(), and llvm::MCStreamer::SwitchSection().
void llvm::MCELFStreamer::reset () inline override virtual
state management
Reimplemented from llvm::MCStreamer.
Definition at line 45 of file MCELFStreamer.h.
References llvm::MCObjectStreamer::reset().
The documentation for this class was generated from the following files:
MCELFStreamer.h
MCELFStreamer.cpp