LLVM: llvm::DIETypeSignature Class Reference
LLVM API Documentation
llvm::DIETypeSignature Class Reference
A signature reference to a type unit.
#include <DIE.h>
Public Member Functions
DIETypeSignature (const DwarfTypeUnit &Unit)
void EmitValue (AsmPrinter *Asm, dwarf::Form Form) const override
Emit type unit signature.
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
Returns size of a ref_sig8 entry.
void print (raw_ostream &O) const override
void dump () const
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Static Public Member Functions
static bool classof (const DIEValue *E)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger, isString, isExpr, isLabel,
isDelta, isEntry, isTypeSignature, isBlock,
isLoc, isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Detailed Description
A signature reference to a type unit.
Definition at line 446 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIETypeSignature::DIETypeSignature (const DwarfTypeUnit & Unit) inline explicit
Definition at line 450 of file DIE.h.
Member Function Documentation
static bool llvm::DIETypeSignature::classof (const DIEValue * E) inline static
Definition at line 463 of file DIE.h.
References llvm::DIEValue::getType(), and llvm::DIEValue::isTypeSignature.
void DIETypeSignature::dump () const
Definition at line 454 of file DIE.cpp.
References llvm::dbgs(), and print().
void DIETypeSignature::EmitValue (AsmPrinter * Asm, dwarf::Form Form) const override virtual
Emit type unit signature.
Implements llvm::DIEValue.
Definition at line 444 of file DIE.cpp.
References assert(), llvm::dwarf::DW_FORM_ref_sig8, llvm::MCStreamer::EmitIntValue(), llvm::DwarfTypeUnit::getTypeSignature(), and llvm::AsmPrinter::OutStreamer.
void DIETypeSignature::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 450 of file DIE.cpp.
References llvm::format(), and llvm::DwarfTypeUnit::getTypeSignature().
Referenced by dump().
unsigned llvm::DIETypeSignature::SizeOf (AsmPrinter * AP, dwarf::Form Form) const inline override virtual
Returns size of a ref_sig8 entry.
Implements llvm::DIEValue.
Definition at line 457 of file DIE.h.
References assert(), and llvm::dwarf::DW_FORM_ref_sig8.
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp