LLVM: llvm::yaml::Scanner Class Reference
LLVM API Documentation
llvm::yaml::Scanner Class Reference
Scans YAML tokens from a MemoryBuffer.
Public Member Functions
Scanner (StringRef Input, SourceMgr &SM)
Scanner (MemoryBufferRef Buffer, SourceMgr &SM_)
Token & peekNext ()
Parse the next token and return it without popping it.
Token getNext ()
Parse the next token and pop it from the queue.
void printError (SMLoc Loc, SourceMgr::DiagKind Kind, const Twine &Message, ArrayRef< SMRange > Ranges=None)
void setError (const Twine &Message, StringRef::iterator Position)
void setError (const Twine &Message)
bool failed ()
Returns true if an error occurred while parsing.
Detailed Description
Scans YAML tokens from a MemoryBuffer.
Definition at line 260 of file YAMLParser.cpp.
Constructor & Destructor Documentation
Scanner::Scanner (StringRef Input, SourceMgr & SM)
Definition at line 704 of file YAMLParser.cpp.
Scanner::Scanner (MemoryBufferRef Buffer, SourceMgr & SM_)
Definition at line 708 of file YAMLParser.cpp.
Member Function Documentation
bool llvm::yaml::Scanner::failed () inline
Returns true if an error occurred while parsing.
Definition at line 292 of file YAMLParser.cpp.
Token Scanner::getNext ()
Parse the next token and pop it from the queue.
Definition at line 755 of file YAMLParser.cpp.
References llvm::iplist< NodeTy, Traits >::empty(), peekNext(), llvm::iplist< NodeTy, Traits >::pop_front(), and llvm::MipsISD::Ret.
Referenced by llvm::yaml::dumpTokens(), and llvm::yaml::scanTokens().
Token & Scanner::peekNext ()
Parse the next token and return it without popping it.
Definition at line 728 of file YAMLParser.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::iplist< NodeTy, Traits >::clear(), llvm::iplist< NodeTy, Traits >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::iplist< NodeTy, Traits >::front(), and llvm::ilist< NodeTy >::push_back().
Referenced by getNext().
void llvm::yaml::Scanner::printError (SMLoc Loc, SourceMgr::DiagKind Kind, const Twine & Message, ArrayRef< SMRange > Ranges = None) inline
Definition at line 271 of file YAMLParser.cpp.
References llvm::SourceMgr::PrintMessage(), and Ranges.
void llvm::yaml::Scanner::setError (const Twine & Message, StringRef::iterator Position) inline
Definition at line 276 of file YAMLParser.cpp.
References llvm::SourceMgr::DK_Error, and llvm::SMLoc::getFromPointer().
void llvm::yaml::Scanner::setError (const Twine & Message) inline
Definition at line 287 of file YAMLParser.cpp.
The documentation for this class was generated from the following file:
YAMLParser.cpp