LLVM: llvm::SystemZMCInstLower Class Reference
LLVM API Documentation
llvm::SystemZMCInstLower Class Reference
#include <SystemZMCInstLower.h>
Public Member Functions
SystemZMCInstLower (MCContext &ctx, SystemZAsmPrinter &asmPrinter)
void lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand lowerOperand (const MachineOperand &MO) const
const MCExpr * getExpr (const MachineOperand &MO, MCSymbolRefExpr::VariantKind Kind) const
Detailed Description
Definition at line 25 of file SystemZMCInstLower.h.
Constructor & Destructor Documentation
SystemZMCInstLower::SystemZMCInstLower (MCContext & ctx, SystemZAsmPrinter & asmPrinter)
Definition at line 29 of file SystemZMCInstLower.cpp.
Member Function Documentation
const MCExpr * SystemZMCInstLower::getExpr (const MachineOperand & MO, MCSymbolRefExpr::VariantKind Kind) const
Definition at line 34 of file SystemZMCInstLower.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, and llvm::ARMBuildAttrs::Symbol.
Referenced by lowerOperand().
void SystemZMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 92 of file SystemZMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), lowerOperand(), and llvm::MCInst::setOpcode().
MCOperand SystemZMCInstLower::lowerOperand (const MachineOperand & MO) const
Definition at line 77 of file SystemZMCInstLower.cpp.
References llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getExpr(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), getVariantKind(), llvm::MachineOperand::MO_Immediate, and llvm::MachineOperand::MO_Register.
Referenced by lower().
The documentation for this class was generated from the following files:
SystemZMCInstLower.h
SystemZMCInstLower.cpp