LLVM: llvm::MSP430MachineFunctionInfo Class Reference
LLVM API Documentation
llvm::MSP430MachineFunctionInfo Class Reference
#include <MSP430MachineFunctionInfo.h>
Public Member Functions
MSP430MachineFunctionInfo ()
MSP430MachineFunctionInfo (MachineFunction &MF)
unsigned getCalleeSavedFrameSize () const
void setCalleeSavedFrameSize (unsigned bytes)
int getRAIndex () const
void setRAIndex (int Index)
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
MSP430MachineFunctionInfo - This class is derived from MachineFunction and contains private MSP430 target-specific information for each MachineFunction.
Definition at line 23 of file MSP430MachineFunctionInfo.h.
Constructor & Destructor Documentation
llvm::MSP430MachineFunctionInfo::MSP430MachineFunctionInfo () inline
Definition at line 37 of file MSP430MachineFunctionInfo.h.
llvm::MSP430MachineFunctionInfo::MSP430MachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 39 of file MSP430MachineFunctionInfo.h.
Member Function Documentation
unsigned llvm::MSP430MachineFunctionInfo::getCalleeSavedFrameSize () const inline
Definition at line 42 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430FrameLowering::emitEpilogue(), and llvm::MSP430FrameLowering::emitPrologue().
int llvm::MSP430MachineFunctionInfo::getRAIndex () const inline
Definition at line 45 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430TargetLowering::getReturnAddressFrameIndex().
int llvm::MSP430MachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 48 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430TargetLowering::LowerVASTART().
void llvm::MSP430MachineFunctionInfo::setCalleeSavedFrameSize (unsigned bytes) inline
Definition at line 43 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430FrameLowering::spillCalleeSavedRegisters().
void llvm::MSP430MachineFunctionInfo::setRAIndex (int Index) inline
Definition at line 46 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430TargetLowering::getReturnAddressFrameIndex().
void llvm::MSP430MachineFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 49 of file MSP430MachineFunctionInfo.h.
The documentation for this class was generated from the following files:
MSP430MachineFunctionInfo.h
MSP430MachineFunctionInfo.cpp