LLVM: llvm::SparseBitVector< ElementSize > Class Template Reference
LLVM API Documentation
llvm::SparseBitVector< ElementSize > Class Template Reference
#include <SparseBitVector.h>
Public Types
typedef SparseBitVectorIterator iterator
Public Member Functions
SparseBitVector ()
~SparseBitVector ()
SparseBitVector (const SparseBitVector &RHS)
void clear ()
SparseBitVector & operator= (const SparseBitVector &RHS)
bool test (unsigned Idx)
void reset (unsigned Idx)
void set (unsigned Idx)
bool test_and_set (unsigned Idx)
bool operator!= (const SparseBitVector &RHS) const
bool operator== (const SparseBitVector &RHS) const
bool operator|= (const SparseBitVector &RHS)
bool operator&= (const SparseBitVector &RHS)
bool intersectWithComplement (const SparseBitVector &RHS)
bool intersectWithComplement (const SparseBitVector< ElementSize > *RHS) const
void intersectWithComplement (const SparseBitVector< ElementSize > &RHS1, const SparseBitVector< ElementSize > &RHS2)
void intersectWithComplement (const SparseBitVector< ElementSize > *RHS1, const SparseBitVector< ElementSize > *RHS2)
bool intersects (const SparseBitVector< ElementSize > *RHS) const
bool intersects (const SparseBitVector< ElementSize > &RHS) const
bool contains (const SparseBitVector< ElementSize > &RHS) const
int find_first () const
bool empty () const
unsigned count () const
iterator begin () const
iterator end () const
Detailed Description
template<unsigned ElementSize = 128>
class llvm::SparseBitVector< ElementSize >
Definition at line 283 of file SparseBitVector.h.
Member Typedef Documentation
template<unsigned ElementSize = 128> typedef SparseBitVectorIterator llvm::SparseBitVector< ElementSize >::iterator
Definition at line 449 of file SparseBitVector.h.
Constructor & Destructor Documentation
template<unsigned ElementSize = 128> llvm::SparseBitVector< ElementSize >::SparseBitVector () inline
Definition at line 451 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin().
template<unsigned ElementSize = 128> llvm::SparseBitVector< ElementSize >::~SparseBitVector () inline
Definition at line 455 of file SparseBitVector.h.
template<unsigned ElementSize = 128> llvm::SparseBitVector< ElementSize >::SparseBitVector (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 459 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::end(), and llvm::ilist< NodeTy >::push_back().
Member Function Documentation
template<unsigned ElementSize = 128> iterator llvm::SparseBitVector< ElementSize >::begin () const inline
Definition at line 813 of file SparseBitVector.h.
Referenced by llvm::dump().
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::clear () inline
Definition at line 470 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::clear().
Referenced by llvm::LiveVariables::runOnMachineFunction().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::contains (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 785 of file SparseBitVector.h.
template<unsigned ElementSize = 128> unsigned llvm::SparseBitVector< ElementSize >::count () const inline
Definition at line 804 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), and llvm::iplist< NodeTy, Traits >::end().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::empty () const inline
Definition at line 800 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::empty().
Referenced by llvm::LiveVariables::HandleVirtRegDef().
template<unsigned ElementSize = 128> iterator llvm::SparseBitVector< ElementSize >::end () const inline
Definition at line 817 of file SparseBitVector.h.
Referenced by llvm::dump().
template<unsigned ElementSize = 128> int llvm::SparseBitVector< ElementSize >::find_first () const inline
Definition at line 792 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::empty(), llvm::SparseBitVectorElement< ElementSize >::find_first(), and llvm::SparseBitVectorElement< ElementSize >::index().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::intersects (const SparseBitVector< ElementSize > * RHS) const inline
Definition at line 751 of file SparseBitVector.h.
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::intersects (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 756 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::empty(), and llvm::iplist< NodeTy, Traits >::end().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::intersectWithComplement (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 651 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::empty(), llvm::iplist< NodeTy, Traits >::end(), and llvm::iplist< NodeTy, Traits >::erase().
Referenced by llvm::SparseBitVector< ElementSize >::intersectWithComplement(), and llvm::operator-().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::intersectWithComplement (const SparseBitVector< ElementSize > * RHS) const inline
Definition at line 688 of file SparseBitVector.h.
References llvm::SparseBitVector< ElementSize >::intersectWithComplement().
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::intersectWithComplement (const SparseBitVector< ElementSize > & RHS1, const SparseBitVector< ElementSize > & RHS2) inline
Definition at line 695 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::clear(), llvm::iplist< NodeTy, Traits >::empty(), llvm::iplist< NodeTy, Traits >::end(), llvm::SparseBitVectorElement< ElementSize >::intersectWithComplement(), and llvm::ilist< NodeTy >::push_back().
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::intersectWithComplement (const SparseBitVector< ElementSize > * RHS1, const SparseBitVector< ElementSize > * RHS2) inline
Definition at line 746 of file SparseBitVector.h.
References llvm::SparseBitVector< ElementSize >::intersectWithComplement().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::operator!= (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 564 of file SparseBitVector.h.
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::operator&= (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 609 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::empty(), llvm::iplist< NodeTy, Traits >::end(), and llvm::iplist< NodeTy, Traits >::erase().
template<unsigned ElementSize = 128> SparseBitVector& llvm::SparseBitVector< ElementSize >::operator= (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 475 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::clear(), llvm::iplist< NodeTy, Traits >::end(), and llvm::ilist< NodeTy >::push_back().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::operator== (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 568 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), and llvm::iplist< NodeTy, Traits >::end().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::operator|= (const SparseBitVector< ElementSize > & RHS) inline
Definition at line 581 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::empty(), llvm::iplist< NodeTy, Traits >::end(), and llvm::ilist< NodeTy >::insert().
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::reset (unsigned Idx) inline
Definition at line 505 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::empty(), llvm::iplist< NodeTy, Traits >::end(), and llvm::iplist< NodeTy, Traits >::erase().
template<unsigned ElementSize = 128> void llvm::SparseBitVector< ElementSize >::set (unsigned Idx) inline
Definition at line 526 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::empty(), llvm::iplist< NodeTy, Traits >::end(), and llvm::ilist< NodeTy >::insert().
Referenced by llvm::LiveVariables::addNewBlock(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::LiveVariables::setPHIJoin(), llvm::SparseBitVector< ElementSize >::test_and_set(), and llvm::LiveIntervalUnion::verify().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::test (unsigned Idx) inline
Definition at line 490 of file SparseBitVector.h.
References llvm::iplist< NodeTy, Traits >::empty(), and llvm::iplist< NodeTy, Traits >::end().
Referenced by llvm::LiveVariables::addNewBlock(), llvm::LiveVariables::HandleVirtRegUse(), llvm::LiveVariables::isLiveOut(), llvm::LiveVariables::isPHIJoin(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), and llvm::SparseBitVector< ElementSize >::test_and_set().
template<unsigned ElementSize = 128> bool llvm::SparseBitVector< ElementSize >::test_and_set (unsigned Idx) inline
Definition at line 555 of file SparseBitVector.h.
References llvm::SparseBitVector< ElementSize >::set(), and llvm::SparseBitVector< ElementSize >::test().
The documentation for this class was generated from the following file:
SparseBitVector.h