LLVM: llvm::MD5 Class Reference
LLVM API Documentation
llvm::MD5 Class Reference
#include <MD5.h>
Public Types
typedef uint8_t MD5Result [16]
Public Member Functions
MD5 ()
void update (ArrayRef< uint8_t > Data)
Updates the hash for the byte stream provided.
void update (StringRef Str)
Updates the hash for the StringRef provided.
void final (MD5Result &Result)
Finishes off the hash and puts the result in result.
Static Public Member Functions
static void stringifyResult (MD5Result &Result, SmallString< 32 > &Str)
Translates the bytes in Res to a hex string that is deposited into Str. The result will be of length 32.
Detailed Description
Definition at line 37 of file MD5.h.
Member Typedef Documentation
typedef uint8_t llvm::MD5::MD5Result[16]
Definition at line 47 of file MD5.h.
Constructor & Destructor Documentation
llvm::MD5::MD5 ()
Definition at line 182 of file MD5.cpp.
Member Function Documentation
void llvm::MD5::final (MD5Result & Result)
Finishes off the hash and puts the result in result.
Finish the hash and place the resulting hash into result.
Parameters
result is assumed to be a minimum of 16-bytes in size.
Definition at line 232 of file MD5.cpp.
References llvm::LibFunc::free, llvm::makeArrayRef(), and llvm::Intrinsic::memset.
Referenced by llvm::DIEHash::computeCUSignature(), llvm::DIEHash::computeDIEODRSignature(), llvm::DIEHash::computeTypeSignature(), makeTypeSignature(), and llvm::IndexedInstrProf::MD5Hash().
void llvm::MD5::stringifyResult (MD5Result & Result, SmallString< 32 > & Str) static
Translates the bytes in Res to a hex string that is deposited into Str. The result will be of length 32.
Definition at line 280 of file MD5.cpp.
References llvm::format().
void llvm::MD5::update (ArrayRef< uint8_t > Data)
Updates the hash for the byte stream provided.
Incrementally add the bytes in Data to the hash.
Definition at line 187 of file MD5.cpp.
References llvm::ArrayRef< T >::data(), llvm::LibFunc::free, llvm::makeArrayRef(), llvm::Intrinsic::memcpy, and llvm::ArrayRef< T >::size().
Referenced by llvm::DIEHash::addSLEB128(), llvm::DIEHash::addULEB128(), makeTypeSignature(), llvm::IndexedInstrProf::MD5Hash(), update(), and llvm::DIEHash::update().
void llvm::MD5::update (StringRef Str)
Updates the hash for the StringRef provided.
Add the bytes in the StringRef Str to the hash.
Definition at line 225 of file MD5.cpp.
References llvm::StringRef::data(), llvm::StringRef::size(), and update().
The documentation for this class was generated from the following files:
MD5.h
MD5.cpp