LLVM: llvm::MCELFObjectTargetWriter Class Reference
LLVM API Documentation
llvm::MCELFObjectTargetWriter Class Reference abstract
#include <MCELFObjectWriter.h>
Public Member Functions
virtual ~MCELFObjectTargetWriter ()
virtual unsigned GetRelocType (const MCValue &Target, const MCFixup &Fixup, bool IsPCRel) const =0
virtual bool needsRelocateWithSymbol (const MCSymbolData &SD, unsigned Type) const
uint8_t getRType (uint32_t Type) const
uint8_t getRType2 (uint32_t Type) const
uint8_t getRType3 (uint32_t Type) const
uint8_t getRSsym (uint32_t Type) const
unsigned setRType (unsigned Value, unsigned Type) const
unsigned setRType2 (unsigned Value, unsigned Type) const
unsigned setRType3 (unsigned Value, unsigned Type) const
unsigned setRSsym (unsigned Value, unsigned Type) const
Accessors
uint8_t getOSABI () const
uint16_t getEMachine () const
bool hasRelocationAddend () const
bool is64Bit () const
bool isN64 () const
Static Public Member Functions
static uint8_t getOSABI (Triple::OSType OSType)
Protected Member Functions
MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend, bool IsN64=false)
Detailed Description
Definition at line 28 of file MCELFObjectWriter.h.
Constructor & Destructor Documentation
MCELFObjectTargetWriter::MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend, bool IsN64 = false) protected
Definition at line 17 of file MCELFObjectTargetWriter.cpp.
virtual llvm::MCELFObjectTargetWriter::~MCELFObjectTargetWriter () inline virtual
Definition at line 53 of file MCELFObjectWriter.h.
Member Function Documentation
uint16_t llvm::MCELFObjectTargetWriter::getEMachine () const inline
Definition at line 64 of file MCELFObjectWriter.h.
static uint8_t llvm::MCELFObjectTargetWriter::getOSABI (Triple::OSType OSType) inline static
Definition at line 42 of file MCELFObjectWriter.h.
References llvm::ELF::ELFOSABI_FREEBSD, llvm::ELF::ELFOSABI_LINUX, llvm::ELF::ELFOSABI_NONE, llvm::Triple::FreeBSD, and llvm::Triple::Linux.
uint8_t llvm::MCELFObjectTargetWriter::getOSABI () const inline
Definition at line 63 of file MCELFObjectWriter.h.
Referenced by llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), llvm::createARMAsmBackend(), llvm::createHexagonAsmBackend(), llvm::MipsAsmBackend::createObjectWriter(), llvm::createPPCAsmBackend(), llvm::createSystemZMCAsmBackend(), llvm::createX86_32AsmBackend(), and llvm::createX86_64AsmBackend().
virtual unsigned llvm::MCELFObjectTargetWriter::GetRelocType (const MCValue & Target, const MCFixup & Fixup, bool IsPCRel) const pure virtual
uint8_t llvm::MCELFObjectTargetWriter::getRSsym (uint32_t Type) const inline
Definition at line 91 of file MCELFObjectWriter.h.
References R_SSYM_SHIFT.
uint8_t llvm::MCELFObjectTargetWriter::getRType (uint32_t Type) const inline
Definition at line 82 of file MCELFObjectWriter.h.
References R_TYPE_SHIFT.
uint8_t llvm::MCELFObjectTargetWriter::getRType2 (uint32_t Type) const inline
Definition at line 85 of file MCELFObjectWriter.h.
References R_TYPE2_SHIFT.
uint8_t llvm::MCELFObjectTargetWriter::getRType3 (uint32_t Type) const inline
Definition at line 88 of file MCELFObjectWriter.h.
References R_TYPE3_SHIFT.
bool llvm::MCELFObjectTargetWriter::hasRelocationAddend () const inline
Definition at line 65 of file MCELFObjectWriter.h.
bool llvm::MCELFObjectTargetWriter::is64Bit () const inline
Definition at line 66 of file MCELFObjectWriter.h.
bool llvm::MCELFObjectTargetWriter::isN64 () const inline
Definition at line 67 of file MCELFObjectWriter.h.
bool MCELFObjectTargetWriter::needsRelocateWithSymbol (const MCSymbolData & SD, unsigned Type) const virtual
Definition at line 27 of file MCELFObjectTargetWriter.cpp.
unsigned llvm::MCELFObjectTargetWriter::setRSsym (unsigned Value, unsigned Type) const inline
Definition at line 105 of file MCELFObjectWriter.h.
References R_SSYM_MASK, and R_SSYM_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::setRType (unsigned Value, unsigned Type) const inline
Definition at line 96 of file MCELFObjectWriter.h.
References R_TYPE_MASK, and R_TYPE_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::setRType2 (unsigned Value, unsigned Type) const inline
Definition at line 99 of file MCELFObjectWriter.h.
References R_TYPE2_MASK, and R_TYPE2_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::setRType3 (unsigned Value, unsigned Type) const inline
Definition at line 102 of file MCELFObjectWriter.h.
References R_TYPE3_MASK, and R_TYPE3_SHIFT.
The documentation for this class was generated from the following files:
MCELFObjectWriter.h
MCELFObjectTargetWriter.cpp