LLVM: llvm::SMRange Class Reference
LLVM API Documentation
llvm::SMRange Class Reference
#include <SMLoc.h>
Public Member Functions
SMRange ()
SMRange (SMLoc St, SMLoc En)
bool isValid () const
Public Attributes
SMLoc Start
SMLoc End
Detailed Description
Represents a range in source code.
SMRange is implemented using a half-open range, as is the convention in C++. In the string "abc", the range (1,3] represents the substring "bc", and the range (2,2] represents an empty range between the characters "b" and "c".
Definition at line 47 of file SMLoc.h.
Constructor & Destructor Documentation
llvm::SMRange::SMRange () inline
Definition at line 51 of file SMLoc.h.
llvm::SMRange::SMRange (SMLoc St, SMLoc En) inline
Definition at line 52 of file SMLoc.h.
References assert(), End, llvm::SMLoc::isValid(), and Start.
Member Function Documentation
bool llvm::SMRange::isValid () const inline
Definition at line 57 of file SMLoc.h.
References llvm::SMLoc::isValid(), and Start.
Referenced by llvm::SourceMgr::GetMessage(), and llvm::SMFixIt::SMFixIt().
Member Data Documentation
SMLoc llvm::SMRange::End
Definition at line 49 of file SMLoc.h.
Referenced by buildFixItLine(), llvm::SourceMgr::GetMessage(), llvm::SMFixIt::operator<(), and SMRange().
SMLoc llvm::SMRange::Start
Definition at line 49 of file SMLoc.h.
Referenced by buildFixItLine(), llvm::SourceMgr::GetMessage(), isValid(), llvm::SMFixIt::operator<(), llvm::yaml::Stream::printError(), and SMRange().
The documentation for this class was generated from the following file:
SMLoc.h