LLVM: llvm::MCUnaryExpr Class Reference
LLVM API Documentation
llvm::MCUnaryExpr Class Reference
MCUnaryExpr - Unary assembler expressions.
#include <MCExpr.h>
Public Types
enum Opcode { LNot, Minus, Not, Plus }
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
Accessors
Opcode getOpcode () const
getOpcode - Get the kind of this unary expression.
const MCExpr * getSubExpr () const
getSubExpr - Get the child of this unary expression.
Public Member Functions inherited from llvm::MCExpr
ExprKind getKind () const
void print (raw_ostream &OS) const
void dump () const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
int64_t evaluateKnownAbsolute (const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
bool EvaluateAsValue (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
const MCSection * FindAssociatedSection () const
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const MCUnaryExpr * Create (Opcode Op, const MCExpr *Expr, MCContext &Ctx)
static const MCUnaryExpr * CreateLNot (const MCExpr *Expr, MCContext &Ctx)
static const MCUnaryExpr * CreateMinus (const MCExpr *Expr, MCContext &Ctx)
static const MCUnaryExpr * CreateNot (const MCExpr *Expr, MCContext &Ctx)
static const MCUnaryExpr * CreatePlus (const MCExpr *Expr, MCContext &Ctx)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet, bool ForceVarExpansion) const
Detailed Description
MCUnaryExpr - Unary assembler expressions.
Definition at line 343 of file MCExpr.h.
Member Enumeration Documentation
enum llvm::MCUnaryExpr::Opcode
Enumerator
LNot
Logical negation.
Minus
Unary minus.
Not
Bitwise negation.
Plus
Unary plus.
Definition at line 345 of file MCExpr.h.
Member Function Documentation
static bool llvm::MCUnaryExpr::classof (const MCExpr * E) inline static
Definition at line 390 of file MCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Unary.
const MCUnaryExpr * MCUnaryExpr::Create (Opcode Op, const MCExpr * Expr, MCContext & Ctx) static
Definition at line 138 of file MCExpr.cpp.
Referenced by CreateLNot(), CreateMinus(), CreateNot(), and CreatePlus().
static const MCUnaryExpr* llvm::MCUnaryExpr::CreateLNot (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 365 of file MCExpr.h.
References Create(), and LNot.
static const MCUnaryExpr* llvm::MCUnaryExpr::CreateMinus (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 368 of file MCExpr.h.
References Create(), and Minus.
Referenced by addNegOperand(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::MCExternalSymbolizer::tryAddingSymbolicOperand().
static const MCUnaryExpr* llvm::MCUnaryExpr::CreateNot (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 371 of file MCExpr.h.
References Create(), and Not.
static const MCUnaryExpr* llvm::MCUnaryExpr::CreatePlus (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 374 of file MCExpr.h.
References Create(), and Plus.
Opcode llvm::MCUnaryExpr::getOpcode () const inline
getOpcode - Get the kind of this unary expression.
Definition at line 383 of file MCExpr.h.
Referenced by llvm::MCExpr::EvaluateAsRelocatableImpl(), and llvm::MCExpr::print().
const MCExpr* llvm::MCUnaryExpr::getSubExpr () const inline
getSubExpr - Get the child of this unary expression.
Definition at line 386 of file MCExpr.h.
Referenced by llvm::MCExpr::EvaluateAsRelocatableImpl(), and llvm::MCExpr::print().
The documentation for this class was generated from the following files:
MCExpr.h
MCExpr.cpp