LLVM: llvm::MCDataFragment Class Reference
LLVM API Documentation
llvm::MCDataFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCDataFragment (MCSectionData *SD=nullptr)
SmallVectorImpl< char > & getContents () override
const SmallVectorImpl< char > & getContents () const override
SmallVectorImpl< MCFixup > & getFixups () override
const SmallVectorImpl< MCFixup > & getFixups () const override
bool hasInstructions () const override
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
virtual void setHasInstructions (bool V)
bool alignToBundleEnd () const override
Should this fragment be placed at the end of an aligned bundle?
void setAlignToBundleEnd (bool V) override
fixup_iterator fixup_begin () override
const_fixup_iterator fixup_begin () const override
fixup_iterator fixup_end () override
const_fixup_iterator fixup_end () const override
Public Member Functions inherited from llvm::MCEncodedFragmentWithFixups
MCEncodedFragmentWithFixups (MCFragment::FragmentType FType, MCSectionData *SD=nullptr)
virtual ~MCEncodedFragmentWithFixups ()
Public Member Functions inherited from llvm::MCEncodedFragment
MCEncodedFragment (MCFragment::FragmentType FType, MCSectionData *SD=nullptr)
virtual ~MCEncodedFragment ()
uint8_t getBundlePadding () const override
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
void setBundlePadding (uint8_t N) override
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
Public Member Functions inherited from llvm::MCFragment
MCFragment ()
virtual ~MCFragment ()
FragmentType getKind () const
MCSectionData * getParent () const
void setParent (MCSectionData *Value)
MCSymbolData * getAtom () const
void setAtom (MCSymbolData *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCFragment >
MCFragment * getPrevNode ()
Get the previous node, or 0 for the list head.
const MCFragment * getPrevNode () const
Get the previous node, or 0 for the list head.
MCFragment * getNextNode ()
Get the next node, or 0 for the list tail.
const MCFragment * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragmentWithFixups
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragment
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCEncodedFragmentWithFixups
typedef SmallVectorImpl
< MCFixup >::const_iterator const_fixup_iterator
typedef SmallVectorImpl
< MCFixup >::iterator fixup_iterator
Public Types inherited from llvm::MCFragment
enum FragmentType {
FT_Align, FT_Data, FT_CompactEncodedInst, FT_Fill,
FT_Relaxable, FT_Org, FT_Dwarf, FT_DwarfFrame,
FT_LEB
}
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType _Kind, MCSectionData *_Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node< MCFragment >
ilist_node ()
Detailed Description
Fragment for data and encoded instructions.
Definition at line 205 of file MCAssembler.h.
Constructor & Destructor Documentation
llvm::MCDataFragment::MCDataFragment (MCSectionData * SD = nullptr) inline
Definition at line 219 of file MCAssembler.h.
Member Function Documentation
bool llvm::MCDataFragment::alignToBundleEnd () const inline override virtual
Should this fragment be placed at the end of an aligned bundle?
Reimplemented from llvm::MCFragment.
Definition at line 241 of file MCAssembler.h.
static bool llvm::MCDataFragment::classof (const MCFragment * F) inline static
Definition at line 250 of file MCAssembler.h.
References llvm::MCFragment::FT_Data, and llvm::MCFragment::getKind().
fixup_iterator llvm::MCDataFragment::fixup_begin () inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 244 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and llvm::MCAssembler::writeSectionData().
const_fixup_iterator llvm::MCDataFragment::fixup_begin () const inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 245 of file MCAssembler.h.
fixup_iterator llvm::MCDataFragment::fixup_end () inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 247 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and llvm::MCAssembler::writeSectionData().
const_fixup_iterator llvm::MCDataFragment::fixup_end () const inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 248 of file MCAssembler.h.
SmallVectorImpl<char>& llvm::MCDataFragment::getContents () inline override virtual
Implements llvm::MCEncodedFragment.
Definition at line 225 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCObjectStreamer::EmitFill(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitValueImpl(), and llvm::MCAssembler::writeSectionData().
const SmallVectorImpl<char>& llvm::MCDataFragment::getContents () const inline override virtual
Implements llvm::MCEncodedFragment.
Definition at line 226 of file MCAssembler.h.
SmallVectorImpl<MCFixup>& llvm::MCDataFragment::getFixups () inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 230 of file MCAssembler.h.
Referenced by llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MCObjectStreamer::EmitGPRel32Value(), llvm::MCObjectStreamer::EmitGPRel64Value(), llvm::MCWinCOFFStreamer::EmitInstToData(), and llvm::MCObjectStreamer::EmitValueImpl().
const SmallVectorImpl<MCFixup>& llvm::MCDataFragment::getFixups () const inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 234 of file MCAssembler.h.
bool llvm::MCDataFragment::hasInstructions () const inline override virtual
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
Reimplemented from llvm::MCFragment.
Definition at line 238 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::getOrCreateDataFragment().
void llvm::MCDataFragment::setAlignToBundleEnd (bool V) inline override virtual
Reimplemented from llvm::MCFragment.
Definition at line 242 of file MCAssembler.h.
virtual void llvm::MCDataFragment::setHasInstructions (bool V) inline virtual
Definition at line 239 of file MCAssembler.h.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp