LLVM: llvm::LazyCallGraph::Node Class Reference
LLVM API Documentation
llvm::LazyCallGraph::Node Class Reference
A node in the call graph.
#include <LazyCallGraph.h>
Public Types
typedef LazyCallGraph::iterator iterator
Public Member Functions
Function & getFunction () const
iterator begin () const
iterator end () const
bool operator== (const Node &N) const
Equality is defined as address equality.
bool operator!= (const Node &N) const
Friends
class LazyCallGraph
class LazyCallGraph::SCC
Detailed Description
A node in the call graph.
This represents a single node. It's primary roles are to cache the list of callees, de-duplicate and provide fast testing of whether a function is a callee, and facilitate iteration of child nodes in the graph.
Definition at line 160 of file LazyCallGraph.h.
Member Typedef Documentation
typedef LazyCallGraph::iterator llvm::LazyCallGraph::Node::iterator
Definition at line 189 of file LazyCallGraph.h.
Member Function Documentation
iterator llvm::LazyCallGraph::Node::begin () const inline
Definition at line 195 of file LazyCallGraph.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and G.
Referenced by llvm::GraphTraits< LazyCallGraph::Node * >::child_begin(), and llvm::GraphTraits< LazyCallGraph * >::child_begin().
iterator llvm::LazyCallGraph::Node::end () const inline
Definition at line 198 of file LazyCallGraph.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and G.
Referenced by llvm::GraphTraits< LazyCallGraph::Node * >::child_end(), and llvm::GraphTraits< LazyCallGraph * >::child_end().
Function& llvm::LazyCallGraph::Node::getFunction () const inline
Definition at line 191 of file LazyCallGraph.h.
References F().
Referenced by llvm::LazyCallGraph::LazyCallGraph(), llvm::LazyCallGraph::SCC::removeInterSCCEdge(), and llvm::LazyCallGraph::SCC::removeIntraSCCEdge().
bool llvm::LazyCallGraph::Node::operator!= (const Node & N) const inline
Definition at line 202 of file LazyCallGraph.h.
References operator==().
bool llvm::LazyCallGraph::Node::operator== (const Node & N) const inline
Equality is defined as address equality.
Definition at line 201 of file LazyCallGraph.h.
References N.
Referenced by operator!=().
Friends And Related Function Documentation
friend class LazyCallGraph friend
Definition at line 161 of file LazyCallGraph.h.
friend class LazyCallGraph::SCC friend
Definition at line 162 of file LazyCallGraph.h.
The documentation for this class was generated from the following files:
LazyCallGraph.h
LazyCallGraph.cpp