LLVM: llvm::AliasSet::iterator Class Reference
LLVM API Documentation
llvm::AliasSet::iterator Class Reference
Define an iterator for alias sets... this is just a forward iterator.
#include <AliasSetTracker.h>
Public Member Functions
iterator (PointerRec *CN=nullptr)
bool operator== (const iterator &x) const
bool operator!= (const iterator &x) const
const iterator & operator= (const iterator &I)
value_type & operator* () const
value_type * operator-> () const
Value * getPointer () const
uint64_t getSize () const
AAMDNodes getAAInfo () const
iterator & operator++ ()
iterator operator++ (int)
Detailed Description
Define an iterator for alias sets... this is just a forward iterator.
Definition at line 184 of file AliasSetTracker.h.
Constructor & Destructor Documentation
llvm::AliasSet::iterator::iterator (PointerRec * CN = nullptr) inline explicit
Definition at line 188 of file AliasSetTracker.h.
Member Function Documentation
AAMDNodes llvm::AliasSet::iterator::getAAInfo () const inline
Definition at line 208 of file AliasSetTracker.h.
Value* llvm::AliasSet::iterator::getPointer () const inline
Definition at line 206 of file AliasSetTracker.h.
uint64_t llvm::AliasSet::iterator::getSize () const inline
Definition at line 207 of file AliasSetTracker.h.
bool llvm::AliasSet::iterator::operator!= (const iterator & x) const inline
Definition at line 193 of file AliasSetTracker.h.
References operator==().
value_type& llvm::AliasSet::iterator::operator* () const inline
Definition at line 200 of file AliasSetTracker.h.
References assert().
Referenced by operator->().
iterator& llvm::AliasSet::iterator::operator++ () inline
Definition at line 210 of file AliasSetTracker.h.
References assert().
iterator llvm::AliasSet::iterator::operator++ (int) inline
Definition at line 215 of file AliasSetTracker.h.
value_type* llvm::AliasSet::iterator::operator-> () const inline
Definition at line 204 of file AliasSetTracker.h.
References operator*().
const iterator& llvm::AliasSet::iterator::operator= (const iterator & I) inline
Definition at line 195 of file AliasSetTracker.h.
bool llvm::AliasSet::iterator::operator== (const iterator & x) const inline
Definition at line 190 of file AliasSetTracker.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
AliasSetTracker.h