LLVM: llvm::ARMInstPrinter Class Reference
LLVM API Documentation
llvm::ARMInstPrinter Class Reference
#include <ARMInstPrinter.h>
Public Member Functions
ARMInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot) override
void printRegName (raw_ostream &OS, unsigned RegNo) const override
printRegName - Print the assembler register name.
void printInstruction (const MCInst *MI, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSORegRegOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printSORegImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAddrModeTBB (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAddrModeTBH (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAddrMode2Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAM2PostIndexOp (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAM2PreOrOffsetIndexOp (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAddrMode2OffsetOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printAddrMode3Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAddrMode3OffsetOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAM3PreOrOffsetIndexOp (const MCInst *MI, unsigned Op, raw_ostream &O, bool AlwaysPrintImm0)
void printPostIdxImm8Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPostIdxRegOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPostIdxImm8s4Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printLdStmModeOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printAddrMode5Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAddrMode6Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAddrMode7Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAddrMode6OffsetOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printBitfieldInvMaskImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMemBOption (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printInstSyncBOption (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printShiftImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPKHLSLShiftImm (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPKHASRShiftImm (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<unsigned scale>
void printAdrLabelOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbS4ImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbSRImm (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbITMask (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbAddrModeRROperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbAddrModeImm5SOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O, unsigned Scale)
void printThumbAddrModeImm5S1Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbAddrModeImm5S2Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbAddrModeImm5S4Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbAddrModeSPOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printT2SOOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printAddrModeImm12Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printT2AddrModeImm8Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printT2AddrModeImm8s4Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printT2AddrModeImm0_1020s4Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printT2AddrModeImm8OffsetOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printT2AddrModeImm8s4OffsetOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printT2AddrModeSoRegOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printSetendOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printCPSIMod (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printCPSIFlag (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMSRMaskOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printBankedRegOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPredicateOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMandatoryPredicateOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printSBitModifierOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printRegisterList (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printNoHashImmediate (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPImmediate (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printCImmediate (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printCoprocOptionImm (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printFPImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printNEONModImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printImmPlusOneOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printRotImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printModImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printGPRPairOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPCLabel (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printThumbLdrLabelOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printFBits16 (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printFBits32 (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorIndex (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListOne (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListTwo (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListTwoSpaced (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListThree (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListFour (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListOneAllLanes (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListTwoAllLanes (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListThreeAllLanes (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListFourAllLanes (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListTwoSpacedAllLanes (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListThreeSpacedAllLanes (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListFourSpacedAllLanes (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListThreeSpaced (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorListFourSpaced (const MCInst *MI, unsigned OpNum, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 24 of file ARMInstPrinter.h.
Constructor & Destructor Documentation
ARMInstPrinter::ARMInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI)
Definition at line 61 of file ARMInstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), and llvm::MCInstPrinter::setAvailableFeatures().
Member Function Documentation
static const char* llvm::ARMInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by llvm::ARMAsmPrinter::PrintAsmMemoryOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), and printRegName().
void ARMInstPrinter::printAddrMode2OffsetOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 497 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM2Offset(), llvm::ARM_AM::getAM2Op(), llvm::ARM_AM::getAM2ShiftOpc(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), printRegImmShift(), printRegName(), and llvm::MCInstPrinter::UseMarkup.
void ARMInstPrinter::printAddrMode2Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 478 of file ARMInstPrinter.cpp.
References assert(), llvm::ARM_AM::getAM2IdxMode(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::ARMII::IndexModePost, llvm::MCOperand::isReg(), printAM2PreOrOffsetIndexOp(), and printOperand().
void ARMInstPrinter::printAddrMode3OffsetOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 570 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), and printRegName().
template<bool AlwaysPrintImm0> void ARMInstPrinter::printAddrMode3Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 556 of file ARMInstPrinter.cpp.
References assert(), llvm::ARM_AM::getAM3IdxMode(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::ARMII::IndexModePost, llvm::MCOperand::isReg(), printAM3PreOrOffsetIndexOp(), and printOperand().
template<bool AlwaysPrintImm0> void ARMInstPrinter::printAddrMode5Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 626 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM5Offset(), llvm::ARM_AM::getAM5Op(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), printOperand(), printRegName(), and llvm::ARM_AM::sub.
void ARMInstPrinter::printAddrMode6OffsetOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 673 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printAddrMode6Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 652 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), and printRegName().
void ARMInstPrinter::printAddrMode7Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 665 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), and printRegName().
template<bool AlwaysPrintImm0> void ARMInstPrinter::printAddrModeImm12Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1103 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), printOperand(), and printRegName().
void ARMInstPrinter::printAddrModeTBB (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 456 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), and printRegName().
void ARMInstPrinter::printAddrModeTBH (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 467 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), and printRegName().
template<unsigned scale> void ARMInstPrinter::printAdrLabelOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 966 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCInstPrinter::markup(), and scale().
void llvm::ARMInstPrinter::printAM2PostIndexOp (const MCInst * MI, unsigned OpNum, raw_ostream & O)
void ARMInstPrinter::printAM2PreOrOffsetIndexOp (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 425 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM2Offset(), llvm::ARM_AM::getAM2Op(), llvm::ARM_AM::getAM2ShiftOpc(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), printRegImmShift(), printRegName(), and llvm::MCInstPrinter::UseMarkup.
Referenced by printAddrMode2Operand().
void ARMInstPrinter::printAM3PreOrOffsetIndexOp (const MCInst * MI, unsigned Op, raw_ostream & O, bool AlwaysPrintImm0)
Definition at line 523 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), printRegName(), and llvm::ARM_AM::sub.
Referenced by printAddrMode3Operand().
void ARMInstPrinter::printBankedRegOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 878 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm_unreachable, and Name.
void ARMInstPrinter::printBitfieldInvMaskImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 685 of file ARMInstPrinter.cpp.
References assert(), llvm::countLeadingZeros(), llvm::countTrailingZeros(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printCImmediate (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 950 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printCoprocOptionImm (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 955 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printCPSIFlag (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 782 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::ARM_PROC::IFlagsToString().
void ARMInstPrinter::printCPSIMod (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 776 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::ARM_PROC::IModToString().
void ARMInstPrinter::printFBits16 (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1367 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printFBits32 (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1374 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printFPImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1277 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getFPImmFloat(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printGPRPairOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 758 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getSubReg(), llvm::MCInstPrinter::MRI, and printRegName().
void ARMInstPrinter::printImmPlusOneOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1296 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) override virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 76 of file ARMInstPrinter.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCRegisterClass::contains(), llvm::MCOperand::CreateReg(), llvm::MCInstPrinter::getAvailableFeatures(), llvm::MCOperand::getImm(), llvm::MCRegisterInfo::getMatchingSuperReg(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), llvm::ARM_AM::getShiftOpcStr(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::markup(), llvm::MCInstPrinter::MRI, llvm::MCInstPrinter::printAnnotation(), printInstruction(), printPredicateOperand(), printRegisterList(), printRegName(), printSBitModifierOperand(), llvm::ARM_AM::rrx, llvm::MCInst::setOpcode(), and translateShiftImm().
void llvm::ARMInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void ARMInstPrinter::printInstSyncBOption (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 704 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::ARM_ISB::InstSyncBOptToString().
void ARMInstPrinter::printLdStmModeOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 618 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAM4SubMode(), llvm::ARM_AM::getAMSubModeStr(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printMandatoryPredicateOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 924 of file ARMInstPrinter.cpp.
References llvm::ARMCondCodeToString(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printMemBOption (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 698 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::getAvailableFeatures(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::ARM_MB::MemBOptToString().
void ARMInstPrinter::printModImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1321 of file ARMInstPrinter.cpp.
References llvm::tgtok::Bits, llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::ARM_AM::getSOImmVal(), llvm::MCOperand::isExpr(), llvm::MCInstPrinter::markup(), printOperand(), and llvm::ARM_AM::rotr32().
void ARMInstPrinter::printMSRMaskOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 794 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::getAvailableFeatures(), llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), and llvm_unreachable.
void ARMInstPrinter::printNEONModImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1285 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::decodeNEONModImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCInstPrinter::markup(), and llvm::raw_ostream::write_hex().
void ARMInstPrinter::printNoHashImmediate (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 940 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 316 of file ARMInstPrinter.cpp.
References assert(), llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::EvaluateAsAbsolute(), llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), printRegName(), and llvm::raw_ostream::write_hex().
Referenced by printAddrMode2Operand(), printAddrMode3Operand(), printAddrMode5Operand(), printAddrModeImm12Operand(), printModImmOperand(), printT2AddrModeImm8s4Operand(), printThumbAddrModeImm5SOperand(), and printThumbAddrModeRROperand().
void ARMInstPrinter::printPCLabel (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 960 of file ARMInstPrinter.cpp.
References llvm_unreachable.
void ARMInstPrinter::printPImmediate (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 945 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printPKHASRShiftImm (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 738 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printPKHLSLShiftImm (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 729 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printPostIdxImm8Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 588 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printPostIdxImm8s4Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 607 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printPostIdxRegOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 598 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printPredicateOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 914 of file ARMInstPrinter.cpp.
References llvm::ARMCC::AL, llvm::ARMCondCodeToString(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by printInst().
void ARMInstPrinter::printRegisterList (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 748 of file ARMInstPrinter.cpp.
References llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
Referenced by printInst().
void ARMInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
printRegName - Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 70 of file ARMInstPrinter.cpp.
References getRegisterName(), and llvm::MCInstPrinter::markup().
Referenced by printAddrMode2OffsetOperand(), printAddrMode3OffsetOperand(), printAddrMode5Operand(), printAddrMode6OffsetOperand(), printAddrMode6Operand(), printAddrMode7Operand(), printAddrModeImm12Operand(), printAddrModeTBB(), printAddrModeTBH(), printAM2PreOrOffsetIndexOp(), printAM3PreOrOffsetIndexOp(), printGPRPairOperand(), printInst(), printOperand(), printPostIdxRegOperand(), printRegisterList(), printSORegImmOperand(), printSORegRegOperand(), printT2AddrModeImm0_1020s4Operand(), printT2AddrModeImm8Operand(), printT2AddrModeImm8s4Operand(), printT2AddrModeSoRegOperand(), printT2SOOperand(), printThumbAddrModeImm5SOperand(), printThumbAddrModeRROperand(), printVectorListFour(), printVectorListFourAllLanes(), printVectorListFourSpaced(), printVectorListFourSpacedAllLanes(), printVectorListOne(), printVectorListOneAllLanes(), printVectorListThree(), printVectorListThreeAllLanes(), printVectorListThreeSpaced(), printVectorListThreeSpacedAllLanes(), printVectorListTwo(), printVectorListTwoAllLanes(), printVectorListTwoSpaced(), and printVectorListTwoSpacedAllLanes().
void ARMInstPrinter::printRotImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1304 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printSBitModifierOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 931 of file ARMInstPrinter.cpp.
References assert(), llvm::MCInst::getOperand(), and llvm::MCOperand::getReg().
Referenced by printInst().
void ARMInstPrinter::printSetendOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 767 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printShiftImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 710 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printSORegImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 408 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), printRegImmShift(), printRegName(), and llvm::MCInstPrinter::UseMarkup.
void ARMInstPrinter::printSORegRegOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 389 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::ARM_AM::getShiftOpcStr(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), printRegName(), and llvm::ARM_AM::rrx.
void ARMInstPrinter::printT2AddrModeImm0_1020s4Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1202 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), and printRegName().
void ARMInstPrinter::printT2AddrModeImm8OffsetOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1219 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
template<bool AlwaysPrintImm0> void ARMInstPrinter::printT2AddrModeImm8Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1137 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), and printRegName().
void ARMInstPrinter::printT2AddrModeImm8s4OffsetOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1234 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
template<bool AlwaysPrintImm0> void ARMInstPrinter::printT2AddrModeImm8s4Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1166 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), printOperand(), and printRegName().
void ARMInstPrinter::printT2AddrModeSoRegOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1252 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), and printRegName().
void ARMInstPrinter::printT2SOOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1088 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), llvm::MCOperand::isImm(), printRegImmShift(), printRegName(), and llvm::MCInstPrinter::UseMarkup.
void ARMInstPrinter::printThumbAddrModeImm5S1Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1061 of file ARMInstPrinter.cpp.
References printThumbAddrModeImm5SOperand().
void ARMInstPrinter::printThumbAddrModeImm5S2Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1067 of file ARMInstPrinter.cpp.
References printThumbAddrModeImm5SOperand().
void ARMInstPrinter::printThumbAddrModeImm5S4Operand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1073 of file ARMInstPrinter.cpp.
References printThumbAddrModeImm5SOperand().
void ARMInstPrinter::printThumbAddrModeImm5SOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O, unsigned Scale)
Definition at line 1038 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), printOperand(), and printRegName().
Referenced by printThumbAddrModeImm5S1Operand(), printThumbAddrModeImm5S2Operand(), printThumbAddrModeImm5S4Operand(), and printThumbAddrModeSPOperand().
void ARMInstPrinter::printThumbAddrModeRROperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1019 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), printOperand(), and printRegName().
void ARMInstPrinter::printThumbAddrModeSPOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1079 of file ARMInstPrinter.cpp.
References printThumbAddrModeImm5SOperand().
void ARMInstPrinter::printThumbITMask (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1002 of file ARMInstPrinter.cpp.
References assert(), llvm::countTrailingZeros(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printThumbLdrLabelOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 356 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printThumbS4ImmOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 987 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printThumbSRImm (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 994 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCInstPrinter::markup().
void ARMInstPrinter::printVectorIndex (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1381 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
void ARMInstPrinter::printVectorListFour (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1432 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListFourAllLanes (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1484 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListFourSpaced (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1561 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListFourSpacedAllLanes (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1529 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListOne (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1386 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListOneAllLanes (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1448 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListThree (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1418 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListThreeAllLanes (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1469 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListThreeSpaced (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1546 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListThreeSpacedAllLanes (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1514 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and printRegName().
void ARMInstPrinter::printVectorListTwo (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1393 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getSubReg(), llvm::MCInstPrinter::MRI, and printRegName().
void ARMInstPrinter::printVectorListTwoAllLanes (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1456 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getSubReg(), llvm::MCInstPrinter::MRI, and printRegName().
void ARMInstPrinter::printVectorListTwoSpaced (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1405 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getSubReg(), llvm::MCInstPrinter::MRI, and printRegName().
void ARMInstPrinter::printVectorListTwoSpacedAllLanes (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 1501 of file ARMInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getSubReg(), llvm::MCInstPrinter::MRI, and printRegName().
The documentation for this class was generated from the following files:
ARMInstPrinter.h
ARMInstPrinter.cpp