LLVM: llvm::RegionInfoBase< RegionTr > Class Template Reference
LLVM API Documentation
llvm::RegionInfoBase< RegionTr > Class Template Reference abstract
Analysis that detects all canonical Regions.
#include <RegionInfo.h>
Public Member Functions
void print (raw_ostream &OS) const
void dump () const
void releaseMemory ()
RegionT * getRegionFor (BlockT *BB) const
Get the smallest region that contains a BasicBlock.
void setRegionFor (BlockT *BB, RegionT *R)
Set the smallest region that surrounds a basic block.
RegionT * operator[] (BlockT *BB) const
A shortcut for getRegionFor().
BlockT * getMaxRegionExit (BlockT *BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
RegionT * getCommonRegion (RegionT *A, RegionT *B) const
Find the smallest region that contains two regions.
RegionT * getCommonRegion (BlockT *A, BlockT *B) const
Find the smallest region that contains two basic blocks.
RegionT * getCommonRegion (SmallVectorImpl< RegionT * > &Regions) const
Find the smallest region that contains a set of regions.
RegionT * getCommonRegion (SmallVectorImpl< BlockT * > &BBs) const
Find the smallest region that contains a set of basic blocks.
RegionT * getTopLevelRegion () const
void splitBlock (BlockT *NewBB, BlockT *OldBB)
Update RegionInfo after a basic block was split.
void clearNodeCache ()
Clear the Node Cache for all Regions.
void verifyAnalysis () const
Static Public Attributes
static bool VerifyRegionInfo = false
static RegionT::PrintStyle printStyle
Friends
class RegionInfo
class MachineRegionInfo
Detailed Description
template<class RegionTr>
class llvm::RegionInfoBase< RegionTr >
Analysis that detects all canonical Regions.
The RegionInfo pass detects all canonical regions in a function. The Regions are connected using the parent relation. This builds a Program Structure Tree.
Definition at line 75 of file RegionInfo.h.
Member Function Documentation
template<class RegionTr> void llvm::RegionInfoBase< RegionTr >::clearNodeCache () inline
Clear the Node Cache for all Regions.
See Also
Region::clearNodeCache()
Definition at line 808 of file RegionInfo.h.
Referenced by llvm::RGPassManager::runOnFunction().
template<class Tr > void llvm::RegionInfoBase< Tr >::dump () const
Definition at line 778 of file RegionInfoImpl.h.
References llvm::dbgs().
Referenced by llvm::MachineRegionInfoPass::dump(), llvm::RegionInfoPass::dump(), and llvm::RGPassManager::runOnFunction().
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::getCommonRegion (RegionT * A, RegionT * B) const
Find the smallest region that contains two regions.
Parameters
A The first region.
B The second region.
Returns
The smallest region containing A and B.
Definition at line 854 of file RegionInfoImpl.h.
References assert().
Referenced by llvm::RegionInfoBase< RegionTraits< Function > >::getCommonRegion().
template<class RegionTr> RegionT* llvm::RegionInfoBase< RegionTr >::getCommonRegion (BlockT * A, BlockT * B) const inline
Find the smallest region that contains two basic blocks.
Parameters
A The first basic block.
B The second basic block.
Returns
The smallest region that contains A and B.
Definition at line 781 of file RegionInfo.h.
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::getCommonRegion (SmallVectorImpl< RegionT * > & Regions) const
Find the smallest region that contains a set of regions.
Parameters
Regions A vector of regions.
Returns
The smallest region that contains all regions in Regions.
Definition at line 869 of file RegionInfoImpl.h.
References llvm::SmallVectorTemplateCommon< T >::back(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back().
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::getCommonRegion (SmallVectorImpl< BlockT * > & BBs) const
Find the smallest region that contains a set of basic blocks.
Parameters
BBs A vector of basic blocks.
Returns
The smallest region that contains all basic blocks in BBS.
Definition at line 881 of file RegionInfoImpl.h.
References llvm::SmallVectorTemplateCommon< T >::back(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back().
template<class Tr > RegionInfoBase< Tr >::BlockT * llvm::RegionInfoBase< Tr >::getMaxRegionExit (BlockT * BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
Parameters
BB The BasicBlock the refined region starts.
Definition at line 813 of file RegionInfoImpl.h.
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::getRegionFor (BlockT * BB) const
Get the smallest region that contains a BasicBlock.
Parameters
BB The basic block.
Returns
The smallest region, that contains BB or NULL, if there is no region containing BB.
Definition at line 796 of file RegionInfoImpl.h.
References I.
Referenced by llvm::RegionInfoBase< RegionTraits< Function > >::getCommonRegion(), llvm::DOTGraphTraits< RegionInfoPass * >::getEdgeAttributes(), and llvm::DOTGraphTraits< RegionInfoPass * >::printRegionCluster().
template<class RegionTr> RegionT* llvm::RegionInfoBase< RegionTr >::getTopLevelRegion () const inline
Definition at line 797 of file RegionInfo.h.
Referenced by llvm::DOTGraphTraits< RegionInfoPass * >::addCustomGraphFeatures(), llvm::GraphTraits< MachineRegionInfo * >::getEntryNode(), llvm::GraphTraits< RegionInfo * >::getEntryNode(), llvm::DOTGraphTraits< RegionInfoPass * >::getNodeLabel(), llvm::DOTGraphTraits< RegionInfoPass * >::printRegionCluster(), and llvm::RGPassManager::runOnFunction().
template<class Tr > Tr::RegionT * llvm::RegionInfoBase< Tr >::operator[] (BlockT * BB) const
A shortcut for getRegionFor().
Parameters
BB The basic block.
Returns
The smallest region, that contains BB or NULL, if there is no region containing BB.
Definition at line 807 of file RegionInfoImpl.h.
template<class Tr > void llvm::RegionInfoBase< Tr >::print (raw_ostream & OS) const
Definition at line 770 of file RegionInfoImpl.h.
Referenced by llvm::MachineRegionInfoPass::print(), and llvm::RegionInfoPass::print().
template<class Tr > void llvm::RegionInfoBase< Tr >::releaseMemory ()
Definition at line 782 of file RegionInfoImpl.h.
Referenced by llvm::MachineRegionInfoPass::releaseMemory(), and llvm::RegionInfoPass::releaseMemory().
template<class Tr > void llvm::RegionInfoBase< Tr >::setRegionFor (BlockT * BB, RegionT * R)
Set the smallest region that surrounds a basic block.
Parameters
BB The basic block surrounded by a region.
R The smallest region that surrounds BB.
Definition at line 802 of file RegionInfoImpl.h.
template<class Tr > void llvm::RegionInfoBase< Tr >::splitBlock (BlockT * NewBB, BlockT * OldBB)
Update RegionInfo after a basic block was split.
Parameters
NewBB The basic block that was created before OldBB.
OldBB The old basic block.
Definition at line 892 of file RegionInfoImpl.h.
template<class Tr > void llvm::RegionInfoBase< Tr >::verifyAnalysis () const
Definition at line 790 of file RegionInfoImpl.h.
Referenced by llvm::MachineRegionInfoPass::verifyAnalysis(), and llvm::RegionInfoPass::verifyAnalysis().
Friends And Related Function Documentation
template<class RegionTr> friend class MachineRegionInfo friend
Definition at line 669 of file RegionInfo.h.
template<class RegionTr> friend class RegionInfo friend
Definition at line 668 of file RegionInfo.h.
Member Data Documentation
template<class RegionTr> Tr::RegionT::PrintStyle llvm::RegionInfoBase< Tr >::printStyle static
Initial value:
=
    RegionBase<Tr>::PrintNone
Definition at line 734 of file RegionInfo.h.
template<class RegionTr> bool llvm::RegionInfoBase< Tr >::VerifyRegionInfo = false static
Definition at line 733 of file RegionInfo.h.
The documentation for this class was generated from the following files:
RegionInfo.h
RegionInfoImpl.h