LLVM: llvm::TextInstrProfReader Class Reference
LLVM API Documentation
llvm::TextInstrProfReader Class Reference
#include <InstrProfReader.h>
Public Member Functions
TextInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer_)
std::error_code readHeader () override
Read the header.
std::error_code readNextRecord (InstrProfRecord &Record) override
Read a single record.
Public Member Functions inherited from llvm::InstrProfReader
InstrProfReader ()
virtual ~InstrProfReader ()
InstrProfIterator begin ()
Iterator over profile data.
InstrProfIterator end ()
bool isEOF ()
Return true if the reader has finished reading the profile data.
bool hasError ()
Return true if the reader encountered an error reading profiling data.
std::error_code getError ()
Get the current error code.
Additional Inherited Members
Static Public Member Functions inherited from llvm::InstrProfReader
static ErrorOr
< std::unique_ptr
< InstrProfReader > > create (std::string Path)
Protected Member Functions inherited from llvm::InstrProfReader
std::error_code error (std::error_code EC)
Set the current std::error_code and return same.
std::error_code success ()
Clear the current error code and return a successful one.
Detailed Description
Reader for the simple text based instrprof format.
This format is a simple text format that's suitable for test data. Records are separated by one or more blank lines, and record fields are separated by new lines.
Each record consists of a function name, a function hash, a number of counters, and then each counter value, in that order.
Definition at line 108 of file InstrProfReader.h.
Constructor & Destructor Documentation
llvm::TextInstrProfReader::TextInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer_) inline
Definition at line 121 of file InstrProfReader.h.
Member Function Documentation
std::error_code llvm::TextInstrProfReader::readHeader () inline override virtual
Read the header.
Implements llvm::InstrProfReader.
Definition at line 125 of file InstrProfReader.h.
References llvm::InstrProfReader::success().
std::error_code TextInstrProfReader::readNextRecord (InstrProfRecord & Record) override virtual
Read a single record.
Implements llvm::InstrProfReader.
Definition at line 89 of file InstrProfReader.cpp.
References llvm::InstrProfRecord::Counts, llvm::StringRef::empty(), llvm::eof, llvm::InstrProfReader::error(), llvm::InstrProfRecord::Hash, I, llvm::line_iterator::is_at_end(), llvm::malformed, llvm::InstrProfRecord::Name, llvm::StringRef::startswith(), llvm::InstrProfReader::success(), and llvm::truncated.
The documentation for this class was generated from the following files:
InstrProfReader.h
InstrProfReader.cpp