LLVM: llvm::object::COFFObjectFile Class Reference
LLVM API Documentation
llvm::object::COFFObjectFile Class Reference
#include <COFF.h>
Public Member Functions
uintptr_t getSymbolTable () const
uint16_t getMachine () const
uint16_t getSizeOfOptionalHeader () const
uint16_t getCharacteristics () const
uint32_t getTimeDateStamp () const
uint32_t getNumberOfSections () const
uint32_t getPointerToSymbolTable () const
uint32_t getNumberOfSymbols () const
COFFObjectFile (MemoryBufferRef Object, std::error_code &EC)
basic_symbol_iterator symbol_begin_impl () const override
basic_symbol_iterator symbol_end_impl () const override
section_iterator section_begin () const override
section_iterator section_end () const override
const coff_section * getCOFFSection (const SectionRef &Section) const
COFFSymbolRef getCOFFSymbol (const DataRefImpl &Ref) const
COFFSymbolRef getCOFFSymbol (const SymbolRef &Symbol) const
const coff_relocation * getCOFFRelocation (const RelocationRef &Reloc) const
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
unsigned getArch () const override
import_directory_iterator import_directory_begin () const
import_directory_iterator import_directory_end () const
delay_import_directory_iterator delay_import_directory_begin () const
delay_import_directory_iterator delay_import_directory_end () const
export_directory_iterator export_directory_begin () const
export_directory_iterator export_directory_end () const
base_reloc_iterator base_reloc_begin () const
base_reloc_iterator base_reloc_end () const
iterator_range
< import_directory_iterator > import_directories () const
iterator_range
< delay_import_directory_iterator > delay_import_directories () const
iterator_range
< export_directory_iterator > export_directories () const
iterator_range
< base_reloc_iterator > base_relocs () const
const dos_header * getDOSHeader () const
std::error_code getPE32Header (const pe32_header *&Res) const
std::error_code getPE32PlusHeader (const pe32plus_header *&Res) const
std::error_code getDataDirectory (uint32_t index, const data_directory *&Res) const
std::error_code getSection (int32_t index, const coff_section *&Res) const
template<typename coff_symbol_type >
std::error_code getSymbol (uint32_t Index, const coff_symbol_type *&Res) const
ErrorOr< COFFSymbolRef > getSymbol (uint32_t index) const
template<typename T >
std::error_code getAuxSymbol (uint32_t index, const T *&Res) const
std::error_code getSymbolName (COFFSymbolRef Symbol, StringRef &Res) const
ArrayRef< uint8_t > getSymbolAuxData (COFFSymbolRef Symbol) const
size_t getSymbolTableEntrySize () const
std::error_code getSectionName (const coff_section *Sec, StringRef &Res) const
uint64_t getSectionSize (const coff_section *Sec) const
std::error_code getSectionContents (const coff_section *Sec, ArrayRef< uint8_t > &Res) const
std::error_code getVaPtr (uint64_t VA, uintptr_t &Res) const
std::error_code getRvaPtr (uint32_t Rva, uintptr_t &Res) const
std::error_code getHintName (uint32_t Rva, uint16_t &Hint, StringRef &Name) const
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
bool is64 () const
template<typename coff_symbol_type >
const coff_symbol_type * toSymb (DataRefImpl Ref) const
Public Member Functions inherited from llvm::object::ObjectFile
symbol_iterator_range symbols () const
section_iterator_range sections () const
virtual std::error_code getPlatformFlags (unsigned &Result) const
Returns platform-specific object flags, if any.
Public Member Functions inherited from llvm::object::SymbolicFile
virtual ~SymbolicFile ()
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
basic_symbol_iterator symbol_begin () const
basic_symbol_iterator symbol_end () const
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isIR () const
bool isLittleEndian () const
Static Public Member Functions
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static ErrorOr< OwningBinary
< ObjectFile > > createObjectFile (StringRef ObjectPath)
Create ObjectFile from path.
static ErrorOr
< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, sys::fs::file_magic Type)
static ErrorOr
< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static ErrorOr
< std::unique_ptr
< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static ErrorOr
< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object)
static ErrorOr
< std::unique_ptr
< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static ErrorOr
< std::unique_ptr
< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, sys::fs::file_magic Type, LLVMContext *Context)
static ErrorOr
< std::unique_ptr
< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static ErrorOr< OwningBinary
< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Protected Member Functions
void moveSymbolNext (DataRefImpl &Symb) const override
std::error_code getSymbolName (DataRefImpl Symb, StringRef &Res) const override
std::error_code getSymbolAddress (DataRefImpl Symb, uint64_t &Res) const override
std::error_code getSymbolSize (DataRefImpl Symb, uint64_t &Res) const override
uint32_t getSymbolFlags (DataRefImpl Symb) const override
std::error_code getSymbolType (DataRefImpl Symb, SymbolRef::Type &Res) const override
std::error_code getSymbolSection (DataRefImpl Symb, section_iterator &Res) const override
void moveSectionNext (DataRefImpl &Sec) const override
std::error_code getSectionName (DataRefImpl Sec, StringRef &Res) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
std::error_code getSectionContents (DataRefImpl Sec, StringRef &Res) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
bool sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
std::error_code getRelocationAddress (DataRefImpl Rel, uint64_t &Res) const override
std::error_code getRelocationOffset (DataRefImpl Rel, uint64_t &Res) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
std::error_code getRelocationType (DataRefImpl Rel, uint64_t &Res) const override
std::error_code getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
std::error_code getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
std::error_code printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual std::error_code getSymbolAlignment (DataRefImpl Symb, uint32_t &Res) const
virtual std::error_code getSymbolOther (DataRefImpl Symb, uint8_t &Res) const
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual std::error_code getRelocationHidden (DataRefImpl Rel, bool &Result) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Friends
class ImportDirectoryEntryRef
class ExportDirectoryEntryRef
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
typedef iterator_range
< symbol_iterator > symbol_iterator_range
typedef iterator_range
< section_iterator > section_iterator_range
Public Types inherited from llvm::object::SymbolicFile
typedef iterator_range
< basic_symbol_iterator > basic_symbol_iterator_range
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_IR, ID_StartObjects,
ID_COFF, ID_ELF32L, ID_ELF32B, ID_ELF64L,
ID_ELF64B, ID_MachO32L, ID_MachO32B, ID_MachO64L,
ID_MachO64B, ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 484 of file Object/COFF.h.
Constructor & Destructor Documentation
COFFObjectFile::COFFObjectFile (MemoryBufferRef Object, std::error_code & EC)
Definition at line 591 of file COFFObjectFile.cpp.
References llvm::object::dos_header::AddressOfNewExeHeader, llvm::object::ObjectFile::base(), llvm::COFF::BigObjMagic, checkSize(), llvm::object::Binary::Data, getNumberOfSections(), getNumberOfSymbols(), getObject(), getPointerToSymbolTable(), llvm::COFF::IMAGE_FILE_MACHINE_UNKNOWN, llvm::object::coff_file_header::isImportLibrary(), llvm::object::coff_file_header::Machine, llvm::object::pe32_header::Magic, llvm::LibFunc::memcmp, llvm::COFF::BigObjHeader::MinBigObjectVersion, llvm::object::pe32_header::NumberOfRvaAndSize, llvm::object::pe32plus_header::NumberOfRvaAndSize, llvm::object::coff_file_header::NumberOfSections, llvm::object::parse_failed, llvm::COFF::PE32Header::PE32, llvm::COFF::PE32Header::PE32_PLUS, llvm::COFF::PEMagic, llvm::object::coff_file_header::SizeOfOptionalHeader, llvm::object::success, llvm::object::coff_bigobj_file_header::UUID, and llvm::object::coff_bigobj_file_header::Version.
Member Function Documentation
base_reloc_iterator COFFObjectFile::base_reloc_begin () const
Definition at line 781 of file COFFObjectFile.cpp.
Referenced by base_relocs().
base_reloc_iterator COFFObjectFile::base_reloc_end () const
Definition at line 785 of file COFFObjectFile.cpp.
Referenced by base_relocs().
iterator_range< base_reloc_iterator > COFFObjectFile::base_relocs () const
Definition at line 835 of file COFFObjectFile.cpp.
References base_reloc_begin(), base_reloc_end(), and llvm::make_range().
static bool llvm::object::COFFObjectFile::classof (const Binary * v) inline static
Definition at line 722 of file Object/COFF.h.
References llvm::object::Binary::isCOFF().
iterator_range< delay_import_directory_iterator > COFFObjectFile::delay_import_directories () const
Definition at line 825 of file COFFObjectFile.cpp.
References delay_import_directory_begin(), delay_import_directory_end(), and llvm::make_range().
delay_import_directory_iterator COFFObjectFile::delay_import_directory_begin () const
Definition at line 742 of file COFFObjectFile.cpp.
Referenced by delay_import_directories().
delay_import_directory_iterator COFFObjectFile::delay_import_directory_end () const
Definition at line 748 of file COFFObjectFile.cpp.
Referenced by delay_import_directories().
iterator_range< export_directory_iterator > COFFObjectFile::export_directories () const
Definition at line 831 of file COFFObjectFile.cpp.
References export_directory_begin(), export_directory_end(), and llvm::make_range().
export_directory_iterator COFFObjectFile::export_directory_begin () const
Definition at line 754 of file COFFObjectFile.cpp.
References ExportDirectoryEntryRef.
Referenced by export_directories().
export_directory_iterator COFFObjectFile::export_directory_end () const
Definition at line 759 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::AddressTableEntries, and ExportDirectoryEntryRef.
Referenced by export_directories().
unsigned COFFObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 806 of file COFFObjectFile.cpp.
References getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::Triple::thumb, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by getBytesInAddress().
template<typename T > std::error_code llvm::object::COFFObjectFile::getAuxSymbol (uint32_t index, const T *& Res) const inline
Definition at line 690 of file Object/COFF.h.
References llvm::ErrorOr< T >::getError(), getSymbol(), and llvm::object::success.
uint8_t COFFObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 789 of file COFFObjectFile.cpp.
References getArch(), and llvm::Triple::x86_64.
uint16_t llvm::object::COFFObjectFile::getCharacteristics () const inline
Definition at line 543 of file Object/COFF.h.
References llvm::object::coff_file_header::Characteristics, llvm::object::coff_file_header::isImportLibrary(), and llvm_unreachable.
const coff_relocation * COFFObjectFile::getCOFFRelocation (const RelocationRef & Reloc) const
Definition at line 1065 of file COFFObjectFile.cpp.
References llvm::object::RelocationRef::getRawDataRefImpl().
const coff_section * COFFObjectFile::getCOFFSection (const SectionRef & Section) const
Definition at line 1048 of file COFFObjectFile.cpp.
References llvm::object::SectionRef::getRawDataRefImpl().
Referenced by getRvaPtr().
COFFSymbolRef llvm::object::COFFObjectFile::getCOFFSymbol (const DataRefImpl & Ref) const
Referenced by getSymbolAddress(), getSymbolFlags(), getSymbolSection(), getSymbolSize(), getSymbolType(), and sectionContainsSymbol().
COFFSymbolRef llvm::object::COFFObjectFile::getCOFFSymbol (const SymbolRef & Symbol) const
std::error_code COFFObjectFile::getDataDirectory (uint32_t index, const data_directory *& Res) const
Definition at line 851 of file COFFObjectFile.cpp.
References assert(), llvm::object::pe32_header::NumberOfRvaAndSize, llvm::object::pe32plus_header::NumberOfRvaAndSize, llvm::object::parse_failed, and llvm::object::success.
const dos_header* llvm::object::COFFObjectFile::getDOSHeader () const inline
Definition at line 655 of file Object/COFF.h.
References llvm::object::ObjectFile::base().
StringRef COFFObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 793 of file COFFObjectFile.cpp.
References getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, and llvm::COFF::IMAGE_FILE_MACHINE_I386.
std::error_code COFFObjectFile::getHintName (uint32_t Rva, uint16_t & Hint, StringRef & Name) const
Definition at line 495 of file COFFObjectFile.cpp.
References getRvaPtr(), and llvm::object::success.
uint16_t llvm::object::COFFObjectFile::getMachine () const inline
Definition at line 527 of file Object/COFF.h.
References llvm_unreachable, llvm::object::coff_file_header::Machine, and llvm::object::coff_bigobj_file_header::Machine.
Referenced by getArch(), getFileFormatName(), and getRelocationTypeName().
uint32_t llvm::object::COFFObjectFile::getNumberOfSections () const inline
Definition at line 559 of file Object/COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::NumberOfSections, and llvm::object::coff_bigobj_file_header::NumberOfSections.
Referenced by COFFObjectFile(), getSection(), and section_end().
uint32_t llvm::object::COFFObjectFile::getNumberOfSymbols () const inline
Definition at line 574 of file Object/COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::NumberOfSymbols, and llvm::object::coff_bigobj_file_header::NumberOfSymbols.
Referenced by COFFObjectFile(), getRelocationSymbol(), getSymbol(), and getSymbolAuxData().
std::error_code COFFObjectFile::getPE32Header (const pe32_header *& Res) const
Definition at line 839 of file COFFObjectFile.cpp.
References llvm::object::success.
std::error_code COFFObjectFile::getPE32PlusHeader (const pe32plus_header *& Res) const
Definition at line 845 of file COFFObjectFile.cpp.
References llvm::object::success.
uint32_t llvm::object::COFFObjectFile::getPointerToSymbolTable () const inline
Definition at line 566 of file Object/COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::PointerToSymbolTable, and llvm::object::coff_bigobj_file_header::PointerToSymbolTable.
Referenced by COFFObjectFile(), getSymbolAuxData(), and toSymb().
std::error_code COFFObjectFile::getRelocationAddress (DataRefImpl Rel, uint64_t & Res) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1010 of file COFFObjectFile.cpp.
References llvm::report_fatal_error().
std::error_code COFFObjectFile::getRelocationOffset (DataRefImpl Rel, uint64_t & Res) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1015 of file COFFObjectFile.cpp.
References llvm::object::Binary::Data, getObject(), llvm::object::success, and llvm::object::coff_relocation::VirtualAddress.
symbol_iterator COFFObjectFile::getRelocationSymbol (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1026 of file COFFObjectFile.cpp.
References getNumberOfSymbols(), llvm_unreachable, llvm::object::DataRefImpl::p, llvm::object::SymbolicFile::symbol_end(), llvm::object::ObjectFile::SymbolRef, and llvm::object::coff_relocation::SymbolTableIndex.
std::error_code COFFObjectFile::getRelocationType (DataRefImpl Rel, uint64_t & Res) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1040 of file COFFObjectFile.cpp.
References llvm::object::success, and llvm::object::coff_relocation::Type.
std::error_code COFFObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1075 of file COFFObjectFile.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMAGE_REL_AMD64_ABSOLUTE, llvm::COFF::IMAGE_REL_AMD64_ADDR32, llvm::COFF::IMAGE_REL_AMD64_ADDR32NB, llvm::COFF::IMAGE_REL_AMD64_ADDR64, llvm::COFF::IMAGE_REL_AMD64_PAIR, llvm::COFF::IMAGE_REL_AMD64_REL32, llvm::COFF::IMAGE_REL_AMD64_REL32_1, llvm::COFF::IMAGE_REL_AMD64_REL32_2, llvm::COFF::IMAGE_REL_AMD64_REL32_3, llvm::COFF::IMAGE_REL_AMD64_REL32_4, llvm::COFF::IMAGE_REL_AMD64_REL32_5, llvm::COFF::IMAGE_REL_AMD64_SECREL, llvm::COFF::IMAGE_REL_AMD64_SECREL7, llvm::COFF::IMAGE_REL_AMD64_SECTION, llvm::COFF::IMAGE_REL_AMD64_SREL32, llvm::COFF::IMAGE_REL_AMD64_SSPAN32, llvm::COFF::IMAGE_REL_AMD64_TOKEN, llvm::COFF::IMAGE_REL_ARM_ABSOLUTE, llvm::COFF::IMAGE_REL_ARM_ADDR32, llvm::COFF::IMAGE_REL_ARM_ADDR32NB, llvm::COFF::IMAGE_REL_ARM_BLX11, llvm::COFF::IMAGE_REL_ARM_BLX23T, llvm::COFF::IMAGE_REL_ARM_BLX24, llvm::COFF::IMAGE_REL_ARM_BRANCH11, llvm::COFF::IMAGE_REL_ARM_BRANCH20T, llvm::COFF::IMAGE_REL_ARM_BRANCH24, llvm::COFF::IMAGE_REL_ARM_BRANCH24T, llvm::COFF::IMAGE_REL_ARM_MOV32A, llvm::COFF::IMAGE_REL_ARM_MOV32T, llvm::COFF::IMAGE_REL_ARM_SECREL, llvm::COFF::IMAGE_REL_ARM_SECTION, llvm::COFF::IMAGE_REL_ARM_TOKEN, llvm::COFF::IMAGE_REL_I386_ABSOLUTE, llvm::COFF::IMAGE_REL_I386_DIR16, llvm::COFF::IMAGE_REL_I386_DIR32, llvm::COFF::IMAGE_REL_I386_DIR32NB, llvm::COFF::IMAGE_REL_I386_REL16, llvm::COFF::IMAGE_REL_I386_REL32, llvm::COFF::IMAGE_REL_I386_SECREL, llvm::COFF::IMAGE_REL_I386_SECREL7, llvm::COFF::IMAGE_REL_I386_SECTION, llvm::COFF::IMAGE_REL_I386_SEG12, llvm::COFF::IMAGE_REL_I386_TOKEN, LLVM_COFF_SWITCH_RELOC_TYPE_NAME, llvm::object::success, and llvm::object::coff_relocation::Type.
std::error_code COFFObjectFile::getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1151 of file COFFObjectFile.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), llvm::ErrorOr< T >::getError(), getSymbol(), getSymbolName(), llvm::object::DataRefImpl::p, llvm::object::success, and llvm::object::coff_relocation::SymbolTableIndex.
std::error_code COFFObjectFile::getRvaPtr (uint32_t Rva, uintptr_t & Res) const
Definition at line 479 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), getCOFFSection(), llvm::object::parse_failed, llvm::object::coff_section::PointerToRawData, llvm::ARMBuildAttrs::Section, llvm::object::ObjectFile::sections(), llvm::object::success, llvm::object::coff_section::VirtualAddress, and llvm::object::coff_section::VirtualSize.
Referenced by llvm::object::ExportDirectoryEntryRef::getDllName(), llvm::object::ExportDirectoryEntryRef::getExportRVA(), getHintName(), llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), llvm::object::ImportDirectoryEntryRef::getImportLookupEntry(), llvm::object::ImportDirectoryEntryRef::getName(), llvm::object::DelayImportDirectoryEntryRef::getName(), llvm::object::ImportedSymbolRef::getOrdinal(), llvm::object::ExportDirectoryEntryRef::getSymbolName(), llvm::object::ImportedSymbolRef::getSymbolName(), and getVaPtr().
std::error_code COFFObjectFile::getSection (int32_t index, const coff_section *& Res) const
Definition at line 869 of file COFFObjectFile.cpp.
References getNumberOfSections(), llvm::COFF::isReservedSectionNumber(), llvm::object::parse_failed, and llvm::object::success.
Referenced by getSymbolAddress(), getSymbolSection(), getSymbolSize(), and getSymbolType().
uint64_t COFFObjectFile::getSectionAddress (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 327 of file COFFObjectFile.cpp.
References llvm::object::coff_section::VirtualAddress.
uint64_t COFFObjectFile::getSectionAlignment (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 345 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics.
std::error_code llvm::object::COFFObjectFile::getSectionContents (DataRefImpl Sec, StringRef & Res) const override protected virtual
Implements llvm::object::ObjectFile.
std::error_code llvm::object::COFFObjectFile::getSectionContents (const coff_section * Sec, ArrayRef< uint8_t > & Res) const
std::error_code llvm::object::COFFObjectFile::getSectionName (DataRefImpl Sec, StringRef & Res) const override protected virtual
Implements llvm::object::ObjectFile.
std::error_code llvm::object::COFFObjectFile::getSectionName (const coff_section * Sec, StringRef & Res) const
uint64_t llvm::object::COFFObjectFile::getSectionSize (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
uint64_t llvm::object::COFFObjectFile::getSectionSize (const coff_section * Sec) const
uint16_t llvm::object::COFFObjectFile::getSizeOfOptionalHeader () const inline
Definition at line 534 of file Object/COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, and llvm::object::coff_file_header::SizeOfOptionalHeader.
template<typename coff_symbol_type > std::error_code llvm::object::COFFObjectFile::getSymbol (uint32_t Index, const coff_symbol_type *& Res) const inline
Definition at line 666 of file Object/COFF.h.
References getNumberOfSymbols(), getSymbolTable(), llvm::object::parse_failed, and llvm::object::success.
Referenced by getAuxSymbol(), getRelocationValueString(), and getSymbol().
ErrorOr<COFFSymbolRef> llvm::object::COFFObjectFile::getSymbol (uint32_t index) const inline
Definition at line 674 of file Object/COFF.h.
References getSymbol(), and llvm::object::parse_failed.
std::error_code COFFObjectFile::getSymbolAddress (DataRefImpl Symb, uint64_t & Res) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 153 of file COFFObjectFile.cpp.
References getCOFFSymbol(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::COFFSymbolRef::getValue(), llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::COFF::isReservedSectionNumber(), llvm::ARMBuildAttrs::Section, llvm::object::success, llvm::object::UnknownAddressOrSize, and llvm::object::coff_section::VirtualAddress.
Referenced by getSymbolSize().
ArrayRef< uint8_t > COFFObjectFile::getSymbolAuxData (COFFSymbolRef Symbol) const
Definition at line 913 of file COFFObjectFile.cpp.
References assert(), llvm::object::ObjectFile::base(), llvm::object::COFFSymbolRef::getNumberOfAuxSymbols(), getNumberOfSymbols(), getPointerToSymbolTable(), llvm::object::COFFSymbolRef::getRawPtr(), getSymbolTableEntrySize(), llvm::makeArrayRef(), and llvm::report_fatal_error().
uint32_t COFFObjectFile::getSymbolFlags (DataRefImpl Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 209 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::object::COFFSymbolRef::isExternal(), llvm::object::COFFSymbolRef::isFileRecord(), llvm::object::COFFSymbolRef::isSectionDefinition(), llvm::object::COFFSymbolRef::isWeakExternal(), llvm::object::BasicSymbolRef::SF_Absolute, llvm::object::BasicSymbolRef::SF_Common, llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Undefined, and llvm::object::BasicSymbolRef::SF_Weak.
std::error_code llvm::object::COFFObjectFile::getSymbolName (DataRefImpl Symb, StringRef & Res) const override protected virtual
Implements llvm::object::ObjectFile.
Referenced by getRelocationValueString().
std::error_code llvm::object::COFFObjectFile::getSymbolName (COFFSymbolRef Symbol, StringRef & Res) const
std::error_code COFFObjectFile::getSymbolSection (DataRefImpl Symb, section_iterator & Res) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 299 of file COFFObjectFile.cpp.
References getCOFFSymbol(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::isReservedSectionNumber(), llvm::object::DataRefImpl::p, section_end(), llvm::object::ObjectFile::SectionRef, and llvm::object::success.
std::error_code COFFObjectFile::getSymbolSize (DataRefImpl Symb, uint64_t & Res) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 237 of file COFFObjectFile.cpp.
References getCOFFSymbol(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), getSymbolAddress(), llvm::object::COFFSymbolRef::getValue(), llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::COFF::isReservedSectionNumber(), llvm::ARMBuildAttrs::Section, section_end(), sectionContainsSymbol(), llvm::object::coff_section::SizeOfRawData, llvm::object::success, llvm::object::ObjectFile::symbols(), and llvm::object::UnknownAddressOrSize.
uintptr_t llvm::object::COFFObjectFile::getSymbolTable () const inline
Definition at line 520 of file Object/COFF.h.
Referenced by getSymbol(), and symbol_begin_impl().
size_t llvm::object::COFFObjectFile::getSymbolTableEntrySize () const inline
Definition at line 701 of file Object/COFF.h.
References llvm_unreachable.
Referenced by getSymbolAuxData().
std::error_code COFFObjectFile::getSymbolType (DataRefImpl Symb, SymbolRef::Type & Res) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 179 of file COFFObjectFile.cpp.
References Characteristics, llvm::object::coff_section::Characteristics, getCOFFSymbol(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::IMAGE_SCN_CNT_CODE, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SYM_DEBUG, llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::object::COFFSymbolRef::isFileRecord(), llvm::object::COFFSymbolRef::isFunctionDefinition(), llvm::COFF::isReservedSectionNumber(), llvm::ARMBuildAttrs::Section, llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_File, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::object::SymbolRef::ST_Unknown, and llvm::object::success.
uint32_t llvm::object::COFFObjectFile::getTimeDateStamp () const inline
Definition at line 552 of file Object/COFF.h.
References llvm_unreachable, llvm::object::coff_file_header::TimeDateStamp, and llvm::object::coff_bigobj_file_header::TimeDateStamp.
std::error_code COFFObjectFile::getVaPtr (uint64_t VA, uintptr_t & Res) const
Definition at line 470 of file COFFObjectFile.cpp.
References assert(), getRvaPtr(), llvm::object::pe32_header::ImageBase, and llvm::object::pe32plus_header::ImageBase.
iterator_range< import_directory_iterator > COFFObjectFile::import_directories () const
Definition at line 820 of file COFFObjectFile.cpp.
References import_directory_begin(), import_directory_end(), and llvm::make_range().
import_directory_iterator COFFObjectFile::import_directory_begin () const
Definition at line 731 of file COFFObjectFile.cpp.
References ImportDirectoryEntryRef.
Referenced by import_directories().
import_directory_iterator COFFObjectFile::import_directory_end () const
Definition at line 736 of file COFFObjectFile.cpp.
References ImportDirectoryEntryRef.
Referenced by import_directories().
bool llvm::object::COFFObjectFile::is64 () const inline
Definition at line 720 of file Object/COFF.h.
Referenced by llvm::object::DelayImportDirectoryEntryRef::getImportAddress().
bool COFFObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 1166 of file COFFObjectFile.cpp.
bool COFFObjectFile::isSectionBSS (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 360 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA.
bool COFFObjectFile::isSectionData (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 355 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA.
bool COFFObjectFile::isSectionText (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 350 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::COFF::IMAGE_SCN_CNT_CODE.
bool COFFObjectFile::isSectionVirtual (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 365 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA.
void COFFObjectFile::moveRelocationNext (DataRefImpl & Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1005 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
void COFFObjectFile::moveSectionNext (DataRefImpl & Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 315 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
void COFFObjectFile::moveSymbolNext (DataRefImpl & Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 132 of file COFFObjectFile.cpp.
References llvm_unreachable, llvm::object::coff_symbol< SectionNumberType >::NumberOfAuxSymbols, and llvm::object::DataRefImpl::p.
section_iterator COFFObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 767 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, and llvm::object::ObjectFile::SectionRef.
section_iterator COFFObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 773 of file COFFObjectFile.cpp.
References getNumberOfSections(), llvm::object::coff_file_header::isImportLibrary(), llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, and llvm::object::ObjectFile::SectionRef.
Referenced by getSymbolSection(), and getSymbolSize().
relocation_iterator COFFObjectFile::section_rel_begin (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 412 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::sys::path::begin(), llvm::object::Binary::Data, getFirstReloc(), llvm::object::DataRefImpl::p, llvm::object::ObjectFile::RelocationRef, and llvm::MipsISD::Ret.
relocation_iterator COFFObjectFile::section_rel_end (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 420 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, getFirstReloc(), getNumberOfRelocations(), I, llvm::object::DataRefImpl::p, llvm::object::ObjectFile::RelocationRef, and llvm::MipsISD::Ret.
bool COFFObjectFile::sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 370 of file COFFObjectFile.cpp.
References getCOFFSymbol(), and llvm::object::COFFSymbolRef::getSectionNumber().
Referenced by getSymbolSize().
basic_symbol_iterator COFFObjectFile::symbol_begin_impl () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 718 of file COFFObjectFile.cpp.
References getSymbolTable(), llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, and llvm::object::ObjectFile::SymbolRef.
basic_symbol_iterator COFFObjectFile::symbol_end_impl () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 724 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, llvm::MipsISD::Ret, and llvm::object::ObjectFile::SymbolRef.
template<typename coff_symbol_type > const coff_symbol_type* llvm::object::COFFObjectFile::toSymb (DataRefImpl Ref) const
Definition at line 100 of file COFFObjectFile.cpp.
References assert(), llvm::object::ObjectFile::base(), checkOffset(), llvm::object::Binary::Data, getPointerToSymbolTable(), and llvm::object::DataRefImpl::p.
Friends And Related Function Documentation
friend class ExportDirectoryEntryRef friend
Definition at line 487 of file Object/COFF.h.
Referenced by export_directory_begin(), and export_directory_end().
friend class ImportDirectoryEntryRef friend
Definition at line 486 of file Object/COFF.h.
Referenced by import_directory_begin(), and import_directory_end().
The documentation for this class was generated from the following files:
Object/COFF.h
COFFObjectFile.cpp