LLVM: llvm::ARMException Class Reference
LLVM API Documentation
llvm::ARMException Class Reference
#include <DwarfException.h>
Public Member Functions
ARMException (AsmPrinter *A)
virtual ~ARMException ()
void endModule () override
void beginFunction (const MachineFunction *MF) override
void endFunction (const MachineFunction *) override
endFunction - Gather and emit post-function exception information.
Public Member Functions inherited from llvm::EHStreamer
EHStreamer (AsmPrinter *A)
virtual ~EHStreamer ()
void endModule () override
Emit all exception information that should come after the content.
void beginFunction (const MachineFunction *MF) override
void endFunction (const MachineFunction *) override
Gather and emit post-function exception information.
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g. common symbols), this tracks that size.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
Additional Inherited Members
Protected Types inherited from llvm::EHStreamer
typedef DenseMap< MCSymbol
*, PadRange > RangeMapType
Protected Member Functions inherited from llvm::EHStreamer
unsigned computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LPs, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
bool callToNoUnwindFunction (const MachineInstr *MI)
void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, const SmallVectorImpl< const LandingPadInfo * > &LPs, const SmallVectorImpl< unsigned > &FirstActions)
void emitExceptionTable ()
Static Protected Member Functions inherited from llvm::EHStreamer
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
Protected Attributes inherited from llvm::EHStreamer
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Detailed Description
Definition at line 58 of file DwarfException.h.
Constructor & Destructor Documentation
ARMException::ARMException (AsmPrinter * A)
Definition at line 39 of file ARMException.cpp.
ARMException::~ARMException () virtual
Definition at line 42 of file ARMException.cpp.
Member Function Documentation
void ARMException::beginFunction (const MachineFunction * MF) override virtual
beginFunction - Gather pre-function exception information. Assumes being emitted immediately after the function entry point.
beginFunction - Gather pre-function exception information. Assumes it's being emitted immediately after the function entry point.
Implements llvm::AsmPrinterHandler.
Definition at line 58 of file ARMException.cpp.
References llvm::ARM, llvm::EHStreamer::Asm, assert(), llvm::AsmPrinter::CFI_M_Debug, llvm::AsmPrinter::CFI_M_EH, llvm::MCStreamer::EmitCFIStartProc(), llvm::ARMTargetStreamer::emitFnStart(), llvm::MCStreamer::EmitLabel(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::AsmPrinter::getFunctionNumber(), llvm::AsmPrinter::GetTempSymbol(), llvm::AsmPrinter::MAI, llvm::AsmPrinter::needsCFIMoves(), and llvm::AsmPrinter::OutStreamer.
void ARMException::endFunction (const MachineFunction *) override virtual
endFunction - Gather and emit post-function exception information.
endFunction - Gather and emit post-function exception information.
Implements llvm::AsmPrinterHandler.
Definition at line 75 of file ARMException.cpp.
References llvm::ARM, llvm::EHStreamer::Asm, llvm::ARMTargetStreamer::emitCantUnwind(), llvm::MCStreamer::EmitCFIEndProc(), llvm::EHStreamer::emitExceptionTable(), llvm::ARMTargetStreamer::emitFnEnd(), llvm::ARMTargetStreamer::emitHandlerData(), llvm::MCStreamer::EmitLabel(), llvm::ARMTargetStreamer::emitPersonality(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFunction(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineModuleInfo::getLandingPads(), llvm::MachineModuleInfo::getPersonalities(), llvm::MachineModuleInfo::getPersonalityIndex(), llvm::AsmPrinter::getSymbol(), llvm::AsmPrinter::GetTempSymbol(), llvm::AsmPrinter::MAI, llvm::MCSA_Global, llvm::AsmPrinter::MF, llvm::EHStreamer::MMI, llvm::Function::needsUnwindTableEntry(), llvm::AsmPrinter::OutStreamer, and llvm::MachineModuleInfo::TidyLandingPads().
void ARMException::endModule () override virtual
endModule - Emit all exception information that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 51 of file ARMException.cpp.
References llvm::EHStreamer::Asm, llvm::MCStreamer::EmitCFISections(), and llvm::AsmPrinter::OutStreamer.
The documentation for this class was generated from the following files:
DwarfException.h
ARMException.cpp