LLVM: llvm::RuntimeDyldCheckerExprEval Class Reference
LLVM API Documentation
llvm::RuntimeDyldCheckerExprEval Class Reference
Public Member Functions
RuntimeDyldCheckerExprEval (const RuntimeDyldCheckerImpl &Checker, raw_ostream &ErrStream)
bool evaluate (StringRef Expr) const
Detailed Description
Definition at line 28 of file RuntimeDyldChecker.cpp.
Constructor & Destructor Documentation
llvm::RuntimeDyldCheckerExprEval::RuntimeDyldCheckerExprEval (const RuntimeDyldCheckerImpl & Checker, raw_ostream & ErrStream) inline
Definition at line 30 of file RuntimeDyldChecker.cpp.
Member Function Documentation
bool llvm::RuntimeDyldCheckerExprEval::evaluate (StringRef Expr) const inline
Definition at line 34 of file RuntimeDyldChecker.cpp.
References llvm::StringRef::find(), llvm::format(), llvm::StringRef::ltrim(), llvm::StringRef::rtrim(), llvm::StringRef::substr(), and llvm::StringRef::trim().
Referenced by llvm::RuntimeDyldCheckerImpl::check().
The documentation for this class was generated from the following file:
RuntimeDyldChecker.cpp