LLVM: llvm::AMDGPUInstPrinter Class Reference
LLVM API Documentation
llvm::AMDGPUInstPrinter Class Reference
#include <AMDGPUInstPrinter.h>
Public Member Functions
AMDGPUInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, raw_ostream &O)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot) override
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
printRegName - Print the assembler register name.
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 22 of file AMDGPUInstPrinter.h.
Constructor & Destructor Documentation
llvm::AMDGPUInstPrinter::AMDGPUInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 24 of file AMDGPUInstPrinter.h.
Member Function Documentation
static const char* llvm::AMDGPUInstPrinter::getRegisterName (unsigned RegNo) static
void AMDGPUInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) override virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 22 of file AMDGPUInstPrinter.cpp.
References llvm::raw_ostream::flush(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
Referenced by llvm::AMDGPUAsmPrinter::EmitInstruction().
void llvm::AMDGPUInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
The documentation for this class was generated from the following files:
AMDGPUInstPrinter.h
AMDGPUInstPrinter.cpp