LLVM: llvm::DwarfDebug Class Reference
LLVM API Documentation
llvm::DwarfDebug Class Reference
Collects and handles dwarf debug information.
#include <DwarfDebug.h>
Public Member Functions
DwarfDebug (AsmPrinter *A, Module *M)
~DwarfDebug () override
void beginModule ()
Emit all Dwarf sections that should come prior to the content.
void endModule () override
Emit all Dwarf sections that should come after the content.
void beginFunction (const MachineFunction *MF) override
Gather pre-function debug information.
void endFunction (const MachineFunction *MF) override
Gather and emit post-function debug information.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
void addDwarfTypeUnitType (DwarfCompileUnit &CU, StringRef Identifier, DIE &Die, DICompositeType CTy)
Add a DIE to the set of types that we're going to pull into type units.
void addArangeLabel (SymbolCU SCU)
Add a label so that arange data can be generated for it.
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g. common symbols), this tracks that size.
void emitDIE (DIE &Die)
Recursively Emits a debug information entry.
bool useDwarfAccelTables () const
Returns whether or not to emit tables that dwarf consumers can use to accelerate lookup.
bool useSplitDwarf () const
Returns whether or not to change the current debug info for the split dwarf proposal support.
unsigned getDwarfVersion () const
Returns the Dwarf Version.
MCSymbol * getDebugLocSym () const
Returns the section symbol for the .debug_loc section.
MCSymbol * getDebugStrSym () const
Returns the section symbol for the .debug_str section.
MCSymbol * getRangeSectionSym () const
Returns the section symbol for the .debug_ranges section.
const DwarfCompileUnit * getPrevCU () const
Returns the previous CU that was being updated.
void setPrevCU (const DwarfCompileUnit *PrevCU)
const SmallVectorImpl
< DebugLocList > & getDebugLocEntries () const
Returns the entries for the .debug_loc section.
void emitDebugLocEntry (ByteStreamer &Streamer, const DebugLocEntry &Entry)
Emit an entry for the debug loc section. This can be used to handle an entry that's going to be emitted into the debug loc section.
void emitDebugLocValue (ByteStreamer &Streamer, const DebugLocEntry::Value &Value, unsigned PieceOffsetInBits=0)
emit a single value for the debug loc section.
void emitLocPieces (ByteStreamer &Streamer, const DITypeIdentifierMap &Map, ArrayRef< DebugLocEntry::Value > Values)
Emits an optimal (=sorted) sequence of DW_OP_pieces.
void emitDebugLocEntryLocation (const DebugLocEntry &Entry)
Emit the location for a debug loc entry, including the size header.
template<typename T >
T resolve (DIRef< T > Ref) const
Find the MDNode for the given reference.
const DITypeIdentifierMap & getTypeIdentifierMap () const
Return the TypeIdentifierMap.
DwarfCompileUnit * lookupUnit (const DIE *CU) const
Find the DwarfCompileUnit for the given CU Die.
bool isSubprogramContext (const MDNode *Context)
void addSubprogramNames (DISubprogram SP, DIE &Die)
AddressPool & getAddressPool ()
void addAccelName (StringRef Name, const DIE &Die)
void addAccelObjC (StringRef Name, const DIE &Die)
void addAccelNamespace (StringRef Name, const DIE &Die)
void addAccelType (StringRef Name, const DIE &Die, char Flags)
const MachineFunction * getCurrentFunction () const
const MCSymbol * getFunctionBeginSym () const
const MCSymbol * getFunctionEndSym () const
iterator_range
< ImportedEntityMap::const_iterator > findImportedEntitiesForScope (const MDNode *Scope) const
bool isLexicalScopeDIENull (LexicalScope *Scope)
A helper function to check whether the DIE for a given Scope is going to be null.
MCSymbol * getLabelBeforeInsn (const MachineInstr *MI)
Return Label preceding the instruction.
MCSymbol * getLabelAfterInsn (const MachineInstr *MI)
Return Label immediately following the instruction.
unsigned getNextRangeNumber ()
SmallPtrSet< const MDNode *, 16 > & getProcessedSPNodes ()
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
Detailed Description
Collects and handles dwarf debug information.
Definition at line 156 of file DwarfDebug.h.
Constructor & Destructor Documentation
DwarfDebug::DwarfDebug (AsmPrinter * A, Module * M)
Definition at line 171 of file DwarfDebug.cpp.
References beginModule(), DbgTimerName, Default, DwarfAccelTables, DWARFGroupName, DwarfPubSections, llvm::MCTargetOptions::DwarfVersion, llvm::MCStreamer::getContext(), llvm::Module::getDwarfVersion(), llvm::MachineModuleInfo::getModule(), llvm::TargetOptions::MCOptions, llvm::TargetMachine::Options, llvm::AsmPrinter::OutStreamer, llvm::MCContext::setDwarfVersion(), SplitDwarf, T, llvm::TimePassesIsEnabled, and llvm::AsmPrinter::TM.
DwarfDebug::~DwarfDebug () override
Definition at line 224 of file DwarfDebug.cpp.
Member Function Documentation
void DwarfDebug::addAccelName (StringRef Name, const DIE & Die)
Definition at line 2165 of file DwarfDebug.cpp.
References llvm::DwarfAccelTable::AddName(), llvm::DwarfFile::getStringPool(), llvm::DwarfStringPool::getSymbol(), and useDwarfAccelTables().
Referenced by addSubprogramNames(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
void DwarfDebug::addAccelNamespace (StringRef Name, const DIE & Die)
Definition at line 2179 of file DwarfDebug.cpp.
References llvm::DwarfAccelTable::AddName(), llvm::DwarfFile::getStringPool(), llvm::DwarfStringPool::getSymbol(), and useDwarfAccelTables().
Referenced by llvm::DwarfUnit::getOrCreateNameSpace().
void DwarfDebug::addAccelObjC (StringRef Name, const DIE & Die)
Definition at line 2172 of file DwarfDebug.cpp.
References llvm::DwarfAccelTable::AddName(), llvm::DwarfFile::getStringPool(), llvm::DwarfStringPool::getSymbol(), and useDwarfAccelTables().
Referenced by addSubprogramNames().
void DwarfDebug::addAccelType (StringRef Name, const DIE & Die, char Flags)
Definition at line 2186 of file DwarfDebug.cpp.
References llvm::DwarfAccelTable::AddName(), llvm::DwarfFile::getStringPool(), llvm::DwarfStringPool::getSymbol(), and useDwarfAccelTables().
void llvm::DwarfDebug::addArangeLabel (SymbolCU SCU) inline
Add a label so that arange data can be generated for it.
Definition at line 519 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocalLabelAddress(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
void DwarfDebug::addDwarfTypeUnitType (DwarfCompileUnit & CU, StringRef Identifier, DIE & Die, DICompositeType CTy)
Add a DIE to the set of types that we're going to pull into type units.
Definition at line 2088 of file DwarfDebug.cpp.
References llvm::DwarfUnit::addDIETypeSignature(), llvm::DwarfCompileUnit::applyStmtList(), llvm::DwarfUnit::constructTypeDIE(), llvm::dwarf::DW_AT_language, llvm::dwarf::DW_FORM_data2, llvm::DwarfUnit::getLanguage(), llvm::DwarfFile::getUnits(), llvm::AddressPool::hasBeenUsed(), makeTypeSignature(), llvm::AddressPool::resetUsedFlag(), and useSplitDwarf().
Referenced by llvm::DwarfUnit::getOrCreateTypeDIE().
void DwarfDebug::addSubprogramNames (DISubprogram SP, DIE & Die)
Definition at line 278 of file DwarfDebug.cpp.
References addAccelName(), addAccelObjC(), llvm::tgtok::Class, llvm::DISubprogram::getLinkageName(), llvm::DISubprogram::getName(), getObjCClassCategory(), getObjCMethodName(), llvm::DISubprogram::isDefinition(), and isObjCClass().
Referenced by llvm::DwarfCompileUnit::constructInlinedScopeDIE(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
void DwarfDebug::beginFunction (const MachineFunction * MF) override virtual
Gather pre-function debug information.
Implements llvm::AsmPrinterHandler.
Definition at line 1133 of file DwarfDebug.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::calculateDbgValueHistory(), llvm::dwarf::DW_TAG_arg_variable, DWARF2_FLAG_IS_STMT, llvm::SmallVectorBase::empty(), llvm::LexicalScopes::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), findPrologueEndLoc(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::DebugLoc::getCol(), llvm::Function::getContext(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::getDISubprogram(), llvm::DebugLoc::getFnDebugLoc(), llvm::MachineFunction::getFunction(), llvm::DebugLoc::getLine(), llvm::DebugLoc::getScope(), llvm::LexicalScope::getScopeNode(), llvm::DwarfUnit::getUniqueID(), llvm::MachineModuleInfo::hasDebugInfo(), I, llvm::LexicalScopes::initialize(), llvm::DebugLoc::isUnknown(), and piecesOverlap().
void DwarfDebug::beginInstruction (const MachineInstr * MI) override virtual
Process beginning of an instruction.
Implements llvm::AsmPrinterHandler.
Definition at line 1017 of file DwarfDebug.cpp.
References assert(), llvm::MCContext::CreateTempSymbol(), DL, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, llvm::DebugLoc::getCol(), llvm::MachineModuleInfo::getContext(), llvm::MachineInstr::getDebugLoc(), llvm::DebugLoc::getLine(), llvm::DebugLoc::getScope(), I, llvm::MachineInstr::isDebugValue(), llvm::DebugLoc::isUnknown(), llvm::AArch64CC::MI, and UnknownLocations.
void DwarfDebug::beginModule ()
Emit all Dwarf sections that should come prior to the content.
Definition at line 435 of file DwarfDebug.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), DisableDebugInfoPrinting, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::generateDITypeIdentifierMap(), llvm::DITypedArray< T >::getElement(), llvm::DICompileUnit::getEnumTypes(), llvm::DICompileUnit::getGlobalVariables(), llvm::DICompileUnit::getImportedEntities(), llvm::MachineModuleInfo::getModule(), llvm::Module::getNamedMetadata(), llvm::DITypedArray< T >::getNumElements(), llvm::NamedMDNode::getNumOperands(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DICompileUnit::getRetainedTypes(), llvm::DICompileUnit::getSubprograms(), llvm::makeSubprogramMap(), llvm::NamedMDNode::operands(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), resolve(), and llvm::MachineModuleInfo::setDebugInfoAvailability().
Referenced by DwarfDebug().
void DwarfDebug::emitDebugLocEntry (ByteStreamer & Streamer, const DebugLocEntry & Entry)
Emit an entry for the debug loc section. This can be used to handle an entry that's going to be emitted into the debug loc section.
Definition at line 1699 of file DwarfDebug.cpp.
References assert(), emitDebugLocValue(), emitLocPieces(), llvm::DebugLocEntry::getValues(), and llvm::DebugLocEntry::Value::isVariablePiece().
Referenced by emitDebugLocEntryLocation().
void DwarfDebug::emitDebugLocEntryLocation (const DebugLocEntry & Entry)
Emit the location for a debug loc entry, including the size header.
Definition at line 1747 of file DwarfDebug.cpp.
References llvm::sys::path::begin(), emitDebugLocEntry(), and llvm::sys::path::end().
void DwarfDebug::emitDebugLocValue (ByteStreamer & Streamer, const DebugLocEntry::Value & Value, unsigned PieceOffsetInBits = 0)
emit a single value for the debug loc section.
Definition at line 1710 of file DwarfDebug.cpp.
References llvm::DwarfExpression::AddExpression(), llvm::DwarfExpression::AddMachineRegExpression(), llvm::DwarfExpression::AddMachineRegIndirect(), llvm::DwarfExpression::AddSignedConstant(), llvm::DwarfExpression::AddUnsignedConstant(), llvm::dwarf::DW_ATE_signed, llvm::dwarf::DW_ATE_signed_char, llvm::dwarf::DW_OP_deref, llvm::DebugLocDwarfExpression::EmitOp(), llvm::DIBasicType::getEncoding(), llvm::DebugLocEntry::Value::getExpression(), llvm::DebugLocEntry::Value::getInt(), llvm::DebugLocEntry::Value::getLoc(), llvm::DIExpression::getNumElements(), llvm::MachineLocation::getOffset(), llvm::MachineLocation::getReg(), llvm::DIVariable::getType(), llvm::DebugLocEntry::Value::getVariable(), llvm::DIVariable::isIndirect(), llvm::DebugLocEntry::Value::isInt(), llvm::DebugLocEntry::Value::isLocation(), resolve(), and llvm::DIBasicType::Verify().
Referenced by emitDebugLocEntry(), and emitLocPieces().
void DwarfDebug::emitDIE (DIE & Die)
Recursively Emits a debug information entry.
Definition at line 1399 of file DwarfDebug.cpp.
References llvm::dwarf::AccessibilityString(), assert(), llvm::dwarf::AttributeString(), llvm::dwarf::DW_AT_accessibility, llvm::DIE::getAbbrev(), llvm::DIE::getChildren(), llvm::DIEAbbrev::getData(), llvm::DIEAbbrev::getNumber(), llvm::DIE::getOffset(), llvm::DIE::getSize(), llvm::DIEAbbrev::getTag(), llvm::DIE::getValues(), llvm::DIEAbbrev::hasChildren(), N, llvm::SmallVectorTemplateCommon< T >::size(), llvm::dwarf::TagString(), and llvm::Twine::utohexstr().
Referenced by llvm::DwarfFile::emitUnits().
void DwarfDebug::emitLocPieces (ByteStreamer & Streamer, const DITypeIdentifierMap & Map, ArrayRef< DebugLocEntry::Value > Values)
Emits an optimal (=sorted) sequence of DW_OP_pieces.
Definition at line 1661 of file DwarfDebug.cpp.
References assert(), llvm::ArrayRef< T >::begin(), emitDebugLocValue(), llvm::ArrayRef< T >::end(), llvm::DIExpression::getPieceOffset(), llvm::DIExpression::getPieceSize(), llvm::DIVariable::getSizeInBits(), llvm::DIVariable::isIndirect(), and P.
Referenced by emitDebugLocEntry().
void DwarfDebug::endFunction (const MachineFunction * MF) override virtual
Gather and emit post-function debug information.
Implements llvm::AsmPrinterHandler.
Definition at line 1236 of file DwarfDebug.cpp.
References assert(), llvm::LexicalScopes::empty(), llvm::LexicalScopes::getAbstractScopesList(), llvm::DIVariable::getContext(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::MachineFunction::getFunction(), llvm::LexicalScope::getScopeNode(), llvm::DwarfFile::getScopeVariables(), llvm::DISubprogram::getVariables(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::DIDescriptor::isSubprogram(), llvm::DIDescriptor::isVariable(), and llvm::DIBuilder::LineTablesOnly.
void DwarfDebug::endInstruction () override virtual
Process end of an instruction.
Implements llvm::AsmPrinterHandler.
Definition at line 1063 of file DwarfDebug.cpp.
References assert(), llvm::MCContext::CreateTempSymbol(), llvm::MachineModuleInfo::getContext(), I, and llvm::MachineInstr::isDebugValue().
void DwarfDebug::endModule () override virtual
Emit all Dwarf sections that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 659 of file DwarfDebug.cpp.
References assert(), llvm::AddressPool::emit(), GenerateARangeSection, GenerateGnuPubSections, useDwarfAccelTables(), and useSplitDwarf().
iterator_range<ImportedEntityMap::const_iterator> llvm::DwarfDebug::findImportedEntitiesForScope (const MDNode * Scope) const inline
Definition at line 612 of file DwarfDebug.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::make_range().
Referenced by llvm::DwarfCompileUnit::constructScopeDIE().
AddressPool& llvm::DwarfDebug::getAddressPool () inline
Definition at line 597 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfUnit::addOpAddress(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
const MachineFunction* llvm::DwarfDebug::getCurrentFunction () const inline
Definition at line 607 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
const SmallVectorImpl<DebugLocList>& llvm::DwarfDebug::getDebugLocEntries () const inline
Returns the entries for the .debug_loc section.
Definition at line 558 of file DwarfDebug.h.
Referenced by llvm::DIELocList::EmitValue().
MCSymbol* llvm::DwarfDebug::getDebugLocSym () const inline
Returns the section symbol for the .debug_loc section.
Definition at line 544 of file DwarfDebug.h.
Referenced by llvm::DIELocList::EmitValue().
MCSymbol* llvm::DwarfDebug::getDebugStrSym () const inline
Returns the section symbol for the .debug_str section.
Definition at line 547 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::addLocalString().
unsigned llvm::DwarfDebug::getDwarfVersion () const inline
Returns the Dwarf Version.
Definition at line 541 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addFlag(), llvm::DwarfCompileUnit::addLocationList(), llvm::DwarfCompileUnit::addSectionDelta(), llvm::DwarfCompileUnit::addSectionLabel(), llvm::DwarfUnit::addSectionOffset(), llvm::DwarfCompileUnit::attachLowHighPC(), llvm::DwarfUnit::emitHeader(), llvm::DwarfExpression::getDwarfVersion(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), and llvm::DIEEntry::getRefAddrSize().
const MCSymbol* llvm::DwarfDebug::getFunctionBeginSym () const inline
Definition at line 608 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
const MCSymbol* llvm::DwarfDebug::getFunctionEndSym () const inline
Definition at line 609 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
MCSymbol * DwarfDebug::getLabelAfterInsn (const MachineInstr * MI)
Return Label immediately following the instruction.
Definition at line 1012 of file DwarfDebug.cpp.
Referenced by llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), and isLexicalScopeDIENull().
MCSymbol * DwarfDebug::getLabelBeforeInsn (const MachineInstr * MI)
Return Label preceding the instruction.
Definition at line 1005 of file DwarfDebug.cpp.
References assert().
Referenced by llvm::DwarfCompileUnit::attachRangesOrLowHighPC().
unsigned llvm::DwarfDebug::getNextRangeNumber () inline
Definition at line 633 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addScopeRangeList().
const DwarfCompileUnit* llvm::DwarfDebug::getPrevCU () const inline
Returns the previous CU that was being updated.
Definition at line 553 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addRange().
SmallPtrSet<const MDNode *, 16>& llvm::DwarfDebug::getProcessedSPNodes () inline
Definition at line 637 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::constructSubprogramScopeDIE().
MCSymbol* llvm::DwarfDebug::getRangeSectionSym () const inline
Returns the section symbol for the .debug_ranges section.
Definition at line 550 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addScopeRangeList().
const DITypeIdentifierMap& llvm::DwarfDebug::getTypeIdentifierMap () const inline
Return the TypeIdentifierMap.
Definition at line 583 of file DwarfDebug.h.
Referenced by llvm::DbgVariable::getType(), and llvm::DbgVariable::isBlockByrefVariable().
bool DwarfDebug::isLexicalScopeDIENull (LexicalScope * Scope)
A helper function to check whether the DIE for a given Scope is going to be null.
Check whether we should create a DIE for the given Scope, return true if we don't create a DIE (the corresponding DIE is null).
Definition at line 316 of file DwarfDebug.cpp.
References llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), getLabelAfterInsn(), llvm::LexicalScope::getRanges(), llvm::LexicalScope::isAbstractScope(), Ranges, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::DwarfCompileUnit::constructLexicalScopeDIE(), and llvm::DwarfCompileUnit::constructScopeDIE().
bool DwarfDebug::isSubprogramContext (const MDNode * Context)
isSubprogramContext - Return true if Context is either a subprogram or another context nested inside a subprogram.
Definition at line 303 of file DwarfDebug.cpp.
References llvm::DIDescriptor::isSubprogram(), llvm::DIDescriptor::isType(), and resolve().
DwarfCompileUnit* llvm::DwarfDebug::lookupUnit (const DIE * CU) const inline
Find the DwarfCompileUnit for the given CU Die.
Definition at line 588 of file DwarfDebug.h.
Referenced by llvm::DIEEntry::EmitValue().
template<typename T > T llvm::DwarfDebug::resolve (DIRef< T > Ref) const inline
Find the MDNode for the given reference.
Definition at line 578 of file DwarfDebug.h.
References llvm::DIRef< T >::resolve().
Referenced by beginModule(), emitDebugLocValue(), getBaseTypeSize(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), isSubprogramContext(), isUnsignedDIType(), and llvm::DwarfUnit::resolve().
void llvm::DwarfDebug::setPrevCU (const DwarfCompileUnit * PrevCU) inline
Definition at line 554 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addRange().
void llvm::DwarfDebug::setSymbolSize (const MCSymbol * Sym, uint64_t Size) inline override virtual
For symbols that have a size designated (e.g. common symbols), this tracks that size.
Implements llvm::AsmPrinterHandler.
Definition at line 523 of file DwarfDebug.h.
bool llvm::DwarfDebug::useDwarfAccelTables () const inline
Returns whether or not to emit tables that dwarf consumers can use to accelerate lookup.
Definition at line 534 of file DwarfDebug.h.
Referenced by addAccelName(), addAccelNamespace(), addAccelObjC(), addAccelType(), and endModule().
bool llvm::DwarfDebug::useSplitDwarf () const inline
Returns whether or not to change the current debug info for the split dwarf proposal support.
Definition at line 538 of file DwarfDebug.h.
Referenced by addDwarfTypeUnitType(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfUnit::addOpAddress(), llvm::DIEEntry::EmitValue(), llvm::DIELocList::EmitValue(), endModule(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
The documentation for this class was generated from the following files:
DwarfDebug.h
DwarfDebug.cpp