LLVM: llvm::X86MCAsmInfoDarwin Class Reference
LLVM API Documentation
llvm::X86MCAsmInfoDarwin Class Reference
#include <X86MCAsmInfo.h>
Public Member Functions
X86MCAsmInfoDarwin (const Triple &Triple)
Public Member Functions inherited from llvm::MCAsmInfoDarwin
MCAsmInfoDarwin ()
bool isSectionAtomizableBySymbols (const MCSection &Section) const override
True if the section is atomized using the symbols in it. This is false if the section is not atomized at all (most ELF sections) or if it is atomized based on its contents (MachO' __TEXT,__cstring for example).
Public Member Functions inherited from llvm::MCAsmInfo
MCAsmInfo ()
virtual ~MCAsmInfo ()
unsigned getPointerSize () const
Get the pointer size in bytes.
unsigned getCalleeSaveStackSlotSize () const
bool isLittleEndian () const
True if the target is little endian.
bool isStackGrowthDirectionUp () const
True if target stack grow up.
bool hasSubsectionsViaSymbols () const
const char * getData8bitsDirective () const
const char * getData16bitsDirective () const
const char * getData32bitsDirective () const
const char * getData64bitsDirective () const
const char * getGPRel64Directive () const
const char * getGPRel32Directive () const
virtual const MCSection * getNonexecutableStackSection (MCContext &Ctx) const
virtual const MCExpr * getExprForPersonalitySymbol (const MCSymbol *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual const MCExpr * getExprForFDESymbol (const MCSymbol *Sym, unsigned Encoding, MCStreamer &Streamer) const
bool usesSunStyleELFSectionSwitchSyntax () const
bool usesELFSectionDirectiveForBSS () const
bool needsDwarfSectionOffsetDirective () const
bool hasMachoZeroFillDirective () const
bool hasMachoTBSSDirective () const
bool hasStaticCtorDtorReferenceInStaticMode () const
unsigned getMaxInstLength () const
unsigned getMinInstAlignment () const
bool getDollarIsPC () const
const char * getSeparatorString () const
unsigned getCommentColumn () const
const char * getCommentString () const
const char * getLabelSuffix () const
bool useAssignmentForEHBegin () const
const char * getPrivateGlobalPrefix () const
const char * getPrivateLabelPrefix () const
bool hasLinkerPrivateGlobalPrefix () const
const char * getLinkerPrivateGlobalPrefix () const
const char * getInlineAsmStart () const
const char * getInlineAsmEnd () const
const char * getCode16Directive () const
const char * getCode32Directive () const
const char * getCode64Directive () const
unsigned getAssemblerDialect () const
bool doesAllowAtInName () const
bool doesSupportDataRegionDirectives () const
const char * getZeroDirective () const
const char * getAsciiDirective () const
const char * getAscizDirective () const
bool getAlignmentIsInBytes () const
unsigned getTextAlignFillValue () const
const char * getGlobalDirective () const
bool doesSetDirectiveSuppressesReloc () const
bool hasAggressiveSymbolFolding () const
bool getCOMMDirectiveAlignmentIsInBytes () const
LCOMM::LCOMMType getLCOMMDirectiveAlignmentType () const
bool hasDotTypeDotSizeDirective () const
bool hasSingleParameterDotFile () const
bool hasIdentDirective () const
bool hasNoDeadStrip () const
const char * getWeakDirective () const
const char * getWeakRefDirective () const
bool hasWeakDefDirective () const
bool hasWeakDefCanBeHiddenDirective () const
bool hasLinkOnceDirective () const
MCSymbolAttr getHiddenVisibilityAttr () const
MCSymbolAttr getHiddenDeclarationVisibilityAttr () const
MCSymbolAttr getProtectedVisibilityAttr () const
bool doesSupportDebugInformation () const
bool doesSupportExceptionHandling () const
ExceptionHandling getExceptionHandlingType () const
WinEH::EncodingType getWinEHEncodingType () const
bool usesItaniumLSDAForExceptions () const
bool usesWindowsCFI () const
bool doesDwarfUseRelocationsAcrossSections () const
bool doDwarfFDESymbolsUseAbsDiff () const
bool useDwarfRegNumForCFI () const
bool useParensForSymbolVariant () const
void addInitialFrameState (const MCCFIInstruction &Inst)
const std::vector
< MCCFIInstruction > & getInitialFrameState () const
bool useIntegratedAssembler () const
Return true if assembly (inline or otherwise) should be parsed.
virtual void setUseIntegratedAssembler (bool Value)
Set whether assembly (inline or otherwise) should be parsed.
bool compressDebugSections () const
void setCompressDebugSections (bool CompressDebugSections)
Additional Inherited Members
Protected Attributes inherited from llvm::MCAsmInfo
unsigned PointerSize
Pointer size in bytes. Default is 4.
unsigned CalleeSaveStackSlotSize
bool IsLittleEndian
True if target is little endian. Default is true.
bool StackGrowsUp
True if target stack grow up. Default is false.
bool HasSubsectionsViaSymbols
bool HasMachoZeroFillDirective
bool HasMachoTBSSDirective
bool HasStaticCtorDtorReferenceInStaticMode
unsigned MaxInstLength
unsigned MinInstAlignment
bool DollarIsPC
const char * SeparatorString
const char * CommentString
const char * LabelSuffix
This is appended to emitted labels. Defaults to ":".
bool UseAssignmentForEHBegin
const char * PrivateGlobalPrefix
const char * PrivateLabelPrefix
const char * LinkerPrivateGlobalPrefix
const char * InlineAsmStart
const char * InlineAsmEnd
const char * Code16Directive
const char * Code32Directive
const char * Code64Directive
unsigned AssemblerDialect
Which dialect of an assembler variant to use. Defaults to 0.
bool AllowAtInName
bool UseDataRegionDirectives
const char * ZeroDirective
const char * AsciiDirective
const char * AscizDirective
const char * Data8bitsDirective
const char * Data16bitsDirective
const char * Data32bitsDirective
const char * Data64bitsDirective
const char * GPRel64Directive
const char * GPRel32Directive
bool SunStyleELFSectionSwitchSyntax
bool UsesELFSectionDirectiveForBSS
bool NeedsDwarfSectionOffsetDirective
bool AlignmentIsInBytes
unsigned TextAlignFillValue
const char * GlobalDirective
bool SetDirectiveSuppressesReloc
bool HasAggressiveSymbolFolding
instead of
bool COMMDirectiveAlignmentIsInBytes
LCOMM::LCOMMType LCOMMDirectiveAlignmentType
bool HasDotTypeDotSizeDirective
bool HasSingleParameterDotFile
bool HasIdentDirective
bool HasNoDeadStrip
const char * WeakDirective
Used to declare a global as being a weak symbol. Defaults to ".weak".
const char * WeakRefDirective
bool HasWeakDefDirective
bool HasWeakDefCanBeHiddenDirective
bool HasLinkOnceDirective
MCSymbolAttr HiddenVisibilityAttr
MCSymbolAttr HiddenDeclarationVisibilityAttr
MCSymbolAttr ProtectedVisibilityAttr
bool SupportsDebugInformation
ExceptionHandling ExceptionsType
Exception handling format for the target. Defaults to None.
WinEH::EncodingType WinEHEncodingType
Windows exception handling data (.pdata) encoding. Defaults to Invalid.
bool DwarfUsesRelocationsAcrossSections
bool DwarfFDESymbolsUseAbsDiff
bool DwarfRegNumForCFI
bool UseParensForSymbolVariant
std::vector< MCCFIInstruction > InitialFrameState
bool UseIntegratedAssembler
bool CompressDebugSections
Compress DWARF debug sections. Defaults to false.
Detailed Description
Definition at line 25 of file X86MCAsmInfo.h.
Constructor & Destructor Documentation
X86MCAsmInfoDarwin::X86MCAsmInfoDarwin (const Triple & Triple) explicit
Definition at line 44 of file X86MCAsmInfo.cpp.
References AsmWriterFlavor, llvm::MCAsmInfo::AssemblerDialect, llvm::MCAsmInfo::CalleeSaveStackSlotSize, llvm::MCAsmInfo::CommentString, llvm::MCAsmInfo::Data64bitsDirective, llvm::DwarfCFI, llvm::MCAsmInfo::DwarfFDESymbolsUseAbsDiff, llvm::MCAsmInfo::ExceptionsType, llvm::Triple::getArch(), llvm::MCAsmInfo::HasWeakDefCanBeHiddenDirective, is64Bit(), llvm::Triple::isMacOSX(), llvm::Triple::isMacOSXVersionLT(), MarkedJTDataRegions, llvm::MCAsmInfo::PointerSize, llvm::MCAsmInfo::SupportsDebugInformation, llvm::MCAsmInfo::TextAlignFillValue, llvm::MCAsmInfo::UseDataRegionDirectives, llvm::MCAsmInfo::UseIntegratedAssembler, and llvm::Triple::x86_64.
The documentation for this class was generated from the following files:
X86MCAsmInfo.h
X86MCAsmInfo.cpp