LLVM: llvm::OverflowingBinaryOperator Class Reference
LLVM API Documentation
llvm::OverflowingBinaryOperator Class Reference
#include <Operator.h>
Public Types
enum { NoUnsignedWrap = (1 << 0), NoSignedWrap = (1 << 1) }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range
< op_iterator > op_range
typedef iterator_range
< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MetadataAsValueVal, InlineAsmVal, InstructionVal,
ConstantFirstVal = FunctionVal, ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl
< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl
< const User > const_user_iterator
Public Member Functions
bool hasNoUnsignedWrap () const
bool hasNoSignedWrap () const
Public Member Functions inherited from llvm::Operator
unsigned getOpcode () const
Return the opcode for this Instruction or ConstantExpr.
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range
< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range
< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Static Public Member Functions
static bool classof (const Instruction *I)
static bool classof (const ConstantExpr *CE)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Operator
static unsigned getOpcode (const Value *V)
static bool classof (const Instruction *)
static bool classof (const ConstantExpr *)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class BinaryOperator
class ConstantExpr
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Member Functions inherited from llvm::Operator
~Operator ()
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
Utility class for integer arithmetic operators which may exhibit overflow - Add, Sub, and Mul. It does not include SDiv, despite that operator having the potential for overflow.
Definition at line 75 of file Operator.h.
Member Enumeration Documentation
anonymous enum
Enumerator
NoUnsignedWrap
NoSignedWrap
Definition at line 77 of file Operator.h.
Member Function Documentation
static bool llvm::OverflowingBinaryOperator::classof (const Instruction * I) inline static
Definition at line 107 of file Operator.h.
References llvm::Add, llvm::Instruction::getOpcode(), and llvm::Sub.
Referenced by classof().
static bool llvm::OverflowingBinaryOperator::classof (const ConstantExpr * CE) inline static
Definition at line 113 of file Operator.h.
References llvm::Add, llvm::ConstantExpr::getOpcode(), and llvm::Sub.
static bool llvm::OverflowingBinaryOperator::classof (const Value * V) inline static
Definition at line 119 of file Operator.h.
References classof().
bool llvm::OverflowingBinaryOperator::hasNoSignedWrap () const inline
Test whether this operation is known to never undergo signed overflow, aka the nsw property.
Definition at line 103 of file Operator.h.
References NoSignedWrap, and llvm::Value::SubclassOptionalData.
Referenced by DecomposeSimpleLinearExpr(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), MaintainNoSignedWrap(), and SimplifyDiv().
bool llvm::OverflowingBinaryOperator::hasNoUnsignedWrap () const inline
Test whether this operation is known to never undergo unsigned overflow, aka the nuw property.
Definition at line 97 of file Operator.h.
References NoUnsignedWrap, and llvm::Value::SubclassOptionalData.
Referenced by DecomposeSimpleLinearExpr(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), and SimplifyDiv().
Friends And Related Function Documentation
friend class BinaryOperator friend
Definition at line 83 of file Operator.h.
friend class ConstantExpr friend
Definition at line 84 of file Operator.h.
The documentation for this class was generated from the following file:
Operator.h