LLVM: llvm::RGPassManager Class Reference
LLVM API Documentation
llvm::RGPassManager Class Reference
The pass manager to schedule RegionPasses.
#include <RegionPass.h>
Public Member Functions
RGPassManager ()
bool runOnFunction (Function &F) override
Execute all of the passes scheduled for execution.
void getAnalysisUsage (AnalysisUsage &Info) const override
Pass Manager itself does not invalidate any analysis info.
const char * getPassName () const override
PMDataManager * getAsPMDataManager () override
Pass * getAsPass () override
void dumpPassStructure (unsigned Offset) override
Print passes managed by this manager.
Pass * getContainedPass (unsigned N)
Get passes contained by this manager.
PassManagerType getPassManagerType () const override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual void verifyAnalysis () const
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Member Functions inherited from llvm::PMDataManager
PMDataManager ()
virtual ~PMDataManager ()
void recordAvailableAnalysis (Pass *P)
Augment AvailableAnalysis by adding analysis made available by pass P.
void verifyPreservedAnalysis (Pass *P)
verifyPreservedAnalysis – Verify analysis presreved by pass P.
void removeNotPreservedAnalysis (Pass *P)
Remove Analysis that is not preserved by the pass.
void removeDeadPasses (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove dead passes used by P.
void freePass (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove P.
void add (Pass *P, bool ProcessAnalysis=true)
virtual void addLowerLevelRequiredPass (Pass *P, Pass *RequiredPass)
virtual Pass * getOnTheFlyPass (Pass *P, AnalysisID PI, Function &F)
void initializeAnalysisInfo ()
Initialize available analysis information.
bool preserveHigherLevelAnalysis (Pass *P)
void collectRequiredAnalysis (SmallVectorImpl< Pass * > &RequiredPasses, SmallVectorImpl< AnalysisID > &ReqPassNotAvailable, Pass *P)
void initializeAnalysisImpl (Pass *P)
Pass * findAnalysisPass (AnalysisID AID, bool Direction)
PMTopLevelManager * getTopLevelManager ()
void setTopLevelManager (PMTopLevelManager *T)
unsigned getDepth () const
void setDepth (unsigned newDepth)
void dumpLastUses (Pass *P, unsigned Offset) const
void dumpPassArguments () const
void dumpPassInfo (Pass *P, enum PassDebuggingString S1, enum PassDebuggingString S2, StringRef Msg)
void dumpRequiredSet (const Pass *P) const
void dumpPreservedSet (const Pass *P) const
unsigned getNumContainedPasses () const
DenseMap< AnalysisID, Pass * > * getAvailableAnalysis ()
void populateInheritedAnalysis (PMStack &PMS)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Protected Member Functions inherited from llvm::PMDataManager
bool isPassDebuggingExecutionsOrMore () const
Protected Attributes inherited from llvm::PMDataManager
PMTopLevelManager * TPM
SmallVector< Pass *, 16 > PassVector
DenseMap< AnalysisID, Pass * > * InheritedAnalysis [PMT_Last]
Detailed Description
The pass manager to schedule RegionPasses.
Definition at line 84 of file RegionPass.h.
Constructor & Destructor Documentation
RGPassManager::RGPassManager () explicit
Definition at line 30 of file RegionPass.cpp.
Member Function Documentation
void RGPassManager::dumpPassStructure (unsigned Offset) override virtual
Print passes managed by this manager.
Reimplemented from llvm::Pass.
Definition at line 169 of file RegionPass.cpp.
References llvm::PMDataManager::dumpLastUses(), llvm::Pass::dumpPassStructure(), llvm::errs(), getContainedPass(), llvm::PMDataManager::getNumContainedPasses(), llvm::raw_ostream::indent(), and P.
void RGPassManager::getAnalysisUsage (AnalysisUsage & Info) const override virtual
Pass Manager itself does not invalidate any analysis info.
Pass Manager itself does not invalidate any analysis info. RGPassManager needs RegionInfo.
Reimplemented from llvm::Pass.
Definition at line 46 of file RegionPass.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::AnalysisUsage::setPreservesAll().
Pass* llvm::RGPassManager::getAsPass () inline override virtual
Implements llvm::PMDataManager.
Definition at line 109 of file RegionPass.h.
PMDataManager* llvm::RGPassManager::getAsPMDataManager () inline override virtual
Reimplemented from llvm::Pass.
Definition at line 108 of file RegionPass.h.
Pass* llvm::RGPassManager::getContainedPass (unsigned N) inline
Get passes contained by this manager.
Definition at line 115 of file RegionPass.h.
References assert(), N, and llvm::PMDataManager::PassVector.
Referenced by dumpPassStructure(), and runOnFunction().
PassManagerType llvm::RGPassManager::getPassManagerType () const inline override virtual
Reimplemented from llvm::PMDataManager.
Definition at line 121 of file RegionPass.h.
References llvm::PMT_RegionPassManager.
const char* llvm::RGPassManager::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 104 of file RegionPass.h.
bool RGPassManager::runOnFunction (Function & F) override virtual
Execute all of the passes scheduled for execution.
Returns
True if any of the passes modifies the function.
run - Execute all of the passes scheduled for execution. Keep track of whether any of the passes modifies the function, and if so, return true.
Implements llvm::FunctionPass.
Definition at line 53 of file RegionPass.cpp.
References llvm::PMTopLevelManager::activeStack, addRegionIntoQueue(), llvm::RegionInfoBase< RegionTr >::clearNodeCache(), llvm::dbgs(), DEBUG, llvm::RegionPass::doFinalization(), llvm::RegionPass::doInitialization(), llvm::RegionInfoBase< RegionTr >::dump(), llvm::PMDataManager::dumpPassInfo(), llvm::PMDataManager::dumpPreservedSet(), llvm::PMDataManager::dumpRequiredSet(), llvm::EXECUTION_MSG, llvm::PMDataManager::freePass(), getContainedPass(), llvm::RegionBase< RegionTr >::getEntry(), llvm::Value::getName(), llvm::RegionBase< RegionTr >::getNameStr(), llvm::PMDataManager::getNumContainedPasses(), llvm::getPassTimer(), llvm::RegionInfoBase< RegionTr >::getTopLevelRegion(), I, llvm::PMDataManager::initializeAnalysisImpl(), llvm::MODIFICATION_MSG, llvm::ON_REGION_MSG, P, llvm::PMDataManager::populateInheritedAnalysis(), llvm::PMDataManager::recordAvailableAnalysis(), llvm::PMDataManager::removeDeadPasses(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::NVPTX::PTXCvtMode::RP, llvm::RegionPass::runOnRegion(), llvm::PMDataManager::TPM, llvm::PMDataManager::verifyPreservedAnalysis(), llvm::RegionBase< RegionTr >::verifyRegion(), and llvm::X.
Member Data Documentation
char RGPassManager::ID = 0 static
Definition at line 92 of file RegionPass.h.
The documentation for this class was generated from the following files:
RegionPass.h
RegionPass.cpp