LLVM: llvm::ARMConstantPoolMBB Class Reference
LLVM API Documentation
llvm::ARMConstantPoolMBB Class Reference
#include <ARMConstantPoolValue.h>
Public Member Functions
const MachineBasicBlock * getMBB () const
int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool hasSameValue (ARMConstantPoolValue *ACPV) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const ARMConstantPoolMBB *A) const
Public Member Functions inherited from llvm::ARMConstantPoolValue
virtual ~ARMConstantPoolValue ()
ARMCP::ARMCPModifier getModifier () const
const char * getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
unsigned getRelocationInfo () const override
bool equals (const ARMConstantPoolValue *A) const
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()
Type * getType () const
Static Public Member Functions
static ARMConstantPoolMBB * Create (LLVMContext &C, const MachineBasicBlock *mbb, unsigned ID, unsigned char PCAdj)
static bool classof (const ARMConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::ARMConstantPoolValue
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, unsigned Alignment)
Detailed Description
ARMConstantPoolMBB - ARM-specific constantpool value of a machine basic block.
Definition at line 223 of file ARMConstantPoolValue.h.
Member Function Documentation
void ARMConstantPoolMBB::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 254 of file ARMConstantPoolValue.cpp.
References llvm::FoldingSetNodeID::AddPointer(), and llvm::ARMConstantPoolValue::addSelectionDAGCSEId().
static bool llvm::ARMConstantPoolMBB::classof (const ARMConstantPoolValue * ACPV) inline static
Definition at line 248 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::isMachineBasicBlock().
ARMConstantPoolMBB * ARMConstantPoolMBB::Create (LLVMContext & C, const MachineBasicBlock * mbb, unsigned ID, unsigned char PCAdj) static
Definition at line 236 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::no_modifier.
bool llvm::ARMConstantPoolMBB::equals (const ARMConstantPoolMBB * A) const inline
Definition at line 252 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::equals().
int ARMConstantPoolMBB::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) override virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 243 of file ARMConstantPoolValue.cpp.
const MachineBasicBlock* llvm::ARMConstantPoolMBB::getMBB () const inline
Definition at line 235 of file ARMConstantPoolValue.h.
bool ARMConstantPoolMBB::hasSameValue (ARMConstantPoolValue * ACPV) override virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 248 of file ARMConstantPoolValue.cpp.
References llvm::dyn_cast(), and llvm::ARMConstantPoolValue::hasSameValue().
void ARMConstantPoolMBB::print (raw_ostream & O) const override virtual
print - Implement operator<<
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 259 of file ARMConstantPoolValue.cpp.
References llvm::MachineBasicBlock::getNumber(), and llvm::ARMConstantPoolValue::print().
The documentation for this class was generated from the following files:
ARMConstantPoolValue.h
ARMConstantPoolValue.cpp