LLVM: llvm::NamedMDNode Class Reference
LLVM API Documentation
llvm::NamedMDNode Class Reference
A tuple of MDNodes.
#include <Metadata.h>
Public Types
typedef op_iterator_impl
< MDNode *, MDNode > op_iterator
typedef op_iterator_impl
< const MDNode *, MDNode > const_op_iterator
Public Member Functions
void eraseFromParent ()
Drop all references and remove the node from parent module.
void dropAllReferences ()
Remove all uses and clear node vector.
~NamedMDNode ()
Module * getParent ()
Get the module that holds this named metadata collection.
const Module * getParent () const
MDNode * getOperand (unsigned i) const
unsigned getNumOperands () const
void addOperand (MDNode *M)
void setOperand (unsigned I, MDNode *New)
StringRef getName () const
void print (raw_ostream &ROS) const
void dump () const
op_iterator op_begin ()
op_iterator op_end ()
const_op_iterator op_begin () const
const_op_iterator op_end () const
iterator_range< op_iterator > operands ()
iterator_range< const_op_iterator > operands () const
Public Member Functions inherited from llvm::ilist_node< NamedMDNode >
NamedMDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
const NamedMDNode * getPrevNode () const
Get the previous node, or 0 for the list head.
NamedMDNode * getNextNode ()
Get the next node, or 0 for the list tail.
const NamedMDNode * getNextNode () const
Get the next node, or 0 for the list tail.
Friends
class SymbolTableListTraits< NamedMDNode, Module >
struct ilist_traits< NamedMDNode >
class LLVMContextImpl
class Module
Additional Inherited Members
Protected Member Functions inherited from llvm::ilist_node< NamedMDNode >
ilist_node ()
Detailed Description
A tuple of MDNodes.
Despite its name, a NamedMDNode isn't itself an MDNode. NamedMDNodes belong to modules, have names, and contain lists of MDNodes.
TODO: Inherit from Metadata.
Definition at line 919 of file Metadata.h.
Member Typedef Documentation
typedef op_iterator_impl<const MDNode *, MDNode> llvm::NamedMDNode::const_op_iterator
Definition at line 998 of file Metadata.h.
typedef op_iterator_impl<MDNode *, MDNode> llvm::NamedMDNode::op_iterator
Definition at line 994 of file Metadata.h.
Constructor & Destructor Documentation
NamedMDNode::~NamedMDNode ()
Definition at line 983 of file Metadata.cpp.
References dropAllReferences(), and getNMDOps().
Member Function Documentation
void NamedMDNode::addOperand (MDNode * M)
Definition at line 998 of file Metadata.cpp.
References getNMDOps().
Referenced by llvm::Module::addModuleFlag(), llvm::CloneModule(), llvm::DIBuilder::createCompileUnit(), and LLVMAddNamedMetadataOperand().
void NamedMDNode::dropAllReferences ()
Remove all uses and clear node vector.
Definition at line 1009 of file Metadata.cpp.
References getNMDOps().
Referenced by ~NamedMDNode().
void NamedMDNode::dump () const
Definition at line 2671 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
void NamedMDNode::eraseFromParent ()
Drop all references and remove the node from parent module.
Definition at line 1005 of file Metadata.cpp.
References llvm::Module::eraseNamedMetadata(), and getParent().
Referenced by llvm::StripDebugInfo().
StringRef NamedMDNode::getName () const
Definition at line 1013 of file Metadata.cpp.
Referenced by llvm::CloneModule(), llvm::Module::eraseNamedMetadata(), llvm::AssemblyWriter::printNamedMDNode(), and llvm::StripDebugInfo().
unsigned NamedMDNode::getNumOperands () const
Definition at line 988 of file Metadata.cpp.
References getNMDOps().
Referenced by llvm::DwarfDebug::beginModule(), cacheAnnotationFromMD(), llvm::CloneModule(), llvm::generateDITypeIdentifierMap(), getOperand(), LLVMGetNamedMetadataOperands(), op_end(), llvm::AssemblyWriter::printNamedMDNode(), llvm::TypeFinder::run(), and setOperand().
MDNode * NamedMDNode::getOperand (unsigned i) const
Definition at line 992 of file Metadata.cpp.
References assert(), getNMDOps(), getNumOperands(), and N.
Referenced by cacheAnnotationFromMD(), llvm::CloneModule(), llvm::generateDITypeIdentifierMap(), LLVMGetNamedMetadataOperands(), llvm::AssemblyWriter::printNamedMDNode(), and llvm::TypeFinder::run().
Module* llvm::NamedMDNode::getParent () inline
Get the module that holds this named metadata collection.
Definition at line 980 of file Metadata.h.
Referenced by eraseFromParent(), and print().
const Module* llvm::NamedMDNode::getParent () const inline
Definition at line 981 of file Metadata.h.
op_iterator llvm::NamedMDNode::op_begin () inline
Definition at line 995 of file Metadata.h.
Referenced by operands().
const_op_iterator llvm::NamedMDNode::op_begin () const inline
Definition at line 999 of file Metadata.h.
op_iterator llvm::NamedMDNode::op_end () inline
Definition at line 996 of file Metadata.h.
References getNumOperands().
Referenced by operands().
const_op_iterator llvm::NamedMDNode::op_end () const inline
Definition at line 1000 of file Metadata.h.
References getNumOperands().
iterator_range<op_iterator> llvm::NamedMDNode::operands () inline
Definition at line 1002 of file Metadata.h.
References op_begin(), and op_end().
Referenced by llvm::DwarfDebug::beginModule(), llvm::Module::getModuleFlagsMetadata(), and llvm::makeSubprogramMap().
iterator_range<const_op_iterator> llvm::NamedMDNode::operands () const inline
Definition at line 1005 of file Metadata.h.
References op_begin(), and op_end().
void NamedMDNode::print (raw_ostream & ROS) const
Definition at line 2531 of file AsmWriter.cpp.
References getParent(), and llvm::AssemblyWriter::printNamedMDNode().
Referenced by dump().
void NamedMDNode::setOperand (unsigned I, MDNode * New)
Definition at line 1000 of file Metadata.cpp.
References assert(), getNMDOps(), getNumOperands(), and I.
Friends And Related Function Documentation
friend struct ilist_traits< NamedMDNode > friend
Definition at line 921 of file Metadata.h.
friend class LLVMContextImpl friend
Definition at line 922 of file Metadata.h.
friend class Module friend
Definition at line 923 of file Metadata.h.
friend class SymbolTableListTraits< NamedMDNode, Module > friend
Definition at line 920 of file Metadata.h.
The documentation for this class was generated from the following files:
Metadata.h
AsmWriter.cpp
Metadata.cpp