LLVM: llvm::object::SymbolRef Class Reference
LLVM API Documentation
llvm::object::SymbolRef Class Reference
#include <ObjectFile.h>
Public Types
enum Type {
ST_Unknown, ST_Data, ST_Debug, ST_File,
ST_Function, ST_Other
}
Public Types inherited from llvm::object::BasicSymbolRef
enum Flags : unsigned {
SF_None = 0, SF_Undefined = 1U << 0, SF_Global = 1U << 1, SF_Weak = 1U << 2,
SF_Absolute = 1U << 3, SF_Common = 1U << 4, SF_Indirect = 1U << 5, SF_FormatSpecific = 1U << 6,
SF_Thumb = 1U << 7
}
Public Member Functions
SymbolRef ()
SymbolRef (DataRefImpl SymbolP, const ObjectFile *Owner)
std::error_code getName (StringRef &Result) const
std::error_code getAddress (uint64_t &Result) const
std::error_code getAlignment (uint32_t &Result) const
Get the alignment of this symbol as the actual value (not log 2).
std::error_code getSize (uint64_t &Result) const
std::error_code getType (SymbolRef::Type &Result) const
std::error_code getOther (uint8_t &Result) const
std::error_code getSection (section_iterator &Result) const
Get section this symbol is defined in reference to. Result is end_sections() if it is undefined or is an absolute symbol.
const ObjectFile * getObject () const
Public Member Functions inherited from llvm::object::BasicSymbolRef
BasicSymbolRef ()
BasicSymbolRef (DataRefImpl SymbolP, const SymbolicFile *Owner)
bool operator== (const BasicSymbolRef &Other) const
bool operator< (const BasicSymbolRef &Other) const
void moveNext ()
std::error_code printName (raw_ostream &OS) const
uint32_t getFlags () const
Get symbol flags (bitwise OR of SymbolRef::Flags)
DataRefImpl getRawDataRefImpl () const
const SymbolicFile * getObject () const
Friends
class SectionRef
Detailed Description
SymbolRef - This is a value type class that represents a single symbol in the list of symbols in the object file.
Definition at line 126 of file ObjectFile.h.
Member Enumeration Documentation
enum llvm::object::SymbolRef::Type
Enumerator
ST_Unknown
ST_Data
ST_Debug
ST_File
ST_Function
ST_Other
Definition at line 132 of file ObjectFile.h.
Constructor & Destructor Documentation
llvm::object::SymbolRef::SymbolRef () inline
Definition at line 130 of file ObjectFile.h.
llvm::object::SymbolRef::SymbolRef (DataRefImpl SymbolP, const ObjectFile * Owner) inline
Definition at line 324 of file ObjectFile.h.
Member Function Documentation
std::error_code llvm::object::SymbolRef::getAddress (uint64_t & Result) const inline
Returns the symbol virtual address (i.e. address at which it will be mapped).
Definition at line 331 of file ObjectFile.h.
References getObject(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::ObjectFile::getSymbolAddress().
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory(), and llvm::getOffset().
std::error_code llvm::object::SymbolRef::getAlignment (uint32_t & Result) const inline
Get the alignment of this symbol as the actual value (not log 2).
Definition at line 335 of file ObjectFile.h.
References getObject(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::ObjectFile::getSymbolAlignment().
std::error_code llvm::object::SymbolRef::getName (StringRef & Result) const inline
Definition at line 327 of file ObjectFile.h.
References getObject(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::ObjectFile::getSymbolName().
Referenced by llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), printRelocationTargetName(), and llvm::RuntimeDyldELF::processRelocationRef().
const ObjectFile * llvm::object::SymbolRef::getObject () const inline
Definition at line 355 of file ObjectFile.h.
References llvm::object::BasicSymbolRef::getObject().
Referenced by getAddress(), getAlignment(), getName(), llvm::getOffset(), getOther(), getSection(), getSize(), and getType().
std::error_code llvm::object::SymbolRef::getOther (uint8_t & Result) const inline
Definition at line 351 of file ObjectFile.h.
References getObject(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::ObjectFile::getSymbolOther().
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
std::error_code llvm::object::SymbolRef::getSection (section_iterator & Result) const inline
Get section this symbol is defined in reference to. Result is end_sections() if it is undefined or is an absolute symbol.
Definition at line 343 of file ObjectFile.h.
References getObject(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::ObjectFile::getSymbolSection().
Referenced by llvm::getOffset(), and llvm::RuntimeDyldELF::processRelocationRef().
std::error_code llvm::object::SymbolRef::getSize (uint64_t & Result) const inline
Definition at line 339 of file ObjectFile.h.
References getObject(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::ObjectFile::getSymbolSize().
std::error_code llvm::object::SymbolRef::getType (SymbolRef::Type & Result) const inline
Definition at line 347 of file ObjectFile.h.
References getObject(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::ObjectFile::getSymbolType().
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
Friends And Related Function Documentation
friend class SectionRef friend
Definition at line 127 of file ObjectFile.h.
The documentation for this class was generated from the following file:
ObjectFile.h