LLVM: llvm::SparcInstPrinter Class Reference
LLVM API Documentation
llvm::SparcInstPrinter Class Reference
#include <SparcInstPrinter.h>
Public Member Functions
SparcInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &sti)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
printRegName - Print the assembler register name.
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot) override
bool printSparcAliasInstr (const MCInst *MI, raw_ostream &OS)
bool isV9 () const
void printInstruction (const MCInst *MI, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, raw_ostream &O)
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &O)
void printOperand (const MCInst *MI, int opNum, raw_ostream &OS)
void printMemOperand (const MCInst *MI, int opNum, raw_ostream &OS, const char *Modifier=nullptr)
void printCCOperand (const MCInst *MI, int opNum, raw_ostream &OS)
bool printGetPCX (const MCInst *MI, unsigned OpNo, raw_ostream &OS)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 24 of file SparcInstPrinter.h.
Constructor & Destructor Documentation
llvm::SparcInstPrinter::SparcInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & sti) inline
Definition at line 27 of file SparcInstPrinter.h.
Member Function Documentation
static const char* llvm::SparcInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by llvm::SparcTargetAsmStreamer::emitSparcRegisterIgnore(), llvm::SparcTargetAsmStreamer::emitSparcRegisterScratch(), and printRegName().
bool SparcInstPrinter::isV9 () const
Definition at line 37 of file SparcInstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by printSparcAliasInstr().
bool llvm::SparcInstPrinter::printAliasInstr (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void SparcInstPrinter::printCCOperand (const MCInst * MI, int opNum, raw_ostream & OS)
Definition at line 149 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), and llvm::SPARCCondCodeToString().
void llvm::SparcInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & O)
bool SparcInstPrinter::printGetPCX (const MCInst * MI, unsigned OpNo, raw_ostream & OS)
Definition at line 173 of file SparcInstPrinter.cpp.
References llvm_unreachable.
void SparcInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) override virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 46 of file SparcInstPrinter.cpp.
References printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), and printSparcAliasInstr().
void llvm::SparcInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void SparcInstPrinter::printMemOperand (const MCInst * MI, int opNum, raw_ostream & OS, const char * Modifier = nullptr)
Definition at line 126 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), printOperand(), and llvm::LibFunc::strcmp.
Referenced by printSparcAliasInstr().
void SparcInstPrinter::printOperand (const MCInst * MI, int opNum, raw_ostream & OS)
Definition at line 107 of file SparcInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCExpr::print(), and printRegName().
Referenced by printMemOperand(), and printSparcAliasInstr().
void SparcInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
printRegName - Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 41 of file SparcInstPrinter.cpp.
References getRegisterName(), and llvm::StringRef::lower().
Referenced by printOperand().
bool SparcInstPrinter::printSparcAliasInstr (const MCInst * MI, raw_ostream & OS)
Definition at line 54 of file SparcInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), isV9(), printMemOperand(), and printOperand().
Referenced by printInst().
The documentation for this class was generated from the following files:
SparcInstPrinter.h
SparcInstPrinter.cpp