LLVM: llvm::Optional< T > Class Template Reference
LLVM API Documentation
llvm::Optional< T > Class Template Reference
#include <Optional.h>
Public Types
typedef T value_type
Public Member Functions
Optional (NoneType)
Optional ()
Optional (const T &y)
Optional (const Optional &O)
Optional (T &&y)
Optional (Optional< T > &&O)
Optional & operator= (T &&y)
Optional & operator= (Optional &&O)
void emplace ()
Create a new object by default-constructing it in place.
template<typename T1 >
void emplace (T1 &&A1)
Create a new object by constructing it in place with the given arguments.
template<typename T1 , typename T2 >
void emplace (T1 &&A1, T2 &&A2)
Create a new object by constructing it in place with the given arguments.
template<typename T1 , typename T2 , typename T3 >
void emplace (T1 &&A1, T2 &&A2, T3 &&A3)
Create a new object by constructing it in place with the given arguments.
template<typename T1 , typename T2 , typename T3 , typename T4 >
void emplace (T1 &&A1, T2 &&A2, T3 &&A3, T4 &&A4)
Create a new object by constructing it in place with the given arguments.
Optional & operator= (const T &y)
Optional & operator= (const Optional &O)
void reset ()
~Optional ()
const T * getPointer () const
T * getPointer ()
const T & getValue () const LLVM_LVALUE_FUNCTION
T & getValue () LLVM_LVALUE_FUNCTION
LLVM_EXPLICIT operator bool () const
bool hasValue () const
const T * operator-> () const
T * operator-> ()
const T & operator* () const LLVM_LVALUE_FUNCTION
T & operator* () LLVM_LVALUE_FUNCTION
template<typename U >
LLVM_CONSTEXPR T getValueOr (U &&value) const LLVM_LVALUE_FUNCTION
Static Public Member Functions
static Optional create (const T *y)
Detailed Description
template<typename T>
class llvm::Optional< T >
Definition at line 29 of file Optional.h.
Member Typedef Documentation
template<typename T> typedef T llvm::Optional< T >::value_type
Definition at line 33 of file Optional.h.
Constructor & Destructor Documentation
template<typename T> llvm::Optional< T >::Optional (NoneType) inline
Definition at line 35 of file Optional.h.
template<typename T> llvm::Optional< T >::Optional () inline explicit
Definition at line 36 of file Optional.h.
Referenced by llvm::Optional< COFF::AuxiliarySectionDefinition >::create().
template<typename T> llvm::Optional< T >::Optional (const T & y) inline
Definition at line 37 of file Optional.h.
template<typename T> llvm::Optional< T >::Optional (const Optional< T > & O) inline
Definition at line 40 of file Optional.h.
template<typename T> llvm::Optional< T >::Optional (T && y) inline
Definition at line 45 of file Optional.h.
template<typename T> llvm::Optional< T >::Optional (Optional< T > && O) inline
Definition at line 48 of file Optional.h.
template<typename T> llvm::Optional< T >::~Optional () inline
Definition at line 162 of file Optional.h.
Member Function Documentation
template<typename T> static Optional llvm::Optional< T >::create (const T * y) inline static
Definition at line 128 of file Optional.h.
template<typename T> void llvm::Optional< T >::emplace () inline
Create a new object by default-constructing it in place.
Definition at line 86 of file Optional.h.
template<typename T> template<typename T1 > void llvm::Optional< T >::emplace (T1 && A1) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 94 of file Optional.h.
template<typename T> template<typename T1 , typename T2 > void llvm::Optional< T >::emplace (T1 && A1, T2 && A2) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 102 of file Optional.h.
template<typename T> template<typename T1 , typename T2 , typename T3 > void llvm::Optional< T >::emplace (T1 && A1, T2 && A2, T3 && A3) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 110 of file Optional.h.
template<typename T> template<typename T1 , typename T2 , typename T3 , typename T4 > void llvm::Optional< T >::emplace (T1 && A1, T2 && A2, T3 && A3, T4 && A4) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 119 of file Optional.h.
template<typename T> const T* llvm::Optional< T >::getPointer () const inline
Definition at line 166 of file Optional.h.
Referenced by llvm::Optional< COFF::AuxiliarySectionDefinition >::getValue(), llvm::Optional< COFF::AuxiliarySectionDefinition >::operator*(), and llvm::Optional< COFF::AuxiliarySectionDefinition >::operator->().
template<typename T> T* llvm::Optional< T >::getPointer () inline
Definition at line 167 of file Optional.h.
template<typename T> const T& llvm::Optional< T >::getValue () const inline
Definition at line 168 of file Optional.h.
Referenced by llvm::DWARFFormValue::dump(), llvm::sys::Process::FindInEnvPath(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsAddress(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsReference(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsSectionOffset(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsString(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsUnsignedConstant(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getUnsignedRange(), and llvm::Optional< COFF::AuxiliarySectionDefinition >::getValueOr().
template<typename T> T& llvm::Optional< T >::getValue () inline
Definition at line 169 of file Optional.h.
template<typename T> template<typename U > LLVM_CONSTEXPR T llvm::Optional< T >::getValueOr (U && value) const inline
Definition at line 179 of file Optional.h.
template<typename T> bool llvm::Optional< T >::hasValue () const inline
Definition at line 172 of file Optional.h.
Referenced by llvm::DWARFFormValue::dump(), llvm::sys::Process::FindInEnvPath(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsAddress(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsReference(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsSectionOffset(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsString(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsUnsignedConstant(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getUnsignedRange(), and llvm::Optional< COFF::AuxiliarySectionDefinition >::getValueOr().
template<typename T> LLVM_EXPLICIT llvm::Optional< T >::operator bool () const inline
Definition at line 171 of file Optional.h.
template<typename T> const T& llvm::Optional< T >::operator* () const inline
Definition at line 175 of file Optional.h.
template<typename T> T& llvm::Optional< T >::operator* () inline
Definition at line 176 of file Optional.h.
template<typename T> const T* llvm::Optional< T >::operator-> () const inline
Definition at line 173 of file Optional.h.
template<typename T> T* llvm::Optional< T >::operator-> () inline
Definition at line 174 of file Optional.h.
template<typename T> Optional& llvm::Optional< T >::operator= (T && y) inline
Definition at line 54 of file Optional.h.
template<typename T> Optional& llvm::Optional< T >::operator= (Optional< T > && O) inline
Definition at line 63 of file Optional.h.
template<typename T> Optional& llvm::Optional< T >::operator= (const T & y) inline
Definition at line 137 of file Optional.h.
template<typename T> Optional& llvm::Optional< T >::operator= (const Optional< T > & O) inline
Definition at line 147 of file Optional.h.
template<typename T> void llvm::Optional< T >::reset () inline
Definition at line 155 of file Optional.h.
Referenced by llvm::Optional< COFF::AuxiliarySectionDefinition >::emplace(), llvm::Optional< COFF::AuxiliarySectionDefinition >::operator=(), and llvm::Optional< COFF::AuxiliarySectionDefinition >::~Optional().
The documentation for this class was generated from the following file:
Optional.h