LLVM: llvm::FunctionType Class Reference
LLVM API Documentation
llvm::FunctionType Class Reference
#include <DerivedTypes.h>
Public Types
typedef Type::subtype_iterator param_iterator
Public Types inherited from llvm::Type
enum TypeID {
VoidTyID = 0, HalfTyID, FloatTyID, DoubleTyID,
X86_FP80TyID, FP128TyID, PPC_FP128TyID, LabelTyID,
MetadataTyID, X86_MMXTyID, IntegerTyID, FunctionTyID,
StructTyID, ArrayTyID, PointerTyID, VectorTyID
}
typedef Type *const * subtype_iterator
typedef std::reverse_iterator
< subtype_iterator > subtype_reverse_iterator
Public Member Functions
bool isVarArg () const
Type * getReturnType () const
param_iterator param_begin () const
param_iterator param_end () const
ArrayRef< Type * > params () const
Type * getParamType (unsigned i) const
Parameter type accessors.
unsigned getNumParams () const
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O) const
void dump () const
LLVMContext & getContext () const
getContext - Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
bool isVoidTy () const
isVoidTy - Return true if this is 'void'.
bool isHalfTy () const
isHalfTy - Return true if this is 'half', a 16-bit IEEE fp type.
bool isFloatTy () const
isFloatTy - Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
isDoubleTy - Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
isX86_FP80Ty - Return true if this is x86 long double.
bool isFP128Ty () const
isFP128Ty - Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
isPPC_FP128Ty - Return true if this is powerpc long double.
bool isFloatingPointTy () const
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
isX86_MMXTy - Return true if this is X86 MMX.
bool isFPOrFPVectorTy () const
bool isLabelTy () const
isLabelTy - Return true if this is 'label'.
bool isMetadataTy () const
isMetadataTy - Return true if this is 'metadata'.
bool isIntegerTy () const
bool isIntegerTy (unsigned Bitwidth) const
isIntegerTy - Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
bool isFunctionTy () const
bool isStructTy () const
bool isArrayTy () const
bool isPointerTy () const
bool isPtrOrPtrVectorTy () const
bool isVectorTy () const
bool canLosslesslyBitCastTo (Type *Ty) const
Determine if this type could be losslessly bitcast to Ty.
bool isEmptyTy () const
bool isFirstClassType () const
bool isSingleValueType () const
bool isAggregateType () const
bool isSized (SmallPtrSetImpl< const Type * > *Visited=nullptr) const
unsigned getPrimitiveSizeInBits () const LLVM_READONLY
unsigned getScalarSizeInBits () const LLVM_READONLY
int getFPMantissaWidth () const
const Type * getScalarType () const LLVM_READONLY
Type * getScalarType () LLVM_READONLY
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
unsigned getNumContainedTypes () const
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
Type * getSequentialElementType () const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
unsigned getVectorNumElements () const
Type * getVectorElementType () const
Type * getPointerElementType () const
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0)
Static Public Member Functions
static FunctionType * get (Type *Result, ArrayRef< Type * > Params, bool isVarArg)
static FunctionType * get (Type *Result, bool isVarArg)
static bool isValidReturnType (Type *RetTy)
static bool isValidArgumentType (Type *ArgTy)
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
getPrimitiveType - Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Additional Inherited Members
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()
void setTypeID (TypeID ID)
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys
Type *const * ContainedTys
Detailed Description
FunctionType - Class to represent function types
Definition at line 96 of file DerivedTypes.h.
Member Typedef Documentation
typedef Type::subtype_iterator llvm::FunctionType::param_iterator
Definition at line 123 of file DerivedTypes.h.
Member Function Documentation
static bool llvm::FunctionType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 139 of file DerivedTypes.h.
References llvm::Type::FunctionTyID, and llvm::Type::getTypeID().
FunctionType * FunctionType::get (Type * Result, ArrayRef< Type * > Params, bool isVarArg) static
FunctionType::get - This static method is the primary way of constructing a FunctionType.
Definition at line 359 of file Type.cpp.
References llvm::DenseSet< ValueT, ValueInfoT >::end(), llvm::DenseSet< ValueT, ValueInfoT >::find_as(), llvm::LLVMContextImpl::FunctionTypes, llvm::Type::getContext(), I, llvm::DenseSet< ValueT, ValueInfoT >::insert(), llvm::LLVMContext::pImpl, llvm::ArrayRef< T >::size(), and llvm::LLVMContextImpl::TypeAllocator.
Referenced by appendToGlobalArray(), llvm::CloneFunction(), EnsureFunctionExists(), GenerateARCBBEntranceAnnotation(), GenerateARCBBTerminatorAnnotation(), llvm::TypeBuilder< R(), cross >::get(), llvm::TypeBuilder< R(A1), cross >::get(), llvm::TypeBuilder< R(A1, A2), cross >::get(), llvm::TypeBuilder< R(A1, A2, A3), cross >::get(), llvm::TypeBuilder< R(A1, A2, A3, A4), cross >::get(), llvm::TypeBuilder< R(A1, A2, A3, A4, A5), cross >::get(), llvm::TypeBuilder< R(...), cross >::get(), llvm::TypeBuilder< R(A1,...), cross >::get(), llvm::TypeBuilder< R(A1, A2,...), cross >::get(), llvm::TypeBuilder< R(A1, A2, A3,...), cross >::get(), llvm::TypeBuilder< R(A1, A2, A3, A4,...), cross >::get(), llvm::TypeBuilder< R(A1, A2, A3, A4, A5,...), cross >::get(), llvm::Module::getOrInsertFunction(), llvm::Intrinsic::getType(), inlineAsmOut(), LLVMFunctionType(), ReplaceCallWith(), llvm::JumpInstrTables::transformType(), and UpgradeIntrinsicFunction1().
FunctionType * FunctionType::get (Type * Result, bool isVarArg) static
FunctionType::get - Create a FunctionType taking no parameters.
Definition at line 379 of file Type.cpp.
References isVarArg(), and llvm::None.
unsigned llvm::FunctionType::getNumParams () const inline
getNumParams - Return the number of fixed parameters this function type requires. This does not consider varargs.
Definition at line 136 of file DerivedTypes.h.
References llvm::Type::NumContainedTys.
Referenced by llvm::Function::arg_empty(), llvm::Function::arg_size(), checkStringCopyLibFuncSignature(), FindCXAAtExit(), getAllocationData(), getMangledTypeStr(), llvm::Mangler::getNameWithPrefix(), llvm::isFreeCall(), isMemsetPattern16(), isTrigLibCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::TypePrinting::print(), llvm::AssemblyWriter::printFunction(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::FastISel::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::JumpInstrTables::transformType(), UpgradeX86IntrinsicsWith8BitMask(), llvm::InlineAsm::Verify(), and WriteTypeTable().
Type* llvm::FunctionType::getParamType (unsigned i) const inline
Parameter type accessors.
Definition at line 131 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by checkStringCopyLibFuncSignature(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), FindCXAAtExit(), getAllocationData(), getMangledTypeStr(), llvm::isFreeCall(), isMemsetPattern16(), isTrigLibCall(), llvm::SITargetLowering::LowerFormalArguments(), needsFPStubFromParams(), llvm::AssemblyWriter::printFunction(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), UpgradeSSE41Function(), UpgradeX86IntrinsicsWith8BitMask(), whichFPParamVariantNeeded(), and WriteTypeTable().
Type* llvm::FunctionType::getReturnType () const inline
Definition at line 121 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by checkStringCopyLibFuncSignature(), llvm::CloneFunction(), FindCXAAtExit(), getAllocationData(), getMangledTypeStr(), llvm::Function::getReturnType(), llvm::isFreeCall(), isTrigLibCall(), needsFPReturnHelper(), llvm::TypePrinting::print(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), SimplifyCall(), llvm::InlineAsm::Verify(), and WriteTypeTable().
bool FunctionType::isValidArgumentType (Type * ArgTy) static
isValidArgumentType - Return true if the specified type is valid as an argument type.
Definition at line 392 of file Type.cpp.
References llvm::Type::isFirstClassType().
bool FunctionType::isValidReturnType (Type * RetTy) static
isValidReturnType - Return true if the specified type is valid as a return type.
Definition at line 385 of file Type.cpp.
References llvm::Type::isFunctionTy(), llvm::Type::isLabelTy(), and llvm::Type::isMetadataTy().
bool llvm::FunctionType::isVarArg () const inline
Definition at line 120 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by llvm::Interpreter::callFunction(), llvm::CloneFunction(), llvm::ComputeUsesVAFloatArgument(), get(), getMangledTypeStr(), llvm::Mangler::getNameWithPrefix(), llvm::InlineFunction(), isMemsetPattern16(), llvm::Function::isVarArg(), llvm::TypePrinting::print(), llvm::AssemblyWriter::printFunction(), llvm::MCJIT::runFunction(), llvm::FastISel::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::JumpInstrTables::transformType(), llvm::InlineAsm::Verify(), and WriteTypeTable().
param_iterator llvm::FunctionType::param_begin () const inline
Definition at line 124 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by LLVMGetParamTypes(), llvm::TypePrinting::print(), and llvm::JumpInstrTables::transformType().
param_iterator llvm::FunctionType::param_end () const inline
Definition at line 125 of file DerivedTypes.h.
References llvm::Type::ContainedTys, and llvm::Type::NumContainedTys.
Referenced by LLVMGetParamTypes(), llvm::TypePrinting::print(), and llvm::JumpInstrTables::transformType().
ArrayRef<Type *> llvm::FunctionType::params () const inline
Definition at line 126 of file DerivedTypes.h.
References llvm::makeArrayRef().
The documentation for this class was generated from the following files:
DerivedTypes.h
Type.cpp