LLVM: llvm::ScopedHashTableVal< K, V > Class Template Reference
LLVM API Documentation
llvm::ScopedHashTableVal< K, V > Class Template Reference
#include <ScopedHashTable.h>
Public Member Functions
const K & getKey () const
const V & getValue () const
V & getValue ()
ScopedHashTableVal * getNextForKey ()
const ScopedHashTableVal * getNextForKey () const
ScopedHashTableVal * getNextInScope ()
template<typename AllocatorTy >
void Destroy (AllocatorTy &Allocator)
Static Public Member Functions
template<typename AllocatorTy >
static ScopedHashTableVal * Create (ScopedHashTableVal *nextInScope, ScopedHashTableVal *nextForKey, const K &key, const V &val, AllocatorTy &Allocator)
Detailed Description
template<typename K, typename V>
class llvm::ScopedHashTableVal< K, V >
Definition at line 44 of file ScopedHashTable.h.
Member Function Documentation
template<typename K, typename V> template<typename AllocatorTy > static ScopedHashTableVal* llvm::ScopedHashTableVal< K, V >::Create (ScopedHashTableVal< K, V > * nextInScope, ScopedHashTableVal< K, V > * nextForKey, const K & key, const V & val, AllocatorTy & Allocator) inline static
Definition at line 61 of file ScopedHashTable.h.
Referenced by llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::insertIntoScope().
template<typename K, typename V> template<typename AllocatorTy > void llvm::ScopedHashTableVal< K, V >::Destroy (AllocatorTy & Allocator) inline
Definition at line 74 of file ScopedHashTable.h.
Referenced by llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope().
template<typename K, typename V> const K& llvm::ScopedHashTableVal< K, V >::getKey () const inline
Definition at line 52 of file ScopedHashTable.h.
template<typename K, typename V> ScopedHashTableVal* llvm::ScopedHashTableVal< K, V >::getNextForKey () inline
Definition at line 56 of file ScopedHashTable.h.
Referenced by llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope().
template<typename K, typename V> const ScopedHashTableVal* llvm::ScopedHashTableVal< K, V >::getNextForKey () const inline
Definition at line 57 of file ScopedHashTable.h.
template<typename K, typename V> ScopedHashTableVal* llvm::ScopedHashTableVal< K, V >::getNextInScope () inline
Definition at line 58 of file ScopedHashTable.h.
Referenced by llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope().
template<typename K, typename V> const V& llvm::ScopedHashTableVal< K, V >::getValue () const inline
Definition at line 53 of file ScopedHashTable.h.
template<typename K, typename V> V& llvm::ScopedHashTableVal< K, V >::getValue () inline
Definition at line 54 of file ScopedHashTable.h.
The documentation for this class was generated from the following file:
ScopedHashTable.h