LLVM: llvm::GEPOperator Class Reference
LLVM API Documentation
llvm::GEPOperator Class Reference
#include <Operator.h>
Public Member Functions
bool isInBounds () const
Test whether this is an inbounds GEP, as defined by LangRef.html.
op_iterator idx_begin ()
const_op_iterator idx_begin () const
op_iterator idx_end ()
const_op_iterator idx_end () const
Value * getPointerOperand ()
const Value * getPointerOperand () const
Type * getPointerOperandType () const
Method to return the pointer operand as a PointerType.
unsigned getPointerAddressSpace () const
Method to return the address space of the pointer operand.
unsigned getNumIndices () const
bool hasIndices () const
bool hasAllZeroIndices () const
bool hasAllConstantIndices () const
bool accumulateConstantOffset (const DataLayout &DL, APInt &Offset) const
Accumulate the constant address offset of this GEP if possible.
Public Member Functions inherited from llvm::Operator
unsigned getOpcode () const
Return the opcode for this Instruction or ConstantExpr.
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range
< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range
< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Static Public Member Functions
static unsigned getPointerOperandIndex ()
Static Public Member Functions inherited from llvm::ConcreteOperator< Operator, Instruction::GetElementPtr >
static bool classof (const Instruction *I)
static bool classof (const ConstantExpr *CE)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Operator
static unsigned getOpcode (const Value *V)
static bool classof (const Instruction *)
static bool classof (const ConstantExpr *)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class GetElementPtrInst
class ConstantExpr
Additional Inherited Members
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range
< op_iterator > op_range
typedef iterator_range
< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MetadataAsValueVal, InlineAsmVal, InstructionVal,
ConstantFirstVal = FunctionVal, ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl
< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl
< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Member Functions inherited from llvm::Operator
~Operator ()
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
Definition at line 364 of file Operator.h.
Member Function Documentation
bool llvm::GEPOperator::accumulateConstantOffset (const DataLayout & DL, APInt & Offset) const inline
Accumulate the constant address offset of this GEP if possible.
This routine accepts an APInt into which it will accumulate the constant offset of this GEP if the GEP is in fact constant. If the GEP is not all-constant, it returns false and the value of the offset APInt is undefined (it is not preserved!). The APInt passed into this routine must be at exactly as wide as the IntPtr type for the address space of the base GEP pointer.
Definition at line 448 of file Operator.h.
References assert(), llvm::dyn_cast(), llvm::gep_type_begin(), llvm::gep_type_end(), llvm::APInt::getBitWidth(), llvm::StructLayout::getElementOffset(), llvm::DataLayout::getPointerSizeInBits(), llvm::DataLayout::getStructLayout(), llvm::DataLayout::getTypeAllocSize(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), llvm::ConstantInt::isZero(), and llvm::APInt::sextOrTrunc().
Referenced by IsConstantOffsetFromGlobal(), and llvm::ObjectSizeOffsetVisitor::visitGEPOperator().
unsigned llvm::GEPOperator::getNumIndices () const inline
Definition at line 408 of file Operator.h.
References llvm::User::getNumOperands().
unsigned llvm::GEPOperator::getPointerAddressSpace () const inline
Method to return the address space of the pointer operand.
Definition at line 404 of file Operator.h.
Referenced by DecomposeGEPExpression(), and isGEPKnownNonNull().
Value* llvm::GEPOperator::getPointerOperand () inline
Definition at line 388 of file Operator.h.
References llvm::User::getOperand().
Referenced by llvm::DependenceAnalysis::depends(), llvm::DependenceAnalysis::getSplitIteration(), isGEPKnownNonNull(), llvm::ObjectSizeOffsetVisitor::visitGEPOperator(), and llvm::ObjectSizeOffsetEvaluator::visitGEPOperator().
const Value* llvm::GEPOperator::getPointerOperand () const inline
Definition at line 391 of file Operator.h.
References llvm::User::getOperand().
static unsigned llvm::GEPOperator::getPointerOperandIndex () inline static
Definition at line 394 of file Operator.h.
Type* llvm::GEPOperator::getPointerOperandType () const inline
Method to return the pointer operand as a PointerType.
Definition at line 399 of file Operator.h.
References getPointerOperand().
Referenced by llvm::DependenceAnalysis::depends(), and llvm::DependenceAnalysis::getSplitIteration().
bool llvm::GEPOperator::hasAllConstantIndices () const inline
Return true if all of the indices of this GEP are constant integers. If so, the result pointer and the first operand have a constant offset between them.
Definition at line 432 of file Operator.h.
References I.
Referenced by llvm::InstCombiner::FoldGEPICmp().
bool llvm::GEPOperator::hasAllZeroIndices () const inline
Return true if all of the indices of this GEP are zeros. If so, the result pointer and the first operand have the same value, just potentially different types.
Definition at line 419 of file Operator.h.
References llvm::CallingConv::C, and I.
Referenced by DecomposeGEPExpression(), evaluateICmpRelation(), llvm::InstCombiner::FoldGEPICmp(), and shouldMergeGEPs().
bool llvm::GEPOperator::hasIndices () const inline
Definition at line 412 of file Operator.h.
References llvm::User::getNumOperands().
op_iterator llvm::GEPOperator::idx_begin () inline
Definition at line 383 of file Operator.h.
References llvm::User::op_begin().
Referenced by llvm::DependenceAnalysis::depends(), and llvm::DependenceAnalysis::getSplitIteration().
const_op_iterator llvm::GEPOperator::idx_begin () const inline
Definition at line 384 of file Operator.h.
References llvm::User::op_begin().
op_iterator llvm::GEPOperator::idx_end () inline
Definition at line 385 of file Operator.h.
References llvm::User::op_end().
Referenced by llvm::DependenceAnalysis::depends(), and llvm::DependenceAnalysis::getSplitIteration().
const_op_iterator llvm::GEPOperator::idx_end () const inline
Definition at line 386 of file Operator.h.
References llvm::User::op_end().
bool llvm::GEPOperator::isInBounds () const inline
Test whether this is an inbounds GEP, as defined by LangRef.html.
Definition at line 379 of file Operator.h.
References llvm::Value::SubclassOptionalData.
Referenced by llvm::EmitGEPOffset(), llvm::InstCombiner::FoldGEPICmp(), and isGEPKnownNonNull().
Friends And Related Function Documentation
friend class ConstantExpr friend
Definition at line 371 of file Operator.h.
friend class GetElementPtrInst friend
Definition at line 370 of file Operator.h.
The documentation for this class was generated from the following file:
Operator.h