LLVM: llvm::VLIWMachineScheduler Class Reference
LLVM API Documentation
llvm::VLIWMachineScheduler Class Reference
#include <HexagonMachineScheduler.h>
Public Member Functions
VLIWMachineScheduler (MachineSchedContext *C, std::unique_ptr< MachineSchedStrategy > S)
void schedule () override
void postprocessDAG ()
Perform platform-specific DAG postprocessing.
Public Member Functions inherited from llvm::ScheduleDAGMILive
ScheduleDAGMILive (MachineSchedContext *C, std::unique_ptr< MachineSchedStrategy > S)
virtual ~ScheduleDAGMILive ()
bool hasVRegLiveness () const override
Return true if this DAG supports VReg liveness and RegPressure.
bool isTrackingPressure () const
Return true if register pressure tracking is enabled.
const IntervalPressure & getTopPressure () const
Get current register pressure for the top scheduled instructions.
const RegPressureTracker & getTopRPTracker () const
const IntervalPressure & getBotPressure () const
Get current register pressure for the bottom scheduled instructions.
const RegPressureTracker & getBotRPTracker () const
const IntervalPressure & getRegPressure () const
Get register pressure for the entire scheduling region before scheduling.
const std::vector
< PressureChange > & getRegionCriticalPSets () const
PressureDiff & getPressureDiff (const SUnit *SU)
void computeDFSResult ()
const SchedDFSResult * getDFSResult () const
Return a non-null DFS result if the scheduling strategy initialized it.
BitVector & getScheduledTrees ()
void enterRegion (MachineBasicBlock *bb, MachineBasicBlock::iterator begin, MachineBasicBlock::iterator end, unsigned regioninstrs) override
unsigned computeCyclicCriticalPath ()
Compute the cyclic critical path through the DAG.
Public Member Functions inherited from llvm::ScheduleDAGMI
ScheduleDAGMI (MachineSchedContext *C, std::unique_ptr< MachineSchedStrategy > S, bool IsPostRA)
~ScheduleDAGMI () override
void addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation)
bool canAddEdge (SUnit *SuccSU, SUnit *PredSU)
True if an edge can be added from PredSU to SuccSU without creating a cycle.
bool addEdge (SUnit *SuccSU, const SDep &PredDep)
Add a DAG edge to the given SU with the given predecessor dependence data.
MachineBasicBlock::iterator top () const
MachineBasicBlock::iterator bottom () const
void moveInstruction (MachineInstr *MI, MachineBasicBlock::iterator InsertPos)
const SUnit * getNextClusterPred () const
const SUnit * getNextClusterSucc () const
void viewGraph (const Twine &Name, const Twine &Title) override
void viewGraph () override
Out-of-line implementation with no arguments is handy for gdb.
Public Member Functions inherited from llvm::ScheduleDAGInstrs
ScheduleDAGInstrs (MachineFunction &mf, const MachineLoopInfo *mli, bool IsPostRAFlag, bool RemoveKillFlags=false, LiveIntervals *LIS=nullptr)
virtual ~ScheduleDAGInstrs ()
bool isPostRA () const
LiveIntervals * getLIS () const
Expose LiveIntervals for use in DAG mutators and such.
const TargetSchedModel * getSchedModel () const
Get the machine model for instruction scheduling.
const MCSchedClassDesc * getSchedClass (SUnit *SU) const
Resolve and cache a resolved scheduling class for an SUnit.
MachineBasicBlock::iterator begin () const
begin - Return an iterator to the top of the current scheduling region.
MachineBasicBlock::iterator end () const
end - Return an iterator to the bottom of the current scheduling region.
SUnit * newSUnit (MachineInstr *MI)
newSUnit - Creates a new SUnit and return a ptr to it.
SUnit * getSUnit (MachineInstr *MI) const
getSUnit - Return an existing SUnit for this MI, or NULL.
virtual void startBlock (MachineBasicBlock *BB)
startBlock - Prepare to perform scheduling in the given block.
virtual void finishBlock ()
finishBlock - Clean up after scheduling in the given block.
virtual void exitRegion ()
Notify that the scheduler has finished scheduling the current region.
void buildSchedGraph (AliasAnalysis *AA, RegPressureTracker *RPTracker=nullptr, PressureDiffs *PDiffs=nullptr)
void addSchedBarrierDeps ()
virtual void finalizeSchedule ()
void dumpNode (const SUnit *SU) const override
std::string getGraphNodeLabel (const SUnit *SU) const override
Return a label for a DAG node that points to an instruction.
std::string getDAGName () const override
Return a label for the region of code covered by the DAG.
void fixupKills (MachineBasicBlock *MBB)
Fix register kill flags that scheduling has made invalid.
Public Member Functions inherited from llvm::ScheduleDAG
ScheduleDAG (MachineFunction &mf)
virtual ~ScheduleDAG ()
void clearDAG ()
clearDAG - clear the DAG state (between regions).
const MCInstrDesc * getInstrDesc (const SUnit *SU) const
virtual void addCustomGraphFeatures (GraphWriter< ScheduleDAG * > &) const
unsigned VerifyScheduledDAG (bool isBottomUp)
Additional Inherited Members
Public Attributes inherited from llvm::ScheduleDAG
const TargetMachine & TM
const TargetInstrInfo * TII
const TargetRegisterInfo * TRI
MachineFunction & MF
MachineRegisterInfo & MRI
std::vector< SUnit > SUnits
SUnit EntrySU
SUnit ExitSU
bool StressSched
Protected Types inherited from llvm::ScheduleDAGInstrs
typedef std::vector< std::pair
< MachineInstr *, MachineInstr * > > DbgValueVector
Protected Member Functions inherited from llvm::ScheduleDAGMILive
void buildDAGWithRegPressure ()
Build the DAG and setup three register pressure trackers.
void scheduleMI (SUnit *SU, bool IsTopNode)
Move an instruction and update register pressure.
void initRegPressure ()
void updatePressureDiffs (ArrayRef< unsigned > LiveUses)
void updateScheduledPressure (const SUnit *SU, const std::vector< unsigned > &NewMaxPressure)
Protected Member Functions inherited from llvm::ScheduleDAGMI
void postprocessDAG ()
Apply each ScheduleDAGMutation step in order.
void initQueues (ArrayRef< SUnit * > TopRoots, ArrayRef< SUnit * > BotRoots)
Release ExitSU predecessors and setup scheduler queues.
void updateQueues (SUnit *SU, bool IsTopNode)
Update scheduler DAG and queues after scheduling an instruction.
void placeDebugValues ()
Reinsert debug_values recorded in ScheduleDAGInstrs::DbgValues.
void dumpSchedule () const
dump the scheduled Sequence.
bool checkSchedLimit ()
void findRootsAndBiasEdges (SmallVectorImpl< SUnit * > &TopRoots, SmallVectorImpl< SUnit * > &BotRoots)
void releaseSucc (SUnit *SU, SDep *SuccEdge)
void releaseSuccessors (SUnit *SU)
releaseSuccessors - Call releaseSucc on each of SU's successors.
void releasePred (SUnit *SU, SDep *PredEdge)
void releasePredecessors (SUnit *SU)
releasePredecessors - Call releasePred on each of SU's predecessors.
Protected Member Functions inherited from llvm::ScheduleDAGInstrs
void initSUnits ()
void addPhysRegDataDeps (SUnit *SU, unsigned OperIdx)
void addPhysRegDeps (SUnit *SU, unsigned OperIdx)
void addVRegDefDeps (SUnit *SU, unsigned OperIdx)
void addVRegUseDeps (SUnit *SU, unsigned OperIdx)
void startBlockForKills (MachineBasicBlock *BB)
PostRA helper for rewriting kill flags.
bool toggleKillFlag (MachineInstr *MI, MachineOperand &MO)
Toggle a register operand kill flag.
Protected Attributes inherited from llvm::ScheduleDAGMILive
RegisterClassInfo * RegClassInfo
SchedDFSResult * DFSResult
BitVector ScheduledTrees
MachineBasicBlock::iterator LiveRegionEnd
PressureDiffs SUPressureDiffs
bool ShouldTrackPressure
Register pressure in this region computed by initRegPressure.
IntervalPressure RegPressure
RegPressureTracker RPTracker
std::vector< PressureChange > RegionCriticalPSets
IntervalPressure TopPressure
The top of the unscheduled zone.
RegPressureTracker TopRPTracker
IntervalPressure BotPressure
The bottom of the unscheduled zone.
RegPressureTracker BotRPTracker
Protected Attributes inherited from llvm::ScheduleDAGMI
AliasAnalysis * AA
std::unique_ptr
< MachineSchedStrategy > SchedImpl
ScheduleDAGTopologicalSort Topo
std::vector< std::unique_ptr
< ScheduleDAGMutation > > Mutations
Ordered list of DAG postprocessing steps.
MachineBasicBlock::iterator CurrentTop
The top of the unscheduled zone.
MachineBasicBlock::iterator CurrentBottom
The bottom of the unscheduled zone.
const SUnit * NextClusterPred
Record the next node in a scheduled cluster.
const SUnit * NextClusterSucc
unsigned NumInstrsScheduled
Protected Attributes inherited from llvm::ScheduleDAGInstrs
const MachineLoopInfo * MLI
const MachineFrameInfo * MFI
LiveIntervals * LIS
Live Intervals provides reaching defs in preRA scheduling.
TargetSchedModel SchedModel
TargetSchedModel provides an interface to the machine model.
bool IsPostRA
isPostRA flag indicates vregs cannot be present.
bool RemoveKillFlags
bool CanHandleTerminators
MachineBasicBlock * BB
The block in which to insert instructions.
MachineBasicBlock::iterator RegionBegin
The beginning of the range to be scheduled.
MachineBasicBlock::iterator RegionEnd
The end of the range to be scheduled.
unsigned NumRegionInstrs
Instructions in this region (distance(RegionBegin, RegionEnd)).
DenseMap< MachineInstr *, SUnit * > MISUnitMap
VReg2UseMap VRegUses
Reg2SUnitsMap Defs
Reg2SUnitsMap Uses
VReg2SUnitMap VRegDefs
Track the last instruction in this region defining each virtual register.
std::vector< SUnit * > PendingLoads
DbgValueVector DbgValues
MachineInstr * FirstDbgValue
BitVector LiveRegs
Set of live physical registers for updating kill flags.
Detailed Description
Extend the standard ScheduleDAGMI to provide more context and override the top-level schedule() driver.
Definition at line 96 of file HexagonMachineScheduler.h.
Constructor & Destructor Documentation
llvm::VLIWMachineScheduler::VLIWMachineScheduler (MachineSchedContext * C, std::unique_ptr< MachineSchedStrategy > S) inline
Definition at line 98 of file HexagonMachineScheduler.h.
Member Function Documentation
void VLIWMachineScheduler::postprocessDAG ()
Perform platform-specific DAG postprocessing.
Platform-specific modifications to DAG.
Definition at line 24 of file HexagonMachineScheduler.cpp.
References llvm::SDep::Barrier, and llvm::ScheduleDAG::SUnits.
Referenced by schedule().
void VLIWMachineScheduler::schedule () override virtual
Schedule - This is called back from ScheduleDAGInstrs::Run() when it's time to do some work.
schedule - Called back from MachineScheduler::runOnMachineFunction after setting up the current scheduling region. [RegionBegin, RegionEnd) only includes instructions that have DAG nodes, not scheduling boundaries.
Reimplemented from llvm::ScheduleDAGMILive.
Definition at line 143 of file HexagonMachineScheduler.cpp.
References assert(), llvm::ScheduleDAGInstrs::BB, llvm::ScheduleDAGMILive::buildDAGWithRegPressure(), llvm::ScheduleDAGMI::checkSchedLimit(), llvm::ScheduleDAGMI::CurrentBottom, llvm::ScheduleDAGMI::CurrentTop, llvm::dbgs(), DEBUG, llvm::ScheduleDAGMI::findRootsAndBiasEdges(), llvm::MachineFunction::getFunction(), llvm::MachineLoopInfo::getLoopDepth(), llvm::MachineBasicBlock::getName(), llvm::Value::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::getParent(), llvm::ScheduleDAGMI::initQueues(), llvm::ScheduleDAGInstrs::MLI, llvm::ScheduleDAGMI::placeDebugValues(), postprocessDAG(), llvm::ScheduleDAGMI::SchedImpl, llvm::ScheduleDAGMILive::scheduleMI(), llvm::ScheduleDAG::SUnits, and llvm::ScheduleDAGMI::updateQueues().
The documentation for this class was generated from the following files:
HexagonMachineScheduler.h
HexagonMachineScheduler.cpp