LLVM: llvm::DIEValue Class Reference
LLVM API Documentation
llvm::DIEValue Class Reference abstract
#include <DIE.h>
Public Types
enum Type {
isInteger, isString, isExpr, isLabel,
isDelta, isEntry, isTypeSignature, isBlock,
isLoc, isLocList
}
Public Member Functions
Type getType () const
virtual void EmitValue (AsmPrinter *AP, dwarf::Form Form) const =0
virtual unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const =0
virtual void print (raw_ostream &O) const =0
void dump () const
Protected Member Functions
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes
Type Ty
Detailed Description
DIEValue - A debug information entry value. Some of these roughly correlate to DWARF attribute classes.
Definition at line 202 of file DIE.h.
Member Enumeration Documentation
enum llvm::DIEValue::Type
Enumerator
isInteger
isString
isExpr
isLabel
isDelta
isEntry
isTypeSignature
isBlock
isLoc
isLocList
Definition at line 206 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEValue::DIEValue (Type T) inline explicit protected
Definition at line 224 of file DIE.h.
virtual llvm::DIEValue::~DIEValue () inline protected virtual
Definition at line 225 of file DIE.h.
Member Function Documentation
void DIEValue::dump () const
Definition at line 196 of file DIE.cpp.
References llvm::dbgs(), and print().
virtual void llvm::DIEValue::EmitValue (AsmPrinter * AP, dwarf::Form Form) const pure virtual
EmitValue - Emit value via the Dwarf writer.
Implemented in llvm::DIELocList, llvm::DIEBlock, llvm::DIELoc, llvm::DIETypeSignature, llvm::DIEEntry, llvm::DIEString, llvm::DIEDelta, llvm::DIELabel, llvm::DIEExpr, and llvm::DIEInteger.
Referenced by llvm::DIEString::EmitValue().
Type llvm::DIEValue::getType () const inline
Definition at line 229 of file DIE.h.
References Ty.
Referenced by llvm::DIEInteger::classof(), llvm::DIEExpr::classof(), llvm::DIELabel::classof(), llvm::DIEDelta::classof(), llvm::DIEString::classof(), llvm::DIEEntry::classof(), llvm::DIETypeSignature::classof(), llvm::DIELoc::classof(), llvm::DIEBlock::classof(), and llvm::DIELocList::classof().
virtual void llvm::DIEValue::print (raw_ostream & O) const pure virtual
Implemented in llvm::DIELocList, llvm::DIEBlock, llvm::DIELoc, llvm::DIETypeSignature, llvm::DIEEntry, llvm::DIEString, llvm::DIEDelta, llvm::DIELabel, llvm::DIEExpr, and llvm::DIEInteger.
Referenced by dump(), and llvm::DIEString::print().
virtual unsigned llvm::DIEValue::SizeOf (AsmPrinter * AP, dwarf::Form Form) const pure virtual
SizeOf - Return the size of a value in bytes.
Implemented in llvm::DIELocList, llvm::DIEBlock, llvm::DIELoc, llvm::DIETypeSignature, llvm::DIEEntry, llvm::DIEString, llvm::DIEDelta, llvm::DIELabel, llvm::DIEExpr, and llvm::DIEInteger.
Referenced by llvm::DIEString::SizeOf().
Member Data Documentation
Type llvm::DIEValue::Ty protected
Ty - Type of data stored in the value.
Definition at line 222 of file DIE.h.
Referenced by getType().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp