LLVM: llvm::MCWinCOFFStreamer Class Reference
LLVM API Documentation
llvm::MCWinCOFFStreamer Class Reference
#include <MCWinCOFFStreamer.h>
Public Member Functions
MCWinCOFFStreamer (MCContext &Context, MCAsmBackend &MAB, MCCodeEmitter &CE, raw_ostream &OS)
void reset () override
state management
MCStreamer interface
void InitSections (bool NoExecStack) override
Create the default sections and set the initial one.
void EmitLabel (MCSymbol *Symbol) override
void EmitAssemblerFlag (MCAssemblerFlag Flag) override
EmitAssemblerFlag - Note in the output the specified Flag.
void EmitThumbFunc (MCSymbol *Func) override
bool EmitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute) override
EmitSymbolAttribute - Add the given Attribute to Symbol.
void EmitSymbolDesc (MCSymbol *Symbol, unsigned DescValue) override
void BeginCOFFSymbolDef (MCSymbol const *Symbol) override
void EmitCOFFSymbolStorageClass (int StorageClass) override
void EmitCOFFSymbolType (int Type) override
void EndCOFFSymbolDef () override
EndCOFFSymbolDef - Marks the end of the symbol definition.
void EmitCOFFSectionIndex (MCSymbol const *Symbol) override
void EmitCOFFSecRel32 (MCSymbol const *Symbol) override
void EmitELFSize (MCSymbol *Symbol, const MCExpr *Value) override
void EmitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void EmitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void EmitZerofill (const MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void EmitTBSSSymbol (const MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void EmitFileDirective (StringRef Filename) override
void EmitIdent (StringRef IdentString) override
void EmitWinEHHandlerData () override
void FinishImpl () override
FinishImpl - Streamer specific finalization.
Public Member Functions inherited from llvm::MCObjectStreamer
bool isIntegratedAssemblerRequired () const override
Object streamers require the integrated assembler.
MCSymbolData & getOrCreateSymbolData (const MCSymbol *Symbol)
void EmitFrames (MCAsmBackend *MAB)
void EmitCFISections (bool EH, bool Debug) override
void visitUsedSymbol (const MCSymbol &Sym) override
MCAssembler & getAssembler ()
void EmitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
void EmitValueImpl (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc()) override
void EmitULEB128Value (const MCExpr *Value) override
void EmitSLEB128Value (const MCExpr *Value) override
void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
void ChangeSection (const MCSection *Section, const MCExpr *Subsection) override
void EmitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
virtual void EmitInstToFragment (const MCInst &Inst, const MCSubtargetInfo &)
Emit an instruction to a special fragment, because this instruction can change its size during relaxation.
void EmitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
void EmitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void EmitBundleUnlock () override
Ends a bundle-locked group.
void EmitBytes (StringRef Data) override
void EmitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0) override
void EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit=0) override
bool EmitValueToOffset (const MCExpr *Offset, unsigned char Value) override
void EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override
EmitDwarfLocDirective - This implements the DWARF2.
void EmitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize)
void EmitDwarfAdvanceFrameAddr (const MCSymbol *LastLabel, const MCSymbol *Label)
void EmitGPRel32Value (const MCExpr *Value) override
void EmitGPRel64Value (const MCExpr *Value) override
void EmitFill (uint64_t NumBytes, uint8_t FillValue) override
void EmitZeros (uint64_t NumBytes) override
Emit NumBytes worth of zeros. This function properly handles data in virtual sections.
bool mayHaveInstructions () const override
Public Member Functions inherited from llvm::MCStreamer
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
MCContext & getContext () const
MCTargetStreamer * getTargetStreamer ()
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
unsigned getNumWinFrameInfos ()
ArrayRef< WinEH::FrameInfo * > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual unsigned EmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, unsigned CUID=0)
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
void EmitCFIStartProc (bool IsSimple)
void EmitCFIEndProc ()
virtual void EmitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void EmitCFIDefCfaOffset (int64_t Offset)
virtual void EmitCFIDefCfaRegister (int64_t Register)
virtual void EmitCFIOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFIRememberState ()
virtual void EmitCFIRestoreState ()
virtual void EmitCFISameValue (int64_t Register)
virtual void EmitCFIRestore (int64_t Register)
virtual void EmitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void EmitCFIEscape (StringRef Values)
virtual void EmitCFISignalFrame ()
virtual void EmitCFIUndefined (int64_t Register)
virtual void EmitCFIRegister (int64_t Register1, int64_t Register2)
virtual void EmitCFIWindowSave ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol)
virtual void EmitWinCFIEndProc ()
virtual void EmitWinCFIStartChained ()
virtual void EmitWinCFIEndChained ()
virtual void EmitWinCFIPushReg (unsigned Register)
virtual void EmitWinCFISetFrame (unsigned Register, unsigned Offset)
virtual void EmitWinCFIAllocStack (unsigned Size)
virtual void EmitWinCFISaveReg (unsigned Register, unsigned Offset)
virtual void EmitWinCFISaveXMM (unsigned Register, unsigned Offset)
virtual void EmitWinCFIPushFrame (bool Code)
virtual void EmitWinCFIEndProlog ()
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except)
void EmitRawText (const Twine &String)
virtual void Flush ()
Flush - Causes any cached state to be written out.
void Finish ()
Finish - Finish emission of machine code.
virtual bool isVerboseAsm () const
virtual bool hasRawTextSupport () const
virtual void AddComment (const Twine &T)
virtual raw_ostream & GetCommentOS ()
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
MCSectionSubPair getPreviousSection () const
unsigned GetSymbolOrder (const MCSymbol *Sym) const
void PushSection ()
bool PopSection ()
bool SubSection (const MCExpr *Subsection)
virtual void SwitchSection (const MCSection *Section, const MCExpr *Subsection=nullptr)
void SwitchSectionNoChange (const MCSection *Section, const MCExpr *Subsection=nullptr)
void AssignSection (MCSymbol *Symbol, const MCSection *Section)
virtual void EmitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void EmitLinkerOptions (ArrayRef< std::string > Kind)
virtual void EmitDataRegion (MCDataRegionType Kind)
EmitDataRegion - Note in the output the specified region Kind.
virtual void EmitVersionMin (MCVersionMinType, unsigned Major, unsigned Minor, unsigned Update)
EmitVersionMin - Specify the MachO minimum deployment target version.
virtual void EmitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
void EmitValue (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc())
virtual void EmitIntValue (uint64_t Value, unsigned Size)
void EmitULEB128IntValue (uint64_t Value, unsigned Padding=0)
void EmitSLEB128IntValue (int64_t Value)
void EmitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Protected Member Functions
void EmitInstToData (const MCInst &Inst, const MCSubtargetInfo &STI) override
Protected Member Functions inherited from llvm::MCObjectStreamer
MCObjectStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter)
MCObjectStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, MCAssembler *_Assembler)
~MCObjectStreamer ()
MCSectionData * getCurrentSectionData () const
MCFragment * getCurrentFragment () const
void insert (MCFragment *F)
MCDataFragment * getOrCreateDataFragment ()
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables ()
virtual void EmitRawTextImpl (StringRef String)
Protected Attributes
const MCSymbol * CurSymbol
Detailed Description
Definition at line 28 of file MCWinCOFFStreamer.h.
Constructor & Destructor Documentation
llvm::MCWinCOFFStreamer::MCWinCOFFStreamer (MCContext & Context, MCAsmBackend & MAB, MCCodeEmitter & CE, raw_ostream & OS)
Definition at line 41 of file WinCOFFStreamer.cpp.
Member Function Documentation
void llvm::MCWinCOFFStreamer::BeginCOFFSymbolDef (MCSymbol const * Symbol) override virtual
BeginCOFFSymbolDef - Start emitting COFF symbol definition
Parameters
Symbol - The symbol to have its External & Type fields set.
Reimplemented from llvm::MCStreamer.
Definition at line 121 of file WinCOFFStreamer.cpp.
References assert(), CurSymbol, llvm::MCSymbol::getSection(), llvm::MCSection::getVariant(), llvm::MCSymbol::isInSection(), llvm::MCSection::SV_COFF, and llvm::ARMBuildAttrs::Symbol.
void llvm::MCWinCOFFStreamer::EmitAssemblerFlag (MCAssemblerFlag Flag) override virtual
EmitAssemblerFlag - Note in the output the specified Flag.
Reimplemented from llvm::MCStreamer.
Definition at line 85 of file WinCOFFStreamer.cpp.
References llvm_unreachable.
void llvm::MCWinCOFFStreamer::EmitCOFFSecRel32 (MCSymbol const * Symbol) override virtual
EmitCOFFSecRel32 - Emits a COFF section relative relocation.
Parameters
Symbol - Symbol the section relative relocation should point to.
Reimplemented from llvm::MCStreamer.
Definition at line 169 of file WinCOFFStreamer.cpp.
References llvm::MCFixup::Create(), llvm::MCSymbolRefExpr::Create(), llvm::FK_SecRel_4, llvm::MCDataFragment::getContents(), llvm::MCStreamer::getContext(), llvm::MCDataFragment::getFixups(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
void llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex (MCSymbol const * Symbol) override virtual
EmitCOFFSectionIndex - Emits a COFF section index.
Parameters
Symbol - Symbol the section number relocation should point to.
Reimplemented from llvm::MCStreamer.
Definition at line 161 of file WinCOFFStreamer.cpp.
References llvm::MCFixup::Create(), llvm::MCSymbolRefExpr::Create(), llvm::FK_SecRel_2, llvm::MCDataFragment::getContents(), llvm::MCStreamer::getContext(), llvm::MCDataFragment::getFixups(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
void llvm::MCWinCOFFStreamer::EmitCOFFSymbolStorageClass (int StorageClass) override virtual
EmitCOFFSymbolStorageClass - Emit the storage class of the symbol.
Parameters
StorageClass - The storage class the symbol should have.
Reimplemented from llvm::MCStreamer.
Definition at line 132 of file WinCOFFStreamer.cpp.
References CurSymbol, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::itostr(), llvm::MCSymbolData::modifyFlags(), llvm::COFF::SF_ClassMask, llvm::COFF::SF_ClassShift, and llvm::COFF::SSC_Invalid.
void llvm::MCWinCOFFStreamer::EmitCOFFSymbolType (int Type) override virtual
EmitCOFFSymbolType - Emit the type of the symbol.
Parameters
Type - A COFF type identifier (see COFF::SymbolType in X86COFF.h)
Reimplemented from llvm::MCStreamer.
Definition at line 144 of file WinCOFFStreamer.cpp.
References CurSymbol, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::itostr(), llvm::MCSymbolData::modifyFlags(), llvm::COFF::SF_TypeMask, and llvm::COFF::SF_TypeShift.
void llvm::MCWinCOFFStreamer::EmitCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
EmitCommonSymbol - Emit a common symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol if non-zero. This must be a power of 2.
Implements llvm::MCStreamer.
Definition at line 181 of file WinCOFFStreamer.cpp.
References assert(), llvm::MCStreamer::AssignSection(), llvm::MCObjectStreamer::EmitBytes(), llvm::raw_ostream::flush(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDrectveSection(), llvm::MCSymbol::getName(), llvm::MCContext::getObjectFileInfo(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCSymbol::getSection(), llvm::MCObjectFileInfo::getTargetTriple(), llvm::MCSection::getVariant(), llvm::MCSymbol::isInSection(), llvm::Triple::isKnownWindowsMSVCEnvironment(), llvm::Log2_32_Ceil(), llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::report_fatal_error(), llvm::MCSymbolData::setCommon(), llvm::MCSymbolData::setExternal(), llvm::MCSection::SV_COFF, and llvm::MCStreamer::SwitchSection().
void llvm::MCWinCOFFStreamer::EmitELFSize (MCSymbol * Symbol, const MCExpr * Value) override virtual
EmitELFSize - Emit an ELF .size directive.
This corresponds to an assembler statement such as: .size symbol, expression
Reimplemented from llvm::MCStreamer.
Definition at line 177 of file WinCOFFStreamer.cpp.
References llvm_unreachable.
void llvm::MCWinCOFFStreamer::EmitFileDirective (StringRef Filename) override virtual
EmitFileDirective - Switch to a new logical file. This is used to implement the '.file "foo.c"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 253 of file WinCOFFStreamer.cpp.
References llvm::MCAssembler::addFileName(), and llvm::MCObjectStreamer::getAssembler().
void llvm::MCWinCOFFStreamer::EmitIdent (StringRef IdentString) override virtual
Emit the "identifiers" directive. This implements the '.ident "version foo"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 258 of file WinCOFFStreamer.cpp.
References llvm_unreachable.
void llvm::MCWinCOFFStreamer::EmitInstToData (const MCInst & Inst, const MCSubtargetInfo & STI) override protected virtual
Implements llvm::MCObjectStreamer.
Definition at line 45 of file WinCOFFStreamer.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::tgtok::Code, llvm::MCCodeEmitter::EncodeInstruction(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::raw_ostream::flush(), llvm::MCObjectStreamer::getAssembler(), llvm::MCDataFragment::getContents(), llvm::MCAssembler::getEmitter(), llvm::MCDataFragment::getFixups(), llvm::getOffset(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::SmallVectorTemplateCommon< T >::size().
void llvm::MCWinCOFFStreamer::EmitLabel (MCSymbol * Symbol) override virtual
EmitLabel - Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 80 of file WinCOFFStreamer.cpp.
References assert(), llvm::MCObjectStreamer::EmitLabel(), and llvm::MCSymbol::isUndefined().
void llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
EmitLocalCommonSymbol - Emit a local common (.lcomm) symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the common symbol in bytes.
Reimplemented from llvm::MCStreamer.
Definition at line 218 of file WinCOFFStreamer.cpp.
References assert(), llvm::MCStreamer::AssignSection(), llvm::LCOMM::ByteAlignment, llvm::MCSectionData::getAlignment(), llvm::MCObjectStreamer::getAssembler(), llvm::MCObjectFileInfo::getBSSSection(), llvm::MCStreamer::getContext(), llvm::MCContext::getObjectFileInfo(), llvm::MCAssembler::getOrCreateSectionData(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCSymbol::isInSection(), llvm::ARMBuildAttrs::Section, llvm::MCSectionData::setAlignment(), llvm::MCSymbolData::setExternal(), and llvm::MCSymbolData::setFragment().
bool llvm::MCWinCOFFStreamer::EmitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) override virtual
EmitSymbolAttribute - Add the given Attribute to Symbol.
Implements llvm::MCStreamer.
Definition at line 93 of file WinCOFFStreamer.cpp.
References assert(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCSymbol::getSection(), llvm::MCSection::getVariant(), llvm::MCSymbol::isInSection(), llvm::MCSA_Global, llvm::MCSA_Weak, llvm::MCSA_WeakReference, llvm::MCSymbolData::modifyFlags(), llvm::MCSymbolData::setExternal(), llvm::COFF::SF_WeakExternal, and llvm::MCSection::SV_COFF.
void llvm::MCWinCOFFStreamer::EmitSymbolDesc (MCSymbol * Symbol, unsigned DescValue) override virtual
EmitSymbolDesc - Set the DescValue for the Symbol.
Parameters
Symbol - The symbol to have its n_desc field set.
DescValue - The value to set into the n_desc field.
Reimplemented from llvm::MCStreamer.
Definition at line 117 of file WinCOFFStreamer.cpp.
References llvm_unreachable.
void llvm::MCWinCOFFStreamer::EmitTBSSSymbol (const MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
EmitTBSSSymbol - Emit a thread local bss (.tbss) symbol.
Parameters
Section - The thread local common section.
Symbol - The thread local common symbol to emit.
Size - The size of the symbol.
ByteAlignment - The alignment of the thread local common symbol if non-zero. This must be a power of 2 on some targets.
Reimplemented from llvm::MCStreamer.
Definition at line 247 of file WinCOFFStreamer.cpp.
References llvm_unreachable.
void llvm::MCWinCOFFStreamer::EmitThumbFunc (MCSymbol * Func) override virtual
EmitThumbFunc - Note in the output that the specified Func is a Thumb mode function (ARM target only).
Reimplemented from llvm::MCStreamer.
Definition at line 89 of file WinCOFFStreamer.cpp.
References llvm_unreachable.
void llvm::MCWinCOFFStreamer::EmitWinEHHandlerData () override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 262 of file WinCOFFStreamer.cpp.
References llvm_unreachable.
void llvm::MCWinCOFFStreamer::EmitZerofill (const MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
EmitZerofill - Emit the zerofill section and an optional symbol.
Parameters
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol if non-zero. This must be a power of 2 on some targets.
Implements llvm::MCStreamer.
Definition at line 241 of file WinCOFFStreamer.cpp.
References llvm_unreachable.
void llvm::MCWinCOFFStreamer::EndCOFFSymbolDef () override virtual
EndCOFFSymbolDef - Marks the end of the symbol definition.
Reimplemented from llvm::MCStreamer.
Definition at line 155 of file WinCOFFStreamer.cpp.
References CurSymbol.
void llvm::MCWinCOFFStreamer::FinishImpl () override virtual
FinishImpl - Streamer specific finalization.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 266 of file WinCOFFStreamer.cpp.
References llvm::MCObjectStreamer::FinishImpl().
void llvm::MCWinCOFFStreamer::InitSections (bool NoExecStack) override virtual
Create the default sections and set the initial one.
Reimplemented from llvm::MCStreamer.
Definition at line 64 of file WinCOFFStreamer.cpp.
References llvm::MCObjectStreamer::EmitCodeAlignment(), llvm::MCStreamer::getContext(), and llvm::MCStreamer::SwitchSection().
void llvm::MCWinCOFFStreamer::reset () inline override virtual
state management
Reimplemented from llvm::MCObjectStreamer.
Definition at line 34 of file MCWinCOFFStreamer.h.
References CurSymbol, and llvm::MCObjectStreamer::reset().
Member Data Documentation
const MCSymbol* llvm::MCWinCOFFStreamer::CurSymbol protected
Definition at line 71 of file MCWinCOFFStreamer.h.
Referenced by BeginCOFFSymbolDef(), EmitCOFFSymbolStorageClass(), EmitCOFFSymbolType(), EndCOFFSymbolDef(), and reset().
The documentation for this class was generated from the following files:
MCWinCOFFStreamer.h
WinCOFFStreamer.cpp