LLVM: llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy > Class Template Reference
LLVM API Documentation
llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy > Class Template Reference
#include <SparseMultiSet.h>
Public Types
typedef std::iterator
< std::bidirectional_iterator_tag,
ValueT > super
typedef super::value_type value_type
typedef super::difference_type difference_type
typedef super::pointer pointer
typedef super::reference reference
Public Member Functions
reference operator* () const
pointer operator-> () const
bool operator== (const iterator_base &RHS) const
Comparison operators.
bool operator!= (const iterator_base &RHS) const
iterator_base & operator-- ()
Increment and decrement operators.
iterator_base & operator++ ()
iterator_base operator-- (int)
iterator_base operator++ (int)
Friends
class SparseMultiSet
Detailed Description
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t>
template<typename SMSPtrTy>
class llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >
Our iterators are iterators over the collection of objects that share a key.
Definition at line 218 of file SparseMultiSet.h.
Member Typedef Documentation
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > typedef super::difference_type llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::difference_type
Definition at line 249 of file SparseMultiSet.h.
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > typedef super::pointer llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::pointer
Definition at line 250 of file SparseMultiSet.h.
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > typedef super::reference llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::reference
Definition at line 251 of file SparseMultiSet.h.
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > typedef std::iterator<std::bidirectional_iterator_tag, ValueT> llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::super
Definition at line 247 of file SparseMultiSet.h.
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > typedef super::value_type llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::value_type
Definition at line 248 of file SparseMultiSet.h.
Member Function Documentation
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > bool llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator!= (const iterator_base< SMSPtrTy > & RHS) const inline
Definition at line 273 of file SparseMultiSet.h.
References llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator==().
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > reference llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator* () const inline
Definition at line 253 of file SparseMultiSet.h.
References assert().
Referenced by llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator->().
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > iterator_base& llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator++ () inline
Definition at line 291 of file SparseMultiSet.h.
References assert().
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > iterator_base llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator++ (int) inline
Definition at line 301 of file SparseMultiSet.h.
References llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::I.
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > iterator_base& llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator-- () inline
Increment and decrement operators.
Definition at line 278 of file SparseMultiSet.h.
References assert().
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > iterator_base llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator-- (int) inline
Definition at line 296 of file SparseMultiSet.h.
References llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::I.
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > pointer llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator-> () const inline
Definition at line 259 of file SparseMultiSet.h.
References llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator*().
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > bool llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator== (const iterator_base< SMSPtrTy > & RHS) const inline
Comparison operators.
Definition at line 262 of file SparseMultiSet.h.
References assert().
Referenced by llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator!=().
Friends And Related Function Documentation
template<typename ValueT, typename KeyFunctorT = llvm::identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > friend class SparseMultiSet friend
Definition at line 220 of file SparseMultiSet.h.
The documentation for this class was generated from the following file:
SparseMultiSet.h