LLVM: llvm::IndexedInstrProfReader Class Reference
LLVM API Documentation
llvm::IndexedInstrProfReader Class Reference
Reader for the indexed binary instrprof format.
#include <InstrProfReader.h>
Public Member Functions
IndexedInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer)
std::error_code readHeader () override
Read the file header.
std::error_code readNextRecord (InstrProfRecord &Record) override
Read a single record.
std::error_code getFunctionCounts (StringRef FuncName, uint64_t FuncHash, std::vector< uint64_t > &Counts)
Fill Counts with the profile data for the given function name.
uint64_t getMaximumFunctionCount ()
Return the maximum of all known function counts.
Public Member Functions inherited from llvm::InstrProfReader
InstrProfReader ()
virtual ~InstrProfReader ()
InstrProfIterator begin ()
Iterator over profile data.
InstrProfIterator end ()
bool isEOF ()
Return true if the reader has finished reading the profile data.
bool hasError ()
Return true if the reader encountered an error reading profiling data.
std::error_code getError ()
Get the current error code.
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &DataBuffer)
Return true if the given buffer is in an indexed instrprof format.
static std::error_code create (std::string Path, std::unique_ptr< IndexedInstrProfReader > &Result)
Factory method to create an indexed reader.
Static Public Member Functions inherited from llvm::InstrProfReader
static ErrorOr
< std::unique_ptr
< InstrProfReader > > create (std::string Path)
Additional Inherited Members
Protected Member Functions inherited from llvm::InstrProfReader
std::error_code error (std::error_code EC)
Set the current std::error_code and return same.
std::error_code success ()
Clear the current error code and return a successful one.
Detailed Description
Reader for the indexed binary instrprof format.
Definition at line 261 of file InstrProfReader.h.
Constructor & Destructor Documentation
llvm::IndexedInstrProfReader::IndexedInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer) inline
Definition at line 280 of file InstrProfReader.h.
Member Function Documentation
std::error_code IndexedInstrProfReader::create (std::string Path, std::unique_ptr< IndexedInstrProfReader > & Result) static
Factory method to create an indexed reader.
Definition at line 67 of file InstrProfReader.cpp.
References llvm::bad_magic, hasFormat(), initializeReader(), and setupMemoryBuffer().
Referenced by llvm::coverage::CoverageMapping::load().
std::error_code IndexedInstrProfReader::getFunctionCounts (StringRef FuncName, uint64_t FuncHash, std::vector< uint64_t > & Counts)
Fill Counts with the profile data for the given function name.
Definition at line 340 of file InstrProfReader.cpp.
References llvm::InstrProfReader::error(), llvm::hash_mismatch, I, llvm::malformed, llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), llvm::InstrProfReader::success(), and llvm::unknown_function.
Referenced by llvm::coverage::CoverageMapping::load().
uint64_t llvm::IndexedInstrProfReader::getMaximumFunctionCount () inline
Return the maximum of all known function counts.
Definition at line 295 of file InstrProfReader.h.
bool IndexedInstrProfReader::hasFormat (const MemoryBuffer & DataBuffer) static
Return true if the given buffer is in an indexed instrprof format.
Definition at line 293 of file InstrProfReader.cpp.
References llvm::MemoryBuffer::getBufferSize(), llvm::MemoryBuffer::getBufferStart(), and llvm::IndexedInstrProf::Magic.
Referenced by llvm::InstrProfReader::create(), and create().
std::error_code IndexedInstrProfReader::readHeader () override virtual
Read the file header.
Implements llvm::InstrProfReader.
Definition at line 302 of file InstrProfReader.cpp.
References llvm::bad_magic, llvm::OnDiskIterableChainedHashTable< Info >::Create(), llvm::InstrProfReader::error(), llvm::IndexedInstrProf::HashType, llvm::IndexedInstrProf::Last, llvm::IndexedInstrProf::Magic, llvm::InstrProfReader::success(), llvm::truncated, llvm::unsupported_hash_type, llvm::unsupported_version, and llvm::IndexedInstrProf::Version.
std::error_code IndexedInstrProfReader::readNextRecord (InstrProfRecord & Record) override virtual
Read a single record.
Implements llvm::InstrProfReader.
Definition at line 369 of file InstrProfReader.cpp.
References llvm::InstrProfRecord::Counts, llvm::eof, llvm::InstrProfReader::error(), llvm::InstrProfRecord::Hash, llvm::malformed, llvm::InstrProfRecord::Name, llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), and llvm::InstrProfReader::success().
The documentation for this class was generated from the following files:
InstrProfReader.h
InstrProfReader.cpp