LLVM: llvm::AsmPrinter Class Reference
LLVM API Documentation
llvm::AsmPrinter Class Reference
This class is intended to be used as a driving class for all asm writers.
#include <AsmPrinter.h>
Public Types
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
Public Member Functions
virtual ~AsmPrinter ()
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
bool isVerbose () const
unsigned getFunctionNumber () const
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
StringRef getTargetTriple () const
Return the target triple string.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool doInitialization (Module &M) override
bool doFinalization (Module &M) override
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
void SetupMachineFunction (MachineFunction &MF)
void EmitFunctionHeader ()
This method emits the header for the current function.
void EmitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
CFIMoveType needsCFIMoves ()
bool needsSEHMoves ()
virtual void EmitConstantPool ()
void EmitJumpTableInfo ()
virtual void EmitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
void EmitAlignment (unsigned NumBits, const GlobalObject *GO=nullptr) const
void EmitBasicBlockStart (const MachineBasicBlock &MBB) const
const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void EmitGlobalConstant (const Constant *CV)
Print a general LLVM constant to the .s file.
virtual void EmitStartOfAsmFile (Module &)
virtual void EmitEndOfAsmFile (Module &)
virtual void EmitFunctionBodyStart ()
virtual void EmitFunctionBodyEnd ()
virtual void EmitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual void EmitInstruction (const MachineInstr *)
Targets should implement this to emit instructions.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void EmitFunctionEntryLabel ()
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void EmitXXStructor (const Constant *CV)
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
virtual void emitImplicitDef (const MachineInstr *MI) const
MCSymbol * GetTempSymbol (Twine Name, unsigned ID) const
MCSymbol * GetTempSymbol (Twine Name) const
Return an assembler temporary label with the specified stem.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void EmitInt8 (int Value) const
void EmitInt16 (int Value) const
void EmitInt32 (int Value) const
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
void EmitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void EmitCFAByte (unsigned Val) const
Emit a .byte 42 directive for a DW_CFA_xxx value.
void EmitEncodingByte (unsigned Val, const char *Desc=nullptr) const
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
void EmitSectionOffset (const MCSymbol *Label, const MCSymbol *SectionLabel) const
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void EmitDwarfOpPiece (ByteStreamer &Streamer, unsigned SizeInBits, unsigned OffsetInBits=0) const
void EmitDwarfRegOpPiece (ByteStreamer &BS, const MachineLocation &MLoc, unsigned PieceSize=0, unsigned PieceOffset=0) const
Emit a partial DWARF register operation.
virtual void EmitDwarfRegOp (ByteStreamer &BS, const MachineLocation &MLoc, bool Indirect) const
EmitDwarfRegOp - Emit dwarf register operation.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
virtual bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS)
virtual bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS)
virtual void emitInlineAsmStart (const MCSubtargetInfo &StartInfo) const
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Attributes
TargetMachine & TM
const MCAsmInfo * MAI
const MCInstrInfo * MII
MCContext & OutContext
MCStreamer & OutStreamer
const MachineFunction * MF
The current machine function.
MachineModuleInfo * MMI
This is a pointer to the current MachineModuleInfo.
Mangler * Mang
MCSymbol * CurrentFnSym
MCSymbol * CurrentFnSymForSize
Protected Member Functions
AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
This class is intended to be used as a driving class for all asm writers.
Definition at line 62 of file AsmPrinter.h.
Member Enumeration Documentation
enum llvm::AsmPrinter::CFIMoveType
Enumerator
CFI_M_None
CFI_M_EH
CFI_M_Debug
Definition at line 210 of file AsmPrinter.h.
Constructor & Destructor Documentation
AsmPrinter::AsmPrinter (TargetMachine & TM, MCStreamer & Streamer) explicit protected
Definition at line 101 of file AsmPrinter.cpp.
References CurrentFnSym, CurrentFnSymForSize, llvm::MCStreamer::isVerboseAsm(), MF, and MMI.
AsmPrinter::~AsmPrinter () virtual
Definition at line 112 of file AsmPrinter.cpp.
References assert(), llvm::SmallVectorBase::empty(), getGCMap(), and OutStreamer.
Member Function Documentation
bool AsmPrinter::doFinalization (Module & M) override virtual
Shut down the asmprinter. If you override this in your pass, you must make sure to call it explicitly.
Reimplemented from llvm::Pass.
Reimplemented in llvm::NVPTXAsmPrinter.
Definition at line 896 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), assert(), llvm::GCModuleInfo::begin(), llvm::CallingConv::C, llvm::MCSymbolRefExpr::Create(), llvm::GlobalValue::DefaultVisibility, DL, EmitAlignment(), llvm::MCStreamer::EmitAssignment(), EmitEndOfAsmFile(), EmitGlobalVariable(), llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::EmitLabel(), llvm::TargetLoweringObjectFile::emitModuleFlags(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitThumbFunc(), llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::GCModuleInfo::end(), llvm::JumpInstrTableInfo::entryByteAlignment(), F(), llvm::MCStreamer::Finish(), llvm::MCStreamer::Flush(), G, llvm::Triple::getArch(), llvm::TargetSubtargetInfo::getDataLayout(), GetExternalSymbolSymbol(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MCAsmInfo::getNonexecutableStackSection(), llvm::MCContext::getObjectFileInfo(), getObjFileLowering(), llvm::MCContext::GetOrCreateSymbol(), llvm::DataLayout::getPointerSize(), llvm::SectionKind::getReadOnly(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::TargetMachine::getSubtargetImpl(), getSubtargetInfo(), getSymbol(), llvm::JumpInstrTableInfo::getTables(), getTargetTriple(), llvm::MCObjectFileInfo::getTextSection(), llvm::TargetInstrInfo::getTrap(), llvm::TargetInstrInfo::getUnconditionalBranch(), llvm::MCAsmInfo::getWeakRefDirective(), llvm::Module::globals(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::AArch64CC::HI, I, llvm::Log2_64(), lowerConstant(), MAI, Mang, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_Global, llvm::MCSA_WeakReference, llvm::AArch64CC::MI, MMI, Name, llvm::NextPowerOf2(), OutContext, OutStreamer, llvm::MCStreamer::reset(), llvm::MCStreamer::SwitchSection(), T, llvm::Triple::thumb, llvm::Triple::thumbeb, llvm::TimePassesIsEnabled, TM, llvm::Value::use_empty(), llvm::MachineModuleInfo::usesMorestackAddr(), and llvm::MCSymbolRefExpr::VK_PLT.
Referenced by llvm::NVPTXAsmPrinter::doFinalization().
bool AsmPrinter::doInitialization (Module & M) override virtual
Set up the AsmPrinter when we are working on a new module. If your pass overrides this, it must make sure to explicitly call this implementation.
Reimplemented from llvm::Pass.
Reimplemented in llvm::NVPTXAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 168 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCStreamer::AddComment(), llvm::MachineModuleInfo::AnalyzeModule(), llvm::ARM, assert(), CodeViewLineTablesGroupName, DbgTimerName, llvm::MCAsmInfo::doesSupportDebugInformation(), llvm::DwarfCFI, DWARFGroupName, EHTimerName, llvm::MCStreamer::EmitFileDirective(), EmitStartOfAsmFile(), llvm::MCStreamer::EmitVersionMin(), F(), llvm::Module::functions(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::Module::getModuleIdentifier(), llvm::Module::getModuleInlineAsm(), getObjFileLowering(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetMachine::getTargetTriple(), getTargetTriple(), llvm::MCAsmInfo::getWinEHEncodingType(), llvm::MCAsmInfo::hasSingleParameterDotFile(), I, llvm::MCStreamer::InitSections(), llvm::WinEH::Itanium, llvm::ItaniumWinEH, llvm_unreachable, MAI, Mang, llvm::MCVM_IOSVersionMin, llvm::MCVM_OSXVersionMin, llvm::AArch64CC::MI, MMI, llvm::MSVC, llvm::None, OutContext, OutStreamer, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Attribute::SanitizeAddress, llvm::SjLj, and TM.
Referenced by llvm::X86AsmPrinter::doInitialization().
void AsmPrinter::EmitAlignment (unsigned NumBits, const GlobalObject * GO = nullptr) const
Emit an alignment directive to the specified power of two boundary. For example, if you pass in 3 here, you will get an 8 byte alignment. If a global value is specified, and if that global has an explicit alignment requested, it will override the alignment request if required for correctness.
Definition at line 1540 of file AsmPrinter.cpp.
References assert(), llvm::MCStreamer::EmitCodeAlignment(), llvm::MCStreamer::EmitValueToAlignment(), getCurrentSection(), llvm::TargetSubtargetInfo::getDataLayout(), getGVAlignmentLog2(), llvm::TargetMachine::getSubtargetImpl(), OutStreamer, and TM.
Referenced by doFinalization(), EmitBasicBlockStart(), EmitConstantPool(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), EmitFunctionHeader(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitInstruction(), EmitJumpTableInfo(), and llvm::ARMAsmPrinter::runOnMachineFunction().
virtual void llvm::AsmPrinter::EmitBasicBlockEnd (const MachineBasicBlock & MBB) inline virtual
Targets can override this to emit stuff at the end of a basic block.
Reimplemented in llvm::X86AsmPrinter.
Definition at line 275 of file AsmPrinter.h.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitBasicBlockStart (const MachineBasicBlock & MBB) const
This method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
EmitBasicBlockStart - This method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
Definition at line 2203 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddComment(), EmitAlignment(), emitBasicBlockLoopComments(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::emitRawComment(), llvm::MachineModuleInfo::getAddrLabelSymbolToEmit(), llvm::MachineBasicBlock::getAlignment(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineBasicBlock::hasAddressTaken(), isBlockOnlyReachableByFallthrough(), isVerbose(), MMI, OutStreamer, and llvm::MachineBasicBlock::pred_empty().
Referenced by EmitFunctionBody().
void AsmPrinter::EmitCFAByte (unsigned Val) const
Emit a .byte 42 directive for a DW_CFA_xxx value.
EmitCFAByte - Emit a .byte 42 directive for a DW_CFA_xxx value.
Definition at line 76 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::AddComment(), llvm::dwarf::CallFrameString(), llvm::dwarf::DW_CFA_offset, llvm::MCStreamer::EmitIntValue(), isVerbose(), and OutStreamer.
void AsmPrinter::emitCFIInstruction (const MachineInstr & MI)
Definition at line 735 of file AsmPrinter.cpp.
References llvm::ARM, CFI_M_None, llvm::DwarfCFI, llvm::MachineOperand::getCFIIndex(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineModuleInfo::getFrameInstructions(), llvm::MachineFunction::getMMI(), llvm::MachineInstr::getOperand(), MAI, MF, MMI, and needsCFIMoves().
Referenced by EmitFunctionBody().
void AsmPrinter::emitCFIInstruction (const MCCFIInstruction & Inst) const
Emit frame instruction to describe the layout of the frame.
Definition at line 265 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::EmitCFIDefCfa(), llvm::MCStreamer::EmitCFIDefCfaOffset(), llvm::MCStreamer::EmitCFIDefCfaRegister(), llvm::MCStreamer::EmitCFIOffset(), llvm::MCStreamer::EmitCFIRegister(), llvm::MCStreamer::EmitCFISameValue(), llvm::MCStreamer::EmitCFIWindowSave(), llvm::MCCFIInstruction::getOffset(), llvm::MCCFIInstruction::getOperation(), llvm::MCCFIInstruction::getRegister(), llvm::MCCFIInstruction::getRegister2(), llvm_unreachable, llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaOffset, llvm::MCCFIInstruction::OpDefCfaRegister, llvm::MCCFIInstruction::OpOffset, llvm::MCCFIInstruction::OpRegister, llvm::MCCFIInstruction::OpSameValue, llvm::MCCFIInstruction::OpWindowSave, and OutStreamer.
void AsmPrinter::EmitConstantPool () virtual
Print to the current output stream assembly representations of the constants in the constant pool MCP. This is used to print out constants which have been "spilled to memory" by the code generator.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP. This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented in llvm::MipsAsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 1090 of file AsmPrinter.cpp.
References Align(), llvm::CallingConv::C, llvm::MachineConstantPoolEntry::ConstVal, EmitAlignment(), EmitGlobalConstant(), llvm::MCStreamer::EmitLabel(), EmitMachineConstantPoolValue(), llvm::MCStreamer::EmitZeros(), llvm::MachineConstantPoolEntry::getAlignment(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), GetCPISymbol(), llvm::TargetSubtargetInfo::getDataLayout(), getObjFileLowering(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::MachineConstantPoolEntry::getSectionKind(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineConstantPoolEntry::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::MCSymbol::isUndefined(), llvm::Log2_32(), llvm::MachineConstantPoolEntry::MachineCPVal, MF, OutStreamer, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MCStreamer::SwitchSection(), TM, and llvm::MachineConstantPoolEntry::Val.
Referenced by llvm::MipsAsmPrinter::EmitConstantPool(), and EmitFunctionHeader().
void AsmPrinter::EmitDwarfOpPiece (ByteStreamer & Streamer, unsigned SizeInBits, unsigned OffsetInBits = 0) const
Emit a dwarf register operation for describing
a small value occupying only part of a register or
a register representing only part of a value.
Definition at line 222 of file AsmPrinterDwarf.cpp.
References llvm::DwarfExpression::AddOpPiece().
void AsmPrinter::EmitDwarfRegOp (ByteStreamer & BS, const MachineLocation & MLoc, bool Indirect) const virtual
EmitDwarfRegOp - Emit dwarf register operation.
EmitDwarfRegOp - Emit a dwarf register operation.
Parameters
Indirect whether this is a register-indirect address
Definition at line 230 of file AsmPrinterDwarf.cpp.
References llvm::DwarfExpression::AddMachineRegPiece(), llvm::DwarfExpression::AddReg(), llvm::DwarfExpression::AddRegIndirect(), llvm::dwarf::DW_OP_nop, llvm::DebugLocDwarfExpression::EmitOp(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineLocation::getOffset(), llvm::MachineLocation::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineLocation::isIndirect(), and TM.
void AsmPrinter::EmitDwarfRegOpPiece (ByteStreamer & BS, const MachineLocation & MLoc, unsigned PieceSize = 0, unsigned PieceOffset = 0) const
Emit a partial DWARF register operation.
Parameters
MLoc the register
PieceSize size and
PieceOffset offset of the piece in bits, if this is one piece of an aggregate value.
If size and offset is zero an operation for the entire register is emitted: Some targets do not provide a DWARF register number for every register. If this is the case, this function will attempt to emit a DWARF register by emitting a piece of a super-register or by piecing together multiple subregisters that alias the register.
Definition at line 213 of file AsmPrinterDwarf.cpp.
References assert(), llvm::MachineLocation::getReg(), and llvm::MachineLocation::isReg().
void AsmPrinter::EmitEncodingByte (unsigned Val, const char * Desc = nullptr) const
Emit a .byte 42 directive that corresponds to an encoding. If verbose assembly output is enabled, we output comments describing the encoding. Desc is a string saying what the encoding is specifying (e.g. "LSDA").
EmitEncodingByte - Emit a .byte 42 directive that corresponds to an encoding. If verbose assembly output is enabled, we output comments describing the encoding. Desc is an optional string saying what the encoding is specifying (e.g. "LSDA").
Definition at line 132 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::AddComment(), DecodeDWARFEncoding(), llvm::MCStreamer::EmitIntValue(), isVerbose(), and OutStreamer.
Referenced by llvm::EHStreamer::emitExceptionTable().
virtual void llvm::AsmPrinter::EmitEndOfAsmFile (Module &) inline virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 264 of file AsmPrinter.h.
Referenced by doFinalization().
void AsmPrinter::emitFrameAlloc (const MachineInstr & MI)
Definition at line 751 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCStreamer::EmitAssignment(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMCSymbol(), llvm::MachineInstr::getOperand(), OutContext, and OutStreamer.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitFunctionBody ()
This method emits the body and trailer for a function.
EmitFunctionBody - This method emits the body and trailer for a function.
Definition at line 763 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCStreamer::AddComment(), llvm::TargetOpcode::CFI_INSTRUCTION, llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), llvm::MCContext::CreateTempSymbol(), CurrentFnSym, CurrentFnSymForSize, llvm::TargetOpcode::DBG_VALUE, llvm::TargetOpcode::EH_LABEL, EmitBasicBlockEnd(), EmitBasicBlockStart(), emitCFIInstruction(), emitComments(), emitDebugValueComment(), llvm::MCStreamer::EmitELFSize(), emitFrameAlloc(), EmitFunctionBodyEnd(), EmitFunctionBodyStart(), emitImplicitDef(), EmitInstruction(), llvm::MCStreamer::EmitInstruction(), EmitJumpTableInfo(), emitKill(), llvm::MCStreamer::EmitLabel(), llvm::MachineModuleInfo::EndFunction(), F(), llvm::TargetOpcode::FRAME_ALLOC, llvm::TargetOpcode::GC_LABEL, GetBlockAddressSymbol(), llvm::MCStreamer::GetCommentOS(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetInstrInfo::getNoopForMachoTarget(), llvm::MCInst::getOpcode(), llvm::TargetMachine::getSubtargetImpl(), getSubtargetInfo(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::MCAsmInfo::hasSubsectionsViaSymbols(), llvm::AArch64CC::HI, llvm::TargetOpcode::IMPLICIT_DEF, llvm::TargetOpcode::INLINEASM, llvm::MCSymbol::isDefined(), isVerbose(), llvm::TargetOpcode::KILL, MAI, MF, llvm::AArch64CC::MI, MMI, OutContext, OutStreamer, T, llvm::TimePassesIsEnabled, and TM.
Referenced by llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and runOnMachineFunction().
virtual void llvm::AsmPrinter::EmitFunctionBodyEnd () inline virtual
Targets can override this to emit stuff after the last basic block in the function.
Reimplemented in llvm::MipsAsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 272 of file AsmPrinter.h.
Referenced by EmitFunctionBody().
virtual void llvm::AsmPrinter::EmitFunctionBodyStart () inline virtual
Targets can override this to emit stuff before the first basic block in the function.
Reimplemented in llvm::MipsAsmPrinter.
Definition at line 268 of file AsmPrinter.h.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitFunctionEntryLabel () virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function. This can be overridden by targets as required to do custom stuff.
Reimplemented in llvm::MipsAsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 561 of file AsmPrinter.cpp.
References CurrentFnSym, llvm::MCStreamer::EmitLabel(), llvm::MCSymbol::getName(), llvm::MCSymbol::isDefined(), llvm::MCSymbol::isVariable(), OutStreamer, llvm::MCSymbol::redefineIfPossible(), and llvm::report_fatal_error().
Referenced by EmitFunctionHeader().
void AsmPrinter::EmitFunctionHeader ()
This method emits the header for the current function.
EmitFunctionHeader - This method emits the header for the current function.
Definition at line 507 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddComment(), CurrentFnSym, EmitAlignment(), EmitConstantPool(), EmitFunctionEntryLabel(), EmitGlobalConstant(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolAttribute(), F(), llvm::MachineFunction::getAlignment(), llvm::MCStreamer::GetCommentOS(), llvm::MachineFunction::getFunction(), getObjFileLowering(), llvm::GlobalValue::getParent(), llvm::Function::getPrefixData(), llvm::Function::getPrologueData(), llvm::GlobalValue::getVisibility(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::Function::hasPrefixData(), llvm::Function::hasPrologueData(), llvm::AArch64CC::HI, isVerbose(), MAI, Mang, llvm::MCSA_ELF_TypeFunction, MF, MMI, OutStreamer, llvm::Value::printAsOperand(), llvm::MCStreamer::SwitchSection(), T, llvm::MachineModuleInfo::takeDeletedSymbolsForFunction(), llvm::TimePassesIsEnabled, and TM.
Referenced by llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and runOnMachineFunction().
void AsmPrinter::EmitGlobalConstant (const Constant * CV)
Print a general LLVM constant to the .s file.
EmitGlobalConstant - Print a general LLVM constant to the .s file.
Definition at line 2044 of file AsmPrinter.cpp.
References emitGlobalConstantImpl(), llvm::MCStreamer::EmitIntValue(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::TargetMachine::getSubtargetImpl(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::MCAsmInfo::hasSubsectionsViaSymbols(), MAI, OutStreamer, and TM.
Referenced by EmitConstantPool(), EmitFunctionHeader(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), and EmitXXStructor().
void AsmPrinter::EmitGlobalVariable (const GlobalVariable * GV) virtual
Emit the specified global variable to the .s file.
EmitGlobalVariable - Emit the specified global variable to the .s file.
Definition at line 334 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), Align(), llvm::MCConstantExpr::Create(), DL, EmitAlignment(), llvm::MCStreamer::EmitCommonSymbol(), llvm::MCStreamer::EmitELFSize(), EmitGlobalConstant(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitLocalCommonSymbol(), EmitSpecialLLVMGlobal(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitTBSSSymbol(), llvm::MCStreamer::EmitZerofill(), llvm::MCObjectFileInfo::getCommDirectiveSupportsAlignment(), llvm::MCStreamer::GetCommentOS(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::SequentialType::getElementType(), GetExternalSymbolSymbol(), getGVAlignmentLog2(), llvm::GlobalVariable::getInitializer(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MCAsmInfo::getLCOMMDirectiveAlignmentType(), llvm::MCSymbol::getName(), getObjFileLowering(), llvm::MCContext::GetOrCreateSymbol(), llvm::GlobalValue::getParent(), llvm::DataLayout::getPointerTypeSize(), llvm::TargetMachine::getSubtargetImpl(), getSymbol(), llvm::MCObjectFileInfo::getTLSBSSSection(), llvm::MCObjectFileInfo::getTLSExtraDataSection(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::GlobalValue::getVisibility(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::GlobalVariable::hasInitializer(), llvm::MCAsmInfo::hasMachoTBSSDirective(), llvm::MCAsmInfo::hasMachoZeroFillDirective(), llvm::AArch64CC::HI, llvm::SectionKind::isBSSExtern(), llvm::SectionKind::isBSSLocal(), llvm::SectionKind::isCommon(), llvm::GlobalValue::isDeclaration(), llvm::MCSymbol::isDefined(), llvm::SectionKind::isThreadBSS(), llvm::SectionKind::isThreadData(), llvm::SectionKind::isThreadLocal(), llvm::MCSymbol::isVariable(), isVerbose(), MAI, Mang, llvm::MCSA_ELF_TypeObject, llvm::MCSA_Global, llvm::MCSA_Local, llvm::LCOMM::NoAlignment, OutContext, OutStreamer, llvm::Value::printAsOperand(), llvm::MCSymbol::redefineIfPossible(), llvm::report_fatal_error(), llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::MCStreamer::SwitchSection(), T, llvm::TimePassesIsEnabled, and TM.
Referenced by doFinalization().
void AsmPrinter::emitImplicitDef (const MachineInstr * MI) const virtual
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
emitImplicitDef - This method emits the specified machine instruction that is an implicit def.
Definition at line 618 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCStreamer::AddComment(), llvm::MCRegisterInfo::getName(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetMachine::getSubtargetImpl(), OutStreamer, and TM.
Referenced by EmitFunctionBody().
void AsmPrinter::emitInlineAsmEnd (const MCSubtargetInfo & StartInfo, const MCSubtargetInfo * EndInfo) const virtual
Let the target do anything it needs to do after emitting inlineasm. This callback can be used restore the original mode in case the inlineasm contains directives to switch modes. StartInfo - the original subtarget info before inline asm EndInfo - the final subtarget info after parsing the inline asm, or NULL if the value is unknown.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 574 of file AsmPrinterInlineAsm.cpp.
void AsmPrinter::emitInlineAsmStart (const MCSubtargetInfo & StartInfo) const virtual
Let the target do anything it needs to do before emitting inlineasm. StartInfo - the subtarget info before parsing inline asm
Definition at line 572 of file AsmPrinterInlineAsm.cpp.
virtual void llvm::AsmPrinter::EmitInstruction (const MachineInstr *) inline virtual
Targets should implement this to emit instructions.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::HexagonAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 278 of file AsmPrinter.h.
References llvm_unreachable.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitInt16 (int Value) const
Emit a short directive and value.
EmitInt16 - Emit a short directive and value.
Definition at line 1480 of file AsmPrinter.cpp.
References llvm::MCStreamer::EmitIntValue(), and OutStreamer.
Referenced by llvm::DwarfUnit::emitHeader(), llvm::DIELoc::EmitValue(), and llvm::DIEBlock::EmitValue().
void AsmPrinter::EmitInt32 (int Value) const
Emit a long directive and value.
EmitInt32 - Emit a long directive and value.
Definition at line 1486 of file AsmPrinter.cpp.
References llvm::MCStreamer::EmitIntValue(), and OutStreamer.
Referenced by llvm::DwarfUnit::emitHeader(), llvm::DIEEntry::EmitValue(), llvm::DIELoc::EmitValue(), llvm::DIEBlock::EmitValue(), and llvm::WinCodeViewLineTables::endModule().
void AsmPrinter::EmitInt8 (int Value) const
Emit a byte directive and value.
EmitInt8 - Emit a byte directive and value.
Definition at line 1474 of file AsmPrinter.cpp.
References llvm::MCStreamer::EmitIntValue(), and OutStreamer.
Referenced by llvm::DwarfUnit::emitHeader(), llvm::APByteStreamer::EmitInt8(), llvm::DIELoc::EmitValue(), llvm::DIEBlock::EmitValue(), and llvm::WinCodeViewLineTables::endModule().
void AsmPrinter::EmitJumpTableInfo ()
Print assembly representations of the jump tables used by the current function to the current output stream.
EmitJumpTableInfo - Print assembly representations of the jump tables used by the current function to the current output stream.
emit a .set directive for each unique entry.
Definition at line 1171 of file AsmPrinter.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), DL, llvm::MCAsmInfo::doesSetDirectiveSuppressesReloc(), llvm::MachineJumpTableInfo::EK_Inline, llvm::MachineJumpTableInfo::EK_LabelDifference32, EmitAlignment(), llvm::MCStreamer::EmitAssignment(), llvm::MCStreamer::EmitDataRegion(), llvm::MCStreamer::EmitLabel(), F(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::MachineJumpTableInfo::getEntryAlignment(), llvm::MachineJumpTableInfo::getEntryKind(), llvm::MachineFunction::getFunction(), GetJTISymbol(), GetJTSetSymbol(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineBasicBlock::getNumber(), getObjFileLowering(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::SectionKind::getReadOnly(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineBasicBlock::getSymbol(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::DataLayout::hasLinkerPrivateGlobalPrefix(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::GlobalValue::isWeakForLinker(), llvm::Log2_32(), MAI, Mang, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT32, MF, OutContext, OutStreamer, llvm::MCStreamer::SwitchSection(), and TM.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitLabelDifference (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels. This implicitly uses .set if it is available.
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels. This implicitly uses .set if it avoids relocations.
Definition at line 1493 of file AsmPrinter.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), llvm::MCAsmInfo::doesSetDirectiveSuppressesReloc(), llvm::MCStreamer::EmitAssignment(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitValue(), GetTempSymbol(), MAI, OutContext, and OutStreamer.
Referenced by llvm::EHStreamer::emitExceptionTable(), EmitSectionOffset(), llvm::DIEDelta::EmitValue(), and llvm::DIELocList::EmitValue().
void AsmPrinter::EmitLabelPlusOffset (const MCSymbol * Label, uint64_t Offset, unsigned Size, bool IsSectionRelative = false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label. This implicitly uses .set if it is available.
EmitLabelPlusOffset - Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label. This implicitly uses .set if it is available.
Definition at line 1515 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCStreamer::EmitCOFFSecRel32(), llvm::MCStreamer::EmitValue(), MAI, llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), OutContext, and OutStreamer.
Referenced by EmitLabelReference(), and llvm::DIEEntry::EmitValue().
void llvm::AsmPrinter::EmitLabelReference (const MCSymbol * Label, unsigned Size, bool IsSectionRelative = false) const inline
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
Definition at line 367 of file AsmPrinter.h.
References EmitLabelPlusOffset().
Referenced by llvm::DIELabel::EmitValue().
void AsmPrinter::EmitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) virtual
Reimplemented in llvm::ARMAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 2056 of file AsmPrinter.cpp.
References llvm_unreachable.
Referenced by EmitConstantPool(), and llvm::MipsAsmPrinter::EmitInstruction().
void AsmPrinter::EmitSectionOffset (const MCSymbol * Label, const MCSymbol * SectionLabel) const
Emit the 4-byte offset of Label from the start of its section. This can be done with a special directive if the target supports it (e.g. cygwin) or by emitting it as an offset from a label at the start of the section.
SectionLabel is a temporary label emitted at the start of the section that Label lives in.
EmitSectionOffset - Emit the 4-byte offset of Label from the start of its section. This can be done with a special directive if the target supports it (e.g. cygwin) or by emitting it as an offset from a label at the start of the section.
SectionLabel is a temporary label emitted at the start of the section that Label lives in.
Definition at line 182 of file AsmPrinterDwarf.cpp.
References assert(), llvm::MCStreamer::EmitCOFFSecRel32(), EmitLabelDifference(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCSymbol::getSection(), llvm::MCSection::isBaseAddressKnownZero(), llvm::MCSymbol::isInSection(), MAI, llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), OutStreamer, and llvm::ARMBuildAttrs::Section.
Referenced by llvm::DwarfUnit::emitHeader(), and llvm::DIELocList::EmitValue().
void AsmPrinter::EmitSLEB128 (int64_t Value, const char * Desc = nullptr) const
Emit the specified signed leb128 value.
EmitSLEB128 - emit the specified signed leb128 value.
Definition at line 59 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCStreamer::EmitSLEB128IntValue(), isVerbose(), and OutStreamer.
Referenced by llvm::EHStreamer::emitExceptionTable(), llvm::APByteStreamer::EmitSLEB128(), and llvm::DIEInteger::EmitValue().
bool AsmPrinter::EmitSpecialLLVMGlobal (const GlobalVariable * GV)
Check to see if the specified global is a special global used by LLVM. If so, emit it and return true, otherwise do nothing and return false.
EmitSpecialLLVMGlobal - Check to see if the specified global is a special global used by LLVM. If so, emit it and return true, otherwise do nothing and return false.
Definition at line 1325 of file AsmPrinter.cpp.
References assert(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::GlobalVariable::getInitializer(), llvm::Value::getName(), llvm::MCContext::GetOrCreateSymbol(), llvm::TargetMachine::getRelocationModel(), llvm::GlobalObject::getSection(), llvm::GlobalValue::hasAppendingLinkage(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalVariable::hasInitializer(), llvm::MCAsmInfo::hasNoDeadStrip(), llvm::MCAsmInfo::hasStaticCtorDtorReferenceInStaticMode(), MAI, llvm::MCSA_Reference, OutContext, OutStreamer, llvm::Reloc::Static, and TM.
Referenced by EmitGlobalVariable().
virtual void llvm::AsmPrinter::EmitStartOfAsmFile (Module &) inline virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 260 of file AsmPrinter.h.
Referenced by doInitialization().
void AsmPrinter::EmitToStreamer (MCStreamer & S, const MCInst & Inst)
Definition at line 144 of file AsmPrinter.cpp.
References llvm::MCStreamer::EmitInstruction(), and getSubtargetInfo().
Referenced by llvm::SystemZAsmPrinter::EmitInstruction(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJump2Table(), and llvm::ARMAsmPrinter::runOnMachineFunction().
void AsmPrinter::EmitTTypeReference (const GlobalValue * GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
Definition at line 163 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitValue(), getObjFileLowering(), GetSizeOfEncodedValue(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), Mang, MMI, OutStreamer, and TM.
Referenced by llvm::EHStreamer::emitTypeInfos().
void AsmPrinter::EmitULEB128 (uint64_t Value, const char * Desc = nullptr, unsigned PadTo = 0) const
Emit the specified unsigned leb128 value.
EmitULEB128 - emit the specified signed leb128 value.
Definition at line 67 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCStreamer::EmitULEB128IntValue(), isVerbose(), and OutStreamer.
Referenced by llvm::DIEAbbrev::Emit(), llvm::DwarfFile::emitAbbrevs(), llvm::EHStreamer::emitExceptionTable(), llvm::EHStreamer::emitTypeInfos(), llvm::APByteStreamer::EmitULEB128(), llvm::DIEInteger::EmitValue(), llvm::DIELoc::EmitValue(), and llvm::DIEBlock::EmitValue().
virtual void llvm::AsmPrinter::EmitXXStructor (const Constant * CV) inline virtual
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 291 of file AsmPrinter.h.
References EmitGlobalConstant().
void AsmPrinter::getAnalysisUsage (AnalysisUsage & AU) const override virtual
Record analysis usage.
Reimplemented from llvm::Pass.
Definition at line 159 of file AsmPrinter.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), isVerbose(), and llvm::AnalysisUsage::setPreservesAll().
MCSymbol * AsmPrinter::GetBlockAddressSymbol (const BlockAddress * BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
Definition at line 2089 of file AsmPrinter.cpp.
References llvm::MachineModuleInfo::getAddrLabelSymbol(), llvm::BlockAddress::getBasicBlock(), and MMI.
Referenced by EmitFunctionBody(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::MSP430MCInstLower::GetBlockAddressSymbol(), llvm::SystemZMCInstLower::getExpr(), llvm::HexagonLowerToMC(), lowerConstant(), llvm::AArch64MCInstLower::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), LowerSymbolOperand(), and llvm::MipsAsmPrinter::printOperand().
MCSymbol * AsmPrinter::GetBlockAddressSymbol (const BasicBlock * BB) const
Definition at line 2093 of file AsmPrinter.cpp.
References llvm::MachineModuleInfo::getAddrLabelSymbol(), and MMI.
MCSymbol * AsmPrinter::GetCPISymbol (unsigned CPID) const virtual
Return the symbol for the specified constant pool entry.
GetCPISymbol - Return the symbol for the specified constant pool entry.
Reimplemented in llvm::X86AsmPrinter.
Definition at line 2098 of file AsmPrinter.cpp.
References llvm::TargetSubtargetInfo::getDataLayout(), getFunctionNumber(), llvm::MCContext::GetOrCreateSymbol(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::TargetMachine::getSubtargetImpl(), OutContext, and TM.
Referenced by EmitConstantPool(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::GetCPISymbol(), llvm::SystemZMCInstLower::getExpr(), llvm::HexagonLowerToMC(), llvm::AArch64MCInstLower::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), LowerSymbolOperand(), llvm::HexagonAsmPrinter::printOperand(), and llvm::ARMAsmPrinter::printOperand().
const MCSection * AsmPrinter::getCurrentSection () const
Return the current section we are emitting to.
getCurrentSection() - Return the current section we are emitting to.
Definition at line 153 of file AsmPrinter.cpp.
References llvm::MCStreamer::getCurrentSection(), and OutStreamer.
Referenced by EmitAlignment().
const DataLayout & AsmPrinter::getDataLayout () const
Return information about data layout.
getDataLayout - Return information about data layout.
Definition at line 136 of file AsmPrinter.cpp.
References llvm::TargetSubtargetInfo::getDataLayout(), llvm::TargetMachine::getSubtargetImpl(), and TM.
Referenced by llvm::DwarfUnit::addConstantFPValue(), llvm::DwarfUnit::addConstantValue(), llvm::AddressPool::emit(), llvm::EHStreamer::emitExceptionTable(), llvm::DwarfUnit::emitHeader(), llvm::DIEInteger::EmitValue(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DIEEntry::getRefAddrSize(), llvm::DIEInteger::SizeOf(), llvm::DIEExpr::SizeOf(), llvm::DIELabel::SizeOf(), llvm::DIEDelta::SizeOf(), and llvm::DIELocList::SizeOf().
DwarfDebug* llvm::AsmPrinter::getDwarfDebug () inline
Definition at line 135 of file AsmPrinter.h.
Referenced by llvm::DIEEntry::EmitValue(), llvm::DIELocList::EmitValue(), llvm::DwarfExpression::getDwarfVersion(), and llvm::DIEEntry::getRefAddrSize().
DwarfDebug* llvm::AsmPrinter::getDwarfDebug () const inline
Definition at line 136 of file AsmPrinter.h.
MCSymbol * AsmPrinter::GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
GetExternalSymbolSymbol - Return the MCSymbol for the specified ExternalSymbol.
Definition at line 2127 of file AsmPrinter.cpp.
References llvm::Mangler::getNameWithPrefix(), llvm::MCContext::GetOrCreateSymbol(), Mang, OutContext, and llvm::SmallString< InternalLen >::str().
Referenced by doFinalization(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::SystemZMCInstLower::getExpr(), llvm::MSP430MCInstLower::GetExternalSymbolSymbol(), llvm::AArch64MCInstLower::GetExternalSymbolSymbol(), llvm::HexagonLowerToMC(), llvm::ARMAsmPrinter::lowerOperand(), and LowerSymbolOperand().
unsigned AsmPrinter::getFunctionNumber () const
Return a unique ID for the current function.
getFunctionNumber - Return a unique ID for the current function.
Definition at line 127 of file AsmPrinter.cpp.
References llvm::MachineFunction::getFunctionNumber(), and MF.
Referenced by llvm::Win64Exception::beginFunction(), llvm::DwarfCFIException::beginFunction(), llvm::ARMException::beginFunction(), emitBasicBlockLoopComments(), llvm::EHStreamer::emitExceptionTable(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::Win64Exception::endFunction(), llvm::DwarfCFIException::endFunction(), llvm::ARMException::endFunction(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), GetCPISymbol(), GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), llvm::MipsAsmPrinter::printOperand(), and PrintSpecial().
virtual unsigned llvm::AsmPrinter::getISAEncoding () inline virtual
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 407 of file AsmPrinter.h.
Referenced by llvm::DwarfUnit::applySubprogramAttributes().
MCSymbol * AsmPrinter::GetJTISymbol (unsigned JTID, bool isLinkerPrivate = false) const
Return the symbol for the specified jump table entry.
GetJTISymbol - Return the symbol for the specified jump table entry.
Definition at line 2106 of file AsmPrinter.cpp.
References llvm::MachineFunction::getJTISymbol(), MF, and OutContext.
Referenced by EmitJumpTableInfo(), llvm::SystemZMCInstLower::getExpr(), llvm::HexagonLowerToMC(), llvm::AArch64MCInstLower::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), and llvm::LowerPPCMachineInstrToMCInst().
MCSymbol * AsmPrinter::GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
GetJTSetSymbol - Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
Definition at line 2112 of file AsmPrinter.cpp.
References llvm::TargetSubtargetInfo::getDataLayout(), getFunctionNumber(), llvm::MCContext::GetOrCreateSymbol(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::TargetMachine::getSubtargetImpl(), OutContext, and TM.
Referenced by EmitJumpTableInfo().
void AsmPrinter::getNameWithPrefix (SmallVectorImpl< char > & Name, const GlobalValue * GV) const
Definition at line 324 of file AsmPrinter.cpp.
References llvm::TargetMachine::getNameWithPrefix(), Mang, and TM.
const TargetLoweringObjectFile & AsmPrinter::getObjFileLowering () const
Return information about object file lowering.
Definition at line 131 of file AsmPrinter.cpp.
References llvm::TargetLoweringBase::getObjFileLowering(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetSubtargetInfo::getTargetLowering(), and TM.
Referenced by llvm::Win64Exception::beginFunction(), llvm::DwarfCFIException::beginFunction(), doFinalization(), doInitialization(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::AddressPool::emit(), EmitConstantPool(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::AMDGPUAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), EmitFunctionHeader(), EmitGlobalVariable(), EmitJumpTableInfo(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), EmitTTypeReference(), llvm::DwarfCFIException::endModule(), llvm::WinCodeViewLineTables::endModule(), llvm::X86AsmPrinter::GetCPISymbol(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), getSymbolWithGlobalValueBase(), lowerConstant(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), and llvm::WinCodeViewLineTables::WinCodeViewLineTables().
unsigned AsmPrinter::GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
GetSizeOfEncodedValue - Return the size of the encoding in bytes.
Definition at line 145 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_omit, llvm::dwarf::DW_EH_PE_udata2, llvm::dwarf::DW_EH_PE_udata4, llvm::dwarf::DW_EH_PE_udata8, llvm::TargetSubtargetInfo::getDataLayout(), llvm::DataLayout::getPointerSize(), llvm::TargetMachine::getSubtargetImpl(), llvm_unreachable, and TM.
Referenced by llvm::EHStreamer::emitExceptionTable(), and EmitTTypeReference().
const MCSubtargetInfo & AsmPrinter::getSubtargetInfo () const
Return information about subtarget.
Definition at line 140 of file AsmPrinter.cpp.
References llvm::TargetMachine::getSubtarget(), and TM.
Referenced by doFinalization(), EmitFunctionBody(), llvm::X86AsmPrinter::EmitInstruction(), and EmitToStreamer().
MCSymbol * AsmPrinter::getSymbol (const GlobalValue * GV) const
Definition at line 329 of file AsmPrinter.cpp.
References llvm::TargetMachine::getSymbol(), Mang, and TM.
Referenced by doFinalization(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), EmitGlobalVariable(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMException::endFunction(), llvm::DwarfCFIException::endModule(), llvm::SystemZMCInstLower::getExpr(), llvm::MSP430MCInstLower::GetGlobalAddressSymbol(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), GetSymbolFromOperand(), llvm::HexagonLowerToMC(), lowerConstant(), LowerSymbolOperand(), llvm::HexagonAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printOperand(), printSymbolOperand(), and SetupMachineFunction().
MCSymbol * AsmPrinter::getSymbolWithGlobalValueBase (const GlobalValue * GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
Definition at line 2119 of file AsmPrinter.cpp.
References getObjFileLowering(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), Mang, and TM.
Referenced by printSymbolOperand().
StringRef AsmPrinter::getTargetTriple () const
Return the target triple string.
Definition at line 148 of file AsmPrinter.cpp.
References llvm::TargetMachine::getTargetTriple(), and TM.
Referenced by doFinalization(), and doInitialization().
MCSymbol * AsmPrinter::GetTempSymbol (Twine Name, unsigned ID) const
Return the MCSymbol corresponding to the assembler temporary label with the specified stem and unique ID.
GetTempSymbol - Return the MCSymbol corresponding to the assembler temporary label with the specified stem and unique ID.
Definition at line 2074 of file AsmPrinter.cpp.
References llvm::TargetSubtargetInfo::getDataLayout(), llvm::MCContext::GetOrCreateSymbol(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::TargetMachine::getSubtargetImpl(), OutContext, and TM.
Referenced by llvm::DwarfCompileUnit::addScopeRangeList(), llvm::Win64Exception::beginFunction(), llvm::DwarfCFIException::beginFunction(), llvm::ARMException::beginFunction(), llvm::EHStreamer::emitExceptionTable(), EmitLabelDifference(), emitSectionSym(), llvm::Win64Exception::endFunction(), llvm::DwarfCFIException::endFunction(), llvm::ARMException::endFunction(), llvm::DwarfAccelTable::FinalizeTable(), getEntry(), and llvm::DwarfCompileUnit::initSection().
MCSymbol * AsmPrinter::GetTempSymbol (Twine Name) const
Return an assembler temporary label with the specified stem.
GetTempSymbol - Return an assembler temporary label with the specified stem.
Definition at line 2082 of file AsmPrinter.cpp.
References llvm::TargetSubtargetInfo::getDataLayout(), llvm::MCContext::GetOrCreateSymbol(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::TargetMachine::getSubtargetImpl(), OutContext, and TM.
bool AsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const virtual
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented in llvm::MipsAsmPrinter, and llvm::HexagonAsmPrinter.
Definition at line 2266 of file AsmPrinter.cpp.
References llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::isLandingPad(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::AArch64CC::MI, OP, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::pred_size(), and llvm::MachineBasicBlock::terminators().
Referenced by EmitBasicBlockStart(), and llvm::HexagonAsmPrinter::isBlockOnlyReachableByFallthrough().
bool llvm::AsmPrinter::isVerbose () const inline
Return true if assembly output should contain comments.
Definition at line 140 of file AsmPrinter.h.
Referenced by EmitBasicBlockStart(), EmitCFAByte(), EmitEncodingByte(), EmitFunctionBody(), EmitFunctionHeader(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), EmitGlobalVariable(), EmitSLEB128(), EmitULEB128(), getAnalysisUsage(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and SetupMachineFunction().
const MCExpr * AsmPrinter::lowerConstant (const Constant * CV)
Lower the specified LLVM Constant to an MCExpr.
Definition at line 1560 of file AsmPrinter.cpp.
References llvm::Add, llvm::APIntOps::And(), llvm::CallingConv::C, llvm::ConstantFoldConstantExpression(), llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCBinaryExpr::CreateAnd(), llvm::MCBinaryExpr::CreateDiv(), llvm::MCBinaryExpr::CreateMod(), llvm::MCBinaryExpr::CreateMul(), llvm::MCBinaryExpr::CreateOr(), llvm::MCBinaryExpr::CreateShl(), llvm::MCBinaryExpr::CreateSub(), llvm::MCBinaryExpr::CreateXor(), llvm::dyn_cast(), GetBlockAddressSymbol(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::ConstantExpr::getIntegerCast(), llvm::DataLayout::getIntPtrType(), getObjFileLowering(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::APInt::getSExtValue(), llvm::TargetMachine::getSubtargetImpl(), getSymbol(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeAllocSizeInBits(), llvm::Constant::isNullValue(), llvm_unreachable, Mang, MF, llvm::APIntOps::Or(), OutContext, llvm::Value::printAsOperand(), llvm::report_fatal_error(), llvm::raw_string_ostream::str(), llvm::Sub, TM, and llvm::APIntOps::Xor().
Referenced by doFinalization(), and emitGlobalConstantImpl().
AsmPrinter::CFIMoveType AsmPrinter::needsCFIMoves ()
Definition at line 720 of file AsmPrinter.cpp.
References CFI_M_Debug, CFI_M_EH, CFI_M_None, llvm::DwarfCFI, llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFunction(), llvm::MachineModuleInfo::hasDebugInfo(), MAI, MF, MMI, and llvm::Function::needsUnwindTableEntry().
Referenced by llvm::DwarfCFIException::beginFunction(), llvm::ARMException::beginFunction(), and emitCFIInstruction().
bool AsmPrinter::needsSEHMoves ()
Definition at line 731 of file AsmPrinter.cpp.
References llvm::MachineFunction::getFunction(), MAI, MF, llvm::Function::needsUnwindTableEntry(), and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by llvm::Win64Exception::beginFunction().
bool AsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::ARMAsmPrinter, llvm::HexagonAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 565 of file AsmPrinterInlineAsm.cpp.
Referenced by EmitGCCInlineAsmStr(), and EmitMSInlineAsmStr().
bool AsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::ARMAsmPrinter, llvm::HexagonAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 539 of file AsmPrinterInlineAsm.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getType(), and llvm::MachineOperand::MO_Immediate.
Referenced by EmitGCCInlineAsmStr(), EmitMSInlineAsmStr(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::X86AsmPrinter::PrintAsmOperand(), and llvm::MipsAsmPrinter::PrintAsmOperand().
void AsmPrinter::printOffset (int64_t Offset, raw_ostream & OS) const
This is just convenient handler for printing offsets.
Definition at line 2061 of file AsmPrinter.cpp.
Referenced by llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), and printSymbolOperand().
void AsmPrinter::PrintSpecial (const MachineInstr * MI, raw_ostream & OS, const char * Code) const virtual
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself. This can be useful for portably encoding the comment character or other bits of target-specific knowledge into the asmstrings. The syntax used is ${:comment}. Targets can override this to add support for their own strange codes.
PrintSpecial - Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself. This can be useful for portably encoding the comment character or other bits of target-specific knowledge into the asmstrings. The syntax used is ${:comment}. Targets can override this to add support for their own strange codes.
Definition at line 509 of file AsmPrinterInlineAsm.cpp.
References DL, llvm::MCAsmInfo::getCommentString(), llvm::TargetSubtargetInfo::getDataLayout(), getFunctionNumber(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::TargetMachine::getSubtargetImpl(), MAI, llvm::AArch64CC::MI, llvm::report_fatal_error(), llvm::raw_string_ostream::str(), llvm::LibFunc::strcmp, and TM.
Referenced by EmitGCCInlineAsmStr().
bool llvm::AsmPrinter::runOnMachineFunction (MachineFunction & MF) inline override virtual
Emit the specified function out to the OutStreamer.
Implements llvm::MachineFunctionPass.
Reimplemented in llvm::X86AsmPrinter, llvm::MipsAsmPrinter, llvm::AMDGPUAsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 185 of file AsmPrinter.h.
References EmitFunctionBody(), EmitFunctionHeader(), and SetupMachineFunction().
Referenced by llvm::MipsAsmPrinter::runOnMachineFunction().
void AsmPrinter::SetupMachineFunction (MachineFunction & MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
Definition at line 1065 of file AsmPrinter.cpp.
References CurrentFnSym, CurrentFnSymForSize, llvm::MachineFunction::getFunction(), getSymbol(), isVerbose(), and MF.
Referenced by llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and runOnMachineFunction().
Member Data Documentation
MCSymbol* llvm::AsmPrinter::CurrentFnSym
The symbol for the current function. This is recalculated at the beginning of each call to runOnMachineFunction().
Definition at line 95 of file AsmPrinter.h.
Referenced by AsmPrinter(), llvm::Win64Exception::beginFunction(), EmitFunctionBody(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::ARMAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), EmitFunctionEntryLabel(), EmitFunctionHeader(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and SetupMachineFunction().
MCSymbol* llvm::AsmPrinter::CurrentFnSymForSize
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g. using the .size directive). By default, this is equal to CurrentFnSym.
Definition at line 100 of file AsmPrinter.h.
Referenced by AsmPrinter(), EmitFunctionBody(), and SetupMachineFunction().
const MCAsmInfo* llvm::AsmPrinter::MAI
Target Asm Printer information.
Definition at line 70 of file AsmPrinter.h.
Referenced by llvm::DwarfUnit::addLocalString(), llvm::DwarfCompileUnit::addSectionLabel(), llvm::DwarfCFIException::beginFunction(), llvm::ARMException::beginFunction(), llvm::EHStreamer::computeCallSiteTable(), doFinalization(), doInitialization(), emitCFIInstruction(), llvm::EHStreamer::emitExceptionTable(), EmitFunctionBody(), EmitFunctionHeader(), EmitGlobalConstant(), EmitGlobalVariable(), EmitJumpTableInfo(), EmitLabelDifference(), EmitLabelPlusOffset(), EmitSectionOffset(), EmitSpecialLLVMGlobal(), llvm::DIEEntry::EmitValue(), llvm::DIELocList::EmitValue(), llvm::ARMException::endFunction(), llvm::DwarfCFIException::endModule(), needsCFIMoves(), needsSEHMoves(), and PrintSpecial().
Mangler* llvm::AsmPrinter::Mang
Name-mangler for global names.
Definition at line 90 of file AsmPrinter.h.
Referenced by llvm::Win64Exception::beginFunction(), llvm::DwarfCFIException::beginFunction(), doFinalization(), doInitialization(), llvm::NVPTXAsmPrinter::doInitialization(), EmitCamlGlobal(), EmitFunctionHeader(), EmitGlobalVariable(), EmitJumpTableInfo(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), EmitTTypeReference(), GetExternalSymbolSymbol(), getNameWithPrefix(), getSymbol(), GetSymbolFromOperand(), getSymbolWithGlobalValueBase(), and lowerConstant().
const MachineFunction* llvm::AsmPrinter::MF
The current machine function.
Definition at line 83 of file AsmPrinter.h.
Referenced by AsmPrinter(), llvm::WinCodeViewLineTables::beginInstruction(), llvm::EHStreamer::computeCallSiteTable(), emitCFIInstruction(), EmitConstantPool(), emitDebugValueComment(), llvm::MipsAsmPrinter::emitFrameDirective(), EmitFunctionBody(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), EmitFunctionHeader(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJump2Table(), llvm::ARMAsmPrinter::EmitJumpTable(), EmitJumpTableInfo(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::ARMException::endFunction(), llvm::X86AsmPrinter::GetCPISymbol(), getFunctionNumber(), GetJTISymbol(), llvm::DIEDwarfExpression::isFrameRegister(), lowerConstant(), needsCFIMoves(), needsSEHMoves(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), printSymbolOperand(), SetupMachineFunction(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
const MCInstrInfo* llvm::AsmPrinter::MII
Definition at line 72 of file AsmPrinter.h.
Referenced by llvm::HexagonAsmPrinter::EmitInstruction().
MachineModuleInfo* llvm::AsmPrinter::MMI
This is a pointer to the current MachineModuleInfo.
Definition at line 86 of file AsmPrinter.h.
Referenced by AsmPrinter(), llvm::WinCodeViewLineTables::beginFunction(), doFinalization(), doInitialization(), llvm::NVPTXAsmPrinter::doInitialization(), EmitBasicBlockStart(), emitCFIInstruction(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), EmitFunctionBody(), EmitFunctionHeader(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), EmitTTypeReference(), GetBlockAddressSymbol(), getMachOMMI(), needsCFIMoves(), printSymbolOperand(), and llvm::WinCodeViewLineTables::WinCodeViewLineTables().
MCContext& llvm::AsmPrinter::OutContext
This is the context for the output file that we are streaming. This owns all of the global MC-related objects for the generated translation unit.
Definition at line 75 of file AsmPrinter.h.
Referenced by llvm::DwarfCFIException::beginFunction(), doFinalization(), doInitialization(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::AddressPool::emit(), EmitCamlGlobal(), llvm::AMDGPUAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), emitFrameAlloc(), EmitFunctionBody(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJump2Table(), llvm::ARMAsmPrinter::EmitJumpTable(), EmitJumpTableInfo(), EmitLabelDifference(), EmitLabelPlusOffset(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::ARMAsmPrinter::EmitXXStructor(), GetCPISymbol(), GetExternalSymbolSymbol(), GetJTISymbol(), GetJTSetSymbol(), GetSymbolFromOperand(), GetSymbolRef(), GetTempSymbol(), llvm::HexagonLowerToMC(), lowerConstant(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), LowerSymbolOperand(), printSymbolOperand(), and llvm::MipsAsmPrinter::runOnMachineFunction().
MCStreamer& llvm::AsmPrinter::OutStreamer
This is the MCStreamer object for the file we are generating. This contains the transient state for the current translation unit that we are generating (such as the current section etc).
Definition at line 80 of file AsmPrinter.h.
Referenced by llvm::Win64Exception::beginFunction(), llvm::DwarfCFIException::beginFunction(), llvm::ARMException::beginFunction(), doFinalization(), doInitialization(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::DwarfDebug::DwarfDebug(), llvm::DwarfStringPool::emit(), llvm::AddressPool::emit(), llvm::DwarfFile::emitAbbrevs(), EmitAlignment(), emitBasicBlockLoopComments(), EmitBasicBlockStart(), EmitCamlGlobal(), EmitCFAByte(), emitCFIInstruction(), EmitConstantPool(), emitDebugValueComment(), EmitEncodingByte(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::AMDGPUAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), emitFrameAlloc(), EmitFunctionBody(), llvm::ARMAsmPrinter::EmitFunctionBodyEnd(), llvm::ARMAsmPrinter::EmitFunctionEntryLabel(), EmitFunctionEntryLabel(), EmitFunctionHeader(), EmitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), EmitGlobalVariable(), llvm::DwarfCompileUnit::emitHeader(), llvm::DwarfUnit::emitHeader(), llvm::DwarfTypeUnit::emitHeader(), emitImplicitDef(), llvm::ARMAsmPrinter::emitInlineAsmEnd(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::AMDGPUAsmPrinter::EmitInstruction(), EmitInt16(), EmitInt32(), llvm::APByteStreamer::EmitInt8(), EmitInt8(), llvm::ARMAsmPrinter::EmitJump2Table(), llvm::ARMAsmPrinter::EmitJumpTable(), EmitJumpTableInfo(), emitKill(), EmitLabelDifference(), EmitLabelPlusOffset(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), EmitSectionOffset(), emitSectionSym(), llvm::APByteStreamer::EmitSLEB128(), EmitSLEB128(), EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), EmitTTypeReference(), llvm::EHStreamer::emitTypeInfos(), llvm::APByteStreamer::EmitULEB128(), EmitULEB128(), llvm::DwarfFile::emitUnits(), llvm::DIEInteger::EmitValue(), llvm::DIEExpr::EmitValue(), llvm::DIEEntry::EmitValue(), llvm::DIETypeSignature::EmitValue(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::Win64Exception::endFunction(), llvm::DwarfCFIException::endFunction(), llvm::ARMException::endFunction(), llvm::WinCodeViewLineTables::endFunction(), llvm::DwarfCFIException::endModule(), llvm::ARMException::endModule(), llvm::WinCodeViewLineTables::endModule(), llvm::X86AsmPrinter::GetCPISymbol(), getCurrentSection(), llvm::DwarfCompileUnit::getOrCreateSourceID(), llvm::DwarfCompileUnit::initStmtList(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), llvm::StackMaps::serializeToStackMapSection(), and ~AsmPrinter().
TargetMachine& llvm::AsmPrinter::TM
Target machine description.
Definition at line 66 of file AsmPrinter.h.
Referenced by llvm::Win64Exception::beginFunction(), llvm::DwarfCFIException::beginFunction(), doFinalization(), doInitialization(), llvm::DwarfDebug::DwarfDebug(), EmitAlignment(), EmitConstantPool(), emitDebugValueComment(), EmitDwarfRegOp(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::MipsAsmPrinter::emitFrameDirective(), EmitFunctionBody(), EmitFunctionHeader(), EmitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), EmitGlobalVariable(), emitImplicitDef(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJumpTable(), EmitJumpTableInfo(), emitKill(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), EmitTTypeReference(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::DwarfCFIException::endModule(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::X86AsmPrinter::GetCPISymbol(), GetCPISymbol(), getDataLayout(), GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), getNameWithPrefix(), getObjFileLowering(), GetSizeOfEncodedValue(), getSubtargetInfo(), getSymbol(), GetSymbolFromOperand(), getSymbolWithGlobalValueBase(), getTargetTriple(), GetTempSymbol(), llvm::DwarfExpression::getTRI(), lowerConstant(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), llvm::MipsAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), PrintSpecial(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::StackMaps::serializeToStackMapSection(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
The documentation for this class was generated from the following files:
AsmPrinter.h
AsmPrinter.cpp
AsmPrinterDwarf.cpp
AsmPrinterInlineAsm.cpp