LLVM: llvm::SDNodeIterator Class Reference
LLVM API Documentation
llvm::SDNodeIterator Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
bool operator== (const SDNodeIterator &x) const
bool operator!= (const SDNodeIterator &x) const
const SDNodeIterator & operator= (const SDNodeIterator &I)
pointer operator* () const
pointer operator-> () const
SDNodeIterator & operator++ ()
SDNodeIterator operator++ (int)
size_t operator- (SDNodeIterator Other) const
unsigned getOperand () const
const SDNode * getNode () const
Static Public Member Functions
static SDNodeIterator begin (const SDNode *N)
static SDNodeIterator end (const SDNode *N)
Detailed Description
Definition at line 2055 of file SelectionDAGNodes.h.
Member Function Documentation
static SDNodeIterator llvm::SDNodeIterator::begin (const SDNode * N) inline static
Definition at line 2091 of file SelectionDAGNodes.h.
Referenced by llvm::GraphTraits< SDNode * >::child_begin(), llvm::DOTGraphTraits< SelectionDAG * >::getEdgeSourceLabel(), and llvm::DOTGraphTraits< SelectionDAG * >::getEdgeTarget().
static SDNodeIterator llvm::SDNodeIterator::end (const SDNode * N) inline static
Definition at line 2092 of file SelectionDAGNodes.h.
References llvm::SDNode::getNumOperands().
Referenced by llvm::GraphTraits< SDNode * >::child_end().
const SDNode* llvm::SDNodeIterator::getNode () const inline
Definition at line 2097 of file SelectionDAGNodes.h.
References llvm::FoldingSetImpl::Node::Node().
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::getEdgeTarget().
unsigned llvm::SDNodeIterator::getOperand () const inline
Definition at line 2096 of file SelectionDAGNodes.h.
bool llvm::SDNodeIterator::operator!= (const SDNodeIterator & x) const inline
Definition at line 2065 of file SelectionDAGNodes.h.
References llvm::operator==().
pointer llvm::SDNodeIterator::operator* () const inline
Definition at line 2073 of file SelectionDAGNodes.h.
References llvm::FoldingSetImpl::Node::Node().
SDNodeIterator& llvm::SDNodeIterator::operator++ () inline
Definition at line 2078 of file SelectionDAGNodes.h.
SDNodeIterator llvm::SDNodeIterator::operator++ (int) inline
Definition at line 2082 of file SelectionDAGNodes.h.
size_t llvm::SDNodeIterator::operator- (SDNodeIterator Other) const inline
Definition at line 2085 of file SelectionDAGNodes.h.
References assert(), and llvm::FoldingSetImpl::Node::Node().
pointer llvm::SDNodeIterator::operator-> () const inline
Definition at line 2076 of file SelectionDAGNodes.h.
References llvm::bfi_detail::operator*().
const SDNodeIterator& llvm::SDNodeIterator::operator= (const SDNodeIterator & I) inline
Definition at line 2067 of file SelectionDAGNodes.h.
References assert(), and llvm::FoldingSetImpl::Node::Node().
bool llvm::SDNodeIterator::operator== (const SDNodeIterator & x) const inline
Definition at line 2062 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h