LLVM: llvm::PBQP::MDMatrix< Metadata > Class Template Reference
LLVM API Documentation
llvm::PBQP::MDMatrix< Metadata > Class Template Reference
#include <Math.h>
Public Member Functions
MDMatrix (const Matrix &m)
MDMatrix (Matrix &&m)
const Metadata & getMetadata () const
Public Member Functions inherited from llvm::PBQP::Matrix
Matrix (unsigned Rows, unsigned Cols)
Construct a PBQP Matrix with the given dimensions.
Matrix (unsigned Rows, unsigned Cols, PBQPNum InitVal)
Construct a PBQP Matrix with the given dimensions and initial value.
Matrix (const Matrix &M)
Copy construct a PBQP matrix.
Matrix (Matrix &&M)
Move construct a PBQP matrix.
~Matrix ()
Destroy this matrix, return its memory.
Matrix & operator= (const Matrix &M)
Copy-assignment operator.
Matrix & operator= (Matrix &&M)
Move-assignment operator.
bool operator== (const Matrix &M) const
Comparison operator.
unsigned getRows () const
Return the number of rows in this matrix.
unsigned getCols () const
Return the number of cols in this matrix.
PBQPNum * operator[] (unsigned R)
Matrix element access.
const PBQPNum * operator[] (unsigned R) const
Matrix element access.
Vector getRowAsVector (unsigned R) const
Returns the given row as a vector.
Vector getColAsVector (unsigned C) const
Returns the given column as a vector.
Matrix & reset (PBQPNum Val=0)
Reset the matrix to the given value.
Matrix & setRow (unsigned R, PBQPNum Val)
Set a single row of this matrix to the given value.
Matrix & setCol (unsigned C, PBQPNum Val)
Set a single column of this matrix to the given value.
Matrix transpose () const
Matrix transpose.
Vector diagonalize () const
Returns the diagonal of the matrix as a vector.
Matrix & operator+= (const Matrix &M)
Add the given matrix to this one.
Matrix operator+ (const Matrix &M)
PBQPNum getRowMin (unsigned R) const
Returns the minimum of the given row.
PBQPNum getColMin (unsigned C) const
Returns the minimum of the given column.
Matrix & subFromRow (unsigned R, PBQPNum Val)
Subtracts the given scalar from the elements of the given row.
Matrix & subFromCol (unsigned C, PBQPNum Val)
Subtracts the given scalar from the elements of the given column.
bool isZero () const
Returns true if this is a zero matrix.
Detailed Description
template<typename Metadata>
class llvm::PBQP::MDMatrix< Metadata >
Definition at line 412 of file Math.h.
Constructor & Destructor Documentation
template<typename Metadata> llvm::PBQP::MDMatrix< Metadata >::MDMatrix (const Matrix & m) inline
Definition at line 414 of file Math.h.
template<typename Metadata> llvm::PBQP::MDMatrix< Metadata >::MDMatrix (Matrix && m) inline
Definition at line 415 of file Math.h.
Member Function Documentation
template<typename Metadata> const Metadata& llvm::PBQP::MDMatrix< Metadata >::getMetadata () const inline
Definition at line 416 of file Math.h.
Referenced by llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleDisconnectEdge(), llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleReconnectEdge(), and llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleSetEdgeCosts().
The documentation for this class was generated from the following file:
Math.h