LLVM: llvm::EdgeBundles Class Reference
LLVM API Documentation
llvm::EdgeBundles Class Reference
#include <EdgeBundles.h>
Public Member Functions
EdgeBundles ()
unsigned getBundle (unsigned N, bool Out) const
unsigned getNumBundles () const
getNumBundles - Return the total number of bundles in the CFG.
ArrayRef< unsigned > getBlocks (unsigned Bundle) const
getBlocks - Return an array of blocks that are connected to Bundle.
const MachineFunction * getMachineFunction () const
getMachineFunction - Return the last machine function computed.
void view () const
view - Visualize the annotated bipartite CFG with Graphviz.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 26 of file EdgeBundles.h.
Constructor & Destructor Documentation
llvm::EdgeBundles::EdgeBundles () inline
Definition at line 39 of file EdgeBundles.h.
Member Function Documentation
ArrayRef<unsigned> llvm::EdgeBundles::getBlocks (unsigned Bundle) const inline
getBlocks - Return an array of blocks that are connected to Bundle.
Definition at line 49 of file EdgeBundles.h.
unsigned llvm::EdgeBundles::getBundle (unsigned N, bool Out) const inline
getBundle - Return the ingoing (Out = false) or outgoing (Out = true) bundle number for basic block N
Definition at line 43 of file EdgeBundles.h.
Referenced by llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), and llvm::SpillPlacement::addPrefSpill().
const MachineFunction* llvm::EdgeBundles::getMachineFunction () const inline
getMachineFunction - Return the last machine function computed.
Definition at line 52 of file EdgeBundles.h.
unsigned llvm::EdgeBundles::getNumBundles () const inline
getNumBundles - Return the total number of bundles in the CFG.
Definition at line 46 of file EdgeBundles.h.
References llvm::IntEqClasses::getNumClasses().
Referenced by llvm::SpillPlacement::prepare().
void EdgeBundles::view () const
view - Visualize the annotated bipartite CFG with Graphviz.
Definition at line 95 of file EdgeBundles.cpp.
References llvm::ViewGraph().
Member Data Documentation
char EdgeBundles::ID = 0 static
Definition at line 38 of file EdgeBundles.h.
The documentation for this class was generated from the following files:
EdgeBundles.h
EdgeBundles.cpp