LLVM: llvm::StackProtector Class Reference
LLVM API Documentation
llvm::StackProtector Class Reference
#include <StackProtector.h>
Public Types
enum SSPLayoutKind { SSPLK_None, SSPLK_LargeArray, SSPLK_SmallArray, SSPLK_AddrOf }
typedef ValueMap< const
AllocaInst *, SSPLayoutKind > SSPLayoutMap
A mapping of AllocaInsts to their required SSP layout.
Public Member Functions
StackProtector ()
StackProtector (const TargetMachine *TM)
void getAnalysisUsage (AnalysisUsage &AU) const override
SSPLayoutKind getSSPLayout (const AllocaInst *AI) const
void adjustForColoring (const AllocaInst *From, const AllocaInst *To)
bool runOnFunction (Function &Fn) override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 32 of file StackProtector.h.
Member Typedef Documentation
typedef ValueMap<const AllocaInst *, SSPLayoutKind> llvm::StackProtector::SSPLayoutMap
A mapping of AllocaInsts to their required SSP layout.
Definition at line 48 of file StackProtector.h.
Member Enumeration Documentation
enum llvm::StackProtector::SSPLayoutKind
SSPLayoutKind. Stack Smashing Protection (SSP) rules require that vulnerable stack allocations are located close the stack protector.
Enumerator
SSPLK_None
Did not trigger a stack protector. No effect on data layout.
SSPLK_LargeArray
Array or nested array >= SSP-buffer-size. Closest to the stack protector.
SSPLK_SmallArray
Array or nested array < SSP-buffer-size. 2nd closest to the stack protector.
SSPLK_AddrOf
The address of this allocation is exposed and triggered protection. 3rd closest to the protector.
Definition at line 36 of file StackProtector.h.
Constructor & Destructor Documentation
llvm::StackProtector::StackProtector () inline
Definition at line 108 of file StackProtector.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeStackProtectorPass().
llvm::StackProtector::StackProtector (const TargetMachine * TM) inline
Definition at line 112 of file StackProtector.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeStackProtectorPass().
Member Function Documentation
void StackProtector::adjustForColoring (const AllocaInst * From, const AllocaInst * To)
Definition at line 64 of file StackProtector.cpp.
References llvm::ValueMap< KeyT, ValueT, Config >::end(), llvm::ValueMap< KeyT, ValueT, Config >::erase(), llvm::ValueMap< KeyT, ValueT, Config >::find(), I, llvm::ValueMap< KeyT, ValueT, Config >::insert(), llvm::ValueMapIterator< DenseMapT, KeyT >::ValueTypeProxy::second, SSPLK_AddrOf, and SSPLK_LargeArray.
void llvm::StackProtector::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 118 of file StackProtector.h.
References llvm::AnalysisUsage::addPreserved().
StackProtector::SSPLayoutKind StackProtector::getSSPLayout (const AllocaInst * AI) const
Definition at line 60 of file StackProtector.cpp.
References llvm::ValueMap< KeyT, ValueT, Config >::lookup(), and SSPLK_None.
bool StackProtector::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 85 of file StackProtector.cpp.
References llvm::AttributeSet::FunctionIndex, llvm::StringRef::getAsInteger(), llvm::AttributeSet::getAttribute(), llvm::Function::getAttributes(), llvm::DominatorTreeWrapperPass::getDomTree(), llvm::GlobalValue::getParent(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::Attribute::getValueAsString(), and llvm::Attribute::isStringAttribute().
Member Data Documentation
char StackProtector::ID = 0 static
Definition at line 107 of file StackProtector.h.
The documentation for this class was generated from the following files:
StackProtector.h
StackProtector.cpp