LLVM: llvm::PBQP::RegAlloc::RegAllocSolverImpl Class Reference
LLVM API Documentation
llvm::PBQP::RegAlloc::RegAllocSolverImpl Class Reference
#include <RegAllocPBQP.h>
Classes
struct EdgeMetadata
Public Types
typedef PBQP::Vector RawVector
typedef PBQP::Matrix RawMatrix
typedef PBQP::Vector Vector
typedef RAMatrix Matrix
typedef
PBQP::PoolCostAllocator
< Vector, Matrix > CostAllocator
typedef GraphBase::NodeId NodeId
typedef GraphBase::EdgeId EdgeId
typedef RegAlloc::NodeMetadata NodeMetadata
typedef RegAlloc::GraphMetadata GraphMetadata
typedef PBQP::Graph
< RegAllocSolverImpl > Graph
Public Member Functions
RegAllocSolverImpl (Graph &G)
Solution solve ()
void handleAddNode (NodeId NId)
void handleRemoveNode (NodeId NId)
void handleSetNodeCosts (NodeId NId, const Vector &newCosts)
void handleAddEdge (EdgeId EId)
void handleRemoveEdge (EdgeId EId)
void handleDisconnectEdge (EdgeId EId, NodeId NId)
void handleReconnectEdge (EdgeId EId, NodeId NId)
void handleSetEdgeCosts (EdgeId EId, const Matrix &NewCosts)
Detailed Description
Definition at line 281 of file RegAllocPBQP.h.
Member Typedef Documentation
typedef PBQP::PoolCostAllocator<Vector, Matrix> llvm::PBQP::RegAlloc::RegAllocSolverImpl::CostAllocator
Definition at line 289 of file RegAllocPBQP.h.
typedef GraphBase::EdgeId llvm::PBQP::RegAlloc::RegAllocSolverImpl::EdgeId
Definition at line 292 of file RegAllocPBQP.h.
typedef PBQP::Graph<RegAllocSolverImpl> llvm::PBQP::RegAlloc::RegAllocSolverImpl::Graph
Definition at line 298 of file RegAllocPBQP.h.
typedef RegAlloc::GraphMetadata llvm::PBQP::RegAlloc::RegAllocSolverImpl::GraphMetadata
Definition at line 296 of file RegAllocPBQP.h.
typedef RAMatrix llvm::PBQP::RegAlloc::RegAllocSolverImpl::Matrix
Definition at line 288 of file RegAllocPBQP.h.
typedef GraphBase::NodeId llvm::PBQP::RegAlloc::RegAllocSolverImpl::NodeId
Definition at line 291 of file RegAllocPBQP.h.
typedef RegAlloc::NodeMetadata llvm::PBQP::RegAlloc::RegAllocSolverImpl::NodeMetadata
Definition at line 294 of file RegAllocPBQP.h.
typedef PBQP::Matrix llvm::PBQP::RegAlloc::RegAllocSolverImpl::RawMatrix
Definition at line 286 of file RegAllocPBQP.h.
typedef PBQP::Vector llvm::PBQP::RegAlloc::RegAllocSolverImpl::RawVector
Definition at line 285 of file RegAllocPBQP.h.
typedef PBQP::Vector llvm::PBQP::RegAlloc::RegAllocSolverImpl::Vector
Definition at line 287 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
llvm::PBQP::RegAlloc::RegAllocSolverImpl::RegAllocSolverImpl (Graph & G) inline
Definition at line 300 of file RegAllocPBQP.h.
Member Function Documentation
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleAddEdge (EdgeId EId) inline
Definition at line 317 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeNode1Id(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), and handleReconnectEdge().
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleAddNode (NodeId NId) inline
Definition at line 311 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getNodeCosts(), llvm::PBQP::Graph< SolverT >::getNodeMetadata(), and llvm::PBQP::RegAlloc::NodeMetadata::setup().
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleDisconnectEdge (EdgeId EId, NodeId NId) inline
Definition at line 327 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeCosts(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), llvm::PBQP::MDMatrix< Metadata >::getMetadata(), llvm::PBQP::Graph< SolverT >::getNodeDegree(), llvm::PBQP::Graph< SolverT >::getNodeMetadata(), llvm::PBQP::RegAlloc::NodeMetadata::getReductionState(), llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge(), llvm::PBQP::RegAlloc::NodeMetadata::isConservativelyAllocatable(), and llvm::PBQP::RegAlloc::NodeMetadata::NotProvablyAllocatable.
Referenced by handleRemoveEdge().
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleReconnectEdge (EdgeId EId, NodeId NId) inline
Definition at line 342 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeCosts(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), llvm::PBQP::MDMatrix< Metadata >::getMetadata(), llvm::PBQP::Graph< SolverT >::getNodeMetadata(), and llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge().
Referenced by handleAddEdge().
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleRemoveEdge (EdgeId EId) inline
Definition at line 322 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeNode1Id(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), and handleDisconnectEdge().
Referenced by handleSetEdgeCosts().
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleRemoveNode (NodeId NId) inline
Definition at line 314 of file RegAllocPBQP.h.
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleSetEdgeCosts (EdgeId EId, const Matrix & NewCosts) inline
Definition at line 348 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeNode1Id(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), llvm::PBQP::MDMatrix< Metadata >::getMetadata(), llvm::PBQP::Graph< SolverT >::getNodeMetadata(), llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge(), and handleRemoveEdge().
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleSetNodeCosts (NodeId NId, const Vector & newCosts) inline
Definition at line 315 of file RegAllocPBQP.h.
Solution llvm::PBQP::RegAlloc::RegAllocSolverImpl::solve () inline
Definition at line 302 of file RegAllocPBQP.h.
References llvm::PBQP::backpropagate(), llvm::PBQP::Graph< SolverT >::setSolver(), and llvm::PBQP::Graph< SolverT >::unsetSolver().
Referenced by llvm::PBQP::RegAlloc::solve().
The documentation for this class was generated from the following file:
RegAllocPBQP.h