LLVM: llvm::LiveRangeCalc Class Reference
LLVM API Documentation
llvm::LiveRangeCalc Class Reference
#include <LiveRangeCalc.h>
Public Member Functions
LiveRangeCalc ()
void reset (const MachineFunction *MF, SlotIndexes *, MachineDominatorTree *, VNInfo::Allocator *)
void extend (LiveRange &LR, SlotIndex Kill, unsigned PhysReg=0)
void createDeadDefs (LiveRange &LR, unsigned Reg)
void extendToUses (LiveRange &LR, unsigned PhysReg)
void calculate (LiveInterval &LI)
void setLiveOutValue (MachineBasicBlock *MBB, VNInfo *VNI)
void addLiveInBlock (LiveRange &LR, MachineDomTreeNode *DomNode, SlotIndex Kill=SlotIndex())
void calculateValues ()
Detailed Description
Definition at line 36 of file LiveRangeCalc.h.
Constructor & Destructor Documentation
llvm::LiveRangeCalc::LiveRangeCalc () inline
Definition at line 138 of file LiveRangeCalc.h.
Member Function Documentation
void llvm::LiveRangeCalc::addLiveInBlock (LiveRange & LR, MachineDomTreeNode * DomNode, SlotIndex Kill = SlotIndex()) inline
addLiveInBlock - Add a block with an unknown live-in value. This function can only be called once per basic block. Once the live-in value has been determined, calculateValues() will add liveness to LI.
Parameters
LR The live range that is live-in to the block.
DomNode The domtree node for the block.
Kill Index in block where LI is killed. If the value is live-through, set Kill = SLotIndex() and also call setLiveOutValue(MBB, 0).
Definition at line 226 of file LiveRangeCalc.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void LiveRangeCalc::calculate (LiveInterval & LI)
Calculates liveness for the register specified in live interval LI. Creates subregister live ranges as needed if subreg liveness tracking is enabled.
Definition at line 56 of file LiveRangeCalc.cpp.
References assert(), llvm::LiveRange::clear(), llvm::LiveInterval::constructMainRangeFromSubranges(), createDeadDef(), llvm::LiveInterval::createSubRange(), llvm::LiveInterval::createSubRangeFrom(), llvm::LiveRange::empty(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::LiveInterval::hasSubRanges(), llvm::LiveInterval::SubRange::LaneMask, llvm::LiveInterval::reg, llvm::MachineRegisterInfo::reg_nodbg_operands(), llvm::LiveInterval::removeEmptySubRanges(), llvm::LiveInterval::subranges(), and llvm::MachineRegisterInfo::tracksSubRegLiveness().
void LiveRangeCalc::calculateValues ()
calculateValues - Calculate the value that will be live-in to each block added with addLiveInBlock. Add PHI-def values as needed to preserve SSA form. Add liveness to all live-in blocks up to the Kill point, or the whole block for live-through blocks.
Every predecessor of a live-in block must have been given a value with setLiveOutValue, the value may be null for live-trough blocks.
Definition at line 252 of file LiveRangeCalc.cpp.
References assert().
Referenced by extend().
void LiveRangeCalc::createDeadDefs (LiveRange & LR, unsigned Reg)
createDeadDefs - Create a dead def in LI for every def operand of Reg. Each instruction defining Reg gets a new VNInfo with a corresponding minimal live range.
Definition at line 134 of file LiveRangeCalc.cpp.
References assert(), createDeadDef(), and llvm::MachineRegisterInfo::def_operands().
void LiveRangeCalc::extend (LiveRange & LR, SlotIndex Kill, unsigned PhysReg = 0)
extend - Extend the live range of LI to reach Kill.
The existing values in LI must be live so they jointly dominate Kill. If Kill is not dominated by a single existing value, PHI-defs are inserted as required to preserve SSA form. If Kill is known to be dominated by a single existing value, Alloc may be null.
PhysReg, when set, is used to verify live-in lists on basic blocks.
Definition at line 225 of file LiveRangeCalc.cpp.
References assert(), calculateValues(), llvm::LiveRange::extendInBlock(), llvm::SlotIndexes::getMBBFromIndex(), llvm::SlotIndexes::getMBBStartIdx(), llvm::SlotIndex::getPrevSlot(), llvm::SlotIndex::isValid(), and llvm::RegState::Kill.
Referenced by llvm::LiveIntervals::extendToIndices().
void llvm::LiveRangeCalc::extendToUses (LiveRange & LR, unsigned PhysReg) inline
Extend the live range of LR to reach all uses of Reg.
All uses must be jointly dominated by existing liveness. PHI-defs are inserted as needed to preserve SSA form.
Definition at line 184 of file LiveRangeCalc.h.
void LiveRangeCalc::reset (const MachineFunction * MF, SlotIndexes * SI, MachineDominatorTree * MDT, VNInfo::Allocator * VNIA)
reset - Prepare caches for a new set of non-overlapping live ranges. The caches must be reset before attempting calculations with a live range that may overlap a previously computed live range, and before the first live range in a function. If live ranges are not known to be non-overlapping, call reset before each.
Definition at line 29 of file LiveRangeCalc.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::MachineFunction::getRegInfo(), and SI.
Referenced by llvm::LiveIntervals::extendToIndices(), and llvm::SplitEditor::reset().
void llvm::LiveRangeCalc::setLiveOutValue (MachineBasicBlock * MBB, VNInfo * VNI) inline
setLiveOutValue - Indicate that VNI is live out from MBB. The calculateValues() function will not add liveness for MBB, the caller should take care of that.
VNI may be null only if MBB is a live-through block also passed to addLiveInBlock().
Definition at line 212 of file LiveRangeCalc.h.
References llvm::MachineBasicBlock::getNumber(), and llvm::BitVector::set().
The documentation for this class was generated from the following files:
LiveRangeCalc.h
LiveRangeCalc.cpp