LLVM: llvm::StatepointOpers Class Reference
LLVM API Documentation
llvm::StatepointOpers Class Reference
#include <StackMaps.h>
Public Member Functions
StatepointOpers (const MachineInstr *MI)
unsigned getVarIdx () const
unsigned getNumVMSArgsIdx () const
unsigned getNumVMSArgs () const
const MachineOperand & getCallTarget () const
Returns the target of the underlying call.
Detailed Description
MI-level Statepoint operands
Statepoint operands take the form: <num call="" arguments>="">, <call target>="">, [call arguments], <StackMaps::ConstantOp>, <flags>, <StackMaps::ConstantOp>, <num other="" args>="">, [other args], [gc values]
Definition at line 91 of file StackMaps.h.
Constructor & Destructor Documentation
llvm::StatepointOpers::StatepointOpers (const MachineInstr * MI) inline explicit
Definition at line 99 of file StackMaps.h.
Member Function Documentation
const MachineOperand& llvm::StatepointOpers::getCallTarget () const inline
Returns the target of the underlying call.
Definition at line 122 of file StackMaps.h.
References llvm::MachineInstr::getOperand().
Referenced by LowerSTATEPOINT().
unsigned llvm::StatepointOpers::getNumVMSArgs () const inline
Returns the number of non-gc non-call arguments attached to the statepoint. Note that this is the number of arguments, not the number of operands required to represent those arguments.
Definition at line 117 of file StackMaps.h.
References llvm::MachineOperand::getImm(), getNumVMSArgsIdx(), and llvm::MachineInstr::getOperand().
unsigned llvm::StatepointOpers::getNumVMSArgsIdx () const inline
Returns the index of the operand containing the number of non-gc non-call arguments.
Definition at line 110 of file StackMaps.h.
References getVarIdx().
Referenced by getNumVMSArgs().
unsigned llvm::StatepointOpers::getVarIdx () const inline
Get starting index of non call related arguments (statepoint flags, vm state and gc state).
Definition at line 104 of file StackMaps.h.
References llvm::MachineOperand::getImm(), and llvm::MachineInstr::getOperand().
Referenced by getNumVMSArgsIdx().
The documentation for this class was generated from the following file:
StackMaps.h