LLVM: llvm::TypePrinting Class Reference
LLVM API Documentation
llvm::TypePrinting Class Reference
#include <AsmWriter.h>
Public Member Functions
TypePrinting ()
~TypePrinting ()
void incorporateTypes (const Module &M)
void print (Type *Ty, raw_ostream &OS)
void printStructBody (StructType *Ty, raw_ostream &OS)
Public Attributes
TypeFinder NamedTypes
NamedTypes - The named types that are used by the current module.
DenseMap< StructType *, unsigned > NumberedTypes
NumberedTypes - The numbered types, along with their value.
Detailed Description
Definition at line 44 of file AsmWriter.h.
Constructor & Destructor Documentation
llvm::TypePrinting::TypePrinting () inline
Definition at line 56 of file AsmWriter.h.
llvm::TypePrinting::~TypePrinting () inline
Definition at line 57 of file AsmWriter.h.
Member Function Documentation
void llvm::TypePrinting::incorporateTypes (const Module & M)
Definition at line 383 of file AsmWriter.cpp.
References llvm::TypeFinder::begin(), llvm::StringRef::empty(), llvm::TypeFinder::end(), llvm::TypeFinder::erase(), llvm::StructType::getName(), I, llvm::StructType::isLiteral(), NamedTypes, NumberedTypes, and llvm::TypeFinder::run().
Referenced by llvm::Metadata::printAsOperand(), and llvm::Value::printAsOperand().
void llvm::TypePrinting::print (Type * Ty, raw_ostream & OS)
CalcTypeName - Write the specified type to the specified raw_ostream, making use of type names or up references to shorten the type name where possible.
Definition at line 410 of file AsmWriter.cpp.
References llvm::Type::ArrayTyID, llvm::Type::DoubleTyID, llvm::StringRef::empty(), llvm::Type::FloatTyID, llvm::Type::FP128TyID, llvm::Type::FunctionTyID, llvm::PointerType::getAddressSpace(), getBitWidth(), llvm::SequentialType::getElementType(), llvm::StructType::getName(), llvm::ArrayType::getNumElements(), llvm::VectorType::getNumElements(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getReturnType(), llvm::Type::getTypeID(), llvm::Type::HalfTyID, I, llvm::Type::IntegerTyID, llvm::StructType::isLiteral(), llvm::FunctionType::isVarArg(), llvm::Type::LabelTyID, LocalPrefix, llvm::Type::MetadataTyID, NumberedTypes, llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::Type::PointerTyID, llvm::Type::PPC_FP128TyID, PrintLLVMName(), printStructBody(), llvm::Type::StructTyID, llvm::Type::VectorTyID, llvm::Type::VoidTyID, llvm::Type::X86_FP80TyID, and llvm::Type::X86_MMXTyID.
Referenced by llvm::Type::print(), llvm::Value::print(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printArgument(), llvm::Value::printAsOperand(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), llvm::AssemblyWriter::printInstruction(), llvm::WriteAsOperandInternal(), llvm::WriteConstantInternal(), llvm::AssemblyWriter::writeOperand(), and llvm::AssemblyWriter::writeParamOperand().
void llvm::TypePrinting::printStructBody (StructType * Ty, raw_ostream & OS)
Definition at line 485 of file AsmWriter.cpp.
Referenced by print(), llvm::Type::print(), and llvm::AssemblyWriter::printTypeIdentities().
Member Data Documentation
TypeFinder llvm::TypePrinting::NamedTypes
NamedTypes - The named types that are used by the current module.
Definition at line 50 of file AsmWriter.h.
Referenced by incorporateTypes(), and llvm::AssemblyWriter::printTypeIdentities().
DenseMap<StructType*, unsigned> llvm::TypePrinting::NumberedTypes
NumberedTypes - The numbered types, along with their value.
Definition at line 53 of file AsmWriter.h.
Referenced by incorporateTypes(), print(), and llvm::AssemblyWriter::printTypeIdentities().
The documentation for this class was generated from the following files:
AsmWriter.h
AsmWriter.cpp