LLVM: llvm::R600SchedStrategy Class Reference
LLVM API Documentation
llvm::R600SchedStrategy Class Reference
#include <R600MachineScheduler.h>
Public Member Functions
R600SchedStrategy ()
virtual ~R600SchedStrategy ()
void initialize (ScheduleDAGMI *dag) override
Initialize the strategy after building the DAG for a new region.
SUnit * pickNode (bool &IsTopNode) override
void schedNode (SUnit *SU, bool IsTopNode) override
void releaseTopNode (SUnit *SU) override
void releaseBottomNode (SUnit *SU) override
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual bool shouldTrackPressure () const
virtual void registerRoots ()
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
Detailed Description
Definition at line 27 of file R600MachineScheduler.h.
Constructor & Destructor Documentation
llvm::R600SchedStrategy::R600SchedStrategy () inline
Definition at line 70 of file R600MachineScheduler.h.
virtual llvm::R600SchedStrategy::~R600SchedStrategy () inline virtual
Definition at line 74 of file R600MachineScheduler.h.
Member Function Documentation
void R600SchedStrategy::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Definition at line 26 of file R600MachineScheduler.cpp.
References assert(), llvm::R600InstrInfo::getMaxAlusPerClause(), llvm::AMDGPUSubtarget::getTexVTXClauseSize(), llvm::ScheduleDAGMI::hasVRegLiveness(), and llvm::AArch64DB::ST.
SUnit * R600SchedStrategy::pickNode (bool & IsTopNode) override virtual
Pick the next node to schedule, or return NULL. Set IsTopNode to true to schedule the node at the top of the unscheduled region. Otherwise it will be scheduled at the bottom.
Implements llvm::MachineSchedStrategy.
Definition at line 58 of file R600MachineScheduler.cpp.
References llvm::dbgs(), DEBUG, llvm::SUnit::dump(), getWFCountLimitedByGPR(), llvm::SUnit::isScheduled, and llvm::ScheduleDAG::SUnits.
void R600SchedStrategy::releaseBottomNode (SUnit * SU) override virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 197 of file R600MachineScheduler.cpp.
References llvm::dbgs(), DEBUG, llvm::SUnit::dump(), llvm::SUnit::getInstr(), and isPhysicalRegCopy().
void R600SchedStrategy::releaseTopNode (SUnit * SU) override virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 193 of file R600MachineScheduler.cpp.
References llvm::dbgs(), DEBUG, and llvm::SUnit::dump().
void R600SchedStrategy::schedNode (SUnit * SU, bool IsTopNode) override virtual
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
Implements llvm::MachineSchedStrategy.
Definition at line 145 of file R600MachineScheduler.cpp.
References llvm::dbgs(), DEBUG, llvm::SUnit::getInstr(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::MachineInstr::operands_begin(), and llvm::MachineInstr::operands_end().
The documentation for this class was generated from the following files:
R600MachineScheduler.h
R600MachineScheduler.cpp