LLVM: llvm::CastInst Class Reference
LLVM API Documentation
llvm::CastInst Class Reference
Base class of casting instructions.
#include <InstrTypes.h>
Public Member Functions
bool isIntegerCast () const
Determine if this is an integer-only cast.
bool isLosslessCast () const
Determine if this is a lossless cast.
bool isNoopCast (Type *IntPtrTy) const
Determine if this cast is a no-op cast.
bool isNoopCast (const DataLayout *DL) const
Determine if this cast is a no-op cast.
Instruction::CastOps getOpcode () const
Return the opcode of this CastInst.
Type * getSrcTy () const
Return the source type, as a convenience.
Type * getDestTy () const
Return the destination type, as a convenience.
Public Member Functions inherited from llvm::UnaryInstruction
void * operator new (size_t s)
~UnaryInstruction ()
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Public Member Functions inherited from llvm::Instruction
~Instruction ()
Instruction * user_back ()
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const DataLayout * getDataLayout () const
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
void getAAMetadata (AAMDNodes &N, bool Merge=false) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void dropUnknownMetadata (ArrayRef< unsigned > KnownIDs)
Drop unknown metadata. Passes are required to drop metadata they don't understand. This is a convenience method for passes to do so.
void dropUnknownMetadata ()
void dropUnknownMetadata (unsigned ID1)
void dropUnknownMetadata (unsigned ID1, unsigned ID2)
void setAAMetadata (const AAMDNodes &N)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
void setHasUnsafeAlgebra (bool B)
void setHasNoNaNs (bool B)
void setHasNoInfs (bool B)
void setHasNoSignedZeros (bool B)
void setHasAllowReciprocal (bool B)
void setFastMathFlags (FastMathFlags FMF)
void copyFastMathFlags (FastMathFlags FMF)
bool hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
FastMathFlags getFastMathFlags () const
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool isAtomic () const
bool mayThrow () const
bool mayReturn () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range
< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range
< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Public Member Functions inherited from llvm::ilist_node< Instruction >
Instruction * getPrevNode ()
Get the previous node, or 0 for the list head.
const Instruction * getPrevNode () const
Get the previous node, or 0 for the list head.
Instruction * getNextNode ()
Get the next node, or 0 for the list tail.
const Instruction * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static CastInst * Create (Instruction::CastOps, Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Construct any of the CastInst subclasses.
static CastInst * Create (Instruction::CastOps, Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Construct any of the CastInst subclasses.
static CastInst * CreateZExtOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a ZExt or BitCast cast instruction.
static CastInst * CreateZExtOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a ZExt or BitCast cast instruction.
static CastInst * CreateSExtOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a SExt or BitCast cast instruction.
static CastInst * CreateSExtOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a SExt or BitCast cast instruction.
static CastInst * CreatePointerCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a BitCast AddrSpaceCast, or a PtrToInt cast instruction.
static CastInst * CreatePointerCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a BitCast, AddrSpaceCast or a PtrToInt cast instruction.
static CastInst * CreatePointerBitCastOrAddrSpaceCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a BitCast or an AddrSpaceCast cast instruction.
static CastInst * CreatePointerBitCastOrAddrSpaceCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=0)
Create a BitCast or an AddrSpaceCast cast instruction.
static CastInst * CreateBitOrPointerCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=0)
Create a BitCast, a PtrToInt, or an IntToPTr cast instruction.
static CastInst * CreateIntegerCast (Value *S, Type *Ty, bool isSigned, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a ZExt, BitCast, or Trunc for int -> int casts.
static CastInst * CreateIntegerCast (Value *S, Type *Ty, bool isSigned, const Twine &Name, BasicBlock *InsertAtEnd)
Create a ZExt, BitCast, or Trunc for int -> int casts.
static CastInst * CreateFPCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
static CastInst * CreateFPCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
static CastInst * CreateTruncOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a Trunc or BitCast cast instruction.
static CastInst * CreateTruncOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a Trunc or BitCast cast instruction.
static bool isCastable (Type *SrcTy, Type *DestTy)
Check whether it is valid to call getCastOpcode for these types.
static bool isBitCastable (Type *SrcTy, Type *DestTy)
Check whether a bitcast between these types is valid.
static bool isBitOrNoopPointerCastable (Type *SrcTy, Type *DestTy, const DataLayout *Layout=0)
Check whether a bitcast, inttoptr, or ptrtoint cast between these types is valid and a no-op.
static Instruction::CastOps getCastOpcode (const Value *Val, bool SrcIsSigned, Type *Ty, bool DstIsSigned)
Infer the opcode for cast operand and type.
static bool isNoopCast (Instruction::CastOps Opcode, Type *SrcTy, Type *DstTy, Type *IntPtrTy)
Determine if the described cast is a no-op cast.
static unsigned isEliminableCastPair (Instruction::CastOps firstOpcode, Instruction::CastOps secondOpcode, Type *SrcTy, Type *MidTy, Type *DstTy, Type *SrcIntPtrTy, Type *MidIntPtrTy, Type *DstIntPtrTy)
Determine if a cast pair is eliminable.
static bool castIsValid (Instruction::CastOps op, Value *S, Type *DstTy)
Determine if a cast is valid without creating one.
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::UnaryInstruction
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
CastInst (Type *Ty, unsigned iType, Value *S, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics for subclasses.
CastInst (Type *Ty, unsigned iType, Value *S, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-at-end-of-block semantics for subclasses.
Protected Member Functions inherited from llvm::UnaryInstruction
UnaryInstruction (Type *Ty, unsigned iType, Value *V, Instruction *IB=nullptr)
UnaryInstruction (Type *Ty, unsigned iType, Value *V, BasicBlock *IAE)
Protected Member Functions inherited from llvm::Instruction
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
virtual Instruction * clone_impl () const =0
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Instruction >
ilist_node ()
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range
< op_iterator > op_range
typedef iterator_range
< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MetadataAsValueVal, InlineAsmVal, InstructionVal,
ConstantFirstVal = FunctionVal, ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl
< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl
< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
Base class of casting instructions.
This is the base class for all instructions that perform data casts. It is simply provided so that instruction category testing can be performed with code like:
if (isa<CastInst>(Instr)) { ... }
Definition at line 385 of file InstrTypes.h.
Constructor & Destructor Documentation
llvm::CastInst::CastInst (Type * Ty, unsigned iType, Value * S, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) inline protected
Constructor with insert-before-instruction semantics for subclasses.
Definition at line 389 of file InstrTypes.h.
llvm::CastInst::CastInst (Type * Ty, unsigned iType, Value * S, const Twine & NameStr, BasicBlock * InsertAtEnd) inline protected
Constructor with insert-at-end-of-block semantics for subclasses.
Definition at line 395 of file InstrTypes.h.
Member Function Documentation
bool CastInst::castIsValid (Instruction::CastOps op, Value * S, Type * DstTy) static
Determine if a cast is valid without creating one.
This method can be used to determine if a cast from S to DstTy using Opcode op is valid or not.
Returns
true iff the proposed cast is valid.
Check that the construction parameters for a CastInst are correct. This could be broken out into the separate constructors but it is useful to have it in one place and to eliminate the redundant code for getting the sizes of the types involved.
Definition at line 2850 of file Instructions.cpp.
References llvm::dyn_cast(), llvm::PointerType::getAddressSpace(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Type::isAggregateType(), llvm::Type::isFirstClassType(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isPointerTy(), and llvm::Type::isVectorTy().
Referenced by llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::BitCastInst::BitCastInst(), ConstantFoldLoadThroughBitcast(), Create(), llvm::FPExtInst::FPExtInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPTruncInst::FPTruncInst(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::ConstantExpr::getBitCast(), llvm::ConstantExpr::getCast(), llvm::IntToPtrInst::IntToPtrInst(), llvm::PtrToIntInst::PtrToIntInst(), llvm::SExtInst::SExtInst(), llvm::SIToFPInst::SIToFPInst(), llvm::TruncInst::TruncInst(), llvm::UIToFPInst::UIToFPInst(), and llvm::ZExtInst::ZExtInst().
static bool llvm::CastInst::classof (const Instruction * I) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 662 of file InstrTypes.h.
References llvm::Instruction::isCast().
static bool llvm::CastInst::classof (const Value * V) inline static
Definition at line 665 of file InstrTypes.h.
CastInst * CastInst::Create (Instruction::CastOps op, Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Construct any of the CastInst subclasses.
Provides a way to construct any of the CastInst subclasses using an opcode instead of the subclass's constructor. The opcode must be in the CastOps category (Instruction::isCast(opcode) returns true). This constructor has insert-before-instruction semantics to automatically insert the new CastInst before InsertBefore (if it is non-null).
Parameters
op The opcode of the cast instruction
S The value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2406 of file Instructions.cpp.
References assert(), castIsValid(), and llvm_unreachable.
Referenced by BuildNew(), llvm::InstCombiner::commonCastTransforms(), CreateBitOrPointerCast(), llvm::NoFolder::CreateCast(), llvm::IRBuilder< true, TargetFolder >::CreateCast(), CreateFPCast(), CreateIntegerCast(), CreatePointerBitCastOrAddrSpaceCast(), CreatePointerCast(), CreateSExtOrBitCast(), CreateTruncOrBitCast(), CreateZExtOrBitCast(), llvm::InstCombiner::FoldSelectOpOp(), llvm::ConstantExpr::getAsInstruction(), SinkCast(), SinkShiftAndTruncate(), llvm::UpgradeBitCastInst(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitOr(), and llvm::InstCombiner::visitXor().
CastInst * CastInst::Create (Instruction::CastOps op, Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Construct any of the CastInst subclasses.
Provides a way to construct any of the CastInst subclasses using an opcode instead of the subclass's constructor. The opcode must be in the CastOps category. This constructor has insert-at-end-of-block semantics to automatically insert the new CastInst at the end of InsertAtEnd (if its non-null).
Parameters
op The opcode for the cast instruction
S The value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2428 of file Instructions.cpp.
References assert(), castIsValid(), and llvm_unreachable.
CastInst * CastInst::CreateBitOrPointerCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = 0) static
Create a BitCast, a PtrToInt, or an IntToPTr cast instruction.
If the value is a pointer type and the destination an integer type, creates a PtrToInt cast. If the value is an integer type and the destination a pointer type, creates an IntToPtr cast. Otherwise, creates a bitcast.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2559 of file Instructions.cpp.
References Create(), llvm::Value::getType(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
CastInst * CastInst::CreateFPCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
Parameters
S The floating point value to be casted
Ty The floating point type to cast to
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2598 of file Instructions.cpp.
References assert(), Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), and llvm::Type::isFPOrFPVectorTy().
Referenced by llvm::NoFolder::CreateFPCast(), llvm::IRBuilder< true, TargetFolder >::CreateFPCast(), and llvm::InstCombiner::visitFPTrunc().
CastInst * CastInst::CreateFPCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
Parameters
S The floating point value to be casted
Ty The floating point type to cast to
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2611 of file Instructions.cpp.
References assert(), Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), and llvm::Type::isFPOrFPVectorTy().
CastInst * CastInst::CreateIntegerCast (Value * S, Type * Ty, bool isSigned, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a ZExt, BitCast, or Trunc for int -> int casts.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which cast should be made
isSigned Whether to regard S as signed or not
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2570 of file Instructions.cpp.
References assert(), Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), and llvm::Type::isIntOrIntVectorTy().
Referenced by llvm::NoFolder::CreateIntCast(), llvm::IRBuilder< true, TargetFolder >::CreateIntCast(), createMalloc(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitPtrToInt(), and llvm::InstCombiner::visitTrunc().
CastInst * CastInst::CreateIntegerCast (Value * S, Type * Ty, bool isSigned, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a ZExt, BitCast, or Trunc for int -> int casts.
Parameters
S The integer value to be casted (operand 0)
Ty The integer type to which operand is casted
isSigned Whether to regard S as signed or not
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2584 of file Instructions.cpp.
References assert(), Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), and llvm::Type::isIntOrIntVectorTy().
CastInst * CastInst::CreatePointerBitCastOrAddrSpaceCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a BitCast or an AddrSpaceCast cast instruction.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2533 of file Instructions.cpp.
References assert(), Create(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreatePointerBitCastOrAddrSpaceCast(), CreatePointerCast(), and llvm::InstCombiner::visitGetElementPtrInst().
CastInst * CastInst::CreatePointerBitCastOrAddrSpaceCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = 0) static
Create a BitCast or an AddrSpaceCast cast instruction.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2546 of file Instructions.cpp.
References assert(), Create(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), and llvm::Type::isPtrOrPtrVectorTy().
CastInst * CastInst::CreatePointerCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a BitCast AddrSpaceCast, or a PtrToInt cast instruction.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2498 of file Instructions.cpp.
References assert(), Create(), CreatePointerBitCastOrAddrSpaceCast(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isPtrOrPtrVectorTy(), and llvm::Type::isVectorTy().
Referenced by llvm::NoFolder::CreatePointerCast(), and llvm::IRBuilder< true, TargetFolder >::CreatePointerCast().
CastInst * CastInst::CreatePointerCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a BitCast, AddrSpaceCast or a PtrToInt cast instruction.
Create a BitCast or a PtrToInt cast instruction.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2516 of file Instructions.cpp.
References assert(), Create(), CreatePointerBitCastOrAddrSpaceCast(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isPtrOrPtrVectorTy(), and llvm::Type::isVectorTy().
CastInst * CastInst::CreateSExtOrBitCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a SExt or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2466 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), and llvm::Value::getType().
Referenced by llvm::NoFolder::CreateSExtOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateSExtOrBitCast(), and llvm::InstCombiner::visitSub().
CastInst * CastInst::CreateSExtOrBitCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a SExt or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2474 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), and llvm::Value::getType().
CastInst * CastInst::CreateTruncOrBitCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a Trunc or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2482 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), and llvm::Value::getType().
Referenced by llvm::NoFolder::CreateTruncOrBitCast(), and llvm::IRBuilder< true, TargetFolder >::CreateTruncOrBitCast().
CastInst * CastInst::CreateTruncOrBitCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a Trunc or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2490 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), and llvm::Value::getType().
CastInst * CastInst::CreateZExtOrBitCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a ZExt or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 2450 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), and llvm::Value::getType().
Referenced by llvm::NoFolder::CreateZExtOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateZExtOrBitCast(), and llvm::InstCombiner::visitSub().
CastInst * CastInst::CreateZExtOrBitCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a ZExt or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 2458 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), and llvm::Value::getType().
Instruction::CastOps CastInst::getCastOpcode (const Value * Val, bool SrcIsSigned, Type * Ty, bool DstIsSigned) static
Infer the opcode for cast operand and type.
Returns the opcode necessary to cast Val into Ty using usual casting rules.
Parameters
Val The value to cast
SrcIsSigned Whether to treat the source as signed
Ty The Type to which the value should be casted
DstIsSigned Whether to treate the dest. as signed
Definition at line 2747 of file Instructions.cpp.
References assert(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::Type::isFirstClassType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::Type::isVectorTy(), llvm::Type::isX86_MMXTy(), and llvm_unreachable.
Referenced by CastGEPIndices(), llvm::ConstantFoldCastInstruction(), getFoldedAlignOf(), getFoldedOffsetOf(), and getFoldedSizeOf().
Type* llvm::CastInst::getDestTy () const inline
Return the destination type, as a convenience.
Definition at line 653 of file InstrTypes.h.
References llvm::Intrinsic::getType().
Instruction::CastOps llvm::CastInst::getOpcode () const inline
Return the opcode of this CastInst.
Definition at line 646 of file InstrTypes.h.
References llvm::Instruction::getOpcode().
Referenced by llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::BitCastInst::BitCastInst(), llvm::InstCombiner::commonCastTransforms(), llvm::FPExtInst::FPExtInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPTruncInst::FPTruncInst(), llvm::IntToPtrInst::IntToPtrInst(), isEliminableCastPair(), isIntegerCast(), isLosslessCast(), isNoopCast(), llvm::PtrToIntInst::PtrToIntInst(), llvm::SExtInst::SExtInst(), SinkCast(), SinkShiftAndTruncate(), llvm::SIToFPInst::SIToFPInst(), llvm::TruncInst::TruncInst(), llvm::UIToFPInst::UIToFPInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), visitIVCast(), llvm::InstCombiner::visitOr(), and llvm::ZExtInst::ZExtInst().
Type* llvm::CastInst::getSrcTy () const inline
Return the source type, as a convenience.
Definition at line 651 of file InstrTypes.h.
Referenced by llvm::InstCombiner::visitFCmpInst().
bool CastInst::isBitCastable (Type * SrcTy, Type * DestTy) static
Check whether a bitcast between these types is valid.
Parameters
SrcTy The Type from which the value should be cast.
DestTy The Type to which the value should be cast.
Definition at line 2687 of file Instructions.cpp.
References llvm::Type::getPrimitiveSizeInBits(), llvm::Type::isFirstClassType(), and llvm::Type::isX86_MMXTy().
Referenced by isBitOrNoopPointerCastable().
bool CastInst::isBitOrNoopPointerCastable (Type * SrcTy, Type * DestTy, const DataLayout * Layout = 0) static
Check whether a bitcast, inttoptr, or ptrtoint cast between these types is valid and a no-op.
This ensures that any pointer<->integer cast has enough bits in the integer and any other cast is a bitcast.
Parameters
SrcTy The Type from which the value should be cast.
DestTy The Type to which the value should be cast.
Layout Optional DataLayout.
Definition at line 2727 of file Instructions.cpp.
References llvm::DataLayout::getPointerTypeSizeInBits(), and isBitCastable().
Referenced by llvm::FindAvailableLoadedValue().
bool CastInst::isCastable (Type * SrcTy, Type * DestTy) static
Check whether it is valid to call getCastOpcode for these types.
Parameters
SrcTy The Type from which the value should be cast.
DestTy The Type to which the value should be cast.
Definition at line 2626 of file Instructions.cpp.
References llvm::Type::getPrimitiveSizeInBits(), llvm::Type::isFirstClassType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::Type::isVectorTy(), and llvm::Type::isX86_MMXTy().
unsigned CastInst::isEliminableCastPair (Instruction::CastOps firstOp, Instruction::CastOps secondOp, Type * SrcTy, Type * MidTy, Type * DstTy, Type * SrcIntPtrTy, Type * MidIntPtrTy, Type * DstIntPtrTy) static
Determine if a cast pair is eliminable.
Determine how a pair of casts can be eliminated, if they can be at all. This is a helper function for both CastInst and ConstantExpr.
Returns
0 if the CastInst pair can't be eliminated, otherwise returns Instruction::CastOps value for a cast that can replace the pair, casting SrcTy to DstTy.
This function determines if a pair of casts can be eliminated and what opcode should be used in the elimination. This assumes that there are two instructions like this:
F = firstOpcode SrcTy x to MidTy
S = secondOpcode MidTy F to DstTy The function returns a resultOpcode so these two casts can be replaced with:
Replacement = resultOpcode SrcTy x to DstTy If no such cast is permited, the function returns 0.
Parameters
firstOp Opcode of first cast
secondOp Opcode of second cast
SrcTy SrcTy of 1st cast
MidTy DstTy of 1st cast & SrcTy of 2nd cast
DstTy DstTy of 2nd cast
SrcIntPtrTy Integer type corresponding to Ptr SrcTy, or null
MidIntPtrTy Integer type corresponding to Ptr MidTy, or null
DstIntPtrTy Integer type corresponding to Ptr DstTy, or null
Definition at line 2187 of file Instructions.cpp.
References assert(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerElementType(), llvm::Type::getScalarSizeInBits(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isPtrOrPtrVectorTy(), llvm::Type::isVectorTy(), and llvm_unreachable.
Referenced by foldConstantCastPair(), and isEliminableCastPair().
bool CastInst::isIntegerCast () const
Determine if this is an integer-only cast.
There are several places where we need to know if a cast instruction only deals with integer source and destination types. To simplify that logic, this method is provided.
Returns
true iff the cast has only integral typed operand and dest type.
Definition at line 2088 of file Instructions.cpp.
References getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::Type::isIntegerTy().
bool CastInst::isLosslessCast () const
Determine if this is a lossless cast.
A lossless cast is one that does not alter the basic value. It implies a no-op cast but is more stringent, preventing things like int->float, long->double, or int->ptr.
Returns
true iff the cast is lossless.
Definition at line 2101 of file Instructions.cpp.
References getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::Type::isPointerTy().
Referenced by isSafeToEliminateVarargsCast().
bool CastInst::isNoopCast (Instruction::CastOps Opcode, Type * SrcTy, Type * DestTy, Type * IntPtrTy) static
Determine if the described cast is a no-op cast.
Determine if the described cast is a no-op.
A no-op cast is one that can be effected without changing any bits. It implies that the source and destination types are the same size. The IntPtrTy argument is used to make accurate determinations for casts involving Integer and Pointer types. They are no-op casts if the integer is the same size as the pointer. However, pointer size varies with platform. Generally, the result of DataLayout::getIntPtrType() should be passed in. If that's not available, use Type::Int64Ty, which will make the isNoopCast call conservative.
This function determines if the CastInst does not require any bits to be changed in order to effect the cast. Essentially, it identifies cases where no code gen is necessary for the cast, hence the name no-op cast. For example, the following are all no-op casts:
bitcast i32* x to i8*
bitcast <2 x i32> x to <4 x i16>
ptrtoint i32* x to i32 ; on 32-bit plaforms only
Parameters
Opcode Opcode of cast
SrcTy SrcTy of cast
DestTy DstTy of cast
IntPtrTy Integer type corresponding to Ptr types
Definition at line 2126 of file Instructions.cpp.
References llvm::Type::getScalarSizeInBits(), and llvm_unreachable.
Referenced by isNoopCast().
bool CastInst::isNoopCast (Type * IntPtrTy) const
Determine if this cast is a no-op cast.
Determine if a cast is a no-op.
Parameters
IntPtrTy Integer type corresponding to pointer
Definition at line 2156 of file Instructions.cpp.
References getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), and isNoopCast().
bool CastInst::isNoopCast (const DataLayout * DL) const
Determine if this cast is a no-op cast.
Parameters
DL DataLayout to get the Int Ptr type from.
Definition at line 2160 of file Instructions.cpp.
References llvm::Value::getContext(), llvm::Type::getInt64Ty(), llvm::DataLayout::getIntPtrType(), getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), and isNoopCast().
The documentation for this class was generated from the following files:
InstrTypes.h
Instructions.cpp