LLVM: llvm::ValueAsMetadata Class Reference
LLVM API Documentation
llvm::ValueAsMetadata Class Reference
Value wrapper in the Metadata hierarchy.
#include <Metadata.h>
Public Member Functions
Value * getValue () const
Type * getType () const
LLVMContext & getContext () const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void print (raw_ostream &OS) const
void printAsOperand (raw_ostream &OS, bool PrintType=true, const Module *M=nullptr) const
Static Public Member Functions
static ValueAsMetadata * get (Value *V)
static ConstantAsMetadata * getConstant (Value *C)
static LocalAsMetadata * getLocal (Value *Local)
static ValueAsMetadata * getIfExists (Value *V)
static ConstantAsMetadata * getConstantIfExists (Value *C)
static LocalAsMetadata * getLocalIfExists (Value *Local)
static void handleDeletion (Value *V)
static void handleRAUW (Value *From, Value *To)
static bool classof (const Metadata *MD)
Protected Member Functions
ValueAsMetadata (unsigned ID, Value *V)
~ValueAsMetadata ()
void replaceAllUsesWith (Metadata *MD)
Handle collisions after Value::replaceAllUsesWith().
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID)
~Metadata ()
bool isStoredDistinctInContext () const
Store this in a big non-uniqued untyped bucket.
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Friends
class ReplaceableMetadataImpl
class LLVMContextImpl
Additional Inherited Members
Public Types inherited from llvm::Metadata
enum MetadataKind {
MDTupleKind, MDLocationKind, MDNodeFwdDeclKind, ConstantAsMetadataKind,
LocalAsMetadataKind, MDStringKind
}
Protected Attributes inherited from llvm::Metadata
bool IsDistinctInContext: 1
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned short SubclassData16
unsigned SubclassData32
Detailed Description
Value wrapper in the Metadata hierarchy.
This is a custom value handle that allows other metadata to refer to classes in the Value hierarchy.
Because of full uniquing support, each value is only wrapped by a single ValueAsMetadata object, so the lookup maps are far more efficient than those using ValueHandleBase.
Definition at line 185 of file Metadata.h.
Constructor & Destructor Documentation
llvm::ValueAsMetadata::ValueAsMetadata (unsigned ID, Value * V) inline protected
Definition at line 197 of file Metadata.h.
References assert().
llvm::ValueAsMetadata::~ValueAsMetadata () inline protected
Definition at line 201 of file Metadata.h.
Member Function Documentation
static bool llvm::ValueAsMetadata::classof (const Metadata * MD) inline static
Definition at line 238 of file Metadata.h.
References llvm::Metadata::ConstantAsMetadataKind, llvm::Metadata::getMetadataID(), and llvm::Metadata::LocalAsMetadataKind.
ValueAsMetadata * ValueAsMetadata::get (Value * V) static
Definition at line 249 of file Metadata.cpp.
References assert(), llvm::CallingConv::C, llvm::Value::getContext(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValuesAsMetadata.
Referenced by getDbgIntrinsicValueImpl(), and MapMetadataImpl().
static ConstantAsMetadata* llvm::ValueAsMetadata::getConstant (Value * C) inline static
Definition at line 205 of file Metadata.h.
References llvm::CallingConv::C.
Referenced by llvm::ConstantAsMetadata::get().
static ConstantAsMetadata* llvm::ValueAsMetadata::getConstantIfExists (Value * C) inline static
Definition at line 213 of file Metadata.h.
References getIfExists().
Referenced by llvm::ConstantAsMetadata::getIfExists().
LLVMContext& llvm::ValueAsMetadata::getContext () const inline
Definition at line 222 of file Metadata.h.
References llvm::Value::getContext().
ValueAsMetadata * ValueAsMetadata::getIfExists (Value * V) static
Definition at line 269 of file Metadata.cpp.
References assert(), llvm::Value::getContext(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValuesAsMetadata.
Referenced by getConstantIfExists(), and getLocalIfExists().
static LocalAsMetadata* llvm::ValueAsMetadata::getLocal (Value * Local) inline static
Definition at line 208 of file Metadata.h.
Referenced by llvm::LocalAsMetadata::get().
static LocalAsMetadata* llvm::ValueAsMetadata::getLocalIfExists (Value * Local) inline static
Definition at line 216 of file Metadata.h.
References getIfExists().
Referenced by llvm::LocalAsMetadata::getIfExists().
Type* llvm::ValueAsMetadata::getType () const inline
Definition at line 221 of file Metadata.h.
References llvm::Value::getType().
Value* llvm::ValueAsMetadata::getValue () const inline
Definition at line 220 of file Metadata.h.
Referenced by llvm::ConstantAsMetadata::getValue(), handleDeletion(), handleRAUW(), and WriteValueAsMetadata().
void ValueAsMetadata::handleDeletion (Value * V) static
Definition at line 274 of file Metadata.cpp.
References assert(), llvm::Type::getContext(), llvm::Value::getType(), getValue(), I, llvm::LLVMContext::pImpl, replaceAllUsesWith(), llvm::SPII::Store, and llvm::LLVMContextImpl::ValuesAsMetadata.
Referenced by llvm::Value::~Value().
void ValueAsMetadata::handleRAUW (Value * From, Value * To) static
Definition at line 293 of file Metadata.cpp.
References assert(), llvm::CallingConv::C, llvm::ConstantAsMetadata::get(), llvm::Type::getContext(), getLocalFunction(), llvm::Value::getType(), getValue(), I, replaceAllUsesWith(), and llvm::SPII::Store.
Referenced by llvm::Value::replaceAllUsesWith().
void llvm::ValueAsMetadata::replaceAllUsesWith (Metadata * MD) inline protected
Handle collisions after Value::replaceAllUsesWith().
RAUW isn't supported directly for ValueAsMetadata, but if the wrapped Value gets RAUW'ed and the target already exists, this is used to merge the two metadata nodes.
Definition at line 233 of file Metadata.h.
References llvm::ReplaceableMetadataImpl::replaceAllUsesWith().
Referenced by handleDeletion(), and handleRAUW().
Friends And Related Function Documentation
friend class LLVMContextImpl friend
Definition at line 187 of file Metadata.h.
friend class ReplaceableMetadataImpl friend
Definition at line 186 of file Metadata.h.
The documentation for this class was generated from the following files:
Metadata.h
Metadata.cpp