LLVM: llvm::sys::RWMutexImpl Class Reference
LLVM API Documentation
llvm::sys::RWMutexImpl Class Reference
Platform agnostic RWMutex class.
#include <RWMutex.h>
Public Member Functions
Constructors
RWMutexImpl ()
Default Constructor.
~RWMutexImpl ()
Destructor.
Methods
bool reader_acquire ()
Unconditionally acquire the lock in reader mode.
bool reader_release ()
Unconditionally release the lock in reader mode.
bool writer_acquire ()
Unconditionally acquire the lock in writer mode.
bool writer_release ()
Unconditionally release the lock in write mode.
Detailed Description
Platform agnostic RWMutex class.
Definition at line 26 of file RWMutex.h.
Constructor & Destructor Documentation
llvm::RWMutexImpl::RWMutexImpl () explicit
Default Constructor.
Initializes the lock but doesn't acquire it.
Definition at line 46 of file RWMutex.cpp.
References assert(), llvm::LibFunc::bzero, and llvm::LibFunc::malloc.
llvm::RWMutexImpl::~RWMutexImpl ()
Destructor.
Releases and removes the lock
Definition at line 68 of file RWMutex.cpp.
References assert(), and llvm::LibFunc::free.
Member Function Documentation
bool llvm::RWMutexImpl::reader_acquire ()
Unconditionally acquire the lock in reader mode.
Attempts to unconditionally acquire the lock in reader mode. If the lock is held by a writer, this method will wait until it can acquire the lock.
Returns
false if any kind of error occurs, true otherwise.
Definition at line 77 of file RWMutex.cpp.
References assert().
Referenced by llvm::sys::SmartRWMutex< true >::lock_shared().
bool llvm::RWMutexImpl::reader_release ()
Unconditionally release the lock in reader mode.
Attempts to release the lock in reader mode.
Returns
false if any kind of error occurs, true otherwise.
Definition at line 87 of file RWMutex.cpp.
References assert().
Referenced by llvm::sys::SmartRWMutex< true >::unlock_shared().
bool llvm::RWMutexImpl::writer_acquire ()
Unconditionally acquire the lock in writer mode.
Attempts to unconditionally acquire the lock in reader mode. If the lock is held by any readers, this method will wait until it can acquire the lock.
Returns
false if any kind of error occurs, true otherwise.
Definition at line 97 of file RWMutex.cpp.
References assert().
Referenced by llvm::sys::SmartRWMutex< true >::lock().
bool llvm::RWMutexImpl::writer_release ()
Unconditionally release the lock in write mode.
Attempts to release the lock in writer mode.
Returns
false if any kind of error occurs, true otherwise.
Definition at line 107 of file RWMutex.cpp.
References assert().
Referenced by llvm::sys::SmartRWMutex< true >::unlock().
The documentation for this class was generated from the following files:
RWMutex.h
RWMutex.cpp