LLVM: llvm::SuccIterator< Term_, BB_ > Class Template Reference
LLVM API Documentation
llvm::SuccIterator< Term_, BB_ > Class Template Reference
#include <CFG.h>
Public Types
typedef super::pointer pointer
typedef super::reference reference
Public Member Functions
SuccIterator (Term_ T)
SuccIterator (Term_ T, bool)
const Self & operator= (const Self &I)
unsigned getSuccessorIndex () const
bool operator== (const Self &x) const
bool operator!= (const Self &x) const
reference operator* () const
pointer operator-> () const
Self & operator++ ()
Self operator++ (int)
Self & operator-- ()
Self operator-- (int)
bool operator< (const Self &x) const
bool operator<= (const Self &x) const
bool operator>= (const Self &x) const
bool operator> (const Self &x) const
Self & operator+= (int Right)
Self operator+ (int Right) const
Self & operator-= (int Right)
Self operator- (int Right) const
int operator- (const Self &x) const
SuccessorProxy operator[] (int offset)
BB_ * getSource ()
Get the source BB of this iterator.
Detailed Description
template<class Term_, class BB_>
class llvm::SuccIterator< Term_, BB_ >
Definition at line 107 of file IR/CFG.h.
Member Typedef Documentation
template<class Term_ , class BB_ > typedef super::pointer llvm::SuccIterator< Term_, BB_ >::pointer
Definition at line 113 of file IR/CFG.h.
template<class Term_ , class BB_ > typedef super::reference llvm::SuccIterator< Term_, BB_ >::reference
Definition at line 114 of file IR/CFG.h.
Constructor & Destructor Documentation
template<class Term_ , class BB_ > llvm::SuccIterator< Term_, BB_ >::SuccIterator (Term_ T) inline explicit
Definition at line 146 of file IR/CFG.h.
template<class Term_ , class BB_ > llvm::SuccIterator< Term_, BB_ >::SuccIterator (Term_ T, bool) inline
Definition at line 148 of file IR/CFG.h.
Member Function Documentation
template<class Term_ , class BB_ > BB_* llvm::SuccIterator< Term_, BB_ >::getSource () inline
Get the source BB of this iterator.
Definition at line 241 of file IR/CFG.h.
References assert().
template<class Term_ , class BB_ > unsigned llvm::SuccIterator< Term_, BB_ >::getSuccessorIndex () const inline
getSuccessorIndex - This is used to interface between code that wants to operate on terminator instructions directly.
Definition at line 169 of file IR/CFG.h.
Referenced by llvm::DOTGraphTraits< const Function * >::getEdgeSourceLabel(), llvm::BranchProbabilityInfo::getEdgeWeight(), and llvm::SplitCriticalEdge().
template<class Term_ , class BB_ > bool llvm::SuccIterator< Term_, BB_ >::operator!= (const Self & x) const inline
Definition at line 172 of file IR/CFG.h.
References llvm::SuccIterator< Term_, BB_ >::operator==().
template<class Term_ , class BB_ > reference llvm::SuccIterator< Term_, BB_ >::operator* () const inline
Definition at line 174 of file IR/CFG.h.
Referenced by llvm::SuccIterator< Term_, BB_ >::operator->().
template<class Term_ , class BB_ > Self llvm::SuccIterator< Term_, BB_ >::operator+ (int Right) const inline
Definition at line 214 of file IR/CFG.h.
Referenced by llvm::SuccIterator< Term_, BB_ >::operator-().
template<class Term_ , class BB_ > Self& llvm::SuccIterator< Term_, BB_ >::operator++ () inline
Definition at line 177 of file IR/CFG.h.
template<class Term_ , class BB_ > Self llvm::SuccIterator< Term_, BB_ >::operator++ (int) inline
Definition at line 179 of file IR/CFG.h.
template<class Term_ , class BB_ > Self& llvm::SuccIterator< Term_, BB_ >::operator+= (int Right) inline
Definition at line 207 of file IR/CFG.h.
References assert().
Referenced by llvm::SuccIterator< Term_, BB_ >::operator-=().
template<class Term_ , class BB_ > Self llvm::SuccIterator< Term_, BB_ >::operator- (int Right) const inline
Definition at line 224 of file IR/CFG.h.
References llvm::SuccIterator< Term_, BB_ >::operator+().
template<class Term_ , class BB_ > int llvm::SuccIterator< Term_, BB_ >::operator- (const Self & x) const inline
Definition at line 228 of file IR/CFG.h.
References assert().
template<class Term_ , class BB_ > Self& llvm::SuccIterator< Term_, BB_ >::operator-- () inline
Definition at line 183 of file IR/CFG.h.
template<class Term_ , class BB_ > Self llvm::SuccIterator< Term_, BB_ >::operator-- (int) inline
Definition at line 184 of file IR/CFG.h.
template<class Term_ , class BB_ > Self& llvm::SuccIterator< Term_, BB_ >::operator-= (int Right) inline
Definition at line 220 of file IR/CFG.h.
References llvm::SuccIterator< Term_, BB_ >::operator+=().
template<class Term_ , class BB_ > pointer llvm::SuccIterator< Term_, BB_ >::operator-> () const inline
Definition at line 175 of file IR/CFG.h.
References llvm::SuccIterator< Term_, BB_ >::operator*().
template<class Term_ , class BB_ > bool llvm::SuccIterator< Term_, BB_ >::operator< (const Self & x) const inline
Definition at line 188 of file IR/CFG.h.
References assert().
template<class Term_ , class BB_ > bool llvm::SuccIterator< Term_, BB_ >::operator<= (const Self & x) const inline
Definition at line 193 of file IR/CFG.h.
References assert().
template<class Term_ , class BB_ > const Self& llvm::SuccIterator< Term_, BB_ >::operator= (const Self & I) inline
Definition at line 161 of file IR/CFG.h.
References assert().
template<class Term_ , class BB_ > bool llvm::SuccIterator< Term_, BB_ >::operator== (const Self & x) const inline
Definition at line 171 of file IR/CFG.h.
Referenced by llvm::SuccIterator< Term_, BB_ >::operator!=().
template<class Term_ , class BB_ > bool llvm::SuccIterator< Term_, BB_ >::operator> (const Self & x) const inline
Definition at line 202 of file IR/CFG.h.
References assert().
template<class Term_ , class BB_ > bool llvm::SuccIterator< Term_, BB_ >::operator>= (const Self & x) const inline
Definition at line 197 of file IR/CFG.h.
References assert().
template<class Term_ , class BB_ > SuccessorProxy llvm::SuccIterator< Term_, BB_ >::operator[] (int offset) inline
Definition at line 234 of file IR/CFG.h.
The documentation for this class was generated from the following file:
IR/CFG.h