LLVM: llvm::MDNodeFwdDecl Class Reference
LLVM API Documentation
llvm::MDNodeFwdDecl Class Reference
Forward declaration of metadata.
#include <Metadata.h>
Public Member Functions
~MDNodeFwdDecl ()
void operator delete (void *Mem)
Public Member Functions inherited from llvm::MDNode
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isDistinct () const
Check if node is distinct.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void print (raw_ostream &OS) const
void printAsOperand (raw_ostream &OS, bool PrintType=true, const Module *M=nullptr) const
Static Public Member Functions
static MDNodeFwdDecl * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDNode * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNode * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNode * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNodeFwdDecl * getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
Return a temporary MDNode.
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static AAMDNodes getMostGenericAA (const AAMDNodes &A, const AAMDNodes &B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
Friends
class Metadata
class ReplaceableMetadataImpl
Additional Inherited Members
Public Types inherited from llvm::MDNode
typedef const MDOperand * op_iterator
typedef iterator_range
< op_iterator > op_range
Public Types inherited from llvm::Metadata
enum MetadataKind {
MDTupleKind, MDLocationKind, MDNodeFwdDeclKind, ConstantAsMetadataKind,
LocalAsMetadataKind, MDStringKind
}
Protected Member Functions inherited from llvm::MDNode
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
MDNode (LLVMContext &Context, unsigned ID, ArrayRef< Metadata * > MDs)
~MDNode ()
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID)
~Metadata ()
bool isStoredDistinctInContext () const
Store this in a big non-uniqued untyped bucket.
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Protected Attributes inherited from llvm::MDNode
unsigned MDNodeSubclassData
Protected Attributes inherited from llvm::Metadata
bool IsDistinctInContext: 1
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned short SubclassData16
unsigned SubclassData32
Detailed Description
Forward declaration of metadata.
Forward declaration of metadata, in the form of a basic tuple. Unlike MDTuple, this class has full support for RAUW, is not owned, is not uniqued, and is suitable for forward references.
Definition at line 888 of file Metadata.h.
Constructor & Destructor Documentation
llvm::MDNodeFwdDecl::~MDNodeFwdDecl () inline
Definition at line 896 of file Metadata.h.
References llvm::MDNode::dropAllReferences().
Member Function Documentation
static bool llvm::MDNodeFwdDecl::classof (const Metadata * MD) inline static
Definition at line 905 of file Metadata.h.
References llvm::Metadata::getMetadataID(), and llvm::Metadata::MDNodeFwdDeclKind.
static MDNodeFwdDecl* llvm::MDNodeFwdDecl::get (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 901 of file Metadata.h.
Referenced by llvm::MDNode::getTemporary().
void llvm::MDNodeFwdDecl::operator delete (void * Mem) inline
Definition at line 899 of file Metadata.h.
Friends And Related Function Documentation
friend class Metadata friend
Definition at line 889 of file Metadata.h.
friend class ReplaceableMetadataImpl friend
Definition at line 890 of file Metadata.h.
The documentation for this class was generated from the following file:
Metadata.h