LLVM: WidenVector Class Reference
LLVM API Documentation
WidenVector Class Reference
Public Member Functions
WidenVector (SelectionDAG &DAG)
SDValue operator() (SDValue V64Reg)
Detailed Description
WidenVector - Given a value in the V64 register class, produce the equivalent value in the V128 register class.
Definition at line 1154 of file AArch64ISelDAGToDAG.cpp.
Constructor & Destructor Documentation
WidenVector::WidenVector (SelectionDAG & DAG) inline
Definition at line 1158 of file AArch64ISelDAGToDAG.cpp.
Member Function Documentation
SDValue WidenVector::operator() (SDValue V64Reg) inline
Definition at line 1160 of file AArch64ISelDAGToDAG.cpp.
References DL, llvm::EVT::getSimpleVT(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::TargetOpcode::IMPLICIT_DEF, and llvm::RegState::Undef.
The documentation for this class was generated from the following file:
AArch64ISelDAGToDAG.cpp