LLVM: llvm::MDString Class Reference
LLVM API Documentation
llvm::MDString Class Reference
A single uniqued string.
#include <Metadata.h>
Public Types
typedef StringRef::iterator iterator
Public Types inherited from llvm::Metadata
enum MetadataKind {
MDTupleKind, MDLocationKind, MDNodeFwdDeclKind, ConstantAsMetadataKind,
LocalAsMetadataKind, MDStringKind
}
Public Member Functions
StringRef getString () const
unsigned getLength () const
iterator begin () const
Pointer to the first byte of the string.
iterator end () const
Pointer to one byte past the end of the string.
const unsigned char * bytes_begin () const
const unsigned char * bytes_end () const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void print (raw_ostream &OS) const
void printAsOperand (raw_ostream &OS, bool PrintType=true, const Module *M=nullptr) const
Static Public Member Functions
static MDString * get (LLVMContext &Context, StringRef Str)
static MDString * get (LLVMContext &Context, const char *Str)
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast.
Friends
class StringMapEntry< MDString >
Additional Inherited Members
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID)
~Metadata ()
bool isStoredDistinctInContext () const
Store this in a big non-uniqued untyped bucket.
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Protected Attributes inherited from llvm::Metadata
bool IsDistinctInContext: 1
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned short SubclassData16
unsigned SubclassData32
Detailed Description
A single uniqued string.
These are used to efficiently contain a byte sequence for metadata. MDString is always unnamed.
Definition at line 441 of file Metadata.h.
Member Typedef Documentation
typedef StringRef::iterator llvm::MDString::iterator
Definition at line 462 of file Metadata.h.
Member Function Documentation
iterator llvm::MDString::begin () const inline
Pointer to the first byte of the string.
Definition at line 465 of file Metadata.h.
References llvm::StringRef::begin(), and getString().
const unsigned char* llvm::MDString::bytes_begin () const inline
Definition at line 470 of file Metadata.h.
References llvm::StringRef::bytes_begin(), and getString().
Referenced by WriteModuleMetadata().
const unsigned char* llvm::MDString::bytes_end () const inline
Definition at line 471 of file Metadata.h.
References llvm::StringRef::bytes_end(), and getString().
Referenced by WriteModuleMetadata().
static bool llvm::MDString::classof (const Metadata * MD) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 474 of file Metadata.h.
References llvm::Metadata::getMetadataID(), and llvm::Metadata::MDStringKind.
iterator llvm::MDString::end () const inline
Pointer to one byte past the end of the string.
Definition at line 468 of file Metadata.h.
References llvm::StringRef::end(), and getString().
MDString * MDString::get (LLVMContext & Context, StringRef Str) static
Definition at line 358 of file Metadata.cpp.
References assert(), I, llvm::LLVMContextImpl::MDStringCache, llvm::LLVMContext::pImpl, and llvm::SPII::Store.
Referenced by llvm::Module::addModuleFlag(), AppendMDNodeToSourcePtr(), CloneLoopBlocks(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createEnumerationType(), createFilePathPair(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createReplaceableForwardDecl(), llvm::MDBuilder::createString(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createTemplateTemplateParameter(), llvm::DIBuilder::createUnionType(), LLVMMDStringInContext(), SequenceToMDString(), and SetLoopAlreadyUnrolled().
static MDString* llvm::MDString::get (LLVMContext & Context, const char * Str) inline static
Definition at line 454 of file Metadata.h.
unsigned llvm::MDString::getLength () const inline
Definition at line 460 of file Metadata.h.
References getString(), and llvm::StringRef::size().
StringRef MDString::getString () const
Definition at line 373 of file Metadata.cpp.
References assert().
Referenced by begin(), bytes_begin(), bytes_end(), cacheAnnotationFromMD(), CloneLoopBlocks(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::TargetLoweringObjectFileCOFF::emitModuleFlags(), end(), getLength(), llvm::DIRef< T >::getName(), GetUnrollMetadata(), and SetLoopAlreadyUnrolled().
Friends And Related Function Documentation
friend class StringMapEntry< MDString > friend
Definition at line 442 of file Metadata.h.
The documentation for this class was generated from the following files:
Metadata.h
Metadata.cpp