LLVM: llvm::DWARFAbbreviationDeclarationSet Class Reference
LLVM API Documentation
llvm::DWARFAbbreviationDeclarationSet Class Reference
#include <DWARFDebugAbbrev.h>
Public Member Functions
DWARFAbbreviationDeclarationSet ()
uint32_t getOffset () const
void dump (raw_ostream &OS) const
bool extract (DataExtractor Data, uint32_t *OffsetPtr)
const
DWARFAbbreviationDeclaration * getAbbreviationDeclaration (uint32_t AbbrCode) const
Detailed Description
Definition at line 20 of file DWARFDebugAbbrev.h.
Constructor & Destructor Documentation
DWARFAbbreviationDeclarationSet::DWARFAbbreviationDeclarationSet ()
Definition at line 15 of file DWARFDebugAbbrev.cpp.
Member Function Documentation
void DWARFAbbreviationDeclarationSet::dump (raw_ostream & OS) const
Definition at line 47 of file DWARFDebugAbbrev.cpp.
bool DWARFAbbreviationDeclarationSet::extract (DataExtractor Data, uint32_t * OffsetPtr)
Definition at line 25 of file DWARFDebugAbbrev.cpp.
References llvm::DWARFAbbreviationDeclaration::extract(), and llvm::DWARFAbbreviationDeclaration::getCode().
Referenced by llvm::DWARFDebugAbbrev::extract().
const DWARFAbbreviationDeclaration * DWARFAbbreviationDeclarationSet::getAbbreviationDeclaration (uint32_t AbbrCode) const
Definition at line 53 of file DWARFDebugAbbrev.cpp.
Referenced by llvm::DWARFDebugInfoEntryMinimal::extractFast().
uint32_t llvm::DWARFAbbreviationDeclarationSet::getOffset () const inline
Definition at line 30 of file DWARFDebugAbbrev.h.
The documentation for this class was generated from the following files:
DWARFDebugAbbrev.h
DWARFDebugAbbrev.cpp