LLVM: llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator > Class Template Reference
LLVM API Documentation
llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator > Class Template Reference
Public Member Functions
PatternRewriteDescriptor (StringRef P, StringRef T)
bool performOnModule (Module &M) override
Public Member Functions inherited from llvm::SymbolRewriter::RewriteDescriptor
virtual ~RewriteDescriptor ()
Type getType () const
Public Member Functions inherited from llvm::ilist_node< RewriteDescriptor >
RewriteDescriptor * getPrevNode ()
Get the previous node, or 0 for the list head.
const RewriteDescriptor * getPrevNode () const
Get the previous node, or 0 for the list head.
RewriteDescriptor * getNextNode ()
Get the next node, or 0 for the list tail.
const RewriteDescriptor * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const RewriteDescriptor *RD)
Public Attributes
const std::string Pattern
const std::string Transform
Additional Inherited Members
Public Types inherited from llvm::SymbolRewriter::RewriteDescriptor
enum Type { Type::Invalid, Type::Function, Type::GlobalVariable, Type::NamedAlias }
Protected Member Functions inherited from llvm::SymbolRewriter::RewriteDescriptor
RewriteDescriptor (Type T)
Protected Member Functions inherited from llvm::ilist_node< RewriteDescriptor >
ilist_node ()
Detailed Description
template<RewriteDescriptor::Type DT, typename ValueType, ValueType *(llvm::Module::*)(StringRef) const Get, iterator_range< typename iplist< ValueType >::iterator >(llvm::Module::*)() Iterator>
class llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >
Definition at line 135 of file SymbolRewriter.cpp.
Constructor & Destructor Documentation
template<RewriteDescriptor::Type DT, typename ValueType , ValueType *(llvm::Module::*)(StringRef) const Get, iterator_range< typename iplist< ValueType >::iterator >(llvm::Module::*)() Iterator> llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >::PatternRewriteDescriptor (StringRef P, StringRef T) inline
Definition at line 140 of file SymbolRewriter.cpp.
Member Function Documentation
template<RewriteDescriptor::Type DT, typename ValueType , ValueType *(llvm::Module::*)(StringRef) const Get, iterator_range< typename iplist< ValueType >::iterator >(llvm::Module::*)() Iterator> static bool llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >::classof (const RewriteDescriptor * RD) inline static
Definition at line 145 of file SymbolRewriter.cpp.
References llvm::SymbolRewriter::RewriteDescriptor::getType().
template<RewriteDescriptor::Type DT, typename ValueType , ValueType *(llvm::Module::*)(StringRef) const Get, iterator_range< typename iplist< ValueType >::iterator >(llvm::Module::*)() Iterator> bool llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >::performOnModule (Module & M) override virtual
Implements llvm::SymbolRewriter::RewriteDescriptor.
Definition at line 155 of file SymbolRewriter.cpp.
References llvm::CallingConv::C, llvm::lltok::Error, Name, llvm::report_fatal_error(), llvm::SymbolRewriter::rewriteComdat(), and llvm::Regex::sub().
Member Data Documentation
template<RewriteDescriptor::Type DT, typename ValueType , ValueType *(llvm::Module::*)(StringRef) const Get, iterator_range< typename iplist< ValueType >::iterator >(llvm::Module::*)() Iterator> const std::string llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >::Pattern
Definition at line 137 of file SymbolRewriter.cpp.
template<RewriteDescriptor::Type DT, typename ValueType , ValueType *(llvm::Module::*)(StringRef) const Get, iterator_range< typename iplist< ValueType >::iterator >(llvm::Module::*)() Iterator> const std::string llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >::Transform
Definition at line 138 of file SymbolRewriter.cpp.
The documentation for this class was generated from the following file:
SymbolRewriter.cpp