LLVM: llvm::HexagonSubtarget Class Reference
LLVM API Documentation
llvm::HexagonSubtarget Class Reference
#include <HexagonSubtarget.h>
Public Types
enum HexagonArchEnum {
V1, V2, V3, V4,
V5
}
Public Member Functions
HexagonSubtarget (StringRef TT, StringRef CPU, StringRef FS, const TargetMachine &TM)
const InstrItineraryData * getInstrItineraryData () const override
const HexagonInstrInfo * getInstrInfo () const override
const HexagonRegisterInfo * getRegisterInfo () const override
const HexagonTargetLowering * getTargetLowering () const override
const HexagonFrameLowering * getFrameLowering () const override
const HexagonSelectionDAGInfo * getSelectionDAGInfo () const override
const DataLayout * getDataLayout () const override
HexagonSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool hasV2TOps () const
bool hasV2TOpsOnly () const
bool hasV3TOps () const
bool hasV3TOpsOnly () const
bool hasV4TOps () const
bool hasV4TOpsOnly () const
bool useMemOps () const
bool hasV5TOps () const
bool hasV5TOpsOnly () const
bool modeIEEERndNear () const
bool isSubtargetV2 () const
const std::string & getCPUString () const
unsigned getSmallDataThreshold () const
const HexagonArchEnum & getHexagonArchVersion () const
Public Attributes
HexagonArchEnum HexagonArchVersion
Detailed Description
Definition at line 34 of file HexagonSubtarget.h.
Member Enumeration Documentation
enum llvm::HexagonSubtarget::HexagonArchEnum
Enumerator
V1
V2
V3
V4
V5
Definition at line 41 of file HexagonSubtarget.h.
Constructor & Destructor Documentation
HexagonSubtarget::HexagonSubtarget (StringRef TT, StringRef CPU, StringRef FS, const TargetMachine & TM)
Definition at line 74 of file HexagonSubtarget.cpp.
References DisableMemOps, EnableIEEERndNear, and EnableMemOps.
Member Function Documentation
const std::string& llvm::HexagonSubtarget::getCPUString () const inline
Definition at line 98 of file HexagonSubtarget.h.
const DataLayout* llvm::HexagonSubtarget::getDataLayout () const inline override
Definition at line 77 of file HexagonSubtarget.h.
const HexagonFrameLowering* llvm::HexagonSubtarget::getFrameLowering () const inline override
Definition at line 71 of file HexagonSubtarget.h.
const HexagonArchEnum& llvm::HexagonSubtarget::getHexagonArchVersion () const inline
Definition at line 104 of file HexagonSubtarget.h.
References HexagonArchVersion.
Referenced by llvm::HexagonRegisterInfo::getCalleeSavedRegClasses(), and llvm::HexagonRegisterInfo::getCalleeSavedRegs().
const HexagonInstrInfo* llvm::HexagonSubtarget::getInstrInfo () const inline override
Definition at line 64 of file HexagonSubtarget.h.
Referenced by llvm::HexagonMCInst::getUnits().
const InstrItineraryData* llvm::HexagonSubtarget::getInstrItineraryData () const inline override
getInstrItins - Return the instruction itineraries based on subtarget selection.
Definition at line 61 of file HexagonSubtarget.h.
Referenced by llvm::HexagonMCInst::getUnits().
const HexagonRegisterInfo* llvm::HexagonSubtarget::getRegisterInfo () const inline override
Definition at line 65 of file HexagonSubtarget.h.
References llvm::HexagonInstrInfo::getRegisterInfo().
const HexagonSelectionDAGInfo* llvm::HexagonSubtarget::getSelectionDAGInfo () const inline override
Definition at line 74 of file HexagonSubtarget.h.
unsigned llvm::HexagonSubtarget::getSmallDataThreshold () const inline
Definition at line 101 of file HexagonSubtarget.h.
References Hexagon_SMALL_DATA_THRESHOLD.
const HexagonTargetLowering* llvm::HexagonSubtarget::getTargetLowering () const inline override
Definition at line 68 of file HexagonSubtarget.h.
bool llvm::HexagonSubtarget::hasV2TOps () const inline
Definition at line 86 of file HexagonSubtarget.h.
References HexagonArchVersion, and V2.
bool llvm::HexagonSubtarget::hasV2TOpsOnly () const inline
Definition at line 87 of file HexagonSubtarget.h.
References HexagonArchVersion, and V2.
bool llvm::HexagonSubtarget::hasV3TOps () const inline
Definition at line 88 of file HexagonSubtarget.h.
References HexagonArchVersion, and V3.
bool llvm::HexagonSubtarget::hasV3TOpsOnly () const inline
Definition at line 89 of file HexagonSubtarget.h.
References HexagonArchVersion, and V3.
bool llvm::HexagonSubtarget::hasV4TOps () const inline
Definition at line 90 of file HexagonSubtarget.h.
References HexagonArchVersion, and V4.
Referenced by areCombinableOperations(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::HexagonInstrInfo::isConditionalLoad(), llvm::HexagonInstrInfo::isConditionalStore(), llvm::HexagonInstrInfo::isConstExtended(), llvm::HexagonInstrInfo::isExtendable(), llvm::HexagonInstrInfo::isOperandExtended(), llvm::HexagonInstrInfo::isPredicable(), and llvm::HexagonInstrInfo::mayBeNewStore().
bool llvm::HexagonSubtarget::hasV4TOpsOnly () const inline
Definition at line 91 of file HexagonSubtarget.h.
References HexagonArchVersion, and V4.
bool llvm::HexagonSubtarget::hasV5TOps () const inline
Definition at line 93 of file HexagonSubtarget.h.
References HexagonArchVersion, and V5.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
bool llvm::HexagonSubtarget::hasV5TOpsOnly () const inline
Definition at line 94 of file HexagonSubtarget.h.
References HexagonArchVersion, and V5.
HexagonSubtarget & HexagonSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 52 of file HexagonSubtarget.cpp.
References EnableV3, HexagonArchVersion, llvm_unreachable, ParseSubtargetFeatures(), V2, V3, V4, and V5.
bool llvm::HexagonSubtarget::isSubtargetV2 () const inline
Definition at line 97 of file HexagonSubtarget.h.
References HexagonArchVersion, and V2.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
bool llvm::HexagonSubtarget::modeIEEERndNear () const inline
Definition at line 95 of file HexagonSubtarget.h.
void llvm::HexagonSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
Referenced by initializeSubtargetDependencies().
bool llvm::HexagonSubtarget::useMemOps () const inline
Definition at line 92 of file HexagonSubtarget.h.
References HexagonArchVersion, and V4.
Member Data Documentation
HexagonArchEnum llvm::HexagonSubtarget::HexagonArchVersion
Definition at line 45 of file HexagonSubtarget.h.
Referenced by getHexagonArchVersion(), hasV2TOps(), hasV2TOpsOnly(), hasV3TOps(), hasV3TOpsOnly(), hasV4TOps(), hasV4TOpsOnly(), hasV5TOps(), hasV5TOpsOnly(), initializeSubtargetDependencies(), isSubtargetV2(), and useMemOps().
The documentation for this class was generated from the following files:
HexagonSubtarget.h
HexagonSubtarget.cpp