LLVM: llvm::ConstantPool Class Reference
LLVM API Documentation
llvm::ConstantPool Class Reference
#include <ConstantPools.h>
Public Member Functions
ConstantPool ()
const MCExpr * addEntry (const MCExpr *Value, MCContext &Context, unsigned Size)
void emitEntries (MCStreamer &Streamer)
bool empty ()
Detailed Description
Definition at line 38 of file ConstantPools.h.
Constructor & Destructor Documentation
llvm::ConstantPool::ConstantPool () inline
Definition at line 44 of file ConstantPools.h.
Member Function Documentation
const MCExpr * ConstantPool::addEntry (const MCExpr * Value, MCContext & Context, unsigned Size)
Definition at line 38 of file ConstantPools.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCContext::CreateTempSymbol(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::AssemblerConstantPools::addEntry().
void ConstantPool::emitEntries (MCStreamer & Streamer)
Definition at line 24 of file ConstantPools.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::MCStreamer::EmitCodeAlignment(), llvm::MCStreamer::EmitDataRegion(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValue(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::MCDR_DataRegion, and llvm::MCDR_DataRegionEnd.
Referenced by emitConstantPool().
bool ConstantPool::empty ()
Definition at line 46 of file ConstantPools.cpp.
References llvm::SmallVectorBase::empty().
Referenced by emitConstantPool().
The documentation for this class was generated from the following files:
ConstantPools.h
ConstantPools.cpp