LLVM: llvm::object::Archive Class Reference
LLVM API Documentation
llvm::object::Archive Class Reference
#include <Archive.h>
Classes
class Child
class child_iterator
class Symbol
class symbol_iterator
Public Types
enum Kind { K_GNU, K_BSD, K_COFF }
Public Member Functions
Archive (MemoryBufferRef Source, std::error_code &EC)
Kind kind () const
child_iterator child_begin (bool SkipInternal=true) const
child_iterator child_end () const
iterator_range< child_iterator > children (bool SkipInternal=true) const
symbol_iterator symbol_begin () const
symbol_iterator symbol_end () const
child_iterator findSym (StringRef name) const
bool hasSymbolTable () const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isIR () const
bool isLittleEndian () const
Static Public Member Functions
static ErrorOr
< std::unique_ptr< Archive > > create (MemoryBufferRef Source)
static bool classof (Binary const *v)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_IR, ID_StartObjects,
ID_COFF, ID_ELF32L, ID_ELF32B, ID_ELF64L,
ID_ELF64B, ID_MachO32L, ID_MachO32B, ID_MachO64L,
ID_MachO64B, ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 48 of file Archive.h.
Member Enumeration Documentation
enum llvm::object::Archive::Kind
Enumerator
K_GNU
K_BSD
K_COFF
Definition at line 170 of file Archive.h.
Constructor & Destructor Documentation
Archive::Archive (MemoryBufferRef Source, std::error_code & EC)
Definition at line 197 of file Archive.cpp.
References child_begin(), child_end(), llvm::object::Binary::Data, llvm::ErrorOr< T >::get(), llvm::MemoryBufferRef::getBuffer(), llvm::ErrorOr< T >::getError(), llvm::object::Archive::Child::getName(), llvm::object::Archive::Child::getRawName(), llvm::object::invalid_file_type, K_BSD, K_COFF, K_GNU, Magic, Name, llvm::object::parse_failed, llvm::StringRef::startswith(), llvm::object::success, and ThinMagic.
Referenced by create().
Member Function Documentation
Archive::child_iterator Archive::child_begin (bool SkipInternal = true) const
Definition at line 318 of file Archive.cpp.
References child_end(), llvm::object::Binary::Data, llvm::MemoryBufferRef::getBufferSize(), llvm::MemoryBufferRef::getBufferStart(), Magic, and llvm::LibFunc::strlen.
Referenced by Archive(), and children().
Archive::child_iterator Archive::child_end () const
Definition at line 330 of file Archive.cpp.
Referenced by Archive(), child_begin(), children(), findSym(), llvm::MCJIT::getSymbolAddress(), and hasSymbolTable().
iterator_range<child_iterator> llvm::object::Archive::children (bool SkipInternal = true) const inline
Definition at line 180 of file Archive.h.
References child_begin(), and child_end().
static bool llvm::object::Archive::classof (Binary const * v) inline static
Definition at line 189 of file Archive.h.
References llvm::object::Binary::isArchive().
ErrorOr< std::unique_ptr< Archive > > Archive::create (MemoryBufferRef Source) static
Definition at line 189 of file Archive.cpp.
References Archive(), and llvm::MipsISD::Ret.
Referenced by llvm::object::createBinary(), and llvm::object::MachOUniversalBinary::ObjectForArch::getAsArchive().
Archive::child_iterator Archive::findSym (StringRef name) const
Definition at line 491 of file Archive.cpp.
References child_end(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::object::Archive::Symbol::getMember(), llvm::object::Archive::Symbol::getName(), symbol_begin(), and symbol_end().
Referenced by llvm::MCJIT::getSymbolAddress().
bool Archive::hasSymbolTable () const
Definition at line 508 of file Archive.cpp.
References child_end().
Referenced by symbol_begin(), and symbol_end().
Kind llvm::object::Archive::kind () const inline
Definition at line 176 of file Archive.h.
Referenced by symbol_begin(), and symbol_end().
Archive::symbol_iterator Archive::symbol_begin () const
Definition at line 432 of file Archive.cpp.
References llvm::StringRef::begin(), llvm::object::Archive::Child::getBuffer(), hasSymbolTable(), K_BSD, K_GNU, kind(), and llvm::ARMBuildAttrs::Symbol.
Referenced by findSym().
Archive::symbol_iterator Archive::symbol_end () const
Definition at line 470 of file Archive.cpp.
References llvm::StringRef::begin(), llvm::object::Archive::Child::getBuffer(), hasSymbolTable(), K_BSD, K_GNU, kind(), and llvm::ARMBuildAttrs::Symbol.
Referenced by findSym().
The documentation for this class was generated from the following files:
Archive.h
Archive.cpp