LLVM: llvm::LLVMTargetMachine Class Reference
LLVM API Documentation
llvm::LLVMTargetMachine Class Reference
#include <TargetMachine.h>
Public Member Functions
void addAnalysisPasses (PassManagerBase &PM) override
Register analysis passes for this target with a pass manager.
virtual TargetPassConfig * createPassConfig (PassManagerBase &PM)
bool addPassesToEmitFile (PassManagerBase &PM, formatted_raw_ostream &Out, CodeGenFileType FileType, bool DisableVerify=true, AnalysisID StartAfter=nullptr, AnalysisID StopAfter=nullptr) override
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_ostream &OS, bool DisableVerify=true) override
Public Member Functions inherited from llvm::TargetMachine
virtual ~TargetMachine ()
const Target & getTarget () const
StringRef getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
virtual const TargetSubtargetInfo * getSubtargetImpl () const
virtual const TargetSubtargetInfo * getSubtargetImpl (const Function &) const
virtual TargetLoweringObjectFile * getObjFileLowering () const
template<typename STC >
const STC & getSubtarget () const
template<typename STC >
const STC & getSubtarget (const Function *) const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
bool getAsmVerbosityDefault () const
void setAsmVerbosityDefault (bool)
bool getDataSections () const
bool getFunctionSections () const
void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
void setFunctionSections (bool)
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV, Mangler &Mang) const
Protected Member Functions
LLVMTargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Additional Inherited Members
Public Types inherited from llvm::TargetMachine
enum CodeGenFileType { CGFT_AssemblyFile, CGFT_ObjectFile, CGFT_Null }
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned RequireStructuredCFG: 1
Detailed Description
LLVMTargetMachine - This class describes a target machine that is implemented with the LLVM target-independent code generator.
Definition at line 230 of file Target/TargetMachine.h.
Constructor & Destructor Documentation
LLVMTargetMachine::LLVMTargetMachine (const Target & T, StringRef TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) protected
Definition at line 71 of file LLVMTargetMachine.cpp.
References llvm::TargetMachine::CodeGenInfo, and llvm::Target::createMCCodeGenInfo().
Member Function Documentation
void LLVMTargetMachine::addAnalysisPasses (PassManagerBase & PM) override virtual
Register analysis passes for this target with a pass manager.
This registers target independent analysis passes.
Reimplemented from llvm::TargetMachine.
Reimplemented in llvm::NVPTXTargetMachine, llvm::ARMBaseTargetMachine, llvm::AMDGPUTargetMachine, llvm::AArch64TargetMachine, llvm::PPCTargetMachine, llvm::MipsTargetMachine, llvm::X86TargetMachine, and llvm::XCoreTargetMachine.
Definition at line 80 of file LLVMTargetMachine.cpp.
References llvm::createBasicTargetTransformInfoPass().
Referenced by llvm::MipsTargetMachine::addAnalysisPasses(), and addPassesToGenerateCode().
bool LLVMTargetMachine::addPassesToEmitFile (PassManagerBase & PM, formatted_raw_ostream & Out, CodeGenFileType FileType, bool DisableVerify = true, AnalysisID StartAfter = nullptr, AnalysisID StopAfter = nullptr) override virtual
addPassesToEmitFile - Add passes to the specified pass manager to get the specified file emitted. Typically this will involve several steps of code generation.
Reimplemented from llvm::TargetMachine.
Definition at line 139 of file LLVMTargetMachine.cpp.
References addPassesToGenerateCode(), llvm::MCTargetOptions::AsmVerbose, llvm::TargetOptions::CFIEnforcing, llvm::TargetOptions::CFIType, llvm::TargetMachine::CGFT_AssemblyFile, llvm::TargetMachine::CGFT_Null, llvm::TargetMachine::CGFT_ObjectFile, llvm::Target::createAsmPrinter(), llvm::Target::createAsmStreamer(), llvm::createForwardControlFlowIntegrityPass(), llvm::createJumpInstrTableInfoPass(), llvm::createJumpInstrTablesPass(), llvm::Target::createMCAsmBackend(), llvm::Target::createMCCodeEmitter(), llvm::Target::createMCInstPrinter(), llvm::createNullStreamer(), llvm::createPrintModulePass(), llvm::TargetOptions::FCFI, llvm::TargetOptions::getCFIFuncName(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetMachine::getTarget(), llvm::TargetMachine::getTargetTriple(), llvm::TargetOptions::JTType, llvm::TargetOptions::MCOptions, llvm::MCTargetOptions::MCRelaxAll, llvm::MCTargetOptions::MCSaveTempLabels, llvm::MCTargetOptions::MCUseDwarfDirectory, llvm::TargetMachine::Options, Printer, llvm::MCAsmBackend::reset(), llvm::MCStreamer::reset(), llvm::MCContext::setAllowTemporaryLabels(), llvm::MCTargetOptions::ShowMCEncoding, llvm::MCTargetOptions::ShowMCInst, and llvm::TargetMachine::TargetCPU.
bool LLVMTargetMachine::addPassesToEmitMC (PassManagerBase & PM, MCContext *& Ctx, raw_ostream & Out, bool DisableVerify = true) override virtual
addPassesToEmitMC - Add passes to the specified pass manager to get machine code emitted with the MCJIT. This method returns true if machine code is not supported. It fills the MCContext Ctx pointer which can be used to build custom MCStreamer.
Reimplemented from llvm::TargetMachine.
Reimplemented in llvm::NVPTXTargetMachine.
Definition at line 241 of file LLVMTargetMachine.cpp.
References addPassesToGenerateCode(), llvm::Target::createAsmPrinter(), llvm::Target::createMCAsmBackend(), llvm::Target::createMCCodeEmitter(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetMachine::getTarget(), llvm::TargetMachine::getTargetTriple(), llvm::TargetOptions::MCOptions, llvm::MCTargetOptions::MCRelaxAll, llvm::MCTargetOptions::MCSaveTempLabels, llvm::TargetMachine::Options, Printer, llvm::MCAsmBackend::reset(), llvm::MCContext::setAllowTemporaryLabels(), and llvm::TargetMachine::TargetCPU.
TargetPassConfig * LLVMTargetMachine::createPassConfig (PassManagerBase & PM) virtual
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented in llvm::MipsTargetMachine, llvm::ARMBaseTargetMachine, llvm::AMDGPUTargetMachine, llvm::NVPTXTargetMachine, llvm::X86TargetMachine, llvm::AArch64TargetMachine, llvm::PPCTargetMachine, llvm::HexagonTargetMachine, llvm::SystemZTargetMachine, llvm::MSP430TargetMachine, llvm::SparcTargetMachine, and llvm::XCoreTargetMachine.
Definition at line 274 of file Passes.cpp.
Referenced by addPassesToGenerateCode().
void LLVMTargetMachine::initAsmInfo () protected
Definition at line 51 of file LLVMTargetMachine.cpp.
References llvm::TargetMachine::AsmInfo, assert(), llvm::TargetOptions::CompressDebugSections, llvm::Target::createMCAsmInfo(), llvm::TargetOptions::DisableIntegratedAS, llvm::TargetMachine::getSubtargetImpl(), llvm::TargetMachine::getTargetTriple(), llvm::TargetMachine::Options, llvm::MCAsmInfo::setCompressDebugSections(), llvm::MCAsmInfo::setUseIntegratedAssembler(), and llvm::TargetMachine::TheTarget.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::AMDGPUTargetMachine::AMDGPUTargetMachine(), llvm::ARMTargetMachine::ARMTargetMachine(), llvm::HexagonTargetMachine::HexagonTargetMachine(), llvm::MipsTargetMachine::MipsTargetMachine(), llvm::MSP430TargetMachine::MSP430TargetMachine(), llvm::NVPTXTargetMachine::NVPTXTargetMachine(), llvm::PPCTargetMachine::PPCTargetMachine(), llvm::SparcTargetMachine::SparcTargetMachine(), llvm::SystemZTargetMachine::SystemZTargetMachine(), llvm::ThumbTargetMachine::ThumbTargetMachine(), llvm::X86TargetMachine::X86TargetMachine(), and llvm::XCoreTargetMachine::XCoreTargetMachine().
The documentation for this class was generated from the following files:
Target/TargetMachine.h
LLVMTargetMachine.cpp
Passes.cpp