LLVM: llvm::CriticalAntiDepBreaker Class Reference
LLVM API Documentation
llvm::CriticalAntiDepBreaker Class Reference
#include <CriticalAntiDepBreaker.h>
Public Member Functions
CriticalAntiDepBreaker (MachineFunction &MFi, const RegisterClassInfo &)
~CriticalAntiDepBreaker ()
void StartBlock (MachineBasicBlock *BB) override
Initialize anti-dep breaking for a new basic block.
unsigned BreakAntiDependencies (const std::vector< SUnit > &SUnits, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned InsertPosIndex, DbgValueVector &DbgValues) override
void Observe (MachineInstr *MI, unsigned Count, unsigned InsertPosIndex) override
void FinishBlock () override
Finish anti-dep breaking for a basic block.
Public Member Functions inherited from llvm::AntiDepBreaker
virtual ~AntiDepBreaker ()
void UpdateDbgValue (MachineInstr *MI, unsigned OldReg, unsigned NewReg)
Additional Inherited Members
Public Types inherited from llvm::AntiDepBreaker
typedef std::vector< std::pair
< MachineInstr *, MachineInstr * > > DbgValueVector
Detailed Description
Definition at line 34 of file CriticalAntiDepBreaker.h.
Constructor & Destructor Documentation
CriticalAntiDepBreaker::CriticalAntiDepBreaker (MachineFunction & MFi, const RegisterClassInfo & RCI)
Definition at line 30 of file CriticalAntiDepBreaker.cpp.
CriticalAntiDepBreaker::~CriticalAntiDepBreaker ()
Definition at line 38 of file CriticalAntiDepBreaker.cpp.
Member Function Documentation
unsigned CriticalAntiDepBreaker::BreakAntiDependencies (const std::vector< SUnit > & SUnits, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned InsertPosIndex, DbgValueVector & DbgValues) override virtual
Identifiy anti-dependencies along the critical path of the ScheduleDAG and break them by renaming registers.
Implements llvm::AntiDepBreaker.
Definition at line 423 of file CriticalAntiDepBreaker.cpp.
References llvm::SDep::Anti, assert(), CriticalPathStep(), llvm::SDep::Data, llvm::dbgs(), DEBUG, llvm::SUnit::getDepth(), llvm::SUnit::getInstr(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::hasExtraDefRegAllocReq(), I, llvm::MachineRegisterInfo::isAllocatable(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineInstr::isKill(), llvm::TargetInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::SUnit::Latency, P, llvm::SUnit::Preds, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::BitVector::test(), and llvm::AntiDepBreaker::UpdateDbgValue().
void CriticalAntiDepBreaker::FinishBlock () override virtual
Finish anti-dep breaking for a basic block.
Implements llvm::AntiDepBreaker.
Definition at line 86 of file CriticalAntiDepBreaker.cpp.
References llvm::BitVector::reset().
void CriticalAntiDepBreaker::Observe (MachineInstr * MI, unsigned Count, unsigned InsertPosIndex) override virtual
Update liveness information to account for the current instruction, which will not be scheduled.
Implements llvm::AntiDepBreaker.
Definition at line 91 of file CriticalAntiDepBreaker.cpp.
References assert(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineInstr::isDebugValue(), and llvm::MachineInstr::isKill().
void CriticalAntiDepBreaker::StartBlock (MachineBasicBlock * BB) override virtual
Initialize anti-dep breaking for a new basic block.
Implements llvm::AntiDepBreaker.
Definition at line 41 of file CriticalAntiDepBreaker.cpp.
References llvm::MachineBasicBlock::back(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineFrameInfo::getPristineRegs(), I, llvm::MachineInstr::isReturn(), llvm::MCRegAliasIterator::isValid(), llvm::BitVector::reset(), SI, llvm::MachineBasicBlock::size(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), and llvm::BitVector::test().
The documentation for this class was generated from the following files:
CriticalAntiDepBreaker.h
CriticalAntiDepBreaker.cpp