LLVM: llvm::SmallPtrSetImpl< PtrType > Class Template Reference
LLVM API Documentation
llvm::SmallPtrSetImpl< PtrType > Class Template Reference
A templated base class for SmallPtrSet which provides the typesafe interface that is common across all small sizes.
#include <SmallPtrSet.h>
Public Types
typedef SmallPtrSetIterator
< PtrType > iterator
typedef SmallPtrSetIterator
< PtrType > const_iterator
Public Types inherited from llvm::SmallPtrSetImplBase
typedef unsigned size_type
Public Member Functions
std::pair< iterator, bool > insert (PtrType Ptr)
bool erase (PtrType Ptr)
size_type count (PtrType Ptr) const
count - Return 1 if the specified pointer is in the set, 0 otherwise.
template<typename IterT >
void insert (IterT I, IterT E)
iterator begin () const
iterator end () const
Public Member Functions inherited from llvm::SmallPtrSetImplBase
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
size_type size () const
void clear ()
Protected Member Functions
SmallPtrSetImpl (const void **SmallStorage, const SmallPtrSetImpl &that)
SmallPtrSetImpl (const void **SmallStorage, unsigned SmallSize, SmallPtrSetImpl &&that)
SmallPtrSetImpl (const void **SmallStorage, unsigned SmallSize)
Protected Member Functions inherited from llvm::SmallPtrSetImplBase
SmallPtrSetImplBase (const void **SmallStorage, const SmallPtrSetImplBase &that)
SmallPtrSetImplBase (const void **SmallStorage, unsigned SmallSize, SmallPtrSetImplBase &&that)
SmallPtrSetImplBase (const void **SmallStorage, unsigned SmallSize)
~SmallPtrSetImplBase ()
std::pair< const void *const
*, bool > insert_imp (const void *Ptr)
bool erase_imp (const void *Ptr)
bool count_imp (const void *Ptr) const
void swap (SmallPtrSetImplBase &RHS)
void CopyFrom (const SmallPtrSetImplBase &RHS)
void MoveFrom (unsigned SmallSize, SmallPtrSetImplBase &&RHS)
Additional Inherited Members
Static Protected Member Functions inherited from llvm::SmallPtrSetImplBase
static void * getTombstoneMarker ()
static void * getEmptyMarker ()
Protected Attributes inherited from llvm::SmallPtrSetImplBase
const void ** SmallArray
SmallArray - Points to a fixed size set of buckets, used in 'small mode'.
const void ** CurArray
unsigned CurArraySize
CurArraySize - The allocated size of CurArray, always a power of two.
unsigned NumElements
unsigned NumTombstones
Detailed Description
template<typename PtrType>
class llvm::SmallPtrSetImpl< PtrType >
A templated base class for SmallPtrSet which provides the typesafe interface that is common across all small sizes.
This is particularly useful for passing around between interface boundaries to avoid encoding a particular small size in the interface boundary.
Definition at line 242 of file SmallPtrSet.h.
Member Typedef Documentation
template<typename PtrType> typedef SmallPtrSetIterator<PtrType> llvm::SmallPtrSetImpl< PtrType >::const_iterator
Definition at line 258 of file SmallPtrSet.h.
template<typename PtrType> typedef SmallPtrSetIterator<PtrType> llvm::SmallPtrSetImpl< PtrType >::iterator
Definition at line 257 of file SmallPtrSet.h.
Constructor & Destructor Documentation
template<typename PtrType> llvm::SmallPtrSetImpl< PtrType >::SmallPtrSetImpl (const void ** SmallStorage, const SmallPtrSetImpl< PtrType > & that) inline protected
Definition at line 248 of file SmallPtrSet.h.
template<typename PtrType> llvm::SmallPtrSetImpl< PtrType >::SmallPtrSetImpl (const void ** SmallStorage, unsigned SmallSize, SmallPtrSetImpl< PtrType > && that) inline protected
Definition at line 250 of file SmallPtrSet.h.
template<typename PtrType> llvm::SmallPtrSetImpl< PtrType >::SmallPtrSetImpl (const void ** SmallStorage, unsigned SmallSize) inline explicit protected
Definition at line 253 of file SmallPtrSet.h.
Member Function Documentation
template<typename PtrType> iterator llvm::SmallPtrSetImpl< PtrType >::begin () const inline
Definition at line 286 of file SmallPtrSet.h.
References llvm::SmallPtrSetImplBase::CurArray, and llvm::SmallPtrSetImplBase::CurArraySize.
Referenced by llvm::ObjectSizeOffsetEvaluator::compute(), llvm::findPHICopyInsertPoint(), FindPredecessorAutoreleaseWithSafePath(), FindPredecessorRetainWithSafePath(), llvm::LeakDetectorImpl< llvm::Metadata >::hasGarbage(), PeepholePPC64ZExtGather(), and llvm::LLVMContextImpl::~LLVMContextImpl().
template<typename PtrType> size_type llvm::SmallPtrSetImpl< PtrType >::count (PtrType Ptr) const inline
count - Return 1 if the specified pointer is in the set, 0 otherwise.
Definition at line 276 of file SmallPtrSet.h.
References llvm::SmallPtrSetImplBase::count_imp().
Referenced by llvm::LeakDetectorImpl< llvm::Metadata >::addGarbage(), llvm::CodeMetrics::analyzeBasicBlock(), llvm::PreservedAnalyses::areAllPreserved(), areAllUsesIn(), bothUsedInPHI(), llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), CanPropagatePredecessorsForPHIs(), checkForCyclesHelper(), llvm::DomTreeNodeBase< NodeT >::compare(), completeEphemeralValues(), ComputePostOrders(), llvm::LoopBase< BasicBlock, Loop >::contains(), determinePointerReadAttrs(), DominatesMergePoint(), llvm::InstCombiner::DoOneIteration(), llvm::FindFunctionBackedges(), llvm::DominatorTreeBase< BasicBlock >::findNearestCommonDominator(), llvm::findPHICopyInsertPoint(), FoldTwoEntryPHINode(), hasMultipleUsesOf(), hasOutsideLoopUser(), llvm::SDNode::hasPredecessorHelper(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), llvm::PreservedAnalyses::intersect(), isEphemeralValueOf(), isProfitableToFoldUnconditional(), IsSafeAndProfitableToMove(), isSimplifiedLoopNest(), llvm::SelectionDAG::LegalizeOp(), LinearizeExprTree(), llvm::PreservedAnalyses::preserved(), llvm::removeUnreachableBlocks(), llvm::LiveVariables::runOnMachineFunction(), SafeToMergeTerminators(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), StripSymbolNames(), llvm::AssumptionCacheTracker::verifyAnalysis(), and llvm::InstCombiner::visitLandingPadInst().
template<typename PtrType> iterator llvm::SmallPtrSetImpl< PtrType >::end () const inline
Definition at line 289 of file SmallPtrSet.h.
References llvm::SmallPtrSetImplBase::CurArray, and llvm::SmallPtrSetImplBase::CurArraySize.
Referenced by llvm::ObjectSizeOffsetEvaluator::compute(), llvm::LeakDetectorImpl< llvm::Metadata >::hasGarbage(), and PeepholePPC64ZExtGather().
template<typename PtrType> bool llvm::SmallPtrSetImpl< PtrType >::erase (PtrType Ptr) inline
erase - If the set contains the specified pointer, remove it and return true, otherwise return false.
Definition at line 271 of file SmallPtrSet.h.
References llvm::SmallPtrSetImplBase::erase_imp().
Referenced by checkForCyclesHelper(), ComputePostOrders(), llvm::FindFunctionBackedges(), llvm::PreservedAnalyses::intersect(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::LoopBase< BasicBlock, Loop >::removeBlockFromLoop(), and llvm::LeakDetectorImpl< llvm::Metadata >::removeGarbage().
template<typename PtrType> std::pair<iterator, bool> llvm::SmallPtrSetImpl< PtrType >::insert (PtrType Ptr) inline
Inserts Ptr if and only if there is no element in the container equal to Ptr. The bool component of the returned pair is true if and only if the insertion takes place, and the iterator component of the pair points to the element equal to Ptr.
Definition at line 264 of file SmallPtrSet.h.
References llvm::SmallPtrSetImplBase::CurArray, llvm::SmallPtrSetImplBase::CurArraySize, and llvm::SmallPtrSetImplBase::insert_imp().
Referenced by AddAliasScopeMetadata(), llvm::LoopBase< BasicBlock, Loop >::addBlockEntry(), llvm::LeakDetectorImpl< llvm::Metadata >::addGarbage(), llvm::AArch64FunctionInfo::addLOHDirective(), AddReachableCodeToWorklist(), llvm::IVUsers::AddUsersImpl(), llvm::PreservedAnalyses::all(), AllUsesOfValueWillTrapIfNull(), analyzeGlobalAux(), AreAnyUnderlyingObjectsAnAlloca(), llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), canTrapImpl(), checkForCyclesHelper(), llvm::collectUsedGlobalVariables(), llvm::DomTreeNodeBase< NodeT >::compare(), completeEphemeralValues(), ComputePostOrders(), ConstantFoldConstantExpressionImpl(), ConstHasGlobalValuePredicate(), contains(), llvm::MachineBasicBlock::CorrectExtraCFGEdges(), cxxDtorIsEmpty(), DeadPHICycle(), DominatesMergePoint(), DumpNodesr(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::DwarfDebug::endFunction(), enqueueUsersInWorklist(), llvm::Eval(), extendSegmentsToUses(), llvm::CodeExtractor::extractCodeRegion(), llvm::DIBuilder::finalize(), findCallees(), llvm::objcarc::FindDependencies(), llvm::FindFunctionBackedges(), llvm::DominatorTreeBase< BasicBlock >::findNearestCommonDominator(), findNonImmUse(), llvm::findPHICopyInsertPoint(), FindUsedValues(), findUsedValues(), FoldBlockIntoPredecessor(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), getAdjustedPtr(), llvm::LexicalScopes::getMachineBasicBlocks(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), GetStringLengthH(), getUnderlyingObjects(), llvm::GetUnderlyingObjects(), HandleInlinedInvoke(), hasConcreteDef(), hasConcreteDefImpl(), llvm::SDNode::hasPredecessorHelper(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), InlineCallIfPossible(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), isDereferenceablePointer(), isEphemeralValueOf(), isHighCostExpansion(), isSafeToMove(), isSimpleEnoughValueToCommit(), isSimplifiedLoopNest(), llvm::StructType::isSized(), IsStoredObjCPointer(), iterateChainSucc(), llvm::LazyCallGraph::LazyCallGraph(), llvm::SelectionDAG::Legalize(), llvm::SelectionDAG::LegalizeOp(), LinearizeExprTree(), LoadUsesSimpleEnoughForHeapSRA(), llvm::LoopBase< BasicBlock, Loop >::LoopBase(), markAliveBlocks(), MarkBlocksLiveIn(), llvm::SelectionDAG::MorphNodeTo(), llvm::ARMBaseInstrInfo::optimizeSelect(), PeepholePPC64ZExtGather(), PHIsEqualValue(), llvm::PreservedAnalyses::preserve(), printNodes(), pushIVUsers(), llvm::RecursivelyDeleteDeadPHINode(), llvm::LiveRange::RenumberValues(), llvm::LazyCallGraphPrinterPass::run(), searchForVNI(), simplifyOneLoop(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SmallPtrSet< const T *, 8 >::SmallPtrSet(), sortOpts(), llvm::Value::stripAndAccumulateInBoundsConstantOffsets(), stripAndComputeConstantOffsets(), llvm::IVStrideUse::transformToPostInc(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::AssumptionCacheTracker::verifyAnalysis(), llvm::LoopBase< N, M >::verifyLoop(), llvm::InstCombiner::visitLandingPadInst(), and llvm::InstCombiner::visitPHINode().
template<typename PtrType> template<typename IterT > void llvm::SmallPtrSetImpl< PtrType >::insert (IterT I, IterT E) inline
Definition at line 281 of file SmallPtrSet.h.
References I, and llvm::SmallPtrSetImpl< PtrType >::insert().
The documentation for this class was generated from the following file:
SmallPtrSet.h