LLVM: llvm::MipsFunctionInfo Class Reference
LLVM API Documentation
llvm::MipsFunctionInfo Class Reference
#include <MipsMachineFunction.h>
Public Member Functions
MipsFunctionInfo (MachineFunction &MF)
~MipsFunctionInfo ()
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
bool globalBaseRegSet () const
unsigned getGlobalBaseReg ()
bool mips16SPAliasRegSet () const
unsigned getMips16SPAliasReg ()
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
bool hasByvalArg () const
void setFormalArgInfo (unsigned Size, bool HasByval)
unsigned getIncomingArgSize () const
bool callsEhReturn () const
void setCallsEhReturn ()
void createEhDataRegsFI ()
int getEhDataRegFI (unsigned Reg) const
bool isEhDataRegFI (int FI) const
MachinePointerInfo callPtrInfo (StringRef Name)
Create a MachinePointerInfo that has a MipsCallEntr object representing a GOT entry for an external function.
MachinePointerInfo callPtrInfo (const GlobalValue *Val)
Create a MachinePointerInfo that has a MipsCallEntr object representing a GOT entry for a global function.
void setSaveS2 ()
bool hasSaveS2 () const
int getMoveF64ViaSpillFI (const TargetRegisterClass *RC)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Public Attributes
std::map< const char *, const
llvm::Mips16HardFloatInfo::FuncSignature * > StubsNeeded
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
MipsFunctionInfo - This class is derived from MachineFunction private Mips target-specific information for each MachineFunction.
Definition at line 53 of file MipsMachineFunction.h.
Constructor & Destructor Documentation
llvm::MipsFunctionInfo::MipsFunctionInfo (MachineFunction & MF) inline
Definition at line 55 of file MipsMachineFunction.h.
MipsFunctionInfo::~MipsFunctionInfo ()
Definition at line 62 of file MipsMachineFunction.cpp.
References I.
Member Function Documentation
MachinePointerInfo MipsFunctionInfo::callPtrInfo (StringRef Name)
Create a MachinePointerInfo that has a MipsCallEntr object representing a GOT entry for an external function.
Definition at line 118 of file MipsMachineFunction.cpp.
References Name.
MachinePointerInfo MipsFunctionInfo::callPtrInfo (const GlobalValue * Val)
Create a MachinePointerInfo that has a MipsCallEntr object representing a GOT entry for a global function.
Definition at line 127 of file MipsMachineFunction.cpp.
bool llvm::MipsFunctionInfo::callsEhReturn () const inline
Definition at line 82 of file MipsMachineFunction.h.
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), and llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan().
void MipsFunctionInfo::createEhDataRegsFI ()
Definition at line 102 of file MipsMachineFunction.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), I, llvm::MipsSubtarget::isABI_N64(), and llvm::AArch64DB::ST.
Referenced by llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan().
int llvm::MipsFunctionInfo::getEhDataRegFI (unsigned Reg) const inline
Definition at line 86 of file MipsMachineFunction.h.
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), and llvm::MipsSEFrameLowering::emitPrologue().
unsigned MipsFunctionInfo::getGlobalBaseReg ()
Definition at line 76 of file MipsMachineFunction.cpp.
References llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isABI_N64(), and llvm::AArch64DB::ST.
Referenced by llvm::MipsTargetLowering::getGlobalReg().
unsigned llvm::MipsFunctionInfo::getIncomingArgSize () const inline
Definition at line 80 of file MipsMachineFunction.h.
unsigned MipsFunctionInfo::getMips16SPAliasReg ()
Definition at line 93 of file MipsMachineFunction.cpp.
References llvm::MachineRegisterInfo::createVirtualRegister(), and llvm::MachineFunction::getRegInfo().
int MipsFunctionInfo::getMoveF64ViaSpillFI (const TargetRegisterClass * RC)
Definition at line 136 of file MipsMachineFunction.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), and llvm::TargetRegisterClass::getSize().
unsigned llvm::MipsFunctionInfo::getSRetReturnReg () const inline
Definition at line 62 of file MipsMachineFunction.h.
int llvm::MipsFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 71 of file MipsMachineFunction.h.
bool MipsFunctionInfo::globalBaseRegSet () const
Definition at line 72 of file MipsMachineFunction.cpp.
bool llvm::MipsFunctionInfo::hasByvalArg () const inline
Definition at line 74 of file MipsMachineFunction.h.
bool llvm::MipsFunctionInfo::hasSaveS2 () const inline
Definition at line 98 of file MipsMachineFunction.h.
Referenced by llvm::MipsRegisterInfo::getReservedRegs().
bool MipsFunctionInfo::isEhDataRegFI (int FI) const
Definition at line 113 of file MipsMachineFunction.cpp.
bool MipsFunctionInfo::mips16SPAliasRegSet () const
Definition at line 90 of file MipsMachineFunction.cpp.
void llvm::MipsFunctionInfo::setCallsEhReturn () inline
Definition at line 83 of file MipsMachineFunction.h.
void llvm::MipsFunctionInfo::setFormalArgInfo (unsigned Size, bool HasByval) inline
Definition at line 75 of file MipsMachineFunction.h.
void llvm::MipsFunctionInfo::setSaveS2 () inline
Definition at line 97 of file MipsMachineFunction.h.
void llvm::MipsFunctionInfo::setSRetReturnReg (unsigned Reg) inline
Definition at line 63 of file MipsMachineFunction.h.
void llvm::MipsFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 72 of file MipsMachineFunction.h.
Member Data Documentation
std::map<const char *, const llvm::Mips16HardFloatInfo::FuncSignature *> llvm::MipsFunctionInfo::StubsNeeded
Definition at line 103 of file MipsMachineFunction.h.
Referenced by llvm::MipsAsmPrinter::runOnMachineFunction().
The documentation for this class was generated from the following files:
MipsMachineFunction.h
MipsMachineFunction.cpp