LLVM: llvm::GCRelocateOperands Class Reference
LLVM API Documentation
llvm::GCRelocateOperands Class Reference
#include <Statepoint.h>
Public Member Functions
GCRelocateOperands (const User *U)
GCRelocateOperands (const Instruction *inst)
GCRelocateOperands (CallSite CS)
const Instruction * statepoint ()
The statepoint with which this gc.relocate is associated.
int basePtrIndex ()
int derivedPtrIndex ()
Value * basePtr ()
Value * derivedPtr ()
Detailed Description
Wraps a call to a gc.relocate and provides access to it's operands. TODO: This should likely be refactored to resememble the wrappers in InstrinsicInst.h.
Definition at line 176 of file Statepoint.h.
Constructor & Destructor Documentation
llvm::GCRelocateOperands::GCRelocateOperands (const User * U) inline
Definition at line 180 of file Statepoint.h.
References assert(), and llvm::isGCRelocate().
llvm::GCRelocateOperands::GCRelocateOperands (const Instruction * inst) inline
Definition at line 183 of file Statepoint.h.
References assert(), and llvm::isGCRelocate().
llvm::GCRelocateOperands::GCRelocateOperands (CallSite CS) inline
Definition at line 186 of file Statepoint.h.
References assert(), and llvm::isGCRelocate().
Member Function Documentation
Value* llvm::GCRelocateOperands::basePtr () inline
Definition at line 205 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), basePtrIndex(), and statepoint().
Referenced by getIncomingStatepointGCValues().
int llvm::GCRelocateOperands::basePtrIndex () inline
The index into the associate statepoint's argument list which contains the base pointer of the pointer whose relocation this gc.relocate describes.
Definition at line 197 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument().
Referenced by basePtr().
Value* llvm::GCRelocateOperands::derivedPtr () inline
Definition at line 209 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), derivedPtrIndex(), and statepoint().
Referenced by getIncomingStatepointGCValues(), and llvm::InstCombiner::visitCallInst().
int llvm::GCRelocateOperands::derivedPtrIndex () inline
The index into the associate statepoint's argument list which contains the pointer whose relocation this gc.relocate describes.
Definition at line 202 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument().
Referenced by derivedPtr().
const Instruction* llvm::GCRelocateOperands::statepoint () inline
The statepoint with which this gc.relocate is associated.
Definition at line 191 of file Statepoint.h.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument().
Referenced by basePtr(), and derivedPtr().
The documentation for this class was generated from the following file:
Statepoint.h