LLVM: llvm::Argument Class Reference
LLVM API Documentation
llvm::Argument Class Reference
LLVM Argument representation.
#include <Argument.h>
Public Member Functions
Argument (Type *Ty, const Twine &Name="", Function *F=nullptr)
Constructor.
const Function * getParent () const
Function * getParent ()
unsigned getArgNo () const
Return the index of this formal argument in its containing function.
bool hasNonNullAttr () const
Return true if this argument has the nonnull attribute on it in its containing function. Also returns true if at least one byte is known to be dereferenceable and the pointer is in addrspace(0).
uint64_t getDereferenceableBytes () const
If this argument has the dereferenceable attribute on it in its containing function, return the number of bytes known to be dereferenceable. Otherwise, zero is returned.
bool hasByValAttr () const
Return true if this argument has the byval attribute on it in its containing function.
bool hasByValOrInAllocaAttr () const
Return true if this argument has the byval attribute or inalloca attribute on it in its containing function. These attributes both represent arguments being passed by value.
unsigned getParamAlignment () const
If this is a byval or inalloca argument, return its alignment.
bool hasNestAttr () const
Return true if this argument has the nest attribute on it in its containing function.
bool hasNoAliasAttr () const
Return true if this argument has the noalias attribute on it in its containing function.
bool hasNoCaptureAttr () const
Return true if this argument has the nocapture attribute on it in its containing function.
bool hasStructRetAttr () const
Return true if this argument has the sret attribute on it in its containing function.
bool hasReturnedAttr () const
Return true if this argument has the returned attribute on it in its containing function.
bool onlyReadsMemory () const
Return true if this argument has the readonly or readnone attribute on it in its containing function.
bool hasInAllocaAttr () const
Return true if this argument has the inalloca attribute on it in its containing function.
bool hasZExtAttr () const
Return true if this argument has the zext attribute on it in its containing function.
bool hasSExtAttr () const
Return true if this argument has the sext attribute on it in its containing function.
void addAttr (AttributeSet AS)
Add a Attribute to an argument.
void removeAttr (AttributeSet AS)
Remove a Attribute from an argument.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range
< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range
< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Public Member Functions inherited from llvm::ilist_node< Argument >
Argument * getPrevNode ()
Get the previous node, or 0 for the list head.
const Argument * getPrevNode () const
Get the previous node, or 0 for the list head.
Argument * getNextNode ()
Get the next node, or 0 for the list tail.
const Argument * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const Value *V)
Method for support type inquiry through isa, cast, and dyn_cast.
Friends
class SymbolTableListTraits< Argument, Function >
Additional Inherited Members
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MetadataAsValueVal, InlineAsmVal, InstructionVal,
ConstantFirstVal = FunctionVal, ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl
< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl
< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Argument >
ilist_node ()
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
LLVM Argument representation.
This class represents an incoming formal argument to a Function. A formal argument, since it is ``formal'', does not contain an actual value but instead represents the type, argument number, and attributes of an argument for a specific function. When used in the body of said function, the argument of course represents the value of the actual argument that the function was called with.
Definition at line 35 of file Argument.h.
Constructor & Destructor Documentation
Argument::Argument (Type * Ty, const Twine & Name = "", Function * F = nullptr) explicit
Constructor.
If F is specified, the argument is inserted at the end of the argument list for F.
Definition at line 44 of file Function.cpp.
References llvm::Function::getArgumentList(), llvm::iplist< NodeTy, Traits >::push_back(), and llvm::Value::setName().
Member Function Documentation
void Argument::addAttr (AttributeSet AS)
Add a Attribute to an argument.
addAttr - Add attributes to an argument.
Definition at line 185 of file Function.cpp.
References llvm::Function::addAttributes(), assert(), getArgNo(), llvm::Function::getContext(), llvm::AttributeSet::getNumSlots(), getParent(), and llvm::AttributeSet::getSlotIndex().
Referenced by LLVMAddAttribute(), and LLVMSetParamAlignment().
static bool llvm::Argument::classof (const Value * V) inline static
Method for support type inquiry through isa, cast, and dyn_cast.
Definition at line 124 of file Argument.h.
References llvm::Value::ArgumentVal, and llvm::Value::getValueID().
unsigned Argument::getArgNo () const
Return the index of this formal argument in its containing function.
For example in "void foo(int a, float b)" a is 0 and b is 1.
getArgNo - Return the index of this formal argument in its containing function. For example in "void foo(int a, float b)" a is 0 and b is 1.
Definition at line 59 of file Function.cpp.
References llvm::Function::arg_begin(), assert(), F(), and getParent().
Referenced by addAttr(), AllCallersPassInValidPointerForArgument(), getDereferenceableBytes(), getParamAlignment(), hasByValAttr(), hasByValOrInAllocaAttr(), hasInAllocaAttr(), hasNestAttr(), hasNoAliasAttr(), hasNoCaptureAttr(), hasNonNullAttr(), hasReturnedAttr(), hasSExtAttr(), hasZExtAttr(), LLVMAddAttribute(), LLVMGetAttribute(), LLVMRemoveAttribute(), LLVMSetParamAlignment(), onlyReadsMemory(), and removeAttr().
uint64_t Argument::getDereferenceableBytes () const
If this argument has the dereferenceable attribute on it in its containing function, return the number of bytes known to be dereferenceable. Otherwise, zero is returned.
Definition at line 114 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getDereferenceableBytes(), getParent(), and llvm::Value::getType().
Referenced by hasNonNullAttr().
unsigned Argument::getParamAlignment () const
If this is a byval or inalloca argument, return its alignment.
Definition at line 108 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamAlignment(), getParent(), and llvm::Value::getType().
Referenced by llvm::ObjectSizeOffsetVisitor::visitArgument().
const Function* llvm::Argument::getParent () const inline
Definition at line 49 of file Argument.h.
Referenced by addAttr(), AllCallersPassInValidPointerForArgument(), getArgNo(), getDereferenceableBytes(), getParamAlignment(), hasByValAttr(), hasByValOrInAllocaAttr(), hasInAllocaAttr(), hasNestAttr(), hasNoAliasAttr(), hasNoCaptureAttr(), hasNonNullAttr(), hasReturnedAttr(), hasSExtAttr(), hasStructRetAttr(), hasZExtAttr(), isOnlyUsedInEntryBlock(), LLVMGetAttribute(), LLVMGetNextParam(), LLVMGetPreviousParam(), onlyReadsMemory(), and removeAttr().
Function* llvm::Argument::getParent () inline
Definition at line 50 of file Argument.h.
bool Argument::hasByValAttr () const
Return true if this argument has the byval attribute on it in its containing function.
hasByValAttr - Return true if this argument has the byval attribute on it in its containing function.
Definition at line 87 of file Function.cpp.
References llvm::Attribute::ByVal, getArgNo(), llvm::Function::getAttributes(), getParent(), and llvm::Value::getType().
bool Argument::hasByValOrInAllocaAttr () const
Return true if this argument has the byval attribute or inalloca attribute on it in its containing function. These attributes both represent arguments being passed by value.
Definition at line 101 of file Function.cpp.
References llvm::Attribute::ByVal, getArgNo(), llvm::Function::getAttributes(), getParent(), llvm::Value::getType(), llvm::AttributeSet::hasAttribute(), and llvm::Attribute::InAlloca.
Referenced by llvm::ObjectSizeOffsetVisitor::visitArgument().
bool Argument::hasInAllocaAttr () const
Return true if this argument has the inalloca attribute on it in its containing function.
Definition at line 95 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), llvm::Value::getType(), and llvm::Attribute::InAlloca.
Referenced by determinePointerReadAttrs().
bool Argument::hasNestAttr () const
Return true if this argument has the nest attribute on it in its containing function.
hasNestAttr - Return true if this argument has the nest attribute on it in its containing function.
Definition at line 122 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), llvm::Value::getType(), and llvm::Attribute::Nest.
bool Argument::hasNoAliasAttr () const
Return true if this argument has the noalias attribute on it in its containing function.
hasNoAliasAttr - Return true if this argument has the noalias attribute on it in its containing function.
Definition at line 130 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), llvm::Value::getType(), and llvm::Attribute::NoAlias.
bool Argument::hasNoCaptureAttr () const
Return true if this argument has the nocapture attribute on it in its containing function.
hasNoCaptureAttr - Return true if this argument has the nocapture attribute on it in its containing function.
Definition at line 138 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), llvm::Value::getType(), and llvm::Attribute::NoCapture.
bool Argument::hasNonNullAttr () const
Return true if this argument has the nonnull attribute on it in its containing function. Also returns true if at least one byte is known to be dereferenceable and the pointer is in addrspace(0).
hasNonNullAttr - Return true if this argument has the nonnull attribute on it in its containing function. Also returns true if at least one byte is known to be dereferenceable and the pointer is in addrspace(0).
Definition at line 74 of file Function.cpp.
References getArgNo(), llvm::Intrinsic::getAttributes(), getDereferenceableBytes(), getParent(), llvm::Value::getType(), and llvm::Attribute::NonNull.
bool Argument::hasReturnedAttr () const
Return true if this argument has the returned attribute on it in its containing function.
hasReturnedAttr - Return true if this argument has the returned attribute on it in its containing function.
Definition at line 156 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), and llvm::Attribute::Returned.
bool Argument::hasSExtAttr () const
Return true if this argument has the sext attribute on it in its containing function.
hasSExtAttr Return true if this argument has the sext attribute on it in its containing function.
Definition at line 170 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), and llvm::Attribute::SExt.
bool Argument::hasStructRetAttr () const
Return true if this argument has the sret attribute on it in its containing function.
hasSRetAttr - Return true if this argument has the sret attribute on it in its containing function.
Definition at line 146 of file Function.cpp.
References llvm::Function::getAttributes(), getParent(), llvm::Value::getType(), and llvm::Attribute::StructRet.
bool Argument::hasZExtAttr () const
Return true if this argument has the zext attribute on it in its containing function.
hasZExtAttr - Return true if this argument has the zext attribute on it in its containing function.
Definition at line 163 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), and llvm::Attribute::ZExt.
bool Argument::onlyReadsMemory () const
Return true if this argument has the readonly or readnone attribute on it in its containing function.
Return true if this argument has the readonly or readnone attribute on it in its containing function.
Definition at line 177 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getParent(), llvm::Attribute::ReadNone, and llvm::Attribute::ReadOnly.
void Argument::removeAttr (AttributeSet AS)
Remove a Attribute from an argument.
removeAttr - Remove attributes from an argument.
Definition at line 195 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getContext(), llvm::AttributeSet::getNumSlots(), getParent(), llvm::AttributeSet::getSlotIndex(), and llvm::Function::removeAttributes().
Referenced by LLVMRemoveAttribute().
Friends And Related Function Documentation
friend class SymbolTableListTraits< Argument, Function > friend
Definition at line 39 of file Argument.h.
The documentation for this class was generated from the following files:
Argument.h
Function.cpp