LLVM: llvm::DwarfStringPool Class Reference
LLVM API Documentation
llvm::DwarfStringPool Class Reference
#include <DwarfStringPool.h>
Public Member Functions
DwarfStringPool (BumpPtrAllocator &A, AsmPrinter &Asm, StringRef Prefix)
void emit (AsmPrinter &Asm, const MCSection *StrSection, const MCSection *OffsetSection=nullptr)
MCSymbol * getSymbol (AsmPrinter &Asm, StringRef Str)
Returns an entry into the string pool with the given string text.
unsigned getIndex (AsmPrinter &Asm, StringRef Str)
Returns the index into the string pool with the given string text.
bool empty () const
Detailed Description
Definition at line 27 of file DwarfStringPool.h.
Constructor & Destructor Documentation
llvm::DwarfStringPool::DwarfStringPool (BumpPtrAllocator & A, AsmPrinter & Asm, StringRef Prefix) inline
Definition at line 32 of file DwarfStringPool.h.
Member Function Documentation
void DwarfStringPool::emit (AsmPrinter & Asm, const MCSection * StrSection, const MCSection * OffsetSection = nullptr)
Definition at line 35 of file DwarfStringPool.cpp.
References llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::AsmPrinter::OutStreamer, and llvm::MCStreamer::SwitchSection().
Referenced by llvm::DwarfFile::emitStrings().
bool llvm::DwarfStringPool::empty () const inline
Definition at line 46 of file DwarfStringPool.h.
unsigned DwarfStringPool::getIndex (AsmPrinter & Asm, StringRef Str)
Returns the index into the string pool with the given string text.
Definition at line 31 of file DwarfStringPool.cpp.
References getEntry().
Referenced by llvm::DwarfUnit::addIndexedString().
MCSymbol * DwarfStringPool::getSymbol (AsmPrinter & Asm, StringRef Str)
Returns an entry into the string pool with the given string text.
Definition at line 27 of file DwarfStringPool.cpp.
References getEntry().
Referenced by llvm::DwarfDebug::addAccelName(), llvm::DwarfDebug::addAccelNamespace(), llvm::DwarfDebug::addAccelObjC(), llvm::DwarfDebug::addAccelType(), and llvm::DwarfUnit::addLocalString().
The documentation for this class was generated from the following files:
DwarfStringPool.h
DwarfStringPool.cpp