LLVM: llvm::SystemZSubtarget Class Reference
LLVM API Documentation
llvm::SystemZSubtarget Class Reference
#include <SystemZSubtarget.h>
Public Member Functions
SystemZSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
const TargetFrameLowering * getFrameLowering () const override
const SystemZInstrInfo * getInstrInfo () const override
const DataLayout * getDataLayout () const override
const SystemZRegisterInfo * getRegisterInfo () const override
const SystemZTargetLowering * getTargetLowering () const override
const TargetSelectionDAGInfo * getSelectionDAGInfo () const override
bool useAA () const override
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool hasDistinctOps () const
bool hasLoadStoreOnCond () const
bool hasHighWord () const
bool hasFPExtension () const
bool hasFastSerialization () const
bool hasInterlockedAccess1 () const
bool isPC32DBLSymbol (const GlobalValue *GV, Reloc::Model RM, CodeModel::Model CM) const
bool isTargetELF () const
Protected Attributes
bool HasDistinctOps
bool HasLoadStoreOnCond
bool HasHighWord
bool HasFPExtension
bool HasFastSerialization
bool HasInterlockedAccess1
Detailed Description
Definition at line 34 of file SystemZSubtarget.h.
Constructor & Destructor Documentation
SystemZSubtarget::SystemZSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
Definition at line 40 of file SystemZSubtarget.cpp.
Member Function Documentation
const DataLayout* llvm::SystemZSubtarget::getDataLayout () const inline override
Definition at line 62 of file SystemZSubtarget.h.
const TargetFrameLowering* llvm::SystemZSubtarget::getFrameLowering () const inline override
Definition at line 58 of file SystemZSubtarget.h.
const SystemZInstrInfo* llvm::SystemZSubtarget::getInstrInfo () const inline override
Definition at line 61 of file SystemZSubtarget.h.
const SystemZRegisterInfo* llvm::SystemZSubtarget::getRegisterInfo () const inline override
Definition at line 63 of file SystemZSubtarget.h.
References llvm::SystemZInstrInfo::getRegisterInfo().
const TargetSelectionDAGInfo* llvm::SystemZSubtarget::getSelectionDAGInfo () const inline override
Definition at line 69 of file SystemZSubtarget.h.
const SystemZTargetLowering* llvm::SystemZSubtarget::getTargetLowering () const inline override
Definition at line 66 of file SystemZSubtarget.h.
bool llvm::SystemZSubtarget::hasDistinctOps () const inline
Definition at line 80 of file SystemZSubtarget.h.
References HasDistinctOps.
Referenced by llvm::SystemZInstrInfo::convertToThreeAddress().
bool llvm::SystemZSubtarget::hasFastSerialization () const inline
Definition at line 92 of file SystemZSubtarget.h.
References HasFastSerialization.
Referenced by llvm::SystemZAsmPrinter::EmitInstruction().
bool llvm::SystemZSubtarget::hasFPExtension () const inline
Definition at line 89 of file SystemZSubtarget.h.
References HasFPExtension.
Referenced by llvm::SystemZTargetLowering::SystemZTargetLowering().
bool llvm::SystemZSubtarget::hasHighWord () const inline
Definition at line 86 of file SystemZSubtarget.h.
References HasHighWord.
Referenced by llvm::SystemZTargetLowering::SystemZTargetLowering().
bool llvm::SystemZSubtarget::hasInterlockedAccess1 () const inline
Definition at line 95 of file SystemZSubtarget.h.
References HasInterlockedAccess1.
bool llvm::SystemZSubtarget::hasLoadStoreOnCond () const inline
Definition at line 83 of file SystemZSubtarget.h.
References HasLoadStoreOnCond.
Referenced by llvm::SystemZInstrInfo::isPredicable(), and llvm::SystemZInstrInfo::PredicateInstruction().
bool SystemZSubtarget::isPC32DBLSymbol (const GlobalValue * GV, Reloc::Model RM, CodeModel::Model CM) const
Definition at line 64 of file SystemZSubtarget.cpp.
References bindsLocally(), llvm::GlobalValue::getAlignment(), and llvm::CodeModel::Small.
bool llvm::SystemZSubtarget::isTargetELF () const inline
Definition at line 102 of file SystemZSubtarget.h.
References llvm::Triple::isOSBinFormatELF().
Referenced by llvm::SystemZAsmPrinter::EmitEndOfAsmFile().
void llvm::SystemZSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool llvm::SystemZSubtarget::useAA () const inline override
Definition at line 74 of file SystemZSubtarget.h.
Member Data Documentation
bool llvm::SystemZSubtarget::HasDistinctOps protected
Definition at line 37 of file SystemZSubtarget.h.
Referenced by hasDistinctOps().
bool llvm::SystemZSubtarget::HasFastSerialization protected
Definition at line 41 of file SystemZSubtarget.h.
Referenced by hasFastSerialization().
bool llvm::SystemZSubtarget::HasFPExtension protected
Definition at line 40 of file SystemZSubtarget.h.
Referenced by hasFPExtension().
bool llvm::SystemZSubtarget::HasHighWord protected
Definition at line 39 of file SystemZSubtarget.h.
Referenced by hasHighWord().
bool llvm::SystemZSubtarget::HasInterlockedAccess1 protected
Definition at line 42 of file SystemZSubtarget.h.
Referenced by hasInterlockedAccess1().
bool llvm::SystemZSubtarget::HasLoadStoreOnCond protected
Definition at line 38 of file SystemZSubtarget.h.
Referenced by hasLoadStoreOnCond().
The documentation for this class was generated from the following files:
SystemZSubtarget.h
SystemZSubtarget.cpp