LLVM: llvm::X86AsmPrinter Class Reference
LLVM API Documentation
llvm::X86AsmPrinter Class Reference
#include <X86AsmPrinter.h>
Public Member Functions
X86AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
const char * getPassName () const override
const X86Subtarget & getSubtarget () const
void EmitStartOfAsmFile (Module &M) override
void EmitEndOfAsmFile (Module &M) override
void EmitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
void EmitBasicBlockEnd (const MachineBasicBlock &MBB) override
Targets can override this to emit stuff at the end of a basic block.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS) override
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS) override
MCSymbol * GetCPISymbol (unsigned CPID) const override
Return the symbol for the specified constant pool entry.
bool doInitialization (Module &M) override
bool runOnMachineFunction (MachineFunction &F) override
Public Member Functions inherited from llvm::AsmPrinter
virtual ~AsmPrinter ()
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
bool isVerbose () const
unsigned getFunctionNumber () const
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
StringRef getTargetTriple () const
Return the target triple string.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool doFinalization (Module &M) override
void SetupMachineFunction (MachineFunction &MF)
void EmitFunctionHeader ()
This method emits the header for the current function.
void EmitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
CFIMoveType needsCFIMoves ()
bool needsSEHMoves ()
virtual void EmitConstantPool ()
void EmitJumpTableInfo ()
virtual void EmitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
void EmitAlignment (unsigned NumBits, const GlobalObject *GO=nullptr) const
void EmitBasicBlockStart (const MachineBasicBlock &MBB) const
const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void EmitGlobalConstant (const Constant *CV)
Print a general LLVM constant to the .s file.
virtual void EmitFunctionBodyStart ()
virtual void EmitFunctionBodyEnd ()
virtual void EmitFunctionEntryLabel ()
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void EmitXXStructor (const Constant *CV)
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
virtual void emitImplicitDef (const MachineInstr *MI) const
MCSymbol * GetTempSymbol (Twine Name, unsigned ID) const
MCSymbol * GetTempSymbol (Twine Name) const
Return an assembler temporary label with the specified stem.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void EmitInt8 (int Value) const
void EmitInt16 (int Value) const
void EmitInt32 (int Value) const
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
void EmitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void EmitCFAByte (unsigned Val) const
Emit a .byte 42 directive for a DW_CFA_xxx value.
void EmitEncodingByte (unsigned Val, const char *Desc=nullptr) const
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
void EmitSectionOffset (const MCSymbol *Label, const MCSymbol *SectionLabel) const
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void EmitDwarfOpPiece (ByteStreamer &Streamer, unsigned SizeInBits, unsigned OffsetInBits=0) const
void EmitDwarfRegOpPiece (ByteStreamer &BS, const MachineLocation &MLoc, unsigned PieceSize=0, unsigned PieceOffset=0) const
Emit a partial DWARF register operation.
virtual void EmitDwarfRegOp (ByteStreamer &BS, const MachineLocation &MLoc, bool Indirect) const
EmitDwarfRegOp - Emit dwarf register operation.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
virtual void emitInlineAsmStart (const MCSubtargetInfo &StartInfo) const
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
const MCAsmInfo * MAI
const MCInstrInfo * MII
MCContext & OutContext
MCStreamer & OutStreamer
const MachineFunction * MF
The current machine function.
MachineModuleInfo * MMI
This is a pointer to the current MachineModuleInfo.
Mangler * Mang
MCSymbol * CurrentFnSym
MCSymbol * CurrentFnSymForSize
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 27 of file X86AsmPrinter.h.
Constructor & Destructor Documentation
llvm::X86AsmPrinter::X86AsmPrinter (TargetMachine & TM, MCStreamer & Streamer) inline explicit
Definition at line 88 of file X86AsmPrinter.h.
References llvm::TargetMachine::getSubtarget().
Member Function Documentation
bool llvm::X86AsmPrinter::doInitialization (Module & M) inline override virtual
Set up the AsmPrinter when we are working on a new module. If your pass overrides this, it must make sure to explicitly call this implementation.
Reimplemented from llvm::AsmPrinter.
Definition at line 119 of file X86AsmPrinter.h.
References llvm::AsmPrinter::doInitialization().
void llvm::X86AsmPrinter::EmitBasicBlockEnd (const MachineBasicBlock & MBB) inline override virtual
Targets can override this to emit stuff at the end of a basic block.
Reimplemented from llvm::AsmPrinter.
Definition at line 105 of file X86AsmPrinter.h.
void X86AsmPrinter::EmitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 605 of file X86AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCStreamer::EmitAssemblerFlag(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitLabel(), emitNonLazySymbolPointer(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitSymbolValue(), llvm::MachineModuleInfo::getContext(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::MCObjectFileInfo::getDataRelSection(), llvm::MCObjectFileInfo::getDrectveSection(), llvm::MachineModuleInfoMachO::GetFnStubList(), llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MachineModuleInfoELF::GetGVStubList(), llvm::MachineModuleInfoMachO::GetHiddenGVStubList(), llvm::MCContext::getMachOSection(), llvm::SectionKind::getMetadata(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::MCContext::GetOrCreateSymbol(), llvm::DataLayout::getPointerSize(), llvm::TargetMachine::getSubtargetImpl(), llvm::AsmPrinter::getSymbol(), llvm::GlobalValue::hasDLLExportStorageClass(), llvm::X86Subtarget::is64Bit(), llvm::GlobalValue::isDeclaration(), llvm::X86Subtarget::isTargetCOFF(), llvm::X86Subtarget::isTargetELF(), llvm::X86Subtarget::isTargetKnownWindowsMSVC(), llvm::X86Subtarget::isTargetMachO(), llvm::MCAF_SubsectionsViaSymbols, llvm::MCSA_Global, llvm::MCSA_IndirectSymbol, llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::MachO::S_ATTR_PURE_INSTRUCTIONS, llvm::MachO::S_ATTR_SELF_MODIFYING_CODE, llvm::MachO::S_NON_LAZY_SYMBOL_POINTERS, llvm::MachO::S_SYMBOL_STUBS, llvm::StackMaps::serializeToStackMapSection(), llvm::MCStreamer::SwitchSection(), llvm::ARMBuildAttrs::Symbol, llvm::AsmPrinter::TM, and llvm::MachineModuleInfo::usesVAFloatArgument().
void X86AsmPrinter::EmitInstruction (const MachineInstr *) override virtual
Targets should implement this to emit instructions.
Reimplemented from llvm::AsmPrinter.
Definition at line 989 of file X86MCInstLower.cpp.
References llvm::MCStreamer::AddComment(), assert(), llvm::CallingConv::C, llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCBinaryExpr::CreateSub(), llvm::MCContext::CreateTempSymbol(), llvm::TargetOpcode::DBG_VALUE, llvm::DecodePSHUFBMask(), llvm::DecodeVPERMILPMask(), llvm::ISD::EH_RETURN, llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::emitRawComment(), llvm::MCStreamer::EmitWinCFIAllocStack(), llvm::MCStreamer::EmitWinCFIEndProlog(), llvm::MCStreamer::EmitWinCFIPushFrame(), llvm::MCStreamer::EmitWinCFIPushReg(), llvm::MCStreamer::EmitWinCFISaveReg(), llvm::MCStreamer::EmitWinCFISaveXMM(), llvm::MCStreamer::EmitWinCFISetFrame(), llvm::SmallVectorBase::empty(), getConstantFromPool(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::User::getOperand(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getPICBaseSymbol(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::X86ATTInstPrinter::getRegisterName(), getRetOpcode(), llvm::X86RegisterInfo::getSEHRegNum(), getShuffleComment(), llvm::TargetMachine::getSubtargetImpl(), llvm::AsmPrinter::getSubtargetInfo(), llvm::MachineOperand::getTargetFlags(), llvm::X86Subtarget::is64Bit(), llvm::MachineInstr::isCall(), llvm::MCStreamer::isVerboseAsm(), llvm_unreachable, LowerSTATEPOINT(), llvm::X86II::MO_GOT_ABSOLUTE_ADDRESS, llvm::AsmPrinter::OutContext, llvm::TargetOpcode::PATCHPOINT, PrevCrossBBInst(), llvm::TargetOpcode::STACKMAP, llvm::TargetOpcode::STATEPOINT, llvm::raw_string_ostream::str(), and llvm::AsmPrinter::TM.
void X86AsmPrinter::EmitStartOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 507 of file X86AsmPrinter.cpp.
References llvm::MCStreamer::BeginCOFFSymbolDef(), llvm::MCConstantExpr::Create(), llvm::MCStreamer::EmitAssignment(), llvm::MCStreamer::EmitCOFFSymbolStorageClass(), llvm::MCStreamer::EmitCOFFSymbolType(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EndCOFFSymbolDef(), llvm::MachineModuleInfo::getContext(), llvm::AsmPrinter::getObjFileLowering(), llvm::MCContext::GetOrCreateSymbol(), llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_NULL, llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isTargetCOFF(), llvm::X86Subtarget::isTargetMachO(), llvm::MCSA_Global, llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutStreamer, llvm::MCSymbol::setAbsolute(), and llvm::MCStreamer::SwitchSection().
MCSymbol * X86AsmPrinter::GetCPISymbol (unsigned CPID) const override virtual
Return the symbol for the specified constant pool entry.
Reimplemented from llvm::AsmPrinter.
Definition at line 556 of file X86AsmPrinter.cpp.
References llvm::CallingConv::C, llvm::MachineConstantPoolEntry::ConstVal, llvm::MCStreamer::EmitSymbolAttribute(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), llvm::AsmPrinter::GetCPISymbol(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineConstantPoolEntry::getSectionKind(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::X86Subtarget::isTargetKnownWindowsMSVC(), llvm::MCSA_Global, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutStreamer, llvm::AsmPrinter::TM, and llvm::MachineConstantPoolEntry::Val.
Referenced by printSymbolOperand().
const char* llvm::X86AsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 93 of file X86AsmPrinter.h.
const X86Subtarget& llvm::X86AsmPrinter::getSubtarget () const inline
Definition at line 97 of file X86AsmPrinter.h.
Referenced by printAsmMRegister(), and SimplifyShortMoveForm().
bool X86AsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 474 of file X86AsmPrinter.cpp.
References printIntelMemReference(), and printMemReference().
bool X86AsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) override virtual
PrintAsmOperand - Print out an operand for an inline asm expression.
Reimplemented from llvm::AsmPrinter.
Definition at line 383 of file X86AsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImm(), llvm::X86Subtarget::isPICStyleRIPRel(), llvm::MachineOperand::isReg(), llvm_unreachable, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_Register, printAsmMRegister(), llvm::AsmPrinter::PrintAsmOperand(), printOperand(), printPCRelImm(), and printSymbolOperand().
bool X86AsmPrinter::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - Emit the function body.
Reimplemented from llvm::AsmPrinter.
Definition at line 49 of file X86AsmPrinter.cpp.
References llvm::MCStreamer::BeginCOFFSymbolDef(), llvm::AsmPrinter::CurrentFnSym, llvm::MCStreamer::EmitCOFFSymbolStorageClass(), llvm::MCStreamer::EmitCOFFSymbolType(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AsmPrinter::EmitFunctionHeader(), llvm::MCStreamer::EndCOFFSymbolDef(), llvm::MachineFunction::getFunction(), llvm::GlobalValue::hasInternalLinkage(), llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::X86Subtarget::isTargetCOFF(), llvm::AsmPrinter::OutStreamer, llvm::COFF::SCT_COMPLEX_TYPE_SHIFT, and llvm::AsmPrinter::SetupMachineFunction().
The documentation for this class was generated from the following files:
X86AsmPrinter.h
X86AsmPrinter.cpp
X86MCInstLower.cpp