LLVM: llvm::sys::path::reverse_iterator Class Reference
LLVM API Documentation
llvm::sys::path::reverse_iterator Class Reference
Reverse path iterator.
#include <Path.h>
Public Member Functions
reference operator* () const
pointer operator-> () const
reverse_iterator & operator++ ()
reverse_iterator & operator++ (int)
bool operator== (const reverse_iterator &RHS) const
bool operator!= (const reverse_iterator &RHS) const
Friends
reverse_iterator rbegin (StringRef path)
Get reverse begin iterator over path.
reverse_iterator rend (StringRef path)
Get reverse end iterator over path.
Detailed Description
Reverse path iterator.
This is an input iterator that iterates over the individual components in path in reverse order. The traversal order is exactly reversed from that of const_iterator
Definition at line 77 of file Path.h.
Member Function Documentation
bool llvm::sys::path::reverse_iterator::operator!= (const reverse_iterator & RHS) const inline
Definition at line 92 of file Path.h.
reference llvm::sys::path::reverse_iterator::operator* () const inline
Definition at line 87 of file Path.h.
reverse_iterator & llvm::sys::path::reverse_iterator::operator++ ()
Definition at line 331 of file Path.cpp.
References llvm::sys::path::is_separator(), llvm::StringRef::size(), llvm::StringRef::slice(), and llvm::StringRef::substr().
reverse_iterator& llvm::sys::path::reverse_iterator::operator++ (int)
pointer llvm::sys::path::reverse_iterator::operator-> () const inline
Definition at line 88 of file Path.h.
bool llvm::sys::path::reverse_iterator::operator== (const reverse_iterator & RHS) const
Definition at line 358 of file Path.cpp.
References llvm::StringRef::begin().
Friends And Related Function Documentation
reverse_iterator rbegin (StringRef path) friend
Get reverse begin iterator over path.
Parameters
path Input path.
Returns
Iterator initialized with the first reverse component of path.
Definition at line 316 of file Path.cpp.
reverse_iterator rend (StringRef path) friend
Get reverse end iterator over path.
Parameters
path Input path.
Returns
Iterator initialized to the reverse end of path.
Definition at line 323 of file Path.cpp.
The documentation for this class was generated from the following files:
Path.h
Path.cpp