LLVM: llvm::MipsSEFrameLowering Class Reference
LLVM API Documentation
llvm::MipsSEFrameLowering Class Reference
#include <MipsSEFrameLowering.h>
Public Member Functions
MipsSEFrameLowering (const MipsSubtarget &STI)
void emitPrologue (MachineFunction &MF) const override
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
bool hasReservedCallFrame (const MachineFunction &MF) const override
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS) const override
unsigned ehDataReg (unsigned I) const
Public Member Functions inherited from llvm::MipsFrameLowering
MipsFrameLowering (const MipsSubtarget &sti, unsigned Alignment)
bool hasFP (const MachineFunction &MF) const override
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool isFPCloseToIncomingSP () const
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
virtual bool targetHandlesStackFrameRounding () const
virtual void adjustForSegmentedStacks (MachineFunction &MF) const
virtual void adjustForHiPEPrologue (MachineFunction &MF) const
virtual void adjustForFrameAllocatePrologue (MachineFunction &MF) const
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual int getFrameIndexOffset (const MachineFunction &MF, int FI) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual int getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::MipsFrameLowering
static const MipsFrameLowering * create (const MipsSubtarget &ST)
Protected Member Functions inherited from llvm::MipsFrameLowering
uint64_t estimateStackSize (const MachineFunction &MF) const
Protected Attributes inherited from llvm::MipsFrameLowering
const MipsSubtarget & STI
Detailed Description
Definition at line 21 of file MipsSEFrameLowering.h.
Constructor & Destructor Documentation
MipsSEFrameLowering::MipsSEFrameLowering (const MipsSubtarget & STI) explicit
Definition at line 398 of file MipsSEFrameLowering.cpp.
Member Function Documentation
unsigned MipsSEFrameLowering::ehDataReg (unsigned I) const
Definition at line 401 of file MipsSEFrameLowering.cpp.
References I, llvm::MipsSubtarget::isABI_N64(), and llvm::MipsFrameLowering::STI.
Referenced by emitEpilogue(), and emitPrologue().
void MipsSEFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 646 of file MipsSEFrameLowering.cpp.
References llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MachineBasicBlock::erase(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getSubtarget(), hasReservedCallFrame(), llvm::MipsSubtarget::isABI_N64(), and llvm::MipsFrameLowering::STI.
void MipsSEFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 546 of file MipsSEFrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MipsFunctionInfo::callsEhReturn(), ehDataReg(), llvm::DebugLoc::get(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MipsFunctionInfo::getEhDataRegFI(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MipsFrameLowering::hasFP(), llvm::MipsSubtarget::isABI_N64(), and llvm::MipsFrameLowering::STI.
void MipsSEFrameLowering::emitPrologue (MachineFunction & MF) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 412 of file MipsSEFrameLowering.cpp.
References llvm::MachineModuleInfo::addFrameInst(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::MachineFrameInfo::adjustsStack(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MipsFunctionInfo::callsEhReturn(), llvm::TargetOpcode::CFI_INSTRUCTION, contains(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), ehDataReg(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameSetup, llvm::MachineFunction::front(), llvm::DebugLoc::get(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MipsFunctionInfo::getEhDataRegFI(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MCContext::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MipsFrameLowering::hasFP(), I, llvm::MipsSubtarget::isABI_N64(), llvm::MipsSubtarget::isLittle(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MipsFrameLowering::STI, and std::swap().
bool MipsSEFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function. This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 633 of file MipsSEFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::isInt< 16 >().
Referenced by eliminateCallFramePseudoInstr().
void MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 665 of file MipsSEFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::MipsFunctionInfo::callsEhReturn(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::MachineFrameInfo::CreateStackObject(), llvm::MipsFrameLowering::estimateStackSize(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterClass::getSize(), llvm::MipsFrameLowering::hasFP(), llvm::MipsSubtarget::hasMips64(), llvm::MipsSubtarget::isABI_N64(), llvm::isInt< 16 >(), llvm::MachineRegisterInfo::setPhysRegUsed(), and llvm::MipsFrameLowering::STI.
bool MipsSEFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 602 of file MipsSEFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::begin(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::isReturnAddressTaken(), and llvm::TargetInstrInfo::storeRegToStackSlot().
The documentation for this class was generated from the following files:
MipsSEFrameLowering.h
MipsSEFrameLowering.cpp