LLVM: llvm::ImutAVLTreeGenericIterator< ImutInfo > Class Template Reference
LLVM API Documentation
llvm::ImutAVLTreeGenericIterator< ImutInfo > Class Template Reference
#include <ImmutableSet.h>
Public Types
enum VisitFlag { VisitedNone =0x0, VisitedLeft =0x1, VisitedRight =0x3, Flags =0x3 }
typedef ImutAVLTree< ImutInfo > TreeTy
typedef
ImutAVLTreeGenericIterator
< ImutInfo > _Self
Public Member Functions
ImutAVLTreeGenericIterator ()
ImutAVLTreeGenericIterator (const TreeTy *Root)
TreeTy * operator* () const
uintptr_t getVisitState () const
bool atEnd () const
bool atBeginning () const
void skipToParent ()
bool operator== (const _Self &x) const
bool operator!= (const _Self &x) const
_Self & operator++ ()
_Self & operator-- ()
Detailed Description
template<typename ImutInfo>
class llvm::ImutAVLTreeGenericIterator< ImutInfo >
Definition at line 35 of file ImmutableSet.h.
Member Typedef Documentation
template<typename ImutInfo > typedef ImutAVLTreeGenericIterator<ImutInfo> llvm::ImutAVLTreeGenericIterator< ImutInfo >::_Self
Definition at line 657 of file ImmutableSet.h.
template<typename ImutInfo > typedef ImutAVLTree<ImutInfo> llvm::ImutAVLTreeGenericIterator< ImutInfo >::TreeTy
Definition at line 656 of file ImmutableSet.h.
Member Enumeration Documentation
template<typename ImutInfo > enum llvm::ImutAVLTreeGenericIterator::VisitFlag
Enumerator
VisitedNone
VisitedLeft
VisitedRight
Flags
Definition at line 653 of file ImmutableSet.h.
Constructor & Destructor Documentation
template<typename ImutInfo > llvm::ImutAVLTreeGenericIterator< ImutInfo >::ImutAVLTreeGenericIterator () inline
Definition at line 659 of file ImmutableSet.h.
template<typename ImutInfo > llvm::ImutAVLTreeGenericIterator< ImutInfo >::ImutAVLTreeGenericIterator (const TreeTy * Root) inline
Definition at line 660 of file ImmutableSet.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Member Function Documentation
template<typename ImutInfo > bool llvm::ImutAVLTreeGenericIterator< ImutInfo >::atBeginning () const inline
Definition at line 677 of file ImmutableSet.h.
References llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedNone.
template<typename ImutInfo > bool llvm::ImutAVLTreeGenericIterator< ImutInfo >::atEnd () const inline
Definition at line 675 of file ImmutableSet.h.
References llvm::SmallVectorBase::empty().
template<typename ImutInfo > uintptr_t llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState () const inline
Definition at line 669 of file ImmutableSet.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), and llvm::ImutAVLTreeGenericIterator< ImutInfo >::Flags.
Referenced by llvm::ImutAVLTreeGenericIterator< ImutInfo >::atBeginning(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), and llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent().
template<typename ImutInfo > bool llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator!= (const _Self & x) const inline
Definition at line 702 of file ImmutableSet.h.
References llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator==().
template<typename ImutInfo > TreeTy* llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator* () const inline
Definition at line 664 of file ImmutableSet.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), and llvm::ImutAVLTreeGenericIterator< ImutInfo >::Flags.
template<typename ImutInfo > _Self& llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++ () inline
Definition at line 704 of file ImmutableSet.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::Flags, llvm::ImutAVLTree< ImutInfo >::getLeft(), llvm::ImutAVLTree< ImutInfo >::getRight(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedLeft, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedNone, and llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedRight.
template<typename ImutInfo > _Self& llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator-- () inline
Definition at line 730 of file ImmutableSet.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::Flags, llvm::ImutAVLTree< ImutInfo >::getLeft(), llvm::ImutAVLTree< ImutInfo >::getRight(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedLeft, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedNone, and llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedRight.
template<typename ImutInfo > bool llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator== (const _Self & x) const inline
Definition at line 698 of file ImmutableSet.h.
Referenced by llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator!=().
template<typename ImutInfo > void llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent () inline
Definition at line 681 of file ImmutableSet.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase::empty(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedLeft, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedNone, and llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedRight.
Referenced by llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++().
The documentation for this class was generated from the following file:
ImmutableSet.h