LLVM: llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle > Class Template Reference
LLVM API Documentation
llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle > Class Template Reference
#include <MachineRegisterInfo.h>
Public Types
typedef std::iterator
< std::forward_iterator_tag,
MachineInstr, ptrdiff_t >
::reference reference
typedef std::iterator
< std::forward_iterator_tag,
MachineInstr, ptrdiff_t >
::pointer pointer
Public Member Functions
defusechain_iterator (const defusechain_iterator &I)
defusechain_iterator ()
bool operator== (const defusechain_iterator &x) const
bool operator!= (const defusechain_iterator &x) const
bool atEnd () const
atEnd - return true if this iterator is equal to reg_end() on the value.
defusechain_iterator & operator++ ()
defusechain_iterator operator++ (int)
unsigned getOperandNo () const
MachineOperand & operator* () const
MachineOperand * operator-> () const
Friends
class MachineRegisterInfo
Detailed Description
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle>
class llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >
reg_begin/reg_end - Provide iteration support to walk over all definitions and uses of a register within the MachineFunction that corresponds to this MachineRegisterInfo object.
defusechain_iterator - This class provides iterator support for machine operands in the function that use or define a specific register. If ReturnUses is true it returns uses of registers, if ReturnDefs is true it returns defs. If neither are true then you are silly and it always returns end(). If SkipDebug is true it skips uses marked Debug when incrementing.
Definition at line 215 of file MachineRegisterInfo.h.
Member Typedef Documentation
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> typedef std::iterator<std::forward_iterator_tag, MachineInstr, ptrdiff_t>::pointer llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::pointer
Definition at line 830 of file MachineRegisterInfo.h.
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> typedef std::iterator<std::forward_iterator_tag, MachineInstr, ptrdiff_t>::reference llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::reference
Definition at line 828 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::defusechain_iterator (const defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle > & I) inline
Definition at line 832 of file MachineRegisterInfo.h.
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::defusechain_iterator () inline
Definition at line 833 of file MachineRegisterInfo.h.
Member Function Documentation
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> bool llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::atEnd () const inline
atEnd - return true if this iterator is equal to reg_end() on the value.
Definition at line 843 of file MachineRegisterInfo.h.
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> unsigned llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::getOperandNo () const inline
getOperandNo - Return the operand # of this MachineOperand in its MachineInstr.
Definition at line 870 of file MachineRegisterInfo.h.
References assert(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getParent().
Referenced by llvm::FastISel::tryToFoldLoad().
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> bool llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator!= (const defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle > & x) const inline
Definition at line 838 of file MachineRegisterInfo.h.
References llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator==().
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> MachineOperand& llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator* () const inline
Definition at line 876 of file MachineRegisterInfo.h.
References assert().
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> defusechain_iterator& llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator++ () inline
Definition at line 846 of file MachineRegisterInfo.h.
References advance(), assert(), llvm::getBundleStart(), llvm::MachineOperand::getParent(), and P.
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> defusechain_iterator llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator++ (int) inline
Definition at line 864 of file MachineRegisterInfo.h.
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> MachineOperand* llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator-> () const inline
Definition at line 881 of file MachineRegisterInfo.h.
References assert().
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> bool llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator== (const defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle > & x) const inline
Definition at line 835 of file MachineRegisterInfo.h.
Referenced by llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator!=().
Friends And Related Function Documentation
template<bool Uses, bool Defs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> friend class MachineRegisterInfo friend
Definition at line 805 of file MachineRegisterInfo.h.
The documentation for this class was generated from the following file:
MachineRegisterInfo.h