LLVM: llvm::AMDGPUMCInstLower Class Reference
LLVM API Documentation
llvm::AMDGPUMCInstLower Class Reference
#include <AMDGPUMCInstLower.h>
Public Member Functions
AMDGPUMCInstLower (MCContext &ctx, const AMDGPUSubtarget &ST)
void lower (const MachineInstr *MI, MCInst &OutMI) const
Lower a MachineInstr to an MCInst.
Detailed Description
Definition at line 21 of file AMDGPUMCInstLower.h.
Constructor & Destructor Documentation
AMDGPUMCInstLower::AMDGPUMCInstLower (MCContext & ctx, const AMDGPUSubtarget & ST)
Definition at line 39 of file AMDGPUMCInstLower.cpp.
Member Function Documentation
void AMDGPUMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Lower a MachineInstr to an MCInst.
Definition at line 43 of file AMDGPUMCInstLower.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::CallingConv::C, llvm::MCSymbolRefExpr::Create(), llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::LLVMContext::emitError(), END_OF_TEXT_LABEL_NAME, llvm::MachineInstr::explicit_operands(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::AMDGPUSubtarget::getInstrInfo(), llvm::Value::getName(), llvm::MachineInstr::getOpcode(), llvm::MCContext::GetOrCreateSymbol(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm_unreachable, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_TargetIndex, llvm::AMDGPUInstrInfo::pseudoToMCOpcode(), llvm::MCInst::setOpcode(), and llvm::AMDGPU::TI_CONSTDATA_START.
Referenced by llvm::AMDGPUAsmPrinter::EmitInstruction().
The documentation for this class was generated from the following files:
AMDGPUMCInstLower.h
AMDGPUMCInstLower.cpp