LLVM: llvm::LocalAsMetadata Class Reference
LLVM API Documentation
llvm::LocalAsMetadata Class Reference
#include <Metadata.h>
Static Public Member Functions
static LocalAsMetadata * get (Value *Local)
static LocalAsMetadata * getIfExists (Value *Local)
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::ValueAsMetadata
static ValueAsMetadata * get (Value *V)
static ConstantAsMetadata * getConstant (Value *C)
static LocalAsMetadata * getLocal (Value *Local)
static ValueAsMetadata * getIfExists (Value *V)
static ConstantAsMetadata * getConstantIfExists (Value *C)
static LocalAsMetadata * getLocalIfExists (Value *Local)
static void handleDeletion (Value *V)
static void handleRAUW (Value *From, Value *To)
static bool classof (const Metadata *MD)
Friends
class ValueAsMetadata
Additional Inherited Members
Public Types inherited from llvm::Metadata
enum MetadataKind {
MDTupleKind, MDLocationKind, MDNodeFwdDeclKind, ConstantAsMetadataKind,
LocalAsMetadataKind, MDStringKind
}
Public Member Functions inherited from llvm::ValueAsMetadata
Value * getValue () const
Type * getType () const
LLVMContext & getContext () const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void print (raw_ostream &OS) const
void printAsOperand (raw_ostream &OS, bool PrintType=true, const Module *M=nullptr) const
Protected Member Functions inherited from llvm::ValueAsMetadata
ValueAsMetadata (unsigned ID, Value *V)
~ValueAsMetadata ()
void replaceAllUsesWith (Metadata *MD)
Handle collisions after Value::replaceAllUsesWith().
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID)
~Metadata ()
bool isStoredDistinctInContext () const
Store this in a big non-uniqued untyped bucket.
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Protected Attributes inherited from llvm::Metadata
bool IsDistinctInContext: 1
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned short SubclassData16
unsigned SubclassData32
Detailed Description
Definition at line 267 of file Metadata.h.
Member Function Documentation
static bool llvm::LocalAsMetadata::classof (const Metadata * MD) inline static
Definition at line 283 of file Metadata.h.
References llvm::Metadata::getMetadataID(), and llvm::Metadata::LocalAsMetadataKind.
static LocalAsMetadata* llvm::LocalAsMetadata::get (Value * Local) inline static
Definition at line 276 of file Metadata.h.
References llvm::ValueAsMetadata::getLocal().
Referenced by LLVMMDNodeInContext().
static LocalAsMetadata* llvm::LocalAsMetadata::getIfExists (Value * Local) inline static
Definition at line 279 of file Metadata.h.
References llvm::ValueAsMetadata::getLocalIfExists().
Referenced by llvm::FindAllocaDbgDeclare().
Friends And Related Function Documentation
friend class ValueAsMetadata friend
Definition at line 268 of file Metadata.h.
The documentation for this class was generated from the following file:
Metadata.h