LLVM: llvm::AMDGPUAsmPrinter Class Reference
LLVM API Documentation
llvm::AMDGPUAsmPrinter Class Reference
#include <AMDGPUAsmPrinter.h>
Public Member Functions
AMDGPUAsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
const char * getPassName () const override
void EmitInstruction (const MachineInstr *MI) override
Implemented in AMDGPUMCInstLower.cpp.
void EmitEndOfAsmFile (Module &M) override
Public Member Functions inherited from llvm::AsmPrinter
virtual ~AsmPrinter ()
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
bool isVerbose () const
unsigned getFunctionNumber () const
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
StringRef getTargetTriple () const
Return the target triple string.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool doInitialization (Module &M) override
bool doFinalization (Module &M) override
void SetupMachineFunction (MachineFunction &MF)
void EmitFunctionHeader ()
This method emits the header for the current function.
void EmitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
CFIMoveType needsCFIMoves ()
bool needsSEHMoves ()
virtual void EmitConstantPool ()
void EmitJumpTableInfo ()
virtual void EmitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
void EmitAlignment (unsigned NumBits, const GlobalObject *GO=nullptr) const
void EmitBasicBlockStart (const MachineBasicBlock &MBB) const
const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void EmitGlobalConstant (const Constant *CV)
Print a general LLVM constant to the .s file.
virtual void EmitStartOfAsmFile (Module &)
virtual void EmitFunctionBodyStart ()
virtual void EmitFunctionBodyEnd ()
virtual void EmitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void EmitFunctionEntryLabel ()
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void EmitXXStructor (const Constant *CV)
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
virtual void emitImplicitDef (const MachineInstr *MI) const
MCSymbol * GetTempSymbol (Twine Name, unsigned ID) const
MCSymbol * GetTempSymbol (Twine Name) const
Return an assembler temporary label with the specified stem.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void EmitInt8 (int Value) const
void EmitInt16 (int Value) const
void EmitInt32 (int Value) const
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
void EmitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void EmitCFAByte (unsigned Val) const
Emit a .byte 42 directive for a DW_CFA_xxx value.
void EmitEncodingByte (unsigned Val, const char *Desc=nullptr) const
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
void EmitSectionOffset (const MCSymbol *Label, const MCSymbol *SectionLabel) const
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void EmitDwarfOpPiece (ByteStreamer &Streamer, unsigned SizeInBits, unsigned OffsetInBits=0) const
void EmitDwarfRegOpPiece (ByteStreamer &BS, const MachineLocation &MLoc, unsigned PieceSize=0, unsigned PieceOffset=0) const
Emit a partial DWARF register operation.
virtual void EmitDwarfRegOp (ByteStreamer &BS, const MachineLocation &MLoc, bool Indirect) const
EmitDwarfRegOp - Emit dwarf register operation.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
virtual bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS)
virtual bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS)
virtual void emitInlineAsmStart (const MCSubtargetInfo &StartInfo) const
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Protected Attributes
bool DisasmEnabled
std::vector< std::string > DisasmLines
std::vector< std::string > HexLines
size_t DisasmLineMaxLen
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
const MCAsmInfo * MAI
const MCInstrInfo * MII
MCContext & OutContext
MCStreamer & OutStreamer
const MachineFunction * MF
The current machine function.
MachineModuleInfo * MMI
This is a pointer to the current MachineModuleInfo.
Mangler * Mang
MCSymbol * CurrentFnSym
MCSymbol * CurrentFnSymForSize
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 23 of file AMDGPUAsmPrinter.h.
Constructor & Destructor Documentation
AMDGPUAsmPrinter::AMDGPUAsmPrinter (TargetMachine & TM, MCStreamer & Streamer) explicit
Definition at line 86 of file AMDGPUAsmPrinter.cpp.
References DisasmEnabled, and llvm::TargetMachine::getSubtarget().
Member Function Documentation
void AMDGPUAsmPrinter::EmitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 91 of file AMDGPUAsmPrinter.cpp.
References llvm::MCStreamer::EmitLabel(), END_OF_TEXT_LABEL_NAME, llvm::AsmPrinter::getObjFileLowering(), llvm::MCContext::GetOrCreateSymbol(), llvm::MCObjectFileInfo::getTextSection(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, and llvm::MCStreamer::SwitchSection().
void AMDGPUAsmPrinter::EmitInstruction (const MachineInstr * MI) override virtual
Implemented in AMDGPUMCInstLower.cpp.
Reimplemented from llvm::AsmPrinter.
Definition at line 94 of file AMDGPUMCInstLower.cpp.
References DisasmEnabled, DisasmLineMaxLen, DisasmLines, llvm::MachineInstr::dump(), llvm::AsmPrinter::EmitToStreamer(), llvm::MCCodeEmitter::EncodeInstruction(), llvm::MachineBasicBlock::end(), llvm::errs(), llvm::raw_ostream::flush(), llvm::format(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getEmitter(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineInstr::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetMachine::getSubtarget(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineFunction::getTarget(), HexLines, I, llvm::MachineInstr::isBundle(), llvm::AMDGPUMCInstLower::lower(), llvm::AsmPrinter::MF, llvm::AArch64CC::MI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::AMDGPUInstPrinter::printInst(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::AsmPrinter::TM, and llvm::TargetInstrInfo::verifyInstruction().
const char* llvm::AMDGPUAsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 92 of file AMDGPUAsmPrinter.h.
bool AMDGPUAsmPrinter::runOnMachineFunction (MachineFunction & MF) override virtual
Emit the specified function out to the OutStreamer.
Reimplemented from llvm::AsmPrinter.
Definition at line 101 of file AMDGPUAsmPrinter.cpp.
References DisasmEnabled, DisasmLineMaxLen, DisasmLines, llvm::AMDGPUSubtarget::dumpCode(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitCodeAlignment(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AsmPrinter::EmitFunctionHeader(), llvm::MCStreamer::emitRawComment(), llvm::MachineFunction::getAlignment(), llvm::TargetLoweringObjectFile::getContext(), llvm::MCContext::getELFSection(), llvm::AMDGPUSubtarget::getGeneration(), llvm::MachineFunction::getInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::SectionKind::getReadOnly(), llvm::TargetMachine::getSubtarget(), HexLines, llvm::AMDGPUSubtarget::isAmdHsaOS(), llvm::AsmPrinter::isVerbose(), llvm::AsmPrinter::OutStreamer, llvm::MachineFunction::setAlignment(), llvm::AsmPrinter::SetupMachineFunction(), llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PROGBITS, llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS, llvm::R600MachineFunctionInfo::StackSize, llvm::MCStreamer::SwitchSection(), and llvm::AsmPrinter::TM.
Member Data Documentation
bool llvm::AMDGPUAsmPrinter::DisasmEnabled protected
Definition at line 102 of file AMDGPUAsmPrinter.h.
Referenced by AMDGPUAsmPrinter(), EmitInstruction(), and runOnMachineFunction().
size_t llvm::AMDGPUAsmPrinter::DisasmLineMaxLen protected
Definition at line 104 of file AMDGPUAsmPrinter.h.
Referenced by EmitInstruction(), and runOnMachineFunction().
std::vector<std::string> llvm::AMDGPUAsmPrinter::DisasmLines protected
Definition at line 103 of file AMDGPUAsmPrinter.h.
Referenced by EmitInstruction(), and runOnMachineFunction().
std::vector<std::string> llvm::AMDGPUAsmPrinter::HexLines protected
Definition at line 103 of file AMDGPUAsmPrinter.h.
Referenced by EmitInstruction(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
AMDGPUAsmPrinter.h
AMDGPUAsmPrinter.cpp
AMDGPUMCInstLower.cpp