LLVM: llvm::ARMMCExpr Class Reference
LLVM API Documentation
llvm::ARMMCExpr Class Reference
#include <ARMMCExpr.h>
Public Types
enum VariantKind { VK_ARM_None, VK_ARM_HI16, VK_ARM_LO16 }
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
void PrintImpl (raw_ostream &OS) const override
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
const MCSection * FindAssociatedSection () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Accessors
VariantKind getKind () const
getOpcode - Get the kind of this expression.
const MCExpr * getSubExpr () const
getSubExpr - Get the child of this expression.
Public Member Functions inherited from llvm::MCExpr
ExprKind getKind () const
void print (raw_ostream &OS) const
void dump () const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
int64_t evaluateKnownAbsolute (const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
bool EvaluateAsValue (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
const MCSection * FindAssociatedSection () const
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const ARMMCExpr * Create (VariantKind Kind, const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * CreateUpper16 (const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * CreateLower16 (const MCExpr *Expr, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet, bool ForceVarExpansion) const
Detailed Description
Definition at line 17 of file ARMMCExpr.h.
Member Enumeration Documentation
enum llvm::ARMMCExpr::VariantKind
Enumerator
VK_ARM_None
VK_ARM_HI16
VK_ARM_LO16
Definition at line 19 of file ARMMCExpr.h.
Member Function Documentation
static bool llvm::ARMMCExpr::classof (const MCExpr * E) inline static
Definition at line 73 of file ARMMCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Target.
const ARMMCExpr * ARMMCExpr::Create (VariantKind Kind, const MCExpr * Expr, MCContext & Ctx) static
Definition at line 18 of file ARMMCExpr.cpp.
Referenced by CreateLower16(), and CreateUpper16().
static const ARMMCExpr* llvm::ARMMCExpr::CreateLower16 (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 43 of file ARMMCExpr.h.
References Create(), and VK_ARM_LO16.
Referenced by llvm::ARMAsmPrinter::EmitInstruction().
static const ARMMCExpr* llvm::ARMMCExpr::CreateUpper16 (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 39 of file ARMMCExpr.h.
References Create(), and VK_ARM_HI16.
Referenced by llvm::ARMAsmPrinter::EmitInstruction().
bool llvm::ARMMCExpr::EvaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 60 of file ARMMCExpr.h.
const MCSection* llvm::ARMMCExpr::FindAssociatedSection () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 66 of file ARMMCExpr.h.
References llvm::MCExpr::FindAssociatedSection(), and getSubExpr().
void llvm::ARMMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 71 of file ARMMCExpr.h.
VariantKind llvm::ARMMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 52 of file ARMMCExpr.h.
const MCExpr* llvm::ARMMCExpr::getSubExpr () const inline
getSubExpr - Get the child of this expression.
Definition at line 55 of file ARMMCExpr.h.
Referenced by FindAssociatedSection(), PrintImpl(), and visitUsedExpr().
void ARMMCExpr::PrintImpl (raw_ostream & OS) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 23 of file ARMMCExpr.cpp.
References llvm::MCExpr::getKind(), getSubExpr(), llvm_unreachable, llvm::MCExpr::print(), llvm::MCExpr::SymbolRef, VK_ARM_HI16, and VK_ARM_LO16.
void ARMMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 38 of file ARMMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
ARMMCExpr.h
ARMMCExpr.cpp