LLVM: llvm::MCDwarfDwoLineTable Class Reference
LLVM API Documentation
llvm::MCDwarfDwoLineTable Class Reference
#include <MCDwarf.h>
Public Member Functions
void setCompilationDir (StringRef CompilationDir)
unsigned getFile (StringRef Directory, StringRef FileName)
void Emit (MCStreamer &MCOS) const
Detailed Description
Definition at line 196 of file MCDwarf.h.
Member Function Documentation
void MCDwarfDwoLineTable::Emit (MCStreamer & MCOS) const
Definition at line 227 of file MCDwarf.cpp.
References llvm::MCDwarfLineTableHeader::Emit(), llvm::MCStreamer::EmitLabel(), and llvm::None.
unsigned llvm::MCDwarfDwoLineTable::getFile (StringRef Directory, StringRef FileName) inline
Definition at line 202 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::getFile().
void llvm::MCDwarfDwoLineTable::setCompilationDir (StringRef CompilationDir) inline
Definition at line 199 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::CompilationDir.
The documentation for this class was generated from the following files:
MCDwarf.h
MCDwarf.cpp