LLVM: llvm::TargetLibraryInfo Class Reference
LLVM API Documentation
llvm::TargetLibraryInfo Class Reference
#include <TargetLibraryInfo.h>
Public Member Functions
TargetLibraryInfo ()
TargetLibraryInfo (const Triple &T)
TargetLibraryInfo (const TargetLibraryInfo &TLI)
bool getLibFunc (StringRef funcName, LibFunc::Func &F) const
bool has (LibFunc::Func F) const
bool hasOptimizedCodeGen (LibFunc::Func F) const
StringRef getName (LibFunc::Func F) const
void setUnavailable (LibFunc::Func F)
void setAvailable (LibFunc::Func F)
void setAvailableWithName (LibFunc::Func F, StringRef Name)
void disableAllFunctions ()
Public Member Functions inherited from llvm::ImmutablePass
virtual void initializePass ()
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePass (char &pid)
virtual ~ImmutablePass ()
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
TargetLibraryInfo - This immutable pass captures information about what library functions are available for the current target, and allows a frontend to disable optimizations through -fno-builtin etc.
Definition at line 698 of file TargetLibraryInfo.h.
Constructor & Destructor Documentation
TargetLibraryInfo::TargetLibraryInfo ()
Definition at line 689 of file TargetLibraryInfo.cpp.
References initialize(), and llvm::Intrinsic::memset.
TargetLibraryInfo::TargetLibraryInfo (const Triple & T)
Definition at line 696 of file TargetLibraryInfo.cpp.
References initialize(), and llvm::Intrinsic::memset.
TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfo & TLI) explicit
Definition at line 703 of file TargetLibraryInfo.cpp.
References llvm::Intrinsic::memcpy.
Member Function Documentation
void TargetLibraryInfo::disableAllFunctions ()
disableAllFunctions - This disables all builtins, which is used for options like -fno-builtin.
Definition at line 752 of file TargetLibraryInfo.cpp.
References llvm::Intrinsic::memset.
bool TargetLibraryInfo::getLibFunc (StringRef funcName, LibFunc::Func & F) const
getLibFunc - Search for a particular function name. If it is one of the known library functions, return true and set F to the corresponding value.
Definition at line 728 of file TargetLibraryInfo.cpp.
References llvm::StringRef::empty(), llvm::StringRef::find(), llvm::StringRef::front(), I, llvm::StringRef::npos, llvm::LibFunc::NumLibFuncs, and llvm::StringRef::substr().
Referenced by getAllocationData(), llvm::getIntrinsicIDForCall(), llvm::isFreeCall(), llvm::FortifiedLibCallSimplifier::optimizeCall(), and llvm::FastISel::selectInstruction().
StringRef llvm::TargetLibraryInfo::getName (LibFunc::Func F) const inline
Definition at line 765 of file TargetLibraryInfo.h.
References assert(), F(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by accumulateAndSortLibcalls(), llvm::EmitFPutS(), llvm::EmitFWrite(), FindCXAAtExit(), and hasMemoryWrite().
bool llvm::TargetLibraryInfo::has (LibFunc::Func F) const inline
has - This function is used by optimizations that want to match on or form a given library function.
Definition at line 729 of file TargetLibraryInfo.h.
Referenced by accumulateAndSortLibcalls(), ConstantFoldScalarCall(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), FindCXAAtExit(), getAllocationData(), hasMemoryWrite(), hasUnaryFloatFn(), llvm::isFreeCall(), isMemsetPattern16(), and llvm::FortifiedLibCallSimplifier::optimizeCall().
bool llvm::TargetLibraryInfo::hasOptimizedCodeGen (LibFunc::Func F) const inline
hasOptimizedCodeGen - Return true if the function is both available as a builtin and a candidate for optimized code generation.
Definition at line 735 of file TargetLibraryInfo.h.
References llvm::LibFunc::ceil, llvm::LibFunc::ceilf, llvm::LibFunc::ceill, llvm::LibFunc::copysign, llvm::LibFunc::copysignf, llvm::LibFunc::copysignl, llvm::LibFunc::cos, llvm::LibFunc::cosf, llvm::LibFunc::cosl, llvm::LibFunc::exp2, llvm::LibFunc::exp2f, llvm::LibFunc::exp2l, llvm::LibFunc::fabs, llvm::LibFunc::fabsf, llvm::LibFunc::fabsl, llvm::LibFunc::floor, llvm::LibFunc::floorf, llvm::LibFunc::floorl, llvm::LibFunc::fmax, llvm::LibFunc::fmaxf, llvm::LibFunc::fmaxl, llvm::LibFunc::fmin, llvm::LibFunc::fminf, llvm::LibFunc::fminl, llvm::LibFunc::log2, llvm::LibFunc::log2f, llvm::LibFunc::log2l, llvm::LibFunc::memchr, llvm::LibFunc::memcmp, llvm::LibFunc::nearbyint, llvm::LibFunc::nearbyintf, llvm::LibFunc::nearbyintl, llvm::LibFunc::rint, llvm::LibFunc::rintf, llvm::LibFunc::rintl, llvm::LibFunc::round, llvm::LibFunc::roundf, llvm::LibFunc::roundl, llvm::LibFunc::sin, llvm::LibFunc::sinf, llvm::LibFunc::sinl, llvm::LibFunc::sqrt, llvm::LibFunc::sqrt_finite, llvm::LibFunc::sqrtf, llvm::LibFunc::sqrtf_finite, llvm::LibFunc::sqrtl, llvm::LibFunc::sqrtl_finite, llvm::LibFunc::stpcpy, llvm::LibFunc::strcmp, llvm::LibFunc::strcpy, llvm::LibFunc::strlen, llvm::LibFunc::strnlen, llvm::LibFunc::trunc, llvm::LibFunc::truncf, and llvm::LibFunc::truncl.
Referenced by llvm::FastISel::selectInstruction().
void llvm::TargetLibraryInfo::setAvailable (LibFunc::Func F) inline
Definition at line 781 of file TargetLibraryInfo.h.
void llvm::TargetLibraryInfo::setAvailableWithName (LibFunc::Func F, StringRef Name) inline
Definition at line 785 of file TargetLibraryInfo.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and Name.
Referenced by initialize().
void llvm::TargetLibraryInfo::setUnavailable (LibFunc::Func F) inline
setUnavailable - this can be used by whatever sets up TargetLibraryInfo to ban use of specific library functions.
Definition at line 777 of file TargetLibraryInfo.h.
Referenced by initialize().
Member Data Documentation
char llvm::TargetLibraryInfo::ID static
Definition at line 718 of file TargetLibraryInfo.h.
The documentation for this class was generated from the following files:
TargetLibraryInfo.h
TargetLibraryInfo.cpp