LLVM: llvm::DIEInteger Class Reference
LLVM API Documentation
llvm::DIEInteger Class Reference
#include <DIE.h>
Public Member Functions
DIEInteger (uint64_t I)
void EmitValue (AsmPrinter *AP, dwarf::Form Form) const override
uint64_t getValue () const
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
void print (raw_ostream &O) const override
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Static Public Member Functions
static dwarf::Form BestForm (bool IsSigned, uint64_t Int)
static bool classof (const DIEValue *I)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger, isString, isExpr, isLabel,
isDelta, isEntry, isTypeSignature, isBlock,
isLoc, isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Detailed Description
DIEInteger - An integer value DIE.
Definition at line 248 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEInteger::DIEInteger (uint64_t I) inline explicit
Definition at line 252 of file DIE.h.
Member Function Documentation
static dwarf::Form llvm::DIEInteger::BestForm (bool IsSigned, uint64_t Int) inline static
BestForm - Choose the best form for integer.
Definition at line 256 of file DIE.h.
References llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_data2, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_data8, and llvm::tgtok::Int.
Referenced by llvm::DwarfUnit::addSInt(), and llvm::DwarfUnit::addUInt().
static bool llvm::DIEInteger::classof (const DIEValue * I) inline static
Definition at line 287 of file DIE.h.
References llvm::DIEValue::getType(), and llvm::DIEValue::isInteger.
void DIEInteger::EmitValue (AsmPrinter * Asm, dwarf::Form Form) const override virtual
EmitValue - Emit integer of appropriate size.
Implements llvm::DIEValue.
Definition at line 207 of file DIE.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::dwarf::DW_FORM_addr, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_data2, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_data8, llvm::dwarf::DW_FORM_flag, llvm::dwarf::DW_FORM_flag_present, llvm::dwarf::DW_FORM_GNU_addr_index, llvm::dwarf::DW_FORM_GNU_str_index, llvm::dwarf::DW_FORM_ref1, llvm::dwarf::DW_FORM_ref2, llvm::dwarf::DW_FORM_ref4, llvm::dwarf::DW_FORM_ref8, llvm::dwarf::DW_FORM_ref_sig8, llvm::dwarf::DW_FORM_sdata, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_udata, llvm::MCStreamer::EmitIntValue(), llvm::AsmPrinter::EmitSLEB128(), llvm::AsmPrinter::EmitULEB128(), llvm::AsmPrinter::getDataLayout(), llvm::DataLayout::getPointerSize(), llvm_unreachable, and llvm::AsmPrinter::OutStreamer.
uint64_t llvm::DIEInteger::getValue () const inline
Definition at line 280 of file DIE.h.
void DIEInteger::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 263 of file DIE.cpp.
References llvm::raw_ostream::write_hex().
unsigned DIEInteger::SizeOf (AsmPrinter * AP, dwarf::Form Form) const override virtual
SizeOf - Determine size of integer value in bytes.
Implements llvm::DIEValue.
Definition at line 239 of file DIE.cpp.
References llvm::dwarf::DW_FORM_addr, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_data2, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_data8, llvm::dwarf::DW_FORM_flag, llvm::dwarf::DW_FORM_flag_present, llvm::dwarf::DW_FORM_GNU_addr_index, llvm::dwarf::DW_FORM_GNU_str_index, llvm::dwarf::DW_FORM_ref1, llvm::dwarf::DW_FORM_ref2, llvm::dwarf::DW_FORM_ref4, llvm::dwarf::DW_FORM_ref8, llvm::dwarf::DW_FORM_ref_sig8, llvm::dwarf::DW_FORM_sdata, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_udata, llvm::AsmPrinter::getDataLayout(), llvm::DataLayout::getPointerSize(), llvm::getSLEB128Size(), llvm::getULEB128Size(), and llvm_unreachable.
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp