LLVM: llvm::MipsAsmPrinter Class Reference
LLVM API Documentation
llvm::MipsAsmPrinter Class Reference
#include <MipsAsmPrinter.h>
Public Member Functions
MipsAsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
const char * getPassName () const override
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
void EmitConstantPool () override
void EmitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
void printSavedRegsBitmask ()
void emitFrameDirective ()
Frame Directive.
const char * getCurrentABIString () const
Emit Set directives.
void EmitFunctionEntryLabel () override
void EmitFunctionBodyStart () override
void EmitFunctionBodyEnd () override
bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const override
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) override
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNum, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) override
void printOperand (const MachineInstr *MI, int opNum, raw_ostream &O)
void printUnsignedImm (const MachineInstr *MI, int opNum, raw_ostream &O)
void printUnsignedImm8 (const MachineInstr *MI, int opNum, raw_ostream &O)
void printMemOperand (const MachineInstr *MI, int opNum, raw_ostream &O)
void printMemOperandEA (const MachineInstr *MI, int opNum, raw_ostream &O)
void printFCCOperand (const MachineInstr *MI, int opNum, raw_ostream &O, const char *Modifier=nullptr)
void printRegisterList (const MachineInstr *MI, int opNum, raw_ostream &O)
void EmitStartOfAsmFile (Module &M) override
void EmitEndOfAsmFile (Module &M) override
void PrintDebugValueComment (const MachineInstr *MI, raw_ostream &OS)
Public Member Functions inherited from llvm::AsmPrinter
virtual ~AsmPrinter ()
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
bool isVerbose () const
unsigned getFunctionNumber () const
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
StringRef getTargetTriple () const
Return the target triple string.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool doInitialization (Module &M) override
bool doFinalization (Module &M) override
void SetupMachineFunction (MachineFunction &MF)
void EmitFunctionHeader ()
This method emits the header for the current function.
void EmitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
CFIMoveType needsCFIMoves ()
bool needsSEHMoves ()
void EmitJumpTableInfo ()
virtual void EmitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
void EmitAlignment (unsigned NumBits, const GlobalObject *GO=nullptr) const
void EmitBasicBlockStart (const MachineBasicBlock &MBB) const
const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void EmitGlobalConstant (const Constant *CV)
Print a general LLVM constant to the .s file.
virtual void EmitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void EmitXXStructor (const Constant *CV)
virtual void emitImplicitDef (const MachineInstr *MI) const
MCSymbol * GetTempSymbol (Twine Name, unsigned ID) const
MCSymbol * GetTempSymbol (Twine Name) const
Return an assembler temporary label with the specified stem.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void EmitInt8 (int Value) const
void EmitInt16 (int Value) const
void EmitInt32 (int Value) const
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
void EmitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void EmitCFAByte (unsigned Val) const
Emit a .byte 42 directive for a DW_CFA_xxx value.
void EmitEncodingByte (unsigned Val, const char *Desc=nullptr) const
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
void EmitSectionOffset (const MCSymbol *Label, const MCSymbol *SectionLabel) const
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void EmitDwarfOpPiece (ByteStreamer &Streamer, unsigned SizeInBits, unsigned OffsetInBits=0) const
void EmitDwarfRegOpPiece (ByteStreamer &BS, const MachineLocation &MLoc, unsigned PieceSize=0, unsigned PieceOffset=0) const
Emit a partial DWARF register operation.
virtual void EmitDwarfRegOp (ByteStreamer &BS, const MachineLocation &MLoc, bool Indirect) const
EmitDwarfRegOp - Emit dwarf register operation.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Attributes
const MipsSubtarget * Subtarget
const MipsFunctionInfo * MipsFI
MipsMCInstLower MCInstLowering
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
const MCAsmInfo * MAI
const MCInstrInfo * MII
MCContext & OutContext
MCStreamer & OutStreamer
const MachineFunction * MF
The current machine function.
MachineModuleInfo * MMI
This is a pointer to the current MachineModuleInfo.
Mangler * Mang
MCSymbol * CurrentFnSym
MCSymbol * CurrentFnSymForSize
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 33 of file MipsAsmPrinter.h.
Constructor & Destructor Documentation
llvm::MipsAsmPrinter::MipsAsmPrinter (TargetMachine & TM, MCStreamer & Streamer) inline explicit
Definition at line 102 of file MipsAsmPrinter.h.
Member Function Documentation
void llvm::MipsAsmPrinter::EmitConstantPool () inline override virtual
Print to the current output stream assembly representations of the constants in the constant pool MCP. This is used to print out constants which have been "spilled to memory" by the code generator.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP. This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented from llvm::AsmPrinter.
Definition at line 112 of file MipsAsmPrinter.h.
References llvm::AsmPrinter::EmitConstantPool().
void MipsAsmPrinter::EmitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 1022 of file MipsAsmPrinter.cpp.
References llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getTextSection(), llvm::AsmPrinter::OutContext, and llvm::MCStreamer::SwitchSection().
void MipsAsmPrinter::emitFrameDirective ()
Frame Directive.
Definition at line 310 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitFrame(), llvm::MachineFunction::getFrameInfo(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MCRegisterInfo::getRARegister(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::TargetMachine::getSubtargetImpl(), llvm::AsmPrinter::MF, and llvm::AsmPrinter::TM.
Referenced by EmitFunctionBodyStart().
void MipsAsmPrinter::EmitFunctionBodyEnd () override virtual
EmitFunctionBodyEnd - Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 379 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::MCStreamer::EmitDataRegion(), llvm::MipsTargetStreamer::emitDirectiveEnd(), llvm::MipsTargetStreamer::emitDirectiveSetAt(), llvm::MipsTargetStreamer::emitDirectiveSetMacro(), llvm::MipsTargetStreamer::emitDirectiveSetReorder(), llvm::MCSymbol::getName(), llvm::MipsSubtarget::inMips16Mode(), llvm::MCDR_DataRegionEnd, and Subtarget.
void MipsAsmPrinter::EmitFunctionBodyStart () override virtual
EmitFunctionBodyStart - Targets can override this to emit stuff before the first basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 355 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoAt(), llvm::MipsTargetStreamer::emitDirectiveSetNoMacro(), llvm::MipsTargetStreamer::emitDirectiveSetNoReorder(), emitFrameDirective(), llvm::AttributeSet::FunctionIndex, llvm::Intrinsic::getAttributes(), llvm::MachineFunction::getContext(), llvm::MachineFunction::getFunction(), llvm::AttributeSet::hasAttribute(), llvm::MipsMCInstLower::Initialize(), llvm::MipsSubtarget::inMips16Mode(), MCInstLowering, llvm::AsmPrinter::MF, llvm::Attribute::Naked, printSavedRegsBitmask(), and Subtarget.
void MipsAsmPrinter::EmitFunctionEntryLabel () override virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function. This can be overridden by targets as required to do custom stuff.
Reimplemented from llvm::AsmPrinter.
Definition at line 331 of file MipsAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::EmitAlignment(), llvm::MipsTargetStreamer::emitDirectiveEnt(), llvm::MipsTargetStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetStreamer::emitDirectiveSetMips16(), llvm::MipsTargetStreamer::emitDirectiveSetNoMicroMips(), llvm::MipsTargetStreamer::emitDirectiveSetNoMips16(), llvm::MCStreamer::EmitLabel(), llvm::MachineFunction::getAlignment(), llvm::MipsSubtarget::inMicroMipsMode(), llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isTargetNaCl(), llvm::AsmPrinter::MF, llvm::MIPS_NACL_BUNDLE_ALIGN, and Subtarget.
void MipsAsmPrinter::EmitInstruction (const MachineInstr *) override virtual
Targets should implement this to emit instructions.
Reimplemented from llvm::AsmPrinter.
Definition at line 132 of file MipsAsmPrinter.cpp.
References llvm::MachineConstantPoolEntry::ConstVal, llvm::MCStreamer::EmitDataRegion(), llvm::AsmPrinter::EmitGlobalConstant(), llvm::MCStreamer::EmitLabel(), llvm::AsmPrinter::EmitMachineConstantPoolValue(), llvm::AsmPrinter::EmitToStreamer(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MachineConstantPool::getConstants(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), I, llvm::MipsSubtarget::inMips16Mode(), llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isDebugValue(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm_unreachable, llvm::MipsMCInstLower::Lower(), llvm::MachineConstantPoolEntry::MachineCPVal, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, MCInstLowering, llvm::AArch64CC::MI, PrintDebugValueComment(), Subtarget, and llvm::MachineConstantPoolEntry::Val.
void MipsAsmPrinter::EmitStartOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 691 of file MipsAsmPrinter.cpp.
References llvm::MipsTargetStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetStreamer::emitDirectiveModuleFP(), llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsTargetStreamer::emitDirectiveNaN2008(), llvm::MipsTargetStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetStreamer::emitDirectiveOptionPic0(), getCurrentABIString(), llvm::SectionKind::getDataRel(), llvm::MCContext::getELFSection(), llvm::TargetMachine::getRelocationModel(), llvm::MipsSubtarget::isABI_EABI(), llvm::MipsSubtarget::isABI_FPXX(), llvm::MipsSubtarget::isABI_N64(), llvm::MipsSubtarget::isABI_O32(), llvm::MipsSubtarget::isABICalls(), llvm::MipsSubtarget::isFP64bit(), llvm::MipsSubtarget::isGP32bit(), llvm::MipsSubtarget::isNaN2008(), llvm::AsmPrinter::OutContext, llvm::NVPTX::PTXCvtMode::RM, llvm::ELF::SHT_PROGBITS, llvm::Reloc::Static, Subtarget, llvm::MCStreamer::SwitchSection(), llvm::AsmPrinter::TM, llvm::MipsTargetStreamer::updateABIInfo(), and llvm::MipsSubtarget::useOddSPReg().
const char * MipsAsmPrinter::getCurrentABIString () const
Emit Set directives.
Definition at line 321 of file MipsAsmPrinter.cpp.
References llvm::MipsABIInfo::EABI, llvm::MipsSubtarget::getABI(), llvm::MipsABIInfo::GetEnumValue(), llvm_unreachable, llvm::MipsABIInfo::N32, llvm::MipsABIInfo::N64, llvm::MipsABIInfo::O32, and Subtarget.
Referenced by EmitStartOfAsmFile().
const char* llvm::MipsAsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 106 of file MipsAsmPrinter.h.
bool MipsAsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const override virtual
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented from llvm::AsmPrinter.
Definition at line 402 of file MipsAsmPrinter.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), I, llvm::MachineBasicBlock::isLandingPad(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), and llvm::MachineBasicBlock::pred_end().
bool MipsAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 541 of file MipsAsmPrinter.cpp.
References assert(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MipsInstPrinter::getRegisterName(), and llvm::MachineOperand::isReg().
bool MipsAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate.
Reimplemented from llvm::AsmPrinter.
Definition at line 442 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MipsInstPrinter::getRegisterName(), llvm::MachineOperand::getType(), llvm::MipsSubtarget::isGP64bit(), llvm::MachineOperand::isImm(), llvm::MipsSubtarget::isLittle(), llvm::MachineOperand::isReg(), llvm::StringRef::lower(), llvm::MachineOperand::MO_Immediate, llvm::AsmPrinter::PrintAsmOperand(), printOperand(), Subtarget, and llvm::utohexstr().
void MipsAsmPrinter::PrintDebugValueComment (const MachineInstr * MI, raw_ostream & OS)
Definition at line 1038 of file MipsAsmPrinter.cpp.
Referenced by EmitInstruction().
void MipsAsmPrinter::printFCCOperand (const MachineInstr * MI, int opNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 677 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), and llvm::Mips::MipsFCCToString().
void MipsAsmPrinter::printMemOperand (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 644 of file MipsAsmPrinter.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), and printOperand().
void MipsAsmPrinter::printMemOperandEA (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 667 of file MipsAsmPrinter.cpp.
References printOperand().
void MipsAsmPrinter::printOperand (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 561 of file MipsAsmPrinter.cpp.
References DL, llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MCSymbol::getName(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOperand(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::MachineOperand::getReg(), llvm::MipsInstPrinter::getRegisterName(), llvm::TargetMachine::getSubtargetImpl(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::StringRef::lower(), llvm::MipsII::MO_ABS_HI, llvm::MipsII::MO_ABS_LO, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::MipsII::MO_GOT, llvm::MipsII::MO_GOT_CALL, llvm::MipsII::MO_GOT_DISP, llvm::MipsII::MO_GOT_OFST, llvm::MipsII::MO_GOT_PAGE, llvm::MipsII::MO_GOTTPREL, llvm::MipsII::MO_GPOFF_HI, llvm::MipsII::MO_GPOFF_LO, llvm::MipsII::MO_GPREL, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MipsII::MO_TLSGD, llvm::MipsII::MO_TPREL_HI, llvm::MipsII::MO_TPREL_LO, and llvm::AsmPrinter::TM.
Referenced by PrintAsmOperand(), printMemOperand(), printMemOperandEA(), printRegisterList(), printUnsignedImm(), and printUnsignedImm8().
void MipsAsmPrinter::printRegisterList (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 684 of file MipsAsmPrinter.cpp.
References llvm::MachineInstr::getNumOperands(), and printOperand().
void MipsAsmPrinter::printSavedRegsBitmask ()
Definition at line 247 of file MipsAsmPrinter.cpp.
References contains(), llvm::MipsTargetStreamer::emitFMask(), llvm::MipsTargetStreamer::emitMask(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetMachine::getSubtargetImpl(), llvm::AsmPrinter::MF, and llvm::AsmPrinter::TM.
Referenced by EmitFunctionBodyStart().
void MipsAsmPrinter::printUnsignedImm (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 625 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), and printOperand().
void MipsAsmPrinter::printUnsignedImm8 (const MachineInstr * MI, int opNum, raw_ostream & O)
Definition at line 634 of file MipsAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), and printOperand().
bool MipsAsmPrinter::runOnMachineFunction (MachineFunction & MF) override virtual
Emit the specified function out to the OutStreamer.
Reimplemented from llvm::AsmPrinter.
Definition at line 60 of file MipsAsmPrinter.cpp.
References llvm::MachineFunction::getConstantPool(), llvm::MachineFunction::getInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::TargetMachine::getSubtarget(), llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isTargetNaCl(), MipsFI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::runOnMachineFunction(), llvm::MipsFunctionInfo::StubsNeeded, Subtarget, llvm::ARMBuildAttrs::Symbol, and llvm::AsmPrinter::TM.
Member Data Documentation
MipsMCInstLower llvm::MipsAsmPrinter::MCInstLowering
Definition at line 95 of file MipsAsmPrinter.h.
Referenced by EmitFunctionBodyStart(), and EmitInstruction().
const MipsFunctionInfo* llvm::MipsAsmPrinter::MipsFI
Definition at line 94 of file MipsAsmPrinter.h.
Referenced by runOnMachineFunction().
const MipsSubtarget* llvm::MipsAsmPrinter::Subtarget
Definition at line 93 of file MipsAsmPrinter.h.
Referenced by EmitFunctionBodyEnd(), EmitFunctionBodyStart(), EmitFunctionEntryLabel(), EmitInstruction(), EmitStartOfAsmFile(), getCurrentABIString(), PrintAsmOperand(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
MipsAsmPrinter.h
MipsAsmPrinter.cpp