LLVM: llvm::legacy::FunctionPassManagerImpl Class Reference
LLVM API Documentation
llvm::legacy::FunctionPassManagerImpl Class Reference
FunctionPassManagerImpl manages FPPassManagers.
Public Member Functions
FunctionPassManagerImpl ()
void add (Pass *P)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void releaseMemoryOnTheFly ()
bool run (Function &F)
bool doInitialization (Module &M) override
bool doFinalization (Module &M) override
PMDataManager * getAsPMDataManager () override
Pass * getAsPass () override
PassManagerType getTopLevelPassManagerType () override
void getAnalysisUsage (AnalysisUsage &Info) const override
Pass Manager itself does not invalidate any analysis info.
FPPassManager * getContainedManager (unsigned N)
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void assignPassManager (PMStack &, PassManagerType)
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Member Functions inherited from llvm::PMDataManager
PMDataManager ()
virtual ~PMDataManager ()
void recordAvailableAnalysis (Pass *P)
Augment AvailableAnalysis by adding analysis made available by pass P.
void verifyPreservedAnalysis (Pass *P)
verifyPreservedAnalysis – Verify analysis presreved by pass P.
void removeNotPreservedAnalysis (Pass *P)
Remove Analysis that is not preserved by the pass.
void removeDeadPasses (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove dead passes used by P.
void freePass (Pass *P, StringRef Msg, enum PassDebuggingString)
Remove P.
void add (Pass *P, bool ProcessAnalysis=true)
virtual void addLowerLevelRequiredPass (Pass *P, Pass *RequiredPass)
virtual Pass * getOnTheFlyPass (Pass *P, AnalysisID PI, Function &F)
void initializeAnalysisInfo ()
Initialize available analysis information.
bool preserveHigherLevelAnalysis (Pass *P)
void collectRequiredAnalysis (SmallVectorImpl< Pass * > &RequiredPasses, SmallVectorImpl< AnalysisID > &ReqPassNotAvailable, Pass *P)
void initializeAnalysisImpl (Pass *P)
Pass * findAnalysisPass (AnalysisID AID, bool Direction)
PMTopLevelManager * getTopLevelManager ()
void setTopLevelManager (PMTopLevelManager *T)
unsigned getDepth () const
void setDepth (unsigned newDepth)
void dumpLastUses (Pass *P, unsigned Offset) const
void dumpPassArguments () const
void dumpPassInfo (Pass *P, enum PassDebuggingString S1, enum PassDebuggingString S2, StringRef Msg)
void dumpRequiredSet (const Pass *P) const
void dumpPreservedSet (const Pass *P) const
unsigned getNumContainedPasses () const
virtual PassManagerType getPassManagerType () const
DenseMap< AnalysisID, Pass * > * getAvailableAnalysis ()
void populateInheritedAnalysis (PMStack &PMS)
Public Member Functions inherited from llvm::PMTopLevelManager
void schedulePass (Pass *P)
void setLastUser (ArrayRef< Pass * > AnalysisPasses, Pass *P)
Set pass P as the last user of the given analysis passes.
void collectLastUses (SmallVectorImpl< Pass * > &LastUses, Pass *P)
Collect passes whose last user is P.
Pass * findAnalysisPass (AnalysisID AID)
const PassInfo * findAnalysisPassInfo (AnalysisID AID) const
Retrieve the PassInfo for an analysis.
AnalysisUsage * findAnalysisUsage (Pass *P)
Find analysis usage information for the pass P.
virtual ~PMTopLevelManager ()
Destructor.
void addImmutablePass (ImmutablePass *P)
Add immutable pass and initialize it.
SmallVectorImpl< ImmutablePass * > & getImmutablePasses ()
void addPassManager (PMDataManager *Manager)
void addIndirectPassManager (PMDataManager *Manager)
void dumpPasses () const
void dumpArguments () const
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::PMTopLevelManager
PMStack activeStack
Protected Member Functions inherited from llvm::PMDataManager
bool isPassDebuggingExecutionsOrMore () const
Protected Member Functions inherited from llvm::PMTopLevelManager
PMTopLevelManager (PMDataManager *PMDM)
Initialize top level manager. Create first pass manager.
unsigned getNumContainedManagers () const
void initializeAllAnalysisInfo ()
Protected Attributes inherited from llvm::PMDataManager
PMTopLevelManager * TPM
SmallVector< Pass *, 16 > PassVector
DenseMap< AnalysisID, Pass * > * InheritedAnalysis [PMT_Last]
Protected Attributes inherited from llvm::PMTopLevelManager
SmallVector< PMDataManager *, 8 > PassManagers
Collection of pass managers.
Detailed Description
FunctionPassManagerImpl manages FPPassManagers.
Definition at line 218 of file LegacyPassManager.cpp.
Constructor & Destructor Documentation
llvm::legacy::FunctionPassManagerImpl::FunctionPassManagerImpl () inline explicit
Definition at line 226 of file LegacyPassManager.cpp.
Member Function Documentation
void llvm::legacy::FunctionPassManagerImpl::add (Pass * P) inline
Add a pass to the queue of passes to run. This passes ownership of the Pass to the PassManager. When the PassManager is destroyed, the pass will be destroyed as well, so there is no need to delete the pass. This may even destroy the pass right away if it is found to be redundant. This implies that all passes MUST be allocated with 'new'.
Definition at line 231 of file LegacyPassManager.cpp.
Referenced by llvm::legacy::FunctionPassManager::add().
Pass* llvm::legacy::FunctionPassManagerImpl::createPrinterPass (raw_ostream & O, const std::string & Banner) const inline override virtual
createPrinterPass - Get a function printer pass.
Implements llvm::Pass.
Definition at line 236 of file LegacyPassManager.cpp.
References llvm::createPrintFunctionPass().
bool FunctionPassManagerImpl::doFinalization (Module & M) override virtual
doFinalization - Run all of the finalizers for the function passes.
Reimplemented from llvm::Pass.
Definition at line 1442 of file LegacyPassManager.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::FPPassManager::doFinalization(), llvm::SmallVectorTemplateCommon< T >::end(), getContainedManager(), llvm::PMTopLevelManager::getImmutablePasses(), llvm::PMTopLevelManager::getNumContainedManagers(), and I.
Referenced by llvm::legacy::FunctionPassManager::doFinalization().
bool FunctionPassManagerImpl::doInitialization (Module & M) override virtual
doInitialization - Run all of the initializers for the function passes.
Reimplemented from llvm::Pass.
Definition at line 1424 of file LegacyPassManager.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::FPPassManager::doInitialization(), llvm::PMTopLevelManager::dumpArguments(), llvm::PMTopLevelManager::dumpPasses(), llvm::SmallVectorTemplateCommon< T >::end(), getContainedManager(), llvm::PMTopLevelManager::getImmutablePasses(), llvm::PMTopLevelManager::getNumContainedManagers(), and I.
Referenced by llvm::legacy::FunctionPassManager::doInitialization().
void llvm::legacy::FunctionPassManagerImpl::getAnalysisUsage (AnalysisUsage & Info) const inline override virtual
Pass Manager itself does not invalidate any analysis info.
Reimplemented from llvm::Pass.
Definition at line 265 of file LegacyPassManager.cpp.
References llvm::AnalysisUsage::setPreservesAll().
Pass* llvm::legacy::FunctionPassManagerImpl::getAsPass () inline override virtual
Implements llvm::PMDataManager.
Definition at line 259 of file LegacyPassManager.cpp.
PMDataManager* llvm::legacy::FunctionPassManagerImpl::getAsPMDataManager () inline override virtual
Implements llvm::PMTopLevelManager.
Definition at line 258 of file LegacyPassManager.cpp.
FPPassManager* llvm::legacy::FunctionPassManagerImpl::getContainedManager (unsigned N) inline
Definition at line 269 of file LegacyPassManager.cpp.
References assert(), and N.
Referenced by doFinalization(), doInitialization(), releaseMemoryOnTheFly(), and run().
PassManagerType llvm::legacy::FunctionPassManagerImpl::getTopLevelPassManagerType () inline override virtual
Implements llvm::PMTopLevelManager.
Definition at line 260 of file LegacyPassManager.cpp.
References llvm::PMT_FunctionPassManager.
void FunctionPassManagerImpl::releaseMemoryOnTheFly ()
Definition at line 1467 of file LegacyPassManager.cpp.
References getContainedManager(), llvm::FPPassManager::getContainedPass(), llvm::PMTopLevelManager::getNumContainedManagers(), llvm::PMDataManager::getNumContainedPasses(), and llvm::Pass::releaseMemory().
bool FunctionPassManagerImpl::run (Function & F)
run - Execute all of the passes scheduled for execution. Keep track of whether any of the passes modifies the module, and if so, return true.
Definition at line 1481 of file LegacyPassManager.cpp.
References llvm::FPPassManager::cleanup(), getContainedManager(), llvm::Function::getContext(), llvm::PMTopLevelManager::getNumContainedManagers(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), llvm::FPPassManager::runOnFunction(), and llvm::LLVMContext::yield().
Referenced by llvm::legacy::FunctionPassManager::run().
Member Data Documentation
char llvm::legacy::FunctionPassManagerImpl::ID = 0 static
Definition at line 225 of file LegacyPassManager.cpp.
The documentation for this class was generated from the following file:
LegacyPassManager.cpp