LLVM: llvm::SmallString< InternalLen > Class Template Reference
LLVM API Documentation
llvm::SmallString< InternalLen > Class Template Reference
#include <SmallString.h>
Public Member Functions
SmallString ()
Default ctor - Initialize to empty.
SmallString (StringRef S)
Initialize from a StringRef.
template<typename ItTy >
SmallString (ItTy S, ItTy E)
Initialize with a range.
String Assignment
void assign (size_t NumElts, char Elt)
Assign from a repeated element.
template<typename in_iter >
void assign (in_iter S, in_iter E)
Assign from an iterator pair.
void assign (StringRef RHS)
Assign from a StringRef.
void assign (const SmallVectorImpl< char > &RHS)
Assign from a SmallVector.
String Concatenation
template<typename in_iter >
void append (in_iter S, in_iter E)
Append from an iterator pair.
void append (size_t NumInputs, char Elt)
void append (StringRef RHS)
Append from a StringRef.
void append (const SmallVectorImpl< char > &RHS)
Append from a SmallVector.
String Comparison
bool equals (StringRef RHS) const
bool equals_lower (StringRef RHS) const
Check for string equality, ignoring case.
int compare (StringRef RHS) const
int compare_lower (StringRef RHS) const
compare_lower - Compare two strings, ignoring case.
int compare_numeric (StringRef RHS) const
String Predicates
bool startswith (StringRef Prefix) const
startswith - Check if this string starts with the given Prefix.
bool endswith (StringRef Suffix) const
endswith - Check if this string ends with the given Suffix.
String Searching
size_t find (char C, size_t From=0) const
size_t find (StringRef Str, size_t From=0) const
size_t rfind (char C, size_t From=StringRef::npos) const
size_t rfind (StringRef Str) const
size_t find_first_of (char C, size_t From=0) const
size_t find_first_of (StringRef Chars, size_t From=0) const
size_t find_first_not_of (char C, size_t From=0) const
size_t find_first_not_of (StringRef Chars, size_t From=0) const
size_t find_last_of (char C, size_t From=StringRef::npos) const
size_t find_last_of (StringRef Chars, size_t From=StringRef::npos) const
Helpful Algorithms
size_t count (char C) const
Return the number of occurrences of C in the string.
size_t count (StringRef Str) const
Substring Operations
StringRef substr (size_t Start, size_t N=StringRef::npos) const
StringRef slice (size_t Start, size_t End) const
StringRef str () const
Explicit conversion to StringRef.
const char * c_str ()
operator StringRef () const
Implicit conversion to StringRef.
const SmallString & operator= (StringRef RHS)
SmallString & operator+= (StringRef RHS)
SmallString & operator+= (char C)
Public Member Functions inherited from llvm::SmallVector< char, InternalLen >
SmallVector ()
SmallVector (size_t Size, const char &Value=char())
SmallVector (ItTy S, ItTy E)
SmallVector (const llvm::iterator_range< RangeTy > R)
SmallVector (const SmallVector &RHS)
SmallVector (SmallVector &&RHS)
const SmallVector & operator= (const SmallVector &RHS)
const SmallVector & operator= (SmallVector &&RHS)
Public Member Functions inherited from llvm::SmallVectorImpl< char >
~SmallVectorImpl ()
void clear ()
void resize (size_type N)
void resize (size_type N, const char &NV)
void reserve (size_type N)
charLLVM_ATTRIBUTE_UNUSED_RESULT pop_back_val ()
void swap (SmallVectorImpl &RHS)
void append (in_iter in_start, in_iter in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, const char &Elt)
Add the specified range to the end of the SmallVector.
void assign (size_type NumElts, const char &Elt)
iterator erase (iterator I)
iterator erase (iterator S, iterator E)
iterator insert (iterator I, char &&Elt)
iterator insert (iterator I, const char &Elt)
iterator insert (iterator I, size_type NumToInsert, const char &Elt)
iterator insert (iterator I, ItTy From, ItTy To)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
void set_size (size_type N)
Public Member Functions inherited from llvm::SmallVectorTemplateBase< T, isPodLike >
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
void emplace_back ()
template<typename T1 >
void emplace_back (T1 &&A1)
template<typename T1 , typename T2 >
void emplace_back (T1 &&A1, T2 &&A2)
template<typename T1 , typename T2 , typename T3 >
void emplace_back (T1 &&A1, T2 &&A2, T3 &&A3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
void emplace_back (T1 &&A1, T2 &&A2, T3 &&A3, T4 &&A4)
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
size_type max_size () const
size_t capacity () const
Return the total number of elements in the currently allocated buffer.
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase
size_t size_in_bytes () const
This returns size()*sizeof(T).
size_t capacity_in_bytes () const
capacity_in_bytes - This returns capacity()*sizeof(T).
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
Additional Inherited Members
Public Types inherited from llvm::SmallVectorImpl< char >
typedef SuperClass::iterator iterator
typedef SuperClass::size_type size_type
Public Types inherited from llvm::SmallVectorTemplateCommon< T >
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
Protected Member Functions inherited from llvm::SmallVectorImpl< char >
SmallVectorImpl (unsigned N)
Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, isPodLike >
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSizeInBytes, size_t TSize)
bool isSmall () const
void resetToSmall ()
Put this vector in a state of being small.
void setEnd (T *P)
iterator capacity_ptr ()
const_iterator capacity_ptr () const
Protected Member Functions inherited from llvm::SmallVectorBase
SmallVectorBase (void *FirstEl, size_t Size)
void grow_pod (void *FirstEl, size_t MinSizeInBytes, size_t TSize)
Static Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, isPodLike >
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static It2 move (It1 I, It1 E, It2 Dest)
template<typename It1 , typename It2 >
static It2 move_backward (It1 I, It1 E, It2 Dest)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Protected Attributes inherited from llvm::SmallVectorBase
void * BeginX
void * EndX
void * CapacityX
Detailed Description
template<unsigned InternalLen>
class llvm::SmallString< InternalLen >
SmallString - A SmallString is just a SmallVector with methods and accessors that make it work better as a string (e.g. operator+ etc).
Definition at line 25 of file SmallString.h.
Constructor & Destructor Documentation
template<unsigned InternalLen> llvm::SmallString< InternalLen >::SmallString () inline
Default ctor - Initialize to empty.
Definition at line 28 of file SmallString.h.
template<unsigned InternalLen> llvm::SmallString< InternalLen >::SmallString (StringRef S) inline
Initialize from a StringRef.
Definition at line 31 of file SmallString.h.
template<unsigned InternalLen> template<typename ItTy > llvm::SmallString< InternalLen >::SmallString (ItTy S, ItTy E) inline
Initialize with a range.
Definition at line 35 of file SmallString.h.
Member Function Documentation
template<unsigned InternalLen> template<typename in_iter > void llvm::SmallString< InternalLen >::append (in_iter S, in_iter E) inline
Append from an iterator pair.
Definition at line 74 of file SmallString.h.
Referenced by llvm::StringTableBuilder::finalize(), mangleCoveragePath(), llvm::SmallString< 256 >::operator+=(), and parseBackslash().
template<unsigned InternalLen> void llvm::SmallString< InternalLen >::append (size_t NumInputs, char Elt) inline
Definition at line 78 of file SmallString.h.
template<unsigned InternalLen> void llvm::SmallString< InternalLen >::append (StringRef RHS) inline
Append from a StringRef.
Definition at line 84 of file SmallString.h.
template<unsigned InternalLen> void llvm::SmallString< InternalLen >::append (const SmallVectorImpl< char > & RHS) inline
Append from a SmallVector.
Definition at line 89 of file SmallString.h.
template<unsigned InternalLen> void llvm::SmallString< InternalLen >::assign (size_t NumElts, char Elt) inline
Assign from a repeated element.
Definition at line 45 of file SmallString.h.
template<unsigned InternalLen> template<typename in_iter > void llvm::SmallString< InternalLen >::assign (in_iter S, in_iter E) inline
Assign from an iterator pair.
Definition at line 51 of file SmallString.h.
template<unsigned InternalLen> void llvm::SmallString< InternalLen >::assign (StringRef RHS) inline
Assign from a StringRef.
Definition at line 57 of file SmallString.h.
template<unsigned InternalLen> void llvm::SmallString< InternalLen >::assign (const SmallVectorImpl< char > & RHS) inline
Assign from a SmallVector.
Definition at line 63 of file SmallString.h.
template<unsigned InternalLen> const char* llvm::SmallString< InternalLen >::c_str () inline
Definition at line 270 of file SmallString.h.
Referenced by llvm::LTOCodeGenerator::compile_to_file(), llvm::LockFileManager::LockFileManager(), parseDouble(), llvm::cl::TokenizeGNUCommandLine(), and llvm::cl::TokenizeWindowsCommandLine().
template<unsigned InternalLen> int llvm::SmallString< InternalLen >::compare (StringRef RHS) const inline
Compare two strings; the result is -1, 0, or 1 if this string is lexicographically less than, equal to, or greater than the RHS.
Definition at line 110 of file SmallString.h.
template<unsigned InternalLen> int llvm::SmallString< InternalLen >::compare_lower (StringRef RHS) const inline
compare_lower - Compare two strings, ignoring case.
Definition at line 115 of file SmallString.h.
template<unsigned InternalLen> int llvm::SmallString< InternalLen >::compare_numeric (StringRef RHS) const inline
compare_numeric - Compare two strings, treating sequences of digits as numbers.
Definition at line 121 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::count (char C) const inline
Return the number of occurrences of C in the string.
Definition at line 223 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::count (StringRef Str) const inline
Return the number of non-overlapped occurrences of Str in the string.
Definition at line 229 of file SmallString.h.
template<unsigned InternalLen> bool llvm::SmallString< InternalLen >::endswith (StringRef Suffix) const inline
endswith - Check if this string ends with the given Suffix.
Definition at line 135 of file SmallString.h.
template<unsigned InternalLen> bool llvm::SmallString< InternalLen >::equals (StringRef RHS) const inline
Check for string equality. This is more efficient than compare() when the relative ordering of inequal strings isn't needed.
Definition at line 99 of file SmallString.h.
template<unsigned InternalLen> bool llvm::SmallString< InternalLen >::equals_lower (StringRef RHS) const inline
Check for string equality, ignoring case.
Definition at line 104 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::find (char C, size_t From = 0) const inline
find - Search for the first character C in the string.
Returns
- The index of the first occurrence of C, or npos if not found.
Definition at line 147 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::find (StringRef Str, size_t From = 0) const inline
Search for the first string Str in the string.
Returns
The index of the first occurrence of Str, or npos if not found.
Definition at line 155 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::find_first_not_of (char C, size_t From = 0) const inline
Find the first character in the string that is not C or npos if not found.
Definition at line 191 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::find_first_not_of (StringRef Chars, size_t From = 0) const inline
Find the first character in the string that is not in the string Chars, or npos if not found.
Complexity: O(size() + Chars.size())
Definition at line 199 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::find_first_of (char C, size_t From = 0) const inline
Find the first character in the string that is C, or npos if not found. Same as find.
Definition at line 177 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::find_first_of (StringRef Chars, size_t From = 0) const inline
Find the first character in the string that is in Chars, or npos if not found.
Complexity: O(size() + Chars.size())
Definition at line 185 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::find_last_of (char C, size_t From = StringRef::npos) const inline
Find the last character in the string that is C, or npos if not found.
Definition at line 205 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::find_last_of (StringRef Chars, size_t From = StringRef::npos) const inline
Find the last character in the string that is in C, or npos if not found.
Complexity: O(size() + Chars.size())
Definition at line 213 of file SmallString.h.
template<unsigned InternalLen> llvm::SmallString< InternalLen >::operator StringRef () const inline
Implicit conversion to StringRef.
Definition at line 277 of file SmallString.h.
template<unsigned InternalLen> SmallString& llvm::SmallString< InternalLen >::operator+= (StringRef RHS) inline
Definition at line 285 of file SmallString.h.
template<unsigned InternalLen> SmallString& llvm::SmallString< InternalLen >::operator+= (char C) inline
Definition at line 289 of file SmallString.h.
template<unsigned InternalLen> const SmallString& llvm::SmallString< InternalLen >::operator= (StringRef RHS) inline
Definition at line 280 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::rfind (char C, size_t From = StringRef::npos) const inline
Search for the last character C in the string.
Returns
The index of the last occurrence of C, or npos if not found.
Definition at line 163 of file SmallString.h.
template<unsigned InternalLen> size_t llvm::SmallString< InternalLen >::rfind (StringRef Str) const inline
Search for the last string Str in the string.
Returns
The index of the last occurrence of Str, or npos if not found.
Definition at line 171 of file SmallString.h.
template<unsigned InternalLen> StringRef llvm::SmallString< InternalLen >::slice (size_t Start, size_t End) const inline
Return a reference to the substring from [Start, End).
Parameters
Start The index of the starting character in the substring; if the index is npos or greater than the length of the string then the empty substring will be returned.
End The index following the last character to include in the substring. If this is npos, or less than Start, or exceeds the number of characters remaining in the string, the string suffix (starting with Start) will be returned.
Definition at line 260 of file SmallString.h.
template<unsigned InternalLen> bool llvm::SmallString< InternalLen >::startswith (StringRef Prefix) const inline
startswith - Check if this string starts with the given Prefix.
Definition at line 130 of file SmallString.h.
template<unsigned InternalLen> StringRef llvm::SmallString< InternalLen >::str () const inline
Explicit conversion to StringRef.
Definition at line 267 of file SmallString.h.
Referenced by llvm::SmallString< 256 >::compare(), llvm::SmallString< 256 >::compare_lower(), llvm::SmallString< 256 >::compare_numeric(), llvm::SmallString< 256 >::count(), CrashHandler(), llvm::createGraphFilename(), llvm::APInt::dump(), emitComments(), llvm::StringToOffsetTable::EmitString(), llvm::SmallString< 256 >::endswith(), llvm::SmallString< 256 >::equals(), llvm::SmallString< 256 >::equals_lower(), llvm::SmallString< 256 >::find(), llvm::SmallString< 256 >::find_first_not_of(), llvm::SmallString< 256 >::find_first_of(), llvm::SmallString< 256 >::find_last_of(), llvm::sys::Process::FindInEnvPath(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::LineEditor::getDefaultHistoryPath(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), llvm::jitprofiling::FilenameCache::getFullPath(), llvm::MachineFunction::getJTISymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), llvm::MCContext::getMachOSection(), llvm::TargetMachine::getSymbol(), GetSymbolFromOperand(), llvm::LockFileManager::LockFileManager(), llvm::MCContext::LookupSymbol(), mangleCoveragePath(), llvm::object::ExportEntry::name(), llvm::SmallString< 256 >::operator StringRef(), llvm::object::ExportEntry::operator==(), llvm::APInt::print(), llvm::SmallString< 256 >::rfind(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::Triple::setArchName(), llvm::FileRemover::setFile(), llvm::SmallString< 256 >::slice(), llvm::SmallString< 256 >::startswith(), llvm::SmallString< 256 >::substr(), llvm::APInt::toString(), llvm::LockFileManager::waitForUnlock(), llvm::WriteConstantInternal(), writeFragment(), llvm::FileRemover::~FileRemover(), and llvm::LockFileManager::~LockFileManager().
template<unsigned InternalLen> StringRef llvm::SmallString< InternalLen >::substr (size_t Start, size_t N = StringRef::npos) const inline
Return a reference to the substring from [Start, Start + N).
Parameters
Start The index of the starting character in the substring; if the index is npos or greater than the length of the string then the empty substring will be returned.
N The number of characters to included in the substring. If N exceeds the number of characters remaining in the string, the string suffix (starting with Start) will be returned.
Definition at line 246 of file SmallString.h.
Referenced by llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
The documentation for this class was generated from the following file:
SmallString.h