LLVM: llvm::AnalysisManager< IRUnitT > Class Template Reference
LLVM API Documentation
llvm::AnalysisManager< IRUnitT > Class Template Reference
A generic analysis pass manager with lazy running and caching of results.
#include <Dominators.h>
Public Member Functions
AnalysisManager (bool DebugLogging=false)
Construct an empty analysis manager.
AnalysisManager (AnalysisManager &&Arg)
AnalysisManager & operator= (AnalysisManager &&RHS)
bool empty () const
Returns true if the analysis manager has an empty results cache.
void clear ()
Clear the analysis result cache.
Public Member Functions inherited from llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >
template<typename PassT >
PassT::Result & getResult (IRUnitT &IR)
Get the result of an analysis pass for this module.
template<typename PassT >
PassT::Result * getCachedResult (IRUnitT &IR) const
Get the cached result of an analysis pass for this module.
template<typename PassT >
void registerPass (PassT Pass)
Register an analysis pass with the manager.
template<typename PassT >
void invalidate (IRUnitT &IR)
Invalidate a specific analysis pass for an IR module.
PreservedAnalyses invalidate (IRUnitT &IR, PreservedAnalyses PA)
Invalidate analyses cached for an IR unit.
Friends
class detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >
Additional Inherited Members
Protected Types inherited from llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >
typedef
detail::AnalysisResultConcept
< IRUnitT > ResultConceptT
typedef
detail::AnalysisPassConcept
< IRUnitT > PassConceptT
Protected Member Functions inherited from llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >
AnalysisManagerBase ()
AnalysisManagerBase (AnalysisManagerBase &&Arg)
AnalysisManagerBase & operator= (AnalysisManagerBase &&RHS)
PassConceptT & lookupPass (void *PassID)
Lookup a registered analysis pass.
const PassConceptT & lookupPass (void *PassID) const
Lookup a registered analysis pass.
Detailed Description
template<typename IRUnitT>
class llvm::AnalysisManager< IRUnitT >
A generic analysis pass manager with lazy running and caching of results.
This analysis manager can be used for any IR unit where the address of the IR unit sufficies as its identity. It manages the cache for a unit of IR via the address of each unit of IR cached.
Definition at line 36 of file Dominators.h.
Constructor & Destructor Documentation
template<typename IRUnitT> llvm::AnalysisManager< IRUnitT >::AnalysisManager (bool DebugLogging = false) inline
Construct an empty analysis manager.
A flag can be passed to indicate that the manager should perform debug logging.
Definition at line 421 of file IR/PassManager.h.
template<typename IRUnitT> llvm::AnalysisManager< IRUnitT >::AnalysisManager (AnalysisManager< IRUnitT > && Arg) inline
Definition at line 425 of file IR/PassManager.h.
Member Function Documentation
template<typename IRUnitT> void llvm::AnalysisManager< IRUnitT >::clear () inline
Clear the analysis result cache.
This routine allows cleaning up when the set of IR units itself has potentially changed, and thus we can't even look up a a result and invalidate it directly. Notably, this does not call invalidate functions as there is nothing to be done for them.
Definition at line 450 of file IR/PassManager.h.
Referenced by llvm::CGSCCAnalysisManagerModuleProxy::Result::invalidate(), llvm::FunctionAnalysisManagerModuleProxy::Result::invalidate(), llvm::CGSCCAnalysisManagerModuleProxy::Result::~Result(), and llvm::FunctionAnalysisManagerModuleProxy::Result::~Result().
template<typename IRUnitT> bool llvm::AnalysisManager< IRUnitT >::empty () const inline
Returns true if the analysis manager has an empty results cache.
Definition at line 437 of file IR/PassManager.h.
References assert().
Referenced by llvm::CGSCCAnalysisManagerModuleProxy::run(), and llvm::FunctionAnalysisManagerModuleProxy::run().
template<typename IRUnitT> AnalysisManager& llvm::AnalysisManager< IRUnitT >::operator= (AnalysisManager< IRUnitT > && RHS) inline
Definition at line 429 of file IR/PassManager.h.
Friends And Related Function Documentation
template<typename IRUnitT> friend class detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT > friend
Definition at line 409 of file IR/PassManager.h.
The documentation for this class was generated from the following files:
Dominators.h
IR/PassManager.h