LLVM: llvm::OutputBuffer Class Reference
LLVM API Documentation
llvm::OutputBuffer Class Reference
#include <OutputBuffer.h>
Public Member Functions
OutputBuffer (std::vector< unsigned char > &Out, bool is64bit, bool le)
void align (unsigned Boundary)
void outbyte (unsigned char X)
void outhalf (unsigned short X)
void outword (unsigned X)
void outxword (uint64_t X)
void outaddr32 (unsigned X)
void outaddr64 (uint64_t X)
void outaddr (uint64_t X)
void outstring (const std::string &S, unsigned Length)
void fixhalf (unsigned short X, unsigned Offset)
void fixword (unsigned X, unsigned Offset)
void fixxword (uint64_t X, unsigned Offset)
void fixaddr (uint64_t X, unsigned Offset)
unsigned char & operator[] (unsigned Index)
const unsigned char & operator[] (unsigned Index) const
Detailed Description
Definition at line 23 of file OutputBuffer.h.
Constructor & Destructor Documentation
llvm::OutputBuffer::OutputBuffer (std::vector< unsigned char > & Out, bool is64bit, bool le) inline
Definition at line 31 of file OutputBuffer.h.
Member Function Documentation
void llvm::OutputBuffer::align (unsigned Boundary) inline
Definition at line 37 of file OutputBuffer.h.
References assert().
void llvm::OutputBuffer::fixaddr (uint64_t X, unsigned Offset) inline
Definition at line 149 of file OutputBuffer.h.
References fixword(), and fixxword().
void llvm::OutputBuffer::fixhalf (unsigned short X, unsigned Offset) inline
Definition at line 126 of file OutputBuffer.h.
References P.
void llvm::OutputBuffer::fixword (unsigned X, unsigned Offset) inline
Definition at line 131 of file OutputBuffer.h.
References P.
Referenced by fixaddr().
void llvm::OutputBuffer::fixxword (uint64_t X, unsigned Offset) inline
Definition at line 138 of file OutputBuffer.h.
References P.
Referenced by fixaddr().
unsigned char& llvm::OutputBuffer::operator[] (unsigned Index) inline
Definition at line 156 of file OutputBuffer.h.
const unsigned char& llvm::OutputBuffer::operator[] (unsigned Index) const inline
Definition at line 159 of file OutputBuffer.h.
void llvm::OutputBuffer::outaddr (uint64_t X) inline
Definition at line 104 of file OutputBuffer.h.
References outword(), and outxword().
void llvm::OutputBuffer::outaddr32 (unsigned X) inline
Definition at line 98 of file OutputBuffer.h.
References outword().
void llvm::OutputBuffer::outaddr64 (uint64_t X) inline
Definition at line 101 of file OutputBuffer.h.
References outxword().
void llvm::OutputBuffer::outbyte (unsigned char X) inline
Definition at line 52 of file OutputBuffer.h.
Referenced by outstring().
void llvm::OutputBuffer::outhalf (unsigned short X) inline
Definition at line 55 of file OutputBuffer.h.
void llvm::OutputBuffer::outstring (const std::string & S, unsigned Length) inline
Definition at line 110 of file OutputBuffer.h.
References outbyte().
void llvm::OutputBuffer::outword (unsigned X) inline
Definition at line 64 of file OutputBuffer.h.
Referenced by outaddr(), and outaddr32().
void llvm::OutputBuffer::outxword (uint64_t X) inline
Definition at line 77 of file OutputBuffer.h.
Referenced by outaddr(), and outaddr64().
The documentation for this class was generated from the following file:
OutputBuffer.h