LLVM: llvm::object::ImportDirectoryEntryRef Class Reference
LLVM API Documentation
llvm::object::ImportDirectoryEntryRef Class Reference
#include <COFF.h>
Public Member Functions
ImportDirectoryEntryRef ()
ImportDirectoryEntryRef (const import_directory_table_entry *Table, uint32_t I, const COFFObjectFile *Owner)
bool operator== (const ImportDirectoryEntryRef &Other) const
void moveNext ()
imported_symbol_iterator imported_symbol_begin () const
imported_symbol_iterator imported_symbol_end () const
iterator_range
< imported_symbol_iterator > imported_symbols () const
std::error_code getName (StringRef &Result) const
std::error_code getImportLookupTableRVA (uint32_t &Result) const
std::error_code getImportAddressTableRVA (uint32_t &Result) const
std::error_code getImportTableEntry (const import_directory_table_entry *&Result) const
std::error_code getImportLookupEntry (const import_lookup_table_entry32 *&Result) const
Detailed Description
Definition at line 726 of file Object/COFF.h.
Constructor & Destructor Documentation
llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef () inline
Definition at line 728 of file Object/COFF.h.
llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef (const import_directory_table_entry * Table, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 729 of file Object/COFF.h.
Member Function Documentation
std::error_code ImportDirectoryEntryRef::getImportAddressTableRVA (uint32_t & Result) const
Definition at line 1254 of file COFFObjectFile.cpp.
References llvm::object::import_directory_table_entry::ImportAddressTableRVA, and llvm::object::success.
std::error_code ImportDirectoryEntryRef::getImportLookupEntry (const import_lookup_table_entry32 *& Result) const
Definition at line 1259 of file COFFObjectFile.cpp.
References llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::import_directory_table_entry::ImportLookupTableRVA, and llvm::object::success.
std::error_code ImportDirectoryEntryRef::getImportLookupTableRVA (uint32_t & Result) const
Definition at line 1248 of file COFFObjectFile.cpp.
References llvm::object::import_directory_table_entry::ImportLookupTableRVA, and llvm::object::success.
std::error_code ImportDirectoryEntryRef::getImportTableEntry (const import_directory_table_entry *& Result) const
Definition at line 1179 of file COFFObjectFile.cpp.
References llvm::object::success.
std::error_code ImportDirectoryEntryRef::getName (StringRef & Result) const
Definition at line 1238 of file COFFObjectFile.cpp.
References llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::import_directory_table_entry::NameRVA, and llvm::object::success.
imported_symbol_iterator ImportDirectoryEntryRef::imported_symbol_begin () const
Definition at line 1222 of file COFFObjectFile.cpp.
References importedSymbolBegin().
Referenced by imported_symbols().
imported_symbol_iterator ImportDirectoryEntryRef::imported_symbol_end () const
Definition at line 1228 of file COFFObjectFile.cpp.
References importedSymbolEnd().
Referenced by imported_symbols().
iterator_range< imported_symbol_iterator > ImportDirectoryEntryRef::imported_symbols () const
Definition at line 1234 of file COFFObjectFile.cpp.
References imported_symbol_begin(), imported_symbol_end(), and llvm::make_range().
void ImportDirectoryEntryRef::moveNext ()
Definition at line 1175 of file COFFObjectFile.cpp.
bool ImportDirectoryEntryRef::operator== (const ImportDirectoryEntryRef & Other) const
Definition at line 1171 of file COFFObjectFile.cpp.
The documentation for this class was generated from the following files:
Object/COFF.h
COFFObjectFile.cpp