LLVM: llvm::PPCSubtarget Class Reference
LLVM API Documentation
llvm::PPCSubtarget Class Reference
#include <PPCSubtarget.h>
Public Member Functions
PPCSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS, const PPCTargetMachine &TM)
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
unsigned getStackAlignment () const
unsigned getDarwinDirective () const
const InstrItineraryData * getInstrItineraryData () const override
const PPCFrameLowering * getFrameLowering () const override
const DataLayout * getDataLayout () const override
const PPCInstrInfo * getInstrInfo () const override
const PPCTargetLowering * getTargetLowering () const override
const PPCSelectionDAGInfo * getSelectionDAGInfo () const override
const PPCRegisterInfo * getRegisterInfo () const override
PPCSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
bool isPPC64 () const
bool has64BitSupport () const
bool use64BitRegs () const
bool useCRBits () const
bool hasLazyResolverStub (const GlobalValue *GV, const TargetMachine &TM) const
bool isLittleEndian () const
bool hasFCPSGN () const
bool hasFSQRT () const
bool hasFRE () const
bool hasFRES () const
bool hasFRSQRTE () const
bool hasFRSQRTES () const
bool hasRecipPrec () const
bool hasSTFIWX () const
bool hasLFIWAX () const
bool hasFPRND () const
bool hasFPCVT () const
bool hasAltivec () const
bool hasSPE () const
bool hasQPX () const
bool hasVSX () const
bool hasP8Vector () const
bool hasMFOCRF () const
bool hasISEL () const
bool hasPOPCNTD () const
bool hasCMPB () const
bool hasLDBRX () const
bool isBookE () const
bool hasOnlyMSYNC () const
bool isPPC4xx () const
bool isPPC6xx () const
bool isE500 () const
bool isDeprecatedMFTB () const
bool isDeprecatedDST () const
const Triple & getTargetTriple () const
bool isDarwin () const
isDarwin - True if this is any darwin platform.
bool isBGQ () const
isBGQ - True if this is a BG/Q platform.
bool isTargetELF () const
bool isTargetMachO () const
bool isDarwinABI () const
bool isSVR4ABI () const
bool isELFv2ABI () const
bool enableEarlyIfConversion () const override
bool enableMachineScheduler () const override
bool enablePostMachineScheduler () const override
AntiDepBreakMode getAntiDepBreakMode () const override
void getCriticalPathRCs (RegClassVector &CriticalPathRCs) const override
void overrideSchedPolicy (MachineSchedPolicy &Policy, MachineInstr *begin, MachineInstr *end, unsigned NumRegionInstrs) const override
bool useAA () const override
bool enableSubRegLiveness () const override
Protected Types
enum { PPC_ABI_UNKNOWN, PPC_ABI_ELFv1, PPC_ABI_ELFv2 }
Protected Attributes
Triple TargetTriple
TargetTriple - What processor and OS we're targeting.
const DataLayout DL
unsigned StackAlignment
InstrItineraryData InstrItins
Selected instruction itineraries (one entry per itinerary class.)
unsigned DarwinDirective
Which cpu directive was used.
bool HasMFOCRF
Used by the ISel to turn in optimizations for POWER4-derived architectures.
bool Has64BitSupport
bool Use64BitRegs
bool UseCRBits
bool IsPPC64
bool HasAltivec
bool HasSPE
bool HasQPX
bool HasVSX
bool HasP8Vector
bool HasFCPSGN
bool HasFSQRT
bool HasFRE
bool HasFRES
bool HasFRSQRTE
bool HasFRSQRTES
bool HasRecipPrec
bool HasSTFIWX
bool HasLFIWAX
bool HasFPRND
bool HasFPCVT
bool HasISEL
bool HasPOPCNTD
bool HasCMPB
bool HasLDBRX
bool IsBookE
bool HasOnlyMSYNC
bool IsE500
bool IsPPC4xx
bool IsPPC6xx
bool DeprecatedMFTB
bool DeprecatedDST
bool HasLazyResolverStubs
bool IsLittleEndian
enum llvm::PPCSubtarget:: { ... } TargetABI
PPCFrameLowering FrameLowering
PPCInstrInfo InstrInfo
PPCTargetLowering TLInfo
PPCSelectionDAGInfo TSInfo
Detailed Description
Definition at line 66 of file PPCSubtarget.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
PPC_ABI_UNKNOWN
PPC_ABI_ELFv1
PPC_ABI_ELFv2
Definition at line 117 of file PPCSubtarget.h.
Constructor & Destructor Documentation
PPCSubtarget::PPCSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS, const PPCTargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 80 of file PPCSubtarget.cpp.
Member Function Documentation
bool llvm::PPCSubtarget::enableEarlyIfConversion () const inline override
Definition at line 248 of file PPCSubtarget.h.
References hasISEL().
bool PPCSubtarget::enableMachineScheduler () const override
Definition at line 202 of file PPCSubtarget.cpp.
References DarwinDirective, and needsAggressiveScheduling().
Referenced by llvm::PPCTargetLowering::getSchedulingPreference(), and llvm::PPCTargetLowering::PPCTargetLowering().
bool PPCSubtarget::enablePostMachineScheduler () const override
Definition at line 210 of file PPCSubtarget.cpp.
bool PPCSubtarget::enableSubRegLiveness () const override
Definition at line 241 of file PPCSubtarget.cpp.
References UseSubRegLiveness.
PPCGenSubtargetInfo::AntiDepBreakMode PPCSubtarget::getAntiDepBreakMode () const override
Definition at line 212 of file PPCSubtarget.cpp.
References llvm::TargetSubtargetInfo::ANTIDEP_ALL.
void PPCSubtarget::getCriticalPathRCs (RegClassVector & CriticalPathRCs) const override
Definition at line 216 of file PPCSubtarget.cpp.
References isPPC64().
unsigned llvm::PPCSubtarget::getDarwinDirective () const inline
getDarwinDirective - Returns the -m directive specified for the cpu.
Definition at line 146 of file PPCSubtarget.h.
References DarwinDirective.
Referenced by llvm::PPCInstrInfo::getOperandLatency(), llvm::PPCTargetLowering::getPrefLoopAlignment(), llvm::PPCInstrInfo::insertNoop(), and llvm::PPCTargetLowering::PPCTargetLowering().
const DataLayout* llvm::PPCSubtarget::getDataLayout () const inline override
Definition at line 157 of file PPCSubtarget.h.
References DL.
const PPCFrameLowering* llvm::PPCSubtarget::getFrameLowering () const inline override
Definition at line 154 of file PPCSubtarget.h.
References FrameLowering.
const PPCInstrInfo* llvm::PPCSubtarget::getInstrInfo () const inline override
Definition at line 158 of file PPCSubtarget.h.
References InstrInfo.
Referenced by getRegisterInfo().
const InstrItineraryData* llvm::PPCSubtarget::getInstrItineraryData () const inline override
getInstrItins - Return the instruction itineraries based on subtarget selection.
Definition at line 150 of file PPCSubtarget.h.
References InstrItins.
const PPCRegisterInfo* llvm::PPCSubtarget::getRegisterInfo () const inline override
Definition at line 165 of file PPCSubtarget.h.
References getInstrInfo(), and llvm::PPCInstrInfo::getRegisterInfo().
const PPCSelectionDAGInfo* llvm::PPCSubtarget::getSelectionDAGInfo () const inline override
Definition at line 162 of file PPCSubtarget.h.
References TSInfo.
unsigned llvm::PPCSubtarget::getStackAlignment () const inline
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 142 of file PPCSubtarget.h.
References StackAlignment.
const PPCTargetLowering* llvm::PPCSubtarget::getTargetLowering () const inline override
Definition at line 159 of file PPCSubtarget.h.
References TLInfo.
const Triple& llvm::PPCSubtarget::getTargetTriple () const inline
Definition at line 234 of file PPCSubtarget.h.
References TargetTriple.
Referenced by PrepareCall().
bool llvm::PPCSubtarget::has64BitSupport () const inline
has64BitSupport - Return true if the selected CPU supports 64-bit instructions, regardless of whether we are in 32-bit or 64-bit mode.
Definition at line 184 of file PPCSubtarget.h.
References Has64BitSupport.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasAltivec () const inline
Definition at line 216 of file PPCSubtarget.h.
References HasAltivec.
Referenced by llvm::PPCTargetLowering::getByValTypeAlignment(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getReservedRegs(), and llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasCMPB () const inline
Definition at line 224 of file PPCSubtarget.h.
References HasCMPB.
bool llvm::PPCSubtarget::hasFCPSGN () const inline
Definition at line 205 of file PPCSubtarget.h.
References HasFCPSGN.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasFPCVT () const inline
Definition at line 215 of file PPCSubtarget.h.
References HasFPCVT.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasFPRND () const inline
Definition at line 214 of file PPCSubtarget.h.
References HasFPRND.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasFRE () const inline
Definition at line 207 of file PPCSubtarget.h.
References HasFRE.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasFRES () const inline
Definition at line 208 of file PPCSubtarget.h.
References HasFRES.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasFRSQRTE () const inline
Definition at line 209 of file PPCSubtarget.h.
References HasFRSQRTE.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasFRSQRTES () const inline
Definition at line 210 of file PPCSubtarget.h.
References HasFRSQRTES.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasFSQRT () const inline
Definition at line 206 of file PPCSubtarget.h.
References HasFSQRT.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasISEL () const inline
Definition at line 222 of file PPCSubtarget.h.
References HasISEL.
Referenced by llvm::PPCInstrInfo::canInsertSelect(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), enableEarlyIfConversion(), and llvm::PPCInstrInfo::insertSelect().
bool PPCSubtarget::hasLazyResolverStub (const GlobalValue * GV, const TargetMachine & TM) const
hasLazyResolverStub - Return true if accesses to the specified global have to go through a dyld lazy resolution stub. This means that an extra load is required to get the address of the global.
Definition at line 176 of file PPCSubtarget.cpp.
References llvm::TargetMachine::getRelocationModel(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasHiddenVisibility(), HasLazyResolverStubs, llvm::GlobalValue::hasLinkOnceLinkage(), llvm::GlobalValue::hasWeakLinkage(), llvm::GlobalValue::isDeclaration(), and llvm::Reloc::Static.
Referenced by GetLabelAccessInfo().
bool llvm::PPCSubtarget::hasLDBRX () const inline
Definition at line 225 of file PPCSubtarget.h.
References HasLDBRX.
bool llvm::PPCSubtarget::hasLFIWAX () const inline
Definition at line 213 of file PPCSubtarget.h.
References HasLFIWAX.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasMFOCRF () const inline
Definition at line 221 of file PPCSubtarget.h.
References HasMFOCRF.
bool llvm::PPCSubtarget::hasOnlyMSYNC () const inline
Definition at line 227 of file PPCSubtarget.h.
References HasOnlyMSYNC.
bool llvm::PPCSubtarget::hasP8Vector () const inline
Definition at line 220 of file PPCSubtarget.h.
References HasP8Vector.
bool llvm::PPCSubtarget::hasPOPCNTD () const inline
Definition at line 223 of file PPCSubtarget.h.
References HasPOPCNTD.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::hasQPX () const inline
Definition at line 218 of file PPCSubtarget.h.
References HasQPX.
Referenced by llvm::PPCTargetLowering::getByValTypeAlignment().
bool llvm::PPCSubtarget::hasRecipPrec () const inline
Definition at line 211 of file PPCSubtarget.h.
References HasRecipPrec.
bool llvm::PPCSubtarget::hasSPE () const inline
Definition at line 217 of file PPCSubtarget.h.
References HasSPE.
bool llvm::PPCSubtarget::hasSTFIWX () const inline
Definition at line 212 of file PPCSubtarget.h.
References HasSTFIWX.
Referenced by llvm::PPCTargetLowering::PerformDAGCombine().
bool llvm::PPCSubtarget::hasVSX () const inline
Definition at line 219 of file PPCSubtarget.h.
References HasVSX.
Referenced by llvm::PPCTargetLowering::allowsMisalignedMemoryAccesses(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), llvm::PPCTargetLowering::PerformDAGCombine(), and llvm::PPCTargetLowering::PPCTargetLowering().
PPCSubtarget & PPCSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
initializeSubtargetDependencies - Initializes using a CPU and feature string so that we can use initializer lists for subtarget initialization.
Definition at line 73 of file PPCSubtarget.cpp.
bool llvm::PPCSubtarget::isBGQ () const inline
isBGQ - True if this is a BG/Q platform.
Definition at line 239 of file PPCSubtarget.h.
References llvm::Triple::BGQ, llvm::Triple::getVendor(), and TargetTriple.
bool llvm::PPCSubtarget::isBookE () const inline
Definition at line 226 of file PPCSubtarget.h.
References IsBookE.
bool llvm::PPCSubtarget::isDarwin () const inline
isDarwin - True if this is any darwin platform.
Definition at line 237 of file PPCSubtarget.h.
References llvm::Triple::isMacOSX(), and TargetTriple.
Referenced by createPPCAsmPrinterPass(), llvm::PPCTargetLowering::getByValTypeAlignment(), isDarwinABI(), isSVR4ABI(), and llvm::PPCTargetLowering::PPCTargetLowering().
bool llvm::PPCSubtarget::isDarwinABI () const inline
Definition at line 244 of file PPCSubtarget.h.
References isDarwin().
Referenced by llvm::PPCFrameLowering::determineFrameLayout(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCTargetLowering::getRegisterByName(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
bool llvm::PPCSubtarget::isDeprecatedDST () const inline
Definition at line 232 of file PPCSubtarget.h.
References DeprecatedDST.
bool llvm::PPCSubtarget::isDeprecatedMFTB () const inline
Definition at line 231 of file PPCSubtarget.h.
References DeprecatedMFTB.
bool llvm::PPCSubtarget::isE500 () const inline
Definition at line 230 of file PPCSubtarget.h.
References IsE500.
bool llvm::PPCSubtarget::isELFv2ABI () const inline
Definition at line 246 of file PPCSubtarget.h.
References PPC_ABI_ELFv2, and TargetABI.
Referenced by llvm::PPCFrameLowering::determineFrameLayout(), llvm::PPCFrameLowering::emitPrologue(), and PrepareCall().
bool llvm::PPCSubtarget::isLittleEndian () const inline
Definition at line 202 of file PPCSubtarget.h.
References IsLittleEndian.
Referenced by llvm::PPCTargetLowering::PerformDAGCombine().
bool llvm::PPCSubtarget::isPPC4xx () const inline
Definition at line 228 of file PPCSubtarget.h.
References IsPPC4xx.
bool llvm::PPCSubtarget::isPPC64 () const inline
isPPC64 - Return true if we are generating code for 64-bit pointer mode.
Definition at line 180 of file PPCSubtarget.h.
References IsPPC64.
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::PPCInstrInfo::AnalyzeBranch(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::PPC::createFastISel(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCInstrInfo::FoldImmediate(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCTargetLowering::getByValTypeAlignment(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), llvm::PPCRegisterInfo::getCallPreservedMask(), getCriticalPathRCs(), llvm::PPCRegisterInfo::getFrameRegister(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::PPCRegisterInfo::getPointerRegClass(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTargetLowering::getRegisterByName(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::hasReservedSpillSlot(), llvm::PPCInstrInfo::InsertBranch(), llvm::PPCTargetLowering::isZExtFree(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCInstrInfo::PredicateInstruction(), PrepareCall(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegRegOnly(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
bool llvm::PPCSubtarget::isPPC6xx () const inline
Definition at line 229 of file PPCSubtarget.h.
References IsPPC6xx.
bool llvm::PPCSubtarget::isSVR4ABI () const inline
Definition at line 245 of file PPCSubtarget.h.
References isDarwin().
Referenced by llvm::PPC::createFastISel(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::hasReservedSpillSlot(), llvm::PPCTargetLowering::PPCTargetLowering(), PrepareCall(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
bool llvm::PPCSubtarget::isTargetELF () const inline
Definition at line 241 of file PPCSubtarget.h.
References llvm::Triple::isOSBinFormatELF(), and TargetTriple.
Referenced by PrepareCall().
bool llvm::PPCSubtarget::isTargetMachO () const inline
Definition at line 242 of file PPCSubtarget.h.
References llvm::Triple::isOSBinFormatMachO(), and TargetTriple.
void PPCSubtarget::overrideSchedPolicy (MachineSchedPolicy & Policy, MachineInstr * begin, MachineInstr * end, unsigned NumRegionInstrs) const override
Definition at line 222 of file PPCSubtarget.cpp.
References DarwinDirective, needsAggressiveScheduling(), llvm::MachineSchedPolicy::OnlyBottomUp, llvm::MachineSchedPolicy::OnlyTopDown, and llvm::MachineSchedPolicy::ShouldTrackPressure.
void llvm::PPCSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
bool llvm::PPCSubtarget::use64BitRegs () const inline
use64BitRegs - Return true if in 64-bit mode or if we should use 64-bit registers in 32-bit mode when possible. This can only true if has64BitSupport() returns true.
Definition at line 189 of file PPCSubtarget.h.
References Use64BitRegs.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
bool PPCSubtarget::useAA () const override
Definition at line 236 of file PPCSubtarget.cpp.
References DarwinDirective, and needsAggressiveScheduling().
bool llvm::PPCSubtarget::useCRBits () const inline
useCRBits - Return true if we should store and manipulate i1 values in the individual condition register bits.
Definition at line 193 of file PPCSubtarget.h.
References UseCRBits.
Referenced by llvm::PPCTargetLowering::getSetCCResultType(), and llvm::PPCTargetLowering::PPCTargetLowering().
Member Data Documentation
unsigned llvm::PPCSubtarget::DarwinDirective protected
Which cpu directive was used.
Definition at line 82 of file PPCSubtarget.h.
Referenced by enableMachineScheduler(), getDarwinDirective(), overrideSchedPolicy(), and useAA().
bool llvm::PPCSubtarget::DeprecatedDST protected
Definition at line 113 of file PPCSubtarget.h.
Referenced by isDeprecatedDST().
bool llvm::PPCSubtarget::DeprecatedMFTB protected
Definition at line 112 of file PPCSubtarget.h.
Referenced by isDeprecatedMFTB().
const DataLayout llvm::PPCSubtarget::DL protected
Definition at line 72 of file PPCSubtarget.h.
Referenced by getDataLayout().
PPCFrameLowering llvm::PPCSubtarget::FrameLowering protected
Definition at line 123 of file PPCSubtarget.h.
Referenced by getFrameLowering().
bool llvm::PPCSubtarget::Has64BitSupport protected
Definition at line 86 of file PPCSubtarget.h.
Referenced by has64BitSupport().
bool llvm::PPCSubtarget::HasAltivec protected
Definition at line 90 of file PPCSubtarget.h.
Referenced by hasAltivec().
bool llvm::PPCSubtarget::HasCMPB protected
Definition at line 105 of file PPCSubtarget.h.
Referenced by hasCMPB().
bool llvm::PPCSubtarget::HasFCPSGN protected
Definition at line 95 of file PPCSubtarget.h.
Referenced by hasFCPSGN().
bool llvm::PPCSubtarget::HasFPCVT protected
Definition at line 102 of file PPCSubtarget.h.
Referenced by hasFPCVT().
bool llvm::PPCSubtarget::HasFPRND protected
Definition at line 101 of file PPCSubtarget.h.
Referenced by hasFPRND().
bool llvm::PPCSubtarget::HasFRE protected
Definition at line 97 of file PPCSubtarget.h.
Referenced by hasFRE().
bool llvm::PPCSubtarget::HasFRES protected
Definition at line 97 of file PPCSubtarget.h.
Referenced by hasFRES().
bool llvm::PPCSubtarget::HasFRSQRTE protected
Definition at line 97 of file PPCSubtarget.h.
Referenced by hasFRSQRTE().
bool llvm::PPCSubtarget::HasFRSQRTES protected
Definition at line 97 of file PPCSubtarget.h.
Referenced by hasFRSQRTES().
bool llvm::PPCSubtarget::HasFSQRT protected
Definition at line 96 of file PPCSubtarget.h.
Referenced by hasFSQRT().
bool llvm::PPCSubtarget::HasISEL protected
Definition at line 103 of file PPCSubtarget.h.
Referenced by hasISEL().
bool llvm::PPCSubtarget::HasLazyResolverStubs protected
Definition at line 114 of file PPCSubtarget.h.
Referenced by hasLazyResolverStub().
bool llvm::PPCSubtarget::HasLDBRX protected
Definition at line 106 of file PPCSubtarget.h.
Referenced by hasLDBRX().
bool llvm::PPCSubtarget::HasLFIWAX protected
Definition at line 100 of file PPCSubtarget.h.
Referenced by hasLFIWAX().
bool llvm::PPCSubtarget::HasMFOCRF protected
Used by the ISel to turn in optimizations for POWER4-derived architectures.
Definition at line 85 of file PPCSubtarget.h.
Referenced by hasMFOCRF().
bool llvm::PPCSubtarget::HasOnlyMSYNC protected
Definition at line 108 of file PPCSubtarget.h.
Referenced by hasOnlyMSYNC().
bool llvm::PPCSubtarget::HasP8Vector protected
Definition at line 94 of file PPCSubtarget.h.
Referenced by hasP8Vector().
bool llvm::PPCSubtarget::HasPOPCNTD protected
Definition at line 104 of file PPCSubtarget.h.
Referenced by hasPOPCNTD().
bool llvm::PPCSubtarget::HasQPX protected
Definition at line 92 of file PPCSubtarget.h.
Referenced by hasQPX().
bool llvm::PPCSubtarget::HasRecipPrec protected
Definition at line 98 of file PPCSubtarget.h.
Referenced by hasRecipPrec().
bool llvm::PPCSubtarget::HasSPE protected
Definition at line 91 of file PPCSubtarget.h.
Referenced by hasSPE().
bool llvm::PPCSubtarget::HasSTFIWX protected
Definition at line 99 of file PPCSubtarget.h.
Referenced by hasSTFIWX().
bool llvm::PPCSubtarget::HasVSX protected
Definition at line 93 of file PPCSubtarget.h.
Referenced by hasVSX().
PPCInstrInfo llvm::PPCSubtarget::InstrInfo protected
Definition at line 124 of file PPCSubtarget.h.
Referenced by getInstrInfo().
InstrItineraryData llvm::PPCSubtarget::InstrItins protected
Selected instruction itineraries (one entry per itinerary class.)
Definition at line 79 of file PPCSubtarget.h.
Referenced by getInstrItineraryData().
bool llvm::PPCSubtarget::IsBookE protected
Definition at line 107 of file PPCSubtarget.h.
Referenced by isBookE().
bool llvm::PPCSubtarget::IsE500 protected
Definition at line 109 of file PPCSubtarget.h.
Referenced by isE500().
bool llvm::PPCSubtarget::IsLittleEndian protected
Definition at line 115 of file PPCSubtarget.h.
Referenced by isLittleEndian().
bool llvm::PPCSubtarget::IsPPC4xx protected
Definition at line 110 of file PPCSubtarget.h.
Referenced by isPPC4xx().
bool llvm::PPCSubtarget::IsPPC64 protected
Definition at line 89 of file PPCSubtarget.h.
Referenced by isPPC64().
bool llvm::PPCSubtarget::IsPPC6xx protected
Definition at line 111 of file PPCSubtarget.h.
Referenced by isPPC6xx().
unsigned llvm::PPCSubtarget::StackAlignment protected
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
Definition at line 76 of file PPCSubtarget.h.
Referenced by getStackAlignment().
enum { ... } llvm::PPCSubtarget::TargetABI
Referenced by isELFv2ABI().
Triple llvm::PPCSubtarget::TargetTriple protected
TargetTriple - What processor and OS we're targeting.
Definition at line 69 of file PPCSubtarget.h.
Referenced by getTargetTriple(), isBGQ(), isDarwin(), isTargetELF(), and isTargetMachO().
PPCTargetLowering llvm::PPCSubtarget::TLInfo protected
Definition at line 125 of file PPCSubtarget.h.
Referenced by getTargetLowering().
PPCSelectionDAGInfo llvm::PPCSubtarget::TSInfo protected
Definition at line 126 of file PPCSubtarget.h.
Referenced by getSelectionDAGInfo().
bool llvm::PPCSubtarget::Use64BitRegs protected
Definition at line 87 of file PPCSubtarget.h.
Referenced by use64BitRegs().
bool llvm::PPCSubtarget::UseCRBits protected
Definition at line 88 of file PPCSubtarget.h.
Referenced by useCRBits().
The documentation for this class was generated from the following files:
PPCSubtarget.h
PPCSubtarget.cpp