LLVM: llvm::TargetLoweringBase::ValueTypeActionImpl Class Reference
LLVM API Documentation
llvm::TargetLoweringBase::ValueTypeActionImpl Class Reference
#include <TargetLowering.h>
Public Member Functions
ValueTypeActionImpl ()
LegalizeTypeAction getTypeAction (MVT VT) const
void setTypeAction (MVT VT, LegalizeTypeAction Action)
Detailed Description
Definition at line 387 of file TargetLowering.h.
Constructor & Destructor Documentation
llvm::TargetLoweringBase::ValueTypeActionImpl::ValueTypeActionImpl () inline
Definition at line 393 of file TargetLowering.h.
References llvm::sys::path::begin(), and llvm::sys::path::end().
Member Function Documentation
LegalizeTypeAction llvm::TargetLoweringBase::ValueTypeActionImpl::getTypeAction (MVT VT) const inline
Definition at line 397 of file TargetLowering.h.
References llvm::MVT::SimpleTy.
Referenced by llvm::TargetLoweringBase::getTypeAction(), and llvm::TargetLoweringBase::getTypeConversion().
void llvm::TargetLoweringBase::ValueTypeActionImpl::setTypeAction (MVT VT, LegalizeTypeAction Action) inline
Definition at line 401 of file TargetLowering.h.
References I, and llvm::MVT::SimpleTy.
Referenced by llvm::TargetLoweringBase::computeRegisterProperties().
The documentation for this class was generated from the following file:
TargetLowering.h