LLVM: llvm::HexagonAsmPrinter Class Reference
LLVM API Documentation
llvm::HexagonAsmPrinter Class Reference
#include <HexagonAsmPrinter.h>
Public Member Functions
HexagonAsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
const char * getPassName () const override
bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const override
void EmitInstruction (const MachineInstr *MI) override
void printOperand (const MachineInstr *MI, unsigned OpNo, raw_ostream &O)
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS) override
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS) override
Public Member Functions inherited from llvm::AsmPrinter
virtual ~AsmPrinter ()
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
bool isVerbose () const
unsigned getFunctionNumber () const
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
StringRef getTargetTriple () const
Return the target triple string.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool doInitialization (Module &M) override
bool doFinalization (Module &M) override
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
void SetupMachineFunction (MachineFunction &MF)
void EmitFunctionHeader ()
This method emits the header for the current function.
void EmitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
CFIMoveType needsCFIMoves ()
bool needsSEHMoves ()
virtual void EmitConstantPool ()
void EmitJumpTableInfo ()
virtual void EmitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
void EmitAlignment (unsigned NumBits, const GlobalObject *GO=nullptr) const
void EmitBasicBlockStart (const MachineBasicBlock &MBB) const
const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void EmitGlobalConstant (const Constant *CV)
Print a general LLVM constant to the .s file.
virtual void EmitStartOfAsmFile (Module &)
virtual void EmitEndOfAsmFile (Module &)
virtual void EmitFunctionBodyStart ()
virtual void EmitFunctionBodyEnd ()
virtual void EmitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void EmitFunctionEntryLabel ()
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void EmitXXStructor (const Constant *CV)
virtual void emitImplicitDef (const MachineInstr *MI) const
MCSymbol * GetTempSymbol (Twine Name, unsigned ID) const
MCSymbol * GetTempSymbol (Twine Name) const
Return an assembler temporary label with the specified stem.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void EmitInt8 (int Value) const
void EmitInt16 (int Value) const
void EmitInt32 (int Value) const
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
void EmitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void EmitCFAByte (unsigned Val) const
Emit a .byte 42 directive for a DW_CFA_xxx value.
void EmitEncodingByte (unsigned Val, const char *Desc=nullptr) const
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
void EmitSectionOffset (const MCSymbol *Label, const MCSymbol *SectionLabel) const
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void EmitDwarfOpPiece (ByteStreamer &Streamer, unsigned SizeInBits, unsigned OffsetInBits=0) const
void EmitDwarfRegOpPiece (ByteStreamer &BS, const MachineLocation &MLoc, unsigned PieceSize=0, unsigned PieceOffset=0) const
Emit a partial DWARF register operation.
virtual void EmitDwarfRegOp (ByteStreamer &BS, const MachineLocation &MLoc, bool Indirect) const
EmitDwarfRegOp - Emit dwarf register operation.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
virtual void emitInlineAsmStart (const MCSubtargetInfo &StartInfo) const
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
const MCAsmInfo * MAI
const MCInstrInfo * MII
MCContext & OutContext
MCStreamer & OutStreamer
const MachineFunction * MF
The current machine function.
MachineModuleInfo * MMI
This is a pointer to the current MachineModuleInfo.
Mangler * Mang
MCSymbol * CurrentFnSym
MCSymbol * CurrentFnSymForSize
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 24 of file HexagonAsmPrinter.h.
Constructor & Destructor Documentation
llvm::HexagonAsmPrinter::HexagonAsmPrinter (TargetMachine & TM, MCStreamer & Streamer) inline explicit
Definition at line 28 of file HexagonAsmPrinter.h.
References llvm::TargetMachine::getSubtarget().
Member Function Documentation
void HexagonAsmPrinter::EmitInstruction (const MachineInstr * MI) override virtual
printMachineInstruction – Print out a single Hexagon MI in Darwin syntax to the current output stream.
Reimplemented from llvm::AsmPrinter.
Definition at line 175 of file HexagonAsmPrinter.cpp.
References llvm::HexagonMCInst::AppendImplicitOperands(), assert(), llvm::TargetOpcode::DBG_VALUE, llvm::AsmPrinter::EmitToStreamer(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getBundleSize(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getParent(), llvm::HexagonLowerToMC(), llvm::TargetOpcode::IMPLICIT_DEF, llvm::MachineInstr::isBundle(), llvm::AArch64CC::MI, llvm::AsmPrinter::MII, llvm::AsmPrinter::OutStreamer, llvm::HexagonMCInst::setPacketBegin(), and llvm::HexagonMCInst::setPacketEnd().
const char* llvm::HexagonAsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 33 of file HexagonAsmPrinter.h.
static const char* llvm::HexagonAsmPrinter::getRegisterName (unsigned RegNo) static
bool HexagonAsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const override virtual
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented from llvm::AsmPrinter.
Definition at line 99 of file HexagonAsmPrinter.cpp.
References llvm::MachineBasicBlock::hasAddressTaken(), and llvm::AsmPrinter::isBlockOnlyReachableByFallthrough().
bool HexagonAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 146 of file HexagonAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm_unreachable, and printOperand().
bool HexagonAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) override virtual
PrintAsmOperand - Print out an operand for an inline asm expression.
Reimplemented from llvm::AsmPrinter.
Definition at line 109 of file HexagonAsmPrinter.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::AsmPrinter::PrintAsmOperand(), and printOperand().
void HexagonAsmPrinter::printOperand (const MachineInstr * MI, unsigned OpNo, raw_ostream & O)
Definition at line 64 of file HexagonAsmPrinter.cpp.
References llvm::AsmPrinter::GetCPISymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::HexagonInstPrinter::getRegisterName(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, and llvm::AsmPrinter::printOffset().
Referenced by PrintAsmMemoryOperand(), and PrintAsmOperand().
The documentation for this class was generated from the following files:
HexagonAsmPrinter.h
HexagonAsmPrinter.cpp