LLVM: llvm::object::ImportedSymbolRef Class Reference
LLVM API Documentation
llvm::object::ImportedSymbolRef Class Reference
#include <COFF.h>
Public Member Functions
ImportedSymbolRef ()
ImportedSymbolRef (const import_lookup_table_entry32 *Entry, uint32_t I, const COFFObjectFile *Owner)
ImportedSymbolRef (const import_lookup_table_entry64 *Entry, uint32_t I, const COFFObjectFile *Owner)
bool operator== (const ImportedSymbolRef &Other) const
void moveNext ()
std::error_code getSymbolName (StringRef &Result) const
std::error_code getOrdinal (uint16_t &Result) const
Detailed Description
Definition at line 804 of file Object/COFF.h.
Constructor & Destructor Documentation
llvm::object::ImportedSymbolRef::ImportedSymbolRef () inline
Definition at line 806 of file Object/COFF.h.
llvm::object::ImportedSymbolRef::ImportedSymbolRef (const import_lookup_table_entry32 * Entry, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 807 of file Object/COFF.h.
llvm::object::ImportedSymbolRef::ImportedSymbolRef (const import_lookup_table_entry64 * Entry, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 810 of file Object/COFF.h.
Member Function Documentation
std::error_code ImportedSymbolRef::getOrdinal (uint16_t & Result) const
Definition at line 1428 of file COFFObjectFile.cpp.
References llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::object::import_lookup_table_entry< IntTy >::getOrdinal(), llvm::object::COFFObjectFile::getRvaPtr(), and llvm::object::success.
std::error_code ImportedSymbolRef::getSymbolName (StringRef & Result) const
Definition at line 1408 of file COFFObjectFile.cpp.
References llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::object::COFFObjectFile::getRvaPtr(), and llvm::object::success.
void ImportedSymbolRef::moveNext ()
Definition at line 1403 of file COFFObjectFile.cpp.
bool ImportedSymbolRef::operator== (const ImportedSymbolRef & Other) const
Definition at line 1398 of file COFFObjectFile.cpp.
The documentation for this class was generated from the following files:
Object/COFF.h
COFFObjectFile.cpp