LLVM: llvm::object::MachOObjectFile Class Reference
LLVM API Documentation
llvm::object::MachOObjectFile Class Reference
#include <MachO.h>
Classes
struct LoadCommandInfo
Public Member Functions
MachOObjectFile (MemoryBufferRef Object, bool IsLittleEndian, bool Is64Bits, std::error_code &EC)
void moveSymbolNext (DataRefImpl &Symb) const override
std::error_code getSymbolName (DataRefImpl Symb, StringRef &Res) const override
std::error_code getIndirectName (DataRefImpl Symb, StringRef &Res) const
unsigned getSectionType (SectionRef Sec) const
std::error_code getSymbolAddress (DataRefImpl Symb, uint64_t &Res) const override
std::error_code getSymbolAlignment (DataRefImpl Symb, uint32_t &Res) const override
std::error_code getSymbolSize (DataRefImpl Symb, uint64_t &Res) const override
std::error_code getSymbolType (DataRefImpl Symb, SymbolRef::Type &Res) const override
uint32_t getSymbolFlags (DataRefImpl Symb) const override
std::error_code getSymbolSection (DataRefImpl Symb, section_iterator &Res) const override
void moveSectionNext (DataRefImpl &Sec) const override
std::error_code getSectionName (DataRefImpl Sec, StringRef &Res) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
std::error_code getSectionContents (DataRefImpl Sec, StringRef &Res) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
bool sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
std::error_code getRelocationAddress (DataRefImpl Rel, uint64_t &Res) const override
std::error_code getRelocationOffset (DataRefImpl Rel, uint64_t &Res) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
std::error_code getRelocationType (DataRefImpl Rel, uint64_t &Res) const override
std::error_code getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
std::error_code getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
std::error_code getRelocationHidden (DataRefImpl Rel, bool &Result) const override
std::error_code getLibraryShortNameByIndex (unsigned Index, StringRef &) const
basic_symbol_iterator symbol_begin_impl () const override
basic_symbol_iterator symbol_end_impl () const override
basic_symbol_iterator getSymbolByIndex (unsigned Index) const
section_iterator section_begin () const override
section_iterator section_end () const override
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
unsigned getArch () const override
Triple getArch (const char **McpuDefault, Triple *ThumbTriple) const
relocation_iterator section_rel_begin (unsigned Index) const
relocation_iterator section_rel_end (unsigned Index) const
dice_iterator begin_dices () const
dice_iterator end_dices () const
iterator_range< export_iterator > exports () const
For use iterating over all exported symbols.
iterator_range< rebase_iterator > rebaseTable () const
For use iterating over all rebase table entries.
iterator_range< bind_iterator > bindTable () const
For use iterating over all bind table entries.
iterator_range< bind_iterator > lazyBindTable () const
For use iterating over all lazy bind table entries.
iterator_range< bind_iterator > weakBindTable () const
For use iterating over all lazy bind table entries.
StringRef getSectionFinalSegmentName (DataRefImpl Sec) const
ArrayRef< char > getSectionRawName (DataRefImpl Sec) const
ArrayRef< char > getSectionRawFinalSegmentName (DataRefImpl Sec) const
bool isRelocationScattered (const MachO::any_relocation_info &RE) const
unsigned getPlainRelocationSymbolNum (const MachO::any_relocation_info &RE) const
bool getPlainRelocationExternal (const MachO::any_relocation_info &RE) const
bool getScatteredRelocationScattered (const MachO::any_relocation_info &RE) const
uint32_t getScatteredRelocationValue (const MachO::any_relocation_info &RE) const
uint32_t getScatteredRelocationType (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationAddress (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationPCRel (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationLength (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationType (const MachO::any_relocation_info &RE) const
SectionRef getRelocationSection (const MachO::any_relocation_info &RE) const
LoadCommandInfo getFirstLoadCommandInfo () const
LoadCommandInfo getNextLoadCommandInfo (const LoadCommandInfo &L) const
MachO::section getSection (DataRefImpl DRI) const
MachO::section_64 getSection64 (DataRefImpl DRI) const
MachO::section getSection (const LoadCommandInfo &L, unsigned Index) const
MachO::section_64 getSection64 (const LoadCommandInfo &L, unsigned Index) const
MachO::nlist getSymbolTableEntry (DataRefImpl DRI) const
MachO::nlist_64 getSymbol64TableEntry (DataRefImpl DRI) const
MachO::linkedit_data_command getLinkeditDataLoadCommand (const LoadCommandInfo &L) const
MachO::segment_command getSegmentLoadCommand (const LoadCommandInfo &L) const
MachO::segment_command_64 getSegment64LoadCommand (const LoadCommandInfo &L) const
MachO::linker_option_command getLinkerOptionLoadCommand (const LoadCommandInfo &L) const
MachO::version_min_command getVersionMinLoadCommand (const LoadCommandInfo &L) const
MachO::dylib_command getDylibIDLoadCommand (const LoadCommandInfo &L) const
MachO::dyld_info_command getDyldInfoLoadCommand (const LoadCommandInfo &L) const
MachO::dylinker_command getDylinkerCommand (const LoadCommandInfo &L) const
MachO::uuid_command getUuidCommand (const LoadCommandInfo &L) const
MachO::rpath_command getRpathCommand (const LoadCommandInfo &L) const
MachO::source_version_command getSourceVersionCommand (const LoadCommandInfo &L) const
MachO::entry_point_command getEntryPointCommand (const LoadCommandInfo &L) const
MachO::encryption_info_command getEncryptionInfoCommand (const LoadCommandInfo &L) const
MachO::encryption_info_command_64 getEncryptionInfoCommand64 (const LoadCommandInfo &L) const
MachO::sub_framework_command getSubFrameworkCommand (const LoadCommandInfo &L) const
MachO::sub_umbrella_command getSubUmbrellaCommand (const LoadCommandInfo &L) const
MachO::sub_library_command getSubLibraryCommand (const LoadCommandInfo &L) const
MachO::sub_client_command getSubClientCommand (const LoadCommandInfo &L) const
MachO::routines_command getRoutinesCommand (const LoadCommandInfo &L) const
MachO::routines_command_64 getRoutinesCommand64 (const LoadCommandInfo &L) const
MachO::thread_command getThreadCommand (const LoadCommandInfo &L) const
MachO::any_relocation_info getRelocation (DataRefImpl Rel) const
MachO::data_in_code_entry getDice (DataRefImpl Rel) const
MachO::mach_header getHeader () const
MachO::mach_header_64 getHeader64 () const
uint32_t getIndirectSymbolTableEntry (const MachO::dysymtab_command &DLC, unsigned Index) const
MachO::data_in_code_entry getDataInCodeTableEntry (uint32_t DataOffset, unsigned Index) const
MachO::symtab_command getSymtabLoadCommand () const
MachO::dysymtab_command getDysymtabLoadCommand () const
MachO::linkedit_data_command getDataInCodeLoadCommand () const
ArrayRef< uint8_t > getDyldInfoRebaseOpcodes () const
ArrayRef< uint8_t > getDyldInfoBindOpcodes () const
ArrayRef< uint8_t > getDyldInfoWeakBindOpcodes () const
ArrayRef< uint8_t > getDyldInfoLazyBindOpcodes () const
ArrayRef< uint8_t > getDyldInfoExportsTrie () const
ArrayRef< uint8_t > getUuid () const
StringRef getStringTableData () const
bool is64Bit () const
void ReadULEB128s (uint64_t Index, SmallVectorImpl< uint64_t > &Out) const
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
bool hasPageZeroSegment () const
Public Member Functions inherited from llvm::object::ObjectFile
symbol_iterator_range symbols () const
section_iterator_range sections () const
virtual std::error_code getPlatformFlags (unsigned &Result) const
Returns platform-specific object flags, if any.
Public Member Functions inherited from llvm::object::SymbolicFile
virtual ~SymbolicFile ()
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
basic_symbol_iterator symbol_begin () const
basic_symbol_iterator symbol_end () const
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isIR () const
bool isLittleEndian () const
Static Public Member Functions
static iterator_range
< export_iterator > exports (ArrayRef< uint8_t > Trie)
For use examining a trie not in a MachOObjectFile.
static iterator_range
< rebase_iterator > rebaseTable (ArrayRef< uint8_t > Opcodes, bool is64)
For use examining rebase opcodes not in a MachOObjectFile.
static iterator_range
< bind_iterator > bindTable (ArrayRef< uint8_t > Opcodes, bool is64, MachOBindEntry::Kind)
For use examining bind opcodes not in a MachOObjectFile.
static StringRef guessLibraryShortName (StringRef Name, bool &isFramework, StringRef &Suffix)
static Triple::ArchType getArch (uint32_t CPUType)
static Triple getArch (uint32_t CPUType, uint32_t CPUSubType, const char **McpuDefault=nullptr)
static Triple getThumbArch (uint32_t CPUType, uint32_t CPUSubType, const char **McpuDefault=nullptr)
static Triple getArch (uint32_t CPUType, uint32_t CPUSubType, const char **McpuDefault, Triple *ThumbTriple)
static bool isValidArch (StringRef ArchFlag)
static Triple getHostArch ()
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static ErrorOr< OwningBinary
< ObjectFile > > createObjectFile (StringRef ObjectPath)
Create ObjectFile from path.
static ErrorOr
< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, sys::fs::file_magic Type)
static ErrorOr
< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static ErrorOr
< std::unique_ptr
< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static ErrorOr
< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object)
static ErrorOr
< std::unique_ptr
< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static ErrorOr
< std::unique_ptr
< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, sys::fs::file_magic Type, LLVMContext *Context)
static ErrorOr
< std::unique_ptr
< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static ErrorOr< OwningBinary
< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
typedef iterator_range
< symbol_iterator > symbol_iterator_range
typedef iterator_range
< section_iterator > section_iterator_range
Public Types inherited from llvm::object::SymbolicFile
typedef iterator_range
< basic_symbol_iterator > basic_symbol_iterator_range
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_IR, ID_StartObjects,
ID_COFF, ID_ELF32L, ID_ELF32B, ID_ELF64L,
ID_ELF64B, ID_MachO32L, ID_MachO32B, ID_MachO64L,
ID_MachO64B, ID_EndObjects
}
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
std::error_code printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual std::error_code getSymbolOther (DataRefImpl Symb, uint8_t &Res) const
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 187 of file Object/MachO.h.
Constructor & Destructor Documentation
MachOObjectFile::MachOObjectFile (MemoryBufferRef Object, bool IsLittleEndian, bool Is64Bits, std::error_code & EC)
Definition at line 232 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, llvm::MachO::load_command::cmd, getFirstLoadCommandInfo(), getHeader(), getNextLoadCommandInfo(), getSectionPtr(), getSegmentLoadCommandNumSections(), I, is64Bit(), isPageZeroSegment(), llvm::MachO::LC_DATA_IN_CODE, llvm::MachO::LC_DYLD_INFO, llvm::MachO::LC_DYLD_INFO_ONLY, llvm::MachO::LC_DYSYMTAB, llvm::MachO::LC_LAZY_LOAD_DYLIB, llvm::MachO::LC_LOAD_DYLIB, llvm::MachO::LC_LOAD_UPWARD_DYLIB, llvm::MachO::LC_LOAD_WEAK_DYLIB, llvm::MachO::LC_REEXPORT_DYLIB, llvm::MachO::LC_SEGMENT, llvm::MachO::LC_SEGMENT_64, llvm::MachO::LC_SYMTAB, llvm::MachO::LC_UUID, llvm::SPII::Load, llvm::MachO::mach_header::ncmds, llvm::object::parse_failed, llvm::object::MachOObjectFile::LoadCommandInfo::Ptr, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Member Function Documentation
dice_iterator MachOObjectFile::begin_dices () const
Definition at line 1462 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, getDataInCodeLoadCommand(), getPtr(), and llvm::object::DataRefImpl::p.
iterator_range<bind_iterator> llvm::object::MachOObjectFile::bindTable () const
For use iterating over all bind table entries.
Referenced by lazyBindTable(), and weakBindTable().
static iterator_range<bind_iterator> llvm::object::MachOObjectFile::bindTable (ArrayRef< uint8_t > Opcodes, bool is64, MachOBindEntry::Kind) static
For use examining bind opcodes not in a MachOObjectFile.
static bool llvm::object::MachOObjectFile::classof (const Binary * v) inline static
Definition at line 426 of file Object/MachO.h.
References llvm::object::Binary::isMachO().
dice_iterator MachOObjectFile::end_dices () const
Definition at line 1472 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, getDataInCodeLoadCommand(), getPtr(), and llvm::object::DataRefImpl::p.
iterator_range<export_iterator> llvm::object::MachOObjectFile::exports () const
For use iterating over all exported symbols.
iterator_range< export_iterator > MachOObjectFile::exports (ArrayRef< uint8_t > Trie) static
For use examining a trie not in a MachOObjectFile.
Definition at line 1644 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::size().
unsigned MachOObjectFile::getAnyRelocationAddress (const MachO::any_relocation_info & RE) const
Definition at line 2157 of file MachOObjectFile.cpp.
References getPlainRelocationAddress(), getScatteredRelocationAddress(), and isRelocationScattered().
Referenced by getRelocationOffset().
unsigned MachOObjectFile::getAnyRelocationLength (const MachO::any_relocation_info & RE) const
Definition at line 2171 of file MachOObjectFile.cpp.
References getPlainRelocationLength(), getScatteredRelocationLength(), and isRelocationScattered().
Referenced by llvm::RuntimeDyldMachO::getRelocationEntry(), getRelocationValueString(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
unsigned MachOObjectFile::getAnyRelocationPCRel (const MachO::any_relocation_info & RE) const
Definition at line 2164 of file MachOObjectFile.cpp.
References getPlainRelocationPCRel(), getScatteredRelocationPCRel(), and isRelocationScattered().
Referenced by llvm::RuntimeDyldMachO::getRelocationEntry(), getRelocationValueString(), llvm::RuntimeDyldMachO::makeValueAddendPCRel(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
unsigned MachOObjectFile::getAnyRelocationType (const MachO::any_relocation_info & RE) const
Definition at line 2179 of file MachOObjectFile.cpp.
References getPlainRelocationType(), getScatteredRelocationType(), and isRelocationScattered().
Referenced by llvm::RuntimeDyldMachO::getRelocationEntry(), getRelocationType(), getRelocationValueString(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
unsigned llvm::object::MachOObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Referenced by getArch(), llvm::object::MachOUniversalBinary::ObjectForArch::getArchTypeName(), getRelocationHidden(), getRelocationTypeName(), and getRelocationValueString().
Triple llvm::object::MachOObjectFile::getArch (const char ** McpuDefault, Triple * ThumbTriple) const
Triple::ArchType MachOObjectFile::getArch (uint32_t CPUType) static
Definition at line 1254 of file MachOObjectFile.cpp.
References llvm::Triple::aarch64, llvm::Triple::arm, llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, llvm::MachO::CPU_TYPE_X86_64, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
static Triple llvm::object::MachOObjectFile::getArch (uint32_t CPUType, uint32_t CPUSubType, const char ** McpuDefault = nullptr) static
Triple MachOObjectFile::getArch (uint32_t CPUType, uint32_t CPUSubType, const char ** McpuDefault, Triple * ThumbTriple) static
Definition at line 1394 of file MachOObjectFile.cpp.
References getArch(), getThumbArch(), and T.
uint8_t MachOObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 1223 of file MachOObjectFile.cpp.
References is64Bit().
MachO::linkedit_data_command MachOObjectFile::getDataInCodeLoadCommand () const
Definition at line 2445 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::cmd, and llvm::MachO::LC_DATA_IN_CODE.
Referenced by begin_dices(), and end_dices().
MachO::data_in_code_entry MachOObjectFile::getDataInCodeTableEntry (uint32_t DataOffset, unsigned Index) const
Definition at line 2394 of file MachOObjectFile.cpp.
References getPtr().
MachO::data_in_code_entry MachOObjectFile::getDice (DataRefImpl Rel) const
Definition at line 2373 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by llvm::object::DiceRef::getKind(), llvm::object::DiceRef::getLength(), and llvm::object::DiceRef::getOffset().
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoBindOpcodes () const
Definition at line 2469 of file MachOObjectFile.cpp.
References getPtr().
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoExportsTrie () const
Definition at line 2502 of file MachOObjectFile.cpp.
References getPtr().
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoLazyBindOpcodes () const
Definition at line 2491 of file MachOObjectFile.cpp.
References getPtr().
Referenced by lazyBindTable().
MachO::dyld_info_command MachOObjectFile::getDyldInfoLoadCommand (const LoadCommandInfo & L) const
Definition at line 2279 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoRebaseOpcodes () const
Definition at line 2458 of file MachOObjectFile.cpp.
References getPtr().
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoWeakBindOpcodes () const
Definition at line 2480 of file MachOObjectFile.cpp.
References getPtr().
Referenced by weakBindTable().
MachO::dylib_command MachOObjectFile::getDylibIDLoadCommand (const LoadCommandInfo & L) const
Definition at line 2274 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::dylinker_command MachOObjectFile::getDylinkerCommand (const LoadCommandInfo & L) const
Definition at line 2284 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::dysymtab_command MachOObjectFile::getDysymtabLoadCommand () const
Definition at line 2415 of file MachOObjectFile.cpp.
References llvm::MachO::dysymtab_command::cmd, and llvm::MachO::LC_DYSYMTAB.
Referenced by llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection().
MachO::encryption_info_command MachOObjectFile::getEncryptionInfoCommand (const LoadCommandInfo & L) const
Definition at line 2309 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::encryption_info_command_64 MachOObjectFile::getEncryptionInfoCommand64 (const LoadCommandInfo & L) const
Definition at line 2314 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::entry_point_command MachOObjectFile::getEntryPointCommand (const LoadCommandInfo & L) const
Definition at line 2304 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
StringRef MachOObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1227 of file MachOObjectFile.cpp.
References llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, llvm::MachO::CPU_TYPE_X86_64, getCPUType(), and is64Bit().
MachOObjectFile::LoadCommandInfo MachOObjectFile::getFirstLoadCommandInfo () const
Definition at line 2198 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, getPtr(), is64Bit(), llvm::SPII::Load, and llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by MachOObjectFile().
MachO::mach_header MachOObjectFile::getHeader () const
Definition at line 2378 of file MachOObjectFile.cpp.
References getPtr().
Referenced by getCPUType(), getRelocationOffset(), isRelocatableObject(), and MachOObjectFile().
MachO::mach_header_64 MachOObjectFile::getHeader64 () const
Definition at line 2382 of file MachOObjectFile.cpp.
References getPtr().
Triple MachOObjectFile::getHostArch () static
Definition at line 1403 of file MachOObjectFile.cpp.
References llvm::sys::getDefaultTargetTriple().
std::error_code MachOObjectFile::getIndirectName (DataRefImpl Symb, StringRef & Res) const
Definition at line 330 of file MachOObjectFile.cpp.
References llvm::StringRef::data(), getStringTableData(), getSymbol64TableEntry(), getSymbolTableEntry(), is64Bit(), llvm::MachO::N_INDR, llvm::MachO::N_TYPE, llvm::MachO::nlist::n_type, llvm::MachO::nlist_64::n_type, llvm::MachO::nlist::n_value, llvm::MachO::nlist_64::n_value, llvm::object::parse_failed, llvm::StringRef::size(), and llvm::object::success.
uint32_t MachOObjectFile::getIndirectSymbolTableEntry (const MachO::dysymtab_command & DLC, unsigned Index) const
Definition at line 2386 of file MachOObjectFile.cpp.
References getPtr(), and llvm::MachO::dysymtab_command::indirectsymoff.
Referenced by llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection().
std::error_code MachOObjectFile::getLibraryShortNameByIndex (unsigned Index, StringRef & Res) const
Definition at line 1148 of file MachOObjectFile.cpp.
References llvm::MachO::dylib_command::cmdsize, llvm::MachO::dylib_command::dylib, llvm::StringRef::empty(), guessLibraryShortName(), llvm::MachO::dylib::name, Name, P, llvm::object::parse_failed, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::StringRef::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::object::success.
MachO::linkedit_data_command MachOObjectFile::getLinkeditDataLoadCommand (const LoadCommandInfo & L) const
Definition at line 2249 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::linker_option_command MachOObjectFile::getLinkerOptionLoadCommand (const LoadCommandInfo & L) const
Definition at line 2264 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachOObjectFile::LoadCommandInfo MachOObjectFile::getNextLoadCommandInfo (const LoadCommandInfo & L) const
Definition at line 2209 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, llvm::MachO::load_command::cmdsize, and llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by MachOObjectFile().
bool MachOObjectFile::getPlainRelocationExternal (const MachO::any_relocation_info & RE) const
Definition at line 2135 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by getRelocationSection(), getRelocationSymbol(), llvm::RuntimeDyldMachO::getRelocationValueRef(), printRelocationTargetName(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
unsigned MachOObjectFile::getPlainRelocationSymbolNum (const MachO::any_relocation_info & RE) const
Definition at line 2128 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by getRelocationSection(), getRelocationSymbol(), printRelocationTargetName(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
MachO::any_relocation_info MachOObjectFile::getRelocation (DataRefImpl Rel) const
Definition at line 2354 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, getPtr(), getSection(), getSection64(), is64Bit(), P, llvm::MachO::section::reloff, and llvm::MachO::section_64::reloff.
Referenced by llvm::RuntimeDyldMachO::getRelocationEntry(), getRelocationOffset(), getRelocationSymbol(), getRelocationType(), llvm::RuntimeDyldMachO::getRelocationValueRef(), getRelocationValueString(), llvm::RuntimeDyldMachO::makeValueAddendPCRel(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
std::error_code MachOObjectFile::getRelocationAddress (DataRefImpl Rel, uint64_t & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 636 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, getRelocationOffset(), getSectionAddress(), and llvm::object::success.
std::error_code MachOObjectFile::getRelocationHidden (DataRefImpl Rel, bool & Result) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 973 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::Triple::arm, llvm::object::DataRefImpl::d, llvm::MachO::GENERIC_RELOC_PAIR, getArch(), getRelocationType(), llvm::Triple::ppc, llvm::object::success, Type, llvm::Triple::x86, llvm::Triple::x86_64, llvm::MachO::X86_64_RELOC_SUBTRACTOR, and llvm::MachO::X86_64_RELOC_UNSIGNED.
std::error_code MachOObjectFile::getRelocationOffset (DataRefImpl Rel, uint64_t & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 648 of file MachOObjectFile.cpp.
References assert(), getAnyRelocationAddress(), getHeader(), getRelocation(), llvm::MachO::MH_OBJECT, and llvm::object::success.
Referenced by getRelocationAddress().
SectionRef MachOObjectFile::getRelocationSection (const MachO::any_relocation_info & RE) const
Definition at line 2187 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, getPlainRelocationExternal(), getPlainRelocationSymbolNum(), isRelocationScattered(), section_end(), and llvm::object::ObjectFile::SectionRef.
Referenced by llvm::RuntimeDyldMachO::getRelocationValueRef().
symbol_iterator MachOObjectFile::getRelocationSymbol (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 658 of file MachOObjectFile.cpp.
References getPlainRelocationExternal(), getPlainRelocationSymbolNum(), getPtr(), getRelocation(), getSymtabLoadCommand(), is64Bit(), isRelocationScattered(), llvm::object::DataRefImpl::p, llvm::object::SymbolicFile::symbol_end(), llvm::object::ObjectFile::SymbolRef, and llvm::MachO::symtab_command::symoff.
std::error_code MachOObjectFile::getRelocationType (DataRefImpl Rel, uint64_t & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 678 of file MachOObjectFile.cpp.
References getAnyRelocationType(), getRelocation(), and llvm::object::success.
Referenced by getRelocationHidden(), and getRelocationTypeName().
std::error_code MachOObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 686 of file MachOObjectFile.cpp.
References llvm::Triple::aarch64, llvm::SmallVectorImpl< T >::append(), llvm::Triple::arm, llvm::array_lengthof(), llvm::StringRef::begin(), llvm::StringRef::end(), getArch(), getRelocationType(), llvm::Triple::ppc, llvm::object::success, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
std::error_code MachOObjectFile::getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 798 of file MachOObjectFile.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::Triple::arm, llvm::MachO::ARM_RELOC_HALF, llvm::MachO::ARM_RELOC_HALF_SECTDIFF, llvm::MachO::ARM_RELOC_PAIR, llvm::raw_ostream::flush(), llvm::MachO::GENERIC_RELOC_LOCAL_SECTDIFF, llvm::MachO::GENERIC_RELOC_PAIR, llvm::MachO::GENERIC_RELOC_SECTDIFF, llvm::MachO::GENERIC_RELOC_TLV, getAnyRelocationLength(), getAnyRelocationPCRel(), getAnyRelocationType(), getArch(), getRelocation(), moveRelocationNext(), llvm::Triple::ppc, printRelocationTargetName(), llvm::report_fatal_error(), llvm::object::success, llvm::Triple::x86, llvm::Triple::x86_64, llvm::MachO::X86_64_RELOC_GOT, llvm::MachO::X86_64_RELOC_GOT_LOAD, llvm::MachO::X86_64_RELOC_SIGNED_1, llvm::MachO::X86_64_RELOC_SIGNED_2, llvm::MachO::X86_64_RELOC_SIGNED_4, llvm::MachO::X86_64_RELOC_SUBTRACTOR, llvm::MachO::X86_64_RELOC_TLV, and llvm::MachO::X86_64_RELOC_UNSIGNED.
MachO::routines_command MachOObjectFile::getRoutinesCommand (const LoadCommandInfo & L) const
Definition at line 2339 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::routines_command_64 MachOObjectFile::getRoutinesCommand64 (const LoadCommandInfo & L) const
Definition at line 2344 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::rpath_command MachOObjectFile::getRpathCommand (const LoadCommandInfo & L) const
Definition at line 2294 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
bool MachOObjectFile::getScatteredRelocationScattered (const MachO::any_relocation_info & RE) const
Definition at line 2142 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
uint32_t MachOObjectFile::getScatteredRelocationType (const MachO::any_relocation_info & RE) const
Definition at line 2152 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by getAnyRelocationType().
uint32_t MachOObjectFile::getScatteredRelocationValue (const MachO::any_relocation_info & RE) const
Definition at line 2147 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
MachO::section llvm::object::MachOObjectFile::getSection (DataRefImpl DRI) const
Referenced by getRelocation(), getSectionAddress(), getSectionAlignment(), getSectionContents(), getSectionFlags(), getSectionSize(), and llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection().
MachO::section llvm::object::MachOObjectFile::getSection (const LoadCommandInfo & L, unsigned Index) const
MachO::section_64 llvm::object::MachOObjectFile::getSection64 (DataRefImpl DRI) const
Referenced by getRelocation(), getSectionAddress(), getSectionAlignment(), getSectionContents(), getSectionFlags(), and getSectionSize().
MachO::section_64 llvm::object::MachOObjectFile::getSection64 (const LoadCommandInfo & L, unsigned Index) const
uint64_t MachOObjectFile::getSectionAddress (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 522 of file MachOObjectFile.cpp.
References llvm::MachO::section::addr, llvm::MachO::section_64::addr, getSection(), getSection64(), and is64Bit().
Referenced by getRelocationAddress(), getSymbolSize(), and sectionContainsSymbol().
uint64_t MachOObjectFile::getSectionAlignment (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 553 of file MachOObjectFile.cpp.
References Align(), llvm::MachO::section::align, llvm::MachO::section_64::align, getSection(), getSection64(), and is64Bit().
std::error_code MachOObjectFile::getSectionContents (DataRefImpl Sec, StringRef & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 534 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), getSection(), getSection64(), is64Bit(), llvm::MachO::section::offset, llvm::MachO::section_64::offset, llvm::MachO::section::size, llvm::MachO::section_64::size, llvm::StringRef::substr(), and llvm::object::success.
StringRef MachOObjectFile::getSectionFinalSegmentName (DataRefImpl Sec) const
Definition at line 2101 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::data(), getSectionRawFinalSegmentName(), and parseSegmentOrSectionName().
std::error_code MachOObjectFile::getSectionName (DataRefImpl Sec, StringRef & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 515 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::data(), getSectionRawName(), parseSegmentOrSectionName(), and llvm::object::success.
ArrayRef< char > MachOObjectFile::getSectionRawFinalSegmentName (DataRefImpl Sec) const
Definition at line 2114 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and llvm::makeArrayRef().
Referenced by getSectionFinalSegmentName().
ArrayRef< char > MachOObjectFile::getSectionRawName (DataRefImpl Sec) const
Definition at line 2107 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and llvm::makeArrayRef().
Referenced by getSectionName().
uint64_t MachOObjectFile::getSectionSize (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 528 of file MachOObjectFile.cpp.
References getSection(), getSection64(), is64Bit(), llvm::MachO::section::size, and llvm::MachO::section_64::size.
Referenced by getSymbolSize(), and sectionContainsSymbol().
unsigned MachOObjectFile::getSectionType (SectionRef Sec) const
Definition at line 322 of file MachOObjectFile.cpp.
References llvm::object::SectionRef::getRawDataRefImpl(), getSectionFlags(), and llvm::MachO::SECTION_TYPE.
MachO::segment_command_64 MachOObjectFile::getSegment64LoadCommand (const LoadCommandInfo & L) const
Definition at line 2259 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by getSegmentLoadCommandNumSections(), and isPageZeroSegment().
MachO::segment_command MachOObjectFile::getSegmentLoadCommand (const LoadCommandInfo & L) const
Definition at line 2254 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by getSegmentLoadCommandNumSections(), and isPageZeroSegment().
MachO::source_version_command MachOObjectFile::getSourceVersionCommand (const LoadCommandInfo & L) const
Definition at line 2299 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
StringRef MachOObjectFile::getStringTableData () const
Definition at line 2521 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), getSymtabLoadCommand(), llvm::MachO::symtab_command::stroff, llvm::MachO::symtab_command::strsize, and llvm::StringRef::substr().
Referenced by getIndirectName(), and getSymbolName().
MachO::sub_client_command MachOObjectFile::getSubClientCommand (const LoadCommandInfo & L) const
Definition at line 2334 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::sub_framework_command MachOObjectFile::getSubFrameworkCommand (const LoadCommandInfo & L) const
Definition at line 2319 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::sub_library_command MachOObjectFile::getSubLibraryCommand (const LoadCommandInfo & L) const
Definition at line 2329 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::sub_umbrella_command MachOObjectFile::getSubUmbrellaCommand (const LoadCommandInfo & L) const
Definition at line 2324 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::nlist_64 MachOObjectFile::getSymbol64TableEntry (DataRefImpl DRI) const
Definition at line 2243 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by getIndirectName(), and getSymbolAddress().
std::error_code MachOObjectFile::getSymbolAddress (DataRefImpl Symb, uint64_t & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 352 of file MachOObjectFile.cpp.
References getSymbol64TableEntry(), getSymbolTableEntry(), is64Bit(), llvm::MachO::N_TYPE, llvm::MachO::nlist::n_type, llvm::MachO::nlist_64::n_type, llvm::MachO::N_UNDF, llvm::MachO::nlist::n_value, llvm::MachO::nlist_64::n_value, llvm::object::success, and llvm::object::UnknownAddressOrSize.
Referenced by getSymbolFlags(), getSymbolSize(), and sectionContainsSymbol().
std::error_code MachOObjectFile::getSymbolAlignment (DataRefImpl Symb, uint32_t & Res) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 372 of file MachOObjectFile.cpp.
References llvm::MachO::GET_COMM_ALIGN(), getSymbolFlags(), getSymbolTableEntryBase(), llvm::MachO::nlist_base::n_desc, llvm::object::BasicSymbolRef::SF_Common, and llvm::object::success.
basic_symbol_iterator MachOObjectFile::getSymbolByIndex (unsigned Index) const
Definition at line 1198 of file MachOObjectFile.cpp.
References assert(), getPtr(), getSymtabLoadCommand(), is64Bit(), llvm::MachO::symtab_command::nsyms, llvm::object::DataRefImpl::p, llvm::object::ObjectFile::SymbolRef, and llvm::MachO::symtab_command::symoff.
Referenced by llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), and symbol_begin_impl().
uint32_t MachOObjectFile::getSymbolFlags (DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 456 of file MachOObjectFile.cpp.
References getSymbolAddress(), getSymbolTableEntryBase(), llvm::MachO::N_ABS, llvm::MachO::N_ARM_THUMB_DEF, llvm::MachO::nlist_base::n_desc, llvm::MachO::N_EXT, llvm::MachO::N_INDR, llvm::MachO::N_STAB, llvm::MachO::N_TYPE, llvm::MachO::nlist_base::n_type, llvm::MachO::N_UNDF, llvm::MachO::N_WEAK_DEF, llvm::MachO::N_WEAK_REF, llvm::object::BasicSymbolRef::SF_Absolute, llvm::object::BasicSymbolRef::SF_Common, llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Indirect, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Thumb, llvm::object::BasicSymbolRef::SF_Undefined, llvm::object::BasicSymbolRef::SF_Weak, and llvm::object::UnknownAddressOrSize.
Referenced by getSymbolAlignment(), and getSymbolSize().
std::error_code MachOObjectFile::getSymbolName (DataRefImpl Symb, StringRef & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 313 of file MachOObjectFile.cpp.
References llvm::StringRef::data(), getStringTableData(), getSymbolTableEntryBase(), llvm::MachO::nlist_base::n_strx, and llvm::object::success.
std::error_code MachOObjectFile::getSymbolSection (DataRefImpl Symb, section_iterator & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 495 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, getSymbolTableEntryBase(), llvm::MachO::nlist_base::n_sect, section_end(), llvm::object::ObjectFile::SectionRef, and llvm::object::success.
std::error_code MachOObjectFile::getSymbolSize (DataRefImpl Symb, uint64_t & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 384 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, getSectionAddress(), getSectionSize(), getSymbolAddress(), getSymbolFlags(), getSymbolTableEntryBase(), llvm::MachO::nlist_base::n_sect, llvm::object::BasicSymbolRef::SF_Common, llvm::object::success, llvm::ARMBuildAttrs::Symbol, llvm::object::ObjectFile::symbols(), and llvm::object::UnknownAddressOrSize.
MachO::nlist MachOObjectFile::getSymbolTableEntry (DataRefImpl DRI) const
Definition at line 2237 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by getIndirectName(), and getSymbolAddress().
std::error_code MachOObjectFile::getSymbolType (DataRefImpl Symb, SymbolRef::Type & Res) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 432 of file MachOObjectFile.cpp.
References getSymbolTableEntryBase(), llvm::MachO::N_SECT, llvm::MachO::N_STAB, llvm::MachO::N_TYPE, llvm::MachO::nlist_base::n_type, llvm::MachO::N_UNDF, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::object::SymbolRef::ST_Unknown, and llvm::object::success.
Referenced by sectionContainsSymbol().
MachO::symtab_command MachOObjectFile::getSymtabLoadCommand () const
Definition at line 2400 of file MachOObjectFile.cpp.
References llvm::MachO::symtab_command::cmd, and llvm::MachO::LC_SYMTAB.
Referenced by getRelocationSymbol(), getStringTableData(), getSymbolByIndex(), and symbol_end_impl().
MachO::thread_command MachOObjectFile::getThreadCommand (const LoadCommandInfo & L) const
Definition at line 2349 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Triple MachOObjectFile::getThumbArch (uint32_t CPUType, uint32_t CPUSubType, const char ** McpuDefault = nullptr) static
Definition at line 1352 of file MachOObjectFile.cpp.
References llvm::MachO::CPU_SUBTYPE_ARM_V4T, llvm::MachO::CPU_SUBTYPE_ARM_V5TEJ, llvm::MachO::CPU_SUBTYPE_ARM_V6, llvm::MachO::CPU_SUBTYPE_ARM_V6M, llvm::MachO::CPU_SUBTYPE_ARM_V7, llvm::MachO::CPU_SUBTYPE_ARM_V7EM, llvm::MachO::CPU_SUBTYPE_ARM_V7K, llvm::MachO::CPU_SUBTYPE_ARM_V7M, llvm::MachO::CPU_SUBTYPE_ARM_V7S, llvm::MachO::CPU_SUBTYPE_ARM_XSCALE, llvm::MachO::CPU_SUBTYPE_MASK, and llvm::MachO::CPU_TYPE_ARM.
Referenced by getArch().
ArrayRef< uint8_t > MachOObjectFile::getUuid () const
Definition at line 2513 of file MachOObjectFile.cpp.
MachO::uuid_command MachOObjectFile::getUuidCommand (const LoadCommandInfo & L) const
Definition at line 2289 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::version_min_command MachOObjectFile::getVersionMinLoadCommand (const LoadCommandInfo & L) const
Definition at line 2269 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
StringRef MachOObjectFile::guessLibraryShortName (StringRef Name, bool & isFramework, StringRef & Suffix) static
Definition at line 1029 of file MachOObjectFile.cpp.
References F(), llvm::StringRef::find(), llvm::StringRef::npos, llvm::StringRef::rfind(), llvm::StringRef::size(), llvm::StringRef::slice(), and llvm::StringRef::startswith().
Referenced by getLibraryShortNameByIndex().
bool llvm::object::MachOObjectFile::hasPageZeroSegment () const inline
Definition at line 424 of file Object/MachO.h.
bool MachOObjectFile::is64Bit () const
Definition at line 2526 of file MachOObjectFile.cpp.
References llvm::object::Binary::getMachOType(), and llvm::object::Binary::getType().
Referenced by getBytesInAddress(), getFileFormatName(), getFirstLoadCommandInfo(), getIndirectName(), getRelocation(), getRelocationSymbol(), getSectionAddress(), getSectionAlignment(), getSectionContents(), getSectionFlags(), getSectionPtr(), getSectionSize(), getSegmentLoadCommandNumSections(), getSymbolAddress(), getSymbolByIndex(), isPageZeroSegment(), lazyBindTable(), MachOObjectFile(), moveSymbolNext(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), symbol_end_impl(), and weakBindTable().
bool MachOObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 2543 of file MachOObjectFile.cpp.
References llvm::MachO::mach_header::filetype, getHeader(), and llvm::MachO::MH_OBJECT.
bool MachOObjectFile::isRelocationScattered (const MachO::any_relocation_info & RE) const
Definition at line 2121 of file MachOObjectFile.cpp.
References llvm::MachO::CPU_TYPE_X86_64, getCPUType(), getPlainRelocationAddress(), and llvm::MachO::R_SCATTERED.
Referenced by getAnyRelocationAddress(), getAnyRelocationLength(), getAnyRelocationPCRel(), getAnyRelocationType(), getRelocationSection(), getRelocationSymbol(), printRelocationTargetName(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
bool MachOObjectFile::isSectionBSS (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 579 of file MachOObjectFile.cpp.
References getSectionFlags(), llvm::MachO::S_ATTR_PURE_INSTRUCTIONS, llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_ZEROFILL, and llvm::MachO::SECTION_TYPE.
bool MachOObjectFile::isSectionData (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 571 of file MachOObjectFile.cpp.
References getSectionFlags(), llvm::MachO::S_ATTR_PURE_INSTRUCTIONS, llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_ZEROFILL, and llvm::MachO::SECTION_TYPE.
bool MachOObjectFile::isSectionText (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 566 of file MachOObjectFile.cpp.
References getSectionFlags(), and llvm::MachO::S_ATTR_PURE_INSTRUCTIONS.
bool MachOObjectFile::isSectionVirtual (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 587 of file MachOObjectFile.cpp.
bool MachOObjectFile::isValidArch (StringRef ArchFlag) static
Definition at line 1407 of file MachOObjectFile.cpp.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
iterator_range< bind_iterator > MachOObjectFile::lazyBindTable () const
For use iterating over all lazy bind table entries.
Definition at line 2090 of file MachOObjectFile.cpp.
References bindTable(), getDyldInfoLazyBindOpcodes(), is64Bit(), and llvm::object::MachOBindEntry::Lazy.
void MachOObjectFile::moveRelocationNext (DataRefImpl & Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 632 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::b, and llvm::object::DataRefImpl::d.
Referenced by getRelocationValueString().
void MachOObjectFile::moveSectionNext (DataRefImpl & Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 511 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
void MachOObjectFile::moveSymbolNext (DataRefImpl & Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 306 of file MachOObjectFile.cpp.
References is64Bit(), and llvm::object::DataRefImpl::p.
void MachOObjectFile::ReadULEB128s (uint64_t Index, SmallVectorImpl< uint64_t > & Out) const
Definition at line 2531 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), llvm::DataExtractor::getULEB128(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
iterator_range<rebase_iterator> llvm::object::MachOObjectFile::rebaseTable () const
For use iterating over all rebase table entries.
iterator_range< rebase_iterator > MachOObjectFile::rebaseTable (ArrayRef< uint8_t > Opcodes, bool is64) static
For use examining rebase opcodes not in a MachOObjectFile.
Definition at line 1819 of file MachOObjectFile.cpp.
section_iterator MachOObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1212 of file MachOObjectFile.cpp.
References llvm::object::ObjectFile::SectionRef.
Referenced by llvm::RuntimeDyldMachO::getSectionByAddress(), and printRelocationTargetName().
section_iterator MachOObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1217 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, llvm::object::ObjectFile::SectionRef, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by getRelocationSection(), llvm::RuntimeDyldMachO::getSectionByAddress(), and getSymbolSection().
relocation_iterator llvm::object::MachOObjectFile::section_rel_begin (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
relocation_iterator llvm::object::MachOObjectFile::section_rel_begin (unsigned Index) const
relocation_iterator llvm::object::MachOObjectFile::section_rel_end (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
relocation_iterator llvm::object::MachOObjectFile::section_rel_end (unsigned Index) const
bool MachOObjectFile::sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 592 of file MachOObjectFile.cpp.
References getSectionAddress(), getSectionSize(), getSymbolAddress(), getSymbolType(), llvm::AArch64DB::ST, and llvm::object::SymbolRef::ST_Unknown.
basic_symbol_iterator MachOObjectFile::symbol_begin_impl () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1179 of file MachOObjectFile.cpp.
References getSymbolByIndex().
basic_symbol_iterator MachOObjectFile::symbol_end_impl () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1183 of file MachOObjectFile.cpp.
References getPtr(), getSymtabLoadCommand(), is64Bit(), llvm::MachO::symtab_command::nsyms, llvm::object::DataRefImpl::p, llvm::object::ObjectFile::SymbolRef, and llvm::MachO::symtab_command::symoff.
iterator_range< bind_iterator > MachOObjectFile::weakBindTable () const
For use iterating over all lazy bind table entries.
Definition at line 2095 of file MachOObjectFile.cpp.
References bindTable(), getDyldInfoWeakBindOpcodes(), is64Bit(), and llvm::object::MachOBindEntry::Weak.
The documentation for this class was generated from the following files:
Object/MachO.h
MachOObjectFile.cpp