LLVM: llvm::MCAssembler Class Reference
LLVM API Documentation
llvm::MCAssembler Class Reference
#include <MCAssembler.h>
Classes
struct VersionMinInfoType
MachO specific deployment target version info.
Public Types
typedef iplist< MCSectionData > SectionDataListType
typedef iplist< MCSymbolData > SymbolDataListType
typedef
SectionDataListType::const_iterator const_iterator
typedef
SectionDataListType::iterator iterator
typedef
SymbolDataListType::const_iterator const_symbol_iterator
typedef
SymbolDataListType::iterator symbol_iterator
typedef iterator_range
< symbol_iterator > symbol_range
typedef iterator_range
< const_symbol_iterator > const_symbol_range
typedef std::vector< std::string > FileNameVectorType
typedef
FileNameVectorType::const_iterator const_file_name_iterator
typedef std::vector
< IndirectSymbolData >
::const_iterator const_indirect_symbol_iterator
typedef std::vector
< IndirectSymbolData >
::iterator indirect_symbol_iterator
typedef std::vector
< DataRegionData >
::const_iterator const_data_region_iterator
typedef std::vector
< DataRegionData >::iterator data_region_iterator
Public Member Functions
uint64_t computeFragmentSize (const MCAsmLayout &Layout, const MCFragment &F) const
const MCSymbolData * getAtom (const MCSymbolData *Symbol) const
bool isSymbolLinkerVisible (const MCSymbol &SD) const
void writeSectionData (const MCSectionData *Section, const MCAsmLayout &Layout) const
Emit the section contents using the given object writer.
bool isThumbFunc (const MCSymbol *Func) const
Check whether a given symbol has been flagged with .thumb_func.
void setIsThumbFunc (const MCSymbol *Func)
Flag a function symbol as the target of a .thumb_func directive.
unsigned getELFHeaderEFlags () const
ELF e_header flags.
void setELFHeaderEFlags (unsigned Flags)
const VersionMinInfoType & getVersionMinInfo () const
MachO deployment target version information.
void setVersionMinInfo (MCVersionMinType Kind, unsigned Major, unsigned Minor, unsigned Update)
MCAssembler (MCContext &Context_, MCAsmBackend &Backend_, MCCodeEmitter &Emitter_, MCObjectWriter &Writer_, raw_ostream &OS)
~MCAssembler ()
void reset ()
MCContext & getContext () const
MCAsmBackend & getBackend () const
MCCodeEmitter & getEmitter () const
MCObjectWriter & getWriter () const
void Finish ()
bool getSubsectionsViaSymbols () const
void setSubsectionsViaSymbols (bool Value)
bool getRelaxAll () const
void setRelaxAll (bool Value)
bool isBundlingEnabled () const
unsigned getBundleAlignSize () const
void setBundleAlignSize (unsigned Size)
void dump ()
Section List Access
const SectionDataListType & getSectionList () const
SectionDataListType & getSectionList ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_t size () const
Symbol List Access
const SymbolDataListType & getSymbolList () const
SymbolDataListType & getSymbolList ()
symbol_iterator symbol_begin ()
const_symbol_iterator symbol_begin () const
symbol_iterator symbol_end ()
const_symbol_iterator symbol_end () const
symbol_range symbols ()
const_symbol_range symbols () const
size_t symbol_size () const
Indirect Symbol List Access
std::vector< IndirectSymbolData > & getIndirectSymbols ()
indirect_symbol_iterator indirect_symbol_begin ()
const_indirect_symbol_iterator indirect_symbol_begin () const
indirect_symbol_iterator indirect_symbol_end ()
const_indirect_symbol_iterator indirect_symbol_end () const
size_t indirect_symbol_size () const
Linker Option List Access
std::vector< std::vector
< std::string > > & getLinkerOptions ()
Data Region List Access
std::vector< DataRegionData > & getDataRegions ()
data_region_iterator data_region_begin ()
const_data_region_iterator data_region_begin () const
data_region_iterator data_region_end ()
const_data_region_iterator data_region_end () const
size_t data_region_size () const
MCLOHContainer & getLOHContainer ()
const MCLOHContainer & getLOHContainer () const
Backend Data Access
MCSectionData & getSectionData (const MCSection &Section) const
MCSectionData & getOrCreateSectionData (const MCSection &Section, bool *Created=nullptr)
bool hasSymbolData (const MCSymbol &Symbol) const
MCSymbolData & getSymbolData (const MCSymbol &Symbol)
const MCSymbolData & getSymbolData (const MCSymbol &Symbol) const
MCSymbolData & getOrCreateSymbolData (const MCSymbol &Symbol, bool *Created=nullptr)
const_file_name_iterator file_names_begin () const
const_file_name_iterator file_names_end () const
void addFileName (StringRef FileName)
Friends
class MCAsmLayout
Detailed Description
Definition at line 830 of file MCAssembler.h.
Member Typedef Documentation
typedef std::vector<DataRegionData>::const_iterator llvm::MCAssembler::const_data_region_iterator
Definition at line 854 of file MCAssembler.h.
typedef FileNameVectorType::const_iterator llvm::MCAssembler::const_file_name_iterator
Definition at line 847 of file MCAssembler.h.
typedef std::vector<IndirectSymbolData>::const_iterator llvm::MCAssembler::const_indirect_symbol_iterator
Definition at line 850 of file MCAssembler.h.
typedef SectionDataListType::const_iterator llvm::MCAssembler::const_iterator
Definition at line 837 of file MCAssembler.h.
typedef SymbolDataListType::const_iterator llvm::MCAssembler::const_symbol_iterator
Definition at line 840 of file MCAssembler.h.
typedef iterator_range<const_symbol_iterator> llvm::MCAssembler::const_symbol_range
Definition at line 844 of file MCAssembler.h.
typedef std::vector<DataRegionData>::iterator llvm::MCAssembler::data_region_iterator
Definition at line 855 of file MCAssembler.h.
typedef std::vector<std::string> llvm::MCAssembler::FileNameVectorType
Definition at line 846 of file MCAssembler.h.
typedef std::vector<IndirectSymbolData>::iterator llvm::MCAssembler::indirect_symbol_iterator
Definition at line 851 of file MCAssembler.h.
typedef SectionDataListType::iterator llvm::MCAssembler::iterator
Definition at line 838 of file MCAssembler.h.
typedef iplist<MCSectionData> llvm::MCAssembler::SectionDataListType
Definition at line 834 of file MCAssembler.h.
typedef SymbolDataListType::iterator llvm::MCAssembler::symbol_iterator
Definition at line 841 of file MCAssembler.h.
typedef iterator_range<symbol_iterator> llvm::MCAssembler::symbol_range
Definition at line 843 of file MCAssembler.h.
typedef iplist<MCSymbolData> llvm::MCAssembler::SymbolDataListType
Definition at line 835 of file MCAssembler.h.
Constructor & Destructor Documentation
MCAssembler::MCAssembler (MCContext & Context_, MCAsmBackend & Backend_, MCCodeEmitter & Emitter_, MCObjectWriter & Writer_, raw_ostream & OS)
Construct a new assembler instance.
Parameters
OS The stream to output to.
Definition at line 367 of file MCAssembler.cpp.
References llvm::MCAssembler::VersionMinInfoType::Major.
MCAssembler::~MCAssembler ()
Definition at line 376 of file MCAssembler.cpp.
Member Function Documentation
void llvm::MCAssembler::addFileName (StringRef FileName) inline
Definition at line 1240 of file MCAssembler.h.
References file_names_begin(), and file_names_end().
Referenced by llvm::MCWinCOFFStreamer::EmitFileDirective(), and llvm::MCELFStreamer::EmitFileDirective().
iterator llvm::MCAssembler::begin () inline
Definition at line 1084 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::ComputeSymbolTable(), dump(), Finish(), llvm::MCAsmLayout::MCAsmLayout(), and llvm::MachObjectWriter::WriteObject().
const_iterator llvm::MCAssembler::begin () const inline
Definition at line 1085 of file MCAssembler.h.
uint64_t MCAssembler::computeFragmentSize (const MCAsmLayout & Layout, const MCFragment & F) const
Compute the effective fragment size assuming it is laid out at the given SectionAddress and FragmentOffset.
Definition at line 546 of file MCAssembler.cpp.
References F(), llvm::MCFragment::FT_Align, llvm::MCFragment::FT_CompactEncodedInst, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Dwarf, llvm::MCFragment::FT_DwarfFrame, llvm::MCFragment::FT_Fill, llvm::MCFragment::FT_LEB, llvm::MCFragment::FT_Org, llvm::MCFragment::FT_Relaxable, llvm::MCAlignFragment::getAlignment(), getBackend(), llvm::MCAsmLayout::getFragmentOffset(), llvm::MCFragment::getKind(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCAsmBackend::getMinimumNopSize(), llvm::MCOrgFragment::getOffset(), llvm::MCAlignFragment::hasEmitNops(), llvm_unreachable, llvm::OffsetToAlignment(), and llvm::report_fatal_error().
Referenced by llvm::MCAsmLayout::getSectionAddressSize(), llvm::MCAsmLayout::layoutFragment(), and writeFragment().
data_region_iterator llvm::MCAssembler::data_region_begin () inline
Definition at line 1156 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteObject().
const_data_region_iterator llvm::MCAssembler::data_region_begin () const inline
Definition at line 1159 of file MCAssembler.h.
data_region_iterator llvm::MCAssembler::data_region_end () inline
Definition at line 1163 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteObject().
const_data_region_iterator llvm::MCAssembler::data_region_end () const inline
Definition at line 1166 of file MCAssembler.h.
size_t llvm::MCAssembler::data_region_size () const inline
Definition at line 1170 of file MCAssembler.h.
void MCAssembler::dump ()
Definition at line 1279 of file MCAssembler.cpp.
References begin(), end(), llvm::errs(), symbol_begin(), and symbol_end().
Referenced by Finish().
iterator llvm::MCAssembler::end () inline
Definition at line 1087 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::ComputeSymbolTable(), dump(), Finish(), llvm::MCAsmLayout::MCAsmLayout(), and llvm::MachObjectWriter::WriteObject().
const_iterator llvm::MCAssembler::end () const inline
Definition at line 1088 of file MCAssembler.h.
const_file_name_iterator llvm::MCAssembler::file_names_begin () const inline
Definition at line 1232 of file MCAssembler.h.
Referenced by addFileName().
const_file_name_iterator llvm::MCAssembler::file_names_end () const inline
Definition at line 1236 of file MCAssembler.h.
Referenced by addFileName().
void MCAssembler::Finish ()
Finish - Do final processing and write the object to the output stream. Writer is used for custom object writer (as the MCJIT does), if not specified it is automatically created from backend.
Definition at line 881 of file MCAssembler.cpp.
References llvm::MCAsmBackend::applyFixup(), llvm::MCSectionData::begin(), begin(), llvm::SmallVectorTemplateCommon< T, typename >::data(), DEBUG_WITH_TYPE, dump(), llvm::dyn_cast(), llvm::MCSectionData::end(), end(), llvm::errs(), llvm::MCObjectWriter::ExecutePostLayoutBinding(), llvm::MCEncodedFragmentWithFixups::fixup_begin(), llvm::MCEncodedFragmentWithFixups::fixup_end(), getBackend(), llvm::MCEncodedFragment::getContents(), getWriter(), llvm::MCSectionData::setLayoutOrder(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::raw_ostream::tell(), and llvm::MCObjectWriter::WriteObject().
Referenced by llvm::MCObjectStreamer::FinishImpl().
const MCSymbolData * MCAssembler::getAtom (const MCSymbolData * Symbol) const
Find the symbol which defines the atom containing the given symbol, or null if there is no such symbol.
Definition at line 441 of file MCAssembler.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCFragment::getAtom(), getContext(), llvm::MCSymbolData::getFragment(), llvm::MCFragment::getParent(), llvm::MCSectionData::getSection(), llvm::MCSymbolData::getSymbol(), llvm::MCAsmInfo::isSectionAtomizableBySymbols(), and isSymbolLinkerVisible().
MCAsmBackend& llvm::MCAssembler::getBackend () const inline
Definition at line 1042 of file MCAssembler.h.
Referenced by computeFragmentSize(), llvm::MCELFStreamer::EmitAssemblerFlag(), llvm::MCObjectStreamer::EmitInstruction(), Finish(), llvm::MachObjectWriter::isFixupKindPCRel(), isSymbolLinkerVisible(), reset(), writeFragment(), and llvm::MCObjectStreamer::~MCObjectStreamer().
unsigned llvm::MCAssembler::getBundleAlignSize () const inline
Definition at line 1068 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitBundleAlignMode(), llvm::MCAsmLayout::layoutFragment(), and writeFragment().
MCContext& llvm::MCAssembler::getContext () const inline
Definition at line 1040 of file MCAssembler.h.
Referenced by CompressDebugSection(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitFrame(), llvm::MCELFStreamer::EmitIdent(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::PPCMCExpr::EvaluateAsRelocatableImpl(), llvm::MipsTargetELFStreamer::finish(), getAtom(), llvm::MCAsmLayout::getBaseSymbol(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), and llvm::MipsAsmBackend::processFixupValue().
std::vector<DataRegionData>& llvm::MCAssembler::getDataRegions () inline
Definition at line 1152 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteObject().
unsigned llvm::MCAssembler::getELFHeaderEFlags () const inline
ELF e_header flags.
Definition at line 1009 of file MCAssembler.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetELFStreamer::emitDirectiveNaN2008(), llvm::MipsTargetELFStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic0(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic2(), llvm::MipsTargetELFStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetELFStreamer::emitDirectiveSetMips16(), and llvm::MipsTargetELFStreamer::emitDirectiveSetNoReorder().
MCCodeEmitter& llvm::MCAssembler::getEmitter () const inline
Definition at line 1044 of file MCAssembler.h.
Referenced by llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::MCWinCOFFStreamer::EmitInstToData(), llvm::MCObjectStreamer::EmitInstToFragment(), reset(), and llvm::MCObjectStreamer::~MCObjectStreamer().
std::vector<IndirectSymbolData>& llvm::MCAssembler::getIndirectSymbols () inline
Definition at line 1117 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitSymbolAttribute().
std::vector<std::vector<std::string> >& llvm::MCAssembler::getLinkerOptions () inline
Definition at line 1141 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteObject().
MCLOHContainer& llvm::MCAssembler::getLOHContainer () inline
Definition at line 1179 of file MCAssembler.h.
Referenced by getLOHContainer(), reset(), and llvm::MachObjectWriter::WriteObject().
const MCLOHContainer& llvm::MCAssembler::getLOHContainer () const inline
Definition at line 1182 of file MCAssembler.h.
References getLOHContainer().
MCSectionData& llvm::MCAssembler::getOrCreateSectionData (const MCSection & Section, bool * Created = nullptr) inline
Definition at line 1195 of file MCAssembler.h.
References llvm::ARMBuildAttrs::Section.
Referenced by llvm::MCObjectStreamer::ChangeSection(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MipsTargetELFStreamer::finish(), and llvm::MCELFStreamer::Flush().
MCSymbolData& llvm::MCAssembler::getOrCreateSymbolData (const MCSymbol & Symbol, bool * Created = nullptr) inline
Definition at line 1221 of file MCAssembler.h.
References llvm::ARMBuildAttrs::Symbol.
Referenced by llvm::MachObjectWriter::BindIndirectSymbols(), llvm::MCELFStreamer::ChangeSection(), llvm::MCObjectStreamer::EmitAssignment(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolStorageClass(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolType(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MCELFStreamer::EmitELFSize(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MCELFStreamer::EmitLocalCommonSymbol(), llvm::MCWinCOFFStreamer::EmitSymbolAttribute(), llvm::MCELFStreamer::EmitSymbolAttribute(), llvm::MCELFStreamer::EmitWeakReference(), fixELFSymbolsInTLSFixupsImpl(), llvm::MCObjectStreamer::getOrCreateSymbolData(), and llvm::MCObjectStreamer::visitUsedSymbol().
bool llvm::MCAssembler::getRelaxAll () const inline
Definition at line 1061 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitInstruction().
MCSectionData& llvm::MCAssembler::getSectionData (const MCSection & Section) const inline
Definition at line 1189 of file MCAssembler.h.
References assert().
const SectionDataListType& llvm::MCAssembler::getSectionList () const inline
Definition at line 1081 of file MCAssembler.h.
Referenced by llvm::MCSectionData::MCSectionData().
SectionDataListType& llvm::MCAssembler::getSectionList () inline
Definition at line 1082 of file MCAssembler.h.
bool llvm::MCAssembler::getSubsectionsViaSymbols () const inline
Definition at line 1054 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), and llvm::MachObjectWriter::WriteObject().
MCSymbolData& llvm::MCAssembler::getSymbolData (const MCSymbol & Symbol) inline
Definition at line 1210 of file MCAssembler.h.
References getSymbolData().
Referenced by llvm::MCELFStreamer::ChangeSection(), llvm::MCELFStreamer::EmitLabel(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolData(), getSymbolOffsetImpl(), llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolved(), llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), and llvm::MachObjectWriter::WriteObject().
const MCSymbolData& llvm::MCAssembler::getSymbolData (const MCSymbol & Symbol) const inline
Definition at line 1215 of file MCAssembler.h.
References assert().
const SymbolDataListType& llvm::MCAssembler::getSymbolList () const inline
Definition at line 1096 of file MCAssembler.h.
Referenced by llvm::MCSymbolData::MCSymbolData().
SymbolDataListType& llvm::MCAssembler::getSymbolList () inline
Definition at line 1097 of file MCAssembler.h.
const VersionMinInfoType& llvm::MCAssembler::getVersionMinInfo () const inline
MachO deployment target version information.
Definition at line 1013 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteObject().
MCObjectWriter& llvm::MCAssembler::getWriter () const inline
Definition at line 1046 of file MCAssembler.h.
Referenced by Finish(), reset(), writeFragment(), writeSectionData(), and llvm::MCObjectStreamer::~MCObjectStreamer().
bool llvm::MCAssembler::hasSymbolData (const MCSymbol & Symbol) const inline
Definition at line 1206 of file MCAssembler.h.
indirect_symbol_iterator llvm::MCAssembler::indirect_symbol_begin () inline
Definition at line 1121 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::BindIndirectSymbols(), and llvm::MachObjectWriter::WriteObject().
const_indirect_symbol_iterator llvm::MCAssembler::indirect_symbol_begin () const inline
Definition at line 1124 of file MCAssembler.h.
indirect_symbol_iterator llvm::MCAssembler::indirect_symbol_end () inline
Definition at line 1128 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::BindIndirectSymbols(), and llvm::MachObjectWriter::WriteObject().
const_indirect_symbol_iterator llvm::MCAssembler::indirect_symbol_end () const inline
Definition at line 1131 of file MCAssembler.h.
size_t llvm::MCAssembler::indirect_symbol_size () const inline
Definition at line 1135 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteObject().
bool llvm::MCAssembler::isBundlingEnabled () const inline
Definition at line 1064 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitInstruction(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::MCAsmLayout::layoutFragment(), and writeFragment().
bool MCAssembler::isSymbolLinkerVisible (const MCSymbol & SD) const
Check whether a particular symbol is visible to the linker and is required in the symbol table, or whether it can be discarded by the assembler. This also effects whether the assembler treats the label as potentially defining a separate atom.
Definition at line 428 of file MCAssembler.cpp.
References llvm::MCAsmBackend::doesSectionRequireSymbols(), getBackend(), llvm::MCSymbol::getSection(), llvm::MCSymbol::isInSection(), and llvm::MCSymbol::isTemporary().
Referenced by llvm::MachObjectWriter::ComputeSymbolTable(), and getAtom().
bool MCAssembler::isThumbFunc (const MCSymbol * Func) const
Check whether a given symbol has been flagged with .thumb_func.
Definition at line 403 of file MCAssembler.cpp.
References llvm::dyn_cast(), llvm::MCSymbolRefExpr::getKind(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbol::getVariableValue(), llvm::MCSymbol::isVariable(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MachObjectWriter::WriteNlist().
void MCAssembler::reset ()
Reuse an assembler instance
Definition at line 379 of file MCAssembler.cpp.
References getBackend(), getEmitter(), getLOHContainer(), getWriter(), llvm::MCAssembler::VersionMinInfoType::Major, llvm::MCCodeEmitter::reset(), llvm::MCAsmBackend::reset(), llvm::MCObjectWriter::reset(), and llvm::MCLOHContainer::reset().
Referenced by llvm::MCObjectStreamer::reset().
void llvm::MCAssembler::setBundleAlignSize (unsigned Size) inline
Definition at line 1072 of file MCAssembler.h.
References assert().
Referenced by llvm::MCELFStreamer::EmitBundleAlignMode().
void llvm::MCAssembler::setELFHeaderEFlags (unsigned Flags) inline
Definition at line 1010 of file MCAssembler.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetELFStreamer::emitDirectiveNaN2008(), llvm::MipsTargetELFStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic0(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic2(), llvm::MipsTargetELFStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetELFStreamer::emitDirectiveSetMips16(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoReorder(), and llvm::MipsTargetELFStreamer::MipsTargetELFStreamer().
void llvm::MCAssembler::setIsThumbFunc (const MCSymbol * Func) inline
Flag a function symbol as the target of a .thumb_func directive.
Definition at line 1006 of file MCAssembler.h.
void llvm::MCAssembler::setRelaxAll (bool Value) inline
Definition at line 1062 of file MCAssembler.h.
Referenced by llvm::createELFStreamer().
void llvm::MCAssembler::setSubsectionsViaSymbols (bool Value) inline
Definition at line 1057 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitAssemblerFlag().
void llvm::MCAssembler::setVersionMinInfo (MCVersionMinType Kind, unsigned Major, unsigned Minor, unsigned Update) inline
Definition at line 1014 of file MCAssembler.h.
References llvm::MCAssembler::VersionMinInfoType::Kind, llvm::MCAssembler::VersionMinInfoType::Major, llvm::MCAssembler::VersionMinInfoType::Minor, and llvm::MCAssembler::VersionMinInfoType::Update.
size_t llvm::MCAssembler::size () const inline
Definition at line 1090 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteObject().
symbol_iterator llvm::MCAssembler::symbol_begin () inline
Definition at line 1099 of file MCAssembler.h.
Referenced by dump(), and symbols().
const_symbol_iterator llvm::MCAssembler::symbol_begin () const inline
Definition at line 1100 of file MCAssembler.h.
symbol_iterator llvm::MCAssembler::symbol_end () inline
Definition at line 1102 of file MCAssembler.h.
Referenced by dump(), and symbols().
const_symbol_iterator llvm::MCAssembler::symbol_end () const inline
Definition at line 1103 of file MCAssembler.h.
size_t llvm::MCAssembler::symbol_size () const inline
Definition at line 1108 of file MCAssembler.h.
symbol_range llvm::MCAssembler::symbols () inline
Definition at line 1105 of file MCAssembler.h.
References llvm::make_range(), symbol_begin(), and symbol_end().
Referenced by llvm::MachObjectWriter::ComputeSymbolTable(), and llvm::MachObjectWriter::markAbsoluteVariableSymbols().
const_symbol_range llvm::MCAssembler::symbols () const inline
Definition at line 1106 of file MCAssembler.h.
References llvm::make_range(), symbol_begin(), and symbol_end().
void MCAssembler::writeSectionData (const MCSectionData * Section, const MCAsmLayout & Layout) const
Emit the section contents using the given object writer.
Definition at line 806 of file MCAssembler.cpp.
References assert(), llvm::MCSectionData::begin(), llvm::MCSectionData::end(), llvm::MCDataFragment::fixup_begin(), llvm::MCDataFragment::fixup_end(), llvm::MCFragment::FT_Align, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Fill, llvm::MCDataFragment::getContents(), llvm::MCSectionData::getSection(), llvm::MCAsmLayout::getSectionAddressSize(), llvm::MCAsmLayout::getSectionFileSize(), llvm::MCObjectWriter::getStream(), getWriter(), llvm::MCSection::isVirtualSection(), llvm_unreachable, llvm::report_fatal_error(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::raw_ostream::tell(), and writeFragment().
Referenced by llvm::MachObjectWriter::WriteObject().
Friends And Related Function Documentation
friend class MCAsmLayout friend
Definition at line 831 of file MCAssembler.h.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp