LLVM: llvm::MemSDNode Class Reference
LLVM API Documentation
llvm::MemSDNode Class Reference
Abstact virtual class for operations for memory operations.
#include <SelectionDAGNodes.h>
Public Member Functions
MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, EVT MemoryVT, MachineMemOperand *MMO)
MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops, EVT MemoryVT, MachineMemOperand *MMO)
bool readMem () const
bool writeMem () const
unsigned getOriginalAlignment () const
Returns alignment and volatility of the memory access.
unsigned getAlignment () const
unsigned getRawSubclassData () const
bool isVolatile () const
bool isNonTemporal () const
bool isInvariant () const
AtomicOrdering getOrdering () const
SynchronizationScope getSynchScope () const
int64_t getSrcValueOffset () const
AAMDNodes getAAInfo () const
Returns the AA info that describes the dereference.
const MDNode * getRanges () const
Returns the Ranges that describes the dereference.
EVT getMemoryVT () const
getMemoryVT - Return the type of the in-memory value.
MachineMemOperand * getMemOperand () const
const MachinePointerInfo & getPointerInfo () const
unsigned getAddressSpace () const
getAddressSpace - Return the address space for the associated pointer
void refineAlignment (const MachineMemOperand *NewMMO)
const SDValue & getChain () const
const SDValue & getBasePtr () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMemIntrinsic () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
iterator_range< use_iterator > uses ()
iterator_range< use_iterator > uses () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSetImpl< const SDNode * > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< SDUse > ops () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=nullptr) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printr (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printrFull (raw_ostream &O, const SelectionDAG *G=nullptr) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=nullptr, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=nullptr) const
void dumprWithDepth (const SelectionDAG *G=nullptr, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
const SDNode * getPrevNode () const
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
const SDNode * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Protected Attributes
MachineMemOperand * MMO
MMO - Memory reference information.
Protected Attributes inherited from llvm::SDNode
uint16_t SubclassData: 14
Additional Inherited Members
Public Types inherited from llvm::SDNode
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Detailed Description
Abstact virtual class for operations for memory operations.
Definition at line 1076 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
MemSDNode::MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, EVT MemoryVT, MachineMemOperand * MMO)
Definition at line 6267 of file SelectionDAG.cpp.
References assert(), encodeMemSDNodeFlags(), llvm::MachineMemOperand::getSize(), llvm::EVT::getStoreSize(), llvm::MachineMemOperand::isInvariant(), llvm::MachineMemOperand::isNonTemporal(), isNonTemporal(), llvm::MachineMemOperand::isVolatile(), isVolatile(), MMO, llvm::SDNode::SubclassData, and llvm::ISD::UNINDEXED.
MemSDNode::MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops, EVT MemoryVT, MachineMemOperand * MMO)
Definition at line 6281 of file SelectionDAG.cpp.
References assert(), encodeMemSDNodeFlags(), llvm::MachineMemOperand::getSize(), llvm::EVT::getStoreSize(), llvm::MachineMemOperand::isInvariant(), llvm::MachineMemOperand::isNonTemporal(), llvm::MachineMemOperand::isVolatile(), isVolatile(), MMO, llvm::SDNode::SubclassData, and llvm::ISD::UNINDEXED.
Member Function Documentation
static bool llvm::MemSDNode::classof (const SDNode * N) inline static
Definition at line 1162 of file SelectionDAGNodes.h.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::SDNode::getOpcode(), llvm::SDNode::isMemIntrinsic(), llvm::SDNode::isTargetMemoryOpcode(), llvm::ISD::LOAD, llvm::ISD::MLOAD, llvm::ISD::MSTORE, llvm::ISD::PREFETCH, and llvm::ISD::STORE.
AAMDNodes llvm::MemSDNode::getAAInfo () const inline
Returns the AA info that describes the dereference.
Definition at line 1127 of file SelectionDAGNodes.h.
Referenced by ExpandUnalignedLoad(), ExpandUnalignedStore(), and PerformSTORECombine().
unsigned llvm::MemSDNode::getAddressSpace () const inline
getAddressSpace - Return the address space for the associated pointer
Definition at line 1144 of file SelectionDAGNodes.h.
Referenced by ExpandUnalignedStore(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::AMDGPUTargetLowering::LowerSTORE(), and llvm::SITargetLowering::PerformDAGCombine().
unsigned llvm::MemSDNode::getAlignment () const inline
Definition at line 1099 of file SelectionDAGNodes.h.
Referenced by EltsFromConsecutiveLoads(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::SelectionDAG::getIndexedLoad(), LowerF128Load(), LowerF128Store(), lowerFP_TO_SINT_STORE(), llvm::MipsTargetLowering::lowerLOAD(), llvm::MipsTargetLowering::lowerSTORE(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), PerformLOADCombine(), performSTORECombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), ReplaceLoadVector(), replaceSplatVectorStore(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and XFormVExtractWithShuffleIntoLoad().
const SDValue& llvm::MemSDNode::getBasePtr () const inline
Definition at line 1157 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), and llvm::ISD::STORE.
Referenced by llvm::PPCTargetLowering::expandVSXLoadForLE(), isConsecutiveLSLoc(), and llvm::SITargetLowering::PerformDAGCombine().
const SDValue& llvm::MemSDNode::getChain () const inline
Definition at line 1156 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by EltsFromConsecutiveLoads(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), findConsecutiveLoad(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::isConsecutiveLoad(), isLoadIncOrDecStore(), LowerF128Load(), LowerF128Store(), lowerFP_TO_SINT_STORE(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::MipsTargetLowering::lowerLOAD(), llvm::AMDGPUTargetLowering::LowerSTORE(), lowerUnalignedIntStore(), NarrowVectorLoadToElement(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), PerformLOADCombine(), PerformMLOADCombine(), PerformMSTORECombine(), PerformSINT_TO_FPCombine(), performSTORECombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), replaceSplatVectorStore(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
MachineMemOperand* llvm::MemSDNode::getMemOperand () const inline
getMemOperand - Return a MachineMemOperand object describing the memory reference performed by operation.
Definition at line 1137 of file SelectionDAGNodes.h.
Referenced by CombineBaseUpdate(), CombineVLDDUP(), createLoadLR(), createStoreLR(), ExpandUnalignedLoad(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), getCodeAddrSpace(), llvm::SelectionDAG::getIndexedStore(), llvm::AMDGPUTargetLowering::LowerLOAD(), NarrowVectorLoadToElement(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformMLOADCombine(), PerformMSTORECombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
EVT llvm::MemSDNode::getMemoryVT () const inline
getMemoryVT - Return the type of the in-memory value.
Definition at line 1133 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), checkValueWidth(), CombineBaseUpdate(), CombineVLDDUP(), llvm::SelectionDAG::computeKnownBits(), createLoadLR(), createStoreLR(), ExpandUnalignedLoad(), ExpandUnalignedStore(), findConsecutiveLoad(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), isLoadIncOrDecStore(), isValidIndexedLoad(), llvm::PPCTargetLowering::isZExtFree(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::MipsTargetLowering::lowerLOAD(), llvm::AMDGPUTargetLowering::LowerSTORE(), llvm::MipsTargetLowering::lowerSTORE(), PerformANDCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformMLOADCombine(), PerformMSTORECombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformSTORECombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
AtomicOrdering llvm::MemSDNode::getOrdering () const inline
Definition at line 1116 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
unsigned llvm::MemSDNode::getOriginalAlignment () const inline
Returns alignment and volatility of the memory access.
Definition at line 1096 of file SelectionDAGNodes.h.
const MachinePointerInfo& llvm::MemSDNode::getPointerInfo () const inline
Definition at line 1139 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), EltsFromConsecutiveLoads(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), LowerF128Load(), lowerFP_TO_SINT_STORE(), performIntToFpCombine(), PerformLOADCombine(), performSTORECombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), replaceSplatVectorStore(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), and SkipLoadExtensionForVMULL().
const MDNode* llvm::MemSDNode::getRanges () const inline
Returns the Ranges that describes the dereference.
Definition at line 1130 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::computeKnownBits().
unsigned llvm::MemSDNode::getRawSubclassData () const inline
getRawSubclassData - Return the SubclassData value, which contains an encoding of the volatile flag, as well as bits used by subclasses. This function should only be used to compute a FoldingSetNodeID value.
Definition at line 1106 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Referenced by AddNodeIDCustom(), and llvm::SelectionDAG::getIndexedStore().
int64_t llvm::MemSDNode::getSrcValueOffset () const inline
Definition at line 1124 of file SelectionDAGNodes.h.
SynchronizationScope llvm::MemSDNode::getSynchScope () const inline
Definition at line 1119 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
bool llvm::MemSDNode::isInvariant () const inline
Definition at line 1114 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Referenced by EltsFromConsecutiveLoads(), ExpandUnalignedLoad(), performIntToFpCombine(), PerformLOADCombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), SkipLoadExtensionForVMULL(), and llvm::AMDGPUTargetLowering::SplitVectorLoad().
bool llvm::MemSDNode::isNonTemporal () const inline
Definition at line 1113 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Referenced by EltsFromConsecutiveLoads(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::SelectionDAG::getIndexedLoad(), isLoadIncOrDecStore(), lowerFP_TO_SINT_STORE(), MemSDNode(), performIntToFpCombine(), PerformLOADCombine(), performSTORECombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), replaceSplatVectorStore(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
bool llvm::MemSDNode::isVolatile () const inline
Definition at line 1112 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Referenced by EltsFromConsecutiveLoads(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::SelectionDAG::getIndexedLoad(), isCalleeLoad(), lowerFP_TO_SINT_STORE(), MemSDNode(), performIntToFpCombine(), PerformLOADCombine(), PerformSINT_TO_FPCombine(), performSTORECombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), replaceSplatVectorStore(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and XFormVExtractWithShuffleIntoLoad().
bool llvm::MemSDNode::readMem () const inline
Definition at line 1092 of file SelectionDAGNodes.h.
void llvm::MemSDNode::refineAlignment (const MachineMemOperand * NewMMO) inline
refineAlignment - Update this MemSDNode's MachineMemOperand information to reflect the alignment of NewMMO, if it has a greater alignment. This must only be used when the new alignment applies to all users of this MachineMemOperand.
Definition at line 1152 of file SelectionDAGNodes.h.
bool llvm::MemSDNode::writeMem () const inline
Definition at line 1093 of file SelectionDAGNodes.h.
Member Data Documentation
MachineMemOperand* llvm::MemSDNode::MMO protected
MMO - Memory reference information.
Definition at line 1083 of file SelectionDAGNodes.h.
Referenced by MemSDNode().
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp