LLVM: llvm::SMFixIt Class Reference
LLVM API Documentation
llvm::SMFixIt Class Reference
Represents a single fixit, a replacement of one range of text with another.
#include <SourceMgr.h>
Public Member Functions
SMFixIt (SMLoc Loc, const Twine &Insertion)
SMFixIt (SMRange R, const Twine &Replacement)
StringRef getText () const
SMRange getRange () const
bool operator< (const SMFixIt &Other) const
Detailed Description
Represents a single fixit, a replacement of one range of text with another.
Definition at line 200 of file SourceMgr.h.
Constructor & Destructor Documentation
llvm::SMFixIt::SMFixIt (SMLoc Loc, const Twine & Insertion) inline
Definition at line 207 of file SourceMgr.h.
References assert(), and llvm::SMLoc::isValid().
llvm::SMFixIt::SMFixIt (SMRange R, const Twine & Replacement) inline
Definition at line 213 of file SourceMgr.h.
References assert(), and llvm::SMRange::isValid().
Member Function Documentation
SMRange llvm::SMFixIt::getRange () const inline
Definition at line 219 of file SourceMgr.h.
StringRef llvm::SMFixIt::getText () const inline
Definition at line 218 of file SourceMgr.h.
bool llvm::SMFixIt::operator< (const SMFixIt & Other) const inline
Definition at line 221 of file SourceMgr.h.
References llvm::SMRange::End, llvm::SMLoc::getPointer(), and llvm::SMRange::Start.
The documentation for this class was generated from the following file:
SourceMgr.h