LLVM: llvm::object::MachOUniversalBinary Class Reference
LLVM API Documentation
llvm::object::MachOUniversalBinary Class Reference
#include <MachOUniversal.h>
Classes
class object_iterator
class ObjectForArch
Public Member Functions
MachOUniversalBinary (MemoryBufferRef Souce, std::error_code &EC)
object_iterator begin_objects () const
object_iterator end_objects () const
uint32_t getNumberOfObjects () const
ErrorOr< std::unique_ptr
< MachOObjectFile > > getObjectForArch (Triple::ArchType Arch) const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isIR () const
bool isLittleEndian () const
Static Public Member Functions
static ErrorOr
< std::unique_ptr
< MachOUniversalBinary > > create (MemoryBufferRef Source)
static bool classof (Binary const *V)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_IR, ID_StartObjects,
ID_COFF, ID_ELF32L, ID_ELF32B, ID_ELF64L,
ID_ELF64B, ID_MachO32L, ID_MachO32B, ID_MachO64L,
ID_MachO64B, ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 28 of file MachOUniversal.h.
Constructor & Destructor Documentation
MachOUniversalBinary::MachOUniversalBinary (MemoryBufferRef Souce, std::error_code & EC)
Definition at line 106 of file MachOUniversal.cpp.
References llvm::StringRef::begin(), llvm::object::Binary::Data, llvm::MachO::FAT_MAGIC, llvm::MemoryBufferRef::getBufferSize(), llvm::object::Binary::getData(), H, llvm::object::invalid_file_type, llvm::MachO::fat_header::magic, llvm::MachO::fat_header::nfat_arch, llvm::object::parse_failed, llvm::StringRef::size(), and llvm::object::success.
Referenced by create().
Member Function Documentation
object_iterator llvm::object::MachOUniversalBinary::begin_objects () const inline
Definition at line 93 of file MachOUniversal.h.
Referenced by getObjectForArch().
static bool llvm::object::MachOUniversalBinary::classof (Binary const * V) inline static
Definition at line 103 of file MachOUniversal.h.
References llvm::object::Binary::isMachOUniversalBinary().
ErrorOr< std::unique_ptr< MachOUniversalBinary > > MachOUniversalBinary::create (MemoryBufferRef Source) static
Definition at line 97 of file MachOUniversal.cpp.
References MachOUniversalBinary(), and llvm::MipsISD::Ret.
Referenced by llvm::object::createBinary().
object_iterator llvm::object::MachOUniversalBinary::end_objects () const inline
Definition at line 96 of file MachOUniversal.h.
Referenced by getObjectForArch().
uint32_t llvm::object::MachOUniversalBinary::getNumberOfObjects () const inline
Definition at line 100 of file MachOUniversal.h.
Referenced by llvm::object::MachOUniversalBinary::ObjectForArch::ObjectForArch().
ErrorOr< std::unique_ptr< MachOObjectFile > > MachOUniversalBinary::getObjectForArch (Triple::ArchType Arch) const
Definition at line 139 of file MachOUniversal.cpp.
References llvm::object::arch_not_found, begin_objects(), end_objects(), getCTMForArch(), and I.
The documentation for this class was generated from the following files:
MachOUniversal.h
MachOUniversal.cpp