LLVM: llvm::ImmutableSetRef< ValT, ValInfo >::iterator Class Reference
LLVM API Documentation
llvm::ImmutableSetRef< ValT, ValInfo >::iterator Class Reference
#include <ImmutableSet.h>
Public Member Functions
iterator ()
value_type_ref operator* () const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
bool operator== (const iterator &RHS) const
bool operator!= (const iterator &RHS) const
value_type * operator-> () const
Friends
class ImmutableSetRef< ValT, ValInfo >
Detailed Description
template<typename ValT, typename ValInfo = ImutContainerInfo<ValT>>
class llvm::ImmutableSetRef< ValT, ValInfo >::iterator
Definition at line 1198 of file ImmutableSet.h.
Constructor & Destructor Documentation
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> llvm::ImmutableSetRef< ValT, ValInfo >::iterator::iterator () inline
Definition at line 1203 of file ImmutableSet.h.
Member Function Documentation
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> bool llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator!= (const iterator & RHS) const inline
Definition at line 1210 of file ImmutableSet.h.
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> value_type_ref llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator* () const inline
Definition at line 1204 of file ImmutableSet.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
Referenced by llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator->().
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> iterator& llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator++ () inline
Definition at line 1205 of file ImmutableSet.h.
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> iterator llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator++ (int) inline
Definition at line 1206 of file ImmutableSet.h.
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> iterator& llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator-- () inline
Definition at line 1207 of file ImmutableSet.h.
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> iterator llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator-- (int) inline
Definition at line 1208 of file ImmutableSet.h.
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> value_type* llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator-> () const inline
Definition at line 1211 of file ImmutableSet.h.
References llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator*().
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> bool llvm::ImmutableSetRef< ValT, ValInfo >::iterator::operator== (const iterator & RHS) const inline
Definition at line 1209 of file ImmutableSet.h.
Friends And Related Function Documentation
template<typename ValT , typename ValInfo = ImutContainerInfo<ValT>> friend class ImmutableSetRef< ValT, ValInfo > friend
Definition at line 1201 of file ImmutableSet.h.
The documentation for this class was generated from the following file:
ImmutableSet.h