LLVM: llvm::SCEVUDivExpr Class Reference
LLVM API Documentation
llvm::SCEVUDivExpr Class Reference
#include <ScalarEvolutionExpressions.h>
Public Member Functions
const SCEV * getLHS () const
const SCEV * getRHS () const
Type * getType () const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy)
unsigned getSCEVType () const
Type * getType () const
bool isZero () const
bool isOne () const
bool isAllOnesValue () const
bool isNonConstantNegative () const
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Friends
class ScalarEvolution
Additional Inherited Members
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0, FlagNW = (1 << 0), FlagNUW = (1 << 1), FlagNSW = (1 << 2),
NoWrapMask = (1 << 3) -1
}
Protected Attributes inherited from llvm::SCEV
unsigned short SubclassData
Detailed Description
SCEVUDivExpr - This class represents a binary unsigned division operation.
Definition at line 251 of file ScalarEvolutionExpressions.h.
Member Function Documentation
static bool llvm::SCEVUDivExpr::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 273 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), and llvm::scUDivExpr.
const SCEV* llvm::SCEVUDivExpr::getLHS () const inline
Definition at line 260 of file ScalarEvolutionExpressions.h.
Referenced by BuildConstantFromSCEV(), llvm::SCEV::print(), llvm::SCEVTraversal< SV >::visitAll(), llvm::SCEVParameterRewriter::visitUDivExpr(), and llvm::SCEVApplyRewriter::visitUDivExpr().
const SCEV* llvm::SCEVUDivExpr::getRHS () const inline
Definition at line 261 of file ScalarEvolutionExpressions.h.
Referenced by BuildConstantFromSCEV(), getType(), llvm::SCEV::print(), llvm::SCEVTraversal< SV >::visitAll(), llvm::SCEVParameterRewriter::visitUDivExpr(), and llvm::SCEVApplyRewriter::visitUDivExpr().
Type* llvm::SCEVUDivExpr::getType () const inline
Definition at line 263 of file ScalarEvolutionExpressions.h.
References getRHS(), and llvm::SCEV::getType().
Friends And Related Function Documentation
friend class ScalarEvolution friend
Definition at line 252 of file ScalarEvolutionExpressions.h.
The documentation for this class was generated from the following file:
ScalarEvolutionExpressions.h