LLVM: ConstantPools.cpp File Reference
LLVM API Documentation
ConstantPools.cpp File Reference
#include "llvm/ADT/MapVector.h"
#include "llvm/MC/ConstantPools.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCStreamer.h"
Functions
static void emitConstantPool (MCStreamer &Streamer, const MCSection *Section, ConstantPool &CP)
Function Documentation
static void emitConstantPool (MCStreamer & Streamer, const MCSection * Section, ConstantPool & CP) static
Definition at line 65 of file ConstantPools.cpp.
References llvm::ConstantPool::emitEntries(), llvm::ConstantPool::empty(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::AssemblerConstantPools::emitAll(), and llvm::AssemblerConstantPools::emitForCurrentSection().