LLVM: CoverageMapping.cpp File Reference
LLVM API Documentation
CoverageMapping.cpp File Reference
#include "llvm/ProfileData/CoverageMapping.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ProfileData/CoverageMappingReader.h"
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
Macros
#define DEBUG_TYPE "coverage-mapping"
Functions
static Optional< unsigned > findMainViewFileID (StringRef SourceFile, const FunctionRecord &Function)
static Optional< unsigned > findMainViewFileID (const FunctionRecord &Function)
static SmallSet< unsigned, 8 > gatherFileIDs (StringRef SourceFile, const FunctionRecord &Function)
template<class It >
static void sortNestedRegions (It First, It Last)
Sort a nested sequence of regions from a single file.
static bool isExpansion (const CountedRegion &R, unsigned FileID)
Macro Definition Documentation
#define DEBUG_TYPE "coverage-mapping"
Definition at line 27 of file CoverageMapping.cpp.
Function Documentation
static Optional<unsigned> findMainViewFileID (StringRef SourceFile, const FunctionRecord & Function) static
Definition at line 341 of file CoverageMapping.cpp.
References llvm::coverage::FunctionRecord::CountedRegions, llvm::coverage::CounterMappingRegion::ExpansionRegion, llvm::coverage::FunctionRecord::Filenames, I, and llvm::None.
Referenced by llvm::coverage::CoverageMapping::getCoverageForFile(), llvm::coverage::CoverageMapping::getCoverageForFunction(), and llvm::coverage::CoverageMapping::getInstantiations().
static Optional<unsigned> findMainViewFileID (const FunctionRecord & Function) static
Definition at line 359 of file CoverageMapping.cpp.
References llvm::coverage::FunctionRecord::CountedRegions, llvm::coverage::CounterMappingRegion::ExpansionRegion, llvm::coverage::FunctionRecord::Filenames, I, and llvm::None.
static SmallSet<unsigned, 8> gatherFileIDs (StringRef SourceFile, const FunctionRecord & Function) static
Definition at line 370 of file CoverageMapping.cpp.
References llvm::coverage::FunctionRecord::Filenames, I, and llvm::SmallSet< T, N, C >::insert().
Referenced by llvm::coverage::CoverageMapping::getCoverageForFile().
static bool isExpansion (const CountedRegion & R, unsigned FileID) static
Definition at line 390 of file CoverageMapping.cpp.
References llvm::coverage::CounterMappingRegion::ExpansionRegion, llvm::coverage::CounterMappingRegion::FileID, and llvm::coverage::CounterMappingRegion::Kind.
Referenced by llvm::coverage::CoverageMapping::getCoverageForExpansion(), llvm::coverage::CoverageMapping::getCoverageForFile(), and llvm::coverage::CoverageMapping::getCoverageForFunction().
template<class It > static void sortNestedRegions (It First, It Last) static
Sort a nested sequence of regions from a single file.
Definition at line 380 of file CoverageMapping.cpp.
References llvm::coverage::CounterMappingRegion::endLoc(), and llvm::coverage::CounterMappingRegion::startLoc().
Referenced by llvm::coverage::CoverageMapping::getCoverageForExpansion(), llvm::coverage::CoverageMapping::getCoverageForFile(), and llvm::coverage::CoverageMapping::getCoverageForFunction().