LLVM: DataExtractor.cpp File Reference
LLVM API Documentation
DataExtractor.cpp File Reference
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/SwapByteOrder.h"
Functions
template<typename T >
static T getU (uint32_t *offset_ptr, const DataExtractor *de, bool isLittleEndian, const char *Data)
template<typename T >
static T * getUs (uint32_t *offset_ptr, T *dst, uint32_t count, const DataExtractor *de, bool isLittleEndian, const char *Data)
Function Documentation
template<typename T > static T getU (uint32_t * offset_ptr, const DataExtractor * de, bool isLittleEndian, const char * Data) static
Definition at line 17 of file DataExtractor.cpp.
References llvm::sys::IsLittleEndianHost, llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::Intrinsic::memcpy, and llvm::sys::swapByteOrder().
Referenced by llvm::ScaledNumbers::multiply64().
template<typename T > static T* getUs (uint32_t * offset_ptr, T * dst, uint32_t count, const DataExtractor * de, bool isLittleEndian, const char * Data) static
Definition at line 33 of file DataExtractor.cpp.
References llvm::sys::path::end(), and llvm::DataExtractor::isValidOffsetForDataOfSize().