LLVM: DbgValueHistoryCalculator.cpp File Reference
LLVM API Documentation
DbgValueHistoryCalculator.cpp File Reference
#include "DbgValueHistoryCalculator.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include <algorithm>
#include <map>
Macros
#define DEBUG_TYPE "dwarfdebug"
Functions
static unsigned isDescribedByReg (const MachineInstr &MI)
static void dropRegDescribedVar (RegDescribedVarsMap &RegVars, unsigned RegNo, const MDNode *Var)
static void addRegDescribedVar (RegDescribedVarsMap &RegVars, unsigned RegNo, const MDNode *Var)
static void clobberRegisterUses (RegDescribedVarsMap &RegVars, RegDescribedVarsMap::iterator I, DbgValueHistoryMap &HistMap, const MachineInstr &ClobberingInstr)
static void clobberRegisterUses (RegDescribedVarsMap &RegVars, unsigned RegNo, DbgValueHistoryMap &HistMap, const MachineInstr &ClobberingInstr)
template<typename Callable >
static void applyToClobberedRegisters (const MachineInstr &MI, const TargetRegisterInfo *TRI, Callable Func)
static const MachineInstr * getFirstEpilogueInst (const MachineBasicBlock &MBB)
static void collectChangingRegs (const MachineFunction *MF, const TargetRegisterInfo *TRI, BitVector &Regs)
Macro Definition Documentation
#define DEBUG_TYPE "dwarfdebug"
Definition at line 22 of file DbgValueHistoryCalculator.cpp.
Function Documentation
static void addRegDescribedVar (RegDescribedVarsMap & RegVars, unsigned RegNo, const MDNode * Var) static
Definition at line 91 of file DbgValueHistoryCalculator.cpp.
References assert().
Referenced by llvm::calculateDbgValueHistory().
template<typename Callable > static void applyToClobberedRegisters (const MachineInstr & MI, const TargetRegisterInfo * TRI, Callable Func) static
Definition at line 132 of file DbgValueHistoryCalculator.cpp.
References llvm::MCRegAliasIterator::isValid(), and llvm::MachineInstr::operands().
Referenced by llvm::calculateDbgValueHistory(), and collectChangingRegs().
static void clobberRegisterUses (RegDescribedVarsMap & RegVars, RegDescribedVarsMap::iterator I, DbgValueHistoryMap & HistMap, const MachineInstr & ClobberingInstr) static
Definition at line 101 of file DbgValueHistoryCalculator.cpp.
References llvm::DbgValueHistoryMap::endInstrRange().
Referenced by llvm::calculateDbgValueHistory(), and clobberRegisterUses().
static void clobberRegisterUses (RegDescribedVarsMap & RegVars, unsigned RegNo, DbgValueHistoryMap & HistMap, const MachineInstr & ClobberingInstr) static
Definition at line 114 of file DbgValueHistoryCalculator.cpp.
References clobberRegisterUses(), and I.
static void collectChangingRegs (const MachineFunction * MF, const TargetRegisterInfo * TRI, BitVector & Regs) static
Definition at line 167 of file DbgValueHistoryCalculator.cpp.
References applyToClobberedRegisters(), llvm::MachineInstr::FrameSetup, getFirstEpilogueInst(), llvm::AArch64CC::MI, and llvm::BitVector::set().
Referenced by llvm::calculateDbgValueHistory().
static void dropRegDescribedVar (RegDescribedVarsMap & RegVars, unsigned RegNo, const MDNode * Var) static
Definition at line 77 of file DbgValueHistoryCalculator.cpp.
References assert(), and I.
Referenced by llvm::calculateDbgValueHistory().
static const MachineInstr* getFirstEpilogueInst (const MachineBasicBlock & MBB) static
Definition at line 145 of file DbgValueHistoryCalculator.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getLastNonDebugInstr(), I, and llvm::MachineBasicBlock::rend().
Referenced by collectChangingRegs().
static unsigned isDescribedByReg (const MachineInstr & MI) static
Definition at line 27 of file DbgValueHistoryCalculator.cpp.
References assert(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isDebugValue(), and llvm::MachineOperand::isReg().
Referenced by llvm::calculateDbgValueHistory(), and llvm::DbgValueHistoryMap::getRegisterForVar().