LLVM: DIBuilder.cpp File Reference
LLVM API Documentation
DIBuilder.cpp File Reference
#include "llvm/IR/DIBuilder.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Dwarf.h"
Functions
static bool isUnresolved (MDNode *N)
static MDNode * getNonCompileUnitScope (MDNode *N)
If N is compile unit return NULL otherwise return N.
static MDNode * createFilePathPair (LLVMContext &VMContext, StringRef Filename, StringRef Directory)
static DIImportedEntity createImportedModule (LLVMContext &C, dwarf::Tag Tag, DIScope Context, Metadata *NS, unsigned Line, StringRef Name, SmallVectorImpl< TrackingMDNodeRef > &AllImportedModules)
static Metadata * getConstantOrNull (Constant *C)
static DITemplateValueParameter createTemplateValueParameterHelper (LLVMContext &VMContext, unsigned Tag, DIDescriptor Context, StringRef Name, DIType Ty, Metadata *MD, MDNode *File, unsigned LineNo, unsigned ColumnNo)
static HeaderBuilder setTypeFlagsInHeader (StringRef Header, unsigned FlagsToSet)
static DIType createTypeWithFlags (LLVMContext &Context, DIType Ty, unsigned FlagsToSet)
static DIGlobalVariable createGlobalVariableHelper (LLVMContext &VMContext, DIDescriptor Context, StringRef Name, StringRef LinkageName, DIFile F, unsigned LineNumber, DITypeRef Ty, bool isLocalToUnit, Constant *Val, MDNode *Decl, bool isDefinition, std::function< MDNode *(ArrayRef< Metadata * >)> CreateFunc)
static DISubprogram createFunctionHelper (LLVMContext &VMContext, DIDescriptor Context, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned ScopeLine, unsigned Flags, bool isOptimized, Function *Fn, MDNode *TParams, MDNode *Decl, MDNode *Vars, std::function< MDNode *(ArrayRef< Metadata * >)> CreateFunc)
static Value * getDbgIntrinsicValueImpl (LLVMContext &VMContext, Value *V)
Function Documentation
static MDNode* createFilePathPair (LLVMContext & VMContext, StringRef Filename, StringRef Directory) static
Definition at line 128 of file DIBuilder.cpp.
References assert(), llvm::StringRef::empty(), llvm::MDString::get(), and llvm::MDNode::get().
Referenced by llvm::DIBuilder::createCompileUnit(), and llvm::DIBuilder::createFile().
static DISubprogram createFunctionHelper (LLVMContext & VMContext, DIDescriptor Context, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned ScopeLine, unsigned Flags, bool isOptimized, Function * Fn, MDNode * TParams, MDNode * Decl, MDNode * Vars, std::function< MDNode *(ArrayRef< Metadata * >)> CreateFunc) static
Definition at line 973 of file DIBuilder.cpp.
References assert(), llvm::dwarf::DW_TAG_subprogram, llvm::dwarf::DW_TAG_subroutine_type, getConstantOrNull(), llvm::DIFile::getFileNode(), getNonCompileUnitScope(), llvm::DIScope::getRef(), llvm::DIDescriptor::getTag(), and llvm::DIDescriptor::isSubprogram().
Referenced by llvm::DIBuilder::createFunction(), and llvm::DIBuilder::createTempFunctionFwdDecl().
static DIGlobalVariable createGlobalVariableHelper (LLVMContext & VMContext, DIDescriptor Context, StringRef Name, StringRef LinkageName, DIFile F, unsigned LineNumber, DITypeRef Ty, bool isLocalToUnit, Constant * Val, MDNode * Decl, bool isDefinition, std::function< MDNode *(ArrayRef< Metadata * >)> CreateFunc) static
Definition at line 865 of file DIBuilder.cpp.
References assert(), llvm::dwarf::DW_TAG_variable, F(), getConstantOrNull(), and getNonCompileUnitScope().
Referenced by llvm::DIBuilder::createGlobalVariable(), and llvm::DIBuilder::createTempGlobalVariableFwdDecl().
static DIImportedEntity createImportedModule (LLVMContext & C, dwarf::Tag Tag, DIScope Context, Metadata * NS, unsigned Line, StringRef Name, SmallVectorImpl< TrackingMDNodeRef > & AllImportedModules) static
Definition at line 190 of file DIBuilder.cpp.
References assert(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::emplace_back(), llvm::DIDescriptor::get(), llvm::MDNode::get(), and llvm::DIImportedEntity::Verify().
Referenced by llvm::DIBuilder::createImportedDeclaration(), and llvm::DIBuilder::createImportedModule().
static DITemplateValueParameter createTemplateValueParameterHelper (LLVMContext & VMContext, unsigned Tag, DIDescriptor Context, StringRef Name, DIType Ty, Metadata * MD, MDNode * File, unsigned LineNo, unsigned ColumnNo) static
Definition at line 514 of file DIBuilder.cpp.
References llvm::MDNode::get(), getNonCompileUnitScope(), and llvm::DIScope::getRef().
Referenced by llvm::DIBuilder::createTemplateParameterPack(), llvm::DIBuilder::createTemplateTemplateParameter(), and llvm::DIBuilder::createTemplateValueParameter().
static DIType createTypeWithFlags (LLVMContext & Context, DIType Ty, unsigned FlagsToSet) static
Definition at line 751 of file DIBuilder.cpp.
References assert(), llvm::MDNode::get(), llvm::DIDescriptor::getHeader(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), I, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and setTypeFlagsInHeader().
Referenced by llvm::DIBuilder::createArtificialType(), and llvm::DIBuilder::createObjectPointerType().
static Metadata* getConstantOrNull (Constant * C) static
Definition at line 438 of file DIBuilder.cpp.
References llvm::ConstantAsMetadata::get().
Referenced by createFunctionHelper(), createGlobalVariableHelper(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createStaticMemberType(), and llvm::DIBuilder::createTemplateValueParameter().
static Value* getDbgIntrinsicValueImpl (LLVMContext & VMContext, Value * V) static
Definition at line 1130 of file DIBuilder.cpp.
References assert(), llvm::MetadataAsValue::get(), and llvm::ValueAsMetadata::get().
Referenced by llvm::DIBuilder::insertDbgValueIntrinsic(), and llvm::DIBuilder::insertDeclare().
static MDNode* getNonCompileUnitScope (MDNode * N) static
If N is compile unit return NULL otherwise return N.
Definition at line 122 of file DIBuilder.cpp.
References N.
Referenced by llvm::DIBuilder::createClassType(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createForwardDecl(), createFunctionHelper(), createGlobalVariableHelper(), llvm::DIBuilder::createLexicalBlock(), llvm::DIBuilder::createLocalVariable(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createNameSpace(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createReplaceableForwardDecl(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), and llvm::DIBuilder::createUnionType().
static bool isUnresolved (MDNode * N) static
Definition at line 57 of file DIBuilder.cpp.
References N.
static HeaderBuilder setTypeFlagsInHeader (StringRef Header, unsigned FlagsToSet) static
Definition at line 737 of file DIBuilder.cpp.
References advance(), llvm::StringRef::getAsInteger(), llvm::DIHeaderFieldIterator::getPrefix(), llvm::DIHeaderFieldIterator::getSuffix(), and I.
Referenced by createTypeWithFlags().