LLVM: DIE.cpp File Reference
LLVM API Documentation
DIE.cpp File Reference
#include "llvm/CodeGen/DIE.h"
#include "DwarfCompileUnit.h"
#include "DwarfDebug.h"
#include "DwarfUnit.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MD5.h"
Functions
static void emitLabelOffsetDifference (MCStreamer &Streamer, const MCSymbol *Hi, uint64_t Offset, const MCSymbol *Lo, unsigned Size)
Function Documentation
static void emitLabelOffsetDifference (MCStreamer & Streamer, const MCSymbol * Hi, uint64_t Offset, const MCSymbol * Lo, unsigned Size) static
Emit something like ".long Hi+Offset-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
Definition at line 377 of file DIE.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCBinaryExpr::CreateSub(), llvm::MCContext::CreateTempSymbol(), llvm::MCStreamer::EmitAssignment(), llvm::MCStreamer::EmitSymbolValue(), and llvm::MCStreamer::getContext().
Referenced by llvm::DIEEntry::EmitValue().