LLVM: DWARFDebugInfoEntry.cpp File Reference
LLVM API Documentation
DWARFDebugInfoEntry.cpp File Reference
#include "SyntaxHighlighting.h"
#include "llvm/DebugInfo/DWARFCompileUnit.h"
#include "llvm/DebugInfo/DWARFContext.h"
#include "llvm/DebugInfo/DWARFDebugAbbrev.h"
#include "llvm/DebugInfo/DWARFDebugInfoEntry.h"
#include "llvm/DebugInfo/DWARFFormValue.h"
#include "llvm/Support/DataTypes.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
Functions
static const DWARFUnit * findUnitAndExtractFast (DWARFDebugInfoEntryMinimal &DIE, const DWARFUnit *Unit, uint32_t *Offset)
static void dumpApplePropertyAttribute (raw_ostream &OS, uint64_t Val)
static void dumpRanges (raw_ostream &OS, const DWARFAddressRangesVector &Ranges, unsigned AddressSize, unsigned Indent)
Function Documentation
static void dumpApplePropertyAttribute (raw_ostream & OS, uint64_t Val) static
Definition at line 80 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::ApplePropertyString(), assert(), llvm::tgtok::Bit, llvm::countTrailingZeros(), and llvm::format().
Referenced by llvm::DWARFDebugInfoEntryMinimal::dumpAttribute().
static void dumpRanges (raw_ostream & OS, const DWARFAddressRangesVector & Ranges, unsigned AddressSize, unsigned Indent) static
Definition at line 97 of file DWARFDebugInfoEntry.cpp.
References llvm::format(), and llvm::raw_ostream::indent().
Referenced by llvm::DWARFDebugInfoEntryMinimal::dumpAttribute().
static const DWARFUnit* findUnitAndExtractFast (DWARFDebugInfoEntryMinimal & DIE, const DWARFUnit * Unit, uint32_t * Offset) static
Definition at line 29 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFDebugInfoEntryMinimal::extractFast(), llvm::DWARFUnitSectionBase::getUnitForOffset(), and llvm::DWARFUnit::getUnitSection().
Referenced by llvm::DWARFDebugInfoEntryMinimal::dumpAttribute(), and llvm::DWARFDebugInfoEntryMinimal::getName().