LLVM: DwarfStringPool.cpp File Reference
LLVM API Documentation
DwarfStringPool.cpp File Reference
#include "DwarfStringPool.h"
#include "llvm/MC/MCStreamer.h"
Functions
static std::pair< MCSymbol
*, unsigned > & getEntry (AsmPrinter &Asm, StringMap< std::pair< MCSymbol *, unsigned >, BumpPtrAllocator & > &Pool, StringRef Prefix, StringRef Str)
Function Documentation
static std::pair<MCSymbol *, unsigned>& getEntry (AsmPrinter & Asm, StringMap< std::pair< MCSymbol *, unsigned >, BumpPtrAllocator & > & Pool, StringRef Prefix, StringRef Str) static
Definition at line 16 of file DwarfStringPool.cpp.
References llvm::AsmPrinter::GetTempSymbol().
Referenced by computeIndexValue(), llvm::RegionBase< RegionTr >::contains(), llvm::RegionBase< RegionTr >::getEnteringBlock(), llvm::RegionBase< RegionTr >::getExpandedRegion(), llvm::DwarfStringPool::getIndex(), llvm::RegionBase< RegionTr >::getNameStr(), llvm::RegionNodeBase< Tr >::getNodeAs(), llvm::DwarfStringPool::getSymbol(), llvm::RNSuccIterator< NodeType, BlockT, RegionT >::operator++(), llvm::RegionBase< RegionTr >::replaceEntryRecursive(), and llvm::RegionBase< RegionTr >::verifyRegion().