LLVM: DwarfExpression.cpp File Reference
LLVM API Documentation
DwarfExpression.cpp File Reference
#include "DwarfExpression.h"
#include "DwarfDebug.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Functions
static unsigned getOffsetOrZero (unsigned OffsetInBits, unsigned PieceOffsetInBits)
Function Documentation
static unsigned getOffsetOrZero (unsigned OffsetInBits, unsigned PieceOffsetInBits) static
Definition at line 192 of file DwarfExpression.cpp.
References assert().
Referenced by llvm::DwarfExpression::AddExpression(), and llvm::DwarfExpression::AddMachineRegExpression().