LLVM: DWARFContext.cpp File Reference
LLVM API Documentation
DWARFContext.cpp File Reference
#include "llvm/DebugInfo/DWARFContext.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/DebugInfo/DWARFAcceleratorTable.h"
#include "llvm/DebugInfo/DWARFDebugArangeSet.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "dwarf"
Typedefs
typedef DWARFDebugLine::LineTable DWARFLineTable
typedef
DILineInfoSpecifier::FileLineInfoKind FileLineInfoKind
typedef
DILineInfoSpecifier::FunctionNameKind FunctionNameKind
Functions
static void dumpPubSection (raw_ostream &OS, StringRef Name, StringRef Data, bool LittleEndian, bool GnuStyle)
static void dumpAccelSection (raw_ostream &OS, StringRef Name, const DWARFSection &Section, StringRef StringSection, bool LittleEndian)
static bool getFunctionNameForAddress (DWARFCompileUnit *CU, uint64_t Address, FunctionNameKind Kind, std::string &FunctionName)
static bool consumeCompressedDebugSectionHeader (StringRef &data, uint64_t &OriginalSize)
Macro Definition Documentation
#define DEBUG_TYPE "dwarf"
Definition at line 25 of file DWARFContext.cpp.
Typedef Documentation
typedef DWARFDebugLine::LineTable DWARFLineTable
Definition at line 27 of file DWARFContext.cpp.
typedef DILineInfoSpecifier::FileLineInfoKind FileLineInfoKind
Definition at line 28 of file DWARFContext.cpp.
typedef DILineInfoSpecifier::FunctionNameKind FunctionNameKind
Definition at line 29 of file DWARFContext.cpp.
Function Documentation
static bool consumeCompressedDebugSectionHeader (StringRef & data, uint64_t & OriginalSize) static
Definition at line 524 of file DWARFContext.cpp.
References llvm::DataExtractor::getU64(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory().
static void dumpAccelSection (raw_ostream & OS, StringRef Name, const DWARFSection & Section, StringRef StringSection, bool LittleEndian) static
Definition at line 62 of file DWARFContext.cpp.
References llvm::DWARFSection::Data, llvm::DWARFAcceleratorTable::dump(), llvm::DWARFAcceleratorTable::extract(), and llvm::DWARFSection::Relocs.
Referenced by llvm::DWARFContext::dump().
static void dumpPubSection (raw_ostream & OS, StringRef Name, StringRef Data, bool LittleEndian, bool GnuStyle) static
Definition at line 31 of file DWARFContext.cpp.
References llvm::format(), llvm::dwarf::GDBIndexEntryKindString(), llvm::dwarf::GDBIndexEntryLinkageString(), llvm::DataExtractor::getCStr(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU8(), llvm::DataExtractor::isValidOffset(), and llvm::StringRef::size().
Referenced by llvm::DWARFContext::dump().
static bool getFunctionNameForAddress (DWARFCompileUnit * CU, uint64_t Address, FunctionNameKind Kind, std::string & FunctionName) static
Definition at line 382 of file DWARFContext.cpp.
References llvm::DWARFDebugInfoEntryInlinedChain::DIEs, llvm::DWARFUnit::getInlinedChainForAddress(), llvm::DWARFDebugInfoEntryMinimal::getSubroutineName(), Name, llvm::None, and llvm::DWARFDebugInfoEntryInlinedChain::U.
Referenced by llvm::DWARFContext::getLineInfoForAddress(), and llvm::DWARFContext::getLineInfoForAddressRange().