LLVM: ExecutionEngine.cpp File Reference
LLVM API Documentation
ExecutionEngine.cpp File Reference
#include "llvm/ExecutionEngine/ExecutionEngine.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ExecutionEngine/GenericValue.h"
#include "llvm/ExecutionEngine/JITEventListener.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MutexGuard.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <cmath>
#include <cstring>
Macros
#define DEBUG_TYPE "jit"
Functions
STATISTIC (NumInitBytes,"Number of bytes of global vars initialized")
STATISTIC (NumGlobals,"Number of global vars initialized")
static bool isTargetNullPtr (ExecutionEngine *EE, void *Loc)
isTargetNullPtr - Return whether the target pointer stored at Loc is null.
static void StoreIntToMemory (const APInt &IntVal, uint8_t *Dst, unsigned StoreBytes)
static void LoadIntFromMemory (APInt &IntVal, uint8_t *Src, unsigned LoadBytes)
Macro Definition Documentation
#define DEBUG_TYPE "jit"
Definition at line 40 of file ExecutionEngine.cpp.
Function Documentation
static bool isTargetNullPtr (ExecutionEngine * EE, void * Loc) static
isTargetNullPtr - Return whether the target pointer stored at Loc is null.
Definition at line 340 of file ExecutionEngine.cpp.
References llvm::ExecutionEngine::getDataLayout(), and llvm::DataLayout::getPointerSize().
Referenced by llvm::ExecutionEngine::runFunctionAsMain().
static void LoadIntFromMemory (APInt & IntVal, uint8_t * Src, unsigned LoadBytes) static
LoadIntFromMemory - Loads the integer stored in the LoadBytes bytes starting from Src into IntVal, which is assumed to be wide enough and to hold zero.
Definition at line 1007 of file ExecutionEngine.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::APInt::getRawData(), llvm::sys::IsLittleEndianHost, and llvm::Intrinsic::memcpy.
Referenced by llvm::ExecutionEngine::LoadValueFromMemory().
STATISTIC (NumInitBytes , "Number of bytes of global vars initialized")
STATISTIC (NumGlobals , "Number of global vars initialized")
static void StoreIntToMemory (const APInt & IntVal, uint8_t * Dst, unsigned StoreBytes) static
StoreIntToMemory - Fills the StoreBytes bytes of memory starting from Dst with the integer held in IntVal.
Definition at line 934 of file ExecutionEngine.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::APInt::getRawData(), llvm::sys::IsLittleEndianHost, and llvm::Intrinsic::memcpy.
Referenced by llvm::ExecutionEngine::StoreValueToMemory().