LLVM: ExpandISelPseudos.cpp File Reference
LLVM API Documentation
ExpandISelPseudos.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "expand-isel-pseudos"
Functions
INITIALIZE_PASS (ExpandISelPseudos,"expand-isel-pseudos","Expand ISel Pseudo-instructions", false, false) bool ExpandISelPseudos
Macro Definition Documentation
#define DEBUG_TYPE "expand-isel-pseudos"
Definition at line 25 of file ExpandISelPseudos.cpp.
Function Documentation
INITIALIZE_PASS (ExpandISelPseudos , "expand-isel-pseudos" , "Expand ISel Pseudo-instructions" , false , false)
Definition at line 44 of file ExpandISelPseudos.cpp.
References llvm::MachineBasicBlock::begin(), llvm::TargetLowering::EmitInstrWithCustomInserter(), llvm::MachineBasicBlock::end(), I, llvm::AArch64CC::MI, and llvm::MachineInstr::usesCustomInsertionHook().