LLVM: GlobalMerge.cpp File Reference
LLVM API Documentation
GlobalMerge.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "global-merge"
Functions
STATISTIC (NumMerged,"Number of globals merged")
assert (Globals.size() > 1)
for (size_t i=0, e=Globals.size();i!=e;)
Variables
static cl::opt< bool > EnableGlobalMerge ("enable-global-merge", cl::Hidden, cl::desc("Enable global merge pass"), cl::init(true))
static cl::opt< bool > EnableGlobalMergeOnConst ("global-merge-on-const", cl::Hidden, cl::desc("Enable global merge pass on constants"), cl::init(false))
static cl::opt< bool > EnableGlobalMergeOnExternal ("global-merge-on-external", cl::Hidden, cl::desc("Enable global merge pass on external linkage"), cl::init(false))
INITIALIZE_TM_PASS(GlobalMerge,"global-merge","Merge
global variables", false,
false) bool GlobalMerge const
DataLayout * DL = TLI->getDataLayout()
unsigned MaxOffset = TLI->getMaximalGlobalOffset()
Type * Int32Ty = Type::getInt32Ty(M.getContext())
return true
Macro Definition Documentation
#define DEBUG_TYPE "global-merge"
Definition at line 74 of file GlobalMerge.cpp.
Function Documentation
assert (Globals. size(), 1)
Referenced by llvm::GEPOperator::accumulateConstantOffset(), llvm::sys::MutexImpl::acquire(), llvm::StringTableBuilder::add(), llvm::PMDataManager::add(), llvm::AliasSetTracker::add(), llvm::LiveRangeUpdater::add(), llvm::ImutAVLFactory< ImutInfo >::add_internal(), llvm::StratifiedSetsBuilder< T >::addAbove(), llvm::X86Operand::addAbsMemOperands(), llvm::AttrBuilder::addAlignmentAttr(), llvm::cl::Option::addArgument(), llvm::Argument::addAttr(), llvm::AttrBuilder::addAttribute(), llvm::AttributeSet::addAttributes(), llvm::SSAUpdater::AddAvailableValue(), llvm::DominanceFrontierBase< llvm::MachineBasicBlock >::addBasicBlock(), llvm::LoopBase< N, M >::addBasicBlockToLoop(), llvm::StratifiedSetsBuilder< T >::addBelow(), llvm::sampleprof::FunctionSamples::addBodySamples(), llvm::CallGraphNode::addCalledFunction(), llvm::sampleprof::FunctionSamples::addCalledTargetSamples(), llvm::SwitchInst::addCase(), llvm::AddCatchInfo(), llvm::DIE::addChild(), llvm::LoopBase< BasicBlock, Loop >::addChildLoop(), llvm::RecordKeeper::addClass(), llvm::LandingPadInst::addClause(), AddCombineTo64bitMLAL(), llvm::DwarfCompileUnit::addComplexAddress(), llvm::DwarfUnit::addConstantFPValue(), llvm::DwarfUnit::addConstantValue(), llvm::GCOVBlock::addCount(), llvm::SelectionDAG::AddDbgValue(), llvm::RecordKeeper::addDef(), llvm::IndirectBrInst::addDestination(), llvm::GCOVBlock::addDstEdge(), llvm::X86Operand::addDstIdxOperands(), llvm::PBQP::Graph< RegAllocSolverImpl >::addEdge(), llvm::PBQP::Graph< RegAllocSolverImpl >::addEdgeBypassingCostAllocator(), llvm::AliasAnalysis::addEscapingUse(), llvm::addFullAddress(), llvm::LeakDetectorImpl< llvm::Metadata >::addGarbage(), llvm::ExecutionEngine::addGlobalMapping(), llvm::X86Operand::addGR32orGR64Operands(), llvm::X86Operand::addImmOperands(), llvm::PHINode::addIncoming(), llvm::InstCombineWorklist::AddInitialGroup(), llvm::LiveIntervals::addKillFlags(), llvm::cl::parser< const PassInfo * >::addLiteralOption(), llvm::MachineFunction::addLiveIn(), llvm::MachineBasicBlock::addLiveIn(), addLiveInRegs(), llvm::TargetPassConfig::addMachinePasses(), llvm::X86Operand::addMemOffsOperands(), llvm::X86Operand::addMemOperands(), llvm::MachineInstrBuilder::addMetadata(), llvm::LTOCodeGenerator::addModule(), llvm::Module::addModuleFlag(), llvm::DwarfAccelTable::AddName(), llvm::DominatorTreeBase< BasicBlock >::addNewBlock(), llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::addNodeToList(), llvm::Linker::IdentifiedStructTypeSet::addNonOpaque(), llvm::Linker::IdentifiedStructTypeSet::addOpaque(), llvm::MachineInstr::addOperand(), llvm::DwarfExpression::AddOpPiece(), llvm::TargetPassConfig::addPass(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::SUnit::addPred(), llvm::ScheduleDAGTopologicalSort::AddPred(), llvm::DwarfExpression::AddReg(), llvm::MachineInstrBuilder::addReg(), llvm::LivePhysRegs::addReg(), addRegDescribedVar(), llvm::DwarfExpression::AddRegIndirect(), llvm::TargetLoweringBase::addRegisterClass(), llvm::X86Operand::addRegOperands(), llvm::MachineRegisterInfo::addRegOperandToUseList(), addRequiredExtensionForVectorMULL(), AddRequiredExtensionForVMULL(), llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::ScheduleDAGInstrs::addSchedBarrierDeps(), llvm::DwarfFile::addScopeVariable(), llvm::DwarfUnit::addSourceLine(), llvm::GCOVBlock::addSrcEdge(), llvm::X86Operand::addSrcIdxOperands(), llvm::AttrBuilder::addStackAlignmentAttr(), llvm::FoldingSetNodeID::AddString(), llvm::RegionBase< RegionTr >::addSubRegion(), llvm::Record::addSuperClass(), llvm::MachineOperand::addTargetFlag(), llvm::Record::addTemplateArg(), llvm::BlockFrequencyInfoImplBase::addToDist(), llvm::DominanceFrontierBase< BlockT >::addToFrontier(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::addTopLevelLoop(), llvm::DwarfUnit::addType(), llvm::cl::list_storage< DataType, Storage >::addValue(), llvm::cl::bits_storage< DataType, Storage >::addValue(), llvm::Record::addValue(), llvm::DebugLocEntry::addValues(), llvm::ScheduleDAGInstrs::addVRegUseDeps(), llvm::StratifiedSetsBuilder< T >::addWith(), adjustCostForPairing(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::TargetLowering::AdjustInstrPostInstrSelection(), llvm::IntervalMapImpl::adjustSiblingSizes(), adjustSubwordCmp(), llvm::MCRegisterInfo::DiffListIterator::advance(), llvm::RegPressureTracker::advance(), llvm::PPCHazardRecognizer970::AdvanceCycle(), llvm::SmallPtrSetIteratorImpl::AdvanceIfNotValid(), llvm::LiveRange::advanceTo(), llvm::AliasAnalysis::alias(), llvm::AliasSet::aliasesPointer(), llvm::OutputBuffer::align(), llvm::alignAddr(), AllCallersPassInValidPointerForArgument(), llvm::AllocaInst::AllocaInst(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::RegAllocBase::allocatePhysRegs(), llvm::Hexagon_CCState::AllocateStack(), llvm::CCState::AllocateStack(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::AllocationOrder::AllocationOrder(), allocset(), llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::ForwardDominanceFrontierBase< llvm::MachineBasicBlock >::analyze(), llvm::MSP430InstrInfo::AnalyzeBranch(), llvm::ARMBaseInstrInfo::AnalyzeBranch(), llvm::SystemZInstrInfo::AnalyzeBranch(), llvm::X86InstrInfo::AnalyzeBranch(), llvm::SystemZInstrInfo::analyzeCompare(), analyzeGlobalAux(), llvm::BlockFrequencyInfoImplBase::analyzeIrreducible(), llvm::MachineOperandIteratorBase::analyzePhysReg(), llvm::ARMBaseInstrInfo::analyzeSelect(), llvm::TargetInstrInfo::analyzeSelect(), llvm::APInt::APInt(), APIntToHexString(), llvm::LiveRange::append(), appendDigit(), AppendMDNodeToSourcePtr(), llvm::PBQP::applyR1(), llvm::PBQP::applyR2(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfUnit::applySubprogramDefinitionAttributes(), areCombinableOperations(), llvm::SIInstrInfo::areLoadsFromSameBasePtr(), llvm::AArch64InstrInfo::areMemAccessesTriviallyDisjoint(), llvm::SIInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::TargetInstrInfo::areMemAccessesTriviallyDisjoint(), areSlicesNextToEachOther(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_begin(), llvm::ARMBaseInstrInfo::ARMBaseInstrInfo(), llvm::APInt::ashr(), AssertSorted(), llvm::LiveRegMatrix::assign(), llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::BasicBlockPass::assignPassManager(), llvm::SelectionDAG::AssignTopologicalOrder(), llvm::VirtRegMap::assignVirt2Phys(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::AtomicSDNode::AtomicSDNode(), llvm::DwarfCompileUnit::attachLowHighPC(), llvm::AttributeSetImpl::AttributeSetImpl(), llvm::SetVector< llvm::BasicBlock * >::back(), llvm::StringRef::back(), llvm::ArrayRef< uint64_t >::back(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::back(), llvm::TinyPtrVector< EltTy >::back(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::back(), llvm::iplist< Argument >::back(), llvm::ImutAVLFactory< ImutInfo >::balanceTree(), llvm::RecTy::baseClassOf(), llvm::PooledStringPtr::begin(), llvm::LoopBlocksTraversal::begin(), llvm::yaml::begin(), llvm::MCWinCOFFStreamer::BeginCOFFSymbolDef(), llvm::ARMException::beginFunction(), llvm::WinCodeViewLineTables::beginFunction(), llvm::DwarfDebug::beginFunction(), llvm::LiveRange::beginIndex(), llvm::DwarfDebug::beginInstruction(), llvm::LoopBlocksDFS::beginPostorder(), llvm::LoopBlocksDFS::beginRPO(), llvm::BitCastInst::BitCastInst(), llvm::APFloat::bitcastToAPInt(), llvm::yaml::ScalarBitSetTraits< ELFYAML::ELF_EF >::bitset(), llvm::yaml::ScalarBitSetTraits< ELFYAML::ELF_STO >::bitset(), bothcases(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::branched(), llvm::BranchProbability::BranchProbability(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::TargetLowering::BuildExactSDIV(), buildExtractionBlockSet(), buildFixItLine(), buildGraphFrom(), llvm::BuildMI(), BuildNew(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::TargetLowering::BuildSDIV(), buildSetsFrom(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), BuildSplatI(), BuildSubAggregate(), llvm::TargetLowering::BuildUDIV(), llvm::SchedBoundary::bumpCycle(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::SchedBoundary::bumpNode(), llvm::RegPressureTracker::bumpUpwardPressure(), llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::bundle_iterator(), llvm::MachineInstr::bundleWithPred(), llvm::MachineInstr::bundleWithSucc(), BURRSort(), llvm::APInt::byteSwap(), llvm::ARM::WinEH::RuntimeFunction::C(), cacheAnnotationFromMD(), llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), llvm::Calculate(), llvm::LiveRangeCalc::calculate(), llvm::calculateDbgValueHistory(), llvm::R600InstrInfo::calculateIndirectAddress(), llvm::SIInstrInfo::calculateIndirectAddress(), calculateMMLEIndex(), llvm::LiveRangeCalc::calculateValues(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::call_args_begin(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::call_args_end(), callClobbersAnyYmmReg(), llvm::Interpreter::callFunction(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::CallSiteBase(), llvm::EHStreamer::callToNoUnwindFunction(), llvm::objcarc::CanAlterRefCount(), canClobberPhysRegDefs(), llvm::ARMTargetLowering::canCombineStoreAndExtract(), canCombineWithMUL(), CanEvaluateSExtd(), canFoldCopy(), canFoldIntoCSel(), llvm::AliasAnalysis::canInstructionRangeModRef(), canLowerByDroppingEvenElements(), llvm::TargetLoweringBase::canOpTrap(), CanPropagatePredecessorsForPHIs(), llvm::LiveRangeEdit::canRematerializeAt(), canTrapImpl(), canWidenShuffleElements(), llvm::cast(), llvm::cast_or_null(), llvm::CC_ARM_AAPCS_Custom_HA(), CC_Hexagon(), CC_Hexagon_VarArg(), CC_Sparc64_Full(), CC_Sparc64_Half(), CC_Sparc_Assign_SRet(), llvm::DominatorTreeBase< BasicBlock >::changeImmediateDominator(), llvm::MCObjectStreamer::ChangeSection(), llvm::MachineOperand::ChangeToFPImmediate(), llvm::MachineOperand::ChangeToImmediate(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::changeTopLevelLoop(), llvm::EVT::changeVectorElementTypeToInteger(), checkBoolTestSetCCCombine(), llvm::checkForCycles(), llvm::checkGEPType(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::LiveRangeEdit::checkRematerializable(), checkRippleForAdd(), CheckSame(), checkType(), ChooseConstraint(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::X86Subtarget::ClassifyGlobalReference(), llvm::cleanseInlinedVariable(), llvm::FPPassManager::cleanup(), llvm::StatepointLoweringState::clear(), llvm::BitcodeReaderValueList::clear(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::FunctionLoweringInfo::clear(), llvm::VirtRegMap::clearVirt(), llvm::MachineOperand::clobbersPhysReg(), llvm::UnOpInit::clone(), llvm::BinOpInit::clone(), llvm::TernOpInit::clone(), llvm::CloneAndPruneFunctionInto(), llvm::CloneFunctionInto(), cloneMDTuple(), llvm::raw_fd_ostream::close(), llvm::RegPressureTracker::closeBottom(), llvm::LexicalScope::closeInsnRange(), llvm::RegPressureTracker::closeRegion(), llvm::RegPressureTracker::closeTop(), coalescable(), CoerceAvailableValueToLoadType(), llvm::DwarfCompileUnit::collectDeadVariables(), llvm::CodeMetrics::collectEphemeralValues(), collectFailStats(), CollectInsertionElements(), llvm::LiveIntervalUnion::Query::collectInterferingVRegs(), collectInvolvedReg(), collectPDiff(), CollectShuffleElements(), CollectSingleShuffleElements(), combineRedundantDWordShuffle(), combineRedundantHalfShuffle(), combineRestoreSETHIi(), combineShuffleToAddSub(), combineWeight(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), CommitValueTo(), llvm::InstCombiner::commonPointerCastTransforms(), llvm::InstCombiner::commonShiftTransforms(), llvm::SIInstrInfo::commuteInstruction(), llvm::PPCInstrInfo::commuteInstruction(), llvm::TargetInstrInfo::commuteInstruction(), CompactSwizzlableVector(), llvm::APFloat::compare(), llvm::ScaledNumbers::compareImpl(), llvm::EHStreamer::computeActionsTable(), computeADRP(), llvm::ComputeASanStackFrameLayout(), llvm::EHStreamer::computeCallSiteTable(), llvm::TargetLowering::ComputeConstraintToUse(), llvm::TargetSchedModel::computeInstrLatency(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), llvm::computeKnownBitsFromRangeMetadata(), llvm::ComputeLinearIndex(), llvm::ComputeMultiple(), ComputeNumSignBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::TargetInstrInfo::computeOperandLatency(), computeOthers(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::TargetLoweringBase::computeRegisterProperties(), ComputeSignedMinMaxValuesFromKnownBits(), llvm::DwarfFile::computeSizeAndOffset(), ComputeSpeculationCost(), llvm::MachObjectWriter::ComputeSymbolTable(), computeTargetABI(), ComputeUnsignedMinMaxValuesFromKnownBits(), concatenateMemOperands(), ConnectProlog(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantArray::ConstantArray(), llvm::ConstantExprKeyType::ConstantExprKeyType(), llvm::ConstantFoldBinaryInstruction(), ConstantFoldConvertToInt(), ConstantFoldGetElementPtrImpl(), ConstantFoldScalarCall(), llvm::ConstantFoldTerminator(), llvm::ConstantFP::ConstantFP(), llvm::ConstantRange::ConstantRange(), llvm::ConstantStruct::ConstantStruct(), llvm::ConstantVector::ConstantVector(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::LiveInterval::constructMainRangeFromSubranges(), llvm::DwarfCompileUnit::constructScopeDIE(), ConstructSSAForLoadSet(), llvm::DwarfUnit::constructSubprogramArguments(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), llvm::AttrBuilder::contains(), llvm::LiveRange::Segment::containsInterval(), llvm::ConvertDebugDeclareToDebugValue(), llvm::APFloat::convertFromString(), convertLocVTToValVT(), ConvertSelectToConcatVector(), llvm::APFloat::convertToDouble(), llvm::APFloat::convertToFloat(), llvm::X86InstrInfo::convertToThreeAddress(), ConvertTwoCaseSwitch(), llvm::convertUTF16ToUTF8String(), llvm::ConvertUTF8toWide(), convertValue(), llvm::IntervalMapImpl::NodeBase< std::pair< KeyT, KeyT >, ValT, N >::copy(), llvm::GlobalVariable::copyAttributesFrom(), llvm::Function::copyAttributesFrom(), llvm::Instruction::copyFastMathFlags(), llvm::SmallPtrSetImplBase::CopyFrom(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::AliasSetTracker::copyValue(), llvm::AliasAnalysis::copyValue(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::DILocation::copyWithNewScope(), llvm::MachineBasicBlock::CorrectExtraCFGEdges(), llvm::SchedBoundary::countResource(), llvm::MCFixup::Create(), llvm::BinaryOperator::Create(), llvm::StructType::create(), llvm::OnDiskChainedHashTable< Info >::Create(), llvm::CastInst::Create(), llvm::OnDiskIterableChainedHashTable< Info >::Create(), llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), createAArch64MCCodeGenInfo(), llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption(), llvm::DwarfUnit::createAndAddDIE(), llvm::createARMAsmBackend(), llvm::IRBuilderBase::CreateAssumption(), llvm::DIBuilder::createBasicType(), llvm::MDBuilder::createBranchWeights(), createCast(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCompileUnit(), llvm::LiveRange::createDeadDef(), llvm::LiveRangeCalc::createDeadDefs(), llvm::createDefaultScheduler(), llvm::LiveIntervals::createEmptyInterval(), llvm::DIBuilder::createEnumerator(), llvm::IRBuilder< true, TargetFolder >::CreateExtractInteger(), createFilePathPair(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::DIBuilder::createForwardDecl(), llvm::CastInst::CreateFPCast(), llvm::MDBuilder::createFPMath(), createFree(), llvm::CallInst::CreateFree(), llvm::DIBuilder::createFriend(), createFunctionHelper(), llvm::IRBuilderBase::CreateGCStatepoint(), createGlobalVariableHelper(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::createInlinedVariable(), createInstructionShuffler(), llvm::CastInst::CreateIntegerCast(), llvm::MachineJumpTableInfo::createJumpTableIndex(), llvm::DIBuilder::createLexicalBlock(), llvm::DIBuilder::createLexicalBlockFile(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::DIBuilder::createLocalVariable(), createMalloc(), llvm::IRBuilderBase::CreateMaskedLoad(), createMCStreamer(), llvm::createMCSymbolizer(), llvm::X86Operand::CreateMem(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createNameSpace(), llvm::ImutAVLFactory< ImutInfo >::createNode(), llvm::PassInfo::createPass(), createPHIsForSplitLoopExit(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerCast(), llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff(), llvm::MDBuilder::createRange(), llvm::DIBuilder::createReferenceType(), llvm::MachineOperand::CreateReg(), llvm::MachineOperand::CreateRegLiveOut(), llvm::MachineOperand::CreateRegMask(), llvm::DIBuilder::createReplaceableForwardDecl(), llvm::IRBuilder< true, TargetFolder >::CreateSExtOrTrunc(), llvm::MachineFrameInfo::CreateStackObject(), llvm::DIBuilder::createStructType(), llvm::PPCInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::sys::fs::createTemporaryFile(), createTypeWithFlags(), llvm::DIBuilder::createUnspecifiedType(), llvm::IRBuilder< true, TargetFolder >::CreateVectorSplat(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::IRBuilder< true, TargetFolder >::CreateZExtOrTrunc(), llvm::StringTableBuilder::data(), llvm::DbgVariable::DbgVariable(), llvm::RuntimeDyldMachOAArch64::decodeAddend(), DecodeANDI16Imm(), decodeBase64StringEntry(), decodeBDAddr12Operand(), decodeBDAddr20Operand(), decodeBDLAddr12Len8Operand(), decodeBDXAddr12Operand(), decodeBDXAddr20Operand(), llvm::DecodeBLENDMask(), llvm::BitCodeAbbrevOp::DecodeChar6(), decodeCRBitMOperand(), DecodeFixedType(), DecodeINSVE_DF(), decodeLLVMAttributesForBitcode(), llvm::AArch64_AM::decodeLogicalImmediate(), decodeMemRIOperands(), decodeMemRIXOperands(), DecodeMSA128Mem(), decodePCDBLOperand(), decodeRegisterClass(), decodeSImmOperand(), decodeUImmOperand(), llvm::DecodeVPERMILPMask(), decreaseSetPressure(), llvm::DeleteDeadBlock(), llvm::MachineFunction::DeleteMachineBasicBlock(), llvm::AliasAnalysis::deleteValue(), llvm::BitcodeReader::Dematerialize(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::DISubprogram::describes(), llvm::ManagedStaticBase::destroy(), llvm::SpecificBumpPtrAllocator< llvm::LazyCallGraph::SCC >::DestroyAll(), llvm::ConstantDataSequential::destroyConstant(), llvm::Constant::destroyConstantImpl(), determineMissingVNIs(), determinePointerReadAttrs(), llvm::PBQP::Matrix::diagonalize(), llvm::RegPressureTracker::discoverLiveIn(), llvm::RegPressureTracker::discoverLiveOut(), llvm::IntervalMapImpl::distribute(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::ScaledNumbers::divide32(), llvm::ScaledNumbers::divide64(), doemit(), llvm::AsmPrinter::doFinalization(), dofwd(), llvm::AsmPrinter::doInitialization(), doinsert(), llvm::isa_impl_cl< To, From * >::doit(), llvm::isa_impl_cl< To, From *const >::doit(), llvm::isa_impl_cl< To, const From * >::doit(), llvm::isa_impl_cl< To, const From *const >::doit(), llvm::Trace::dominates(), llvm::DominatorTree::dominates(), llvm::DominatorTreeBase< BasicBlock >::dominates(), llvm::InstCombiner::dominatesAllUses(), llvm::ArrayRef< uint64_t >::drop_back(), llvm::StringRef::drop_back(), llvm::StringRef::drop_front(), dropRegDescribedVar(), llvm::Instruction::dropUnknownMetadata(), llvm::DWARFCompileUnit::dump(), llvm::DWARFTypeUnit::dump(), dumpApplePropertyAttribute(), llvm::PMTopLevelManager::dumpArguments(), llvm::PBQP::Graph< RegAllocSolverImpl >::dumpToStream(), dupl(), llvm::TargetInstrInfo::duplicate(), duplicateCPV(), llvm::DwarfUnit::DwarfUnit(), EatNumber(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::SystemZFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), EliminateDeadSwitchCases(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::BitstreamWriter::Emit(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCGenDwarfInfo::Emit(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::AsmPrinter::EmitAlignment(), llvm::emitARMRegPlusImmediate(), emitBasicBlockLoopComments(), llvm::MCELFStreamer::EmitBundleAlignMode(), llvm::MCStreamer::EmitCFISections(), EmitCMP(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), EmitDarwinBCHeaderAndTrailer(), llvm::InstrEmitter::EmitDbgValue(), llvm::DwarfDebug::emitDebugLocEntry(), emitDebugValueComment(), llvm::DwarfDebug::emitDIE(), llvm::AsmPrinter::EmitDwarfRegOpPiece(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::LLVMContext::emitError(), llvm::emitFrameOffset(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), emitGlobalConstantDataSequential(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), llvm::ExecutionEngine::emitGlobals(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::MCStreamer::EmitIntValue(), emitKill(), llvm::MCWinCOFFStreamer::EmitLabel(), llvm::MCELFStreamer::EmitLabel(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCStreamer::EmitLabel(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::DwarfDebug::emitLocPieces(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), EmitNops(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostLd(), emitPostSt(), llvm::HexagonFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::AsmPrinter::EmitSectionOffset(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::StringToOffsetTable::EmitString(), llvm::MCWinCOFFStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitSymbolValue(), llvm::emitT2RegPlusImmediate(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::EmitUnwindInfo(), llvm::DIEEntry::EmitValue(), llvm::DIETypeSignature::EmitValue(), llvm::BitstreamWriter::EmitVBR(), llvm::BitstreamWriter::EmitVBR64(), EmitVectorComparison(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::MCObjectStreamer::EmitZeros(), llvm::AnalysisManager< IRUnitT >::empty(), llvm::PPCTargetLowering::enableAggressiveFMAFusion(), llvm::encode_leb128(), llvm::RuntimeDyldMachOAArch64::encodeAddend(), llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc(), encodeBase64StringEntry(), encodeCounter(), llvm::HexagonMCCodeEmitter::EncodeInstruction(), llvm::AArch64_AM::encodeLogicalImmediate(), encodeMemSDNodeFlags(), llvm::ARM_AM::encodeNEONi16splat(), llvm::ARM_AM::encodeNEONi32splat(), llvm::PooledStringPtr::end(), llvm::WinCodeViewLineTables::endFunction(), llvm::DwarfDebug::endFunction(), llvm::LiveRange::endIndex(), llvm::DbgValueHistoryMap::endInstrRange(), llvm::DwarfDebug::endInstruction(), llvm::WinCodeViewLineTables::endModule(), llvm::DwarfDebug::endModule(), llvm::MachineFrameInfo::ensureMaxAlignment(), llvm::RegScavenger::enterBasicBlock(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvAtEnd(), llvm::SplitEditor::enterIntvBefore(), llvm::ScheduleDAGInstrs::enterRegion(), llvm::yaml::ScalarEnumerationTraits< ELFYAML::ELF_SHT >::enumeration(), llvm::yaml::ScalarEnumerationTraits< ELFYAML::ELF_REL >::enumeration(), llvm::ARM::WinEH::ExceptionDataRecord::EpilogueScopes(), llvm::MapVector< const MCSection *, ConstantPool >::erase(), llvm::TinyPtrVector< EltTy >::erase(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::erase(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::erase(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::MachineInstr::eraseFromBundle(), llvm::MachineBasicBlock::eraseFromParent(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::eraseFromParentAndMarkDBGValuesForRemoval(), llvm::InstCombiner::EraseInstFromFunction(), llvm::objcarc::EraseInstruction(), llvm::DominatorTreeBase< BasicBlock >::eraseNode(), llvm::MipsFrameLowering::estimateStackSize(), EvaluateConstantChrecAtConstant(), evaluateFCmpRelation(), evaluateICmpRelation(), EvaluateStoreInto(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerParameter(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerRVA(), llvm::ARM::WinEH::RuntimeFunction::ExceptionInformationRVA(), ExecGraphViewer(), executeFCMP_BOOL(), executeFCMP_ORD(), executeFCMP_UNO(), executeSelectInst(), llvm::ExecutionEngine::ExecutionEngine(), llvm::BitstreamWriter::ExitBlock(), Expand2AddrUndef(), Expand64BitShift(), ExpandBITCAST(), ExpandBVWithShuffles(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), ExpandHorizontalBinOp(), llvm::TargetLowering::expandMUL(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::LiveRangeCalc::extend(), llvm::LexicalScope::extendInsnRange(), extendSegmentsToUses(), llvm::LiveIntervals::extendToIndices(), llvm::DWARFDebugArangeSet::extract(), llvm::LiveIntervalUnion::extract(), Extract128BitVector(), Extract256BitVector(), ExtractBranchMetadata(), ExtractConstantBytes(), llvm::DWARFDebugInfoEntryMinimal::extractFast(), extractInteger(), extractMDNode(), llvm::DWARFUnit::extractRangeList(), ExtractSubVector(), llvm::ExtractTypeInfo(), extractVector(), llvm::f64AssignAAPCS(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::FCmpInst::FCmpInst(), llvm::BitstreamCursor::fillCurWord(), llvm::StringTableBuilder::finalize(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::SchedDFSImpl::finalize(), llvm::finalizeBundles(), llvm::MCContext::finalizeDwarfSections(), llvm::MCJIT::finalizeModule(), llvm::SparseBitVectorElement< ElementSize >::find_next(), llvm::PMTopLevelManager::findAnalysisPass(), llvm::PMTopLevelManager::findAnalysisPassInfo(), FindCallSeqStart(), findChainOperand(), llvm::TargetInstrInfo::findCommutedOpIndices(), FindFirstNonCommonLetter(), llvm::IntervalMapImpl::LeafNode< typename, typename, unsigned, typename >::findFrom(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, RootBranchCap, Traits >::findFrom(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::findIndex(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::findIndex(), llvm::MachineInstr::findInlineAsmFlagIdx(), llvm::FindInsertedValue(), findIrreducibleHeaders(), llvm::IntEqClasses::findLeader(), FindLoopCounter(), findMaximalSubpartOfIllFormedUTF8Sequence(), llvm::SelectionDAGBuilder::FindMergedConditions(), FindMostPopularDest(), findmust(), llvm::DominatorTreeBase< BasicBlock >::findNearestCommonDominator(), findNonImmUse(), FindOptimalMemOpLowering(), FindPHIForConditionForwarding(), findPrologueEndLoc(), llvm::ScheduleDAGMI::findRootsAndBiasEdges(), FindScalarElement(), llvm::MachineInstr::findTiedOperandIdx(), llvm::SpillPlacement::finish(), llvm::SplitEditor::finish(), llvm::LoopBlocksTraversal::finishPostorder(), firstch(), llvm::R600InstrInfo::fitsConstReadLimitations(), llvm::ARMFrameLowering::fixTCReturn(), fixupVariableFloatArgs(), llvm::APInt::flipBit(), llvm::LiveRangeUpdater::flush(), llvm::UnOpInit::Fold(), llvm::InstCombiner::FoldAndOfICmps(), FoldBitCast(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::SelectionDAG::FoldConstantArithmetic(), foldConstantCastPair(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::InstCombiner::foldFMulConst(), llvm::InstCombiner::FoldICmpAddOpCst(), llvm::InstCombiner::FoldICmpCstShlCst(), llvm::InstCombiner::FoldICmpCstShrCst(), llvm::InstCombiner::FoldICmpShrCst(), llvm::PPCInstrInfo::FoldImmediate(), foldImmediates(), llvm::FoldingSetImpl::FoldingSetImpl(), foldLogOpOfMaskedICmps(), FoldMaskAndShiftToScale(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), FoldOperand(), llvm::InstCombiner::FoldOrOfICmps(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldShiftByConstant(), forceExpAbs(), forceRenaming(), llvm::format_hex(), llvm::formLCSSA(), llvm::RegScavenger::forward(), llvm::FPExtInst::FPExtInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPTruncInst::FPTruncInst(), llvm::BitcodeReader::FreeState(), llvm::MachineRegisterInfo::freezeReservedRegs(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::fromSuccessorIndex(), llvm::StringRef::front(), llvm::ArrayRef< uint64_t >::front(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::front(), llvm::TinyPtrVector< EltTy >::front(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::front(), llvm::iplist< Argument >::front(), llvm::ARM::WinEH::RuntimeFunction::FunctionLength(), FuseInst(), llvm::GCRelocateOperands::GCRelocateOperands(), llvm::MCJIT::generateCodeForModule(), GeneratePerfectShuffle(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), genLoopLimit(), genMadd(), genMaddR(), llvm::MCInstrInfo::get(), llvm::IntegerType::get(), llvm::MCValue::get(), llvm::InlineCost::get(), llvm::LayoutAlignElem::get(), llvm::objcarc::ARCRuntimeEntryPoints::get(), llvm::ConstantInt::get(), llvm::PointerAlignElem::get(), llvm::OptionRegistry::get(), llvm::PointerUnion< const Value *, const PseudoSourceValue * >::get(), llvm::ValueAsMetadata::get(), llvm::StructType::get(), llvm::ConstantFP::get(), llvm::PointerUnion3< PT1, PT2, PT3 >::get(), llvm::ConstantAggregateZero::get(), llvm::ArrayType::get(), llvm::VectorType::get(), llvm::ConstantStruct::get(), llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::get(), llvm::MDString::get(), llvm::PointerType::get(), llvm::BlockAddress::get(), llvm::ConstantExpr::get(), get64BitArgumentGPRs(), get64BitArgumentXMMs(), llvm::PPC::get_VSPLTI_elt(), getAArch64XALUOOp(), llvm::BitstreamCursor::getAbbrev(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::MipsTargetLowering::getAddrGPRel(), llvm::MMIAddrLabelMap::getAddrLabelSymbol(), llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit(), llvm::PointerIntPair< void *, 1, bool, PointerUnionUIntTraits< const Value *, const PseudoSourceValue * > >::getAddrOfPointer(), llvm::PointerUnion< const Value *, const PseudoSourceValue * >::getAddrOfPtr1(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::SparcSubtarget::getAdjustedFrameSize(), getAdjustedPtr(), GetAEABIUnwindPersonalityName(), llvm::Constant::getAggregateElement(), getAISize(), llvm::opt::Option::getAlias(), llvm::opt::Option::getAliasArgs(), llvm::Attribute::getAlignment(), getAllocatableSetForRC(), llvm::ARM_AM::getAM2Opc(), llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisID(), llvm::Pass::getAnalysisIfAvailable(), llvm::ScalarEvolution::getAnyExtendExpr(), llvm::SelectionDAG::getAnyExtendVectorInReg(), llvm::AsmToken::getAPIntVal(), llvm::DagInit::getArg(), llvm::AliasAnalysis::getArgLocation(), llvm::DagInit::getArgName(), llvm::Argument::getArgNo(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo(), llvm::AArch64_AM::getArithExtendImm(), getARMIndexedAddressParts(), getARMLoadDeprecationInfo(), getARMStoreDeprecationInfo(), llvm::ConstantDataSequential::getAsCString(), llvm::ConstantExpr::getAsInstruction(), llvm::StringRef::getAsInteger(), getAsmSymIndex(), llvm::ConstantDataSequential::getAsString(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getAtomicCmpSwap(), llvm::StratifiedSetsBuilder< T >::getAttribute(), llvm::ValueEnumerator::getAttributeGroupID(), llvm::ValueEnumerator::getAttributeID(), llvm::StratifiedSetsBuilder< T >::getAttributes(), llvm::CrashRecoveryContext::getBacktrace(), getBaseTypeSize(), llvm::RegionBase< RegionTr >::getBBNode(), llvm::MCELF::GetBinding(), llvm::BitInit::getBit(), llvm::BitsInit::getBit(), llvm::VarBitInit::getBit(), llvm::ConstantExpr::getBitCast(), llvm::APInt::getBitsNeeded(), llvm::APInt::getBitsSet(), llvm::MachineOperand::getBlockAddress(), llvm::bfi_detail::getBlockName(), llvm::MachineFunction::getBlockNumbered(), getBranchTargetOpValue(), GetBranchWeights(), GetBucketPtr(), llvm::SourceMgr::getBufferInfo(), getBundledDefMI(), getBundledUseMI(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::getCachedResult(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCalledValue(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::MachineModuleInfo::getCallSiteBeginLabel(), llvm::MachineModuleInfo::getCallSiteLandingPad(), llvm::Loop::getCanonicalInductionVariable(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::getCaseSuccessor(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::getCaseValue(), llvm::ConstantExpr::getCast(), llvm::CastInst::getCastOpcode(), llvm::AMDGPURegisterInfo::getCFGStructurizerRegClass(), llvm::MachineOperand::getCFIIndex(), getChunk(), llvm::MachineOperand::getCImm(), llvm::DIDerivedType::getClassType(), getClearedMemory(), llvm::MemDepResult::getClobber(), llvm::X86::getCMovFromCond(), llvm::PBQP::Matrix::getColAsVector(), llvm::PBQP::Matrix::getColMin(), llvm::PBQP::Matrix::getCols(), getComdatGVForCOFF(), llvm::ValueEnumerator::getComdatID(), llvm::MCSymbolData::getCommonAlignment(), llvm::RegionInfoBase< RegionTr >::getCommonRegion(), llvm::MCSymbolData::getCommonSize(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), llvm::ConstantExpr::getCompare(), getConcreteOpcode(), llvm::TargetLoweringBase::getCondCodeAction(), llvm::BranchInst::getCondition(), llvm::SDDbgValue::getConst(), llvm::SelectionDAG::getConstant(), llvm::DIDerivedType::getConstant(), llvm::SelectionDAG::getConstantFP(), getConstantFromPool(), llvm::BitcodeReaderValueList::getConstantFwdRef(), llvm::SDNode::getConstantOperandVal(), llvm::SelectionDAG::getConstantPool(), llvm::MachineConstantPool::getConstantPoolIndex(), llvm::getConstantStringInfo(), llvm::ExecutionEngine::getConstantValue(), llvm::ConstantPoolSDNode::getConstVal(), llvm::legacy::FunctionPassManagerImpl::getContainedManager(), llvm::legacy::PassManagerImpl::getContainedManager(), llvm::RGPassManager::getContainedPass(), llvm::LPPassManager::getContainedPass(), llvm::FPPassManager::getContainedPass(), llvm::Type::getContainedType(), llvm::DIScope::getContext(), llvm::SelectionDAGBuilder::getControlRoot(), getCopyFromParts(), getCopyFromPartsVector(), getCopyToParts(), getCopyToPartsVector(), getCorrespondingDRegAndLane(), llvm::InlineCost::getCost(), getCRFromCRBit(), llvm::TGLexer::getCurBinaryIntVal(), llvm::TGLexer::getCurIntVal(), llvm::MCObjectStreamer::getCurrentFragment(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::TGLexer::getCurStrVal(), llvm::object::COFFObjectFile::getDataDirectory(), getDbgIntrinsicValueImpl(), llvm::MachineInstr::getDebugExpression(), getDebugLocValue(), llvm::MachineInstr::getDebugVariable(), llvm::MemDepResult::getDef(), llvm::Argument::getDereferenceableBytes(), llvm::Attribute::getDereferenceableBytes(), getDIEStringAttr(), llvm::FullDependence::getDirection(), llvm::FullDependence::getDistance(), llvm::HexagonInstrInfo::GetDotOldOp(), GetDSubRegs(), getDwarfRegNum(), getEdgeValueLocal(), llvm::ScalarEvolution::getEffectiveSCEVType(), GetEHSpillList(), llvm::XCoreFunctionInfo::getEHSpillSlot(), llvm::ListInit::getElement(), llvm::DIExpression::getElement(), llvm::ConstantDataSequential::getElementAsDouble(), llvm::ConstantDataSequential::getElementAsFloat(), llvm::ConstantDataSequential::getElementAsInteger(), llvm::ListInit::getElementAsRecord(), llvm::StructLayout::getElementContainingOffset(), llvm::StructLayout::getElementOffset(), llvm::DICompositeType::getElements(), llvm::StructType::getElementType(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MachineTraceMetrics::getEnsemble(), llvm::BlockFrequencyInfoImplBase::getEntryFreq(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), llvm::APFloat::getExactInverse(), llvm::MCOperand::getExpr(), llvm::AArch64_AM::getExtendType(), getExtendTypeForNode(), getExtensionTo64Bits(), llvm::ConstantExpr::getExtractElement(), llvm::TargetInstrInfo::getExtractSubregInputs(), llvm::ARMBaseInstrInfo::getExtractSubregLikeInputs(), llvm::ConstantExpr::getExtractValue(), getExtractVEXTRACTImmediate(), llvm::ConstantInt::getFalse(), getFalse(), llvm::Instruction::getFastMathFlags(), llvm::ConstantExpr::getFCmp(), llvm::SubtargetFeatures::getFeatureBits(), llvm::VarInit::getFieldInit(), llvm::MCDwarfLineTableHeader::getFile(), llvm::jitprofiling::FilenameCache::getFilename(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::SystemZMC::getFirstReg(), llvm::MipsAsmBackend::getFixupKindInfo(), llvm::MCAsmBackend::getFixupKindInfo(), llvm::R600InstrInfo::getFlagOp(), llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMatchingOp(), llvm::InlineAsm::getFlagWordForRegClass(), llvm::ConstantExpr::getFNeg(), llvm::MachineModuleInfoMachO::getFnStubEntry(), getFoldedCast(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::MCOperand::getFPImm(), llvm::MachineOperand::getFPImm(), llvm::Type::getFPMantissaWidth(), getFPReg(), llvm::XCoreFunctionInfo::getFPSpillSlot(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getFPTrunc(), llvm::MCAsmLayout::getFragmentOffset(), llvm::DIInliningInfo::getFrame(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), getFrameIndexOperandNum(), llvm::X86FrameLowering::getFrameIndexReferenceFromSP(), llvm::SDDbgValue::getFrameIx(), llvm::X86AddressMode::getFullAddress(), llvm::jitprofiling::FilenameCache::getFullPath(), llvm::GCModuleInfo::getFunctionInfo(), getFusedLdStOpcode(), getGatherNode(), llvm::Function::getGC(), llvm::ConstantExpr::getGetElementPtr(), llvm::MachineOperand::getGlobal(), llvm::SelectionDAG::getGlobalAddress(), llvm::X86InstrInfo::getGlobalBaseReg(), llvm::opt::Option::getGroup(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfoELF::getGVStubEntry(), llvm::VectorType::getHalfElementsVectorType(), llvm::EVT::getHalfSizedIntegerVT(), llvm::ARMHazardRecognizer::getHazardType(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::ImmutableList< T >::getHead(), getHexDigit(), llvm::MachineModuleInfoMachO::getHiddenGVStubEntry(), llvm::APInt::getHighBitsSet(), llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::COFF::ImportLookupTableEntry32::getHintNameRVA(), llvm::BranchProbabilityInfo::getHotSucc(), llvm::AMDGPURegisterInfo::getHWRegIndex(), llvm::ConstantExpr::getICmp(), llvm::IdentifyingPassPtr::getID(), llvm::opt::Option::getID(), llvm::GetIfCondition(), llvm::ValueAsMetadata::getIfExists(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbol(), llvm::MCOperand::getImm(), llvm::X86Operand::getImm(), llvm::MachineOperand::getImm(), llvm::ConstantDataSequential::getImpl(), llvm::PHINode::getIncomingBlock(), getIncomingStatepointGCValues(), llvm::PHINode::getIncomingValueForBlock(), llvm::MachineOperand::getIndex(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::SelectionDAG::getIndexedLoad(), llvm::TargetLoweringBase::getIndexedLoadAction(), llvm::DataLayout::getIndexedOffset(), llvm::SelectionDAG::getIndexedStore(), llvm::TargetLoweringBase::getIndexedStoreAction(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), llvm::GlobalVariable::getInitializer(), llvm::MachineInstr::getInlineAsmDialect(), llvm::CCState::getInRegsParamInfo(), llvm::ConstantExpr::getInsertElement(), getInsertPointForUses(), getINSERTPS(), llvm::TargetInstrInfo::getInsertSubregInputs(), llvm::ARMBaseInstrInfo::getInsertSubregLikeInputs(), llvm::ConstantExpr::getInsertValue(), getInsertVINSERTImmediate(), llvm::MCOperand::getInst(), llvm::IdentifyingPassPtr::getInstance(), llvm::SUnit::getInstr(), llvm::MachineTraceMetrics::Trace::getInstrSlack(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), llvm::ARMBaseInstrInfo::GetInstSizeInBytes(), llvm::VectorType::getInteger(), llvm::ConstantExpr::getIntegerCast(), llvm::LiveStacks::getInterval(), llvm::LiveStacks::getIntervalRegClass(), llvm::DataLayout::getIntPtrType(), llvm::ConstantExpr::getIntToPtr(), llvm::AsmToken::getIntVal(), llvm::MachineFunction::getJTISymbol(), llvm::SelectionDAG::getJumpTable(), llvm::opt::Option::getKind(), llvm::AttributeImpl::getKindAsEnum(), llvm::Attribute::getKindAsEnum(), llvm::AttributeImpl::getKindAsString(), llvm::Attribute::getKindAsString(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::DwarfDebug::getLabelBeforeInsn(), llvm::DwarfCompileUnit::getLabelBegin(), llvm::RegisterClassInfo::getLastCalleeSavedAlias(), llvm::LatencyPriorityQueue::getLatency(), llvm::ResourcePriorityQueue::getLatency(), llvm::SIInstrInfo::getLdStBaseRegImmOfs(), llvm::EquivalenceClasses< ElemTy >::getLeaderValue(), getLeftShift(), llvm::PBQP::Vector::getLength(), llvm::ScaledNumbers::getLgImpl(), llvm::SourceMgr::getLineAndColumn(), GetLinearExpression(), llvm::StratifiedSets< T >::getLink(), llvm::BitCodeAbbrevOp::getLiteralValue(), llvm::MCRegisterInfo::getLLVMRegNum(), llvm::SelectionDAG::getLoad(), llvm::TargetLoweringBase::getLoadExtAction(), getLoadStoreRegOpcode(), GetLoadValueForLoad(), llvm::MachineFrameInfo::getLocalFrameObjectMap(), getLocalFunction(), llvm::SlotTracker::getLocalSlot(), llvm::LibCallInfo::getLocationInfo(), getLocForRead(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::BlockFrequencyInfoImplBase::getLoopPackage(), llvm::LoopBase< N, M >::getLoopPredecessor(), getLoopTest(), llvm::APInt::getLowBitsSet(), llvm::XCoreFunctionInfo::getLRSpillSlot(), llvm::ConstantPoolSDNode::getMachineCPVal(), llvm::VirtRegMap::getMachineFunction(), llvm::SDNode::getMachineOpcode(), llvm::SourceMgr::getMainFileID(), llvm::getMallocArraySize(), llvm::getMallocType(), llvm::SelectionDAG::getMaskedStore(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::ShuffleVectorInst::getMaskValue(), llvm::TargetLowering::AsmOperandInfo::getMatchedOperand(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::RegPressureTracker::getMaxDownwardPressureDelta(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::RegPressureTracker::getMaxPressureDelta(), llvm::RegPressureTracker::getMaxUpwardPressureDelta(), llvm::MachineOperand::getMBB(), llvm::SlotIndexes::getMBBCoveringRange(), llvm::SlotIndexes::getMBBFromIndex(), llvm::MCContext::getMCDwarfLineTable(), llvm::MachineOperand::getMCSymbol(), llvm::LLVMContext::getMDKindID(), llvm::X86Operand::getMemBaseReg(), llvm::SelectionDAG::getMemcpy(), getMemcpyLoadsAndStores(), llvm::X86Operand::getMemDisp(), llvm::X86Operand::getMemIndexReg(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::X86Operand::getMemModeSize(), llvm::SelectionDAG::getMemmove(), getMemory(), llvm::SourceMgr::getMemoryBuffer(), llvm::X86Operand::getMemScale(), llvm::X86Operand::getMemSegReg(), llvm::SelectionDAG::getMemset(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), llvm::SourceMgr::GetMessage(), llvm::MachineOperand::getMetadata(), llvm::ValueEnumerator::getMetadataID(), llvm::PatchPointOpers::getMetaIdx(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::ScalarEvolution::getMinusSCEV(), llvm::AliasAnalysis::getModRefBehavior(), llvm::AliasAnalysis::getModRefInfo(), getMOVHighToLow(), getMOVLowToHigh(), getMOVLP(), llvm::ScalarEvolution::getMulExpr(), llvm::AMDGPUIntrinsicInfo::getName(), llvm::object::ArchiveMemberHeader::getName(), llvm::Intrinsic::getName(), llvm::MCInstrInfo::getName(), llvm::opt::Option::getName(), llvm::MachineFunction::getName(), llvm::StructType::getName(), llvm::DIScope::getName(), llvm::TargetLibraryInfo::getName(), llvm::VarInit::getName(), llvm::RecordVal::getName(), llvm::Record::getName(), getNameWithPrefixx(), llvm::ConstantExpr::getNeg(), GetNegatedExpression(), llvm::HexagonMCInst::getNewValue(), getNextIntArgReg(), llvm::PatchPointOpers::getNextScratchIdx(), llvm::SUnit::getNode(), llvm::RegionBase< RegionTr >::getNode(), llvm::SelectionDAG::getNode(), llvm::RegionNodeBase< Tr >::getNodeAs(), llvm::DominatorTreeBase< BasicBlock >::getNodeForBlock(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::ScalarEvolution::getNoopOrAnyExtend(), llvm::ScalarEvolution::getNoopOrSignExtend(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::ConstantExpr::getNot(), llvm::BinaryOperator::getNotArgument(), llvm::DbgVariable::getNumAddrElements(), getNumAllocatableRegsForConstraints(), llvm::object::COFFSymbolRef::getNumberOfAuxSymbols(), llvm::DIExpression::getNumElements(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getNumMicroOpsSwiftLdSt(), llvm::TargetLoweringBase::getNumRegisters(), llvm::object::ELFFile< ELFT >::getNumSections(), llvm::LatencyPriorityQueue::getNumSolelyBlockNodes(), llvm::ResourcePriorityQueue::getNumSolelyBlockNodes(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectAllocation(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::StringTableBuilder::getOffset(), llvm::MCCFIInstruction::getOffset(), llvm::MachineOperand::getOffset(), llvm::MCSymbolData::getOffset(), getOffsetOrZero(), getOnesVector(), llvm::MemoryBuffer::getOpenFileSlice(), llvm::User::getOperand(), llvm::SCEVNAryExpr::getOperand(), llvm::MachineInstr::getOperand(), llvm::SDNode::getOperand(), llvm::MDNode::getOperand(), llvm::UnOpInit::getOperand(), llvm::BinOpInit::getOperand(), llvm::NamedMDNode::getOperand(), llvm::TernOpInit::getOperand(), llvm::SDNode::use_iterator::getOperandNo(), llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::getOperandNo(), llvm::User::getOperandUse(), llvm::MipsTargetLowering::getOpndList(), llvm::opt::OptTable::getOption(), llvm::ConstantUniqueMap< llvm::ConstantExpr >::getOrCreate(), llvm::LexicalScopes::getOrCreateAbstractScope(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::LiveStacks::getOrCreateInterval(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::MCContext::GetOrCreateSymbol(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::object::import_lookup_table_entry< IntTy >::getOrdinal(), llvm::COFF::ImportLookupTableEntry32::getOrdinal(), llvm::getOrEnforceKnownAlignment(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), llvm::CallGraph::getOrInsertFunction(), llvm::EquivalenceClasses< ElemTy >::getOrInsertLeaderValue(), llvm::Argument::getParamAlignment(), llvm::LiveRangeEdit::getParent(), llvm::SourceMgr::getParentIncludeLoc(), llvm::LessRecordRegister::RecordParts::getPart(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), llvm::PMDataManager::getPassManagerType(), getPHIDeps(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), llvm::VirtRegMap::getPhys(), getPhysicalRegisterVT(), llvm::SIRegisterInfo::getPhysRegClass(), llvm::SIRegisterInfo::getPhysRegSubReg(), llvm::DIExpression::getPieceOffset(), llvm::DIExpression::getPieceSize(), llvm::PluginLoader::getPlugin(), llvm::Optional< COFF::AuxiliarySectionDefinition >::getPointer(), llvm::DataLayout::getPointerABIAlignment(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::DataLayout::getPointerPrefAlignment(), llvm::DataLayout::getPointerSize(), llvm::TargetLoweringBase::getPointerTypeSizeInBits(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::cl::list< DataType, Storage, ParserClass >::getPosition(), llvm::cl::bits< DataType, Storage, ParserClass >::getPosition(), GetPostIncrementOperand(), llvm::LoopBlocksDFS::getPostorder(), llvm::ConstantExpr::getPredicate(), getPredicatedRegister(), llvm::DataLayout::getPreferredTypeAlignmentShift(), getPrefetchNode(), llvm::Function::getPrefixData(), llvm::RegPressureTracker::getPressureAfterInst(), llvm::MachineFrameInfo::getPristineRegs(), llvm::MCSchedModel::getProcResource(), llvm::MachineTraceMetrics::getProcResourceCycles(), llvm::MachineTraceMetrics::Ensemble::getProcResourceDepths(), llvm::MachineTraceMetrics::Ensemble::getProcResourceHeights(), llvm::Function::getPrologueData(), llvm::NVPTXTargetLowering::getPrototype(), llvm::PressureChange::getPSet(), getPSHUFB(), getPSHUFShuffleMask(), llvm::ConstantExpr::getPtrToInt(), getPUSHiOpcode(), GetRangeFromMetadata(), llvm::StratifiedSetsBuilder< T >::getRawAttribute(), llvm::StratifiedSetsBuilder< T >::getRawAttributes(), getReadPerformanceCounter(), getReadTimeStampCounter(), llvm::DIEEntry::getRefAddrSize(), llvm::MCOperand::getReg(), llvm::X86Operand::getReg(), llvm::SDep::getReg(), llvm::MachineOperand::getReg(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::MCRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClass(), llvm::MachineInstr::getRegClassConstraint(), llvm::MachineInstr::getRegClassConstraintEffect(), llvm::TargetLoweringBase::getRegClassFor(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::MCRegisterClass::getRegister(), llvm::MCCFIInstruction::getRegister(), llvm::MCCFIInstruction::getRegister2(), llvm::cl::getRegisteredOptions(), GetRegistersForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::MachineOperand::getRegLiveOut(), llvm::MachineOperand::getRegMask(), llvm::SIRegisterInfo::getRegPressureSetLimit(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), getRegTy(), llvm::object::ELFObjectFile< ELFT >::getRelocationOffset(), llvm::object::MachOObjectFile::getRelocationOffset(), llvm::CCState::getRemainingRegParmsForType(), llvm::AMDGPURegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::MachineRegisterInfo::getReservedRegs(), llvm::SDDbgValue::getResNo(), llvm::MachineTraceMetrics::getResources(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::getResult(), llvm::XCoreFunctionInfo::getReturnStackOffset(), llvm::object::Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, false >, false >::getRInfo(), llvm::object::Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, false >, true >::getRInfo(), llvm::DominanceFrontierBase< llvm::MachineBasicBlock >::getRoot(), llvm::DominatorTreeBase< BasicBlock >::getRoot(), llvm::EVT::getRoundIntegerType(), llvm::PBQP::Matrix::getRowAsVector(), llvm::PBQP::Matrix::getRowMin(), llvm::PBQP::Matrix::getRows(), llvm::getSamplerName(), getScalingFactorCost(), getScatterNode(), llvm::ScalarEvolution::getSCEV(), llvm::MCSchedModel::getSchedClassDesc(), llvm::MCSubtargetInfo::getSchedModelForCPU(), llvm::SDDbgValue::getSDNode(), llvm::MCSymbol::getSection(), llvm::DwarfUnit::getSection(), llvm::MCAssembler::getSectionData(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::object::COFFSymbolRef::getSectionNumber(), getSectionPrefixForGlobal(), llvm::DwarfCompileUnit::getSectionSym(), llvm::SelectionDAG::getSelect(), llvm::ConstantExpr::getSelect(), llvm::PBQP::Solution::getSelection(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::X86::getSETFromCond(), llvm::ConstantExpr::getSExt(), llvm::APInt::getSExtValue(), llvm::TargetLoweringBase::getShiftAmountTy(), GetShiftedValue(), llvm::AArch64_AM::getShifterImm(), getShuffleAlignrImmediate(), getShufflePSHUFHWImmediate(), getShufflePSHUFLWImmediate(), getShuffleSHUFImmediate(), llvm::ConstantExpr::getShuffleVector(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SelectionDAG::getSignExtendVectorInReg(), llvm::EVT::getSimpleVT(), llvm::Twine::getSingleStringRef(), llvm::ConstantExpr::getSIToFP(), llvm::DIVariable::getSizeInBits(), llvm::ScalarEvolution::getSizeOfExpr(), llvm::AttributeSet::getSlotAttributes(), llvm::AttributeSet::getSlotIndex(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::ScalarEvolution::getSMaxExpr(), llvm::ARM_AM::getSOImmTwoPartSecond(), llvm::SuccIterator< Term_, BB_ >::getSource(), llvm::APInt::getSplat(), llvm::ConstantDataVector::getSplat(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::Constant::getSplatValue(), llvm::BuildVectorSDNode::getSplatValue(), llvm::SelectionDAG::GetSplitDestVTs(), llvm::DependenceAnalysis::getSplitIteration(), llvm::R600InstrInfo::getSrcIdx(), llvm::SelectionDAG::getSrcValue(), llvm::SparcTargetLowering::getSRetArgSize(), llvm::Attribute::getStackAlignment(), llvm::AMDGPUSubtarget::getStackEntrySize(), llvm::VirtRegMap::getStackSlot(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::object::COFFSymbolRef::getStorageClass(), llvm::SelectionDAG::getStore(), llvm::object::ELFFile< ELFT >::getString(), llvm::MDString::getString(), llvm::AsmToken::getStringContents(), llvm::object::COFFSymbolRef::getStringTableOffset(), llvm::TargetRegisterInfo::getSubClassWithSubReg(), llvm::MachineOperand::getSubReg(), llvm::MCRegisterInfo::getSubReg(), llvm::AMDGPURegisterInfo::getSubRegFromChannel(), llvm::MCRegisterInfo::getSubRegIdxOffset(), llvm::MCRegisterInfo::getSubRegIdxSize(), llvm::MCRegisterInfo::getSubRegIndex(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::TargetRegisterInfo::getSubRegIndexName(), llvm::RegionBase< RegionTr >::getSubRegionNode(), llvm::SchedDFSResult::getSubtreeID(), llvm::BranchInst::getSuccessor(), llvm::SwitchInst::getSuccessor(), llvm::InvokeInst::getSuccessor(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::getSuccessorIndex(), llvm::GetSuccessorNumber(), llvm::ScaledNumbers::getSum(), llvm::MachineBranchProbabilityInfo::getSumForBlock(), llvm::getSurfaceName(), llvm::object::COFFObjectFile::getSymbolAuxData(), llvm::object::MachOObjectFile::getSymbolByIndex(), llvm::MCAssembler::getSymbolData(), llvm::object::IRObjectFile::getSymbolFlags(), GetSymbolFromOperand(), llvm::object::ELFFile< ELFT >::getSymbolIndex(), llvm::MachineOperand::getSymbolName(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), getSymTab(), getT2IndexedAddressParts(), llvm::ARM_AM::getT2SOImmTwoPartFirst(), llvm::ARM_AM::getT2SOImmTwoPartSecond(), getTargetShuffleMask(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getTestUnderMaskCond(), llvm::getTextureName(), llvm::AArch64RegisterInfo::getThisReturnPreservedMask(), llvm::AArch64RegisterInfo::getTLSCallPreservedMask(), llvm::X86Operand::getToken(), llvm::ConstantInt::getTrue(), getTrue(), llvm::ConstantExpr::getTrunc(), llvm::VectorType::getTruncatedElementVectorType(), llvm::ScalarEvolution::getTruncateExpr(), llvm::ScalarEvolution::getTruncateOrNoop(), llvm::ScalarEvolution::getTruncateOrSignExtend(), llvm::ScalarEvolution::getTruncateOrZeroExtend(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTruncStoreAction(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::MCELF::GetType(), llvm::object::COFFSymbolRef::getType(), llvm::CompositeType::getTypeAtIndex(), llvm::TargetLoweringBase::getTypeConversion(), llvm::ConstantStruct::getTypeForElements(), llvm::EVT::getTypeForEVT(), llvm::ValueEnumerator::getTypeID(), getTypePartition(), llvm::DataLayout::getTypeSizeInBits(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::TargetLoweringBase::getTypeToExpandTo(), llvm::TargetLoweringBase::getTypeToPromoteTo(), llvm::ScalarEvolution::getUDivExpr(), llvm::ConstantExpr::getUIToFP(), llvm::ScalarEvolution::getUMaxExpr(), getUnderlyingExtractedFromVec(), llvm::GetUnderlyingObject(), getUnderlyingObjectFromInt(), llvm::Loop::getUniqueExitBlocks(), llvm::Constant::getUniqueInteger(), llvm::DIE::getUnit(), llvm::ScalarEvolution::getUnknown(), GetUnrollMetadata(), llvm::RegPressureTracker::getUpwardPressureDelta(), getV4X86ShuffleImm8ForMask(), llvm::ScheduleDAGSDNodes::RegDefIter::GetValue(), llvm::Optional< COFF::AuxiliarySectionDefinition >::getValue(), llvm::cl::OptionValueCopy< cl::boolOrDefault >::getValue(), llvm::AttributeImpl::getValueAsInt(), llvm::Attribute::getValueAsInt(), llvm::AttributeImpl::getValueAsString(), llvm::Attribute::getValueAsString(), llvm::BitcodeReaderValueList::getValueFwdRef(), llvm::ValueEnumerator::getValueID(), getValueImpl(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::MCCFIInstruction::getValues(), llvm::SDNode::getValueType(), llvm::object::COFFObjectFile::getVaPtr(), llvm::MCSymbol::getVariableValue(), llvm::LiveVariables::getVarInfo(), GetVBR(), llvm::EVT::getVectorElementType(), getVectorMaskingNode(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::MCELF::GetVisibility(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), getVLDSTRegisterUpdateOpcode(), llvm::MachineRegisterInfo::getVRegDef(), getVShift(), llvm::PPC::getVSPLTImmediate(), getWFCountLimitedByGPR(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithDereferenceableBytes(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), llvm::Attribute::getWithStackAlignment(), llvm::MCSubtargetInfo::getWriteLatencyEntry(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::SelectionDAG::getZeroExtendVectorInReg(), llvm::SlotIndexes::getZeroIndex(), getZeroVector(), llvm::ConstantExpr::getZExt(), llvm::APInt::getZExtValue(), llvm::GlobalVariable::GlobalVariable(), llvm::IntEqClasses::grow(), llvm::DenseMap< void *, std::unique_ptr< PassConceptT > >::grow(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::grow(), llvm::ARM::WinEH::RuntimeFunction::H(), llvm::MipsTargetLowering::HandleByVal(), llvm::CrashRecoveryContext::HandleCrash(), llvm::ValueAsMetadata::handleDeletion(), HandleMergeInputChains(), llvm::LiveIntervals::handleMove(), HandlePrefixedOrGroupedOption(), llvm::ValueAsMetadata::handleRAUW(), llvm::LiveVariables::HandleVirtRegUse(), llvm::mdconst::hasa(), llvm::Instruction::hasAllowReciprocal(), llvm::SDNode::hasAnyUseOfValue(), llvm::AttrBuilder::hasAttributes(), llvm::AMDGPUSubtarget::hasCFAluBug(), hasFlag(), llvm::CallInst::hasFnAttr(), llvm::InvokeInst::hasFnAttr(), llvm::AArch64FrameLowering::hasFP(), llvm::LeakDetectorImpl< llvm::Metadata >::hasGarbage(), llvm::hashing::detail::hash_combine_range_impl(), llvm::scc_iterator< GraphT, GT >::hasLoop(), hasMoreThanOneUseOtherThanLLVMUsed(), llvm::Instruction::hasNoInfs(), llvm::Instruction::hasNoNaNs(), llvm::Instruction::hasNoSignedZeros(), llvm::SDNode::hasNUsesOfValue(), llvm::AArch64InstrInfo::hasPattern(), hasSameExtUse(), llvm::TargetLoweringBase::hasTargetDAGCombine(), llvm::Instruction::hasUnsafeAlgebra(), hasUseOtherThanLLVMUsed(), haveSameSpecialState(), HUerrBound(), IfNeededExtSP(), IfNeededLDAWSP(), llvm::HexagonInstrInfo::immediateExtend(), IncorporateWeight(), llvm::TargetRegisterInfo::index2StackSlot(), llvm::MemoryBuffer::init(), llvm::LivePhysRegs::init(), llvm::BitstreamReader::init(), llvm::Timer::init(), llvm::BinaryOperator::init(), llvm::LiveIntervalUnion::Query::init(), llvm::RegPressureTracker::init(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), llvm::R600SchedStrategy::initialize(), llvm::ConvergingVLIWScheduler::initialize(), llvm::GenericScheduler::initialize(), INITIALIZE_PASS(), INITIALIZE_PASS_WITH_OPTIONS(), llvm::PMDataManager::initializeAnalysisImpl(), llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::RegPressureTracker::initLiveThru(), llvm::ScheduleDAGSDNodes::InitNumRegDefsLeft(), llvm::SDNode::InitOperands(), llvm::GenericScheduler::initPolicy(), initReachingDef(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::DwarfUnit::initSection(), llvm::PointerIntPair< void *, 1, bool, PointerUnionUIntTraits< const Value *, const PseudoSourceValue * > >::initWithPointer(), InlineCallIfPossible(), llvm::InlineFunction(), InlineHistoryIncludes(), llvm::StringSet< AllocatorTy >::insert(), llvm::TinyPtrVector< EltTy >::insert(), llvm::StringMap< std::unique_ptr< llvm::MipsSubtarget > >::insert(), llvm::MachineBasicBlock::insert(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::insert(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, RootBranchCap, Traits >::insert(), Insert128BitVector(), Insert256BitVector(), llvm::MachineBasicBlock::insertAfter(), llvm::XCoreInstrInfo::InsertBranch(), llvm::MipsInstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::SparcInstrInfo::InsertBranch(), llvm::MSP430InstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::AArch64InstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::SystemZInstrInfo::InsertBranch(), llvm::R600InstrInfo::InsertBranch(), llvm::X86InstrInfo::InsertBranch(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), llvm::LazyCallGraph::insertEdge(), InsertFPConstInst(), llvm::IntervalMapImpl::LeafNode< typename, typename, unsigned, typename >::insertFrom(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), insertInteger(), llvm::BasicBlock::insertInto(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::insertIntoScope(), llvm::LazyCallGraph::SCC::insertIntraSCCEdge(), llvm::LPPassManager::insertLoop(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), llvm::InstCombiner::InsertNewInstBefore(), llvm::FoldingSetImpl::InsertNode(), insertNopBeforeInstruction(), llvm::LazyCallGraph::SCC::insertOutgoingEdge(), llvm::TargetPassConfig::insertPass(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), insertSinCosCall(), InsertSPConstInst(), InsertSubVector(), insertUniqueBackedgeBlock(), insertVector(), llvm::install_fatal_error_handler(), llvm::Instruction::Instruction(), llvm::IntAttributeImpl::IntAttributeImpl(), interpretDecimal(), llvm::ConstantRange::intersectWith(), llvm::IntervalMap< SlotIndex, unsigned >::IntervalMap(), llvm::IntervalPartition::IntervalPartition(), llvm::MipsSERegisterInfo::intRegClass(), llvm::Mips16RegisterInfo::intRegClass(), llvm::IntToPtrInst::IntToPtrInst(), llvm::MachineTraceMetrics::Ensemble::invalidate(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::invalidate(), invertBccCondition(), invertFPCondCodeUser(), llvm::ARMSubtarget::isAAPCS_ABI(), llvm::MachineFrameInfo::isAliasedObjectIndex(), isAMCompletelyFolded(), llvm::ARMSubtarget::isAPCS_ABI(), llvm::scc_iterator< GraphT, GT >::isAtEnd(), llvm::DWARFDebugRangeList::RangeListEntry::isBaseAddressSelectionEntry(), isBitfieldDstMask(), isBitfieldExtractOpFromAnd(), isBitfieldExtractOpFromShr(), isBitfieldInsertOpFromOr(), isBitfieldPositioningOp(), llvm::DbgVariable::isBlockByrefVariable(), isCDisp8(), llvm::CoalescerPair::isCoalescable(), IsConstantOne(), llvm::MachineRegisterInfo::isConstantPhysReg(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::MachineInstr::isConstantValuePHI(), llvm::HexagonMCInst::isConstExtended(), llvm::HexagonInstrInfo::isConstExtended(), llvm::isCriticalEdge(), llvm::MachineOperand::isDead(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineOperand::isDebug(), llvm::GlobalValue::isDeclaration(), llvm::MachineOperand::isDef(), isDescribedByReg(), llvm::MachineOperand::isEarlyClobber(), llvm::CastInst::isEliminableCastPair(), isEnabled(), isEvenReg(), isF128SoftLibCall(), llvm::AMDGPUTargetLowering::isFAbsFree(), llvm::TargetLoweringBase::isFAbsFree(), llvm::AMDGPUTargetLowering::isFNegFree(), llvm::TargetLoweringBase::isFNegFree(), llvm::PPCTargetLowering::isFPExtFree(), llvm::TargetLoweringBase::isFPExtFree(), llvm::AArch64InstrInfo::isFPRCopy(), llvm::AArch64RegisterInfo::isFrameOffsetLegal(), llvm::PPCRegisterInfo::isFrameOffsetLegal(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), isGEPKnownNonNull(), llvm::AArch64InstrInfo::isGPRCopy(), llvm::AArch64InstrInfo::isGPRZero(), isHighReg(), isHorizontalBinOp(), llvm::SIInstrInfo::isImmOperandLegal(), llvm::MachineFrameInfo::isImmutableObjectIndex(), llvm::MachineOperand::isImplicit(), isIndexInRangeOfSequentialType(), llvm::DIVariable::isInlinedFnArgument(), llvm::MachineOperand::isInternalRead(), isIntExtFree(), llvm::APInt::isIntN(), llvm::MachineOperand::isKill(), llvm::AArch64InstrInfo::isLdStPairSuppressed(), isLoadFromGOTOrConstantPool(), llvm::Triple::isMacOSXVersionLT(), llvm::isManaged(), llvm::TargetLowering::AsmOperandInfo::isMatchingInputConstraint(), llvm::NVPTXInstrInfo::isMoveInstr(), IsMultiple(), llvm::ARM_AM::isNEONBytesplat(), isNEONModifiedImm(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), IsNullTerminatedString(), llvm::MachineFrameInfo::isObjectPreAllocated(), isOnlyCopiedFromConstantGlobal(), isOnlyReachableViaThisEdge(), llvm::SIInstrInfo::isOperandLegal(), llvm::SplitAnalysis::isOriginalEndpoint(), llvm::FullDependence::isPeelFirst(), llvm::FullDependence::isPeelLast(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::R600RegisterInfo::isPhysRegLiveAcrossClauses(), isPlainlyKilled(), llvm::isPotentiallyReachable(), llvm::HexagonInstrInfo::isPredicatedNew(), llvm::HexagonInstrInfo::isPredicatedTrue(), isProfitableChain(), isProfitableToFoldUnconditional(), llvm::DominatorTreeBase< BasicBlock >::isReachableFromEntry(), llvm::isReadOnlyData(), llvm::SchedulingPriorityQueue::isReady(), isReg(), isRematerializable(), isRepeatedByteSequence(), llvm::isRequiredForExecution(), isREVMask(), llvm::SystemZInstrInfo::isRxSBGMask(), llvm::APSInt::isSameValue(), llvm::isSampler(), llvm::FullDependence::isScalar(), isScaledConstantInRange(), isShuffleMaskInputInPlace(), llvm::APInt::isSignedIntN(), llvm::BasicBlockEdge::isSingleEdge(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), llvm::ShuffleVectorSDNode::isSplatMask(), llvm::PPC::isSplatShuffleMask(), isSplatVector(), llvm::FullDependence::isSplitable(), llvm::StatepointLoweringState::isStackSlotAllocated(), isStridedPtr(), llvm::isSurface(), llvm::isTexture(), llvm::MachineOperand::isTied(), isTruncateOf(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MachineOperand::isUndef(), isUNPCKH_v_undef_Mask(), isUNPCKHMask(), isUNPCKL_v_undef_Mask(), isUNPCKLMask(), isUnsignedDIType(), llvm::MachineOperand::isUse(), IsUserOfGlobalSafeForSRA(), isValidDisp(), llvm::ConstantFPSDNode::isValueValidForType(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), isVEXTRACTIndex(), isVINSERTIndex(), llvm::TargetRegisterInfo::isVirtualRegister(), isVMerge(), isVREVMask(), isVShiftLImm(), isVShiftRImm(), llvm::PBQP::Matrix::isZero(), llvm::IntEqClasses::join(), llvm::LiveRange::join(), llvm::SchedDFSImpl::joinPredSubtree(), llvm::BitstreamCursor::JumpToBit(), KnuthDiv(), llvm::ARM::WinEH::RuntimeFunction::L(), llvm::MCAsmLayout::layoutFragment(), llvm::LazyCallGraph::LazyCallGraph(), lcm(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvAtTop(), llvm::SplitEditor::leaveIntvBefore(), llvm::SIInstrInfo::legalizeOperands(), llvm::LexicalScope::LexicalScope(), llvm::line_iterator::line_iterator(), LinearizeExprTree(), llvm::lintFunction(), llvm::LivePhysRegs::LivePhysRegs(), lle_X_atexit(), lle_X_fprintf(), lle_X_scanf(), lle_X_sscanf(), llvm_regerror(), llvm_regexec(), llvm::LLVMContext::LLVMContext(), LLVMDisasmInstruction(), LLVMGetMetadata(), LLVMGetOperand(), LLVMMDNodeInContext(), llvm::coverage::CoverageMapping::load(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), LoadIntFromMemory(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::unique_lock< MutexT >::lock(), llvm::sys::SmartMutex< false >::lock(), llvm::sys::SmartRWMutex< true >::lock(), llvm::BlockAddress::lookup(), LookupNEONLdSt(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::lookupPass(), llvm::AMDGPUMCInstLower::lower(), Lower256IntArith(), Lower256IntVSETCC(), lower512BitVectorShuffle(), LowerADD(), llvm::FastISel::lowerArguments(), LowerATOMIC_FENCE(), LowerAVXCONCAT_VECTORS(), LowerBITCAST(), LowerBSWAP(), LowerBuildVectorv4x32(), llvm::SystemZTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallFromStatepoint(), llvm::SelectionDAGBuilder::lowerCallOperands(), LowerCallResult(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), LowerCMP_SWAP(), LowerCONCAT_VECTORS(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRRestore(), LowerCTPOP(), llvm::X86TargetLowering::LowerCustomJumpTableEntry(), LowerDextDins(), lowerDSPIntr(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), LowerExtendedLoad(), LowerF128Load(), llvm::SparcTargetLowering::LowerF128Op(), LowerF128Store(), LowerF64Op(), LowerFABSorFNEG(), LowerFNEGorFABS(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP_EXTEND(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), LowerFSINCOS(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), LowerINTRINSIC_WO_CHAIN(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerIntVSETCC_AVX512(), LowerLargeShift(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::MipsTargetLowering::lowerLOAD(), LowerMUL(), LowerMUL_LOHI(), llvm::ARMAsmPrinter::lowerOperand(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::LowerPPCMachineInstrToMCInst(), LowerPREFETCH(), llvm::SystemZTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), LowerSCALAR_TO_VECTOR(), LowerScalarVariableShift(), LowerSDIV(), LowerShift(), LowerShiftParts(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), LowerSIGN_EXTEND_AVX512(), LowerSINT_TO_FP(), LowerSTATEPOINT(), lowerStatepointMetaArgs(), LowerSUB(), llvm::AArch64MCInstLower::LowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), lowerUnalignedIntStore(), lowerV16F32VectorShuffle(), lowerV16I16VectorShuffle(), lowerV16I32VectorShuffle(), lowerV16I8VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV32I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV4I64VectorShuffle(), lowerV64I8VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8F64VectorShuffle(), lowerV8I16BasicBlendVectorShuffle(), lowerV8I16SingleInputVectorShuffle(), lowerV8I16VectorShuffle(), lowerV8I32VectorShuffle(), lowerV8I64VectorShuffle(), LowerVACOPY(), LowerVECTOR_SHUFFLE_128v4(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), LowerVECTOR_SHUFFLEtoBlend(), LowerVectorAllZeroTest(), LowerVectorBroadcast(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), lowerVectorShuffle(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsByteShift(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsInsertPS(), lowerVectorShuffleAsLanePermuteAndBlend(), lowerVectorShuffleAsSpecificZeroOrAnyExtend(), lowerVectorShuffleAsSplitOrBlend(), lowerVectorShuffleAsZeroOrAnyExtend(), lowerVectorShuffleByMerging128BitLanes(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), LowerVSETCC(), LowerZERO_EXTEND(), LowerZERO_EXTEND_AVX512(), llvm::LSBaseSDNode::LSBaseSDNode(), llvm::opt::InputArgList::MakeIndex(), makeVisible(), mapDistinctNode(), llvm::MapMetadata(), MapMetadataImpl(), llvm::yaml::MappingTraits< ELFYAML::Object >::mapping(), mapUniquedNode(), llvm::MapValue(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::Regex::match(), matchAddSub(), MatchingStackOffset(), matchPairwiseReductionAtLevel(), llvm::ScaledNumbers::matchScales(), llvm::BitcodeReader::materialize(), llvm::BitcodeReader::materializeForwardReferencedFunctions(), llvm::BitcodeReader::MaterializeModule(), MaterializeSETB(), mccase(), llvm::MCFillFragment::MCFillFragment(), mcinvert(), llvm::MCLOHDirective::MCLOHDirective(), llvm::MCRegUnitIterator::MCRegUnitIterator(), llvm::MCRegUnitRootIterator::MCRegUnitRootIterator(), llvm::MemSDNode::MemSDNode(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::AliasSet::mergeSetIn(), llvm::LiveRange::MergeValueNumberInto(), llvm::MIBundleBuilder::MIBundleBuilder(), MIIsInTerminatorSequence(), llvm::AArch64FunctionInfo::MILOHDirective::MILOHDirective(), llvm::PBQP::Vector::minIndex(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsSubtarget::MipsSubtarget(), MIsNeedChainEdge(), llvm::APFloat::mod(), MoveBelowOrigChain(), llvm::SmallPtrSetImplBase::MoveFrom(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets(), llvm::IntervalMapImpl::NodeBase< std::pair< KeyT, KeyT >, ValT, N >::moveLeft(), llvm::IntervalMapImpl::Path::moveLeft(), llvm::MachineRegisterInfo::moveOperands(), llvm::IntervalMapImpl::NodeBase< std::pair< KeyT, KeyT >, ValT, N >::moveRight(), llvm::IntervalMapImpl::Path::moveRight(), llvm::SIInstrInfo::moveSMRDToVALU(), llvm::object::IRObjectFile::moveSymbolNext(), llvm::LoopBase< BasicBlock, Loop >::moveToHeader(), llvm::SIInstrInfo::moveToVALU(), llvm::APInt::multiplicativeInverse(), llvm::sys::MutexImpl::MutexImpl(), NameNeedsQuoting(), llvm::sys::path::native(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::ScheduleDAGSDNodes::newSUnit(), llvm::ScheduleDAGInstrs::newSUnit(), llvm::APFloat::next(), NextPossibleSolution(), nextRealType(), llvm::IntervalMapImpl::NodeRef::NodeRef(), nonnewline(), llvm::Triple::normalize(), llvm::BlockFrequencyInfoImplBase::Distribution::normalize(), NormalizeBuildVector(), llvm::StratifiedSetsBuilder< T >::noteAttribute(), llvm::StratifiedSetsBuilder< T >::noteAttributes(), llvm::CriticalAntiDepBreaker::Observe(), llvm::AggressiveAntiDepBreaker::Observe(), llvm::OnDiskChainedHashTable< Info >::OnDiskChainedHashTable(), llvm::DIType::operator DITypeRef(), operator new(), llvm::StringSwitch< T, R >::operator R(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator ValueT *(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::operator!=(), llvm::APSInt::operator%(), llvm::APSInt::operator%=(), llvm::APSInt::operator&(), llvm::APInt::operator&(), llvm::APSInt::operator&=(), llvm::APInt::operator&=(), llvm::LessRecordRegister::operator()(), llvm::constant_iterator::operator*(), llvm::PredIterator< Ptr, USE_iterator >::operator*(), llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator*(), llvm::ScopedHashTableIterator< K, V, KInfo >::operator*(), llvm::scc_iterator< GraphT, GT >::operator*(), llvm::RNSuccIterator< NodeType, BlockT, RegionT >::operator*(), llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator*(), llvm::Optional< COFF::AuxiliarySectionDefinition >::operator*(), llvm::SmallPtrSetIterator< PtrTy >::operator*(), llvm::AliasSet::iterator::operator*(), llvm::RNSuccIterator< FlatIt< NodeType >, BlockT, RegionT >::operator*(), llvm::APSInt::operator*(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator*(), llvm::EquivalenceClasses< ElemTy >::member_iterator::operator*(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator*(), llvm::TargetRegistry::iterator::operator*(), llvm::SDNode::use_iterator::operator*(), llvm::MCRegAliasIterator::operator*(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator*(), llvm::APInt::operator*(), llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator*(), llvm::MachineRegisterInfo::defusechain_instr_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator*(), llvm::APSInt::operator*=(), llvm::APInt::operator*=(), llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator+(), llvm::APSInt::operator+(), llvm::PBQP::Matrix::operator+(), llvm::APInt::operator+(), llvm::PredIterator< Ptr, USE_iterator >::operator++(), llvm::sys::path::const_iterator::operator++(), llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator++(), llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator++(), llvm::ScopedHashTableIterator< K, V, KInfo >::operator++(), llvm::MachineOperandIteratorBase::operator++(), llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator++(), llvm::AliasSet::iterator::operator++(), llvm::EquivalenceClasses< ElemTy >::member_iterator::operator++(), llvm::coverage::FunctionRecordIterator::operator++(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator++(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator++(), llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::operator++(), llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::operator++(), llvm::TargetRegistry::iterator::operator++(), llvm::SDNode::use_iterator::operator++(), llvm::yaml::document_iterator::operator++(), llvm::MCRegUnitRootIterator::operator++(), llvm::MCRegAliasIterator::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator++(), llvm::SuperRegClassIterator::operator++(), llvm::MachineRegisterInfo::defusechain_instr_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator++(), llvm::PSetIterator::operator++(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::operator++(), llvm::PBQP::Vector::operator+=(), llvm::APSInt::operator+=(), llvm::SuccIterator< Term_, BB_ >::operator+=(), llvm::PBQP::Matrix::operator+=(), llvm::APInt::operator+=(), llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator-(), llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator-(), llvm::SuccIterator< Term_, BB_ >::operator-(), llvm::APSInt::operator-(), llvm::APInt::operator-(), llvm::SDNodeIterator::operator-(), llvm::ilist_iterator< NodeTy >::operator--(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator--(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::operator--(), llvm::PBQP::Vector::operator-=(), llvm::APSInt::operator-=(), llvm::APInt::operator-=(), llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::operator->(), llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator->(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator->(), llvm::MachineRegisterInfo::defusechain_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator->(), llvm::MachineRegisterInfo::defusechain_instr_iterator< Uses, Defs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator->(), llvm::APSInt::operator/(), llvm::APSInt::operator/=(), llvm::opt::operator<(), llvm::ValID::operator<(), llvm::APSInt::operator<(), llvm::SuccIterator< Term_, BB_ >::operator<(), llvm::PBQP::operator<<(), llvm::raw_ostream::operator<<(), llvm::operator<<(), llvm::APSInt::operator<=(), llvm::SuccIterator< Term_, BB_ >::operator<=(), llvm::Timer::operator=(), llvm::RNSuccIterator< NodeType, BlockT, RegionT >::operator=(), llvm::SuccIterator< Term_, BB_ >::operator=(), llvm::RNSuccIterator< FlatIt< NodeType >, BlockT, RegionT >::operator=(), llvm::BitVector::operator=(), llvm::SUnitIterator::operator=(), llvm::SDNodeIterator::operator=(), llvm::object::Archive::Child::operator==(), llvm::PBQP::Vector::operator==(), llvm::RNSuccIterator< NodeType, BlockT, RegionT >::operator==(), llvm::object::MachORebaseEntry::operator==(), llvm::APSInt::operator==(), llvm::object::MachOBindEntry::operator==(), llvm::MDTupleInfo::KeyTy::operator==(), llvm::DataLayout::operator==(), llvm::RNSuccIterator< FlatIt< NodeType >, BlockT, RegionT >::operator==(), llvm::PBQP::Matrix::operator==(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator==(), llvm::IntervalMapImpl::NodeRef::operator==(), llvm::APInt::operator==(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator==(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::operator==(), llvm::APSInt::operator>(), llvm::SuccIterator< Term_, BB_ >::operator>(), llvm::APSInt::operator>=(), llvm::SuccIterator< Term_, BB_ >::operator>=(), llvm::BlockFrequency::operator>>=(), llvm::IndexedMap< unsigned, llvm::VirtReg2IndexFunctor >::operator[](), llvm::UniqueVector< const Comdat * >::operator[](), llvm::BitcodeReaderValueList::operator[](), llvm::IntEqClasses::operator[](), llvm::SetVector< llvm::BasicBlock * >::operator[](), llvm::PBQP::Vector::operator[](), llvm::BitcodeReaderMDValueList::operator[](), llvm::CallGraph::operator[](), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::operator[](), llvm::TinyPtrVector< EltTy >::operator[](), llvm::PressureDiffs::operator[](), llvm::ArrayRef< uint64_t >::operator[](), llvm::StringRef::operator[](), llvm::CallGraphNode::operator[](), llvm::LiveIntervalUnion::Array::operator[](), llvm::PBQP::Matrix::operator[](), llvm::MCRegisterInfo::operator[](), llvm::BitVector::operator[](), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::operator[](), llvm::SmallBitVector::operator[](), llvm::APInt::operator[](), llvm::APSInt::operator^(), llvm::APInt::operator^(), llvm::APSInt::operator^=(), llvm::APInt::operator^=(), llvm::APSInt::operator|(), llvm::APInt::operator|(), llvm::APSInt::operator|=(), llvm::APInt::operator|=(), OptimizeAndOrXor(), OptimizeAwayTrappingUsesOfLoads(), llvm::SystemZInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::X86InstrInfo::optimizeLoadInstr(), llvm::InstCombiner::OptimizePointerDifference(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::opt::Option::Option(), llvm::opt::OptTable::OptTable(), othercase(), llvm::RegionBase< RegionTr >::outermostLoopInRegion(), llvm::SplitEditor::overlapIntv(), llvm::LiveRange::overlaps(), llvm::LiveRange::overlapsFrom(), p_bracket(), p_ere(), p_ere_exp(), p_simp_re(), llvm::ARM::WinEH::RuntimeFunction::PackedUnwindData(), llvm::VLIWPacketizerList::PacketizeMIs(), llvm::DWARFDebugLine::LineTable::parse(), llvm::opt::OptTable::ParseArgs(), llvm::cl::ParseCommandLineOptions(), parseCond(), llvm::TargetLowering::ParseConstraints(), llvm::cl::ParseEnvironmentOptions(), parseRegisterNumber(), partAsHex(), llvm::PatchPointOpers::PatchPointOpers(), llvm::yaml::Scanner::peekNext(), PerformADDCombineWithOperands(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), performBRCONDCombine(), performConcatVectorsCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performExtendCombine(), PerformFMinFMaxCombine(), PerformFORCombine(), PerformHeapAllocSRoA(), PerformINSERTPSCombine(), PerformINTRINSIC_WO_CHAINCombine(), PerformISDSETCCCombine(), PerformMLOADCombine(), PerformMSTORECombine(), performORCombine(), PerformOrCombine(), PerformSELECTCombine(), performSetccAddFolding(), PerformShiftCombine(), PerformSHLCombine(), PerformSTORECombine(), PerformTargetShuffleCombine(), performVZEXTCombine(), llvm::PHITransAddr::PHITranslateValue(), llvm::ConvergingVLIWScheduler::pickNode(), llvm::GenericScheduler::pickNode(), llvm::PostGenericScheduler::pickNode(), llvm::GenericScheduler::pickNodeBidirectional(), llvm::ConvergingVLIWScheduler::pickNodeBidrectional(), llvm::PointerMayBeCaptured(), llvm::PointerMayBeCapturedBefore(), llvm::AliasAnalysis::pointsToConstantMemory(), llvm::sys::fs::recursive_directory_iterator::pop(), llvm::SetVector< llvm::BasicBlock * >::pop_back(), llvm::iplist< Argument >::pop_back(), llvm::iplist< Argument >::pop_front(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), powerOf5(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::TargetInstrInfo::PredicateInstruction(), predictValueUseListOrder(), predictValueUseListOrderImpl(), PrepareCall(), llvm::PressureChange::PressureChange(), llvm::BranchProbabilityInfo::print(), llvm::format_object_base::print(), llvm::DebugLoc::print(), llvm::LiveRange::print(), llvm::LiveRangeUpdater::print(), llvm::PrintRegUnit::print(), llvm::SystemZInstPrinter::printAddress(), llvm::ARMInstPrinter::printAddrMode2Operand(), llvm::ARMInstPrinter::printAddrMode3Operand(), llvm::AArch64InstPrinter::printAddSubImm(), llvm::AArch64InstPrinter::printAMIndexedWB(), llvm::ARMAsmPrinter::PrintAsmMemoryOperand(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::X86IntelInstPrinter::printAVXCC(), llvm::X86ATTInstPrinter::printAVXCC(), llvm::ARMInstPrinter::printBankedRegOperand(), llvm::ARMInstPrinter::printBitfieldInvMaskImmOperand(), llvm::HexagonInstPrinter::printConstantPool(), printDebugLoc(), printExpr(), llvm::HexagonInstPrinter::printExtOperand(), llvm::HexagonInstPrinter::printGlobalOperand(), llvm::SourceMgr::PrintIncludeStack(), llvm::ARMInstPrinter::printInst(), llvm::HexagonInstPrinter::printInst(), llvm::AArch64AppleInstPrinter::printInst(), llvm::HexagonInstPrinter::printJumpTable(), printLeaMemReference(), printLine(), PrintLLVMName(), llvm::X86IntelInstPrinter::printMemOffset(), llvm::X86ATTInstPrinter::printMemOffset(), llvm::X86IntelInstPrinter::printMemReference(), llvm::X86ATTInstPrinter::printMemReference(), printMemReference(), llvm::SourceMgr::PrintMessage(), llvm::AssemblyWriter::printModule(), llvm::MSP430InstPrinter::printOperand(), llvm::X86IntelInstPrinter::printOperand(), llvm::ARMInstPrinter::printOperand(), llvm::NVPTXInstPrinter::printOperand(), llvm::PPCInstPrinter::printOperand(), llvm::SparcInstPrinter::printOperand(), llvm::X86ATTInstPrinter::printOperand(), llvm::AArch64InstPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::X86IntelInstPrinter::printPCRelImm(), llvm::X86ATTInstPrinter::printPCRelImm(), llvm::MSP430InstPrinter::printPCRelImmOperand(), llvm::ARMInstPrinter::printPKHASRShiftImm(), llvm::ARMInstPrinter::printPKHLSLShiftImm(), llvm::PPCInstPrinter::printPredicateOperand(), llvm::NVPTXInstPrinter::printProtoIdent(), printRegImmShift(), llvm::ARMInstPrinter::printRotImmOperand(), llvm::ARMInstPrinter::printSBitModifierOperand(), llvm::ARMInstPrinter::printSORegRegOperand(), llvm::MSP430InstPrinter::printSrcMemOperand(), llvm::X86IntelInstPrinter::printSSECC(), llvm::X86ATTInstPrinter::printSSECC(), llvm::MCSectionCOFF::PrintSwitchToSection(), llvm::MCSectionELF::PrintSwitchToSection(), llvm::MCSectionMachO::PrintSwitchToSection(), llvm::HexagonInstPrinter::printSymbol(), llvm::object::IRObjectFile::printSymbolName(), llvm::AArch64InstPrinter::printSysAlias(), llvm::AArch64InstPrinter::printSysCROperand(), llvm::ARMInstPrinter::printT2AddrModeImm8s4OffsetOperand(), llvm::ARMInstPrinter::printT2AddrModeImm8s4Operand(), llvm::ARMInstPrinter::printT2AddrModeSoRegOperand(), llvm::ARMInstPrinter::printT2SOOperand(), llvm::ARMInstPrinter::printThumbITMask(), llvm::AssemblyWriter::printTypeIdentities(), llvm::PPCInstPrinter::printU2ImmOperand(), llvm::PPCInstPrinter::printU4ImmOperand(), llvm::PPCInstPrinter::printU5ImmOperand(), llvm::PPCInstPrinter::printU6ImmOperand(), llvm::AArch64InstPrinter::printUImm12Offset(), llvm::AssemblyWriter::printUseListOrder(), llvm::AArch64InstPrinter::printVRegOperand(), priorNonDebug(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::AArch64_AM::processLogicalImmediate(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), ProcessUMulZExtIdiom(), llvm::ListInit::Profile(), ProfileDagInit(), PromoteSplat(), ProvideOption(), llvm::PtrToIntInst::PtrToIntInst(), llvm::PMStack::push(), llvm::TinyPtrVector< EltTy >::push_back(), llvm::ARM::WinEH::RuntimeFunction::R(), rangeMetadataExcludesValue(), llvm::sampleprof::SampleProfileReaderText::read(), llvm::coverage::RawCoverageMappingReader::read(), llvm::BitstreamCursor::Read(), readAbbreviatedField(), llvm::StreamingMemoryObject::readBytes(), ReadDataFromGlobal(), llvm::sys::RWMutexImpl::reader_acquire(), llvm::sys::RWMutexImpl::reader_release(), readExponent(), llvm::GCOVFile::readGCDA(), llvm::BitstreamCursor::readRecord(), llvm::MachineOperand::readsReg(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::PMDataManager::recordAvailableAnalysis(), llvm::StackMaps::recordPatchPoint(), llvm::MachineDominatorTree::recordSplitCriticalEdge(), llvm::StackMaps::recordStackMap(), llvm::StackMaps::recordStatepoint(), llvm::RecordVal::RecordVal(), redirectValuesFromPredecessorsToPhi(), llvm::LPPassManager::redoLoop(), llvm::ARM::WinEH::RuntimeFunction::Reg(), regIsPICBase(), registerADRCandidate(), llvm::PassRegistry::registerAnalysisGroup(), llvm::AssumptionCache::registerAssumption(), llvm::ManagedStaticBase::RegisterManagedStatic(), llvm::PassRegistry::registerPass(), llvm::detail::AnalysisManagerBase< AnalysisManager< IRUnitT >, IRUnitT >::registerPass(), llvm::TargetRegistry::RegisterTarget(), llvm::RefCountedBase< DirIterState >::Release(), llvm::sys::MutexImpl::release(), llvm::RefCountedBaseVPTR::Release(), llvm::ThreadSafeRefCountedBase< Derived >::Release(), llvm::ImutAVLTree< ImutInfo >::release(), llvm::ConvergingVLIWScheduler::releaseBottomNode(), llvm::ScalarEvolution::releaseMemory(), llvm::SchedBoundary::releaseNode(), llvm::StatepointLoweringState::relocCallVisited(), llvm::APFloat::remainder(), llvm::RemapInstruction(), llvm::LiveRangeEdit::rematerializeAt(), llvm::LatencyPriorityQueue::remove(), llvm::SetVector< llvm::BasicBlock * >::remove(), llvm::ResourcePriorityQueue::remove(), llvm::iplist< Argument >::remove(), llvm::MachineBasicBlock::remove(), llvm::ConstantUniqueMap< llvm::ConstantExpr >::remove(), llvm::ImutAVLFactory< ImutInfo >::remove_internal(), llvm::Argument::removeAttr(), llvm::AttrBuilder::removeAttribute(), llvm::AttributeSet::removeAttributes(), llvm::AttrBuilder::removeAttributes(), llvm::DominanceFrontierBase< BlockT >::removeBlock(), llvm::R600InstrInfo::RemoveBranch(), llvm::CallGraphNode::removeCallEdgeFor(), llvm::SwitchInst::removeCase(), llvm::LoopBase< BasicBlock, Loop >::removeChildLoop(), llvm::FastISel::removeDeadCode(), RemoveDeadConstant(), llvm::IndirectBrInst::removeDestination(), removeDuplicatesGCPtrs(), llvm::LazyCallGraph::removeEdge(), llvm::MachineInstr::removeFromBundle(), llvm::DominanceFrontierBase< BlockT >::removeFromFrontier(), llvm::MachineFunction::removeFromMBBNumbering(), llvm::MachineBasicBlock::removeFromParent(), llvm::MachineInstr::removeFromParent(), RemoveFromReverseMap(), llvm::RemoveFromVector(), llvm::CallGraph::removeFunctionFromModule(), llvm::PHINode::removeIncomingValue(), RemoveInstInputs(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::LazyCallGraph::SCC::removeInterSCCEdge(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), llvm::StringMapImpl::RemoveKey(), llvm::cl::parser< const PassInfo * >::removeLiteralOption(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::removeLoop(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::ImutAVLFactory< ImutInfo >::removeMinBinding(), llvm::DominatorTreeBase< BasicBlock >::removeNode(), llvm::CallGraphNode::removeOneAbstractEdgeTo(), llvm::MachineInstr::RemoveOperand(), llvm::SUnit::removePred(), llvm::BasicBlock::removePredecessor(), llvm::SchedBoundary::removeReady(), llvm::LivePhysRegs::removeReg(), llvm::MachineRegisterInfo::removeRegOperandFromUseList(), llvm::LiveRange::removeSegment(), llvm::RegionBase< RegionTr >::removeSubRegion(), llvm::MachineBasicBlock::removeSuccessor(), removeUndefValue(), llvm::removeUnreachableBlocks(), RemoveUnusedGlue(), llvm::LiveVariables::removeVirtualRegisterDead(), llvm::LiveVariables::removeVirtualRegisterKilled(), llvm::LiveVariables::removeVirtualRegistersKilled(), RemoveVRSaveCode(), llvm::MachineFunction::RenumberBlocks(), llvm::LiveRange::RenumberValues(), ReorganizeVector(), llvm::SlotIndexes::repairIndexesInRange(), repeat(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::DIDescriptor::replaceAllUsesWith(), llvm::Value::replaceAllUsesWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::replaceAndRecursivelySimplify(), llvm::CallGraphNode::replaceCallEdge(), llvm::LoopBase< N, M >::replaceChildLoopWith(), llvm::replaceDbgDeclareForAlloca(), llvm::InstCombiner::replacedSelectWithOperand(), llvm::RegionBase< RegionTr >::replaceExit(), llvm::DICompileUnit::replaceGlobalVariables(), llvm::ReplaceInstWithInst(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::MachineJumpTableInfo::ReplaceMBBInJumpTable(), llvm::MachineJumpTableInfo::ReplaceMBBInJumpTables(), llvm::CallGraphSCC::ReplaceNode(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::ConstantUniqueMap< llvm::ConstantExpr >::replaceOperandsInPlace(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::DICompileUnit::replaceSubprograms(), llvm::MachineBasicBlock::replaceSuccessor(), llvm::MachineBasicBlock::ReplaceUsesOfBlockWith(), llvm::User::replaceUsesOfWith(), llvm::Constant::replaceUsesOfWithOnConstant(), llvm::GlobalVariable::replaceUsesOfWithOnConstant(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::Constant::replaceUsesOfWithOnConstantImpl(), llvm::Value::replaceUsesOutsideBlock(), llvm::DIBuilder::replaceVTableHolder(), replicateChunk(), llvm::DFAPacketizer::reserveResources(), llvm::StatepointLoweringState::reserveStackSlot(), llvm::PBQP::Matrix::reset(), llvm::BitVector::reset(), llvm::SmallBitVector::reset(), llvm::SchedBoundary::reset(), llvm::MachineRegisterInfo::resetDelegate(), resetVRegCycle(), llvm::DIRef< T >::resolve(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), llvm::UniquableMDNode::resolveCycles(), llvm::Thumb1RegisterInfo::resolveFrameIndex(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::OpInit::resolveListElementReference(), llvm::VarInit::resolveListElementReference(), llvm::RuntimeDyldMachOI386::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), llvm::RuntimeDyldMachOAArch64::resolveRelocation(), llvm::TargetSchedModel::resolveSchedClass(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), RestoreSpillList(), llvm::raw_svector_ostream::resync(), llvm::ARM::WinEH::RuntimeFunction::Ret(), llvm::MetadataTracking::retrack(), reuseTableCompare(), llvm::MipsInstrInfo::ReverseBranchCondition(), llvm::MSP430InstrInfo::ReverseBranchCondition(), llvm::XCoreInstrInfo::ReverseBranchCondition(), llvm::PPCInstrInfo::ReverseBranchCondition(), llvm::SystemZInstrInfo::ReverseBranchCondition(), llvm::X86InstrInfo::ReverseBranchCondition(), llvm::rewriteARMFrameIndex(), llvm::Thumb1RegisterInfo::rewriteFrameIndex(), RewriteHeapSROALoadUser(), RewriteIntelBracExpression(), rewriteLoopExitBlock(), rewriteSingleStoreAlloca(), llvm::rewriteT2FrameIndex(), llvm::RNSuccIterator< FlatIt< NodeType >, BlockT, RegionT >::RNSuccIterator(), llvm::ARM_AM::rotl32(), llvm::ARM_AM::rotr32(), llvm::APInt::roundToDouble(), llvm::RoundUpTo(), llvm::CGSCCAnalysisManagerModuleProxy::run(), llvm::DAGTypeLegalizer::run(), llvm::LoadAndStorePromoter::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::run(), llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::FunctionAnalysisManagerModuleProxy::run(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::BranchProbabilityInfo::runOnFunction(), llvm::IntervalPartition::runOnFunction(), llvm::PEI::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::JumpInstrTables::runOnModule(), llvm::CrashRecoveryContext::RunSafely(), llvm::sys::RWMutexImpl::RWMutexImpl(), llvm::IntervalMapImpl::LeafNode< typename, typename, unsigned, typename >::safeFind(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, RootBranchCap, Traits >::safeFind(), llvm::HexagonMCInst::SanityCheckImplicitOperands(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), scale(), llvm::RegScavenger::scavengeRegister(), llvm::VLIWMachineScheduler::schedule(), llvm::ScheduleDAGMI::schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::ScheduleDAGInstrs::ScheduleDAGInstrs(), llvm::ScheduleDAGMILive::scheduleMI(), llvm::PMTopLevelManager::schedulePass(), llvm::SDep::SDep(), llvm::SDLoc::SDLoc(), llvm::SDNode::SDNode(), llvm::SDValue::SDValue(), searchForVNI(), llvm::LiveRange::Segment::Segment(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::SelectionDAGISel::SelectCodeCommon(), selectIncomingValueForBlock(), llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands(), llvm::FastISel::selectIntrinsicCall(), llvm::SplitEditor::selectIntv(), llvm::FastISel::selectPatchpoint(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::FastISel::selectStackmap(), llvm::EngineBuilder::selectTarget(), separateNestedLoop(), llvm::StackMaps::serializeToStackMapSection(), llvm::FunctionLoweringInfo::set(), llvm::BitVector::set(), llvm::SmallBitVector::set(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::set_size(), llvm::GlobalAlias::setAliasee(), llvm::GlobalObject::setAlignment(), llvm::AllocaInst::setAlignment(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setArgument(), llvm::TargetLibraryInfo::setAvailableWithName(), llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::MCELF::SetBinding(), llvm::StructType::setBody(), llvm::MCAssembler::setBundleAlignSize(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setCalledFunction(), llvm::PBQP::Matrix::setCol(), llvm::MCSymbolData::setCommon(), llvm::TargetLoweringBase::setCondCodeAction(), llvm::BranchInst::setCondition(), llvm::yaml::Input::setCurrentDocument(), llvm::MachineInstr::setDebugLoc(), llvm::MachinePassRegistry::setDefault(), llvm::MachineRegisterInfo::setDelegate(), llvm::MemIntrinsic::setDest(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomain(), llvm::MCOperand::setExpr(), llvm::AtomicCmpXchgInst::setFailureOrdering(), llvm::Instruction::setFastMathFlags(), llvm::MCOperand::setFPImm(), llvm::MachineOperand::setFPImm(), llvm::GlobalObject::setGlobalObjectSubClassData(), llvm::GlobalValue::setGlobalValueSubClassData(), llvm::Instruction::setHasAllowReciprocal(), llvm::Instruction::setHasNoInfs(), llvm::Instruction::setHasNoNaNs(), llvm::Instruction::setHasNoSignedZeros(), llvm::Instruction::setHasUnsafeAlgebra(), llvm::DomTreeNodeBase< NodeT >::setIDom(), llvm::MCOperand::setImm(), llvm::MachineOperand::setImm(), llvm::R600InstrInfo::setImmOperand(), llvm::MachineOperand::setImplicit(), llvm::MachineOperand::setIndex(), llvm::TargetLoweringBase::setIndexedLoadAction(), llvm::TargetLoweringBase::setIndexedStoreAction(), llvm::GlobalVariable::setInitializer(), llvm::IRBuilderBase::SetInsertPoint(), llvm::MCOperand::setInst(), llvm::SUnit::setInstr(), llvm::Instruction::setInstructionSubclassData(), llvm::PointerIntPair< void *, 1, bool, PointerUnionUIntTraits< const Value *, const PseudoSourceValue * > >::setInt(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsDebug(), llvm::MachineOperand::setIsDef(), llvm::MachineOperand::setIsEarlyClobber(), llvm::MachineOperand::setIsInternalRead(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsUndef(), llvm::SCEVExpander::setIVIncInsertPos(), llvm::PMTopLevelManager::setLastUser(), llvm::MemIntrinsic::setLength(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::StatepointLoweringState::setLocation(), llvm::Loop::setLoopID(), llvm::Module::setMaterializer(), llvm::MachineOperand::setMBB(), llvm::MachineInstr::setMemRefs(), llvm::MachineSDNode::setMemRefs(), llvm::Instruction::setMetadata(), llvm::Value::setName(), llvm::SUnit::setNode(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::MachineFrameInfo::setObjectOffset(), llvm::MachineFrameInfo::setObjectSize(), llvm::MachineOperand::setOffset(), llvm::MCSymbolData::setOffset(), llvm::User::setOperand(), llvm::MDNode::setOperand(), llvm::NamedMDNode::setOperand(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetPassConfig::setOpt(), llvm::AtomicRMWInst::setOrdering(), llvm::PointerIntPair< void *, 1, bool, PointerUnionUIntTraits< const Value *, const PseudoSourceValue * > >::setPointer(), llvm::PointerIntPair< void *, 1, bool, PointerUnionUIntTraits< const Value *, const PseudoSourceValue * > >::setPointerAndInt(), llvm::SCEVExpander::setPostInc(), llvm::RuntimeDyld::setProcessAllSections(), llvm::MCOperand::setReg(), llvm::SDep::setReg(), llvm::MachineRegisterInfo::setRegClass(), llvm::CoalescerPair::setRegisters(), llvm::StatepointLoweringState::setRelocLocation(), llvm::Pass::setResolver(), llvm::XCoreFunctionInfo::setReturnStackOffset(), llvm::SelectionDAG::setRoot(), llvm::PBQP::Matrix::setRow(), llvm::MCSectionCOFF::setSelection(), llvm::PBQP::Graph< RegAllocSolverImpl >::setSolver(), llvm::MemTransferInst::setSource(), llvm::IVVisitor::setSplitOverflowIntrinsics(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStop(), llvm::Type::setSubclassData(), llvm::MachineOperand::setSubReg(), llvm::BranchInst::setSuccessor(), llvm::SwitchInst::setSuccessor(), llvm::InvokeInst::setSuccessor(), llvm::AtomicCmpXchgInst::setSuccessOrdering(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::MachineOperand::setTargetFlags(), llvm::MCAsmParser::setTargetParser(), llvm::GlobalValue::setThreadLocalMode(), llvm::X86Operand::setTokenValue(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::MCELF::SetType(), llvm::Type::setTypeID(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::setUniverse(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::setUniverse(), llvm::SelectionDAGBuilder::setUnusedArgValue(), llvm::PackedVectorBase< T, BitNum, BitVectorTy, false >::setValue(), llvm::PackedVectorBase< T, BitNum, BitVectorTy, true >::setValue(), llvm::MemSetInst::setValue(), llvm::SelectionDAGBuilder::setValue(), llvm::SwitchInst::CaseIt::setValue(), llvm::MCSymbol::setVariableValue(), llvm::MCELF::SetVisibility(), llvm::GlobalValue::setVisibility(), llvm::APInt::sext(), llvm::SExtInst::SExtInst(), shiftRightAndRound(), llvm::APInt::shl(), llvm::AArch64TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::ARMTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::PPCTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::X86TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::AMDGPUInstrInfo::shouldScheduleLoadsNear(), llvm::ARMBaseInstrInfo::shouldScheduleLoadsNear(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), shouldUseMmap(), ShrinkDemandedConstant(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), llvm::BitcodeReaderValueList::shrinkTo(), llvm::BitcodeReaderMDValueList::shrinkTo(), llvm::LiveIntervals::shrinkToUses(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ConstantRange::signExtend(), SimplifyAssociativeBinOp(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), llvm::TargetLowering::SimplifyDemandedBits(), SimplifyFCmpInst(), SimplifyICmpInst(), llvm::SimplifyInstructionsInBlock(), simplifyOneLoop(), llvm::TargetLowering::SimplifySetCC(), SimplifyShortImmForm(), SimplifyShortMoveForm(), SinkThenElseCodeToEnd(), llvm::SIToFPInst::SIToFPInst(), llvm::PooledStringPtr::size(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::size(), llvm::DIETypeSignature::SizeOf(), llvm::yaml::skip(), skipAbbreviatedField(), skipAlignedDPRCS2Spills(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), skipLeadingZeroesAndAnyDot(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), llvm::BitstreamCursor::skipRecord(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::ArrayRef< uint64_t >::slice(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::slice(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SlotIndex::SlotIndex(), llvm::APInt::slt(), llvm::SmallPtrSetImplBase::SmallPtrSetImplBase(), llvm::SMFixIt::SMFixIt(), llvm::SMRange::SMRange(), llvm::TargetLowering::softenSetCCOperands(), SolveLinEquationWithOverflow(), SolveQuadraticEquation(), llvm::Value::sortUseList(), speculateSelectInstLoads(), SpeculativelyExecuteBB(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), spillIncomingStatepointValue(), split(), llvm::DominatorTreeBase< BasicBlock >::Split(), splitAndLowerVectorShuffle(), llvm::BasicBlock::splitBasicBlock(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SplitEdge(), llvm::SplitLandingPadPredecessors(), llvm::SplitEditor::splitLiveThroughBlock(), llvm::SplitEditor::splitRegInBlock(), llvm::SplitEditor::splitRegOutBlock(), llvm::SelectionDAG::SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::APInt::sqrt(), SRAGlobal(), srcMgrDiagHandler(), llvm::ARM::WinEH::RuntimeFunction::StackAdjust(), StackMallocSizeClass(), llvm::TargetRegisterInfo::stackSlot2Index(), llvm::IntervalMap< SlotIndex, unsigned >::start(), llvm::AggressiveAntiDepBreaker::StartBlock(), llvm::DbgValueHistoryMap::startInstrRange(), llvm::StatepointLoweringState::startNewStatepoint(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::StatepointBase(), llvm::CallGraphNode::stealCalledFunctionsFrom(), llvm::LivePhysRegs::stepForward(), llvm::IntervalMap< SlotIndex, unsigned >::stop(), llvm::Timer::stopTimer(), llvm::UniquableMDNode::storeDistinctInContext(), StoreIntToMemory(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), StrengthenNoWrapFlags(), llvm::StringRef::StringRef(), llvm::Value::stripAndAccumulateInBoundsConstantOffsets(), stripAndComputeConstantOffsets(), StripPtrCastKeepAS(), stripTrailingZeros(), llvm::PBQP::Matrix::subFromCol(), llvm::PBQP::Matrix::subFromRow(), llvm::MachineOperand::substPhysReg(), llvm::MachineOperand::substVirtReg(), llvm::PPCInstrInfo::SubsumesPredicate(), llvm::ConstantRange::subtract(), llvm::AArch64InstrInfo::suppressLdStPair(), llvm::SmallPtrSetImplBase::swap(), llvm::iplist< Argument >::swap(), llvm::BranchInst::swapSuccessors(), switch(), llvm::MCStreamer::SwitchSection(), llvm::MCStreamer::SwitchSectionNoChange(), SwitchToLookupTable(), SwitchToSelect(), SymbolicallyEvaluateGEP(), llvm::BitstreamReader::takeBlockInfo(), llvm::Value::takeName(), llvm::APInt::tcAdd(), llvm::APInt::tcDivide(), llvm::APInt::tcExtract(), llvm::APInt::tcFullMultiply(), llvm::APInt::tcMultiply(), llvm::APInt::tcMultiplyPart(), llvm::APInt::tcSet(), llvm::APInt::tcSubtract(), ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), ThreadCmpOverPHI(), ThreadCmpOverSelect(), llvm::MachineInstr::tieOperands(), llvm::Timer::Timer(), toCallerWindow(), llvm::ScaledNumber< DigitsT >::toInt(), llvm::APFloat::toString(), llvm::AArch64SysReg::SysRegMapper::toString(), llvm::APInt::toString(), toStringAPFloat(), llvm::object::COFFObjectFile::toSymb(), totalExponent(), trackRegDefsUses(), trailingHexadecimalFraction(), transferImpOps(), llvm::JumpInstrTables::transformType(), translateDstIndex(), translateShiftImm(), translateSrcIndex(), llvm::PBQP::Matrix::transpose(), llvm::APInt::trunc(), llvm::ConstantRange::truncate(), truncateToSize(), llvm::TruncInst::TruncInst(), llvm::sys::MutexImpl::tryacquire(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), tryCombineToEXTR(), llvm::tryFoldSPUpdateIntoPushPop(), tryOrrMovk(), trySequenceOfOnes(), tryToFoldExtendOfConstant(), llvm::FastISel::tryToFoldLoad(), tryToMoveFreeBeforeNullTest(), llvm::BitcodeReaderMDValueList::tryToResolveCycles(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), TryToSinkInstruction(), TurnSwitchRangeIntoICmp(), llvm::Twine::Twine(), TypeSizeToSizeIndex(), TypeToFloatSemantics(), llvm::APInt::udiv(), llvm::APInt::udivrem(), llvm::UIToFPInst::UIToFPInst(), ulpsFromBoundary(), llvm::APInt::ult(), llvm::MachineInstr::unbundleFromPred(), llvm::MachineInstr::unbundleFromSucc(), llvm::sys::UnicodeCharSet::UnicodeCharSet(), llvm::AggressiveAntiDepState::UnionGroups(), llvm::EquivalenceClasses< ElemTy >::unionSets(), llvm::ConstantRange::unionWith(), uniqueSuperReg(), llvm::unique_lock< MutexT >::unlock(), llvm::sys::SmartMutex< false >::unlock(), llvm::sys::SmartRWMutex< true >::unlock(), llvm::sys::SmartRWMutex< true >::unlock_shared(), llvm::RegScavenger::unprocess(), UnrollCountPragmaValue(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopProlog(), llvm::SelectionDAG::UnrollVectorOp(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue(), llvm::PBQP::Graph< RegAllocSolverImpl >::unsetSolver(), llvm::MetadataTracking::untrack(), UpdateCPSRUse(), llvm::AntiDepBreaker::UpdateDbgValue(), llvm::MMIAddrLabelMap::UpdateForDeletedBlock(), llvm::MMIAddrLabelMap::UpdateForRAUWBlock(), llvm::ExecutionEngine::updateGlobalMapping(), llvm::SelectionDAG::UpdateNodeOperands(), updateOperand(), UpdateOperandRegClass(), llvm::ScheduleDAGMILive::updatePressureDiffs(), llvm::MachineBasicBlock::updateTerminator(), llvm::LoopInfo::updateUnloop(), llvm::UpgradeCallsToIntrinsic(), upgradeGlobalArray(), llvm::UpgradeInstWithTBAATag(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), llvm::APInt::urem(), llvm::SplitEditor::useIntv(), llvm::ImutAVLTree< ImutInfo >::validateTree(), llvm::DebugLocEntry::Value::Value(), llvm::Value::Value(), llvm::ValueAsMetadata::ValueAsMetadata(), llvm::ValueHandleBase::ValueIsDeleted(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::DbgVariable::variableHasComplexAddress(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::verify(), llvm::MachineTraceMetrics::Ensemble::verify(), llvm::LiveRange::verify(), llvm::DISubprogram::Verify(), llvm::LiveInterval::verify(), llvm::MachineTraceMetrics::verifyAnalysis(), llvm::AssumptionCacheTracker::verifyAnalysis(), llvm::LoopInfo::verifyAnalysis(), llvm::ScalarEvolution::verifyAnalysis(), llvm::verifyFunction(), llvm::verifyIntrinsicTables(), llvm::LoopBase< N, M >::verifyLoop(), llvm::ScheduleDAG::VerifyScheduledDAG(), llvm::ScheduleDAGSDNodes::VerifyScheduledSequence(), VerifySDNode(), VerifySubsetOf(), llvm::MachineRegisterInfo::verifyUseList(), llvm::LiveIntervalUnion::Query::virtReg(), llvm::TargetRegisterInfo::virtReg2Index(), llvm::Interpreter::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::Interpreter::visitAShr(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitCallInst(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitCallSite(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::InstCombiner::visitLandingPadInst(), llvm::Interpreter::visitLShr(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), llvm::InstCombiner::visitSExt(), llvm::Interpreter::visitShl(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSub(), llvm::SelectionDAGBuilder::visitSwitchCase(), llvm::InstCombiner::visitSwitchInst(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitZExt(), llvm::VLIWResourceModel::VLIWResourceModel(), llvm::StatepointBase< const Instruction, const Value, ImmutableCallSite >::vm_state_end(), wasEscaped(), WidenMaskArithmetic(), llvm::SparseBitVectorElement< ElementSize >::word(), llvm::coverage::CoverageMappingWriter::write(), llvm::raw_ostream::write(), llvm::WriteAsOperandInternal(), llvm::AssemblyWriter::writeAtomicCmpXchg(), llvm::MCObjectWriter::WriteBytes(), WriteConstants(), llvm::MachObjectWriter::WriteDysymtabLoadCommand(), writeFragment(), WriteFunction(), WriteFunctionLocalMetadata(), llvm::MachObjectWriter::WriteHeader(), WriteInstruction(), llvm::MachObjectWriter::WriteLinkeditLoadCommand(), llvm::MachObjectWriter::WriteLinkerOptionsLoadCommand(), WriteMDNode(), llvm::MachObjectWriter::WriteNlist(), llvm::MachObjectWriter::WriteObject(), llvm::sys::RWMutexImpl::writer_acquire(), llvm::sys::RWMutexImpl::writer_release(), llvm::MachObjectWriter::WriteSection(), llvm::MCAssembler::writeSectionData(), llvm::MachObjectWriter::WriteSegmentLoadCommand(), llvm::MachObjectWriter::WriteSymtabLoadCommand(), WriteUseList(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), llvm::X86Subtarget::X86Subtarget(), llvm::yaml::yamlize(), llvm::InstCombineWorklist::Zap(), llvm::ConstantRange::zeroExtend(), llvm::APInt::zext(), llvm::ZExtInst::ZExtInst(), llvm::ArrayRecycler< llvm::MachineOperand >::~ArrayRecycler(), llvm::AsmPrinter::~AsmPrinter(), llvm::BasicBlock::~BasicBlock(), llvm::BitcodeReaderValueList::~BitcodeReaderValueList(), llvm::BitstreamWriter::~BitstreamWriter(), llvm::CallGraphNode::~CallGraphNode(), llvm::SelectionDAG::DAGUpdateListener::~DAGUpdateListener(), llvm::Instruction::~Instruction(), llvm::LazyValueInfo::~LazyValueInfo(), llvm::MachineFunctionAnalysis::~MachineFunctionAnalysis(), llvm::MMIAddrLabelMap::~MMIAddrLabelMap(), llvm::sys::MutexImpl::~MutexImpl(), llvm::PrettyStackTraceEntry::~PrettyStackTraceEntry(), llvm::raw_ostream::~raw_ostream(), llvm::Recycler< llvm::MachineInstr >::~Recycler(), llvm::ReplaceableMetadataImpl::~ReplaceableMetadataImpl(), llvm::sys::RWMutexImpl::~RWMutexImpl(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::~ScopedHashTable(), llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope(), llvm::SelectionDAG::~SelectionDAG(), llvm::StringPool::~StringPool(), llvm::Value::~Value(), and llvm::ValueSymbolTable::~ValueSymbolTable().
for (size_t i = 0, e = Globals.size(); i != e;)
Definition at line 174 of file GlobalMerge.cpp.
References llvm::GlobalAlias::create(), llvm::GlobalValue::ExternalLinkage, llvm::ConstantInt::get(), llvm::StructType::get(), llvm::ConstantStruct::get(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::GlobalValue::InternalLinkage, Name, and llvm::GlobalValue::NotThreadLocal.
STATISTIC (NumMerged , "Number of globals merged")
Variable Documentation
INITIALIZE_TM_PASS (GlobalMerge, "global-merge", "Merge global variables", false, false) bool GlobalMerge const DataLayout* DL = TLI->getDataLayout()
Definition at line 147 of file GlobalMerge.cpp.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::detail::PtrUseVisitorBase::adjustOffsetForGEP(), llvm::MipsSEInstrInfo::adjustStackPtr(), AnalyzeLoadFromClobberingMemInst(), llvm::DwarfDebug::beginInstruction(), llvm::X86TargetLowering::BuildFILD(), buildFromShuffleMostly(), llvm::BuildMI(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::InstCombiner::commonCastTransforms(), llvm::InstCombiner::commonPointerCastTransforms(), computeArraySize(), llvm::InstCombiner::computeKnownBits(), llvm::InstCombiner::ComputeNumSignBits(), llvm::InstCombiner::computeOverflowForUnsignedAdd(), llvm::InstCombiner::computeOverflowForUnsignedMul(), llvm::InstCombiner::ComputeSignBit(), ConstantFold(), ConstantFoldLoadThroughBitcast(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), convertLocVTToValVT(), createFPCmp(), createLoadLR(), createStoreLR(), llvm::DataLayout::DataLayout(), llvm::AsmPrinter::doFinalization(), llvm::InstCombiner::DoOneIteration(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::MSP430FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), emitSPUpdate(), llvm::LazyValueInfo::eraseBlock(), EvaluateExpression(), EvaluateGEPOffsetExpression(), llvm::SparcTargetLowering::expandAtomicRMW(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::FindAvailableLoadedValue(), fixupLineNumbers(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::InstCombiner::FoldGEPICmp(), FoldMaskAndShiftToExtract(), FoldMaskAndShiftToScale(), FoldMaskedShiftToScaledMask(), FoldTwoEntryPHINode(), GenerateTBL(), getAArch64XALUOOp(), getBuildVectorSplat(), getCache(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), getCopyFromPartsVector(), getCTPOP16BitCounts(), llvm::InstCombiner::getDataLayout(), llvm::ExecutionEngine::getDataLayout(), llvm::MachineFunction::getJTISymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), GetLinearExpression(), GetLoadValueForLoad(), getLocForWrite(), llvm::SelectionDAG::getNode(), llvm::MachineFunction::getPICBaseSymbol(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateOnEdge(), getPredicateResult(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::SelectionDAG::getSelect(), GetSymbolFromOperand(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::getX86SubSuperRegister(), InitializeUniqueCases(), llvm::MCRegisterInfo::InitMCRegisterInfo(), llvm::MipsInstrInfo::insertNoop(), llvm::PPCInstrInfo::insertNoop(), insertNopBeforeInstruction(), llvm::object::IRObjectFile::IRObjectFile(), llvm::Value::isDereferenceablePointer(), isDereferenceablePointer(), isGEPKnownNonNull(), isIntegerWideningViable(), isOverwrite(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), llvm::isSafeToLoadUnconditionally(), isSimpleEnoughValueToCommitHelper(), isVectorPromotionViable(), llvm::AMDGPUTargetLowering::isZExtFree(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::X86InstrInfo::loadRegFromAddr(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::loadRegFromStackSlot(), lower256BitVectorShuffle(), lower512BitVectorShuffle(), LowerBITCAST(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), lowerCTPOP16BitElements(), lowerCTPOP32BitElements(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::AMDGPUTargetLowering::LowerIntrinsicIABS(), llvm::AMDGPUTargetLowering::LowerIntrinsicLRP(), LowerLabelRef(), llvm::AMDGPUTargetLowering::LowerLOAD(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatZExt(), lowerMSAStoreIntr(), LowerMUL(), llvm::R600TargetLowering::LowerOperation(), LowerPREFETCH(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::AMDGPUTargetLowering::LowerSTORE(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerV16F32VectorShuffle(), lowerV16I16VectorShuffle(), lowerV16I32VectorShuffle(), lowerV16I8VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV32I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV4I64VectorShuffle(), lowerV64I8VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8F64VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), lowerV8I16VectorShuffle(), lowerV8I32VectorShuffle(), lowerV8I64VectorShuffle(), LowerVAARG(), LowerVASTART(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorIntExtend(), lowerVectorShuffleAsInsertPS(), llvm::SparcTargetLowering::makeAddress(), llvm::Mips16InstrInfo::makeFrame(), llvm::SparcTargetLowering::makeHiLoPair(), llvm::InstCombiner::MaskedValueIsZero(), matchAddSub(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), NarrowVector(), llvm::DebugLoc::operator!=(), WidenVector::operator()(), llvm::InstCombiner::OptimizePointerDifference(), performADDCombine(), PerformBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), performDivRemCombine(), performExtendCombine(), performIntegerAbsCombine(), performSELECTCombine(), performSelectCombine(), performSTORECombine(), performVectorCompareAndMaskUnaryOpCombine(), llvm::AssemblyWriter::printModule(), llvm::MipsAsmPrinter::printOperand(), llvm::AsmPrinter::PrintSpecial(), llvm::X86InstrInfo::reMaterialize(), ReplaceBITCASTResults(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), replaceSplatVectorStore(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), restoreCRs(), llvm::Mips16InstrInfo::restoreFrame(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::LazyValueInfo::runOnFunction(), llvm::InstCombiner::runOnFunction(), llvm::Inliner::runOnSCC(), llvm::Mips16RegisterInfo::saveScavengerRegister(), llvm::Thumb1RegisterInfo::saveScavengerRegister(), selectMADD(), selectMSUB(), llvm::FunctionLoweringInfo::set(), llvm::ExecutionEngine::setDataLayout(), llvm::SimplifyInstruction(), llvm::simplifyLoop(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::X86InstrInfo::storeRegToAddr(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), SwitchToLookupTable(), llvm::LazyValueInfo::threadEdge(), tryCombineFixedPointConvert(), tryCombineToBSL(), tryCombineToEXTR(), tryFormConcatFromShuffle(), tryLowerToSLI(), llvm::UnrollLoop(), llvm::DISubprogram::Verify(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFRem(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::InstCombiner::visitIntToPtr(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPtrToInt(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitSwitchInst(), llvm::InstCombiner::visitUDiv(), llvm::InstCombiner::visitURem(), llvm::InstCombiner::visitXor(), WidenVector(), WriteFunction(), and WriteModuleInfo().
cl::opt<bool> EnableGlobalMerge("enable-global-merge", cl::Hidden, cl::desc("Enable global merge pass"), cl::init(true)) static
cl::opt<bool> EnableGlobalMergeOnConst("global-merge-on-const", cl::Hidden, cl::desc("Enable global merge pass on constants"), cl::init(false)) static
cl::opt<bool> EnableGlobalMergeOnExternal("global-merge-on-external", cl::Hidden, cl::desc("Enable global merge pass on external linkage"), cl::init(false)) static
Type* Int32Ty = Type::getInt32Ty(M.getContext())
Definition at line 163 of file GlobalMerge.cpp.
Referenced by llvm::Module::addModuleFlag(), llvm::MDBuilder::createBranchWeights(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainderUpTo32Bits(), llvm::JumpInstrTables::transformType(), llvm::InstCombiner::visitExtractElementInst(), and llvm::InstCombiner::visitShuffleVectorInst().
unsigned MaxOffset = TLI->getMaximalGlobalOffset()
Definition at line 152 of file GlobalMerge.cpp.
return true
Definition at line 239 of file GlobalMerge.cpp.