LLVM: Dwarf constants dumping functions
LLVM API Documentation
Dwarf constants dumping functions
Functions
const char * llvm::dwarf::TagString (unsigned Tag)
const char * llvm::dwarf::ChildrenString (unsigned Children)
const char * llvm::dwarf::AttributeString (unsigned Attribute)
const char * llvm::dwarf::FormEncodingString (unsigned Encoding)
const char * llvm::dwarf::OperationEncodingString (unsigned Encoding)
const char * llvm::dwarf::AttributeEncodingString (unsigned Encoding)
const char * llvm::dwarf::DecimalSignString (unsigned Sign)
const char * llvm::dwarf::EndianityString (unsigned Endian)
const char * llvm::dwarf::AccessibilityString (unsigned Access)
const char * llvm::dwarf::VisibilityString (unsigned Visibility)
const char * llvm::dwarf::VirtualityString (unsigned Virtuality)
const char * llvm::dwarf::LanguageString (unsigned Language)
const char * llvm::dwarf::CaseString (unsigned Case)
const char * llvm::dwarf::ConventionString (unsigned Convention)
const char * llvm::dwarf::InlineCodeString (unsigned Code)
const char * llvm::dwarf::ArrayOrderString (unsigned Order)
const char * llvm::dwarf::DiscriminantString (unsigned Discriminant)
const char * llvm::dwarf::LNStandardString (unsigned Standard)
const char * llvm::dwarf::LNExtendedString (unsigned Encoding)
const char * llvm::dwarf::MacinfoString (unsigned Encoding)
const char * llvm::dwarf::CallFrameString (unsigned Encoding)
const char * llvm::dwarf::ApplePropertyString (unsigned)
const char * llvm::dwarf::AtomTypeString (unsigned Atom)
const char * llvm::dwarf::GDBIndexEntryKindString (GDBIndexEntryKind Kind)
const char * llvm::dwarf::GDBIndexEntryLinkageString (GDBIndexEntryLinkage Linkage)
Detailed Description
All these functions map their argument's value back to the corresponding enumerator name or return nullptr if the value isn't known.
Function Documentation
const char * llvm::dwarf::AccessibilityString (unsigned Access)
Definition at line 520 of file Dwarf.cpp.
References llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, and llvm::dwarf::DW_ACCESS_public.
Referenced by llvm::dwarf::AttributeValueString(), and llvm::DwarfDebug::emitDIE().
const char * llvm::dwarf::ApplePropertyString (unsigned Prop)
Definition at line 711 of file Dwarf.cpp.
References llvm::dwarf::DW_APPLE_PROPERTY_assign, llvm::dwarf::DW_APPLE_PROPERTY_atomic, llvm::dwarf::DW_APPLE_PROPERTY_copy, llvm::dwarf::DW_APPLE_PROPERTY_getter, llvm::dwarf::DW_APPLE_PROPERTY_nonatomic, llvm::dwarf::DW_APPLE_PROPERTY_readonly, llvm::dwarf::DW_APPLE_PROPERTY_readwrite, llvm::dwarf::DW_APPLE_PROPERTY_retain, llvm::dwarf::DW_APPLE_PROPERTY_setter, llvm::dwarf::DW_APPLE_PROPERTY_strong, llvm::dwarf::DW_APPLE_PROPERTY_unsafe_unretained, and llvm::dwarf::DW_APPLE_PROPERTY_weak.
Referenced by dumpApplePropertyAttribute().
const char * llvm::dwarf::ArrayOrderString (unsigned Order)
Definition at line 615 of file Dwarf.cpp.
References llvm::dwarf::DW_ORD_col_major, and llvm::dwarf::DW_ORD_row_major.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::AtomTypeString (unsigned Atom)
Definition at line 741 of file Dwarf.cpp.
References llvm::dwarf::DW_ATOM_cu_offset, llvm::dwarf::DW_ATOM_die_offset, llvm::dwarf::DW_ATOM_die_tag, llvm::dwarf::DW_ATOM_null, and llvm::dwarf::DW_ATOM_type_flags.
Referenced by llvm::DWARFAcceleratorTable::dump(), and llvm::DwarfAccelTable::Atom::print().
const char * llvm::dwarf::AttributeEncodingString (unsigned Encoding)
Definition at line 474 of file Dwarf.cpp.
References llvm::dwarf::DW_ATE_address, llvm::dwarf::DW_ATE_boolean, llvm::dwarf::DW_ATE_complex_float, llvm::dwarf::DW_ATE_decimal_float, llvm::dwarf::DW_ATE_edited, llvm::dwarf::DW_ATE_float, llvm::dwarf::DW_ATE_hi_user, llvm::dwarf::DW_ATE_imaginary_float, llvm::dwarf::DW_ATE_lo_user, llvm::dwarf::DW_ATE_numeric_string, llvm::dwarf::DW_ATE_packed_decimal, llvm::dwarf::DW_ATE_signed, llvm::dwarf::DW_ATE_signed_char, llvm::dwarf::DW_ATE_signed_fixed, llvm::dwarf::DW_ATE_unsigned, llvm::dwarf::DW_ATE_unsigned_char, llvm::dwarf::DW_ATE_unsigned_fixed, and llvm::dwarf::DW_ATE_UTF.
Referenced by llvm::dwarf::AttributeValueString(), and llvm::DIType::printInternal().
const char * llvm::dwarf::AttributeString (unsigned Attribute)
Definition at line 113 of file Dwarf.cpp.
References llvm::dwarf::DW_AT_abstract_origin, llvm::dwarf::DW_AT_accessibility, llvm::dwarf::DW_AT_addr_base, llvm::dwarf::DW_AT_address_class, llvm::dwarf::DW_AT_allocated, llvm::dwarf::DW_AT_APPLE_block, llvm::dwarf::DW_AT_APPLE_flags, llvm::dwarf::DW_AT_APPLE_isa, llvm::dwarf::DW_AT_APPLE_major_runtime_vers, llvm::dwarf::DW_AT_APPLE_objc_complete_type, llvm::dwarf::DW_AT_APPLE_omit_frame_ptr, llvm::dwarf::DW_AT_APPLE_optimized, llvm::dwarf::DW_AT_APPLE_property, llvm::dwarf::DW_AT_APPLE_property_attribute, llvm::dwarf::DW_AT_APPLE_property_getter, llvm::dwarf::DW_AT_APPLE_property_name, llvm::dwarf::DW_AT_APPLE_property_setter, llvm::dwarf::DW_AT_APPLE_runtime_class, llvm::dwarf::DW_AT_artificial, llvm::dwarf::DW_AT_associated, llvm::dwarf::DW_AT_base_types, llvm::dwarf::DW_AT_binary_scale, llvm::dwarf::DW_AT_bit_offset, llvm::dwarf::DW_AT_bit_size, llvm::dwarf::DW_AT_bit_stride, llvm::dwarf::DW_AT_body_begin, llvm::dwarf::DW_AT_body_end, llvm::dwarf::DW_AT_byte_size, llvm::dwarf::DW_AT_byte_stride, llvm::dwarf::DW_AT_call_column, llvm::dwarf::DW_AT_call_file, llvm::dwarf::DW_AT_call_line, llvm::dwarf::DW_AT_calling_convention, llvm::dwarf::DW_AT_common_reference, llvm::dwarf::DW_AT_comp_dir, llvm::dwarf::DW_AT_const_expr, llvm::dwarf::DW_AT_const_value, llvm::dwarf::DW_AT_containing_type, llvm::dwarf::DW_AT_count, llvm::dwarf::DW_AT_data_bit_offset, llvm::dwarf::DW_AT_data_location, llvm::dwarf::DW_AT_data_member_location, llvm::dwarf::DW_AT_decimal_scale, llvm::dwarf::DW_AT_decimal_sign, llvm::dwarf::DW_AT_decl_column, llvm::dwarf::DW_AT_decl_file, llvm::dwarf::DW_AT_decl_line, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_default_value, llvm::dwarf::DW_AT_description, llvm::dwarf::DW_AT_digit_count, llvm::dwarf::DW_AT_discr, llvm::dwarf::DW_AT_discr_list, llvm::dwarf::DW_AT_discr_value, llvm::dwarf::DW_AT_dwo_id, llvm::dwarf::DW_AT_dwo_name, llvm::dwarf::DW_AT_elemental, llvm::dwarf::DW_AT_encoding, llvm::dwarf::DW_AT_endianity, llvm::dwarf::DW_AT_entry_pc, llvm::dwarf::DW_AT_enum_class, llvm::dwarf::DW_AT_explicit, llvm::dwarf::DW_AT_extension, llvm::dwarf::DW_AT_external, llvm::dwarf::DW_AT_frame_base, llvm::dwarf::DW_AT_friend, llvm::dwarf::DW_AT_GNU_addr_base, llvm::dwarf::DW_AT_GNU_dwo_id, llvm::dwarf::DW_AT_GNU_dwo_name, llvm::dwarf::DW_AT_GNU_odr_signature, llvm::dwarf::DW_AT_GNU_pubnames, llvm::dwarf::DW_AT_GNU_pubtypes, llvm::dwarf::DW_AT_GNU_ranges_base, llvm::dwarf::DW_AT_GNU_template_name, llvm::dwarf::DW_AT_GNU_vector, llvm::dwarf::DW_AT_hi_user, llvm::dwarf::DW_AT_high_pc, llvm::dwarf::DW_AT_identifier_case, llvm::dwarf::DW_AT_import, llvm::dwarf::DW_AT_inline, llvm::dwarf::DW_AT_is_optional, llvm::dwarf::DW_AT_language, llvm::dwarf::DW_AT_linkage_name, llvm::dwarf::DW_AT_lo_user, llvm::dwarf::DW_AT_location, llvm::dwarf::DW_AT_low_pc, llvm::dwarf::DW_AT_lower_bound, llvm::dwarf::DW_AT_mac_info, llvm::dwarf::DW_AT_macro_info, llvm::dwarf::DW_AT_main_subprogram, llvm::dwarf::DW_AT_MIPS_abstract_name, llvm::dwarf::DW_AT_MIPS_allocatable_dopetype, llvm::dwarf::DW_AT_MIPS_assumed_shape_dopetype, llvm::dwarf::DW_AT_MIPS_assumed_size, llvm::dwarf::DW_AT_MIPS_clone_origin, llvm::dwarf::DW_AT_MIPS_epilog_begin, llvm::dwarf::DW_AT_MIPS_has_inlines, llvm::dwarf::DW_AT_MIPS_linkage_name, llvm::dwarf::DW_AT_MIPS_loop_begin, llvm::dwarf::DW_AT_MIPS_loop_unroll_factor, llvm::dwarf::DW_AT_MIPS_ptr_dopetype, llvm::dwarf::DW_AT_MIPS_software_pipeline_depth, llvm::dwarf::DW_AT_MIPS_stride, llvm::dwarf::DW_AT_MIPS_stride_byte, llvm::dwarf::DW_AT_MIPS_stride_elem, llvm::dwarf::DW_AT_MIPS_tail_loop_begin, llvm::dwarf::DW_AT_mutable, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_AT_namelist_item, llvm::dwarf::DW_AT_object_pointer, llvm::dwarf::DW_AT_ordering, llvm::dwarf::DW_AT_picture_string, llvm::dwarf::DW_AT_priority, llvm::dwarf::DW_AT_producer, llvm::dwarf::DW_AT_prototyped, llvm::dwarf::DW_AT_pure, llvm::dwarf::DW_AT_ranges, llvm::dwarf::DW_AT_ranges_base, llvm::dwarf::DW_AT_rank, llvm::dwarf::DW_AT_recursive, llvm::dwarf::DW_AT_reference, llvm::dwarf::DW_AT_return_addr, llvm::dwarf::DW_AT_rvalue_reference, llvm::dwarf::DW_AT_segment, llvm::dwarf::DW_AT_sf_names, llvm::dwarf::DW_AT_sibling, llvm::dwarf::DW_AT_signature, llvm::dwarf::DW_AT_small, llvm::dwarf::DW_AT_specification, llvm::dwarf::DW_AT_src_coords, llvm::dwarf::DW_AT_src_info, llvm::dwarf::DW_AT_start_scope, llvm::dwarf::DW_AT_static_link, llvm::dwarf::DW_AT_stmt_list, llvm::dwarf::DW_AT_str_offsets_base, llvm::dwarf::DW_AT_string_length, llvm::dwarf::DW_AT_string_length_bit_size, llvm::dwarf::DW_AT_string_length_byte_size, llvm::dwarf::DW_AT_threads_scaled, llvm::dwarf::DW_AT_trampoline, llvm::dwarf::DW_AT_type, llvm::dwarf::DW_AT_upper_bound, llvm::dwarf::DW_AT_use_location, llvm::dwarf::DW_AT_use_UTF8, llvm::dwarf::DW_AT_variable_parameter, llvm::dwarf::DW_AT_virtuality, llvm::dwarf::DW_AT_visibility, and llvm::dwarf::DW_AT_vtable_elem_location.
Referenced by llvm::DWARFAbbreviationDeclaration::dump(), llvm::DWARFDebugInfoEntryMinimal::dumpAttribute(), llvm::DIEAbbrev::Emit(), llvm::DwarfDebug::emitDIE(), llvm::DIEAbbrev::print(), and llvm::DIE::print().
const char * llvm::dwarf::CallFrameString (unsigned Encoding)
Definition at line 674 of file Dwarf.cpp.
References llvm::dwarf::DW_CFA_advance_loc, llvm::dwarf::DW_CFA_advance_loc1, llvm::dwarf::DW_CFA_advance_loc2, llvm::dwarf::DW_CFA_advance_loc4, llvm::dwarf::DW_CFA_def_cfa, llvm::dwarf::DW_CFA_def_cfa_expression, llvm::dwarf::DW_CFA_def_cfa_offset, llvm::dwarf::DW_CFA_def_cfa_offset_sf, llvm::dwarf::DW_CFA_def_cfa_register, llvm::dwarf::DW_CFA_def_cfa_sf, llvm::dwarf::DW_CFA_expression, llvm::dwarf::DW_CFA_GNU_args_size, llvm::dwarf::DW_CFA_GNU_window_save, llvm::dwarf::DW_CFA_hi_user, llvm::dwarf::DW_CFA_lo_user, llvm::dwarf::DW_CFA_MIPS_advance_loc8, llvm::dwarf::DW_CFA_nop, llvm::dwarf::DW_CFA_offset, llvm::dwarf::DW_CFA_offset_extended, llvm::dwarf::DW_CFA_offset_extended_sf, llvm::dwarf::DW_CFA_register, llvm::dwarf::DW_CFA_remember_state, llvm::dwarf::DW_CFA_restore, llvm::dwarf::DW_CFA_restore_extended, llvm::dwarf::DW_CFA_restore_state, llvm::dwarf::DW_CFA_same_value, llvm::dwarf::DW_CFA_set_loc, llvm::dwarf::DW_CFA_undefined, llvm::dwarf::DW_CFA_val_expression, llvm::dwarf::DW_CFA_val_offset, and llvm::dwarf::DW_CFA_val_offset_sf.
Referenced by llvm::FrameEntry::dumpInstructions(), and llvm::AsmPrinter::EmitCFAByte().
const char * llvm::dwarf::CaseString (unsigned Case)
Definition at line 584 of file Dwarf.cpp.
References llvm::dwarf::DW_ID_case_insensitive, llvm::dwarf::DW_ID_case_sensitive, llvm::dwarf::DW_ID_down_case, and llvm::dwarf::DW_ID_up_case.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::ChildrenString (unsigned Children)
Definition at line 105 of file Dwarf.cpp.
References llvm::dwarf::DW_CHILDREN_no, and llvm::dwarf::DW_CHILDREN_yes.
Referenced by llvm::DIEAbbrev::Emit(), llvm::DIEAbbrev::print(), and llvm::DIE::print().
const char * llvm::dwarf::ConventionString (unsigned Convention)
Definition at line 594 of file Dwarf.cpp.
References llvm::dwarf::DW_CC_hi_user, llvm::dwarf::DW_CC_lo_user, llvm::dwarf::DW_CC_nocall, llvm::dwarf::DW_CC_normal, and llvm::dwarf::DW_CC_program.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::DecimalSignString (unsigned Sign)
Definition at line 498 of file Dwarf.cpp.
References llvm::dwarf::DW_DS_leading_overpunch, llvm::dwarf::DW_DS_leading_separate, llvm::dwarf::DW_DS_trailing_overpunch, llvm::dwarf::DW_DS_trailing_separate, and llvm::dwarf::DW_DS_unsigned.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::DiscriminantString (unsigned Discriminant)
Definition at line 623 of file Dwarf.cpp.
References llvm::dwarf::DW_DSC_label, and llvm::dwarf::DW_DSC_range.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::EndianityString (unsigned Endian)
Definition at line 509 of file Dwarf.cpp.
References llvm::dwarf::DW_END_big, llvm::dwarf::DW_END_default, llvm::dwarf::DW_END_hi_user, llvm::dwarf::DW_END_little, and llvm::dwarf::DW_END_lo_user.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::FormEncodingString (unsigned Encoding)
Definition at line 272 of file Dwarf.cpp.
References llvm::dwarf::DW_FORM_addr, llvm::dwarf::DW_FORM_block, llvm::dwarf::DW_FORM_block1, llvm::dwarf::DW_FORM_block2, llvm::dwarf::DW_FORM_block4, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_data2, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_data8, llvm::dwarf::DW_FORM_exprloc, llvm::dwarf::DW_FORM_flag, llvm::dwarf::DW_FORM_flag_present, llvm::dwarf::DW_FORM_GNU_addr_index, llvm::dwarf::DW_FORM_GNU_str_index, llvm::dwarf::DW_FORM_indirect, llvm::dwarf::DW_FORM_ref1, llvm::dwarf::DW_FORM_ref2, llvm::dwarf::DW_FORM_ref4, llvm::dwarf::DW_FORM_ref8, llvm::dwarf::DW_FORM_ref_addr, llvm::dwarf::DW_FORM_ref_sig8, llvm::dwarf::DW_FORM_ref_udata, llvm::dwarf::DW_FORM_sdata, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_string, llvm::dwarf::DW_FORM_strp, and llvm::dwarf::DW_FORM_udata.
Referenced by llvm::DWARFAcceleratorTable::dump(), llvm::DWARFAbbreviationDeclaration::dump(), llvm::DWARFDebugInfoEntryMinimal::dumpAttribute(), llvm::DIEAbbrev::Emit(), llvm::DIEAbbrev::print(), llvm::DwarfAccelTable::Atom::print(), and llvm::DIE::print().
const char * llvm::dwarf::GDBIndexEntryKindString (GDBIndexEntryKind Kind)
Definition at line 757 of file Dwarf.cpp.
References llvm::dwarf::GIEK_FUNCTION, llvm::dwarf::GIEK_NONE, llvm::dwarf::GIEK_OTHER, llvm::dwarf::GIEK_TYPE, llvm::dwarf::GIEK_UNUSED5, llvm::dwarf::GIEK_UNUSED6, llvm::dwarf::GIEK_UNUSED7, llvm::dwarf::GIEK_VARIABLE, and llvm_unreachable.
Referenced by dumpPubSection().
const char * llvm::dwarf::GDBIndexEntryLinkageString (GDBIndexEntryLinkage Linkage)
Definition at line 779 of file Dwarf.cpp.
References llvm::dwarf::GIEL_EXTERNAL, llvm::dwarf::GIEL_STATIC, and llvm_unreachable.
Referenced by dumpPubSection().
const char * llvm::dwarf::InlineCodeString (unsigned Code)
Definition at line 605 of file Dwarf.cpp.
References llvm::dwarf::DW_INL_declared_inlined, llvm::dwarf::DW_INL_declared_not_inlined, llvm::dwarf::DW_INL_inlined, and llvm::dwarf::DW_INL_not_inlined.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::LanguageString (unsigned Language)
Definition at line 548 of file Dwarf.cpp.
References llvm::dwarf::DW_LANG_Ada83, llvm::dwarf::DW_LANG_Ada95, llvm::dwarf::DW_LANG_C, llvm::dwarf::DW_LANG_C89, llvm::dwarf::DW_LANG_C99, llvm::dwarf::DW_LANG_C_plus_plus, llvm::dwarf::DW_LANG_C_plus_plus_03, llvm::dwarf::DW_LANG_C_plus_plus_11, llvm::dwarf::DW_LANG_Cobol74, llvm::dwarf::DW_LANG_Cobol85, llvm::dwarf::DW_LANG_D, llvm::dwarf::DW_LANG_Fortran77, llvm::dwarf::DW_LANG_Fortran90, llvm::dwarf::DW_LANG_Fortran95, llvm::dwarf::DW_LANG_Go, llvm::dwarf::DW_LANG_Haskell, llvm::dwarf::DW_LANG_hi_user, llvm::dwarf::DW_LANG_Java, llvm::dwarf::DW_LANG_lo_user, llvm::dwarf::DW_LANG_Mips_Assembler, llvm::dwarf::DW_LANG_Modula2, llvm::dwarf::DW_LANG_Modula3, llvm::dwarf::DW_LANG_ObjC, llvm::dwarf::DW_LANG_ObjC_plus_plus, llvm::dwarf::DW_LANG_OCaml, llvm::dwarf::DW_LANG_OpenCL, llvm::dwarf::DW_LANG_Pascal83, llvm::dwarf::DW_LANG_PLI, llvm::dwarf::DW_LANG_Python, and llvm::dwarf::DW_LANG_UPC.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::LNExtendedString (unsigned Encoding)
Definition at line 649 of file Dwarf.cpp.
References llvm::dwarf::DW_LNE_define_file, llvm::dwarf::DW_LNE_end_sequence, llvm::dwarf::DW_LNE_hi_user, llvm::dwarf::DW_LNE_lo_user, llvm::dwarf::DW_LNE_set_address, and llvm::dwarf::DW_LNE_set_discriminator.
const char * llvm::dwarf::LNStandardString (unsigned Standard)
Definition at line 631 of file Dwarf.cpp.
References llvm::dwarf::DW_LNS_advance_line, llvm::dwarf::DW_LNS_advance_pc, llvm::dwarf::DW_LNS_const_add_pc, llvm::dwarf::DW_LNS_copy, llvm::dwarf::DW_LNS_fixed_advance_pc, llvm::dwarf::DW_LNS_negate_stmt, llvm::dwarf::DW_LNS_set_basic_block, llvm::dwarf::DW_LNS_set_column, llvm::dwarf::DW_LNS_set_epilogue_begin, llvm::dwarf::DW_LNS_set_file, llvm::dwarf::DW_LNS_set_isa, and llvm::dwarf::DW_LNS_set_prologue_end.
Referenced by llvm::DWARFDebugLine::Prologue::dump().
const char * llvm::dwarf::MacinfoString (unsigned Encoding)
Definition at line 662 of file Dwarf.cpp.
References llvm::dwarf::DW_MACINFO_define, llvm::dwarf::DW_MACINFO_end_file, llvm::dwarf::DW_MACINFO_start_file, llvm::dwarf::DW_MACINFO_undef, and llvm::dwarf::DW_MACINFO_vendor_ext.
const char * llvm::dwarf::OperationEncodingString (unsigned Encoding)
Definition at line 307 of file Dwarf.cpp.
References llvm::dwarf::DW_OP_abs, llvm::dwarf::DW_OP_addr, llvm::dwarf::DW_OP_and, llvm::dwarf::DW_OP_bit_piece, llvm::dwarf::DW_OP_bra, llvm::dwarf::DW_OP_breg0, llvm::dwarf::DW_OP_breg1, llvm::dwarf::DW_OP_breg10, llvm::dwarf::DW_OP_breg11, llvm::dwarf::DW_OP_breg12, llvm::dwarf::DW_OP_breg13, llvm::dwarf::DW_OP_breg14, llvm::dwarf::DW_OP_breg15, llvm::dwarf::DW_OP_breg16, llvm::dwarf::DW_OP_breg17, llvm::dwarf::DW_OP_breg18, llvm::dwarf::DW_OP_breg19, llvm::dwarf::DW_OP_breg2, llvm::dwarf::DW_OP_breg20, llvm::dwarf::DW_OP_breg21, llvm::dwarf::DW_OP_breg22, llvm::dwarf::DW_OP_breg23, llvm::dwarf::DW_OP_breg24, llvm::dwarf::DW_OP_breg25, llvm::dwarf::DW_OP_breg26, llvm::dwarf::DW_OP_breg27, llvm::dwarf::DW_OP_breg28, llvm::dwarf::DW_OP_breg29, llvm::dwarf::DW_OP_breg3, llvm::dwarf::DW_OP_breg30, llvm::dwarf::DW_OP_breg31, llvm::dwarf::DW_OP_breg4, llvm::dwarf::DW_OP_breg5, llvm::dwarf::DW_OP_breg6, llvm::dwarf::DW_OP_breg7, llvm::dwarf::DW_OP_breg8, llvm::dwarf::DW_OP_breg9, llvm::dwarf::DW_OP_bregx, llvm::dwarf::DW_OP_call2, llvm::dwarf::DW_OP_call4, llvm::dwarf::DW_OP_call_frame_cfa, llvm::dwarf::DW_OP_call_ref, llvm::dwarf::DW_OP_const1s, llvm::dwarf::DW_OP_const1u, llvm::dwarf::DW_OP_const2s, llvm::dwarf::DW_OP_const2u, llvm::dwarf::DW_OP_const4s, llvm::dwarf::DW_OP_const4u, llvm::dwarf::DW_OP_const8s, llvm::dwarf::DW_OP_const8u, llvm::dwarf::DW_OP_consts, llvm::dwarf::DW_OP_constu, llvm::dwarf::DW_OP_deref, llvm::dwarf::DW_OP_deref_size, llvm::dwarf::DW_OP_div, llvm::dwarf::DW_OP_drop, llvm::dwarf::DW_OP_dup, llvm::dwarf::DW_OP_eq, llvm::dwarf::DW_OP_fbreg, llvm::dwarf::DW_OP_form_tls_address, llvm::dwarf::DW_OP_ge, llvm::dwarf::DW_OP_GNU_addr_index, llvm::dwarf::DW_OP_GNU_const_index, llvm::dwarf::DW_OP_GNU_push_tls_address, llvm::dwarf::DW_OP_gt, llvm::dwarf::DW_OP_implicit_value, llvm::dwarf::DW_OP_le, llvm::dwarf::DW_OP_lit0, llvm::dwarf::DW_OP_lit1, llvm::dwarf::DW_OP_lit10, llvm::dwarf::DW_OP_lit11, llvm::dwarf::DW_OP_lit12, llvm::dwarf::DW_OP_lit13, llvm::dwarf::DW_OP_lit14, llvm::dwarf::DW_OP_lit15, llvm::dwarf::DW_OP_lit16, llvm::dwarf::DW_OP_lit17, llvm::dwarf::DW_OP_lit18, llvm::dwarf::DW_OP_lit19, llvm::dwarf::DW_OP_lit2, llvm::dwarf::DW_OP_lit20, llvm::dwarf::DW_OP_lit21, llvm::dwarf::DW_OP_lit22, llvm::dwarf::DW_OP_lit23, llvm::dwarf::DW_OP_lit24, llvm::dwarf::DW_OP_lit25, llvm::dwarf::DW_OP_lit26, llvm::dwarf::DW_OP_lit27, llvm::dwarf::DW_OP_lit28, llvm::dwarf::DW_OP_lit29, llvm::dwarf::DW_OP_lit3, llvm::dwarf::DW_OP_lit30, llvm::dwarf::DW_OP_lit31, llvm::dwarf::DW_OP_lit4, llvm::dwarf::DW_OP_lit5, llvm::dwarf::DW_OP_lit6, llvm::dwarf::DW_OP_lit7, llvm::dwarf::DW_OP_lit8, llvm::dwarf::DW_OP_lit9, llvm::dwarf::DW_OP_lt, llvm::dwarf::DW_OP_minus, llvm::dwarf::DW_OP_mod, llvm::dwarf::DW_OP_mul, llvm::dwarf::DW_OP_ne, llvm::dwarf::DW_OP_neg, llvm::dwarf::DW_OP_nop, llvm::dwarf::DW_OP_not, llvm::dwarf::DW_OP_or, llvm::dwarf::DW_OP_over, llvm::dwarf::DW_OP_pick, llvm::dwarf::DW_OP_piece, llvm::dwarf::DW_OP_plus, llvm::dwarf::DW_OP_plus_uconst, llvm::dwarf::DW_OP_push_object_address, llvm::dwarf::DW_OP_reg0, llvm::dwarf::DW_OP_reg1, llvm::dwarf::DW_OP_reg10, llvm::dwarf::DW_OP_reg11, llvm::dwarf::DW_OP_reg12, llvm::dwarf::DW_OP_reg13, llvm::dwarf::DW_OP_reg14, llvm::dwarf::DW_OP_reg15, llvm::dwarf::DW_OP_reg16, llvm::dwarf::DW_OP_reg17, llvm::dwarf::DW_OP_reg18, llvm::dwarf::DW_OP_reg19, llvm::dwarf::DW_OP_reg2, llvm::dwarf::DW_OP_reg20, llvm::dwarf::DW_OP_reg21, llvm::dwarf::DW_OP_reg22, llvm::dwarf::DW_OP_reg23, llvm::dwarf::DW_OP_reg24, llvm::dwarf::DW_OP_reg25, llvm::dwarf::DW_OP_reg26, llvm::dwarf::DW_OP_reg27, llvm::dwarf::DW_OP_reg28, llvm::dwarf::DW_OP_reg29, llvm::dwarf::DW_OP_reg3, llvm::dwarf::DW_OP_reg30, llvm::dwarf::DW_OP_reg31, llvm::dwarf::DW_OP_reg4, llvm::dwarf::DW_OP_reg5, llvm::dwarf::DW_OP_reg6, llvm::dwarf::DW_OP_reg7, llvm::dwarf::DW_OP_reg8, llvm::dwarf::DW_OP_reg9, llvm::dwarf::DW_OP_regx, llvm::dwarf::DW_OP_rot, llvm::dwarf::DW_OP_shl, llvm::dwarf::DW_OP_shr, llvm::dwarf::DW_OP_shra, llvm::dwarf::DW_OP_skip, llvm::dwarf::DW_OP_stack_value, llvm::dwarf::DW_OP_swap, llvm::dwarf::DW_OP_xderef, llvm::dwarf::DW_OP_xderef_size, and llvm::dwarf::DW_OP_xor.
Referenced by llvm::DebugLocDwarfExpression::EmitOp().
const char * llvm::dwarf::TagString (unsigned Tag)
Definition at line 20 of file Dwarf.cpp.
References llvm::dwarf::DW_TAG_access_declaration, llvm::dwarf::DW_TAG_APPLE_property, llvm::dwarf::DW_TAG_arg_variable, llvm::dwarf::DW_TAG_array_type, llvm::dwarf::DW_TAG_auto_variable, llvm::dwarf::DW_TAG_base_type, llvm::dwarf::DW_TAG_catch_block, llvm::dwarf::DW_TAG_class_template, llvm::dwarf::DW_TAG_class_type, llvm::dwarf::DW_TAG_coarray_type, llvm::dwarf::DW_TAG_common_block, llvm::dwarf::DW_TAG_common_inclusion, llvm::dwarf::DW_TAG_compile_unit, llvm::dwarf::DW_TAG_condition, llvm::dwarf::DW_TAG_const_type, llvm::dwarf::DW_TAG_constant, llvm::dwarf::DW_TAG_dwarf_procedure, llvm::dwarf::DW_TAG_dynamic_type, llvm::dwarf::DW_TAG_entry_point, llvm::dwarf::DW_TAG_enumeration_type, llvm::dwarf::DW_TAG_enumerator, llvm::dwarf::DW_TAG_expression, llvm::dwarf::DW_TAG_file_type, llvm::dwarf::DW_TAG_formal_parameter, llvm::dwarf::DW_TAG_format_label, llvm::dwarf::DW_TAG_friend, llvm::dwarf::DW_TAG_function_template, llvm::dwarf::DW_TAG_generic_subrange, llvm::dwarf::DW_TAG_GNU_formal_parameter_pack, llvm::dwarf::DW_TAG_GNU_template_parameter_pack, llvm::dwarf::DW_TAG_GNU_template_template_param, llvm::dwarf::DW_TAG_hi_user, llvm::dwarf::DW_TAG_imported_declaration, llvm::dwarf::DW_TAG_imported_module, llvm::dwarf::DW_TAG_imported_unit, llvm::dwarf::DW_TAG_inheritance, llvm::dwarf::DW_TAG_inlined_subroutine, llvm::dwarf::DW_TAG_interface_type, llvm::dwarf::DW_TAG_label, llvm::dwarf::DW_TAG_lexical_block, llvm::dwarf::DW_TAG_lo_user, llvm::dwarf::DW_TAG_member, llvm::dwarf::DW_TAG_MIPS_loop, llvm::dwarf::DW_TAG_module, llvm::dwarf::DW_TAG_namelist, llvm::dwarf::DW_TAG_namelist_item, llvm::dwarf::DW_TAG_namespace, llvm::dwarf::DW_TAG_packed_type, llvm::dwarf::DW_TAG_partial_unit, llvm::dwarf::DW_TAG_pointer_type, llvm::dwarf::DW_TAG_ptr_to_member_type, llvm::dwarf::DW_TAG_reference_type, llvm::dwarf::DW_TAG_restrict_type, llvm::dwarf::DW_TAG_rvalue_reference_type, llvm::dwarf::DW_TAG_set_type, llvm::dwarf::DW_TAG_shared_type, llvm::dwarf::DW_TAG_string_type, llvm::dwarf::DW_TAG_structure_type, llvm::dwarf::DW_TAG_subprogram, llvm::dwarf::DW_TAG_subrange_type, llvm::dwarf::DW_TAG_subroutine_type, llvm::dwarf::DW_TAG_template_alias, llvm::dwarf::DW_TAG_template_type_parameter, llvm::dwarf::DW_TAG_template_value_parameter, llvm::dwarf::DW_TAG_thrown_type, llvm::dwarf::DW_TAG_try_block, llvm::dwarf::DW_TAG_type_unit, llvm::dwarf::DW_TAG_typedef, llvm::dwarf::DW_TAG_union_type, llvm::dwarf::DW_TAG_unspecified_parameters, llvm::dwarf::DW_TAG_unspecified_type, llvm::dwarf::DW_TAG_variable, llvm::dwarf::DW_TAG_variant, llvm::dwarf::DW_TAG_variant_part, llvm::dwarf::DW_TAG_volatile_type, and llvm::dwarf::DW_TAG_with_stmt.
Referenced by llvm::DWARFDebugInfoEntryMinimal::dump(), llvm::DWARFAbbreviationDeclaration::dump(), llvm::DIEAbbrev::Emit(), llvm::DwarfDebug::emitDIE(), llvm::DIEAbbrev::print(), llvm::DwarfAccelTable::HashDataContents::print(), llvm::DIE::print(), llvm::DIDescriptor::print(), and llvm::WriteMDNodeComment().
const char * llvm::dwarf::VirtualityString (unsigned Virtuality)
Definition at line 539 of file Dwarf.cpp.
References llvm::dwarf::DW_VIRTUALITY_none, llvm::dwarf::DW_VIRTUALITY_pure_virtual, and llvm::dwarf::DW_VIRTUALITY_virtual.
Referenced by llvm::dwarf::AttributeValueString().
const char * llvm::dwarf::VisibilityString (unsigned Visibility)
Definition at line 530 of file Dwarf.cpp.
References llvm::dwarf::DW_VIS_exported, llvm::dwarf::DW_VIS_local, and llvm::dwarf::DW_VIS_qualified.
Referenced by llvm::dwarf::AttributeValueString().