LLVM: HexagonRemoveSZExtArgs.cpp File Reference
LLVM API Documentation
HexagonRemoveSZExtArgs.cpp File Reference
#include "Hexagon.h"
#include "HexagonTargetMachine.h"
#include "llvm/CodeGen/MachineFunctionAnalysis.h"
#include "llvm/CodeGen/StackProtector.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
void llvm::initializeHexagonRemoveExtendArgsPass (PassRegistry &)
INITIALIZE_PASS (HexagonRemoveExtendArgs,"reargs","Remove Sign and Zero Extends for Args", false, false) bool HexagonRemoveExtendArgs
Function Documentation
INITIALIZE_PASS (HexagonRemoveExtendArgs , "reargs" , "Remove Sign and Zero Extends for Args" , false , false)
Definition at line 54 of file HexagonRemoveSZExtArgs.cpp.
References assert(), llvm::Instruction::eraseFromParent(), llvm::EVT::getEVT(), llvm::Value::getType(), I, llvm::Instruction::insertBefore(), llvm::Value::replaceAllUsesWith(), llvm::Attribute::SExt, SI, llvm::Value::user_begin(), and llvm::Value::user_end().