LLVM: HexagonMCTargetDesc.cpp File Reference
LLVM API Documentation
HexagonMCTargetDesc.cpp File Reference
#include "HexagonMCTargetDesc.h"
#include "HexagonMCAsmInfo.h"
#include "MCTargetDesc/HexagonInstPrinter.h"
#include "MCTargetDesc/HexagonMCInst.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "HexagonGenInstrInfo.inc"
#include "HexagonGenSubtargetInfo.inc"
#include "HexagonGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createHexagonMCInstrInfo ()
static MCRegisterInfo * createHexagonMCRegisterInfo (StringRef TT)
static MCStreamer * createHexagonELFStreamer (MCContext &Context, MCAsmBackend &MAB, raw_ostream &OS, MCCodeEmitter *CE, bool RelaxAll)
static MCSubtargetInfo * createHexagonMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
static MCAsmInfo * createHexagonMCAsmInfo (const MCRegisterInfo &MRI, StringRef TT)
static MCStreamer * createMCStreamer (Target const &T, StringRef TT, MCContext &Context, MCAsmBackend &MAB, raw_ostream &OS, MCCodeEmitter *Emitter, MCSubtargetInfo const &STI, bool RelaxAll)
static MCCodeGenInfo * createHexagonMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCInstPrinter * createHexagonMCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void LLVMInitializeHexagonTargetMC ()
Macro Definition Documentation
#define GET_INSTRINFO_MC_DESC
Definition at line 30 of file HexagonMCTargetDesc.cpp.
#define GET_REGINFO_MC_DESC
Definition at line 36 of file HexagonMCTargetDesc.cpp.
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 33 of file HexagonMCTargetDesc.cpp.
Function Documentation
static MCStreamer* createHexagonELFStreamer (MCContext & Context, MCAsmBackend & MAB, raw_ostream & OS, MCCodeEmitter * CE, bool RelaxAll) static
Definition at line 52 of file HexagonMCTargetDesc.cpp.
Referenced by createMCStreamer().
static MCAsmInfo* createHexagonMCAsmInfo (const MCRegisterInfo & MRI, StringRef TT) static
Definition at line 67 of file HexagonMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), and llvm::MCCFIInstruction::createDefCfa().
Referenced by LLVMInitializeHexagonTargetMC().
static MCCodeGenInfo* createHexagonMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 89 of file HexagonMCTargetDesc.cpp.
References llvm::MCCodeGenInfo::InitMCCodeGenInfo(), llvm::Reloc::Static, and llvm::X.
Referenced by LLVMInitializeHexagonTargetMC().
static MCInstPrinter* createHexagonMCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 98 of file HexagonMCTargetDesc.cpp.
Referenced by LLVMInitializeHexagonTargetMC().
static MCInstrInfo* createHexagonMCInstrInfo () static
Definition at line 39 of file HexagonMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeHexagonTargetMC().
static MCRegisterInfo* createHexagonMCRegisterInfo (StringRef TT) static
Definition at line 45 of file HexagonMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeHexagonTargetMC().
static MCSubtargetInfo* createHexagonMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS) static
Definition at line 61 of file HexagonMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeHexagonTargetMC().
static MCStreamer* createMCStreamer (Target const & T, StringRef TT, MCContext & Context, MCAsmBackend & MAB, raw_ostream & OS, MCCodeEmitter * Emitter, MCSubtargetInfo const & STI, bool RelaxAll) static
Definition at line 79 of file HexagonMCTargetDesc.cpp.
References createHexagonELFStreamer().
Referenced by LLVMInitializeHexagonTargetMC().
void LLVMInitializeHexagonTargetMC ()
Definition at line 108 of file HexagonMCTargetDesc.cpp.
References llvm::createHexagonAsmBackend(), createHexagonMCAsmInfo(), llvm::createHexagonMCCodeEmitter(), createHexagonMCCodeGenInfo(), createHexagonMCInstPrinter(), createHexagonMCInstrInfo(), createHexagonMCRegisterInfo(), createHexagonMCSubtargetInfo(), createMCStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TheHexagonTarget, and llvm::X.