LLVM: Instruction.cpp File Reference
LLVM API Documentation
Instruction.cpp File Reference
#include "llvm/IR/Instruction.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
Functions
static bool haveSameSpecialState (const Instruction *I1, const Instruction *I2, bool IgnoreAlignment=false)
Function Documentation
static bool haveSameSpecialState (const Instruction * I1, const Instruction * I2, bool IgnoreAlignment = false) static
Return true if both instructions have the same special state This must be kept in sync with lib/Transforms/IPO/MergeFunctions.cpp.
Definition at line 261 of file Instruction.cpp.
References assert(), llvm::Intrinsic::getAttributes(), llvm::Instruction::getOpcode(), LI, and SI.
Referenced by llvm::Instruction::isIdenticalToWhenDefined(), and llvm::Instruction::isSameOperationAs().