LLVM: InstrProfReader.cpp File Reference
LLVM API Documentation
InstrProfReader.cpp File Reference
#include "llvm/ProfileData/InstrProfReader.h"
#include "InstrProfIndexed.h"
#include "llvm/ProfileData/InstrProf.h"
#include <cassert>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
static ErrorOr
< std::unique_ptr
< MemoryBuffer > > setupMemoryBuffer (std::string Path)
static std::error_code initializeReader (InstrProfReader &Reader)
template<class IntPtrT >
static uint64_t getRawMagic ()
template<>
uint64_t getRawMagic< uint64_t > ()
template<>
uint64_t getRawMagic< uint32_t > ()
static uint64_t getRawVersion ()
Function Documentation
template<class IntPtrT > static uint64_t getRawMagic () static
template<> uint64_t getRawMagic< uint32_t > ()
Definition at line 149 of file InstrProfReader.cpp.
template<> uint64_t getRawMagic< uint64_t > ()
Definition at line 136 of file InstrProfReader.cpp.
static uint64_t getRawVersion () static
Definition at line 210 of file InstrProfReader.cpp.
static std::error_code initializeReader (InstrProfReader & Reader) static
Definition at line 36 of file InstrProfReader.cpp.
References llvm::InstrProfReader::readHeader().
Referenced by llvm::InstrProfReader::create(), and llvm::IndexedInstrProfReader::create().
static ErrorOr<std::unique_ptr<MemoryBuffer> > setupMemoryBuffer (std::string Path) static
Definition at line 23 of file InstrProfReader.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFileOrSTDIN(), and llvm::too_large.
Referenced by llvm::InstrProfReader::create(), and llvm::IndexedInstrProfReader::create().