LLVM: IntrinsicInst.cpp File Reference
LLVM API Documentation
IntrinsicInst.cpp File Reference
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Metadata.h"
Functions
static Value * CastOperand (Value *C)
static Value * getValueImpl (Value *Op)
Function Documentation
static Value* CastOperand (Value * C) static
DbgInfoIntrinsic - This is the common base class for debug info intrinsics
Definition at line 34 of file IntrinsicInst.cpp.
Referenced by llvm::DbgInfoIntrinsic::StripCast().
static Value* getValueImpl (Value * Op) static
Definition at line 52 of file IntrinsicInst.cpp.
References assert().
Referenced by llvm::DbgDeclareInst::getAddress(), and llvm::DbgValueInst::getValue().