LLVM: LazyCallGraph.cpp File Reference
LLVM API Documentation
LazyCallGraph.cpp File Reference
#include "llvm/Analysis/LazyCallGraph.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "lcg"
Functions
static void findCallees (SmallVectorImpl< Constant * > &Worklist, SmallPtrSetImpl< Constant * > &Visited, SmallVectorImpl< PointerUnion< Function *, LazyCallGraph::Node * >> &Callees, DenseMap< Function *, size_t > &CalleeIndexMap)
static void printNodes (raw_ostream &OS, LazyCallGraph::Node &N, SmallPtrSetImpl< LazyCallGraph::Node * > &Printed)
static void printSCC (raw_ostream &OS, LazyCallGraph::SCC &SCC)
Macro Definition Documentation
#define DEBUG_TYPE "lcg"
Definition at line 21 of file LazyCallGraph.cpp.
Function Documentation
static void findCallees (SmallVectorImpl< Constant * > & Worklist, SmallPtrSetImpl< Constant * > & Visited, SmallVectorImpl< PointerUnion< Function *, LazyCallGraph::Node * >> & Callees, DenseMap< Function *, size_t > & CalleeIndexMap) static
Definition at line 23 of file LazyCallGraph.cpp.
References llvm::CallingConv::C, llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), F(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::User::operand_values(), llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::LazyCallGraph::LazyCallGraph().
static void printNodes (raw_ostream & OS, LazyCallGraph::Node & N, SmallPtrSetImpl< LazyCallGraph::Node * > & Printed) static
Definition at line 687 of file LazyCallGraph.cpp.
References I, and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by llvm::LazyCallGraphPrinterPass::run().
static void printSCC (raw_ostream & OS, LazyCallGraph::SCC & SCC) static
Definition at line 701 of file LazyCallGraph.cpp.
References llvm::LazyCallGraph::SCC::begin(), and llvm::LazyCallGraph::SCC::end().
Referenced by llvm::LazyCallGraphPrinterPass::run().