LLVM: LiveRegMatrix.cpp File Reference
LLVM API Documentation
LiveRegMatrix.cpp File Reference
#include "llvm/CodeGen/LiveRegMatrix.h"
#include "RegisterCoalescer.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "regalloc"
Functions
STATISTIC (NumAssigned,"Number of registers assigned")
STATISTIC (NumUnassigned,"Number of registers unassigned")
INITIALIZE_PASS_BEGIN (LiveRegMatrix,"liveregmatrix","Live Register Matrix", false, false) INITIALIZE_PASS_END(LiveRegMatrix
template<typename Callable >
bool foreachUnit (const TargetRegisterInfo *TRI, LiveInterval &VRegInterval, unsigned PhysReg, Callable Func)
Variables
liveregmatrix
Live Register Matrix
Live Register false
Macro Definition Documentation
#define DEBUG_TYPE "regalloc"
Definition at line 27 of file LiveRegMatrix.cpp.
Function Documentation
template<typename Callable > bool foreachUnit (const TargetRegisterInfo * TRI, LiveInterval & VRegInterval, unsigned PhysReg, Callable Func)
Definition at line 76 of file LiveRegMatrix.cpp.
References llvm::LiveInterval::hasSubRanges(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegUnitMaskIterator::isValid(), and llvm::LiveInterval::subranges().
Referenced by llvm::LiveRegMatrix::assign(), llvm::LiveRegMatrix::checkRegUnitInterference(), and llvm::LiveRegMatrix::unassign().
INITIALIZE_PASS_BEGIN (LiveRegMatrix , "liveregmatrix" , "Live Register Matrix" , false , false)
STATISTIC (NumAssigned , "Number of registers assigned")
STATISTIC (NumUnassigned , "Number of registers unassigned")
Variable Documentation
Live Register false
Definition at line 37 of file LiveRegMatrix.cpp.
liveregmatrix
Definition at line 37 of file LiveRegMatrix.cpp.
Live Register Matrix
Definition at line 37 of file LiveRegMatrix.cpp.
Referenced by llvm::PBQP::applyR1(), llvm::PBQP::applyR2(), and llvm::PBQP::backpropagate().