LLVM: LiveInterval.cpp File Reference
LLVM API Documentation
LiveInterval.cpp File Reference
#include "llvm/CodeGen/LiveInterval.h"
#include "RegisterCoalescer.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include <algorithm>
Functions
static VNInfo * searchForVNI (const SlotIndexes &Indexes, LiveRange &LR, const MachineBasicBlock *MBB, SmallPtrSetImpl< const MachineBasicBlock * > &Visited)
static void determineMissingVNIs (const SlotIndexes &Indexes, LiveInterval &LI)
static bool coalescable (const LiveRange::Segment &A, const LiveRange::Segment &B)
Function Documentation
static bool coalescable (const LiveRange::Segment & A, const LiveRange::Segment & B) inline static
Definition at line 986 of file LiveInterval.cpp.
References assert(), llvm::LiveRange::Segment::end, llvm::LiveRange::Segment::start, and llvm::LiveRange::Segment::valno.
Referenced by llvm::LiveRangeUpdater::add().
static void determineMissingVNIs (const SlotIndexes & Indexes, LiveInterval & LI) static
Definition at line 651 of file LiveInterval.cpp.
References assert(), llvm::SmallPtrSetImplBase::clear(), llvm::SlotIndexes::getMBBFromIndex(), llvm::SlotIndex::isBlock(), llvm::MachineBasicBlock::predecessors(), searchForVNI(), llvm::LiveRange::segments, llvm::LiveRange::Segment::start, and llvm::LiveRange::Segment::valno.
Referenced by llvm::LiveInterval::constructMainRangeFromSubranges().
static VNInfo* searchForVNI (const SlotIndexes & Indexes, LiveRange & LR, const MachineBasicBlock * MBB, SmallPtrSetImpl< const MachineBasicBlock * > & Visited) static
Helper function for constructMainRangeFromSubranges(): Search the CFG backwards until we find a place covered by a LiveRange segment that actually has a valno set.
Definition at line 621 of file LiveInterval.cpp.
References assert(), llvm::LiveRange::end(), llvm::LiveRange::find(), llvm::SlotIndexes::getMBBEndIdx(), llvm::SlotIndex::getPrevSlot(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::MachineBasicBlock::predecessors().
Referenced by determineMissingVNIs().