LLVM: LiveRangeCalc.cpp File Reference
LLVM API Documentation
LiveRangeCalc.cpp File Reference
#include "LiveRangeCalc.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
Macros
#define DEBUG_TYPE "regalloc"
Functions
static void createDeadDef (SlotIndexes &Indexes, VNInfo::Allocator &Alloc, LiveRange &LR, const MachineOperand &MO)
Macro Definition Documentation
#define DEBUG_TYPE "regalloc"
Definition at line 20 of file LiveRangeCalc.cpp.
Function Documentation
static void createDeadDef (SlotIndexes & Indexes, VNInfo::Allocator & Alloc, LiveRange & LR, const MachineOperand & MO) static
Definition at line 43 of file LiveRangeCalc.cpp.
References llvm::LiveRange::createDeadDef(), llvm::SlotIndexes::getInstructionIndex(), llvm::SlotIndexes::getMBBStartIdx(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getParent(), llvm::SlotIndex::getRegSlot(), llvm::MachineOperand::isEarlyClobber(), llvm::MachineInstr::isPHI(), and llvm::AArch64CC::MI.
Referenced by llvm::LiveRangeCalc::calculate(), and llvm::LiveRangeCalc::createDeadDefs().