LLVM: LoopUnrollPass.cpp File Reference
LLVM API Documentation
LoopUnrollPass.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/FunctionTargetTransformInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/UnrollLoop.h"
#include <climits>
Macros
#define DEBUG_TYPE "loop-unroll"
Functions
static unsigned ApproximateLoopSize (const Loop *L, unsigned &NumCalls, bool &NotDuplicatable, const TargetTransformInfo &TTI, AssumptionCache *AC)
ApproximateLoopSize - Approximate the size of the loop.
static const MDNode * GetUnrollMetadata (const Loop *L, StringRef Name)
static bool HasUnrollFullPragma (const Loop *L)
static bool HasUnrollDisablePragma (const Loop *L)
static unsigned UnrollCountPragmaValue (const Loop *L)
static void SetLoopAlreadyUnrolled (Loop *L)
Variables
static cl::opt< unsigned > UnrollThreshold ("unroll-threshold", cl::init(150), cl::Hidden, cl::desc("The cut-off point for automatic loop unrolling"))
static cl::opt< unsigned > UnrollCount ("unroll-count", cl::init(0), cl::Hidden, cl::desc("Use this unroll count for all loops including those with ""unroll_count pragma values, for testing purposes"))
static cl::opt< bool > UnrollAllowPartial ("unroll-allow-partial", cl::init(false), cl::Hidden, cl::desc("Allows loops to be partially unrolled until ""-unroll-threshold loop size is reached."))
static cl::opt< bool > UnrollRuntime ("unroll-runtime", cl::ZeroOrMore, cl::init(false), cl::Hidden, cl::desc("Unroll loops with run-time trip counts"))
static cl::opt< unsigned > PragmaUnrollThreshold ("pragma-unroll-threshold", cl::init(16 *1024), cl::Hidden, cl::desc("Unrolled size limit for loops with an unroll(full) or ""unroll_count pragma."))
Macro Definition Documentation
#define DEBUG_TYPE "loop-unroll"
Definition at line 35 of file LoopUnrollPass.cpp.
Function Documentation
static unsigned ApproximateLoopSize (const Loop * L, unsigned & NumCalls, bool & NotDuplicatable, const TargetTransformInfo & TTI, AssumptionCache * AC) static
ApproximateLoopSize - Approximate the size of the loop.
Definition at line 207 of file LoopUnrollPass.cpp.
References llvm::CodeMetrics::analyzeBasicBlock(), llvm::LoopBase< N, M >::block_begin(), llvm::LoopBase< N, M >::block_end(), llvm::CodeMetrics::collectEphemeralValues(), I, Metrics, llvm::CodeMetrics::notDuplicatable, llvm::CodeMetrics::NumInlineCandidates, and llvm::CodeMetrics::NumInsts.
static const MDNode* GetUnrollMetadata (const Loop * L, StringRef Name) static
Definition at line 237 of file LoopUnrollPass.cpp.
References assert(), llvm::dyn_cast(), llvm::StringRef::equals(), llvm::Loop::getLoopID(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and llvm::MDString::getString().
Referenced by HasUnrollDisablePragma(), HasUnrollFullPragma(), and UnrollCountPragmaValue().
static bool HasUnrollDisablePragma (const Loop * L) static
Definition at line 267 of file LoopUnrollPass.cpp.
References GetUnrollMetadata().
static bool HasUnrollFullPragma (const Loop * L) static
Definition at line 262 of file LoopUnrollPass.cpp.
References GetUnrollMetadata().
static void SetLoopAlreadyUnrolled (Loop * L) static
Definition at line 290 of file LoopUnrollPass.cpp.
References llvm::dyn_cast(), llvm::MDString::get(), llvm::MDNode::get(), llvm::LoopBase< N, M >::getHeader(), llvm::Loop::getLoopID(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MDNode::replaceOperandWith(), llvm::Loop::setLoopID(), and llvm::StringRef::startswith().
static unsigned UnrollCountPragmaValue (const Loop * L) static
Definition at line 273 of file LoopUnrollPass.cpp.
References assert(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and GetUnrollMetadata().
Variable Documentation
cl::opt<unsigned> PragmaUnrollThreshold("pragma-unroll-threshold", cl::init(16 *1024), cl::Hidden, cl::desc("Unrolled size limit for loops with an unroll(full) or ""unroll_count pragma.")) static
cl::opt<bool> UnrollAllowPartial("unroll-allow-partial", cl::init(false), cl::Hidden, cl::desc("Allows loops to be partially unrolled until ""-unroll-threshold loop size is reached.")) static
cl::opt<unsigned> UnrollCount("unroll-count", cl::init(0), cl::Hidden, cl::desc("Use this unroll count for all loops including those with ""unroll_count pragma values, for testing purposes")) static
cl::opt<bool> UnrollRuntime("unroll-runtime", cl::ZeroOrMore, cl::init(false), cl::Hidden, cl::desc("Unroll loops with run-time trip counts")) static
cl::opt<unsigned> UnrollThreshold("unroll-threshold", cl::init(150), cl::Hidden, cl::desc("The cut-off point for automatic loop unrolling")) static