LLVM: LowerSwitch.cpp File Reference
LLVM API Documentation
LowerSwitch.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/CFG.h"
#include "llvm/Pass.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/UnifyFunctionExitNodes.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "lower-switch"
Functions
static raw_ostream & operator<< (raw_ostream &O, const LowerSwitch::CaseVector &C) LLVM_ATTRIBUTE_USED
static void fixPhis (BasicBlock *SuccBB, BasicBlock *OrigBB, BasicBlock *NewBB, unsigned NumMergedCases)
Macro Definition Documentation
#define DEBUG_TYPE "lower-switch"
Definition at line 32 of file LowerSwitch.cpp.
Function Documentation
static void fixPhis (BasicBlock * SuccBB, BasicBlock * OrigBB, BasicBlock * NewBB, unsigned NumMergedCases) static
Definition at line 143 of file LowerSwitch.cpp.
References llvm::BasicBlock::begin(), llvm::BasicBlock::getFirstNonPHI(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getNumIncomingValues(), I, llvm::ARM_PROC::IE, llvm::PHINode::removeIncomingValue(), and llvm::PHINode::setIncomingBlock().
static raw_ostream & operator<< (raw_ostream & O, const LowerSwitch::CaseVector & C) static
Definition at line 120 of file LowerSwitch.cpp.