LLVM: LTOModule.cpp File Reference
LLVM API Documentation
LTOModule.cpp File Reference
#include "llvm/LTO/LTOModule.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Bitcode/ReaderWriter.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCTargetAsmParser.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
#include <system_error>
Functions
static Module * parseBitcodeFileImpl (MemoryBufferRef Buffer, LLVMContext &Context, bool ShouldBeLazy, std::string &ErrMsg)
Function Documentation
static Module* parseBitcodeFileImpl (MemoryBufferRef Buffer, LLVMContext & Context, bool ShouldBeLazy, std::string & ErrMsg) static
Definition at line 150 of file LTOModule.cpp.
References llvm::object::IRObjectFile::findBitcodeInMemBuffer(), llvm::ErrorOr< T >::getError(), llvm::getLazyBitcodeModule(), llvm::MemoryBuffer::getMemBuffer(), and llvm::parseBitcodeFile().