LLVM: MachineSSAUpdater.cpp File Reference
LLVM API Documentation
MachineSSAUpdater.cpp File Reference
#include "llvm/CodeGen/MachineSSAUpdater.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/AlignOf.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include "llvm/Transforms/Utils/SSAUpdaterImpl.h"
Classes
class llvm::SSAUpdaterTraits< MachineSSAUpdater >
class llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator
Iterator for PHI operands.
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "machine-ssaupdater"
Typedefs
typedef DenseMap
< MachineBasicBlock
*, unsigned > AvailableValsTy
Functions
static AvailableValsTy & getAvailableVals (void *AV)
static unsigned LookForIdenticalPHI (MachineBasicBlock *BB, SmallVectorImpl< std::pair< MachineBasicBlock *, unsigned > > &PredValues)
static MachineInstrBuilder InsertNewDef (unsigned Opcode, MachineBasicBlock *BB, MachineBasicBlock::iterator I, const TargetRegisterClass *RC, MachineRegisterInfo *MRI, const TargetInstrInfo *TII)
static MachineBasicBlock * findCorrespondingPred (const MachineInstr *MI, MachineOperand *U)
Macro Definition Documentation
#define DEBUG_TYPE "machine-ssaupdater"
Definition at line 32 of file MachineSSAUpdater.cpp.
Typedef Documentation
typedef DenseMap<MachineBasicBlock*, unsigned> AvailableValsTy
Definition at line 34 of file MachineSSAUpdater.cpp.
Function Documentation
static MachineBasicBlock* findCorrespondingPred (const MachineInstr * MI, MachineOperand * U) static
Definition at line 210 of file MachineSSAUpdater.cpp.
References llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), and llvm_unreachable.
Referenced by llvm::MachineSSAUpdater::RewriteUse().
static AvailableValsTy& getAvailableVals (void * AV) static
Definition at line 35 of file MachineSSAUpdater.cpp.
Referenced by llvm::MachineSSAUpdater::AddAvailableValue(), llvm::MachineSSAUpdater::HasValueForBlock(), and llvm::MachineSSAUpdater::Initialize().
static MachineInstrBuilder InsertNewDef (unsigned Opcode, MachineBasicBlock * BB, MachineBasicBlock::iterator I, const TargetRegisterClass * RC, MachineRegisterInfo * MRI, const TargetInstrInfo * TII) static
InsertNewDef - Insert an empty PHI or IMPLICIT_DEF instruction which define a value of the given register class at the start of the specified basic block. It returns the virtual register defined by the instruction.
Definition at line 114 of file MachineSSAUpdater.cpp.
References llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), and llvm::MCInstrInfo::get().
Referenced by llvm::SSAUpdaterTraits< MachineSSAUpdater >::CreateEmptyPHI(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::GetUndefVal(), and llvm::MachineSSAUpdater::GetValueInMiddleOfBlock().
static unsigned LookForIdenticalPHI (MachineBasicBlock * BB, SmallVectorImpl< std::pair< MachineBasicBlock *, unsigned > > & PredValues) static
Definition at line 81 of file MachineSSAUpdater.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), and I.
Referenced by llvm::MachineSSAUpdater::GetValueInMiddleOfBlock().