LLVM: MachineModuleInfoImpls.cpp File Reference
LLVM API Documentation
MachineModuleInfoImpls.cpp File Reference
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/MC/MCSymbol.h"
Functions
static int SortSymbolPair (const void *LHS, const void *RHS)
Function Documentation
static int SortSymbolPair (const void * LHS, const void * RHS) static
Definition at line 27 of file MachineModuleInfoImpls.cpp.
References llvm::StringRef::compare(), and llvm::MCSymbol::getName().
Referenced by llvm::MachineModuleInfoImpl::GetSortedStubs().