LLVM: MachineFunction.cpp File Reference
LLVM API Documentation
MachineFunction.cpp File Reference
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Classes
struct llvm::DOTGraphTraits< const MachineFunction * >
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "codegen"
Functions
static unsigned clampStackAlignment (bool ShouldClamp, unsigned Align, unsigned StackAlign)
clampStackAlignment - Clamp the alignment if requested and emit a warning.
static bool CanShareConstantPoolEntry (const Constant *A, const Constant *B, const DataLayout *TD)
Macro Definition Documentation
#define DEBUG_TYPE "codegen"
Definition at line 42 of file MachineFunction.cpp.
Function Documentation
static bool CanShareConstantPoolEntry (const Constant * A, const Constant * B, const DataLayout * TD) static
CanShareConstantPoolEntry - Test whether the given two constants can be allocated the same constant pool entry.
Definition at line 883 of file MachineFunction.cpp.
References llvm::ConstantFoldInstOperands(), llvm::IntegerType::get(), llvm::Value::getContext(), llvm::Value::getType(), and llvm::DataLayout::getTypeStoreSize().
Referenced by llvm::MachineConstantPool::getConstantPoolIndex().
static unsigned clampStackAlignment (bool ShouldClamp, unsigned Align, unsigned StackAlign) inline static
clampStackAlignment - Clamp the alignment if requested and emit a warning.
Definition at line 499 of file MachineFunction.cpp.
References Align(), llvm::dbgs(), and DEBUG.
Referenced by llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateFixedSpillStackObject(), llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::MachineFrameInfo::CreateStackObject(), and llvm::MachineFrameInfo::CreateVariableSizedObject().