LLVM: Main.cpp File Reference
LLVM API Documentation
Main.cpp File Reference
#include "TGParser.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Main.h"
#include "llvm/TableGen/Record.h"
#include <algorithm>
#include <cstdio>
#include <system_error>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
static int createDependencyFile (const TGParser &Parser, const char *argv0)
Create a dependency file for -d option.
int llvm::TableGenMain (char *argv0, TableGenMainFn *MainFn)
Function Documentation
static int createDependencyFile (const TGParser & Parser, const char * argv0) static
Create a dependency file for -d option.
This functionality is really only for the benefit of the build system. It is similar to GCC's -M* family of options.
Definition at line 54 of file Main.cpp.
References llvm::errs(), llvm::sys::fs::F_Text, llvm::TGParser::getDependencies(), llvm::tool_output_file::keep(), and llvm::tool_output_file::os().
Referenced by llvm::TableGenMain().