LLVM: Mangler.cpp File Reference
LLVM API Documentation
Mangler.cpp File Reference
#include "llvm/IR/Mangler.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void getNameWithPrefixx (raw_ostream &OS, const Twine &GVName, Mangler::ManglerPrefixTy PrefixTy, const DataLayout &DL, char Prefix)
static bool hasByteCountSuffix (CallingConv::ID CC)
static void addByteCountSuffix (raw_ostream &OS, const Function *F, const DataLayout &TD)
Function Documentation
static void addByteCountSuffix (raw_ostream & OS, const Function * F, const DataLayout & TD) static
Microsoft fastcall and stdcall functions require a suffix on their name indicating the number of words of arguments they take.
Definition at line 75 of file Mangler.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::DataLayout::getPointerSize(), llvm::DataLayout::getTypeAllocSize(), and llvm::RoundUpToAlignment().
Referenced by llvm::Mangler::getNameWithPrefix().
static void getNameWithPrefixx (raw_ostream & OS, const Twine & GVName, Mangler::ManglerPrefixTy PrefixTy, const DataLayout & DL, char Prefix) static
Definition at line 23 of file Mangler.cpp.
References assert(), llvm::StringRef::empty(), llvm::DataLayout::getLinkerPrivateGlobalPrefix(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::Mangler::LinkerPrivate, Name, llvm::cl::Prefix, llvm::Mangler::Private, llvm::StringRef::substr(), and llvm::Twine::toStringRef().
Referenced by llvm::Mangler::getNameWithPrefix().
static bool hasByteCountSuffix (CallingConv::ID CC) static
Definition at line 62 of file Mangler.cpp.
References llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_StdCall, and llvm::CallingConv::X86_VectorCall.
Referenced by llvm::Mangler::getNameWithPrefix().