LLVM: MCObjectStreamer.cpp File Reference
LLVM API Documentation
MCObjectStreamer.cpp File Reference
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
Functions
static const MCExpr * buildSymbolDiff (MCObjectStreamer &OS, const MCSymbol *A, const MCSymbol *B)
static void emitDwarfSetLineAddr (MCObjectStreamer &OS, int64_t LineDelta, const MCSymbol *Label, int PointerSize)
Variables
static const char *const BundlingNotImplementedMsg
Function Documentation
static const MCExpr* buildSymbolDiff (MCObjectStreamer & OS, const MCSymbol * A, const MCSymbol * B) static
Definition at line 286 of file MCObjectStreamer.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::Create(), llvm::MCStreamer::getContext(), llvm::MCBinaryExpr::Sub, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCObjectStreamer::EmitDwarfAdvanceFrameAddr(), and llvm::MCObjectStreamer::EmitDwarfAdvanceLineAddr().
static void emitDwarfSetLineAddr (MCObjectStreamer & OS, int64_t LineDelta, const MCSymbol * Label, int PointerSize) static
Definition at line 297 of file MCObjectStreamer.cpp.
References llvm::dwarf::DW_LNE_set_address, llvm::dwarf::DW_LNS_extended_op, llvm::MCDwarfLineAddr::Emit(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitSymbolValue(), and llvm::MCStreamer::EmitULEB128IntValue().
Referenced by llvm::MCObjectStreamer::EmitDwarfAdvanceLineAddr().
Variable Documentation
const char* const BundlingNotImplementedMsg static
Initial value:
=
  "Aligned bundling is not implemented for this object format"
Definition at line 257 of file MCObjectStreamer.cpp.
Referenced by llvm::MCObjectStreamer::EmitBundleAlignMode(), llvm::MCObjectStreamer::EmitBundleLock(), and llvm::MCObjectStreamer::EmitBundleUnlock().