LLVM: MCSectionELF.cpp File Reference
LLVM API Documentation
MCSectionELF.cpp File Reference
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void printName (raw_ostream &OS, StringRef Name)
Function Documentation
static void printName (raw_ostream & OS, StringRef Name) static
Definition at line 35 of file MCSectionELF.cpp.
References llvm::StringRef::begin(), llvm::StringRef::end(), llvm::StringRef::find_first_not_of(), Name, and llvm::StringRef::npos.
Referenced by llvm::MCSectionELF::PrintSwitchToSection().