LLVM: MemoryBuffer.cpp File Reference
LLVM API Documentation
MemoryBuffer.cpp File Reference
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Errno.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Program.h"
#include <cassert>
#include <cerrno>
#include <cstdio>
#include <cstring>
#include <new>
#include <sys/types.h>
#include <system_error>
#include <unistd.h>
Functions
static void CopyStringRef (char *Memory, StringRef Data)
void * operator new (size_t N, const NamedBufferAlloc &Alloc)
static ErrorOr
< std::unique_ptr
< MemoryBuffer > > getFileAux (const Twine &Filename, int64_t FileSize, uint64_t MapSize, uint64_t Offset, bool RequiresNullTerminator, bool IsVolatileSize)
static ErrorOr
< std::unique_ptr
< MemoryBuffer > > getMemoryBufferForStream (int FD, const Twine &BufferName)
static ErrorOr
< std::unique_ptr
< MemoryBuffer > > getOpenFileImpl (int FD, const Twine &Filename, uint64_t FileSize, uint64_t MapSize, int64_t Offset, bool RequiresNullTerminator, bool IsVolatileSize)
static bool shouldUseMmap (int FD, size_t FileSize, size_t MapSize, off_t Offset, bool RequiresNullTerminator, int PageSize, bool IsVolatileSize)
Function Documentation
static void CopyStringRef (char * Memory, StringRef Data) static
CopyStringRef - Copies contents of a StringRef into a block of memory and null-terminates it.
Definition at line 60 of file MemoryBuffer.cpp.
References llvm::StringRef::data(), llvm::Intrinsic::memcpy, and llvm::StringRef::size().
Referenced by llvm::MemoryBuffer::getNewUninitMemBuffer(), and operator new().
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileAux (const Twine & Filename, int64_t FileSize, uint64_t MapSize, uint64_t Offset, bool RequiresNullTerminator, bool IsVolatileSize) static
Definition at line 259 of file MemoryBuffer.cpp.
References getOpenFileImpl(), llvm::sys::fs::openFileForRead(), and llvm::MipsISD::Ret.
Referenced by llvm::MemoryBuffer::getFile(), and llvm::MemoryBuffer::getFileSlice().
static ErrorOr<std::unique_ptr<MemoryBuffer> > getMemoryBufferForStream (int FD, const Twine & BufferName) static
Definition at line 227 of file MemoryBuffer.cpp.
References llvm::SmallVectorTemplateCommon< T >::end(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::LibFunc::read, llvm::SmallVectorImpl< char >::reserve(), llvm::SmallVectorImpl< char >::set_size(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by getOpenFileImpl(), and llvm::MemoryBuffer::getSTDIN().
static ErrorOr< std::unique_ptr< MemoryBuffer > > getOpenFileImpl (int FD, const Twine & Filename, uint64_t FileSize, uint64_t MapSize, int64_t Offset, bool RequiresNullTerminator, bool IsVolatileSize) static
Definition at line 330 of file MemoryBuffer.cpp.
References llvm::sys::fs::block_file, getMemoryBufferForStream(), llvm::MemoryBuffer::getNewUninitMemBuffer(), llvm::sys::Process::getPageSize(), llvm::make_error_code(), llvm::Intrinsic::memset, llvm::not_enough_memory, llvm::LibFunc::pread, llvm::LibFunc::read, llvm::sys::fs::regular_file, shouldUseMmap(), llvm::sys::fs::status(), and llvm::sys::fs::file_status::type().
Referenced by getFileAux(), llvm::MemoryBuffer::getOpenFile(), and llvm::MemoryBuffer::getOpenFileSlice().
void* operator new (size_t N, const NamedBufferAlloc & Alloc)
Definition at line 72 of file MemoryBuffer.cpp.
References CopyStringRef(), N, and llvm::StringRef::size().
static bool shouldUseMmap (int FD, size_t FileSize, size_t MapSize, off_t Offset, bool RequiresNullTerminator, int PageSize, bool IsVolatileSize) static
Definition at line 273 of file MemoryBuffer.cpp.
References assert(), and llvm::sys::fs::status().
Referenced by getOpenFileImpl().