LLVM: MipsTargetObjectFile.cpp File Reference
LLVM API Documentation
MipsTargetObjectFile.cpp File Reference
#include "MipsTargetObjectFile.h"
#include "MipsSubtarget.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ELF.h"
#include "llvm/Target/TargetMachine.h"
Functions
static bool IsInSmallSection (uint64_t Size)
Variables
static cl::opt< unsigned > SSThreshold ("mips-ssection-threshold", cl::Hidden, cl::desc("Small data and bss section threshold size (default=8)"), cl::init(8))
static cl::opt< bool > LocalSData ("mlocal-sdata", cl::Hidden, cl::desc("MIPS: Use gp_rel for object-local data."), cl::init(true))
static cl::opt< bool > ExternSData ("mextern-sdata", cl::Hidden, cl::desc("MIPS: Use gp_rel for data that is not defined by the ""current object."), cl::init(true))
Function Documentation
static bool IsInSmallSection (uint64_t Size) static
Definition at line 57 of file MipsTargetObjectFile.cpp.
References SSThreshold.
Referenced by llvm::MipsTargetObjectFile::IsConstantInSmallSection(), and llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl().
Variable Documentation
cl::opt<bool> ExternSData("mextern-sdata", cl::Hidden, cl::desc("MIPS: Use gp_rel for data that is not defined by the ""current object."), cl::init(true)) static
Referenced by llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl().
cl::opt<bool> LocalSData("mlocal-sdata", cl::Hidden, cl::desc("MIPS: Use gp_rel for object-local data."), cl::init(true)) static
Referenced by llvm::MipsTargetObjectFile::IsConstantInSmallSection(), and llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl().
cl::opt<unsigned> SSThreshold("mips-ssection-threshold", cl::Hidden, cl::desc("Small data and bss section threshold size (default=8)"), cl::init(8)) static
Referenced by IsInSmallSection().