LLVM: MipsTargetStreamer.cpp File Reference
LLVM API Documentation
MipsTargetStreamer.cpp File Reference
#include "InstPrinter/MipsInstPrinter.h"
#include "MipsELFStreamer.h"
#include "MipsMCTargetDesc.h"
#include "MipsTargetObjectFile.h"
#include "MipsTargetStreamer.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
Functions
static void printHex32 (unsigned Value, raw_ostream &OS)
Function Documentation
static void printHex32 (unsigned Value, raw_ostream & OS) static
Definition at line 261 of file MipsTargetStreamer.cpp.
References llvm::raw_ostream::write_hex().
Referenced by llvm::MipsTargetAsmStreamer::emitFMask(), and llvm::MipsTargetAsmStreamer::emitMask().