LLVM: llvm::zlib Namespace Reference
LLVM API Documentation
llvm::zlib Namespace Reference
Enumerations
enum CompressionLevel { NoCompression, DefaultCompression, BestSpeedCompression, BestSizeCompression }
enum Status {
StatusOK, StatusUnsupported, StatusOutOfMemory, StatusBufferTooShort,
StatusInvalidArg, StatusInvalidData
}
Functions
bool isAvailable ()
Status compress (StringRef InputBuffer, SmallVectorImpl< char > &CompressedBuffer, CompressionLevel Level=DefaultCompression)
Status uncompress (StringRef InputBuffer, SmallVectorImpl< char > &UncompressedBuffer, size_t UncompressedSize)
uint32_t crc32 (StringRef Buffer)
Enumeration Type Documentation
enum llvm::zlib::CompressionLevel
Enumerator
NoCompression
DefaultCompression
BestSpeedCompression
BestSizeCompression
Definition at line 27 of file Compression.h.
enum llvm::zlib::Status
Enumerator
StatusOK
StatusUnsupported
StatusOutOfMemory
StatusBufferTooShort
StatusInvalidArg
StatusInvalidData
Definition at line 34 of file Compression.h.
Function Documentation
zlib::Status llvm::zlib::compress (StringRef InputBuffer, SmallVectorImpl< char > & CompressedBuffer, CompressionLevel Level = DefaultCompression)
Definition at line 48 of file Compression.cpp.
References __msan_unpoison, llvm::StringRef::data(), llvm::SmallVectorTemplateCommon< T, typename >::data(), encodeZlibCompressionLevel(), encodeZlibReturnValue(), llvm::SmallVectorImpl< T >::resize(), and llvm::StringRef::size().
Referenced by getCompressedFragment().
uint32_t llvm::zlib::crc32 (StringRef Buffer)
Definition at line 78 of file Compression.cpp.
References llvm::StringRef::data(), and llvm::StringRef::size().
bool llvm::zlib::isAvailable ()
Definition at line 47 of file Compression.cpp.
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory().
zlib::Status llvm::zlib::uncompress (StringRef InputBuffer, SmallVectorImpl< char > & UncompressedBuffer, size_t UncompressedSize)
Definition at line 64 of file Compression.cpp.
References __msan_unpoison, llvm::StringRef::data(), llvm::SmallVectorTemplateCommon< T, typename >::data(), encodeZlibReturnValue(), llvm::SmallVectorImpl< T >::resize(), and llvm::StringRef::size().
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory().