LLVM: NVPTXLowerStructArgs.cpp File Reference
LLVM API Documentation
NVPTXLowerStructArgs.cpp File Reference
#include "NVPTX.h"
#include "NVPTXUtilities.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
Classes
class NVPTXLowerStructArgs
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
void llvm::initializeNVPTXLowerStructArgsPass (PassRegistry &)
INITIALIZE_PASS (NVPTXLowerStructArgs,"nvptx-lower-struct-args","Lower structure arguments (NVPTX)", false, false) void NVPTXLowerStructArgs
Function Documentation
INITIALIZE_PASS (NVPTXLowerStructArgs , "nvptx-lower-struct-args" , "Lower structure arguments (NVPTX)" , false , false)
Definition at line 54 of file NVPTXLowerStructArgs.cpp.
References llvm::ADDRESS_SPACE_GENERIC, llvm::ADDRESS_SPACE_PARAM, llvm::Function::args(), assert(), llvm::CallInst::Create(), llvm::dyn_cast(), F(), llvm::BasicBlock::front(), llvm::PointerType::get(), llvm::Module::getContext(), llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), llvm::Function::getEntryBlock(), llvm::Type::getInt8PtrTy(), llvm::Value::getName(), llvm::Function::getParamAlignment(), llvm::GlobalValue::getParent(), llvm::isKernelFunction(), LI, llvm::Intrinsic::nvvm_ptr_gen_to_param, and llvm::AllocaInst::setAlignment().