LLVM: NVPTXFavorNonGenericAddrSpaces.cpp File Reference
LLVM API Documentation
NVPTXFavorNonGenericAddrSpaces.cpp File Reference
#include "NVPTX.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/CommandLine.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
void llvm::initializeNVPTXFavorNonGenericAddrSpacesPass (PassRegistry &)
INITIALIZE_PASS (NVPTXFavorNonGenericAddrSpaces,"nvptx-favor-non-generic","Remove unnecessary non-generic-to-generic addrspacecasts", false, false) static bool IsEliminableAddrSpaceCast(Operator *Cast)
Variables
static cl::opt< bool > DisableFavorNonGeneric ("disable-nvptx-favor-non-generic", cl::init(false), cl::desc("Do not convert generic address space usage ""to non-generic address space usage"), cl::Hidden)
Function Documentation
INITIALIZE_PASS (NVPTXFavorNonGenericAddrSpaces , "nvptx-favor-non-generic" , "Remove unnecessary non-generic-to-generic addrspacecasts" , false , false)
Definition at line 84 of file NVPTXFavorNonGenericAddrSpaces.cpp.
References llvm::ADDRESS_SPACE_GENERIC, llvm::PointerType::getAddressSpace(), llvm::SequentialType::getElementType(), and llvm::Value::getType().
Variable Documentation
cl::opt<bool> DisableFavorNonGeneric("disable-nvptx-favor-non-generic", cl::init(false), cl::desc("Do not convert generic address space usage ""to non-generic address space usage"), cl::Hidden) static