LLVM: PPCMCInstLower.cpp File Reference
LLVM API Documentation
PPCMCInstLower.cpp File Reference
#include "PPC.h"
#include "MCTargetDesc/PPCMCExpr.h"
#include "PPCSubtarget.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Functions
static MachineModuleInfoMachO & getMachOMMI (AsmPrinter &AP)
static MCSymbol * GetSymbolFromOperand (const MachineOperand &MO, AsmPrinter &AP)
static MCOperand GetSymbolRef (const MachineOperand &MO, const MCSymbol *Symbol, AsmPrinter &Printer, bool isDarwin)
Function Documentation
static MachineModuleInfoMachO& getMachOMMI (AsmPrinter & AP) static
Definition at line 33 of file PPCMCInstLower.cpp.
References llvm::MachineModuleInfo::getObjFileInfo(), and llvm::AsmPrinter::MMI.
Referenced by GetSymbolFromOperand().
static MCSymbol* GetSymbolFromOperand (const MachineOperand & MO, AsmPrinter & AP) static
Definition at line 38 of file PPCMCInstLower.cpp.
References assert(), DL, llvm::StringRef::empty(), llvm::TargetSubtargetInfo::getDataLayout(), llvm::MachineModuleInfoMachO::getFnStubEntry(), llvm::MachineOperand::getGlobal(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfoMachO::getHiddenGVStubEntry(), getMachOMMI(), llvm::Mangler::getNameWithPrefix(), llvm::TargetMachine::getNameWithPrefix(), llvm::MCContext::GetOrCreateSymbol(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::DataLayout::getPrivateGlobalPrefix(), llvm::TargetMachine::getSubtargetImpl(), llvm::AsmPrinter::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::TargetMachine::getTargetTriple(), llvm::GlobalValue::hasInternalLinkage(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isSymbol(), llvm::AsmPrinter::Mang, llvm::PPCII::MO_NLP_FLAG, llvm::PPCII::MO_NLP_HIDDEN_FLAG, llvm::PPCII::MO_PLT_OR_STUB, Name, llvm::AsmPrinter::OutContext, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallString< InternalLen >::str(), llvm::StringRef::substr(), llvm::SystemZISD::TM, and llvm::AsmPrinter::TM.
Referenced by llvm::LowerPPCMachineInstrToMCInst().
static MCOperand GetSymbolRef (const MachineOperand & MO, const MCSymbol * Symbol, AsmPrinter & Printer, bool isDarwin) static
Definition at line 114 of file PPCMCInstLower.cpp.
References llvm::LibFunc::access, llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCOperand::CreateExpr(), llvm::PPCMCExpr::CreateHa(), llvm::PPCMCExpr::CreateLo(), llvm::MCBinaryExpr::CreateSub(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getParent(), llvm::MachineFunction::getPICBaseSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::isJTI(), llvm::PPCII::MO_ACCESS_MASK, llvm::PPCII::MO_DTPREL_LO, llvm::PPCII::MO_HA, llvm::PPCII::MO_LO, llvm::PPCII::MO_PIC_FLAG, llvm::PPCII::MO_PLT_OR_STUB, llvm::PPCII::MO_TLS, llvm::PPCII::MO_TLSGD, llvm::PPCII::MO_TLSLD, llvm::PPCII::MO_TLSLD_LO, llvm::PPCII::MO_TOC_LO, llvm::PPCII::MO_TPREL_HA, llvm::PPCII::MO_TPREL_LO, llvm::AsmPrinter::OutContext, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_LO, llvm::MCSymbolRefExpr::VK_PPC_TLS, llvm::MCSymbolRefExpr::VK_PPC_TLSGD, llvm::MCSymbolRefExpr::VK_PPC_TLSLD, llvm::MCSymbolRefExpr::VK_PPC_TOC_LO, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HA, and llvm::MCSymbolRefExpr::VK_PPC_TPREL_LO.
Referenced by llvm::LowerPPCMachineInstrToMCInst().