LLVM: RegisterScavenging.cpp File Reference
LLVM API Documentation
RegisterScavenging.cpp File Reference
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "reg-scavenging"
Functions
static unsigned getFrameIndexOperandNum (MachineInstr *MI)
Macro Definition Documentation
#define DEBUG_TYPE "reg-scavenging"
Definition at line 31 of file RegisterScavenging.cpp.
Function Documentation
static unsigned getFrameIndexOperandNum (MachineInstr * MI) static
Definition at line 357 of file RegisterScavenging.cpp.
References assert(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::isFI().
Referenced by llvm::RegScavenger::scavengeRegister().