LLVM: Scalarizer.cpp File Reference
LLVM API Documentation
Scalarizer.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Macros
#define DEBUG_TYPE "scalarizer"
Functions
INITIALIZE_PASS_WITH_OPTIONS (Scalarizer,"scalarizer","Scalarize vector operations", false, false) Scatterer
Macro Definition Documentation
#define DEBUG_TYPE "scalarizer"
Definition at line 27 of file Scalarizer.cpp.
Function Documentation
INITIALIZE_PASS_WITH_OPTIONS (Scalarizer , "scalarizer" , "Scalarize vector operations" , false , false)
Definition at line 183 of file Scalarizer.cpp.
References assert(), llvm::dyn_cast(), and llvm::Type::getVectorNumElements().