LLVM: SIInstrInfo.cpp File Reference
LLVM API Documentation
SIInstrInfo.cpp File Reference
SI Implementation of TargetInstrInfo.
#include "SIInstrInfo.h"
#include "AMDGPUTargetMachine.h"
#include "SIDefines.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Support/Debug.h"
Functions
static unsigned getNumOperandsNoGlue (SDNode *Node)
static SDValue findChainOperand (SDNode *Load)
static bool nodesHaveSameOperandValue (SDNode *N0, SDNode *N1, unsigned OpName)
Returns true if both nodes have the same value for the given operand Op, or if both nodes do not have this operand.
static bool isStride64 (unsigned Opc)
static bool offsetsDoNotOverlap (int WidthA, int OffsetA, int WidthB, int OffsetB)
static bool compareMachineOp (const MachineOperand &Op0, const MachineOperand &Op1)
Detailed Description
SI Implementation of TargetInstrInfo.
Definition in file SIInstrInfo.cpp.
Function Documentation
static bool compareMachineOp (const MachineOperand & Op0, const MachineOperand & Op1) static
Definition at line 988 of file SIInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_Immediate, and llvm::MachineOperand::MO_Register.
Referenced by llvm::SIInstrInfo::verifyInstruction().
static SDValue findChainOperand (SDNode * Load) static
Definition at line 45 of file SIInstrInfo.cpp.
References assert(), getNumOperandsNoGlue(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), and llvm::MVT::Other.
Referenced by llvm::SIInstrInfo::areLoadsFromSameBasePtr().
static unsigned getNumOperandsNoGlue (SDNode * Node) static
Definition at line 38 of file SIInstrInfo.cpp.
References llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::Glue, and N.
Referenced by llvm::SIInstrInfo::areLoadsFromSameBasePtr(), and findChainOperand().
static bool isStride64 (unsigned Opc) static
Definition at line 170 of file SIInstrInfo.cpp.
Referenced by llvm::SIInstrInfo::getLdStBaseRegImmOfs().
static bool nodesHaveSameOperandValue (SDNode * N0, SDNode * N1, unsigned OpName) static
Returns true if both nodes have the same value for the given operand Op, or if both nodes do not have this operand.
Definition at line 53 of file SIInstrInfo.cpp.
References llvm::SDNode::getMachineOpcode(), llvm::AMDGPU::getNamedOperandIdx(), and llvm::SDNode::getOperand().
Referenced by llvm::SIInstrInfo::areLoadsFromSameBasePtr().
static bool offsetsDoNotOverlap (int WidthA, int OffsetA, int WidthB, int OffsetB) static
Definition at line 856 of file SIInstrInfo.cpp.