LLVM: SIShrinkInstructions.cpp File Reference
LLVM API Documentation
SIShrinkInstructions.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUMCInstLower.h"
#include "AMDGPUSubtarget.h"
#include "SIInstrInfo.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetMachine.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "si-shrink-instructions"
The pass tries to use the 32-bit encoding for instructions when possible.
Functions
STATISTIC (NumInstructionsShrunk,"Number of 64-bit instruction reduced to 32-bit.")
STATISTIC (NumLiteralConstantsFolded,"Number of literal constants folded into 32-bit instructions.")
void llvm::initializeSIShrinkInstructionsPass (PassRegistry &)
INITIALIZE_PASS_BEGIN (SIShrinkInstructions, DEBUG_TYPE,"SI Lower il Copies", false, false) INITIALIZE_PASS_END(SIShrinkInstructions
static bool isVGPR (const MachineOperand *MO, const SIRegisterInfo &TRI, const MachineRegisterInfo &MRI)
static bool canShrink (MachineInstr &MI, const SIInstrInfo *TII, const SIRegisterInfo &TRI, const MachineRegisterInfo &MRI)
static void foldImmediates (MachineInstr &MI, const SIInstrInfo *TII, MachineRegisterInfo &MRI, bool TryToCommute=true)
This function checks MI for operands defined by a move immediate instruction and then folds the literal constant into the instruction if it can. This function assumes that MI is a VOP1, VOP2, or VOPC instruction and will only fold literal constants if we are still in SSA.
Variables
DEBUG_TYPE
SI Lower il Copies
SI Lower il false
Macro Definition Documentation
#define DEBUG_TYPE "si-shrink-instructions"
The pass tries to use the 32-bit encoding for instructions when possible.
Definition at line 26 of file SIShrinkInstructions.cpp.
Function Documentation
static bool canShrink (MachineInstr & MI, const SIInstrInfo * TII, const SIRegisterInfo & TRI, const MachineRegisterInfo & MRI) static
Definition at line 85 of file SIShrinkInstructions.cpp.
References llvm::MachineOperand::getImm(), llvm::SIInstrInfo::getNamedOperand(), llvm::SIInstrInfo::hasModifiersSet(), and isVGPR().
static void foldImmediates (MachineInstr & MI, const SIInstrInfo * TII, MachineRegisterInfo & MRI, bool TryToCommute = true) static
This function checks MI for operands defined by a move immediate instruction and then folds the literal constant into the instruction if it can. This function assumes that MI is a VOP1, VOP2, or VOPC instruction and will only fold literal constants if we are still in SSA.
Definition at line 120 of file SIShrinkInstructions.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::SIInstrInfo::commuteInstruction(), llvm::tgtok::Def, llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getImm(), llvm::SIInstrInfo::getNamedOperand(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SIInstrInfo::getRegisterInfo(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineInstr::isCommutable(), llvm::MachineOperand::isImm(), llvm::SIInstrInfo::isLiteralConstant(), llvm::MachineInstr::isMoveImmediate(), llvm::MachineOperand::isReg(), llvm::MachineRegisterInfo::isSSA(), llvm::isUInt< 32 >(), isVGPR(), llvm::SIInstrInfo::isVOP1(), llvm::SIInstrInfo::isVOP2(), llvm::SIInstrInfo::isVOPC(), and llvm::MachineRegisterInfo::use_empty().
INITIALIZE_PASS_BEGIN (SIShrinkInstructions , DEBUG_TYPE , "SI Lower il Copies" , false , false)
static bool isVGPR (const MachineOperand * MO, const SIRegisterInfo & TRI, const MachineRegisterInfo & MRI) static
Definition at line 74 of file SIShrinkInstructions.cpp.
References llvm::SIRegisterInfo::getPhysRegClass(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::SIRegisterInfo::hasVGPRs(), llvm::MachineOperand::isReg(), and llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by canShrink(), and foldImmediates().
STATISTIC (NumInstructionsShrunk , "Number of 64-bit instruction reduced to 32-bit.")
STATISTIC (NumLiteralConstantsFolded , "Number of literal constants folded into 32-bit instructions.")
Variable Documentation
SI Lower il Copies
Definition at line 65 of file SIShrinkInstructions.cpp.
DEBUG_TYPE
Definition at line 65 of file SIShrinkInstructions.cpp.
SI Lower il false
Definition at line 65 of file SIShrinkInstructions.cpp.