LLVM: SparcMCExpr.cpp File Reference
LLVM API Documentation
SparcMCExpr.cpp File Reference
#include "SparcMCExpr.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELF.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Object/ELF.h"
Macros
#define DEBUG_TYPE "sparcmcexpr"
Functions
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr *Expr, MCAssembler &Asm)
Macro Definition Documentation
#define DEBUG_TYPE "sparcmcexpr"
Definition at line 26 of file SparcMCExpr.cpp.
Function Documentation
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr * Expr, MCAssembler & Asm) static
Definition at line 169 of file SparcMCExpr.cpp.
References llvm::HexStyle::Asm, llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::MCELF::SetType(), llvm::ELF::STT_TLS, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
Referenced by llvm::SparcMCExpr::fixELFSymbolsInTLSFixups().