LLVM: SparcRegisterInfo.cpp File Reference
LLVM API Documentation
SparcRegisterInfo.cpp File Reference
#include "SparcRegisterInfo.h"
#include "Sparc.h"
#include "SparcMachineFunctionInfo.h"
#include "SparcSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "SparcGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
Functions
static void replaceFI (MachineFunction &MF, MachineBasicBlock::iterator II, MachineInstr &MI, DebugLoc dl, unsigned FIOperandNum, int Offset, unsigned FramePtr)
Variables
static cl::opt< bool > ReserveAppRegisters ("sparc-reserve-app-registers", cl::Hidden, cl::init(false), cl::desc("Reserve application registers (%g2-%g4)"))
Macro Definition Documentation
#define GET_REGINFO_TARGET_DESC
Definition at line 30 of file SparcRegisterInfo.cpp.
Function Documentation
static void replaceFI (MachineFunction & MF, MachineBasicBlock::iterator II, MachineInstr & MI, DebugLoc dl, unsigned FIOperandNum, int Offset, unsigned FramePtr) static
Definition at line 95 of file SparcRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MCInstrInfo::get(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getSubtarget(), llvm::HI22(), llvm::HIX22(), llvm::LO10(), llvm::LOX10(), and TII.
Referenced by llvm::SparcRegisterInfo::eliminateFrameIndex().
Variable Documentation
cl::opt<bool> ReserveAppRegisters("sparc-reserve-app-registers", cl::Hidden, cl::init(false), cl::desc("Reserve application registers (%g2-%g4)")) static
Referenced by llvm::SparcRegisterInfo::getReservedRegs().