LLVM: StripDeadPrototypes.cpp File Reference
LLVM API Documentation
StripDeadPrototypes.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "strip-dead-prototypes"
Functions
STATISTIC (NumDeadPrototypes,"Number of dead prototypes removed")
INITIALIZE_PASS (StripDeadPrototypesPass,"strip-dead-prototypes","Strip Unused Function Prototypes", false, false) bool StripDeadPrototypesPass
Macro Definition Documentation
#define DEBUG_TYPE "strip-dead-prototypes"
Definition at line 23 of file StripDeadPrototypes.cpp.
Function Documentation
INITIALIZE_PASS (StripDeadPrototypesPass , "strip-dead-prototypes" , "Strip Unused Function Prototypes" , false , false)
Definition at line 42 of file StripDeadPrototypes.cpp.
References llvm::GlobalVariable::eraseFromParent(), llvm::Function::eraseFromParent(), F(), I, llvm::GlobalValue::isDeclaration(), and llvm::Value::use_empty().
STATISTIC (NumDeadPrototypes , "Number of dead prototypes removed")