LLVM: llvm::MDLocationInfo::KeyTy Struct Reference
LLVM API Documentation
llvm::MDLocationInfo::KeyTy Struct Reference
#include <LLVMContextImpl.h>
Public Member Functions
KeyTy (unsigned Line, unsigned Column, Metadata *Scope, Metadata *InlinedAt)
KeyTy (const MDLocation *L)
bool operator== (const MDLocation *RHS) const
Public Attributes
unsigned Line
unsigned Column
Metadata * Scope
Metadata * InlinedAt
Detailed Description
Definition at line 220 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::MDLocationInfo::KeyTy::KeyTy (unsigned Line, unsigned Column, Metadata * Scope, Metadata * InlinedAt) inline
Definition at line 226 of file LLVMContextImpl.h.
llvm::MDLocationInfo::KeyTy::KeyTy (const MDLocation * L) inline
Definition at line 229 of file LLVMContextImpl.h.
Member Function Documentation
bool llvm::MDLocationInfo::KeyTy::operator== (const MDLocation * RHS) const inline
Definition at line 233 of file LLVMContextImpl.h.
References Column, llvm::MDLocation::getColumn(), llvm::MDLocationInfo::getEmptyKey(), llvm::MDLocation::getInlinedAt(), llvm::MDLocation::getLine(), llvm::MDLocation::getScope(), llvm::MDLocationInfo::getTombstoneKey(), InlinedAt, Line, and Scope.
Member Data Documentation
unsigned llvm::MDLocationInfo::KeyTy::Column
Definition at line 222 of file LLVMContextImpl.h.
Referenced by llvm::MDLocationInfo::getHashValue(), and operator==().
Metadata* llvm::MDLocationInfo::KeyTy::InlinedAt
Definition at line 224 of file LLVMContextImpl.h.
Referenced by llvm::MDLocationInfo::getHashValue(), and operator==().
unsigned llvm::MDLocationInfo::KeyTy::Line
Definition at line 221 of file LLVMContextImpl.h.
Referenced by llvm::MDLocationInfo::getHashValue(), and operator==().
Metadata* llvm::MDLocationInfo::KeyTy::Scope
Definition at line 223 of file LLVMContextImpl.h.
Referenced by llvm::MDLocationInfo::getHashValue(), and operator==().
The documentation for this struct was generated from the following file:
LLVMContextImpl.h