LLVM: llvm::GraphTraits< MachineBlockFrequencyInfo * > Struct Template Reference
LLVM API Documentation
llvm::GraphTraits< MachineBlockFrequencyInfo * > Struct Template Reference
Public Types
typedef const MachineBasicBlock NodeType
typedef
MachineBasicBlock::const_succ_iterator ChildIteratorType
typedef
MachineFunction::const_iterator nodes_iterator
Static Public Member Functions
static const NodeType * getEntryNode (const MachineBlockFrequencyInfo *G)
static ChildIteratorType child_begin (const NodeType *N)
static ChildIteratorType child_end (const NodeType *N)
static nodes_iterator nodes_begin (const MachineBlockFrequencyInfo *G)
static nodes_iterator nodes_end (const MachineBlockFrequencyInfo *G)
Detailed Description
template<>
struct llvm::GraphTraits< MachineBlockFrequencyInfo * >
Definition at line 53 of file MachineBlockFrequencyInfo.cpp.
Member Typedef Documentation
typedef MachineBasicBlock::const_succ_iterator llvm::GraphTraits< MachineBlockFrequencyInfo * >::ChildIteratorType
Definition at line 55 of file MachineBlockFrequencyInfo.cpp.
typedef MachineFunction::const_iterator llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_iterator
Definition at line 56 of file MachineBlockFrequencyInfo.cpp.
typedef const MachineBasicBlock llvm::GraphTraits< MachineBlockFrequencyInfo * >::NodeType
Definition at line 54 of file MachineBlockFrequencyInfo.cpp.
Member Function Documentation
static ChildIteratorType llvm::GraphTraits< MachineBlockFrequencyInfo * >::child_begin (const NodeType * N) inline static
Definition at line 63 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineBasicBlock::succ_begin().
static ChildIteratorType llvm::GraphTraits< MachineBlockFrequencyInfo * >::child_end (const NodeType * N) inline static
Definition at line 67 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineBasicBlock::succ_end().
static const NodeType* llvm::GraphTraits< MachineBlockFrequencyInfo * >::getEntryNode (const MachineBlockFrequencyInfo * G) inline static
Definition at line 59 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineFunction::begin(), and llvm::MachineBlockFrequencyInfo::getFunction().
static nodes_iterator llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_begin (const MachineBlockFrequencyInfo * G) inline static
Definition at line 71 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineFunction::begin(), and llvm::MachineBlockFrequencyInfo::getFunction().
static nodes_iterator llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_end (const MachineBlockFrequencyInfo * G) inline static
Definition at line 75 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineFunction::end(), and llvm::MachineBlockFrequencyInfo::getFunction().
The documentation for this struct was generated from the following file:
MachineBlockFrequencyInfo.cpp