LLVM: llvm::SCEVApplyRewriter Struct Reference
LLVM API Documentation
llvm::SCEVApplyRewriter Struct Reference
#include <ScalarEvolutionExpressions.h>
Public Member Functions
SCEVApplyRewriter (ScalarEvolution &S, LoopToScevMapT &M)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >
const SCEV * visit (const SCEV *S)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *S)
Static Public Member Functions
static const SCEV * rewrite (const SCEV *Scev, LoopToScevMapT &Map, ScalarEvolution &SE)
Detailed Description
The SCEVApplyRewriter takes a scalar evolution expression and applies the Map (Loop -> SCEV) to all AddRecExprs.
Definition at line 735 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
llvm::SCEVApplyRewriter::SCEVApplyRewriter (ScalarEvolution & S, LoopToScevMapT & M) inline
Definition at line 744 of file ScalarEvolutionExpressions.h.
Member Function Documentation
static const SCEV* llvm::SCEVApplyRewriter::rewrite (const SCEV * Scev, LoopToScevMapT & Map, ScalarEvolution & SE) inline static
Definition at line 738 of file ScalarEvolutionExpressions.h.
References Rewriter, and llvm::SCEVVisitor< SC, RetVal >::visit().
Referenced by llvm::apply().
const SCEV* llvm::SCEVApplyRewriter::visitAddExpr (const SCEVAddExpr * Expr) inline
Definition at line 766 of file ScalarEvolutionExpressions.h.
References llvm::ScalarEvolution::getAddExpr(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), Operands, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
const SCEV* llvm::SCEVApplyRewriter::visitAddRecExpr (const SCEVAddRecExpr * Expr) inline
Definition at line 784 of file ScalarEvolutionExpressions.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddRecExpr(), llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), Operands, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
const SCEV* llvm::SCEVApplyRewriter::visitConstant (const SCEVConstant * Constant) inline
Definition at line 747 of file ScalarEvolutionExpressions.h.
References llvm::ISD::Constant.
const SCEV* llvm::SCEVApplyRewriter::visitCouldNotCompute (const SCEVCouldNotCompute * Expr) inline
Definition at line 817 of file ScalarEvolutionExpressions.h.
const SCEV* llvm::SCEVApplyRewriter::visitMulExpr (const SCEVMulExpr * Expr) inline
Definition at line 773 of file ScalarEvolutionExpressions.h.
References llvm::ScalarEvolution::getMulExpr(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), Operands, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
const SCEV* llvm::SCEVApplyRewriter::visitSignExtendExpr (const SCEVSignExtendExpr * Expr) inline
Definition at line 761 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEVCastExpr::getType(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
const SCEV* llvm::SCEVApplyRewriter::visitSMaxExpr (const SCEVSMaxExpr * Expr) inline
Definition at line 799 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), llvm::ScalarEvolution::getSMaxExpr(), Operands, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
const SCEV* llvm::SCEVApplyRewriter::visitTruncateExpr (const SCEVTruncateExpr * Expr) inline
Definition at line 751 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::ScalarEvolution::getTruncateExpr(), llvm::SCEVCastExpr::getType(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
const SCEV* llvm::SCEVApplyRewriter::visitUDivExpr (const SCEVUDivExpr * Expr) inline
Definition at line 780 of file ScalarEvolutionExpressions.h.
References llvm::SCEVUDivExpr::getLHS(), llvm::SCEVUDivExpr::getRHS(), llvm::ScalarEvolution::getUDivExpr(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
const SCEV* llvm::SCEVApplyRewriter::visitUMaxExpr (const SCEVUMaxExpr * Expr) inline
Definition at line 806 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), llvm::ScalarEvolution::getUMaxExpr(), Operands, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
const SCEV* llvm::SCEVApplyRewriter::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 813 of file ScalarEvolutionExpressions.h.
const SCEV* llvm::SCEVApplyRewriter::visitZeroExtendExpr (const SCEVZeroExtendExpr * Expr) inline
Definition at line 756 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::SCEVCastExpr::getType(), llvm::ScalarEvolution::getZeroExtendExpr(), and llvm::SCEVVisitor< SCEVApplyRewriter, const SCEV * >::visit().
The documentation for this struct was generated from the following file:
ScalarEvolutionExpressions.h