LLVM: llvm::DominatorTreeVerifierPass Struct Reference
LLVM API Documentation
llvm::DominatorTreeVerifierPass Struct Reference
Verifier pass for the DominatorTree.
#include <Dominators.h>
Public Member Functions
PreservedAnalyses run (Function &F, AnalysisManager< Function > *AM)
Static Public Member Functions
static StringRef name ()
Detailed Description
Verifier pass for the DominatorTree.
Definition at line 200 of file Dominators.h.
Member Function Documentation
static StringRef llvm::DominatorTreeVerifierPass::name () inline static
Definition at line 203 of file Dominators.h.
PreservedAnalyses DominatorTreeVerifierPass::run (Function & F, AnalysisManager< Function > * AM)
Definition at line 328 of file Dominators.cpp.
References llvm::PreservedAnalyses::all(), F(), and llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::getResult().
The documentation for this struct was generated from the following files:
Dominators.h
Dominators.cpp