LLVM: llvm::DebugLocEntry::Value Struct Reference
LLVM API Documentation
llvm::DebugLocEntry::Value Struct Reference
A single location or constant.
#include <DebugLocEntry.h>
Public Types
enum EntryType { E_Location, E_Integer, E_ConstantFP, E_ConstantInt }
Public Member Functions
Value (const MDNode *Var, const MDNode *Expr, int64_t i)
Value (const MDNode *Var, const MDNode *Expr, const ConstantFP *CFP)
Value (const MDNode *Var, const MDNode *Expr, const ConstantInt *CIP)
Value (const MDNode *Var, const MDNode *Expr, MachineLocation Loc)
bool isLocation () const
bool isInt () const
bool isConstantFP () const
bool isConstantInt () const
int64_t getInt () const
const ConstantFP * getConstantFP () const
const ConstantInt * getConstantInt () const
MachineLocation getLoc () const
const MDNode * getVariableNode () const
DIVariable getVariable () const
bool isVariablePiece () const
DIExpression getExpression () const
Public Attributes
const MDNode * Variable
const MDNode * Expression
enum EntryType EntryKind
union {
int64_t Int
const ConstantFP * CFP
const ConstantInt * CIP
} Constant
MachineLocation Loc
Friends
bool operator== (const Value &, const Value &)
Compare two Values for equality.
bool operator< (const Value &, const Value &)
Compare two pieces based on their offset.
Detailed Description
A single location or constant.
Definition at line 28 of file DebugLocEntry.h.
Member Enumeration Documentation
enum llvm::DebugLocEntry::Value::EntryType
Enumerator
E_Location
E_Integer
E_ConstantFP
E_ConstantInt
Definition at line 54 of file DebugLocEntry.h.
Constructor & Destructor Documentation
llvm::DebugLocEntry::Value::Value (const MDNode * Var, const MDNode * Expr, int64_t i) inline
Definition at line 29 of file DebugLocEntry.h.
llvm::DebugLocEntry::Value::Value (const MDNode * Var, const MDNode * Expr, const ConstantFP * CFP) inline
Definition at line 33 of file DebugLocEntry.h.
References CFP.
llvm::DebugLocEntry::Value::Value (const MDNode * Var, const MDNode * Expr, const ConstantInt * CIP) inline
Definition at line 37 of file DebugLocEntry.h.
References CIP.
llvm::DebugLocEntry::Value::Value (const MDNode * Var, const MDNode * Expr, MachineLocation Loc) inline
Definition at line 41 of file DebugLocEntry.h.
References assert(), and Verify.
Member Function Documentation
const ConstantFP* llvm::DebugLocEntry::Value::getConstantFP () const inline
Definition at line 72 of file DebugLocEntry.h.
const ConstantInt* llvm::DebugLocEntry::Value::getConstantInt () const inline
Definition at line 73 of file DebugLocEntry.h.
DIExpression llvm::DebugLocEntry::Value::getExpression () const inline
Definition at line 78 of file DebugLocEntry.h.
References Expression.
Referenced by llvm::DwarfDebug::emitDebugLocValue(), isVariablePiece(), llvm::operator<(), and llvm::DebugLocEntry::sortUniqueValues().
int64_t llvm::DebugLocEntry::Value::getInt () const inline
Definition at line 71 of file DebugLocEntry.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
MachineLocation llvm::DebugLocEntry::Value::getLoc () const inline
Definition at line 74 of file DebugLocEntry.h.
References Loc.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
DIVariable llvm::DebugLocEntry::Value::getVariable () const inline
Definition at line 76 of file DebugLocEntry.h.
References Variable.
Referenced by llvm::DwarfDebug::emitDebugLocValue(), and llvm::DebugLocEntry::sortUniqueValues().
const MDNode* llvm::DebugLocEntry::Value::getVariableNode () const inline
Definition at line 75 of file DebugLocEntry.h.
References Variable.
bool llvm::DebugLocEntry::Value::isConstantFP () const inline
Definition at line 69 of file DebugLocEntry.h.
References E_ConstantFP, and EntryKind.
bool llvm::DebugLocEntry::Value::isConstantInt () const inline
Definition at line 70 of file DebugLocEntry.h.
References E_ConstantInt, and EntryKind.
bool llvm::DebugLocEntry::Value::isInt () const inline
Definition at line 68 of file DebugLocEntry.h.
References E_Integer, and EntryKind.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
bool llvm::DebugLocEntry::Value::isLocation () const inline
Definition at line 67 of file DebugLocEntry.h.
References E_Location, and EntryKind.
Referenced by llvm::DwarfDebug::emitDebugLocValue().
bool llvm::DebugLocEntry::Value::isVariablePiece () const inline
Definition at line 77 of file DebugLocEntry.h.
References getExpression(), and llvm::DIExpression::isVariablePiece().
Referenced by llvm::DwarfDebug::emitDebugLocEntry().
Friends And Related Function Documentation
bool operator< (const Value & A, const Value & B) friend
Compare two pieces based on their offset.
Definition at line 177 of file DebugLocEntry.h.
bool operator== (const Value & A, const Value & B) friend
Compare two Values for equality.
Definition at line 152 of file DebugLocEntry.h.
Member Data Documentation
const ConstantFP* llvm::DebugLocEntry::Value::CFP
Definition at line 60 of file DebugLocEntry.h.
Referenced by llvm::operator==(), and Value().
const ConstantInt* llvm::DebugLocEntry::Value::CIP
Definition at line 61 of file DebugLocEntry.h.
Referenced by llvm::operator==(), and Value().
union { ... } llvm::DebugLocEntry::Value::Constant
Referenced by llvm::operator==().
enum EntryType llvm::DebugLocEntry::Value::EntryKind
Definition at line 55 of file DebugLocEntry.h.
Referenced by isConstantFP(), isConstantInt(), isInt(), isLocation(), and llvm::operator==().
const MDNode* llvm::DebugLocEntry::Value::Expression
Definition at line 51 of file DebugLocEntry.h.
Referenced by getExpression(), and llvm::operator==().
int64_t llvm::DebugLocEntry::Value::Int
Definition at line 59 of file DebugLocEntry.h.
Referenced by llvm::operator==().
MachineLocation llvm::DebugLocEntry::Value::Loc
Definition at line 65 of file DebugLocEntry.h.
Referenced by getLoc(), and llvm::operator==().
const MDNode* llvm::DebugLocEntry::Value::Variable
Definition at line 48 of file DebugLocEntry.h.
Referenced by getVariable(), getVariableNode(), and llvm::operator==().
The documentation for this struct was generated from the following file:
DebugLocEntry.h