LLVM: llvm::Win64EH::UnwindInfo Struct Reference
LLVM API Documentation
llvm::Win64EH::UnwindInfo Struct Reference
UnwindInfo - An entry in the exception table.
#include <Win64EH.h>
Public Member Functions
uint8_t getVersion () const
uint8_t getFlags () const
uint8_t getFrameRegister () const
uint8_t getFrameOffset () const
void * getLanguageSpecificData ()
Return pointer to language specific data part of UnwindInfo.
const void * getLanguageSpecificData () const
Return pointer to language specific data part of UnwindInfo.
uint32_t getLanguageSpecificHandlerOffset () const
Return image-relative offset of language-specific exception handler.
void setLanguageSpecificHandlerOffset (uint32_t offset)
Set image-relative offset of language-specific exception handler.
void * getExceptionData ()
Return pointer to exception-specific data.
RuntimeFunction * getChainedFunctionEntry ()
Return pointer to chained unwind info.
const RuntimeFunction * getChainedFunctionEntry () const
Return pointer to chained unwind info.
Public Attributes
uint8_t VersionAndFlags
uint8_t PrologSize
uint8_t NumCodes
uint8_t FrameRegisterAndOffset
UnwindCode UnwindCodes [1]
Detailed Description
UnwindInfo - An entry in the exception table.
Definition at line 76 of file Win64EH.h.
Member Function Documentation
RuntimeFunction* llvm::Win64EH::UnwindInfo::getChainedFunctionEntry () inline
Return pointer to chained unwind info.
Definition at line 133 of file Win64EH.h.
References getLanguageSpecificData().
const RuntimeFunction* llvm::Win64EH::UnwindInfo::getChainedFunctionEntry () const inline
Return pointer to chained unwind info.
Definition at line 138 of file Win64EH.h.
References getLanguageSpecificData().
void* llvm::Win64EH::UnwindInfo::getExceptionData () inline
Return pointer to exception-specific data.
Definition at line 127 of file Win64EH.h.
References getLanguageSpecificData().
uint8_t llvm::Win64EH::UnwindInfo::getFlags () const inline
Definition at line 86 of file Win64EH.h.
References VersionAndFlags.
uint8_t llvm::Win64EH::UnwindInfo::getFrameOffset () const inline
Definition at line 92 of file Win64EH.h.
References FrameRegisterAndOffset.
uint8_t llvm::Win64EH::UnwindInfo::getFrameRegister () const inline
Definition at line 89 of file Win64EH.h.
References FrameRegisterAndOffset.
void* llvm::Win64EH::UnwindInfo::getLanguageSpecificData () inline
Return pointer to language specific data part of UnwindInfo.
Definition at line 105 of file Win64EH.h.
References NumCodes, and UnwindCodes.
Referenced by getChainedFunctionEntry(), getExceptionData(), getLanguageSpecificHandlerOffset(), and setLanguageSpecificHandlerOffset().
const void* llvm::Win64EH::UnwindInfo::getLanguageSpecificData () const inline
Return pointer to language specific data part of UnwindInfo.
Definition at line 110 of file Win64EH.h.
References NumCodes, and UnwindCodes.
uint32_t llvm::Win64EH::UnwindInfo::getLanguageSpecificHandlerOffset () const inline
Return image-relative offset of language-specific exception handler.
Definition at line 115 of file Win64EH.h.
References getLanguageSpecificData().
uint8_t llvm::Win64EH::UnwindInfo::getVersion () const inline
Definition at line 83 of file Win64EH.h.
References VersionAndFlags.
void llvm::Win64EH::UnwindInfo::setLanguageSpecificHandlerOffset (uint32_t offset) inline
Set image-relative offset of language-specific exception handler.
Definition at line 121 of file Win64EH.h.
References getLanguageSpecificData().
Member Data Documentation
uint8_t llvm::Win64EH::UnwindInfo::FrameRegisterAndOffset
Definition at line 80 of file Win64EH.h.
Referenced by getFrameOffset(), and getFrameRegister().
uint8_t llvm::Win64EH::UnwindInfo::NumCodes
Definition at line 79 of file Win64EH.h.
Referenced by getLanguageSpecificData().
uint8_t llvm::Win64EH::UnwindInfo::PrologSize
Definition at line 78 of file Win64EH.h.
UnwindCode llvm::Win64EH::UnwindInfo::UnwindCodes[1]
Definition at line 81 of file Win64EH.h.
Referenced by getLanguageSpecificData().
uint8_t llvm::Win64EH::UnwindInfo::VersionAndFlags
Definition at line 77 of file Win64EH.h.
Referenced by getFlags(), and getVersion().
The documentation for this struct was generated from the following file:
Win64EH.h