LLVM: llvm::IntervalPressure Struct Reference
LLVM API Documentation
llvm::IntervalPressure Struct Reference
#include <RegisterPressure.h>
Public Member Functions
void reset ()
Clear the result so it can be used for another round of pressure tracking.
void openTop (SlotIndex NextTop)
void openBottom (SlotIndex PrevBottom)
If the current bottom is not greater than the previous index, open it.
Public Member Functions inherited from llvm::RegisterPressure
void increase (unsigned Reg, const TargetRegisterInfo *TRI, const MachineRegisterInfo *MRI)
void decrease (unsigned Reg, const TargetRegisterInfo *TRI, const MachineRegisterInfo *MRI)
void dump (const TargetRegisterInfo *TRI) const
Public Attributes
SlotIndex TopIdx
Record the boundary of the region being tracked.
SlotIndex BottomIdx
Public Attributes inherited from llvm::RegisterPressure
std::vector< unsigned > MaxSetPressure
Map of max reg pressure indexed by pressure set ID, not class ID.
SmallVector< unsigned, 8 > LiveInRegs
List of live in virtual registers or physical register units.
SmallVector< unsigned, 8 > LiveOutRegs
Detailed Description
RegisterPressure computed within a region of instructions delimited by TopIdx and BottomIdx. During pressure computation, the maximum pressure per register pressure set is increased. Once pressure within a region is fully computed, the live-in and live-out sets are recorded.
This is preferable to RegionPressure when LiveIntervals are available, because delimiting regions by SlotIndex is more robust and convenient than holding block iterators. The block contents can change without invalidating the pressure result.
Definition at line 65 of file RegisterPressure.h.
Member Function Documentation
void IntervalPressure::openBottom (SlotIndex PrevBottom)
If the current bottom is not greater than the previous index, open it.
Definition at line 135 of file RegisterPressure.cpp.
References BottomIdx, llvm::SmallVectorImpl< T >::clear(), and llvm::RegisterPressure::LiveInRegs.
void IntervalPressure::openTop (SlotIndex NextTop)
If the current top is not less than or equal to the next index, open it. We happen to need the SlotIndex for the next top for pressure update.
Definition at line 119 of file RegisterPressure.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::RegisterPressure::LiveInRegs, and TopIdx.
void IntervalPressure::reset ()
Clear the result so it can be used for another round of pressure tracking.
Definition at line 102 of file RegisterPressure.cpp.
References BottomIdx, llvm::SmallVectorImpl< T >::clear(), llvm::RegisterPressure::LiveInRegs, llvm::RegisterPressure::LiveOutRegs, llvm::RegisterPressure::MaxSetPressure, and TopIdx.
Member Data Documentation
SlotIndex llvm::IntervalPressure::BottomIdx
Definition at line 68 of file RegisterPressure.h.
Referenced by openBottom(), and reset().
SlotIndex llvm::IntervalPressure::TopIdx
Record the boundary of the region being tracked.
Definition at line 67 of file RegisterPressure.h.
Referenced by openTop(), and reset().
The documentation for this struct was generated from the following files:
RegisterPressure.h
RegisterPressure.cpp