LLVM: llvm::SIRegisterInfo Struct Reference
LLVM API Documentation
llvm::SIRegisterInfo Struct Reference
#include <SIRegisterInfo.h>
Public Types
enum PreloadedValue {
TGID_X, TGID_Y, TGID_Z, SCRATCH_WAVE_OFFSET,
SCRATCH_PTR, INPUT_PTR, TIDIG_X, TIDIG_Y,
TIDIG_Z
}
Public Member Functions
SIRegisterInfo (const AMDGPUSubtarget &st)
BitVector getReservedRegs (const MachineFunction &MF) const override
unsigned getRegPressureSetLimit (unsigned Idx) const override
bool requiresRegisterScavenging (const MachineFunction &Fn) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const override
const TargetRegisterClass * getCFGStructurizerRegClass (MVT VT) const override
get the register class of the specified type to use in the CFGStructurizer
unsigned getHWRegIndex (unsigned Reg) const override
const TargetRegisterClass * getPhysRegClass (unsigned Reg) const
Return the 'base' register class for this register. e.g. SGPR0 => SReg_32, VGPR => VGPR_32 SGPR0_SGPR1 -> SReg_32, etc.
bool isSGPRClass (const TargetRegisterClass *RC) const
bool isSGPRClassID (unsigned RCID) const
bool hasVGPRs (const TargetRegisterClass *RC) const
const TargetRegisterClass * getEquivalentVGPRClass (const TargetRegisterClass *SRC) const
const TargetRegisterClass * getSubRegClass (const TargetRegisterClass *RC, unsigned SubIdx) const
unsigned getPhysRegSubReg (unsigned Reg, const TargetRegisterClass *SubRC, unsigned Channel) const
bool opCanUseLiteralConstant (unsigned OpType) const
bool opCanUseInlineConstant (unsigned OpType) const
unsigned getPreloadedValue (const MachineFunction &MF, enum PreloadedValue Value) const
Returns the physical register that Value is stored in.
unsigned getNumVGPRsAllowed (unsigned WaveCount) const
Give the maximum number of VGPRs that can be used by WaveCount concurrent waves.
unsigned getNumSGPRsAllowed (unsigned WaveCount) const
Give the maximum number of SGPRs that can be used by WaveCount concurrent waves.
unsigned findUnusedRegister (const MachineRegisterInfo &MRI, const TargetRegisterClass *RC) const
Returns a register that is not used at any point in the function. If all registers are used, then this function will return.
Public Member Functions inherited from llvm::AMDGPURegisterInfo
AMDGPURegisterInfo (const AMDGPUSubtarget &st)
BitVector getReservedRegs (const MachineFunction &MF) const override
unsigned getSubRegFromChannel (unsigned Channel) const
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const override
unsigned getFrameRegister (const MachineFunction &MF) const override
unsigned getIndirectSubReg (unsigned IndirectIndex) const
Additional Inherited Members
Public Attributes inherited from llvm::AMDGPURegisterInfo
const AMDGPUSubtarget & ST
Static Public Attributes inherited from llvm::AMDGPURegisterInfo
static const MCPhysReg CalleeSavedReg = AMDGPU::NoRegister
Detailed Description
Definition at line 24 of file SIRegisterInfo.h.
Member Enumeration Documentation
enum llvm::SIRegisterInfo::PreloadedValue
Enumerator
TGID_X
TGID_Y
TGID_Z
SCRATCH_WAVE_OFFSET
SCRATCH_PTR
INPUT_PTR
TIDIG_X
TIDIG_Y
TIDIG_Z
Definition at line 92 of file SIRegisterInfo.h.
Constructor & Destructor Documentation
SIRegisterInfo::SIRegisterInfo (const AMDGPUSubtarget & st)
Definition at line 28 of file SIRegisterInfo.cpp.
Member Function Documentation
void SIRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS) const override
Definition at line 174 of file SIRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::LLVMContext::emitError(), llvm::MachineInstr::eraseFromParent(), llvm::Function::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::AMDGPUSubtarget::getInstrInfo(), llvm::SIInstrInfo::getNamedOperand(), getNumSubRegsForSpillOp(), llvm::MachineBasicBlock::getParent(), getPhysRegSubReg(), llvm::MachineOperand::getReg(), llvm::SIMachineFunctionInfo::getSpilledReg(), llvm::RegState::ImplicitDefine, llvm::SIInstrInfo::insertNOPs(), llvm::SIInstrInfo::isImmOperandLegal(), llvm::SIMachineFunctionInfo::SpilledReg::Lane, llvm::RegScavenger::scavengeRegister(), llvm::AMDGPURegisterInfo::ST, and llvm::SIMachineFunctionInfo::SpilledReg::VGPR.
unsigned SIRegisterInfo::findUnusedRegister (const MachineRegisterInfo & MRI, const TargetRegisterClass * RC) const
Returns a register that is not used at any point in the function. If all registers are used, then this function will return.
Definition at line 467 of file SIRegisterInfo.cpp.
References llvm::TargetRegisterClass::begin(), llvm::TargetRegisterClass::end(), I, and llvm::MachineRegisterInfo::isPhysRegUsed().
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress(), and llvm::SIMachineFunctionInfo::getSpilledReg().
const TargetRegisterClass * SIRegisterInfo::getCFGStructurizerRegClass (MVT VT) const override virtual
get the register class of the specified type to use in the CFGStructurizer
Reimplemented from llvm::AMDGPURegisterInfo.
Definition at line 296 of file SIRegisterInfo.cpp.
References llvm::MVT::i32, and llvm::MVT::SimpleTy.
const TargetRegisterClass * SIRegisterInfo::getEquivalentVGPRClass (const TargetRegisterClass * SRC) const
Returns
A VGPR reg class with the same width as SRC
Definition at line 341 of file SIRegisterInfo.cpp.
References hasVGPRs().
Referenced by llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOpWithMove(), and llvm::SIInstrInfo::moveToVALU().
unsigned SIRegisterInfo::getHWRegIndex (unsigned Reg) const override virtual
Reimplemented from llvm::AMDGPURegisterInfo.
Definition at line 304 of file SIRegisterInfo.cpp.
Referenced by getPhysRegSubReg().
unsigned SIRegisterInfo::getNumSGPRsAllowed (unsigned WaveCount) const
Give the maximum number of SGPRs that can be used by WaveCount concurrent waves.
Definition at line 493 of file SIRegisterInfo.cpp.
Referenced by getRegPressureSetLimit().
unsigned SIRegisterInfo::getNumVGPRsAllowed (unsigned WaveCount) const
Give the maximum number of VGPRs that can be used by WaveCount concurrent waves.
Definition at line 478 of file SIRegisterInfo.cpp.
Referenced by getRegPressureSetLimit().
const TargetRegisterClass * SIRegisterInfo::getPhysRegClass (unsigned Reg) const
Return the 'base' register class for this register. e.g. SGPR0 => SReg_32, VGPR => VGPR_32 SGPR0_SGPR1 -> SReg_32, etc.
Definition at line 308 of file SIRegisterInfo.cpp.
References assert(), and llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by getPhysRegSubReg(), and isVGPR().
unsigned SIRegisterInfo::getPhysRegSubReg (unsigned Reg, const TargetRegisterClass * SubRC, unsigned Channel) const
Channel This is the register channel (e.g. a value from 0-16), not the SubReg index.
Returns
The sub-register of Reg that is in Channel.
Definition at line 375 of file SIRegisterInfo.cpp.
References assert(), getHWRegIndex(), getPhysRegClass(), llvm::TargetRegisterClass::getRegister(), llvm::TargetRegisterClass::getSize(), and llvm_unreachable.
Referenced by eliminateFrameIndex(), and llvm::SITargetLowering::LowerFormalArguments().
unsigned SIRegisterInfo::getPreloadedValue (const MachineFunction & MF, enum PreloadedValue Value) const
Returns the physical register that Value is stored in.
Definition at line 435 of file SIRegisterInfo.cpp.
References ShaderType::COMPUTE, llvm::MachineFunction::getInfo(), llvm::AMDGPUMachineFunction::getShaderType(), INPUT_PTR, llvm_unreachable, llvm::SIMachineFunctionInfo::NumUserSGPRs, SCRATCH_PTR, SCRATCH_WAVE_OFFSET, llvm::SIMachineFunctionInfo::ScratchOffsetReg, TGID_X, TGID_Y, TGID_Z, TIDIG_X, TIDIG_Y, and TIDIG_Z.
Referenced by llvm::SITargetLowering::LowerFormalArguments().
unsigned SIRegisterInfo::getRegPressureSetLimit (unsigned Idx) const override
Definition at line 53 of file SIRegisterInfo.cpp.
References assert(), llvm::AMDGPUSubtarget::getMaxWavesPerCU(), getNumSGPRsAllowed(), getNumVGPRsAllowed(), I, isSGPRClass(), and llvm::AMDGPURegisterInfo::ST.
BitVector SIRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 32 of file SIRegisterInfo.cpp.
References llvm::BitVector::set().
const TargetRegisterClass * SIRegisterInfo::getSubRegClass (const TargetRegisterClass * RC, unsigned SubIdx) const
Returns
The register class that is used for a sub-register of RC for the given SubIdx. If SubIdx equals NoSubRegister, RC will be returned.
Definition at line 361 of file SIRegisterInfo.cpp.
References isSGPRClass().
bool SIRegisterInfo::hasVGPRs (const TargetRegisterClass * RC) const
Returns
true if this class contains VGPR registers.
Definition at line 332 of file SIRegisterInfo.cpp.
Referenced by llvm::SIInstrInfo::canReadVGPR(), getEquivalentVGPRClass(), hasVGPROperands(), isSGPRClass(), isVGPR(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::moveToVALU(), and llvm::SIInstrInfo::storeRegToStackSlot().
bool llvm::SIRegisterInfo::isSGPRClass (const TargetRegisterClass * RC) const inline
Returns
true if this class contains only SGPR registers
Definition at line 49 of file SIRegisterInfo.h.
References hasVGPRs().
Referenced by llvm::SIInstrInfo::getMovOpcode(), getRegPressureSetLimit(), getSubRegClass(), isSGPRClassID(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), and llvm::SIInstrInfo::usesConstantBus().
bool llvm::SIRegisterInfo::isSGPRClassID (unsigned RCID) const inline
Returns
true if this class ID contains only SGPR registers
Definition at line 57 of file SIRegisterInfo.h.
References isSGPRClass().
bool SIRegisterInfo::opCanUseInlineConstant (unsigned OpType) const
Returns
True if operands defined with this operand type can accept an inline constant. i.e. An integer value in the range (-16, 64) or -4.0f, -2.0f, -1.0f, -0.5f, 0.0f, 0.5f, 1.0f, 2.0f, 4.0f.
Definition at line 428 of file SIRegisterInfo.cpp.
References opCanUseLiteralConstant(), and llvm::AMDGPU::OPERAND_REG_INLINE_C.
Referenced by llvm::SIInstrInfo::isImmOperandLegal().
bool SIRegisterInfo::opCanUseLiteralConstant (unsigned OpType) const
Returns
True if operands defined with this operand type can accept a literal constant (i.e. any 32-bit immediate).
Definition at line 424 of file SIRegisterInfo.cpp.
References llvm::AMDGPU::OPERAND_REG_IMM32.
Referenced by llvm::SIInstrInfo::isImmOperandLegal(), and opCanUseInlineConstant().
bool SIRegisterInfo::requiresRegisterScavenging (const MachineFunction & Fn) const override
Definition at line 81 of file SIRegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasStackObjects().
The documentation for this struct was generated from the following files:
SIRegisterInfo.h
SIRegisterInfo.cpp