LLVM: llvm::bfi_detail::IrreducibleGraph::IrrNode Struct Reference
LLVM API Documentation
llvm::bfi_detail::IrreducibleGraph::IrrNode Struct Reference
#include <BlockFrequencyInfoImpl.h>
Public Types
typedef std::deque< const
IrrNode * >::const_iterator iterator
Public Member Functions
IrrNode (const BlockNode &Node)
iterator pred_begin () const
iterator succ_begin () const
iterator pred_end () const
iterator succ_end () const
Public Attributes
BlockNode Node
unsigned NumIn
std::deque< const IrrNode * > Edges
Detailed Description
Definition at line 531 of file BlockFrequencyInfoImpl.h.
Member Typedef Documentation
typedef std::deque<const IrrNode *>::const_iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::iterator
Definition at line 537 of file BlockFrequencyInfoImpl.h.
Constructor & Destructor Documentation
llvm::bfi_detail::IrreducibleGraph::IrrNode::IrrNode (const BlockNode & Node) inline
Definition at line 535 of file BlockFrequencyInfoImpl.h.
Member Function Documentation
iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::pred_begin () const inline
Definition at line 538 of file BlockFrequencyInfoImpl.h.
References Edges.
iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::pred_end () const inline
Definition at line 540 of file BlockFrequencyInfoImpl.h.
References succ_begin().
iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::succ_begin () const inline
Definition at line 539 of file BlockFrequencyInfoImpl.h.
References Edges, and NumIn.
Referenced by llvm::GraphTraits< IrreducibleGraph >::child_begin(), and pred_end().
iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::succ_end () const inline
Definition at line 541 of file BlockFrequencyInfoImpl.h.
References Edges.
Referenced by llvm::GraphTraits< IrreducibleGraph >::child_end().
Member Data Documentation
std::deque<const IrrNode *> llvm::bfi_detail::IrreducibleGraph::IrrNode::Edges
Definition at line 534 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::bfi_detail::IrreducibleGraph::addEdge(), pred_begin(), succ_begin(), and succ_end().
BlockNode llvm::bfi_detail::IrreducibleGraph::IrrNode::Node
Definition at line 532 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::bfi_detail::BlockEdgesAdder< BT >::operator()().
unsigned llvm::bfi_detail::IrreducibleGraph::IrrNode::NumIn
Definition at line 533 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::bfi_detail::IrreducibleGraph::addEdge(), and succ_begin().
The documentation for this struct was generated from the following file:
BlockFrequencyInfoImpl.h