LLVM: llvm::MultiClass Struct Reference
LLVM API Documentation
llvm::MultiClass Struct Reference
#include <Record.h>
Public Types
typedef std::vector
< std::unique_ptr< Record > > RecordVector
Public Member Functions
void dump () const
MultiClass (const std::string &Name, SMLoc Loc, RecordKeeper &Records)
Public Attributes
Record Rec
RecordVector DefPrototypes
Detailed Description
Definition at line 1664 of file Record.h.
Member Typedef Documentation
typedef std::vector<std::unique_ptr<Record> > llvm::MultiClass::RecordVector
Definition at line 1666 of file Record.h.
Constructor & Destructor Documentation
llvm::MultiClass::MultiClass (const std::string & Name, SMLoc Loc, RecordKeeper & Records) inline
Definition at line 1671 of file Record.h.
Member Function Documentation
void MultiClass::dump () const
Definition at line 1992 of file Record.cpp.
References DefPrototypes, llvm::Record::dump(), llvm::errs(), Rec, and llvm::sys::path::rend().
Referenced by llvm::SubMultiClassReference::dump().
Member Data Documentation
RecordVector llvm::MultiClass::DefPrototypes
Definition at line 1667 of file Record.h.
Referenced by dump().
Record llvm::MultiClass::Rec
Definition at line 1665 of file Record.h.
Referenced by dump(), llvm::UnOpInit::Fold(), and llvm::QualifyName().
The documentation for this struct was generated from the following files:
Record.h
Record.cpp