LLVM: llvm::PostDominatorTree Struct Reference
LLVM API Documentation
llvm::PostDominatorTree Struct Reference
#include <PostDominators.h>
Public Member Functions
PostDominatorTree ()
~PostDominatorTree ()
bool runOnFunction (Function &F) override
void getAnalysisUsage (AnalysisUsage &AU) const override
const std::vector< BasicBlock * > & getRoots () const
DomTreeNode * getRootNode () const
DomTreeNode * operator[] (BasicBlock *BB) const
DomTreeNode * getNode (BasicBlock *BB) const
bool dominates (DomTreeNode *A, DomTreeNode *B) const
bool dominates (const BasicBlock *A, const BasicBlock *B) const
bool properlyDominates (const DomTreeNode *A, DomTreeNode *B) const
bool properlyDominates (BasicBlock *A, BasicBlock *B) const
BasicBlock * findNearestCommonDominator (BasicBlock *A, BasicBlock *B)
const BasicBlock * findNearestCommonDominator (const BasicBlock *A, const BasicBlock *B)
void getDescendants (BasicBlock *R, SmallVectorImpl< BasicBlock * > &Result) const
Get all nodes post-dominated by R, including R itself.
void releaseMemory () override
void print (raw_ostream &OS, const Module *) const override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Attributes
DominatorTreeBase< BasicBlock > * DT
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
PostDominatorTree Class - Concrete subclass of DominatorTree that is used to compute the post-dominator tree.
Definition at line 24 of file PostDominators.h.
Constructor & Destructor Documentation
llvm::PostDominatorTree::PostDominatorTree () inline
Definition at line 28 of file PostDominators.h.
References DT, llvm::PassRegistry::getPassRegistry(), and llvm::initializePostDominatorTreePass().
PostDominatorTree::~PostDominatorTree ()
Definition at line 38 of file PostDominators.cpp.
References DT.
Member Function Documentation
bool llvm::PostDominatorTree::dominates (DomTreeNode * A, DomTreeNode * B) const inline
Definition at line 57 of file PostDominators.h.
References llvm::DominatorTreeBase< N >::dominates(), and DT.
bool llvm::PostDominatorTree::dominates (const BasicBlock * A, const BasicBlock * B) const inline
Definition at line 61 of file PostDominators.h.
References llvm::DominatorTreeBase< N >::dominates(), and DT.
BasicBlock* llvm::PostDominatorTree::findNearestCommonDominator (BasicBlock * A, BasicBlock * B) inline
Definition at line 73 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::findNearestCommonDominator().
const BasicBlock* llvm::PostDominatorTree::findNearestCommonDominator (const BasicBlock * A, const BasicBlock * B) inline
Definition at line 77 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::findNearestCommonDominator().
void llvm::PostDominatorTree::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 37 of file PostDominators.h.
References llvm::AnalysisUsage::setPreservesAll().
void llvm::PostDominatorTree::getDescendants (BasicBlock * R, SmallVectorImpl< BasicBlock * > & Result) const inline
Get all nodes post-dominated by R, including R itself.
Definition at line 83 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::getDescendants().
DomTreeNode* llvm::PostDominatorTree::getNode (BasicBlock * BB) const inline
Definition at line 53 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::getNode().
DomTreeNode* llvm::PostDominatorTree::getRootNode () const inline
Definition at line 45 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::getRootNode().
Referenced by llvm::GraphTraits< PostDominatorTree * >::getEntryNode(), and llvm::DOTGraphTraits< PostDominatorTree * >::getNodeLabel().
const std::vector<BasicBlock*>& llvm::PostDominatorTree::getRoots () const inline
Definition at line 41 of file PostDominators.h.
References DT, and llvm::DominatorBase< NodeT >::getRoots().
DomTreeNode* llvm::PostDominatorTree::operator[] (BasicBlock * BB) const inline
Definition at line 49 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::getNode().
void PostDominatorTree::print (raw_ostream & O, const Module * M) const override virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 42 of file PostDominators.cpp.
References DT, and llvm::DominatorTreeBase< N >::print().
bool llvm::PostDominatorTree::properlyDominates (const DomTreeNode * A, DomTreeNode * B) const inline
Definition at line 65 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::properlyDominates().
bool llvm::PostDominatorTree::properlyDominates (BasicBlock * A, BasicBlock * B) const inline
Definition at line 69 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::properlyDominates().
void llvm::PostDominatorTree::releaseMemory () inline override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 88 of file PostDominators.h.
References DT, and llvm::DominatorTreeBase< N >::releaseMemory().
bool llvm::PostDominatorTree::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Member Data Documentation
DominatorTreeBase<BasicBlock>* llvm::PostDominatorTree::DT
Definition at line 26 of file PostDominators.h.
Referenced by dominates(), findNearestCommonDominator(), getDescendants(), getNode(), getRootNode(), getRoots(), operator[](), PostDominatorTree(), print(), properlyDominates(), releaseMemory(), and ~PostDominatorTree().
char PostDominatorTree::ID = 0 static
Definition at line 25 of file PostDominators.h.
The documentation for this struct was generated from the following files:
PostDominators.h
PostDominators.cpp