LLVM: llvm::Thumb1RegisterInfo Struct Reference
LLVM API Documentation
llvm::Thumb1RegisterInfo Struct Reference
#include <Thumb1RegisterInfo.h>
Public Member Functions
Thumb1RegisterInfo (const ARMSubtarget &STI)
const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
void emitLoadConstPool (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, DebugLoc dl, unsigned DestReg, unsigned SubIdx, int Val, ARMCC::CondCodes Pred=ARMCC::AL, unsigned PredReg=0, unsigned MIFlags=MachineInstr::NoFlags) const override
bool rewriteFrameIndex (MachineBasicBlock::iterator II, unsigned FrameRegIdx, unsigned FrameReg, int &Offset, const ARMBaseInstrInfo &TII) const
void resolveFrameIndex (MachineInstr &MI, unsigned BaseReg, int64_t Offset) const override
bool saveScavengerRegister (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator &UseMI, const TargetRegisterClass *RC, unsigned Reg) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Public Member Functions inherited from llvm::ARMBaseRegisterInfo
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF=nullptr) const override
Code Generation virtual methods...
const uint32_t * getCallPreservedMask (CallingConv::ID) const override
const uint32_t * getNoPreservedMask () const
const uint32_t * getThisReturnPreservedMask (CallingConv::ID) const
BitVector getReservedRegs (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const override
const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC) const override
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
void getRegAllocationHints (unsigned VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > &Hints, const MachineFunction &MF, const VirtRegMap *VRM) const override
void UpdateRegAllocHint (unsigned Reg, unsigned NewReg, MachineFunction &MF) const override
bool avoidWriteAfterWrite (const TargetRegisterClass *RC) const override
bool hasBasePointer (const MachineFunction &MF) const
bool canRealignStack (const MachineFunction &MF) const
bool needsStackRealignment (const MachineFunction &MF) const override
int64_t getFrameIndexInstrOffset (const MachineInstr *MI, int Idx) const override
bool needsFrameBaseReg (MachineInstr *MI, int64_t Offset) const override
void materializeFrameBaseRegister (MachineBasicBlock *MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const override
void resolveFrameIndex (MachineInstr &MI, unsigned BaseReg, int64_t Offset) const override
bool isFrameOffsetLegal (const MachineInstr *MI, int64_t Offset) const override
bool cannotEliminateFrame (const MachineFunction &MF) const
unsigned getFrameRegister (const MachineFunction &MF) const override
unsigned getBaseRegister () const
bool isLowRegister (unsigned Reg) const
bool requiresRegisterScavenging (const MachineFunction &MF) const override
Code Generation virtual methods...
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool requiresVirtualBaseRegisters (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
bool shouldCoalesce (MachineInstr *MI, const TargetRegisterClass *SrcRC, unsigned SubReg, const TargetRegisterClass *DstRC, unsigned DstSubReg, const TargetRegisterClass *NewRC) const override
SrcRC and DstRC will be morphed into NewRC if this returns true.
Additional Inherited Members
Protected Member Functions inherited from llvm::ARMBaseRegisterInfo
ARMBaseRegisterInfo (const ARMSubtarget &STI)
unsigned getOpcode (int Op) const
Protected Attributes inherited from llvm::ARMBaseRegisterInfo
const ARMSubtarget & STI
unsigned FramePtr
FramePtr - ARM physical register used as frame ptr.
unsigned BasePtr
Detailed Description
Definition at line 25 of file Thumb1RegisterInfo.h.
Constructor & Destructor Documentation
Thumb1RegisterInfo::Thumb1RegisterInfo (const ARMSubtarget & STI)
Definition at line 41 of file Thumb1RegisterInfo.cpp.
Member Function Documentation
void Thumb1RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 461 of file Thumb1RegisterInfo.cpp.
References llvm::AddDefaultPred(), assert(), llvm::ARMBaseRegisterInfo::BasePtr, llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), emitLoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::MachineInstr::findFirstPredOperandIdx(), llvm::ISD::FrameIndex, llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::ARMFunctionInfo::getFramePtrSpillOffset(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineFunction::getTarget(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::TargetFrameLowering::hasFP(), llvm::TargetFrameLowering::hasReservedCallFrame(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineInstr::isDebugValue(), llvm::MachineInstr::isPredicable(), llvm::RegScavenger::isScavengingFrameIndex(), llvm::ARMFunctionInfo::isThumbFunction(), llvm_unreachable, llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), llvm::AArch64CC::MI, removeOperands(), rewriteFrameIndex(), llvm::MachineInstr::setDesc(), and TII.
void Thumb1RegisterInfo::emitLoadConstPool (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, DebugLoc dl, unsigned DestReg, unsigned SubIdx, int Val, ARMCC::CondCodes Pred = ARMCC::AL, unsigned PredReg = 0, unsigned MIFlags = MachineInstr::NoFlags) const override virtual
emitLoadConstPool - Emits a load from constpool to materialize the specified immediate.
Reimplemented from llvm::ARMBaseRegisterInfo.
Definition at line 62 of file Thumb1RegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::CallingConv::C, llvm::MCInstrInfo::get(), llvm::ConstantInt::get(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstantPoolIndex(), llvm::Function::getContext(), llvm::getDefRegState(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::Type::getInt32Ty(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::isARMLowRegister(), llvm::MachineInstrBuilder::setMIFlags(), and TII.
Referenced by eliminateFrameIndex().
const TargetRegisterClass * Thumb1RegisterInfo::getLargestLegalSuperClass (const TargetRegisterClass * RC) const override
Definition at line 46 of file Thumb1RegisterInfo.cpp.
References llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass().
const TargetRegisterClass * Thumb1RegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
Definition at line 54 of file Thumb1RegisterInfo.cpp.
void Thumb1RegisterInfo::resolveFrameIndex (MachineInstr & MI, unsigned BaseReg, int64_t Offset) const override
Definition at line 389 of file Thumb1RegisterInfo.cpp.
References assert(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineFunction::getTarget(), llvm::MachineOperand::isFI(), rewriteFrameIndex(), and TII.
bool Thumb1RegisterInfo::rewriteFrameIndex (MachineBasicBlock::iterator II, unsigned FrameRegIdx, unsigned FrameReg, int & Offset, const ARMBaseInstrInfo & TII) const
Definition at line 321 of file Thumb1RegisterInfo.cpp.
References llvm::ARMII::AddrModeMask, llvm::ARMII::AddrModeT1_s, assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), convertToNonSPOpcode(), llvm::emitThumbRegPlusImmediate(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm_unreachable, llvm::AArch64CC::MI, llvm::MachineInstr::setDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by eliminateFrameIndex(), and resolveFrameIndex().
bool Thumb1RegisterInfo::saveScavengerRegister (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator & UseMI, const TargetRegisterClass * RC, unsigned Reg) const override
saveScavengerRegister - Spill the register so it can be used by the register scavenger. Return true.
Definition at line 412 of file Thumb1RegisterInfo.cpp.
References llvm::AddDefaultPred(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineOperand::clobbersPhysReg(), llvm::RegState::Define, DL, llvm::MCInstrInfo::get(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineOperand::isUndef(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::RegState::Kill, and TII.
The documentation for this struct was generated from the following files:
Thumb1RegisterInfo.h
Thumb1RegisterInfo.cpp