LLVM: llvm::AArch64RegisterInfo Struct Reference
LLVM API Documentation
llvm::AArch64RegisterInfo Struct Reference
#include <AArch64RegisterInfo.h>
Public Member Functions
AArch64RegisterInfo (const AArch64InstrInfo *tii, const AArch64Subtarget *sti)
bool isReservedReg (const MachineFunction &MF, unsigned Reg) const
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF=nullptr) const override
Code Generation virtual methods...
const uint32_t * getCallPreservedMask (CallingConv::ID) const override
unsigned getCSRFirstUseCost () const override
const uint32_t * getTLSCallPreservedMask () const
const uint32_t * getThisReturnPreservedMask (CallingConv::ID) const
BitVector getReservedRegs (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool useFPForScavengingIndex (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool needsFrameBaseReg (MachineInstr *MI, int64_t Offset) const override
bool isFrameOffsetLegal (const MachineInstr *MI, int64_t Offset) const override
void materializeFrameBaseRegister (MachineBasicBlock *MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const override
void resolveFrameIndex (MachineInstr &MI, unsigned BaseReg, int64_t Offset) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
bool cannotEliminateFrame (const MachineFunction &MF) const
bool requiresVirtualBaseRegisters (const MachineFunction &MF) const override
bool hasBasePointer (const MachineFunction &MF) const
unsigned getBaseRegister () const
unsigned getFrameRegister (const MachineFunction &MF) const override
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
Detailed Description
Definition at line 28 of file AArch64RegisterInfo.h.
Constructor & Destructor Documentation
AArch64RegisterInfo::AArch64RegisterInfo (const AArch64InstrInfo * tii, const AArch64Subtarget * sti)
Definition at line 40 of file AArch64RegisterInfo.cpp.
Member Function Documentation
bool AArch64RegisterInfo::cannotEliminateFrame (const MachineFunction & MF) const
Definition at line 214 of file AArch64RegisterInfo.cpp.
References llvm::MachineFrameInfo::adjustsStack(), llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasCalls(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan().
void AArch64RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 332 of file AArch64RegisterInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::emitFrameOffset(), llvm::ISD::FrameIndex, llvm::MachineInstr::getDebugLoc(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::isDebugValue(), llvm::RegScavenger::isScavengingFrameIndex(), llvm::AArch64CC::MI, llvm::TargetOpcode::PATCHPOINT, llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::rewriteAArch64FrameIndex(), and llvm::TargetOpcode::STACKMAP.
unsigned AArch64RegisterInfo::getBaseRegister () const
Definition at line 157 of file AArch64RegisterInfo.cpp.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
const MCPhysReg * AArch64RegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = nullptr) const override
Code Generation virtual methods...
Definition at line 45 of file AArch64RegisterInfo.cpp.
References llvm::CallingConv::AnyReg, assert(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), and llvm::CallingConv::GHC.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan().
const uint32_t * AArch64RegisterInfo::getCallPreservedMask (CallingConv::ID CC) const override
Definition at line 58 of file AArch64RegisterInfo.cpp.
References llvm::CallingConv::AnyReg, and llvm::CallingConv::GHC.
const TargetRegisterClass * AArch64RegisterInfo::getCrossCopyRegClass (const TargetRegisterClass * RC) const override
Definition at line 151 of file AArch64RegisterInfo.cpp.
unsigned llvm::AArch64RegisterInfo::getCSRFirstUseCost () const inline override
Definition at line 43 of file AArch64RegisterInfo.h.
unsigned AArch64RegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 183 of file AArch64RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), and llvm::TargetFrameLowering::hasFP().
Referenced by llvm::AArch64FrameLowering::emitPrologue(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
const TargetRegisterClass * AArch64RegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
Definition at line 145 of file AArch64RegisterInfo.cpp.
unsigned llvm::AArch64RegisterInfo::getRegPressureLimit (const TargetRegisterClass * RC, MachineFunction & MF) const override
Definition at line 377 of file AArch64RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetRegisterClass::getID(), llvm::MachineFunction::getSubtarget(), hasBasePointer(), llvm::TargetFrameLowering::hasFP(), llvm::AArch64Subtarget::isTargetDarwin(), and ReserveX18.
BitVector AArch64RegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 90 of file AArch64RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), hasBasePointer(), llvm::TargetFrameLowering::hasFP(), llvm::AArch64Subtarget::isTargetDarwin(), ReserveX18, and llvm::BitVector::set().
const uint32_t * AArch64RegisterInfo::getThisReturnPreservedMask (CallingConv::ID CC) const
getThisReturnPreservedMask - Returns a call preserved mask specific to the case that 'returned' is on an i64 first argument if the calling convention is one that can (partially) model this attribute with a preserved mask (i.e. it is a calling convention that uses the same register for the first i64 argument and an i64 return value)
Should return NULL in the case that the calling convention does not have this property
Definition at line 77 of file AArch64RegisterInfo.cpp.
References assert(), and llvm::CallingConv::GHC.
const uint32_t * AArch64RegisterInfo::getTLSCallPreservedMask () const
Definition at line 68 of file AArch64RegisterInfo.cpp.
References assert(), llvm::AArch64Subtarget::isTargetDarwin(), and llvm::AArch64Subtarget::isTargetELF().
bool AArch64RegisterInfo::hasBasePointer (const MachineFunction & MF) const
Definition at line 159 of file AArch64RegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getLocalFrameSize(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by llvm::AArch64FrameLowering::emitPrologue(), getRegPressureLimit(), getReservedRegs(), isReservedReg(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), and useFPForScavengingIndex().
bool AArch64RegisterInfo::isFrameOffsetLegal (const MachineInstr * MI, int64_t Offset) const override
Definition at line 287 of file AArch64RegisterInfo.cpp.
References llvm::AArch64FrameOffsetIsLegal, assert(), and llvm::isAArch64FrameOffsetLegal().
Referenced by needsFrameBaseReg().
bool AArch64RegisterInfo::isReservedReg (const MachineFunction & MF, unsigned Reg) const
Definition at line 118 of file AArch64RegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), hasBasePointer(), llvm::TargetFrameLowering::hasFP(), llvm::AArch64Subtarget::isTargetDarwin(), and ReserveX18.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan().
void AArch64RegisterInfo::materializeFrameBaseRegister (MachineBasicBlock * MBB, unsigned BaseReg, int FrameIdx, int64_t Offset) const override
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx at the beginning of the basic block.
Definition at line 297 of file AArch64RegisterInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), DL, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::AArch64_AM::getShifterImm(), llvm::MipsISD::Ins, and llvm::AArch64_AM::LSL.
bool AArch64RegisterInfo::needsFrameBaseReg (MachineInstr * MI, int64_t Offset) const override
needsFrameBaseReg - Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP. Used by LocalStackFrameAllocation to determine which frame index references it should create new base registers for.
Definition at line 227 of file AArch64RegisterInfo.cpp.
References assert(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::MachineOperand::isFI(), isFrameOffsetLegal(), llvm::MachineInstr::mayLoad(), and llvm::MachineInstr::mayStore().
bool AArch64RegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const override
Definition at line 208 of file AArch64RegisterInfo.cpp.
bool AArch64RegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const override
Definition at line 189 of file AArch64RegisterInfo.cpp.
bool AArch64RegisterInfo::requiresVirtualBaseRegisters (const MachineFunction & MF) const override
Definition at line 194 of file AArch64RegisterInfo.cpp.
void AArch64RegisterInfo::resolveFrameIndex (MachineInstr & MI, unsigned BaseReg, int64_t Offset) const override
Definition at line 318 of file AArch64RegisterInfo.cpp.
References assert(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isFI(), and llvm::rewriteAArch64FrameIndex().
bool AArch64RegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const override
Definition at line 200 of file AArch64RegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), hasBasePointer(), and llvm::MachineFrameInfo::hasVarSizedObjects().
The documentation for this struct was generated from the following files:
AArch64RegisterInfo.h
AArch64RegisterInfo.cpp