LLVM: llvm::GraphTraits< const MachineFunction * > Struct Template Reference
LLVM API Documentation
llvm::GraphTraits< const MachineFunction * > Struct Template Reference
#include <MachineFunction.h>
Public Types
typedef
MachineFunction::const_iterator nodes_iterator
Public Types inherited from llvm::GraphTraits< const MachineBasicBlock * >
typedef const MachineBasicBlock NodeType
typedef
MachineBasicBlock::const_succ_iterator ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (const MachineFunction *F)
static nodes_iterator nodes_begin (const MachineFunction *F)
static nodes_iterator nodes_end (const MachineFunction *F)
static unsigned size (const MachineFunction *F)
Static Public Member Functions inherited from llvm::GraphTraits< const MachineBasicBlock * >
static NodeType * getEntryNode (const MachineBasicBlock *BB)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
Detailed Description
template<>
struct llvm::GraphTraits< const MachineFunction * >
Definition at line 504 of file MachineFunction.h.
Member Typedef Documentation
typedef MachineFunction::const_iterator llvm::GraphTraits< const MachineFunction * >::nodes_iterator
Definition at line 511 of file MachineFunction.h.
Member Function Documentation
static NodeType* llvm::GraphTraits< const MachineFunction * >::getEntryNode (const MachineFunction * F) inline static
Definition at line 506 of file MachineFunction.h.
References llvm::MachineFunction::front().
static nodes_iterator llvm::GraphTraits< const MachineFunction * >::nodes_begin (const MachineFunction * F) inline static
Definition at line 512 of file MachineFunction.h.
References llvm::MachineFunction::begin().
static nodes_iterator llvm::GraphTraits< const MachineFunction * >::nodes_end (const MachineFunction * F) inline static
Definition at line 515 of file MachineFunction.h.
References llvm::MachineFunction::end().
static unsigned llvm::GraphTraits< const MachineFunction * >::size (const MachineFunction * F) inline static
Definition at line 518 of file MachineFunction.h.
References llvm::MachineFunction::size().
The documentation for this struct was generated from the following file:
MachineFunction.h