LLVM: llvm::LiveRegSet Struct Reference
LLVM API Documentation
llvm::LiveRegSet Struct Reference
A set of live virtual registers and physical register units.
#include <RegisterPressure.h>
Public Member Functions
bool contains (unsigned Reg) const
bool insert (unsigned Reg)
bool erase (unsigned Reg)
Public Attributes
SparseSet< unsigned > PhysRegs
SparseSet< unsigned,
VirtReg2IndexFunctor > VirtRegs
Detailed Description
A set of live virtual registers and physical register units.
Virtual and physical register numbers require separate sparse sets, but most of the RegisterPressureTracker handles them uniformly.
Definition at line 211 of file RegisterPressure.h.
Member Function Documentation
bool llvm::LiveRegSet::contains (unsigned Reg) const inline
Definition at line 215 of file RegisterPressure.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::count(), llvm::TargetRegisterInfo::isVirtualRegister(), PhysRegs, and VirtRegs.
Referenced by llvm::RegPressureTracker::advance(), llvm::RegPressureTracker::bumpUpwardPressure(), llvm::RegPressureTracker::discoverLiveIn(), llvm::RegPressureTracker::discoverLiveOut(), and llvm::RegPressureTracker::recede().
bool llvm::LiveRegSet::erase (unsigned Reg) inline
Definition at line 227 of file RegisterPressure.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::erase(), llvm::TargetRegisterInfo::isVirtualRegister(), PhysRegs, and VirtRegs.
Referenced by llvm::RegPressureTracker::advance(), and llvm::RegPressureTracker::recede().
bool llvm::LiveRegSet::insert (unsigned Reg) inline
Definition at line 221 of file RegisterPressure.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::insert(), llvm::TargetRegisterInfo::isVirtualRegister(), PhysRegs, and VirtRegs.
Referenced by llvm::RegPressureTracker::addLiveRegs(), llvm::RegPressureTracker::advance(), and llvm::RegPressureTracker::recede().
Member Data Documentation
SparseSet<unsigned> llvm::LiveRegSet::PhysRegs
Definition at line 212 of file RegisterPressure.h.
Referenced by llvm::RegPressureTracker::closeBottom(), llvm::RegPressureTracker::closeRegion(), llvm::RegPressureTracker::closeTop(), contains(), erase(), llvm::RegPressureTracker::init(), insert(), and llvm::RegPressureTracker::reset().
SparseSet<unsigned, VirtReg2IndexFunctor> llvm::LiveRegSet::VirtRegs
Definition at line 213 of file RegisterPressure.h.
Referenced by llvm::RegPressureTracker::closeBottom(), llvm::RegPressureTracker::closeRegion(), llvm::RegPressureTracker::closeTop(), contains(), erase(), llvm::RegPressureTracker::init(), insert(), and llvm::RegPressureTracker::reset().
The documentation for this struct was generated from the following file:
RegisterPressure.h