LLVM: llvm::DwarfAccelTable::HashDataContents Struct Reference
LLVM API Documentation
llvm::DwarfAccelTable::HashDataContents Struct Reference
#include <DwarfAccelTable.h>
Public Member Functions
HashDataContents (const DIE *D, char Flags)
void print (raw_ostream &O) const
Public Attributes
const DIE * Die
char Flags
Detailed Description
Definition at line 167 of file DwarfAccelTable.h.
Constructor & Destructor Documentation
llvm::DwarfAccelTable::HashDataContents::HashDataContents (const DIE * D, char Flags) inline
Definition at line 171 of file DwarfAccelTable.h.
Member Function Documentation
void llvm::DwarfAccelTable::HashDataContents::print (raw_ostream & O) const inline
Definition at line 173 of file DwarfAccelTable.h.
References Die, Flags, llvm::DIE::getOffset(), llvm::DIE::getTag(), and llvm::dwarf::TagString().
Referenced by llvm::DwarfAccelTable::print().
Member Data Documentation
const DIE* llvm::DwarfAccelTable::HashDataContents::Die
Definition at line 168 of file DwarfAccelTable.h.
Referenced by compareDIEs(), and print().
char llvm::DwarfAccelTable::HashDataContents::Flags
Definition at line 169 of file DwarfAccelTable.h.
Referenced by print().
The documentation for this struct was generated from the following file:
DwarfAccelTable.h