LLVM: llvm::object::import_lookup_table_entry< IntTy > Struct Template Reference
LLVM API Documentation
llvm::object::import_lookup_table_entry< IntTy > Struct Template Reference
#include <COFF.h>
Public Member Functions
bool isOrdinal () const
uint16_t getOrdinal () const
uint32_t getHintNameRVA () const
Public Attributes
IntTy Data
Detailed Description
template<typename IntTy>
struct llvm::object::import_lookup_table_entry< IntTy >
Definition at line 173 of file Object/COFF.h.
Member Function Documentation
template<typename IntTy > uint32_t llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA () const inline
Definition at line 183 of file Object/COFF.h.
References assert(), llvm::object::import_lookup_table_entry< IntTy >::Data, and llvm::object::import_lookup_table_entry< IntTy >::isOrdinal().
Referenced by llvm::object::ImportedSymbolRef::getOrdinal(), and llvm::object::ImportedSymbolRef::getSymbolName().
template<typename IntTy > uint16_t llvm::object::import_lookup_table_entry< IntTy >::getOrdinal () const inline
Definition at line 178 of file Object/COFF.h.
References assert(), llvm::object::import_lookup_table_entry< IntTy >::Data, and llvm::object::import_lookup_table_entry< IntTy >::isOrdinal().
Referenced by llvm::object::ImportedSymbolRef::getOrdinal().
template<typename IntTy > bool llvm::object::import_lookup_table_entry< IntTy >::isOrdinal () const inline
Definition at line 176 of file Object/COFF.h.
References llvm::object::import_lookup_table_entry< IntTy >::Data.
Referenced by llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), and llvm::object::import_lookup_table_entry< IntTy >::getOrdinal().
Member Data Documentation
template<typename IntTy > IntTy llvm::object::import_lookup_table_entry< IntTy >::Data
Definition at line 174 of file Object/COFF.h.
Referenced by llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::object::import_lookup_table_entry< IntTy >::getOrdinal(), and llvm::object::import_lookup_table_entry< IntTy >::isOrdinal().
The documentation for this struct was generated from the following file:
Object/COFF.h