LLVM: llvm::AArch64SysReg::SysRegMapper Struct Reference
LLVM API Documentation
llvm::AArch64SysReg::SysRegMapper Struct Reference
#include <AArch64BaseInfo.h>
Public Member Functions
SysRegMapper (uint64_t FeatureBits)
uint32_t fromString (StringRef Name, bool &Valid) const
std::string toString (uint32_t Bits) const
Public Attributes
const
AArch64NamedImmMapper::Mapping * InstPairs
size_t NumInstPairs
uint64_t FeatureBits
Static Public Attributes
static const
AArch64NamedImmMapper::Mapping SysRegPairs []
static const
AArch64NamedImmMapper::Mapping CycloneSysRegPairs []
Detailed Description
Definition at line 1136 of file AArch64BaseInfo.h.
Constructor & Destructor Documentation
llvm::AArch64SysReg::SysRegMapper::SysRegMapper (uint64_t FeatureBits) inline
Definition at line 1144 of file AArch64BaseInfo.h.
Member Function Documentation
uint32_t AArch64SysReg::SysRegMapper::fromString (StringRef Name, bool & Valid) const
Definition at line 764 of file AArch64BaseInfo.cpp.
References llvm::array_lengthof(), llvm::tgtok::Bits, llvm::StringRef::lower(), and llvm::Regex::match().
std::string AArch64SysReg::SysRegMapper::toString (uint32_t Bits) const
Definition at line 817 of file AArch64BaseInfo.cpp.
References llvm::array_lengthof(), assert(), and llvm::utostr().
Member Data Documentation
const AArch64NamedImmMapper::Mapping AArch64SysReg::SysRegMapper::CycloneSysRegPairs static
Initial value:
= {
  {"cpm_ioacc_ctl_el3", CPM_IOACC_CTL_EL3}
}
Definition at line 1138 of file AArch64BaseInfo.h.
uint64_t llvm::AArch64SysReg::SysRegMapper::FeatureBits
Definition at line 1142 of file AArch64BaseInfo.h.
const AArch64NamedImmMapper::Mapping* llvm::AArch64SysReg::SysRegMapper::InstPairs
Definition at line 1140 of file AArch64BaseInfo.h.
Referenced by llvm::AArch64SysReg::MRSMapper::MRSMapper(), and llvm::AArch64SysReg::MSRMapper::MSRMapper().
size_t llvm::AArch64SysReg::SysRegMapper::NumInstPairs
Definition at line 1141 of file AArch64BaseInfo.h.
Referenced by llvm::AArch64SysReg::MRSMapper::MRSMapper(), and llvm::AArch64SysReg::MSRMapper::MSRMapper().
const AArch64NamedImmMapper::Mapping AArch64SysReg::SysRegMapper::SysRegPairs static
Definition at line 1137 of file AArch64BaseInfo.h.
The documentation for this struct was generated from the following files:
AArch64BaseInfo.h
AArch64BaseInfo.cpp