LLVM: llvm::MDTupleInfo Struct Reference
LLVM API Documentation
llvm::MDTupleInfo Struct Reference
DenseMapInfo for MDTuple.
#include <LLVMContextImpl.h>
Classes
struct KeyTy
Static Public Member Functions
static MDTuple * getEmptyKey ()
static MDTuple * getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static unsigned getHashValue (const MDTuple *U)
static bool isEqual (const KeyTy &LHS, const MDTuple *RHS)
static bool isEqual (const MDTuple *LHS, const MDTuple *RHS)
Detailed Description
DenseMapInfo for MDTuple.
Note that we don't need the is-function-local bit, since that's implicit in the operands.
Definition at line 173 of file LLVMContextImpl.h.
Member Function Documentation
static MDTuple* llvm::MDTupleInfo::getEmptyKey () inline static
Definition at line 200 of file LLVMContextImpl.h.
Referenced by llvm::MDTupleInfo::KeyTy::operator==().
static unsigned llvm::MDTupleInfo::getHashValue (const KeyTy & Key) inline static
Definition at line 206 of file LLVMContextImpl.h.
References llvm::MDTupleInfo::KeyTy::Hash.
static unsigned llvm::MDTupleInfo::getHashValue (const MDTuple * U) inline static
Definition at line 207 of file LLVMContextImpl.h.
References llvm::MDTuple::getHash().
static MDTuple* llvm::MDTupleInfo::getTombstoneKey () inline static
Definition at line 203 of file LLVMContextImpl.h.
Referenced by llvm::MDTupleInfo::KeyTy::operator==().
static bool llvm::MDTupleInfo::isEqual (const KeyTy & LHS, const MDTuple * RHS) inline static
Definition at line 210 of file LLVMContextImpl.h.
static bool llvm::MDTupleInfo::isEqual (const MDTuple * LHS, const MDTuple * RHS) inline static
Definition at line 213 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h