LLVM: llvm::RegisterTarget< TargetArchType, HasJIT > Struct Template Reference
LLVM API Documentation
llvm::RegisterTarget< TargetArchType, HasJIT > Struct Template Reference
#include <TargetRegistry.h>
Public Member Functions
RegisterTarget (Target &T, const char *Name, const char *Desc)
Static Public Member Functions
static bool getArchMatch (Triple::ArchType Arch)
Detailed Description
template<Triple::ArchType TargetArchType = Triple::UnknownArch, bool HasJIT = false>
struct llvm::RegisterTarget< TargetArchType, HasJIT >
RegisterTarget - Helper template for registering a target, for use in the target's initialization function. Usage:
Target TheFooTarget; // The global target instance.
extern "C" void LLVMInitializeFooTargetInfo() { RegisterTarget<Triple::foo> X(TheFooTarget, "foo", "Foo description"); }
Definition at line 829 of file TargetRegistry.h.
Constructor & Destructor Documentation
template<Triple::ArchType TargetArchType = Triple::UnknownArch, bool HasJIT = false> llvm::RegisterTarget< TargetArchType, HasJIT >::RegisterTarget (Target & T, const char * Name, const char * Desc) inline
Definition at line 830 of file TargetRegistry.h.
References llvm::RegisterTarget< TargetArchType, HasJIT >::getArchMatch(), and llvm::TargetRegistry::RegisterTarget().
Member Function Documentation
template<Triple::ArchType TargetArchType = Triple::UnknownArch, bool HasJIT = false> static bool llvm::RegisterTarget< TargetArchType, HasJIT >::getArchMatch (Triple::ArchType Arch) inline static
Definition at line 834 of file TargetRegistry.h.
Referenced by llvm::RegisterTarget< TargetArchType, HasJIT >::RegisterTarget().
The documentation for this struct was generated from the following file:
TargetRegistry.h