LLVM: llvm::ARM::WinEH::ExceptionDataRecord Struct Reference
LLVM API Documentation
llvm::ARM::WinEH::ExceptionDataRecord Struct Reference
#include <ARMWinEH.h>
Public Member Functions
ExceptionDataRecord (const support::ulittle32_t *Data)
uint32_t FunctionLength () const
uint8_t Vers () const
bool X () const
bool E () const
bool F () const
uint8_t EpilogueCount () const
uint8_t CodeWords () const
ArrayRef< support::ulittle32_t > EpilogueScopes () const
ArrayRef< uint8_t > UnwindByteCode () const
uint32_t ExceptionHandlerRVA () const
uint32_t ExceptionHandlerParameter () const
Public Attributes
const support::ulittle32_t * Data
Detailed Description
Definition at line 313 of file ARMWinEH.h.
Constructor & Destructor Documentation
llvm::ARM::WinEH::ExceptionDataRecord::ExceptionDataRecord (const support::ulittle32_t * Data) inline
Definition at line 316 of file ARMWinEH.h.
Member Function Documentation
uint8_t llvm::ARM::WinEH::ExceptionDataRecord::CodeWords () const inline
Definition at line 344 of file ARMWinEH.h.
References Data, and llvm::ARM::WinEH::HeaderWords().
Referenced by ExceptionHandlerParameter(), ExceptionHandlerRVA(), and UnwindByteCode().
bool llvm::ARM::WinEH::ExceptionDataRecord::E () const inline
Definition at line 330 of file ARMWinEH.h.
References Data.
Referenced by EpilogueScopes(), and UnwindByteCode().
uint8_t llvm::ARM::WinEH::ExceptionDataRecord::EpilogueCount () const inline
Definition at line 338 of file ARMWinEH.h.
References Data, and llvm::ARM::WinEH::HeaderWords().
Referenced by EpilogueScopes(), ExceptionHandlerParameter(), ExceptionHandlerRVA(), and UnwindByteCode().
ArrayRef<support::ulittle32_t> llvm::ARM::WinEH::ExceptionDataRecord::EpilogueScopes () const inline
Definition at line 350 of file ARMWinEH.h.
References assert(), Data, E(), EpilogueCount(), llvm::ARM::WinEH::HeaderWords(), and llvm::makeArrayRef().
uint32_t llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerParameter () const inline
Definition at line 369 of file ARMWinEH.h.
References assert(), CodeWords(), Data, EpilogueCount(), llvm::ARM::WinEH::HeaderWords(), and X().
uint32_t llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerRVA () const inline
Definition at line 364 of file ARMWinEH.h.
References assert(), CodeWords(), Data, EpilogueCount(), llvm::ARM::WinEH::HeaderWords(), and X().
bool llvm::ARM::WinEH::ExceptionDataRecord::F () const inline
Definition at line 334 of file ARMWinEH.h.
References Data.
uint32_t llvm::ARM::WinEH::ExceptionDataRecord::FunctionLength () const inline
Definition at line 318 of file ARMWinEH.h.
References Data.
ArrayRef<uint8_t> llvm::ARM::WinEH::ExceptionDataRecord::UnwindByteCode () const inline
Definition at line 356 of file ARMWinEH.h.
References CodeWords(), Data, E(), EpilogueCount(), llvm::ARM::WinEH::HeaderWords(), and llvm::makeArrayRef().
uint8_t llvm::ARM::WinEH::ExceptionDataRecord::Vers () const inline
Definition at line 322 of file ARMWinEH.h.
References Data.
bool llvm::ARM::WinEH::ExceptionDataRecord::X () const inline
Definition at line 326 of file ARMWinEH.h.
References Data.
Referenced by ExceptionHandlerParameter(), and ExceptionHandlerRVA().
Member Data Documentation
const support::ulittle32_t* llvm::ARM::WinEH::ExceptionDataRecord::Data
Definition at line 314 of file ARMWinEH.h.
Referenced by CodeWords(), E(), EpilogueCount(), EpilogueScopes(), ExceptionHandlerParameter(), ExceptionHandlerRVA(), F(), FunctionLength(), llvm::ARM::WinEH::HeaderWords(), UnwindByteCode(), Vers(), and X().
The documentation for this struct was generated from the following file:
ARMWinEH.h