LLVM: llvm::support::endian::Writer< endian > Struct Template Reference
LLVM API Documentation
llvm::support::endian::Writer< endian > Struct Template Reference
Adapter to write values to a stream in a particular byte order.
#include <EndianStream.h>
Public Member Functions
Writer (raw_ostream &OS)
template<typename value_type >
void write (value_type Val)
Public Attributes
raw_ostream & OS
Detailed Description
template<endianness endian>
struct llvm::support::endian::Writer< endian >
Adapter to write values to a stream in a particular byte order.
Definition at line 26 of file EndianStream.h.
Constructor & Destructor Documentation
template<endianness endian> llvm::support::endian::Writer< endian >::Writer (raw_ostream & OS) inline
Definition at line 28 of file EndianStream.h.
Member Function Documentation
template<endianness endian> template<typename value_type > void llvm::support::endian::Writer< endian >::write (value_type Val) inline
Definition at line 29 of file EndianStream.h.
References llvm::support::endian::Writer< endian >::OS, and llvm::raw_ostream::write().
Referenced by llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), and llvm::InstrProfWriter::write().
Member Data Documentation
template<endianness endian> raw_ostream& llvm::support::endian::Writer< endian >::OS
Definition at line 27 of file EndianStream.h.
Referenced by llvm::support::endian::Writer< endian >::write().
The documentation for this struct was generated from the following file:
EndianStream.h