LLVM: SystemZFrameLowering.cpp File Reference
LLVM API Documentation
SystemZFrameLowering.cpp File Reference
#include "SystemZFrameLowering.h"
#include "SystemZCallingConv.h"
#include "SystemZInstrBuilder.h"
#include "SystemZInstrInfo.h"
#include "SystemZMachineFunctionInfo.h"
#include "SystemZRegisterInfo.h"
#include "SystemZSubtarget.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
Functions
static void addSavedGPR (MachineBasicBlock &MBB, MachineInstrBuilder &MIB, unsigned GPR64, bool IsImplicit)
static void emitIncrement (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, const DebugLoc &DL, unsigned Reg, int64_t NumBytes, const TargetInstrInfo *TII)
Function Documentation
static void addSavedGPR (MachineBasicBlock & MBB, MachineInstrBuilder & MIB, unsigned GPR64, bool IsImplicit) static
Definition at line 110 of file SystemZFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::getImplRegState(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MCRegisterInfo::getSubReg(), llvm::MachineFunction::getSubtarget(), and llvm::MachineBasicBlock::isLiveIn().
Referenced by llvm::SystemZFrameLowering::spillCalleeSavedRegisters().
static void emitIncrement (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, const DebugLoc & DL, unsigned Reg, int64_t NumBytes, const TargetInstrInfo * TII) static
Definition at line 284 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getOperand(), llvm::isInt< 16 >(), llvm::AArch64CC::MI, and llvm::MachineOperand::setIsDead().
Referenced by llvm::SystemZFrameLowering::emitEpilogue(), and llvm::SystemZFrameLowering::emitPrologue().