LLVM: TargetLoweringObjectFile.cpp File Reference
LLVM API Documentation
TargetLoweringObjectFile.cpp File Reference
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Functions
static bool isSuitableForBSS (const GlobalVariable *GV, bool NoZerosInBSS)
static bool IsNullTerminatedString (const Constant *C)
Function Documentation
static bool IsNullTerminatedString (const Constant * C) static
IsNullTerminatedString - Return true if the specified constant (which is known to have a type that is an array of 1/2/4 byte elements) ends with a nul value and contains no other nuls in it. Note that this is more general than ConstantDataSequential::isString because we allow 2 & 4 byte strings.
Definition at line 81 of file TargetLoweringObjectFile.cpp.
References assert(), and llvm::Value::getType().
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
static bool isSuitableForBSS (const GlobalVariable * GV, bool NoZerosInBSS) static
Definition at line 54 of file TargetLoweringObjectFile.cpp.
References llvm::CallingConv::C, llvm::GlobalVariable::getInitializer(), llvm::GlobalObject::hasSection(), llvm::GlobalVariable::isConstant(), and llvm::Constant::isNullValue().
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().