LLVM: TargetInstrInfo.cpp File Reference
LLVM API Documentation
TargetInstrInfo.cpp File Reference
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/ScoreboardHazardRecognizer.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInstrItineraries.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include <cctype>
Functions
static const TargetRegisterClass * canFoldCopy (const MachineInstr *MI, unsigned FoldIdx)
static MachineInstr * foldPatchpoint (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, int FrameIndex, const TargetInstrInfo &TII)
Variables
static cl::opt< bool > DisableHazardRecognizer ("disable-sched-hazard", cl::Hidden, cl::init(false), cl::desc("Disable hazard detection during preRA scheduling"))
Function Documentation
static const TargetRegisterClass* canFoldCopy (const MachineInstr * MI, unsigned FoldIdx) static
Definition at line 344 of file TargetInstrInfo.cpp.
References assert(), llvm::TargetRegisterClass::contains(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::getSubReg(), llvm::TargetRegisterClass::hasSubClassEq(), llvm::MachineInstr::isCopy(), llvm::TargetRegisterInfo::isPhysicalRegister(), and llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by llvm::TargetInstrInfo::canFoldMemoryOperand(), and llvm::TargetInstrInfo::foldMemoryOperand().
static MachineInstr* foldPatchpoint (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, int FrameIndex, const TargetInstrInfo & TII) static
Definition at line 386 of file TargetInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineFunction::CreateMachineInstr(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getTarget(), llvm::PatchPointOpers::getVarIdx(), I, llvm::StackMaps::IndirectMemRefOp, llvm_unreachable, llvm::TargetOpcode::PATCHPOINT, llvm::report_fatal_error(), and llvm::TargetOpcode::STACKMAP.
Referenced by llvm::TargetInstrInfo::foldMemoryOperand().
Variable Documentation
cl::opt<bool> DisableHazardRecognizer("disable-sched-hazard", cl::Hidden, cl::init(false), cl::desc("Disable hazard detection during preRA scheduling")) static
Referenced by llvm::TargetInstrInfo::usePreRAHazardRecognizer().