LLVM: Thumb1RegisterInfo.cpp File Reference
LLVM API Documentation
Thumb1RegisterInfo.cpp File Reference
#include "Thumb1RegisterInfo.h"
#include "ARMBaseInstrInfo.h"
#include "ARMMachineFunctionInfo.h"
#include "ARMSubtarget.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetMachine.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
static void emitThumbRegPlusImmInReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, DebugLoc dl, unsigned DestReg, unsigned BaseReg, int NumBytes, bool CanChangeCC, const TargetInstrInfo &TII, const ARMBaseRegisterInfo &MRI, unsigned MIFlags=MachineInstr::NoFlags)
static void removeOperands (MachineInstr &MI, unsigned i)
static unsigned convertToNonSPOpcode (unsigned Opcode)
Variables
cl::opt< bool > llvm::ReuseFrameIndexVals
Function Documentation
static unsigned convertToNonSPOpcode (unsigned Opcode) static
convertToNonSPOpcode - Change the opcode to the non-SP version, because we're replacing the frame index with a non-SP register.
Definition at line 308 of file Thumb1RegisterInfo.cpp.
Referenced by llvm::Thumb1RegisterInfo::rewriteFrameIndex().
static void emitThumbRegPlusImmInReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, DebugLoc dl, unsigned DestReg, unsigned BaseReg, int NumBytes, bool CanChangeCC, const TargetInstrInfo & TII, const ARMBaseRegisterInfo & MRI, unsigned MIFlags = MachineInstr::NoFlags) static
emitThumbRegPlusImmInReg - Emits a series of instructions to materialize a destreg = basereg + immediate in Thumb code. Materialize the immediate in a register using mov / mvn sequences or load the immediate from a constpool entry.
Definition at line 92 of file Thumb1RegisterInfo.cpp.
References llvm::AddDefaultPred(), llvm::AddDefaultT1CC(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::ARMCC::AL, assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::isARMLowRegister(), llvm::RegState::Kill, and llvm::MachineInstrBuilder::setMIFlags().
Referenced by llvm::Thumb1RegisterInfo::eliminateFrameIndex(), and llvm::emitThumbRegPlusImmediate().
static void removeOperands (MachineInstr & MI, unsigned i) static
Definition at line 300 of file Thumb1RegisterInfo.cpp.
References llvm::MachineInstr::getNumOperands(), and llvm::MachineInstr::RemoveOperand().
Referenced by llvm::Thumb1RegisterInfo::eliminateFrameIndex().