LLVM: Thumb1FrameLowering.cpp File Reference
LLVM API Documentation
Thumb1FrameLowering.cpp File Reference
#include "Thumb1FrameLowering.h"
#include "ARMMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
Functions
static void emitSPUpdate (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, const TargetInstrInfo &TII, DebugLoc dl, const Thumb1RegisterInfo &MRI, int NumBytes, unsigned MIFlags=MachineInstr::NoFlags)
static bool isCSRestore (MachineInstr *MI, const MCPhysReg *CSRegs)
Function Documentation
static void emitSPUpdate (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, const TargetInstrInfo & TII, DebugLoc dl, const Thumb1RegisterInfo & MRI, int NumBytes, unsigned MIFlags = MachineInstr::NoFlags) static
Definition at line 41 of file Thumb1FrameLowering.cpp.
References llvm::emitThumbRegPlusImmediate().
Referenced by llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::emitEpilogue(), and llvm::Thumb1FrameLowering::emitPrologue().
static bool isCSRestore (MachineInstr * MI, const MCPhysReg * CSRegs) static
Definition at line 309 of file Thumb1FrameLowering.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::isCalleeSavedRegister(), and llvm::MachineOperand::isFI().
Referenced by llvm::Thumb1FrameLowering::emitEpilogue().