LLVM: Triple.cpp File Reference
LLVM API Documentation
Triple.cpp File Reference
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/ErrorHandling.h"
#include <cstring>
Functions
static Triple::ArchType parseARMArch (StringRef ArchName)
static Triple::ArchType parseArch (StringRef ArchName)
static Triple::VendorType parseVendor (StringRef VendorName)
static Triple::OSType parseOS (StringRef OSName)
static Triple::EnvironmentType parseEnvironment (StringRef EnvironmentName)
static Triple::ObjectFormatType parseFormat (StringRef EnvironmentName)
static Triple::SubArchType parseSubArch (StringRef SubArchName)
static const char * getObjectFormatTypeName (Triple::ObjectFormatType Kind)
static Triple::ObjectFormatType getDefaultFormat (const Triple &T)
static unsigned EatNumber (StringRef &Str)
static unsigned getArchPointerBitWidth (llvm::Triple::ArchType Arch)
Function Documentation
static unsigned EatNumber (StringRef & Str) static
Definition at line 690 of file Triple.cpp.
References assert(), llvm::StringRef::empty(), and llvm::StringRef::substr().
Referenced by llvm::Triple::getOSVersion().
static unsigned getArchPointerBitWidth (llvm::Triple::ArchType Arch) static
Definition at line 854 of file Triple.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::Triple::amdgcn, llvm::Triple::amdil, llvm::Triple::amdil64, llvm::Triple::arm, llvm::Triple::armeb, llvm::Triple::hexagon, llvm::Triple::hsail, llvm::Triple::hsail64, llvm::Triple::kalimba, llvm::Triple::le32, llvm::Triple::le64, llvm_unreachable, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::msp430, llvm::Triple::nvptx, llvm::Triple::nvptx64, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::r600, llvm::Triple::sparc, llvm::Triple::sparcv9, llvm::Triple::spir, llvm::Triple::spir64, llvm::Triple::systemz, llvm::Triple::tce, llvm::Triple::thumb, llvm::Triple::thumbeb, llvm::Triple::UnknownArch, llvm::Triple::x86, llvm::Triple::x86_64, and llvm::Triple::xcore.
Referenced by llvm::Triple::isArch16Bit(), llvm::Triple::isArch32Bit(), and llvm::Triple::isArch64Bit().
static Triple::ObjectFormatType getDefaultFormat (const Triple & T) static
Definition at line 430 of file Triple.cpp.
References llvm::Triple::COFF, llvm::Triple::ELF, llvm::Triple::isOSDarwin(), llvm::Triple::isOSWindows(), and llvm::Triple::MachO.
Referenced by llvm::Triple::Triple().
static const char* getObjectFormatTypeName (Triple::ObjectFormatType Kind) static
Definition at line 420 of file Triple.cpp.
References llvm::Triple::COFF, llvm::Triple::ELF, llvm_unreachable, llvm::Triple::MachO, and llvm::Triple::UnknownObjectFormat.
Referenced by llvm::Triple::normalize(), and llvm::Triple::setObjectFormat().
static Triple::ArchType parseArch (StringRef ArchName) static
Definition at line 281 of file Triple.cpp.
References llvm::Triple::amdgcn, llvm::Triple::amdil, llvm::Triple::amdil64, llvm::Triple::arm, llvm::Triple::armeb, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Cases(), llvm::StringSwitch< T, R >::Default(), llvm::Triple::hexagon, llvm::Triple::hsail, llvm::Triple::hsail64, llvm::Triple::kalimba, llvm::Triple::le32, llvm::Triple::le64, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::msp430, llvm::Triple::nvptx, llvm::Triple::nvptx64, parseARMArch(), llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::r600, llvm::Triple::sparc, llvm::Triple::sparcv9, llvm::Triple::spir, llvm::Triple::spir64, llvm::StringSwitch< T, R >::StartsWith(), llvm::Triple::systemz, llvm::Triple::tce, llvm::Triple::UnknownArch, llvm::Triple::x86, llvm::Triple::x86_64, and llvm::Triple::xcore.
Referenced by llvm::Triple::normalize().
static Triple::ArchType parseARMArch (StringRef ArchName) static
Definition at line 229 of file Triple.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::Triple::arm, llvm::Triple::armeb, llvm::StringSwitch< T, R >::Cases(), llvm::StringSwitch< T, R >::Default(), llvm::StringRef::endswith(), llvm::StringRef::equals(), isThumb(), llvm::StringRef::npos, llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::StringRef::substr(), llvm::Triple::thumb, llvm::Triple::thumbeb, and llvm::Triple::UnknownArch.
Referenced by parseArch().
static Triple::EnvironmentType parseEnvironment (StringRef EnvironmentName) static
Definition at line 368 of file Triple.cpp.
References llvm::Triple::Android, llvm::Triple::CODE16, llvm::Triple::Cygnus, llvm::StringSwitch< T, R >::Default(), llvm::Triple::EABI, llvm::Triple::EABIHF, llvm::Triple::GNU, llvm::Triple::GNUEABI, llvm::Triple::GNUEABIHF, llvm::Triple::GNUX32, llvm::Triple::Itanium, llvm::Triple::MSVC, llvm::StringSwitch< T, R >::StartsWith(), and llvm::Triple::UnknownEnvironment.
Referenced by llvm::Triple::normalize().
static Triple::ObjectFormatType parseFormat (StringRef EnvironmentName) static
Definition at line 384 of file Triple.cpp.
References llvm::Triple::COFF, llvm::StringSwitch< T, R >::Default(), llvm::Triple::ELF, llvm::StringSwitch< T, R >::EndsWith(), llvm::Triple::MachO, and llvm::Triple::UnknownObjectFormat.
Referenced by llvm::Triple::normalize().
static Triple::OSType parseOS (StringRef OSName) static
Definition at line 340 of file Triple.cpp.
References llvm::Triple::AIX, llvm::Triple::AMDHSA, llvm::Triple::Bitrig, llvm::Triple::CNK, llvm::Triple::CUDA, llvm::Triple::Darwin, llvm::StringSwitch< T, R >::Default(), llvm::Triple::DragonFly, llvm::Triple::FreeBSD, llvm::Triple::Haiku, llvm::Triple::IOS, llvm::Triple::KFreeBSD, llvm::Triple::Linux, llvm::Triple::Lv2, llvm::Triple::MacOSX, llvm::Triple::Minix, llvm::Triple::NaCl, llvm::Triple::NetBSD, llvm::Triple::NVCL, llvm::Triple::OpenBSD, llvm::Triple::RTEMS, llvm::Triple::Solaris, llvm::StringSwitch< T, R >::StartsWith(), llvm::Triple::UnknownOS, and llvm::Triple::Win32.
Referenced by llvm::Triple::normalize().
static Triple::SubArchType parseSubArch (StringRef SubArchName) static
Definition at line 392 of file Triple.cpp.
References llvm::Triple::ARMSubArch_v4t, llvm::Triple::ARMSubArch_v5, llvm::Triple::ARMSubArch_v5te, llvm::Triple::ARMSubArch_v6, llvm::Triple::ARMSubArch_v6m, llvm::Triple::ARMSubArch_v6t2, llvm::Triple::ARMSubArch_v7, llvm::Triple::ARMSubArch_v7em, llvm::Triple::ARMSubArch_v7m, llvm::Triple::ARMSubArch_v7s, llvm::Triple::ARMSubArch_v8, llvm::StringSwitch< T, R >::Default(), llvm::StringSwitch< T, R >::EndsWith(), llvm::StringRef::endswith(), llvm::Triple::KalimbaSubArch_v3, llvm::Triple::KalimbaSubArch_v4, llvm::Triple::KalimbaSubArch_v5, llvm::Triple::NoSubArch, llvm::StringRef::size(), and llvm::StringRef::substr().
static Triple::VendorType parseVendor (StringRef VendorName) static
Definition at line 324 of file Triple.cpp.
References llvm::Triple::Apple, llvm::Triple::BGP, llvm::Triple::BGQ, llvm::StringSwitch< T, R >::Case(), llvm::Triple::CSR, llvm::StringSwitch< T, R >::Default(), llvm::Triple::Freescale, llvm::Triple::IBM, llvm::Triple::ImaginationTechnologies, llvm::Triple::MipsTechnologies, llvm::Triple::NVIDIA, llvm::Triple::PC, llvm::Triple::SCEI, and llvm::Triple::UnknownVendor.
Referenced by llvm::Triple::normalize().