LLVM: X86ISelLowering.cpp File Reference
LLVM API Documentation
X86ISelLowering.cpp File Reference
#include "X86ISelLowering.h"
#include "Utils/X86ShuffleDecode.h"
#include "X86CallingConv.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86TargetMachine.h"
#include "X86TargetObjectFile.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/VariadicFunction.h"
#include "llvm/CodeGen/IntrinsicLowering.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetOptions.h"
#include "X86IntrinsicsInfo.h"
#include <bitset>
#include <numeric>
#include <cctype>
#include "X86GenCallingConv.inc"
Macros
#define DEBUG_TYPE "x86-isel"
Enumerations
enum StructReturnType { NotStructReturn, RegStructReturn, StackStructReturn }
Functions
STATISTIC (NumTailCalls,"Number of tail calls")
static SDValue getMOVL (SelectionDAG &DAG, SDLoc dl, EVT VT, SDValue V1, SDValue V2)
static SDValue ExtractSubVector (SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, SDLoc dl, unsigned vectorWidth)
static SDValue Extract128BitVector (SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, SDLoc dl)
static SDValue Extract256BitVector (SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, SDLoc dl)
Generate a DAG to grab 256-bits from a 512-bit vector.
static SDValue InsertSubVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, SDLoc dl, unsigned vectorWidth)
static SDValue Insert128BitVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, SDLoc dl)
static SDValue Insert256BitVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, SDLoc dl)
static SDValue Concat128BitVectors (SDValue V1, SDValue V2, EVT VT, unsigned NumElems, SelectionDAG &DAG, SDLoc dl)
static SDValue Concat256BitVectors (SDValue V1, SDValue V2, EVT VT, unsigned NumElems, SelectionDAG &DAG, SDLoc dl)
static void getMaxByValAlign (Type *Ty, unsigned &MaxAlign)
static StructReturnType callIsStructReturn (const SmallVectorImpl< ISD::OutputArg > &Outs)
static StructReturnType argsAreStructReturn (const SmallVectorImpl< ISD::InputArg > &Ins)
Determines whether a function uses struct return semantics.
static SDValue CreateCopyOfByValArgument (SDValue Src, SDValue Dst, SDValue Chain, ISD::ArgFlagsTy Flags, SelectionDAG &DAG, SDLoc dl)
static bool IsTailCallConvention (CallingConv::ID CC)
static bool IsCCallConvention (CallingConv::ID CC)
Return true if the calling convention is a C calling convention.
static bool FuncIsMadeTailCallSafe (CallingConv::ID CC, bool GuaranteedTailCallOpt)
static ArrayRef< MCPhysReg > get64BitArgumentGPRs (CallingConv::ID CallConv, const X86Subtarget *Subtarget)
static ArrayRef< MCPhysReg > get64BitArgumentXMMs (MachineFunction &MF, CallingConv::ID CallConv, const X86Subtarget *Subtarget)
static SDValue EmitTailCallStoreRetAddr (SelectionDAG &DAG, MachineFunction &MF, SDValue Chain, SDValue RetAddrFrIdx, EVT PtrVT, unsigned SlotSize, int FPDiff, SDLoc dl)
static bool MatchingStackOffset (SDValue Arg, unsigned Offset, ISD::ArgFlagsTy Flags, MachineFrameInfo *MFI, const MachineRegisterInfo *MRI, const X86InstrInfo *TII)
static bool MayFoldLoad (SDValue Op)
static bool MayFoldIntoStore (SDValue Op)
static bool isTargetShuffle (unsigned Opcode)
static SDValue getTargetShuffleNode (unsigned Opc, SDLoc dl, EVT VT, SDValue V1, SelectionDAG &DAG)
static SDValue getTargetShuffleNode (unsigned Opc, SDLoc dl, EVT VT, SDValue V1, unsigned TargetMask, SelectionDAG &DAG)
static SDValue getTargetShuffleNode (unsigned Opc, SDLoc dl, EVT VT, SDValue V1, SDValue V2, unsigned TargetMask, SelectionDAG &DAG)
static SDValue getTargetShuffleNode (unsigned Opc, SDLoc dl, EVT VT, SDValue V1, SDValue V2, SelectionDAG &DAG)
static bool isX86CCUnsigned (unsigned X86CC)
Return true if the condition is an unsigned comparison operation.
static unsigned TranslateX86CC (ISD::CondCode SetCCOpcode, bool isFP, SDValue &LHS, SDValue &RHS, SelectionDAG &DAG)
static bool hasFPCMov (unsigned X86CC)
static bool isUndefOrInRange (int Val, int Low, int Hi)
static bool isUndefOrEqual (int Val, int CmpVal)
static bool isSequentialOrUndefInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size, int Low)
static bool isPSHUFDMask (ArrayRef< int > Mask, MVT VT, bool TestSecondOperand=false)
static bool isPSHUFHWMask (ArrayRef< int > Mask, MVT VT, bool HasInt256)
static bool isPSHUFLWMask (ArrayRef< int > Mask, MVT VT, bool HasInt256)
static bool isAlignrMask (ArrayRef< int > Mask, MVT VT, bool InterLane)
Return true if the mask specifies a shuffle of elements that is suitable for input to intralane (palignr) or interlane (valign) vector right-shift.
static bool isPALIGNRMask (ArrayRef< int > Mask, MVT VT, const X86Subtarget *Subtarget)
Return true if the node specifies a shuffle of elements that is suitable for input to PALIGNR.
static bool isVALIGNMask (ArrayRef< int > Mask, MVT VT, const X86Subtarget *Subtarget)
Return true if the node specifies a shuffle of elements that is suitable for input to VALIGN.
static void CommuteVectorShuffleMask (SmallVectorImpl< int > &Mask, unsigned NumElems)
static bool isSHUFPMask (ArrayRef< int > Mask, MVT VT, bool Commuted=false)
static bool isMOVHLPSMask (ArrayRef< int > Mask, MVT VT)
static bool isMOVHLPS_v_undef_Mask (ArrayRef< int > Mask, MVT VT)
static bool isMOVLPMask (ArrayRef< int > Mask, MVT VT)
static bool isMOVLHPSMask (ArrayRef< int > Mask, MVT VT)
static bool isINSERTPSMask (ArrayRef< int > Mask, MVT VT)
static SDValue Compact8x32ShuffleNode (ShuffleVectorSDNode *SVOp, SelectionDAG &DAG)
static bool isUNPCKLMask (ArrayRef< int > Mask, MVT VT, bool HasInt256, bool V2IsSplat=false)
static bool isUNPCKHMask (ArrayRef< int > Mask, MVT VT, bool HasInt256, bool V2IsSplat=false)
static bool isUNPCKL_v_undef_Mask (ArrayRef< int > Mask, MVT VT, bool HasInt256)
static bool isUNPCKH_v_undef_Mask (ArrayRef< int > Mask, MVT VT, bool HasInt256)
static bool isINSERT64x4Mask (ArrayRef< int > Mask, MVT VT, unsigned int *Imm)
static bool isMOVLMask (ArrayRef< int > Mask, EVT VT)
static bool isVPERM2X128Mask (ArrayRef< int > Mask, MVT VT, bool HasFp256)
static unsigned getShuffleVPERM2X128Immediate (ShuffleVectorSDNode *SVOp)
static bool isPermImmMask (ArrayRef< int > Mask, MVT VT, unsigned &Imm8)
static bool isVPERMILPMask (ArrayRef< int > Mask, MVT VT)
static bool isCommutedMOVLMask (ArrayRef< int > Mask, MVT VT, bool V2IsSplat=false, bool V2IsUndef=false)
static bool isMOVSHDUPMask (ArrayRef< int > Mask, MVT VT, const X86Subtarget *Subtarget)
static bool isMOVSLDUPMask (ArrayRef< int > Mask, MVT VT, const X86Subtarget *Subtarget)
static bool isMOVDDUPYMask (ArrayRef< int > Mask, MVT VT, bool HasFp256)
static bool isMOVDDUPMask (ArrayRef< int > Mask, MVT VT)
static bool isVEXTRACTIndex (SDNode *N, unsigned vecWidth)
static bool isVINSERTIndex (SDNode *N, unsigned vecWidth)
static unsigned getShuffleSHUFImmediate (ShuffleVectorSDNode *N)
static unsigned getShufflePSHUFHWImmediate (ShuffleVectorSDNode *N)
static unsigned getShufflePSHUFLWImmediate (ShuffleVectorSDNode *N)
static unsigned getShuffleAlignrImmediate (ShuffleVectorSDNode *SVOp, bool InterLane)
Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with the PALIGNR (if InterLane is false) or with VALIGN (if Interlane is true) instructions.
static unsigned getShufflePALIGNRImmediate (ShuffleVectorSDNode *SVOp)
Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with the PALIGNR instruction.
static unsigned getShuffleVALIGNImmediate (ShuffleVectorSDNode *SVOp)
Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with the VALIGN instruction.
static unsigned getExtractVEXTRACTImmediate (SDNode *N, unsigned vecWidth)
static unsigned getInsertVINSERTImmediate (SDNode *N, unsigned vecWidth)
static bool isZero (SDValue V)
isZero - Returns true if Elt is a constant integer zero
static bool ShouldXformToMOVHLPS (ArrayRef< int > Mask, MVT VT)
static bool isScalarLoadToVector (SDNode *N, LoadSDNode **LD=nullptr)
static bool WillBeConstantPoolLoad (SDNode *N)
static bool ShouldXformToMOVLP (SDNode *V1, SDNode *V2, ArrayRef< int > Mask, MVT VT)
static bool isZeroShuffle (ShuffleVectorSDNode *N)
static SDValue getZeroVector (EVT VT, const X86Subtarget *Subtarget, SelectionDAG &DAG, SDLoc dl)
static SDValue getOnesVector (MVT VT, bool HasInt256, SelectionDAG &DAG, SDLoc dl)
static void NormalizeMask (SmallVectorImpl< int > &Mask, unsigned NumElems)
static SDValue getUnpackl (SelectionDAG &DAG, SDLoc dl, MVT VT, SDValue V1, SDValue V2)
getUnpackl - Returns a vector_shuffle node for an unpackl operation.
static SDValue getUnpackh (SelectionDAG &DAG, SDLoc dl, MVT VT, SDValue V1, SDValue V2)
getUnpackh - Returns a vector_shuffle node for an unpackh operation.
static SDValue PromoteSplati8i16 (SDValue V, SelectionDAG &DAG, int &EltNo)
static SDValue getLegalSplat (SelectionDAG &DAG, SDValue V, int EltNo)
getLegalSplat - Generate a legal splat with supported x86 shuffles
static SDValue PromoteSplat (ShuffleVectorSDNode *SV, SelectionDAG &DAG)
PromoteSplat - Splat is promoted to target supported vector shuffles.
static SDValue getShuffleVectorZeroOrUndef (SDValue V2, unsigned Idx, bool IsZero, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static bool getTargetShuffleMask (SDNode *N, MVT VT, SmallVectorImpl< int > &Mask, bool &IsUnary)
static SDValue getShuffleScalarElt (SDNode *N, unsigned Index, SelectionDAG &DAG, unsigned Depth)
static unsigned getNumOfConsecutiveZeros (ShuffleVectorSDNode *SVOp, unsigned NumElems, bool ZerosFromLeft, SelectionDAG &DAG, unsigned PreferredNum=-1U)
static bool isShuffleMaskConsecutive (ShuffleVectorSDNode *SVOp, unsigned MaskI, unsigned MaskE, unsigned OpIdx, unsigned NumElems, unsigned &OpNum)
static bool isVectorShiftRight (ShuffleVectorSDNode *SVOp, SelectionDAG &DAG, bool &isLeft, SDValue &ShVal, unsigned &ShAmt)
static bool isVectorShiftLeft (ShuffleVectorSDNode *SVOp, SelectionDAG &DAG, bool &isLeft, SDValue &ShVal, unsigned &ShAmt)
static bool isVectorShift (ShuffleVectorSDNode *SVOp, SelectionDAG &DAG, bool &isLeft, SDValue &ShVal, unsigned &ShAmt)
static SDValue LowerBuildVectorv16i8 (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG &DAG, const X86Subtarget *Subtarget, const TargetLowering &TLI)
static SDValue LowerBuildVectorv8i16 (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG &DAG, const X86Subtarget *Subtarget, const TargetLowering &TLI)
static SDValue LowerBuildVectorv4x32 (SDValue Op, SelectionDAG &DAG, const X86Subtarget *Subtarget, const TargetLowering &TLI)
LowerBuildVectorv4x32 - Custom lower build_vector of v4i32 or v4f32.
static SDValue getVShift (bool isLeft, EVT VT, SDValue SrcOp, unsigned NumBits, SelectionDAG &DAG, const TargetLowering &TLI, SDLoc dl)
static SDValue LowerAsSplatVectorLoad (SDValue SrcOp, MVT VT, SDLoc dl, SelectionDAG &DAG)
static SDValue EltsFromConsecutiveLoads (EVT VT, SmallVectorImpl< SDValue > &Elts, SDLoc &DL, SelectionDAG &DAG, bool isAfterLegalize)
static SDValue LowerVectorBroadcast (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static int getUnderlyingExtractedFromVec (SDValue &ExtractedFromVec, SDValue ExtIdx)
For an EXTRACT_VECTOR_ELT with a constant index return the real underlying vector and index.
static SDValue buildFromShuffleMostly (SDValue Op, SelectionDAG &DAG)
static bool isHorizontalBinOp (const BuildVectorSDNode *N, unsigned Opcode, SelectionDAG &DAG, unsigned BaseIdx, unsigned LastIdx, SDValue &V0, SDValue &V1)
Return true if N implements a horizontal binop and return the operands for the horizontal binop into V0 and V1.
static SDValue ExpandHorizontalBinOp (const SDValue &V0, const SDValue &V1, SDLoc DL, SelectionDAG &DAG, unsigned X86Opcode, bool Mode, bool isUndefLO, bool isUndefHI)
Emit a sequence of two 128-bit horizontal add/sub followed by a concat_vector.
static SDValue matchAddSub (const BuildVectorSDNode *BV, SelectionDAG &DAG, const X86Subtarget *Subtarget)
Try to fold a build_vector that performs an 'addsub' into the sequence of 'vadd + vsub + blendi'.
static SDValue PerformBUILD_VECTORCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue LowerAVXCONCAT_VECTORS (SDValue Op, SelectionDAG &DAG)
static SDValue LowerCONCAT_VECTORS (SDValue Op, SelectionDAG &DAG)
static bool isNoopShuffleMask (ArrayRef< int > Mask)
Tiny helper function to identify a no-op mask.
static bool isSingleInputShuffleMask (ArrayRef< int > Mask)
Helper function to classify a mask as a single-input mask.
static bool is128BitLaneCrossingShuffleMask (MVT VT, ArrayRef< int > Mask)
Test whether there are elements crossing 128-bit lanes in this shuffle mask.
static bool is128BitLaneRepeatedShuffleMask (MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > &RepeatedMask)
Test whether a shuffle mask is equivalent within each 128-bit lane.
static SDValue getV4X86ShuffleImm8ForMask (ArrayRef< int > Mask, SelectionDAG &DAG)
Get a 4-lane 8-bit shuffle immediate for a mask.
static SDValue lowerVectorShuffleAsBlend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Try to emit a blend instruction for a shuffle.
static SDValue lowerVectorShuffleAsDecomposedShuffleBlend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
Generic routine to lower a shuffle and blend as a decomposed set of unblended shuffles followed by an unshuffled blend.
static SDValue lowerVectorShuffleAsByteRotate (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Try to lower a vector shuffle as a byte rotation.
static SmallBitVector computeZeroableShuffleElements (ArrayRef< int > Mask, SDValue V1, SDValue V2)
Compute whether each element of a shuffle is zeroable.
static SDValue lowerVectorShuffleAsByteShift (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
Try to lower a vector shuffle as a byte shift (shifts in zeros).
static SDValue lowerVectorShuffleAsSpecificZeroOrAnyExtend (SDLoc DL, MVT VT, int NumElements, int Scale, bool AnyExt, SDValue InputV, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Lower a vector shuffle as a zero or any extension.
static SDValue lowerVectorShuffleAsZeroOrAnyExtend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Try to lower a vector shuffle as a zero extension on any micrarch.
static SDValue getScalarValueForVectorElement (SDValue V, int Idx, SelectionDAG &DAG)
Try to get a scalar value for a specific element of a vector.
static bool isShuffleFoldableLoad (SDValue V)
Helper to test for a load that can be folded with x86 shuffles.
static SDValue lowerVectorShuffleAsElementInsertion (MVT VT, SDLoc DL, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Try to lower insertion of a single element into a zero vector.
static SDValue lowerVectorShuffleAsBroadcast (MVT VT, SDLoc DL, SDValue V, ArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Try to lower broadcast of a single element.
static SDValue lowerVectorShuffleAsInsertPS (SDValue Op, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
static SDValue lowerV2F64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 2-lane 64-bit floating point shuffles.
static SDValue lowerV2I64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 2-lane 64-bit integer shuffles.
static SDValue lowerVectorShuffleWithSHUFPS (SDLoc DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG &DAG)
Lower a vector shuffle using the SHUFPS instruction.
static SDValue lowerV4F32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Lower 4-lane 32-bit floating point shuffles.
static SDValue lowerV4I32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Lower 4-lane i32 vector shuffles.
static SDValue lowerV8I16SingleInputVectorShuffle (SDLoc DL, SDValue V, MutableArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Lowering of single-input v8i16 shuffles is the cornerstone of SSE2 shuffle lowering, and the most complex part.
static bool shouldLowerAsInterleaving (ArrayRef< int > Mask)
Detect whether the mask pattern should be lowered through interleaving.
static SDValue lowerV8I16BasicBlendVectorShuffle (SDLoc DL, SDValue V1, SDValue V2, MutableArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Blend two v8i16 vectors using a naive unpack strategy.
static SDValue lowerV8I16VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Generic lowering of 8-lane i16 shuffles.
static int canLowerByDroppingEvenElements (ArrayRef< int > Mask)
Check whether a compaction lowering can be done by dropping even elements and compute how many times even elements must be dropped.
static SDValue lowerV16I8VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Generic lowering of v16i8 shuffles.
static SDValue lower128BitVectorShuffle (SDValue Op, SDValue V1, SDValue V2, MVT VT, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Dispatching routine to lower various 128-bit x86 vector shuffles.
static bool canWidenShuffleElements (ArrayRef< int > Mask, SmallVectorImpl< int > &WidenedMask)
Helper function to test whether a shuffle mask could be simplified by widening the elements being shuffled.
static SDValue splitAndLowerVectorShuffle (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
Generic routine to split ector shuffle into half-sized shuffles.
static SDValue lowerVectorShuffleAsSplitOrBlend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
Either split a vector in halves or decompose the shuffles and the blend.
static SDValue lowerVectorShuffleAsLanePermuteAndBlend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
Lower a vector shuffle crossing multiple 128-bit lanes as a permutation and blend of those lanes.
static SDValue lowerV2X128VectorShuffle (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering 2-lane 128-bit shuffles.
static SDValue lowerVectorShuffleByMerging128BitLanes (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Lower a vector shuffle by first fixing the 128-bit lanes and then shuffling each lane.
static bool isShuffleMaskInputInPlace (int Input, ArrayRef< int > Mask)
Test whether the specified input (0 or 1) is in-place blended by the given mask.
static SDValue lowerV4F64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 4-lane 64-bit floating point shuffles.
static SDValue lowerV4I64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 4-lane 64-bit integer shuffles.
static SDValue lowerV8F32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 8-lane 32-bit floating point shuffles.
static SDValue lowerV8I32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 8-lane 32-bit integer shuffles.
static SDValue lowerV16I16VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 16-lane 16-bit integer shuffles.
static SDValue lowerV32I8VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 32-lane 8-bit integer shuffles.
static SDValue lower256BitVectorShuffle (SDValue Op, SDValue V1, SDValue V2, MVT VT, const X86Subtarget *Subtarget, SelectionDAG &DAG)
High-level routine to lower various 256-bit x86 vector shuffles.
static SDValue lowerV8F64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 8-lane 64-bit floating point shuffles.
static SDValue lowerV16F32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 16-lane 32-bit floating point shuffles.
static SDValue lowerV8I64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 8-lane 64-bit integer shuffles.
static SDValue lowerV16I32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 16-lane 32-bit integer shuffles.
static SDValue lowerV32I16VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 32-lane 16-bit integer shuffles.
static SDValue lowerV64I8VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Handle lowering of 64-lane 8-bit integer shuffles.
static SDValue lower512BitVectorShuffle (SDValue Op, SDValue V1, SDValue V2, MVT VT, const X86Subtarget *Subtarget, SelectionDAG &DAG)
High-level routine to lower various 512-bit x86 vector shuffles.
static SDValue lowerVectorShuffle (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Top-level lowering for x86 vector shuffles.
static bool isBlendMask (ArrayRef< int > MaskVals, MVT VT, bool hasSSE41, bool hasInt256, unsigned *MaskOut=nullptr)
static SDValue LowerVECTOR_SHUFFLEtoBlend (ShuffleVectorSDNode *SVOp, unsigned MaskValue, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static bool ShuffleCrosses128bitLane (MVT VT, unsigned InputIdx, unsigned OutputIdx)
static SDValue getPSHUFB (ArrayRef< int > MaskVals, SDValue V1, SDLoc &dl, SelectionDAG &DAG)
static SDValue LowerVECTOR_SHUFFLEv8i16 (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerVECTOR_SHUFFLEv16i16 (SDValue Op, SelectionDAG &DAG)
v16i16 shuffles
static SDValue LowerVECTOR_SHUFFLEv16i8 (ShuffleVectorSDNode *SVOp, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerVECTOR_SHUFFLEv32i8 (ShuffleVectorSDNode *SVOp, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue RewriteAsNarrowerShuffle (ShuffleVectorSDNode *SVOp, SelectionDAG &DAG)
static SDValue getVZextMovL (MVT VT, MVT OpVT, SDValue SrcOp, SelectionDAG &DAG, const X86Subtarget *Subtarget, SDLoc dl)
static SDValue LowerVECTOR_SHUFFLE_256 (ShuffleVectorSDNode *SVOp, SelectionDAG &DAG)
static SDValue LowerVECTOR_SHUFFLE_128v4 (ShuffleVectorSDNode *SVOp, SelectionDAG &DAG)
static bool MayFoldVectorLoad (SDValue V)
static SDValue getMOVDDup (SDValue &Op, SDLoc &dl, SDValue V1, SelectionDAG &DAG)
static SDValue getMOVLowToHigh (SDValue &Op, SDLoc &dl, SelectionDAG &DAG, bool HasSSE2)
static SDValue getMOVHighToLow (SDValue &Op, SDLoc &dl, SelectionDAG &DAG)
static SDValue getMOVLP (SDValue &Op, SDLoc &dl, SelectionDAG &DAG, bool HasSSE2)
static SDValue NarrowVectorLoadToElement (LoadSDNode *Load, unsigned Index, SelectionDAG &DAG)
static SDValue getINSERTPS (ShuffleVectorSDNode *SVOp, SDLoc &dl, SelectionDAG &DAG)
static SDValue LowerVectorIntExtend (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue NormalizeVectorShuffle (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static bool BUILD_VECTORtoBlendMask (BuildVectorSDNode *BuildVector, unsigned &MaskValue)
static SDValue lowerVSELECTtoBLENDI (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Try to lower a VSELECT instruction to an immediate-controlled blend instruction.
static SDValue LowerEXTRACT_VECTOR_ELT_SSE4 (SDValue Op, SelectionDAG &DAG)
static SDValue LowerSCALAR_TO_VECTOR (SDValue Op, SelectionDAG &DAG)
static SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerINSERT_SUBVECTOR (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue GetTLSADDR (SelectionDAG &DAG, SDValue Chain, GlobalAddressSDNode *GA, SDValue *InFlag, const EVT PtrVT, unsigned ReturnReg, unsigned char OperandFlags, bool LocalDynamic=false)
static SDValue LowerToTLSGeneralDynamicModel32 (GlobalAddressSDNode *GA, SelectionDAG &DAG, const EVT PtrVT)
static SDValue LowerToTLSGeneralDynamicModel64 (GlobalAddressSDNode *GA, SelectionDAG &DAG, const EVT PtrVT)
static SDValue LowerToTLSLocalDynamicModel (GlobalAddressSDNode *GA, SelectionDAG &DAG, const EVT PtrVT, bool is64Bit)
static SDValue LowerToTLSExecModel (GlobalAddressSDNode *GA, SelectionDAG &DAG, const EVT PtrVT, TLSModel::Model model, bool is64Bit, bool isPIC)
static SDValue LowerShiftParts (SDValue Op, SelectionDAG &DAG)
static SDValue lowerUINT_TO_FP_vXi32 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerAVXExtend (SDValue Op, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue LowerZERO_EXTEND_AVX512 (SDValue Op, SelectionDAG &DAG)
static SDValue LowerANY_EXTEND (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerZERO_EXTEND (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerFP_EXTEND (SDValue Op, SelectionDAG &DAG)
static SDValue LowerFABSorFNEG (SDValue Op, SelectionDAG &DAG)
static SDValue LowerFCOPYSIGN (SDValue Op, SelectionDAG &DAG)
static SDValue LowerFGETSIGN (SDValue Op, SelectionDAG &DAG)
static SDValue LowerVectorAllZeroTest (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static bool hasNonFlagsUse (SDValue Op)
return true if Op has a use that doesn't just read flags.
static bool isAllOnes (SDValue V)
static int translateX86FSETCC (ISD::CondCode SetCCOpcode, SDValue &Op0, SDValue &Op1)
Turns an ISD::CondCode into a value suitable for SSE floating point mask CMPs.
static SDValue Lower256IntVSETCC (SDValue Op, SelectionDAG &DAG)
static SDValue LowerIntVSETCC_AVX512 (SDValue Op, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue ChangeVSETULTtoVSETULE (SDLoc dl, SDValue Op1, SelectionDAG &DAG)
Try to turn a VSETULT into a VSETULE by modifying its second operand Op1. If non-trivial (for example because it's not constant) return an empty value.
static SDValue LowerVSETCC (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static bool isX86LogicalCmp (SDValue Op)
static bool isTruncWithZeroHighBitsInput (SDValue V, SelectionDAG &DAG)
static SDValue LowerSIGN_EXTEND_AVX512 (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerSIGN_EXTEND (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerExtendedLoad (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static bool isAndOrOfSetCCs (SDValue Op, unsigned &Opc)
static bool isXor1OfSetCC (SDValue Op)
static SDValue LowerVACOPY (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue getTargetVShiftByConstNode (unsigned Opc, SDLoc dl, MVT VT, SDValue SrcOp, uint64_t ShiftAmt, SelectionDAG &DAG)
static SDValue getTargetVShiftNode (unsigned Opc, SDLoc dl, MVT VT, SDValue SrcOp, SDValue ShAmt, SelectionDAG &DAG)
static SDValue getVectorMaskingNode (SDValue Op, SDValue Mask, SDValue PreservedSrc, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Return (and Op, Mask) for compare instructions or (vselect Mask, Op, PreservedSrc) for others along with the necessary casting for Mask when lowering masking intrinsics.
static SDValue getScalarMaskingNode (SDValue Op, SDValue Mask, SDValue PreservedSrc, const X86Subtarget *Subtarget, SelectionDAG &DAG)
Creates an SDNode for a predicated scalar operation.
static unsigned getOpcodeForFMAIntrinsic (unsigned IntNo)
static SDValue LowerINTRINSIC_WO_CHAIN (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue getGatherNode (unsigned Opc, SDValue Op, SelectionDAG &DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget *Subtarget)
static SDValue getScatterNode (unsigned Opc, SDValue Op, SelectionDAG &DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain)
static SDValue getPrefetchNode (unsigned Opc, SDValue Op, SelectionDAG &DAG, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain)
static void getReadPerformanceCounter (SDNode *N, SDLoc DL, SelectionDAG &DAG, const X86Subtarget *Subtarget, SmallVectorImpl< SDValue > &Results)
static void getReadTimeStampCounter (SDNode *N, SDLoc DL, unsigned Opcode, SelectionDAG &DAG, const X86Subtarget *Subtarget, SmallVectorImpl< SDValue > &Results)
static SDValue LowerREADCYCLECOUNTER (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerINTRINSIC_W_CHAIN (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerADJUST_TRAMPOLINE (SDValue Op, SelectionDAG &DAG)
static SDValue LowerCTLZ (SDValue Op, SelectionDAG &DAG)
static SDValue LowerCTLZ_ZERO_UNDEF (SDValue Op, SelectionDAG &DAG)
static SDValue LowerCTTZ (SDValue Op, SelectionDAG &DAG)
static SDValue Lower256IntArith (SDValue Op, SelectionDAG &DAG)
static SDValue LowerADD (SDValue Op, SelectionDAG &DAG)
static SDValue LowerSUB (SDValue Op, SelectionDAG &DAG)
static SDValue LowerMUL (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerMUL_LOHI (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerScalarImmediateShift (SDValue Op, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue LowerScalarVariableShift (SDValue Op, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue LowerShift (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerXALUO (SDValue Op, SelectionDAG &DAG)
static bool hasMFENCE (const X86Subtarget &Subtarget)
static SDValue LowerATOMIC_FENCE (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerCMP_SWAP (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerBITCAST (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerCTPOP (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static SDValue LowerLOAD_SUB (SDValue Op, SelectionDAG &DAG)
static SDValue LowerATOMIC_STORE (SDValue Op, SelectionDAG &DAG)
static SDValue LowerADDC_ADDE_SUBC_SUBE (SDValue Op, SelectionDAG &DAG)
static SDValue LowerFSINCOS (SDValue Op, const X86Subtarget *Subtarget, SelectionDAG &DAG)
static MachineBasicBlock * EmitXBegin (MachineInstr *MI, MachineBasicBlock *MBB, const TargetInstrInfo *TII)
Utility function to emit xbegin specifying the start of an RTM region.
static MachineBasicBlock * EmitPCMPSTRM (MachineInstr *MI, MachineBasicBlock *BB, const TargetInstrInfo *TII)
static MachineBasicBlock * EmitPCMPSTRI (MachineInstr *MI, MachineBasicBlock *BB, const TargetInstrInfo *TII)
static MachineBasicBlock * EmitMonitor (MachineInstr *MI, MachineBasicBlock *BB, const TargetInstrInfo *TII, const X86Subtarget *Subtarget)
static bool checkAndUpdateEFLAGSKill (MachineBasicBlock::iterator SelectItr, MachineBasicBlock *BB, const TargetRegisterInfo *TRI)
static bool isShuffleHigh128VectorInsertLow (ShuffleVectorSDNode *SVOp)
static bool isShuffleLow128VectorInsertHigh (ShuffleVectorSDNode *SVOp)
static SDValue PerformShuffleCombine256 (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
PerformShuffleCombine256 - Performs shuffle combines for 256-bit vectors.
static bool combineX86ShuffleChain (SDValue Op, SDValue Root, ArrayRef< int > Mask, int Depth, bool HasPSHUFB, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
Combine an arbitrary chain of shuffles into a single instruction if possible.
static bool combineX86ShufflesRecursively (SDValue Op, SDValue Root, ArrayRef< int > RootMask, int Depth, bool HasPSHUFB, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
Fully generic combining of x86 shuffle instructions.
static SmallVector< int, 4 > getPSHUFShuffleMask (SDValue N)
Get the PSHUF-style mask from PSHUF node.
static SDValue combineRedundantDWordShuffle (SDValue N, MutableArrayRef< int > Mask, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
Search for a combinable shuffle across a chain ending in pshufd.
static bool combineRedundantHalfShuffle (SDValue N, MutableArrayRef< int > Mask, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
Search for a combinable shuffle across a chain ending in pshuflw or pshufhw.
static SDValue PerformTargetShuffleCombine (SDValue N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
Try to combine x86 target specific shuffles.
static SDValue combineShuffleToAddSub (SDNode *N, SelectionDAG &DAG)
Try to combine a shuffle into a target-specific add-sub node.
static SDValue PerformShuffleCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
PerformShuffleCombine - Performs several different shuffle combines.
static SDValue PerformTruncateCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue XFormVExtractWithShuffleIntoLoad (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue PerformEXTRACT_VECTOR_ELTCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static std::pair< unsigned, bool > matchIntegerMINMAX (SDValue Cond, EVT VT, SDValue LHS, SDValue RHS, SelectionDAG &DAG, const X86Subtarget *Subtarget)
Matches a VSELECT onto min/max or return 0 if the node doesn't match.
static SDValue transformVSELECTtoBlendVECTOR_SHUFFLE (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue PerformSELECTCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue checkBoolTestSetCCCombine (SDValue Cmp, X86::CondCode &CC)
static SDValue PerformCMOVCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
Optimize X86ISD::CMOV [LHS, RHS, CONDCODE (e.g. X86::COND_NE), CONDVAL].
static SDValue PerformINTRINSIC_WO_CHAINCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue PerformMulCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue PerformSHLCombine (SDNode *N, SelectionDAG &DAG)
static SDValue performShiftToAllZeros (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
Returns a vector of 0s if the node in input is a vector logical shift by a constant amount which is known to be bigger than or equal to the vector element size in bits.
static SDValue PerformShiftCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
PerformShiftCombine - Combine shifts.
static SDValue CMPEQCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static bool CanFoldXORWithAllOnes (const SDNode *N)
static SDValue WidenMaskArithmetic (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue PerformAndCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue PerformOrCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue performIntegerAbsCombine (SDNode *N, SelectionDAG &DAG)
static SDValue PerformXorCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue PerformLOADCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
PerformLOADCombine - Do target-specific dag combines on LOAD nodes.
static SDValue PerformMLOADCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
PerformMLOADCombine - Resolve extending loads.
static SDValue PerformMSTORECombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
PerformMSTORECombine - Resolve truncating stores.
static SDValue PerformSTORECombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
PerformSTORECombine - Do target-specific dag combines on STORE nodes.
static bool isHorizontalBinOp (SDValue &LHS, SDValue &RHS, bool IsCommutative)
static SDValue PerformFADDCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
Do target-specific dag combines on floating point adds.
static SDValue PerformFSUBCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
Do target-specific dag combines on floating point subs.
static SDValue PerformFORCombine (SDNode *N, SelectionDAG &DAG)
Do target-specific dag combines on X86ISD::FOR and X86ISD::FXOR nodes.
static SDValue PerformFMinFMaxCombine (SDNode *N, SelectionDAG &DAG)
Do target-specific dag combines on X86ISD::FMIN and X86ISD::FMAX nodes.
static SDValue PerformFANDCombine (SDNode *N, SelectionDAG &DAG)
Do target-specific dag combines on X86ISD::FAND nodes.
static SDValue PerformFANDNCombine (SDNode *N, SelectionDAG &DAG)
Do target-specific dag combines on X86ISD::FANDN nodes.
static SDValue PerformBTCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue PerformVZEXT_MOVLCombine (SDNode *N, SelectionDAG &DAG)
static SDValue PerformSIGN_EXTEND_INREGCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue PerformSExtCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue PerformFMACombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue PerformZExtCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue PerformISDSETCCCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue PerformINSERTPSCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue MaterializeSETB (SDLoc DL, SDValue EFLAGS, SelectionDAG &DAG, MVT VT)
static SDValue PerformSETCCCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue PerformBrCondCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
static SDValue performVectorCompareAndMaskUnaryOpCombine (SDNode *N, SelectionDAG &DAG)
static SDValue PerformSINT_TO_FPCombine (SDNode *N, SelectionDAG &DAG, const X86TargetLowering *XTLI)
static SDValue PerformADCCombine (SDNode *N, SelectionDAG &DAG, X86TargetLowering::DAGCombinerInfo &DCI)
static SDValue OptimizeConditionalInDecrement (SDNode *N, SelectionDAG &DAG)
static SDValue PerformAddCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
PerformADDCombine - Do target-specific dag combines on integer adds.
static SDValue PerformSubCombine (SDNode *N, SelectionDAG &DAG, const X86Subtarget *Subtarget)
static SDValue performVZEXTCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget *Subtarget)
performVZEXTCombine - Performs build vector combines
static bool clobbersFlagRegisters (const SmallVector< StringRef, 4 > &AsmPieces)
Variables
static cl::opt< bool > ExperimentalVectorWideningLegalization ("x86-experimental-vector-widening-legalization", cl::init(false), cl::desc("Enable an experimental vector type legalization through widening ""rather than promotion."), cl::Hidden)
static cl::opt< bool > ExperimentalVectorShuffleLowering ("x86-experimental-vector-shuffle-lowering", cl::init(true), cl::desc("Enable an experimental vector shuffle lowering code path."), cl::Hidden)
static cl::opt< bool > ExperimentalVectorShuffleLegality ("x86-experimental-vector-shuffle-legality", cl::init(false), cl::desc("Enable experimental shuffle legality based on the experimental ""shuffle lowering. Should only be used with the experimental ""shuffle lowering."), cl::Hidden)
static cl::opt< int > ReciprocalEstimateRefinementSteps ("x86-recip-refinement-steps", cl::init(1), cl::desc("Specify the number of Newton-Raphson iterations applied to the ""result of the hardware reciprocal estimate instruction."), cl::NotHidden)
static const VariadicFunction1
< bool, ArrayRef< int >, int,
isShuffleEquivalentImpl > isShuffleEquivalent = {}
Checks whether a shuffle mask is equivalent to an explicit list of arguments.
Macro Definition Documentation
#define DEBUG_TYPE "x86-isel"
Definition at line 59 of file X86ISelLowering.cpp.
Enumeration Type Documentation
enum StructReturnType
CallIsStructReturn - Determines whether a call uses struct return semantics.
Enumerator
NotStructReturn
RegStructReturn
StackStructReturn
Definition at line 2244 of file X86ISelLowering.cpp.
Function Documentation
static StructReturnType argsAreStructReturn (const SmallVectorImpl< ISD::InputArg > & Ins) static
Determines whether a function uses struct return semantics.
Definition at line 2264 of file X86ISelLowering.cpp.
References llvm::SmallVectorBase::empty(), llvm::ISD::ArgFlagsTy::isInReg(), llvm::ISD::ArgFlagsTy::isSRet(), NotStructReturn, RegStructReturn, and StackStructReturn.
static bool BUILD_VECTORtoBlendMask (BuildVectorSDNode * BuildVector, unsigned & MaskValue) static
Definition at line 12634 of file X86ISelLowering.cpp.
References llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), and isZero().
Referenced by lowerVSELECTtoBLENDI(), and transformVSELECTtoBlendVECTOR_SHUFFLE().
static SDValue buildFromShuffleMostly (SDValue Op, SelectionDAG & DAG) static
Definition at line 6313 of file X86ISelLowering.cpp.
References DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), getUnderlyingExtractedFromVec(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVectorShuffle(), llvm::ISD::INSERT_VECTOR_ELT, llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::AArch64CC::NV, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ISD::UNDEF.
static StructReturnType callIsStructReturn (const SmallVectorImpl< ISD::OutputArg > & Outs) static
Definition at line 2250 of file X86ISelLowering.cpp.
References llvm::SmallVectorBase::empty(), llvm::ISD::ArgFlagsTy::isInReg(), llvm::ISD::ArgFlagsTy::isSRet(), NotStructReturn, RegStructReturn, and StackStructReturn.
static bool CanFoldXORWithAllOnes (const SDNode * N) static
CanFoldXORWithAllOnes - Test whether the XOR operand is a AllOnes vector so it can be folded inside ANDNP.
Definition at line 24309 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ISD::INSERT_SUBVECTOR, llvm::EVT::is256BitVector(), llvm::ISD::isBuildVectorAllOnes(), and llvm::ISD::UNDEF.
Referenced by PerformAndCombine().
static int canLowerByDroppingEvenElements (ArrayRef< int > Mask) static
Check whether a compaction lowering can be done by dropping even elements and compute how many times even elements must be dropped.
This handles shuffles which take every Nth element where N is a power of two. Example shuffle masks:
N = 1: 0, 2, 4, 6, 8, 10, 12, 14, 0, 2, 4, 6, 8, 10, 12, 14 N = 1: 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30 N = 2: 0, 4, 8, 12, 0, 4, 8, 12, 0, 4, 8, 12, 0, 4, 8, 12 N = 2: 0, 4, 8, 12, 16, 20, 24, 28, 0, 4, 8, 12, 16, 20, 24, 28 N = 3: 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8 N = 3: 0, 8, 16, 24, 0, 8, 16, 24, 0, 8, 16, 24, 0, 8, 16, 24
Any of these lanes can of course be undef.
This routine only supports N <= 3. FIXME: Evaluate whether either AVX or AVX-512 have any opportunities here for larger N.
Returns
N above, or the number of times even elements must be dropped if there is such a number. Otherwise returns zero.
Definition at line 9401 of file X86ISelLowering.cpp.
References llvm::array_lengthof(), assert(), llvm::isPowerOf2_32(), isSingleInputShuffleMask(), and llvm::ArrayRef< T >::size().
Referenced by lowerV16I8VectorShuffle().
static bool canWidenShuffleElements (ArrayRef< int > Mask, SmallVectorImpl< int > & WidenedMask) static
Helper function to test whether a shuffle mask could be simplified by widening the elements being shuffled.
Appends the mask for wider elements in WidenedMask if valid. Otherwise leaves it in an unspecified state.
NOTE: This must handle normal vector shuffle masks and target vector shuffle masks. The latter have the special property of a '-2' representing a zero-ed lane of a vector.
Definition at line 9827 of file X86ISelLowering.cpp.
References assert(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by combineX86ShufflesRecursively(), lowerV4F64VectorShuffle(), lowerV4I64VectorShuffle(), and lowerVectorShuffle().
static SDValue ChangeVSETULTtoVSETULE (SDLoc dl, SDValue Op1, SelectionDAG & DAG) static
Try to turn a VSETULT into a VSETULE by modifying its second operand Op1. If non-trivial (for example because it's not constant) return an empty value.
Definition at line 15332 of file X86ISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::ConstantSDNode::isOpaque(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by LowerVSETCC().
static bool checkAndUpdateEFLAGSKill (MachineBasicBlock::iterator SelectItr, MachineBasicBlock * BB, const TargetRegisterInfo * TRI) static
Definition at line 20838 of file X86ISelLowering.cpp.
References llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineInstr::readsRegister(), llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
static SDValue checkBoolTestSetCCCombine (SDValue Cmp, X86::CondCode & CC) static
Definition at line 23662 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::X86ISD::CMOV, llvm::X86ISD::CMP, llvm::X86::COND_B, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::dyn_cast(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::X86::GetOppositeBranchCondition(), llvm::SDValue::getResNo(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasAnyUseOfValue(), llvm::X86ISD::RDRAND, llvm::X86ISD::RDSEED, llvm::X86ISD::SETCC, llvm::X86ISD::SETCC_CARRY, llvm::X86ISD::SUB, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by PerformBrCondCombine(), PerformCMOVCombine(), and PerformSETCCCombine().
static bool clobbersFlagRegisters (const SmallVector< StringRef, 4 > & AsmPieces) static
Definition at line 26175 of file X86ISelLowering.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::X86TargetLowering::ExpandInlineAsm().
static SDValue CMPEQCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 24209 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::ISD::BR_CC, llvm::ISD::BRCOND, llvm::X86ISD::CMP, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::X86::COND_NP, llvm::X86::COND_P, llvm::ISD::CopyToReg, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::X86ISD::FSETCC, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), isAndOrOfSetCCs(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SELECT, llvm::ISD::SIGN_EXTEND, llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::MVT::v2f64, llvm::MVT::v4f32, and llvm::ISD::ZERO_EXTEND.
Referenced by PerformAndCombine(), and PerformOrCombine().
static SDValue combineRedundantDWordShuffle (SDValue N, MutableArrayRef< int > Mask, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Search for a combinable shuffle across a chain ending in pshufd.
We walk up the chain and look for a combinable shuffle, skipping over shuffles that we could hoist this shuffle's transformation past without altering anything.
Definition at line 22289 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::SmallVectorBase::empty(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPSHUFShuffleMask(), getV4X86ShuffleImm8ForMask(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::SDNode::isOnlyUserOf(), llvm_unreachable, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v16i8, and llvm::MVT::v8i16.
Referenced by PerformTargetShuffleCombine().
static bool combineRedundantHalfShuffle (SDValue N, MutableArrayRef< int > Mask, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Search for a combinable shuffle across a chain ending in pshuflw or pshufhw.
We walk up the chain, skipping shuffles of the other half and looking through shuffles which switch halves trying to find a shuffle of the same pair of dwords.
Definition at line 22421 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPSHUFShuffleMask(), getV4X86ShuffleImm8ForMask(), llvm::SDValue::hasOneUse(), llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, and llvm::MVT::v8i16.
Referenced by PerformTargetShuffleCombine().
static SDValue combineShuffleToAddSub (SDNode * N, SelectionDAG & DAG) static
Try to combine a shuffle into a target-specific add-sub node.
We combine this directly on the abstract vector shuffle nodes so it is easier to generically match. We also insert dummy vector shuffle nodes for the operands which explicitly discard the lanes which are unused by this operation to try to flow through the rest of the combiner the fact that they're unused.
Definition at line 22595 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADDSUB, assert(), llvm::ISD::FADD, llvm::ISD::FSUB, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::SDNode::hasOneUse(), isShuffleEquivalent, N, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v8f32, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by PerformShuffleCombine().
static bool combineX86ShuffleChain (SDValue Op, SDValue Root, ArrayRef< int > Mask, int Depth, bool HasPSHUFB, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Combine an arbitrary chain of shuffles into a single instruction if possible.
This is the leaf of the recursive combinine below. When we have found some chain of single-use x86 shuffle instructions and accumulated the combined shuffle mask represented by them, this will try to pattern match that mask into either a single instruction if there is a special purpose instruction for this operation, or into a PSHUFB instruction which is a fully general instruction but should only be used to replace chains over a certain depth.
Definition at line 21942 of file X86ISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::equals(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i8, llvm::MVT::isFloatingPoint(), llvm_unreachable, llvm::HexagonISD::Lo, llvm::X86ISD::MOVDDUP, llvm::X86ISD::MOVHLPS, llvm::X86ISD::MOVLHPS, llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::X86ISD::PSHUFB, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, llvm::SM_SentinelZero, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v4f32, and llvm::MVT::v8i16.
Referenced by combineX86ShufflesRecursively().
static bool combineX86ShufflesRecursively (SDValue Op, SDValue Root, ArrayRef< int > RootMask, int Depth, bool HasPSHUFB, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Fully generic combining of x86 shuffle instructions.
This should be the last combine run over the x86 shuffle instructions. Once they have been fully optimized, this will recursively consider all chains of single-use shuffle instructions, build a generic model of the cumulative shuffle operation, and check for simpler instructions which implement this operation. We use this primarily for two purposes:
1) Collapse generic shuffles to specialized single instructions when equivalent. In most cases, this is just an encoding size win, but sometimes we will collapse multiple generic shuffles into a single special-purpose shuffle. 2) Look for sequences of shuffle instructions with 3 or more total instructions, and replace them with the slightly more expensive SSSE3 PSHUFB instruction if available. We do this as the last combining step to ensure we avoid using PSHUFB if we can implement the shuffle with a suitable short sequence of other instructions. The PHUFB will either use a register or have to read from memory and so is slightly (but only slightly) more expensive than the other shuffle instructions.
Because this is inherently a quadratic operation (for each shuffle in a chain, we recurse up the chain), the depth is limited to 8 instructions. This should never be an issue in practice as the shuffle lowering doesn't produce sequences of more than 8 instructions.
FIXME: We will currently miss some cases where the redundant shuffling would simplify under the threshold for PSHUFB formation because of combine-ordering. To fix this, we should do the redundant instruction combining in this recursive walk.
Definition at line 22137 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, canWidenShuffleElements(), llvm::SmallVectorImpl< T >::clear(), combineX86ShuffleChain(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), getTargetShuffleMask(), llvm::MVT::getVectorNumElements(), llvm::SDValue::hasOneUse(), llvm::SDNode::isOnlyUserOf(), isTargetShuffle(), llvm::MVT::isVector(), llvm::X86ISD::PSHUFB, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ArrayRef< T >::size(), llvm::X86ISD::UNPCKH, and llvm::X86ISD::UNPCKL.
Referenced by PerformShuffleCombine().
static void CommuteVectorShuffleMask (SmallVectorImpl< int > & Mask, unsigned NumElems) static
CommuteVectorShuffleMask - Change values in a shuffle permute mask assuming the two vector operands have swapped position.
Definition at line 4113 of file X86ISelLowering.cpp.
Referenced by isHorizontalBinOp(), LowerVECTOR_SHUFFLE_128v4(), LowerVECTOR_SHUFFLEv32i8(), and LowerVECTOR_SHUFFLEv8i16().
static SDValue Compact8x32ShuffleNode (ShuffleVectorSDNode * SVOp, SelectionDAG & DAG) static
Definition at line 4302 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getVectorShuffle(), isUndefOrEqual(), llvm::ISD::UNDEF, llvm::MVT::v8f32, and llvm::MVT::v8i32.
Referenced by LowerVECTOR_SHUFFLE_256().
static SmallBitVector computeZeroableShuffleElements (ArrayRef< int > Mask, SDValue V1, SDValue V2) static
Compute whether each element of a shuffle is zeroable.
A "zeroable" vector shuffle element is one which can be lowered to zero. Either it is an undef element in the shuffle mask, the element of the input referenced is undef, or the element of the input referenced is known to be zero. Many x86 shuffles can zero lanes cheaply and we often want to handle as many lanes with this technique as possible to simplify the remaining shuffle.
Definition at line 7694 of file X86ISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::isBuildVectorAllZeros(), llvm::X86::isZeroNode(), llvm::ArrayRef< T >::size(), llvm::ISD::UNDEF, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV16I8VectorShuffle(), lowerVectorShuffleAsByteShift(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsInsertPS(), and lowerVectorShuffleAsZeroOrAnyExtend().
static SDValue Concat128BitVectors (SDValue V1, SDValue V2, EVT VT, unsigned NumElems, SelectionDAG & DAG, SDLoc dl) static
Concat two 128-bit vectors into a 256 bit vector using VINSERTF128 instructions. This is used because creating CONCAT_VECTOR nodes of BUILD_VECTORS returns a larger BUILD_VECTOR while we're trying to lower large BUILD_VECTORS.
Definition at line 190 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getUNDEF(), and Insert128BitVector().
Referenced by getOnesVector(), and LowerAVXCONCAT_VECTORS().
static SDValue Concat256BitVectors (SDValue V1, SDValue V2, EVT VT, unsigned NumElems, SelectionDAG & DAG, SDLoc dl) static
Definition at line 197 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getUNDEF(), and Insert256BitVector().
Referenced by LowerAVXCONCAT_VECTORS().
static SDValue CreateCopyOfByValArgument (SDValue Src, SDValue Dst, SDValue Chain, ISD::ArgFlagsTy Flags, SelectionDAG & DAG, SDLoc dl) static
Make a copy of an aggregate at address specified by "Src" to address "Dst" with size and alignment information specified by the specific parameter attribute. The copy will be passed as a byval function parameter.
Definition at line 2280 of file X86ISelLowering.cpp.
References llvm::ISD::ArgFlagsTy::getByValAlign(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMemcpy(), and llvm::MVT::i32.
static SDValue EltsFromConsecutiveLoads (EVT VT, SmallVectorImpl< SDValue > & Elts, SDLoc & DL, SelectionDAG & DAG, bool isAfterLegalize) static
EltsFromConsecutiveLoads - Given the initializing elements 'Elts' of a vector of type 'VT', see if the elements can be replaced by a single large load which has the same value as a build_vector whose operands are 'elts'.
Example: <load i32 *a, load i32 *a+4, undef, undef> -> zextload a
FIXME: we'd also like to handle the case where the last elements are zero rather than undef via VZEXT_LOAD, but we do not detect that case today. There's even a handy isZeroNode for that purpose.
Definition at line 6025 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::hasAnyUseOfValue(), llvm::MVT::i64, llvm::SelectionDAG::isConsecutiveLoad(), llvm::MemSDNode::isInvariant(), llvm::ISD::isNON_EXTLoad(), llvm::MemSDNode::isNonTemporal(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MemSDNode::isVolatile(), llvm::AArch64DB::LD, llvm::ISD::LOAD, llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TokenFactor, llvm::ISD::UNDEF, llvm::SelectionDAG::UpdateNodeOperands(), llvm::MVT::v2i64, and llvm::X86ISD::VZEXT_LOAD.
Referenced by PerformShuffleCombine().
static MachineBasicBlock* EmitMonitor (MachineInstr * MI, MachineBasicBlock * BB, const TargetInstrInfo * TII, const X86Subtarget * Subtarget) static
Definition at line 20475 of file X86ISelLowering.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::X86::AddrNumOperands, llvm::BuildMI(), llvm::TargetOpcode::COPY, llvm::N86::EAX, llvm::N86::ECX, llvm::N86::EDX, llvm::MachineInstr::eraseFromParent(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and llvm::X86Subtarget::is64Bit().
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter().
static MachineBasicBlock* EmitPCMPSTRI (MachineInstr * MI, MachineBasicBlock * BB, const TargetInstrInfo * TII) static
Definition at line 20440 of file X86ISelLowering.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::BuildMI(), llvm::TargetOpcode::COPY, llvm::N86::ECX, llvm::MachineInstr::eraseFromParent(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::hasOneMemOperand(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm_unreachable, llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), and llvm::MachineInstr::setMemRefs().
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter().
static MachineBasicBlock* EmitPCMPSTRM (MachineInstr * MI, MachineBasicBlock * BB, const TargetInstrInfo * TII) static
Definition at line 20403 of file X86ISelLowering.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::BuildMI(), llvm::TargetOpcode::COPY, llvm::MachineInstr::eraseFromParent(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::hasOneMemOperand(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm_unreachable, llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), and llvm::MachineInstr::setMemRefs().
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter().
static SDValue EmitTailCallStoreRetAddr (SelectionDAG & DAG, MachineFunction & MF, SDValue Chain, SDValue RetAddrFrIdx, EVT PtrVT, unsigned SlotSize, int FPDiff, SDLoc dl) static
Emit a store of the return address if tail call optimization is performed and it is required (FPDiff!=0).
Definition at line 2759 of file X86ISelLowering.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), and llvm::SelectionDAG::getStore().
static MachineBasicBlock* EmitXBegin (MachineInstr * MI, MachineBasicBlock * MBB, const TargetInstrInfo * TII) static
Utility function to emit xbegin specifying the start of an RTM region.
Definition at line 20345 of file X86ISelLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::TargetOpcode::COPY, llvm::MachineFunction::CreateMachineBasicBlock(), llvm::N86::EAX, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), I, llvm::MachineFunction::insert(), llvm::MachineBasicBlock::splice(), and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter().
static SDValue ExpandHorizontalBinOp (const SDValue & V0, const SDValue & V1, SDLoc DL, SelectionDAG & DAG, unsigned X86Opcode, bool Mode, bool isUndefLO, bool isUndefHI) static
Emit a sequence of two 128-bit horizontal add/sub followed by a concat_vector.
This is a helper function of PerformBUILD_VECTORCombine. This function expects two 256-bit vectors called V0 and V1. At first, each vector is split into two separate 128-bit vectors. Then, the resulting 128-bit vectors are used to implement two horizontal binary operations.
The kind of horizontal binary operation is defined by X86Opcode.
Mode specifies how the 128-bit parts of V0 and V1 are passed in input to the two new horizontal binop. When Mode is set, the first horizontal binop dag node would take as input the lower 128-bit of V0 and the upper 128-bit of V0. The second horizontal binop dag node would take as input the lower 128-bit of V1 and the upper 128-bit of V1. Example: HADD V0_LO, V0_HI HADD V1_LO, V1_HI
Otherwise, the first horizontal binop dag node takes as input the lower 128-bit of V0 and the lower 128-bit of V1, and the second horizontal binop dag node takes the the upper 128-bit of V0 and the upper 128-bit of V1. Example: HADD V0_LO, V1_LO HADD V0_HI, V1_HI
If isUndefLO is set, then the algorithm propagates UNDEF to the lower 128-bits of the result. If isUndefHI is set, then UNDEF is propagated to the upper 128-bits of the result.
Definition at line 6586 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, Extract128BitVector(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::AArch64CC::HI, llvm::EVT::is256BitVector(), llvm::AArch64CC::LO, and llvm::ISD::UNDEF.
Referenced by PerformBUILD_VECTORCombine().
static SDValue Extract128BitVector (SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, SDLoc dl) static
Generate a DAG to grab 128-bits from a vector > 128 bits. This sets things up to match to an AVX VEXTRACTF128 / VEXTRACTI128 or AVX-512 VEXTRACTF32x4 / VEXTRACTI32x4 instructions or a simple subregister reference. Idx is an index in the 128 bits we want. It need not be aligned to a 128-bit boundary. That makes lowering EXTRACT_VECTOR_ELT operations easier.
Definition at line 130 of file X86ISelLowering.cpp.
References assert(), ExtractSubVector(), llvm::SDValue::getValueType(), llvm::EVT::is256BitVector(), and llvm::EVT::is512BitVector().
Referenced by ExpandHorizontalBinOp(), Lower256IntArith(), Lower256IntVSETCC(), LowerEXTRACT_SUBVECTOR(), LowerShift(), LowerVECTOR_SHUFFLE_256(), LowerVectorBroadcast(), PerformSELECTCombine(), PerformShuffleCombine256(), PerformSTORECombine(), and PromoteSplat().
static SDValue Extract256BitVector (SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, SDLoc dl) static
Generate a DAG to grab 256-bits from a 512-bit vector.
Definition at line 138 of file X86ISelLowering.cpp.
References assert(), ExtractSubVector(), llvm::SDValue::getValueType(), and llvm::EVT::is512BitVector().
Referenced by LowerEXTRACT_SUBVECTOR().
static SDValue ExtractSubVector (SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, SDLoc dl, unsigned vectorWidth) static
Definition at line 91 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::makeArrayRef(), llvm::SDNode::op_begin(), and llvm::ISD::UNDEF.
Referenced by Extract128BitVector(), and Extract256BitVector().
static bool FuncIsMadeTailCallSafe (CallingConv::ID CC, bool GuaranteedTailCallOpt) static
Return true if the function is being made into a tailcall target by changing its ABI.
Definition at line 2317 of file X86ISelLowering.cpp.
References IsTailCallConvention().
static ArrayRef<MCPhysReg> get64BitArgumentGPRs (CallingConv::ID CallConv, const X86Subtarget * Subtarget) static
Definition at line 2364 of file X86ISelLowering.cpp.
References assert(), llvm::sys::path::begin(), llvm::sys::path::end(), llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isCallingConvWin64(), and llvm::makeArrayRef().
static ArrayRef<MCPhysReg> get64BitArgumentXMMs (MachineFunction & MF, CallingConv::ID CallConv, const X86Subtarget * Subtarget) static
Definition at line 2382 of file X86ISelLowering.cpp.
References assert(), llvm::sys::path::begin(), llvm::sys::path::end(), llvm::AttributeSet::FunctionIndex, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getTarget(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isCallingConvWin64(), llvm::makeArrayRef(), llvm::Attribute::NoImplicitFloat, llvm::None, llvm::TargetMachine::Options, and llvm::TargetOptions::UseSoftFloat.
static unsigned getExtractVEXTRACTImmediate (SDNode * N, unsigned vecWidth) static
Definition at line 4956 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), and llvm_unreachable.
Referenced by llvm::X86::getExtractVEXTRACT128Immediate(), and llvm::X86::getExtractVEXTRACT256Immediate().
static SDValue getGatherNode (unsigned Opc, SDValue Op, SelectionDAG & DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget * Subtarget) static
Definition at line 17392 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SelectionDAG::getRegister(), llvm::ConstantSDNode::getSExtValue(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), getZeroVector(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i1, llvm::MVT::i8, llvm::MVT::Other, and llvm::ISD::UNDEF.
Referenced by LowerINTRINSIC_W_CHAIN().
static SDValue getINSERTPS (ShuffleVectorSDNode * SVOp, SDLoc & dl, SelectionDAG & DAG) static
Definition at line 12078 of file X86ISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::X86ISD::INSERTPS, MayFoldLoad(), NarrowVectorLoadToElement(), llvm::ISD::SCALAR_TO_VECTOR, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v4f32, and llvm::MVT::v4i32.
static unsigned getInsertVINSERTImmediate (SDNode * N, unsigned vecWidth) static
Definition at line 4971 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), and llvm_unreachable.
Referenced by llvm::X86::getInsertVINSERT128Immediate(), and llvm::X86::getInsertVINSERT256Immediate().
static SDValue getLegalSplat (SelectionDAG & DAG, SDValue V, int EltNo) static
getLegalSplat - Generate a legal splat with supported x86 shuffles
Definition at line 5282 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm_unreachable, llvm::MVT::v4f32, and llvm::MVT::v8f32.
Referenced by PromoteSplat().
static void getMaxByValAlign (Type * Ty, unsigned & MaxAlign) static
Helper for getByValTypeAlignment to determine the desired ByVal argument alignment.
Definition at line 1778 of file X86ISelLowering.cpp.
Referenced by llvm::X86TargetLowering::getByValTypeAlignment().
static SDValue getMOVDDup (SDValue & Op, SDLoc & dl, SDValue V1, SelectionDAG & DAG) static
Definition at line 11957 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getTargetShuffleNode(), llvm::X86ISD::MOVDDUP, and llvm::MVT::v2f64.
static SDValue getMOVHighToLow (SDValue & Op, SDLoc & dl, SelectionDAG & DAG) static
Definition at line 11987 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), getTargetShuffleNode(), llvm::X86ISD::MOVHLPS, llvm::ISD::UNDEF, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v4f32, and llvm::MVT::v4i32.
static SDValue getMOVL (SelectionDAG & DAG, SDLoc dl, EVT VT, SDValue V1, SDValue V2) static
getMOVLMask - Returns a vector_shuffle mask for an movs{s|d}, movd operation of specified width.
Definition at line 5226 of file X86ISelLowering.cpp.
References llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
static SDValue getMOVLowToHigh (SDValue & Op, SDLoc & dl, SelectionDAG & DAG, bool HasSSE2) static
Definition at line 11968 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), getTargetShuffleNode(), llvm::X86ISD::MOVLHPD, llvm::X86ISD::MOVLHPS, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, llvm::MVT::v2i64, and llvm::MVT::v4f32.
static SDValue getMOVLP (SDValue & Op, SDLoc & dl, SelectionDAG & DAG, bool HasSSE2) static
Definition at line 12003 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDValue::getOperand(), getShuffleSHUFImmediate(), llvm::SDValue::getSimpleValueType(), getTargetShuffleNode(), llvm::MVT::getVectorNumElements(), isMOVLMask(), MayFoldIntoStore(), MayFoldVectorLoad(), llvm::X86ISD::MOVLPD, llvm::X86ISD::MOVLPS, llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSS, llvm::X86ISD::SHUFP, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::MVT::v4i32.
static unsigned getNumOfConsecutiveZeros (ShuffleVectorSDNode * SVOp, unsigned NumElems, bool ZerosFromLeft, SelectionDAG & DAG, unsigned PreferredNum = -1U) static
getNumOfConsecutiveZeros - Return the number of elements of a vector shuffle operation which come from a consecutively from a zero. The search can start in two different directions, from left or right. We count undefs as zeros until PreferredNum is reached.
Definition at line 5600 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), getShuffleScalarElt(), llvm::X86::isZeroNode(), and llvm::ISD::UNDEF.
Referenced by isVectorShiftLeft(), and isVectorShiftRight().
static SDValue getOnesVector (MVT VT, bool HasInt256, SelectionDAG & DAG, SDLoc dl) static
getOnesVector - Returns a vector of specified type with all bits set. Always build ones vectors as <4 x i32> or <8 x i32>. For 256-bit types with no AVX2 supprt, use two <4 x i32> inserted in a <8 x i32> appropriately. Then bitcast to their original type, ensuring they get CSE'd.
Definition at line 5192 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, Concat128BitVectors(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::isVector(), llvm_unreachable, llvm::MVT::v4i32, and llvm::MVT::v8i32.
static unsigned getOpcodeForFMAIntrinsic (unsigned IntNo) static
Definition at line 16981 of file X86ISelLowering.cpp.
References llvm::X86ISD::FMADD, llvm::X86ISD::FMADDSUB, llvm::X86ISD::FMSUB, llvm::X86ISD::FMSUBADD, llvm::X86ISD::FNMADD, llvm::X86ISD::FNMSUB, llvm_unreachable, llvm::Intrinsic::x86_fma_mask_vfmadd_pd_512, llvm::Intrinsic::x86_fma_mask_vfmadd_ps_512, llvm::Intrinsic::x86_fma_mask_vfmaddsub_pd_512, llvm::Intrinsic::x86_fma_mask_vfmaddsub_ps_512, llvm::Intrinsic::x86_fma_mask_vfmsub_pd_512, llvm::Intrinsic::x86_fma_mask_vfmsub_ps_512, llvm::Intrinsic::x86_fma_mask_vfmsubadd_pd_512, llvm::Intrinsic::x86_fma_mask_vfmsubadd_ps_512, llvm::Intrinsic::x86_fma_mask_vfnmadd_pd_512, llvm::Intrinsic::x86_fma_mask_vfnmadd_ps_512, llvm::Intrinsic::x86_fma_mask_vfnmsub_pd_512, llvm::Intrinsic::x86_fma_mask_vfnmsub_ps_512, llvm::Intrinsic::x86_fma_vfmadd_pd, llvm::Intrinsic::x86_fma_vfmadd_pd_256, llvm::Intrinsic::x86_fma_vfmadd_ps, llvm::Intrinsic::x86_fma_vfmadd_ps_256, llvm::Intrinsic::x86_fma_vfmaddsub_pd, llvm::Intrinsic::x86_fma_vfmaddsub_pd_256, llvm::Intrinsic::x86_fma_vfmaddsub_ps, llvm::Intrinsic::x86_fma_vfmaddsub_ps_256, llvm::Intrinsic::x86_fma_vfmsub_pd, llvm::Intrinsic::x86_fma_vfmsub_pd_256, llvm::Intrinsic::x86_fma_vfmsub_ps, llvm::Intrinsic::x86_fma_vfmsub_ps_256, llvm::Intrinsic::x86_fma_vfmsubadd_pd, llvm::Intrinsic::x86_fma_vfmsubadd_pd_256, llvm::Intrinsic::x86_fma_vfmsubadd_ps, llvm::Intrinsic::x86_fma_vfmsubadd_ps_256, llvm::Intrinsic::x86_fma_vfnmadd_pd, llvm::Intrinsic::x86_fma_vfnmadd_pd_256, llvm::Intrinsic::x86_fma_vfnmadd_ps, llvm::Intrinsic::x86_fma_vfnmadd_ps_256, llvm::Intrinsic::x86_fma_vfnmsub_pd, llvm::Intrinsic::x86_fma_vfnmsub_pd_256, llvm::Intrinsic::x86_fma_vfnmsub_ps, and llvm::Intrinsic::x86_fma_vfnmsub_ps_256.
Referenced by LowerINTRINSIC_WO_CHAIN().
static SDValue getPrefetchNode (unsigned Opc, SDValue Op, SelectionDAG & DAG, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain) static
Definition at line 17442 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::ConstantSDNode::getSExtValue(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i1, llvm::MVT::i8, and llvm::MVT::Other.
Referenced by LowerINTRINSIC_W_CHAIN().
static SDValue getPSHUFB (ArrayRef< int > MaskVals, SDValue V1, SDLoc & dl, SelectionDAG & DAG) static
Generate a PSHUFB if possible. Selects elements from V1 according to MaskVals. MaskVals[OutputIdx] = InputIdx specifies that we want to shuffle the element at InputIdx in V1 to OutputIdx in the result. If MaskVals refers to elements outside of V1 or is undef (-1), insert a zero.
Definition at line 11147 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i8, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::X86ISD::PSHUFB, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), ShuffleCrosses128bitLane(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by LowerVECTOR_SHUFFLEv16i16(), LowerVECTOR_SHUFFLEv32i8(), and LowerVECTOR_SHUFFLEv8i16().
static SmallVector<int, 4> getPSHUFShuffleMask (SDValue N) static
Get the PSHUF-style mask from PSHUF node.
This is a very minor wrapper around getTargetShuffleMask to easy forming v4 PSHUF-style masks that can be reused with such instructions.
Definition at line 22260 of file X86ISelLowering.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::erase(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getSimpleValueType(), getTargetShuffleMask(), llvm_unreachable, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, and llvm::SmallVectorImpl< T >::resize().
Referenced by combineRedundantDWordShuffle(), combineRedundantHalfShuffle(), and PerformTargetShuffleCombine().
static void getReadPerformanceCounter (SDNode * N, SDLoc DL, SelectionDAG & DAG, const X86Subtarget * Subtarget, SmallVectorImpl< SDValue > & Results) static
Definition at line 17467 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_PAIR, llvm::N86::EAX, llvm::N86::ECX, llvm::N86::EDX, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::AArch64CC::HI, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm::AArch64CC::LO, llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::X86ISD::RDPMC_DAG, and llvm::ISD::SHL.
Referenced by LowerINTRINSIC_W_CHAIN(), and llvm::X86TargetLowering::ReplaceNodeResults().
static void getReadTimeStampCounter (SDNode * N, SDLoc DL, unsigned Opcode, SelectionDAG & DAG, const X86Subtarget * Subtarget, SmallVectorImpl< SDValue > & Results) static
Definition at line 17513 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_PAIR, llvm::N86::EAX, llvm::N86::ECX, llvm::N86::EDX, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getStore(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::AArch64CC::HI, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm::AArch64CC::LO, llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::X86ISD::RDTSCP_DAG, and llvm::ISD::SHL.
Referenced by LowerINTRINSIC_W_CHAIN(), LowerREADCYCLECOUNTER(), and llvm::X86TargetLowering::ReplaceNodeResults().
static SDValue getScalarMaskingNode (SDValue Op, SDValue Mask, SDValue PreservedSrc, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Creates an SDNode for a predicated scalar operation.
Returns
(X86vselect Mask, Op, PreservedSrc). The mask is comming as MVT::i8 and it should be truncated to MVT::i1 while lowering masking intrinsics. The main difference between ScalarMaskingNode and VectorMaskingNode is using "X86select" instead of "vselect". We just can't create the "vselect" node for a scalar instruction.
Definition at line 16964 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getValueType(), getZeroVector(), llvm::MVT::i1, isAllOnes(), llvm::X86ISD::SELECT, llvm::ISD::TRUNCATE, and llvm::ISD::UNDEF.
Referenced by LowerINTRINSIC_WO_CHAIN().
static SDValue getScalarValueForVectorElement (SDValue V, int Idx, SelectionDAG & DAG) static
Try to get a scalar value for a specific element of a vector.
Looks through BUILD_VECTOR and SCALAR_TO_VECTOR nodes to find a scalar.
Definition at line 7959 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::isVector(), and llvm::ISD::SCALAR_TO_VECTOR.
Referenced by lowerV2F64VectorShuffle(), and lowerVectorShuffleAsElementInsertion().
static SDValue getScatterNode (unsigned Opc, SDValue Op, SelectionDAG & DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain) static
Definition at line 17419 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::ConstantSDNode::getSExtValue(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i1, llvm::MVT::i8, and llvm::MVT::Other.
Referenced by LowerINTRINSIC_W_CHAIN().
static unsigned getShuffleAlignrImmediate (ShuffleVectorSDNode * SVOp, bool InterLane) static
Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with the PALIGNR (if InterLane is false) or with VALIGN (if Interlane is true) instructions.
Definition at line 4919 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), and llvm::MVT::is512BitVector().
Referenced by getShufflePALIGNRImmediate(), and getShuffleVALIGNImmediate().
static unsigned getShufflePALIGNRImmediate (ShuffleVectorSDNode * SVOp) static
Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with the PALIGNR instruction.
Definition at line 4945 of file X86ISelLowering.cpp.
References getShuffleAlignrImmediate().
static unsigned getShufflePSHUFHWImmediate (ShuffleVectorSDNode * N) static
getShufflePSHUFHWImmediate - Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with the PSHUFHW instruction.
Definition at line 4870 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::v16i16, and llvm::MVT::v8i16.
Referenced by LowerVECTOR_SHUFFLEv8i16().
static unsigned getShufflePSHUFLWImmediate (ShuffleVectorSDNode * N) static
getShufflePSHUFLWImmediate - Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with the PSHUFLW instruction.
Definition at line 4894 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::v16i16, and llvm::MVT::v8i16.
Referenced by LowerVECTOR_SHUFFLEv8i16().
static SDValue getShuffleScalarElt (SDNode * N, unsigned Index, SelectionDAG & DAG, unsigned Depth) static
getShuffleScalarElt - Returns the scalar element that will make up the ith element of the result of the vector shuffle.
Definition at line 5534 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), getTargetShuffleMask(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), isTargetShuffle(), llvm::EVT::isVector(), and llvm::ISD::SCALAR_TO_VECTOR.
Referenced by getNumOfConsecutiveZeros(), and PerformShuffleCombine().
static unsigned getShuffleSHUFImmediate (ShuffleVectorSDNode * N) static
getShuffleSHUFImmediate - Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with PSHUF* and SHUFP* instructions. Handles 128-bit and 256-bit.
Definition at line 4840 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), and llvm::MVT::getVectorNumElements().
Referenced by getMOVLP().
static unsigned getShuffleVALIGNImmediate (ShuffleVectorSDNode * SVOp) static
Return the appropriate immediate to shuffle the specified VECTOR_SHUFFLE mask with the VALIGN instruction.
Definition at line 4951 of file X86ISelLowering.cpp.
References getShuffleAlignrImmediate().
static SDValue getShuffleVectorZeroOrUndef (SDValue V2, unsigned Idx, bool IsZero, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
getShuffleVectorZeroOrUndef - Return a vector_shuffle of the specified vector of zero or undef vector. This produces a shuffle where the low element of V2 is swizzled into the zero/undef vector, landing at element Idx. This produces a shuffle mask like 4,1,2,3 (idx=0) or 0,1,2,4 (idx=3).
Definition at line 5350 of file X86ISelLowering.cpp.
References llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), getZeroVector(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::X86TargetLowering::BuildFILD(), and getTargetVShiftNode().
static unsigned getShuffleVPERM2X128Immediate (ShuffleVectorSDNode * SVOp) static
getShuffleVPERM2X128Immediate - Return the appropriate immediate to shuffle the specified VECTOR_MASK mask with VPERM2F128/VPERM2I128 instructions.
Definition at line 4579 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getSimpleValueType(), and llvm::MVT::getVectorNumElements().
static bool getTargetShuffleMask (SDNode * N, MVT VT, SmallVectorImpl< int > & Mask, bool & IsUnary) static
getTargetShuffleMask - Calculates the shuffle mask corresponding to the target specific opcode. Returns true if the Mask could be calculated. Sets IsUnary to true if only uses one source. Note that this will set IsUnary for shuffles which use a single input multiple times, and in those cases it will adjust the mask to only have indices within that single input.
Definition at line 5370 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::X86ISD::BLENDI, llvm::ISD::BUILD_VECTOR, llvm::CallingConv::C, llvm::DecodeBLENDMask(), llvm::DecodeMOVHLPSMask(), llvm::DecodeMOVLHPSMask(), llvm::DecodeMOVSHDUPMask(), llvm::DecodeMOVSLDUPMask(), llvm::DecodePALIGNRMask(), llvm::DecodePSHUFBMask(), llvm::DecodePSHUFHWMask(), llvm::DecodePSHUFLWMask(), llvm::DecodePSHUFMask(), llvm::DecodeSHUFPMask(), llvm::DecodeUNPCKHMask(), llvm::DecodeUNPCKLMask(), llvm::DecodeVPERM2X128Mask(), llvm::DecodeVPERMMask(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::APInt::getLoBits(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::APInt::getZExtValue(), llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm_unreachable, llvm::APInt::lshr(), llvm::X86ISD::MOVDDUP, llvm::X86ISD::MOVHLPS, llvm::X86ISD::MOVLHPD, llvm::X86ISD::MOVLHPS, llvm::X86ISD::MOVLPD, llvm::X86ISD::MOVLPS, llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::X86ISD::MOVSS, llvm::X86ISD::PALIGNR, llvm::X86ISD::PSHUFB, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::X86ISD::SHUFP, llvm::SM_SentinelUndef, llvm::ISD::UNDEF, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::X86ISD::VPERM2X128, llvm::X86ISD::VPERMI, llvm::X86ISD::VPERMILPI, and llvm::X86ISD::Wrapper.
Referenced by combineX86ShufflesRecursively(), getPSHUFShuffleMask(), getShuffleScalarElt(), and XFormVExtractWithShuffleIntoLoad().
static SDValue getTargetShuffleNode (unsigned Opc, SDLoc dl, EVT VT, SDValue V1, SelectionDAG & DAG) static
Definition at line 3615 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm_unreachable, llvm::X86ISD::MOVDDUP, llvm::X86ISD::MOVSHDUP, and llvm::X86ISD::MOVSLDUP.
Referenced by llvm::X86TargetLowering::BuildFILD(), getMOVDDup(), getMOVHighToLow(), getMOVLowToHigh(), getMOVLP(), LowerShift(), and LowerVECTOR_SHUFFLEv8i16().
static SDValue getTargetShuffleNode (unsigned Opc, SDLoc dl, EVT VT, SDValue V1, unsigned TargetMask, SelectionDAG & DAG) static
Definition at line 3626 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i8, llvm_unreachable, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::X86ISD::VPERMI, and llvm::X86ISD::VPERMILPI.
static SDValue getTargetShuffleNode (unsigned Opc, SDLoc dl, EVT VT, SDValue V1, SDValue V2, unsigned TargetMask, SelectionDAG & DAG) static
Definition at line 3640 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i8, llvm_unreachable, llvm::X86ISD::PALIGNR, llvm::X86ISD::SHUFP, llvm::X86ISD::VALIGN, and llvm::X86ISD::VPERM2X128.
static SDValue getTargetShuffleNode (unsigned Opc, SDLoc dl, EVT VT, SDValue V1, SDValue V2, SelectionDAG & DAG) static
Definition at line 3654 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm_unreachable, llvm::X86ISD::MOVHLPS, llvm::X86ISD::MOVLHPD, llvm::X86ISD::MOVLHPS, llvm::X86ISD::MOVLPD, llvm::X86ISD::MOVLPS, llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSS, llvm::X86ISD::UNPCKH, and llvm::X86ISD::UNPCKL.
static SDValue getTargetVShiftByConstNode (unsigned Opc, SDLoc dl, MVT VT, SDValue SrcOp, uint64_t ShiftAmt, SelectionDAG & DAG) static
Definition at line 16792 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::i8, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::UNDEF, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRAI, and llvm::X86ISD::VSRLI.
Referenced by getTargetVShiftNode(), LowerMUL(), LowerScalarImmediateShift(), and LowerShift().
static SDValue getTargetVShiftNode (unsigned Opc, SDLoc dl, MVT VT, SDValue SrcOp, SDValue ShAmt, SelectionDAG & DAG) static
Definition at line 16868 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getShuffleVectorZeroOrUndef(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::TargetMachine::getSubtarget(), llvm::SelectionDAG::getTarget(), getTargetVShiftByConstNode(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i64, llvm_unreachable, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::X86ISD::VSHL, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRA, llvm::X86ISD::VSRAI, llvm::X86ISD::VSRL, llvm::X86ISD::VSRLI, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerINTRINSIC_WO_CHAIN(), and LowerScalarVariableShift().
static SDValue GetTLSADDR (SelectionDAG & DAG, SDValue Chain, GlobalAddressSDNode * GA, SDValue * InFlag, const EVT PtrVT, unsigned ReturnReg, unsigned char OperandFlags, bool LocalDynamic = false) static
Definition at line 13363 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getCopyFromReg(), llvm::MachineFunction::getFrameInfo(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::TLSModel::LocalDynamic, llvm::MVT::Other, llvm::MachineFrameInfo::setAdjustsStack(), llvm::MachineFrameInfo::setHasCalls(), llvm::X86ISD::TLSADDR, and llvm::X86ISD::TLSBASEADDR.
Referenced by LowerToTLSGeneralDynamicModel32(), LowerToTLSGeneralDynamicModel64(), and LowerToTLSLocalDynamicModel().
static int getUnderlyingExtractedFromVec (SDValue & ExtractedFromVec, SDValue ExtIdx) static
For an EXTRACT_VECTOR_ELT with a constant index return the real underlying vector and index.
Modifies ExtractedFromVec to the real vector and returns the real index.
Definition at line 6283 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), and isUndefOrInRange().
Referenced by buildFromShuffleMostly().
static SDValue getUnpackh (SelectionDAG & DAG, SDLoc dl, MVT VT, SDValue V1, SDValue V2) static
getUnpackh - Returns a vector_shuffle node for an unpackh operation.
Definition at line 5249 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by LowerAVXExtend(), and PromoteSplati8i16().
static SDValue getUnpackl (SelectionDAG & DAG, SDLoc dl, MVT VT, SDValue V1, SDValue V2) static
getUnpackl - Returns a vector_shuffle node for an unpackl operation.
Definition at line 5237 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::X86TargetLowering::BuildFILD(), LowerAVXExtend(), and PromoteSplati8i16().
static SDValue getV4X86ShuffleImm8ForMask (ArrayRef< int > Mask, SelectionDAG & DAG) static
Get a 4-lane 8-bit shuffle immediate for a mask.
This helper function produces an 8-bit shuffle immediate corresponding to the ubiquitous shuffle encoding scheme used in x86 instructions for shuffling 4 lanes. It can be used with most of the PSHUF instructions for example.
NB: We rely heavily on "undef" masks preserving the input lane.
Definition at line 7397 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getConstant(), llvm::MVT::i8, and llvm::ArrayRef< T >::size().
Referenced by combineRedundantDWordShuffle(), combineRedundantHalfShuffle(), lowerV2I64VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), lowerV8I32VectorShuffle(), lowerVectorShuffleAsSpecificZeroOrAnyExtend(), lowerVectorShuffleWithSHUFPS(), and PerformTargetShuffleCombine().
static SDValue getVectorMaskingNode (SDValue Op, SDValue Mask, SDValue PreservedSrc, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Return (and Op, Mask) for compare instructions or (vselect Mask, Op, PreservedSrc) for others along with the necessary casting for Mask when lowering masking intrinsics.
Definition at line 16922 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::X86ISD::CMPM, llvm::X86ISD::CMPMU, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getZeroVector(), llvm::MVT::i1, isAllOnes(), llvm::EVT::isSimple(), llvm::X86ISD::PCMPEQM, llvm::X86ISD::PCMPGTM, llvm::ISD::UNDEF, and llvm::ISD::VSELECT.
Referenced by LowerINTRINSIC_WO_CHAIN().
static SDValue getVShift (bool isLeft, EVT VT, SDValue SrcOp, unsigned NumBits, SelectionDAG & DAG, const TargetLowering & TLI, SDLoc dl) static
getVShift - Return a vector logical shift node.
Definition at line 5929 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getScalarShiftAmountTy(), llvm::SDValue::getValueType(), llvm::EVT::is128BitVector(), llvm::MVT::v2i64, llvm::X86ISD::VSHLDQ, and llvm::X86ISD::VSRLDQ.
static SDValue getVZextMovL (MVT VT, MVT OpVT, SDValue SrcOp, SelectionDAG & DAG, const X86Subtarget * Subtarget, SDLoc dl) static
getVZextMovL - Return a zero-extending vector move low node.
Definition at line 11654 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), isScalarLoadToVector(), llvm::AArch64DB::LD, llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, and llvm::X86ISD::VZEXT_MOVL.
Referenced by NormalizeVectorShuffle().
static SDValue getZeroVector (EVT VT, const X86Subtarget * Subtarget, SelectionDAG & DAG, SDLoc dl) static
getZeroVector - Returns a vector of specified type with all zero elements.
Definition at line 5145 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i32, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::EVT::is512BitVector(), llvm::EVT::isVector(), llvm_unreachable, llvm::MVT::v16i32, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8f32, and llvm::MVT::v8i32.
Referenced by getGatherNode(), getScalarMaskingNode(), getShuffleVectorZeroOrUndef(), getVectorMaskingNode(), LowerAVXExtend(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), LowerBuildVectorv8i16(), LowerScalarImmediateShift(), lowerV16I8VectorShuffle(), lowerVectorShuffleAsSpecificZeroOrAnyExtend(), LowerVSETCC(), NormalizeVectorShuffle(), performShiftToAllZeros(), and PerformShuffleCombine256().
static bool hasFPCMov (unsigned X86CC) static
hasFPCMov - is there a floating point cmov for the specific X86 condition code. Current x86 isa includes the following FP cmov instructions: fcmovb, fcomvbe, fcomve, fcmovu, fcmovae, fcmova, fcmovne, fcmovnu.
Definition at line 3849 of file X86ISelLowering.cpp.
References llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::X86::COND_NP, and llvm::X86::COND_P.
Referenced by PerformCMOVCombine().
static bool hasMFENCE (const X86Subtarget & Subtarget) static
Definition at line 19154 of file X86ISelLowering.cpp.
References llvm::X86Subtarget::hasSSE2(), and llvm::X86Subtarget::is64Bit().
Referenced by LowerATOMIC_FENCE().
static bool hasNonFlagsUse (SDValue Op) static
return true if Op has a use that doesn't just read flags.
Definition at line 14763 of file X86ISelLowering.cpp.
References llvm::ISD::BRCOND, llvm::SDNode::getOpcode(), llvm::SDNode::use_iterator::getOperandNo(), llvm::SDNode::hasOneUse(), llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
static SDValue Insert128BitVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, SDLoc dl) static
Generate a DAG to put 128-bits into a vector > 128 bits. This sets things up to match to an AVX VINSERTF128/VINSERTI128 or AVX-512 VINSERTF32x4/VINSERTI32x4 instructions or a simple superregister reference. Idx is an index in the 128 bits we want. It need not be aligned to a 128-bit boundary. That makes lowering INSERT_VECTOR_ELT operations easier.
Definition at line 174 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getValueType(), InsertSubVector(), and llvm::EVT::is128BitVector().
Referenced by Concat128BitVectors(), LowerINSERT_SUBVECTOR(), LowerSCALAR_TO_VECTOR(), PerformLOADCombine(), and PerformShuffleCombine256().
static SDValue Insert256BitVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, SDLoc dl) static
Definition at line 180 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getValueType(), InsertSubVector(), and llvm::EVT::is256BitVector().
Referenced by Concat256BitVectors(), and LowerINSERT_SUBVECTOR().
static SDValue InsertSubVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, SDLoc dl, unsigned vectorWidth) static
Definition at line 144 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::ISD::INSERT_SUBVECTOR, and llvm::ISD::UNDEF.
Referenced by Insert128BitVector(), and Insert256BitVector().
static bool is128BitLaneCrossingShuffleMask (MVT VT, ArrayRef< int > Mask) static
Test whether there are elements crossing 128-bit lanes in this shuffle mask.
X86 divides up its shuffles into in-lane and cross-lane shuffle operations and we routinely test for these.
Definition at line 7311 of file X86ISelLowering.cpp.
References llvm::MVT::getScalarSizeInBits(), and llvm::ArrayRef< T >::size().
Referenced by lowerV16I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F64VectorShuffle(), lowerV8F32VectorShuffle(), and lowerVectorShuffleByMerging128BitLanes().
static bool is128BitLaneRepeatedShuffleMask (MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > & RepeatedMask) static
Test whether a shuffle mask is equivalent within each 128-bit lane.
This checks a shuffle mask to see if it is performing the same 128-bit lane-relative shuffle in each 128-bit lane. This trivially implies that it is also not lane-crossing. It may however involve a blend from the same lane of a second vector.
The specific repeated shuffle mask is populated in RepeatedMask, as it is non-trivial to compute in the face of undef lanes. The representation is not suitable for use with existing 128-bit shuffles as it will contain entries from both V1 and V2 inputs to the wider mask.
Definition at line 7332 of file X86ISelLowering.cpp.
References llvm::MVT::getScalarSizeInBits(), llvm::SmallVectorImpl< T >::resize(), and llvm::ArrayRef< T >::size().
Referenced by lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I32VectorShuffle(), and lowerVectorShuffleAsBlend().
static bool isAlignrMask (ArrayRef< int > Mask, MVT VT, bool InterLane) static
Return true if the mask specifies a shuffle of elements that is suitable for input to intralane (palignr) or interlane (valign) vector right-shift.
Definition at line 4022 of file X86ISelLowering.cpp.
References llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), isUndefOrEqual(), and isUndefOrInRange().
Referenced by isPALIGNRMask(), and isVALIGNMask().
static bool isAllOnes (SDValue V) static
Definition at line 15138 of file X86ISelLowering.cpp.
References llvm::dyn_cast(), and llvm::ConstantSDNode::isAllOnesValue().
Referenced by getScalarMaskingNode(), getVectorMaskingNode(), LowerINTRINSIC_W_CHAIN(), and LowerINTRINSIC_WO_CHAIN().
static bool isAndOrOfSetCCs (SDValue Op, unsigned & Opc) static
Definition at line 16234 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::hasOneUse(), llvm::ISD::OR, and llvm::X86ISD::SETCC.
Referenced by CMPEQCombine().
static bool isBlendMask (ArrayRef< int > MaskVals, MVT VT, bool hasSSE41, bool hasInt256, unsigned * MaskOut = nullptr) static
Definition at line 11059 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::i8, llvm::MVT::is512BitVector(), and llvm::MVT::v16i16.
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal(), llvm::X86TargetLowering::isVectorClearMaskLegal(), and LowerVECTOR_SHUFFLEtoBlend().
static bool IsCCallConvention (CallingConv::ID CC) static
Return true if the calling convention is a C calling convention.
Definition at line 2298 of file X86ISelLowering.cpp.
References llvm::CallingConv::C, llvm::CallingConv::X86_64_SysV, and llvm::CallingConv::X86_64_Win64.
static bool isCommutedMOVLMask (ArrayRef< int > Mask, MVT VT, bool V2IsSplat = false, bool V2IsUndef = false) static
isCommutedMOVLMask - Returns true if the shuffle mask is except the reverse of what x86 movss want. X86 movs requires the lowest element to be lowest element of vector 2 and the other elements to come from vector 1 in order.
Definition at line 4678 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), isUndefOrEqual(), and isUndefOrInRange().
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal(), llvm::X86TargetLowering::isVectorClearMaskLegal(), and NormalizeVectorShuffle().
static bool isHorizontalBinOp (const BuildVectorSDNode * N, unsigned Opcode, SelectionDAG & DAG, unsigned BaseIdx, unsigned LastIdx, SDValue & V0, SDValue & V1) static
Return true if N implements a horizontal binop and return the operands for the horizontal binop into V0 and V1.
This is a helper function of PerformBUILD_VECTORCombine. This function checks that the build_vector N in input implements a horizontal operation. Parameter Opcode defines the kind of horizontal operation to match. For example, if Opcode is equal to ISD::ADD, then this function checks if N implements a horizontal arithmetic add; if instead Opcode is equal to ISD::SUB, then this function checks if this is a horizontal arithmetic sub.
This function only analyzes elements of N whose indices are in range [BaseIdx, LastIdx).
Definition at line 6478 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SDNode::hasOneUse(), llvm::EVT::isVector(), and llvm::ISD::UNDEF.
Referenced by PerformAddCombine(), PerformBUILD_VECTORCombine(), PerformFADDCombine(), PerformFSUBCombine(), and PerformSubCombine().
static bool isHorizontalBinOp (SDValue & LHS, SDValue & RHS, bool IsCommutative) static
Return 'true' if this vector operation is "horizontal" and return the operands for the horizontal operation in LHS and RHS. A horizontal operation performs the binary operation on successive elements of its first operand, then on successive elements of its second operand, returning the resulting values in a vector. For example, if A = < float a0, float a1, float a2, float a3 > and B = < float b0, float b1, float b2, float b3 > then the result of doing a horizontal operation on A and B is A horizontal-op B = < a0 op a1, a2 op a3, b0 op b1, b2 op b3 >. In short, LHS and RHS are inspected to see if LHS op RHS is of the form A horizontal-op B, for some already available A and B, and if so then LHS is set to A, RHS to B, and the routine returns 'true'. Note that the binary operation should have the property that if one of the operands is UNDEF then the result is UNDEF.
Definition at line 25144 of file X86ISelLowering.cpp.
References llvm::ARM_PROC::A, assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ArrayRef< T >::begin(), llvm::CallingConv::C, CommuteVectorShuffleMask(), llvm::ArrayRef< T >::end(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::ISD::UNDEF, and llvm::ISD::VECTOR_SHUFFLE.
static bool isINSERT64x4Mask (ArrayRef< int > Mask, MVT VT, unsigned int * Imm) static
Definition at line 4500 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is512BitVector(), and isSequentialOrUndefInRange().
static bool isINSERTPSMask (ArrayRef< int > Mask, MVT VT) static
isINSERTPSMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to INSERTPS. i. e: If all but one element come from the same vector.
Definition at line 4270 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isMOVDDUPMask (ArrayRef< int > Mask, MVT VT) static
isMOVDDUPMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to 128-bit version of MOVDDUP.
Definition at line 4770 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), and isUndefOrEqual().
static bool isMOVDDUPYMask (ArrayRef< int > Mask, MVT VT, bool HasFp256) static
isMOVDDUPYMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to 256-bit version of MOVDDUP.
Definition at line 4750 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is256BitVector(), and isUndefOrEqual().
static bool isMOVHLPS_v_undef_Mask (ArrayRef< int > Mask, MVT VT) static
isMOVHLPS_v_undef_Mask - Special case of isMOVHLPSMask for canonical form of vector_shuffle v, v, <2, 3, 2, 3>, i.e. vector_shuffle v, undef, <2, 3, 2, 3>
Definition at line 4208 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), and isUndefOrEqual().
static bool isMOVHLPSMask (ArrayRef< int > Mask, MVT VT) static
isMOVHLPSMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to MOVHLPS.
Definition at line 4189 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), and isUndefOrEqual().
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isMOVLHPSMask (ArrayRef< int > Mask, MVT VT) static
isMOVLHPSMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to MOVLHPS.
Definition at line 4247 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), and isUndefOrEqual().
static bool isMOVLMask (ArrayRef< int > Mask, EVT VT) static
isMOVLMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to MOVSS, MOVSD, and MOVD, i.e. setting the lowest element.
Definition at line 4524 of file X86ISelLowering.cpp.
References llvm::EVT::getSizeInBits(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::is128BitVector(), and isUndefOrEqual().
Referenced by getMOVLP(), llvm::X86TargetLowering::isShuffleMaskLegal(), llvm::X86TargetLowering::isVectorClearMaskLegal(), and NormalizeVectorShuffle().
static bool isMOVLPMask (ArrayRef< int > Mask, MVT VT) static
isMOVLPMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to MOVLP{S|D}.
Definition at line 4225 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), and isUndefOrEqual().
static bool isMOVSHDUPMask (ArrayRef< int > Mask, MVT VT, const X86Subtarget * Subtarget) static
isMOVSHDUPMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to MOVSHDUP. Masks to match: <1, 1, 3, 3> or <1, 1, 3, 3, 5, 5, 7, 7>
Definition at line 4702 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasSSE3(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), and isUndefOrEqual().
static bool isMOVSLDUPMask (ArrayRef< int > Mask, MVT VT, const X86Subtarget * Subtarget) static
isMOVSLDUPMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to MOVSLDUP. Masks to match: <0, 0, 2, 2> or <0, 0, 2, 2, 4, 4, 6, 6>
Definition at line 4726 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasSSE3(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), and isUndefOrEqual().
static bool isNoopShuffleMask (ArrayRef< int > Mask) static
Tiny helper function to identify a no-op mask.
This is a somewhat boring predicate function. It checks whether the mask array input, which is assumed to be a single-input shuffle mask of the kind used by the X86 shuffle instructions (not a fully general ShuffleVectorSDNode mask) requires any shuffles to occur. Both undef and an in-place shuffle are 'no-op's.
Definition at line 7284 of file X86ISelLowering.cpp.
References llvm::ArrayRef< T >::size().
Referenced by lowerV8I16SingleInputVectorShuffle(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsByteShift(), lowerVectorShuffleAsElementInsertion(), and PerformTargetShuffleCombine().
static bool isPALIGNRMask (ArrayRef< int > Mask, MVT VT, const X86Subtarget * Subtarget) static
Return true if the node specifies a shuffle of elements that is suitable for input to PALIGNR.
Definition at line 4090 of file X86ISelLowering.cpp.
References llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), and isAlignrMask().
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isPermImmMask (ArrayRef< int > Mask, MVT VT, unsigned & Imm8) static
Definition at line 4602 of file X86ISelLowering.cpp.
References llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), and isUndefOrInRange().
static bool isPSHUFDMask (ArrayRef< int > Mask, MVT VT, bool TestSecondOperand = false) static
isPSHUFDMask - Return true if the node specifies a shuffle of elements that is suitable for input to PSHUFD. That is, it doesn't reference the other operand - by default will match for first operand.
Definition at line 3944 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::HexagonISD::Hi, isUndefOrInRange(), llvm::HexagonISD::Lo, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isPSHUFHWMask (ArrayRef< int > Mask, MVT VT, bool HasInt256) static
isPSHUFHWMask - Return true if the node specifies a shuffle of elements that is suitable for input to PSHUFHW.
Definition at line 3963 of file X86ISelLowering.cpp.
References isSequentialOrUndefInRange(), isUndefOrInRange(), llvm::MVT::v16i16, and llvm::MVT::v8i16.
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isPSHUFLWMask (ArrayRef< int > Mask, MVT VT, bool HasInt256) static
isPSHUFLWMask - Return true if the node specifies a shuffle of elements that is suitable for input to PSHUFLW.
Definition at line 3992 of file X86ISelLowering.cpp.
References isSequentialOrUndefInRange(), isUndefOrInRange(), llvm::MVT::v16i16, and llvm::MVT::v8i16.
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isScalarLoadToVector (SDNode * N, LoadSDNode ** LD = nullptr) static
isScalarLoadToVector - Returns true if the node is a scalar load that is promoted to a vector. It also returns the LoadSDNode by reference if required.
Definition at line 5051 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ISD::isNON_EXTLoad(), llvm::AArch64DB::LD, N, and llvm::ISD::SCALAR_TO_VECTOR.
Referenced by getVZextMovL(), and ShouldXformToMOVLP().
static bool isSequentialOrUndefInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size, int Low) static
isSequentialOrUndefInRange - Return true if every element in Mask, beginning from position Pos and ending in Pos+Size, falls within the specified sequential range (Low, Low+Size]. or is undef.
Definition at line 3933 of file X86ISelLowering.cpp.
References isUndefOrEqual().
Referenced by isINSERT64x4Mask(), isPSHUFHWMask(), isPSHUFLWMask(), isVPERM2X128Mask(), and lowerVectorShuffleAsByteShift().
static bool isShuffleFoldableLoad (SDValue V) static
Helper to test for a load that can be folded with x86 shuffles.
This is particularly important because the set of instructions varies significantly based on whether the operand is a load or not.
Definition at line 7982 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), and llvm::ISD::isNON_EXTLoad().
Referenced by lowerV2F64VectorShuffle(), and lowerVectorShuffleAsBroadcast().
static bool isShuffleHigh128VectorInsertLow (ShuffleVectorSDNode * SVOp) static
isShuffleHigh128VectorInsertLow - Checks whether the shuffle node is the same as extracting the high 128-bit part of 256-bit vector and then inserting the result into the low part of a new 256-bit vector
Definition at line 21809 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), and isUndefOrEqual().
Referenced by PerformShuffleCombine256().
static bool isShuffleLow128VectorInsertHigh (ShuffleVectorSDNode * SVOp) static
isShuffleLow128VectorInsertHigh - Checks whether the shuffle node is the same as extracting the low 128-bit part of 256-bit vector and then inserting the result into the high part of a new 256-bit vector
Definition at line 21825 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), and isUndefOrEqual().
Referenced by PerformShuffleCombine256().
static bool isShuffleMaskConsecutive (ShuffleVectorSDNode * SVOp, unsigned MaskI, unsigned MaskE, unsigned OpIdx, unsigned NumElems, unsigned & OpNum) static
isShuffleMaskConsecutive - Check if the shuffle mask indicies [MaskI, MaskE) correspond consecutively to elements from one of the vector operands, starting from its index OpIdx. Also tell OpNum which source vector operand.
Definition at line 5626 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMaskElt().
Referenced by isVectorShiftLeft(), and isVectorShiftRight().
static bool isShuffleMaskInputInPlace (int Input, ArrayRef< int > Mask) static
Test whether the specified input (0 or 1) is in-place blended by the given mask.
This returns true if the elements from a particular input are already in the slot required by the given mask and require no permutation.
Definition at line 10208 of file X86ISelLowering.cpp.
References assert(), and llvm::ArrayRef< T >::size().
Referenced by lowerV4F64VectorShuffle(), and lowerV4I64VectorShuffle().
static bool isSHUFPMask (ArrayRef< int > Mask, MVT VT, bool Commuted = false) static
isSHUFPMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to 128/256-bit SHUFPS and SHUFPD. If Commuted is true, then it checks for sources to be reverse of what x86 shuffles want.
Definition at line 4130 of file X86ISelLowering.cpp.
References llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), and isUndefOrInRange().
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal(), and llvm::X86TargetLowering::isVectorClearMaskLegal().
static bool isSingleInputShuffleMask (ArrayRef< int > Mask) static
Helper function to classify a mask as a single-input mask.
This isn't a generic single-input test because in the vector shuffle lowering we canonicalize single inputs to be the first input operand. This means we can more quickly test for a single input by only checking whether an input from the second operand exists. We also assume that the size of mask corresponds to the size of the input vectors which isn't true in the fully general case.
Definition at line 7299 of file X86ISelLowering.cpp.
Referenced by canLowerByDroppingEvenElements(), lowerV16I16VectorShuffle(), lowerV16I8VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I32VectorShuffle(), lowerVectorShuffleAsLanePermuteAndBlend(), lowerVectorShuffleAsSplitOrBlend(), and lowerVectorShuffleByMerging128BitLanes().
static bool IsTailCallConvention (CallingConv::ID CC) static
Return true if the calling convention is one that supports tail call optimization.
Definition at line 2292 of file X86ISelLowering.cpp.
References llvm::CallingConv::Fast, llvm::CallingConv::GHC, and llvm::CallingConv::HiPE.
Referenced by FuncIsMadeTailCallSafe().
static bool isTargetShuffle (unsigned Opcode) static
Definition at line 3586 of file X86ISelLowering.cpp.
References llvm::X86ISD::BLENDI, llvm::X86ISD::MOVDDUP, llvm::X86ISD::MOVHLPS, llvm::X86ISD::MOVLHPD, llvm::X86ISD::MOVLHPS, llvm::X86ISD::MOVLPD, llvm::X86ISD::MOVLPS, llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::X86ISD::MOVSS, llvm::X86ISD::PALIGNR, llvm::X86ISD::PSHUFB, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::X86ISD::SHUFP, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::X86ISD::VPERM2X128, llvm::X86ISD::VPERMI, and llvm::X86ISD::VPERMILPI.
Referenced by combineX86ShufflesRecursively(), getShuffleScalarElt(), PerformShuffleCombine(), and XFormVExtractWithShuffleIntoLoad().
static bool isTruncWithZeroHighBitsInput (SDValue V, SelectionDAG & DAG) static
Definition at line 15699 of file X86ISelLowering.cpp.
References llvm::tgtok::Bits, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueSizeInBits(), llvm::SelectionDAG::MaskedValueIsZero(), and llvm::ISD::TRUNCATE.
static bool isUndefOrEqual (int Val, int CmpVal) static
isUndefOrEqual - Val is either less than zero (undef) or equal to the specified value.
Definition at line 3926 of file X86ISelLowering.cpp.
Referenced by Compact8x32ShuffleNode(), isAlignrMask(), isCommutedMOVLMask(), isMOVDDUPMask(), isMOVDDUPYMask(), isMOVHLPS_v_undef_Mask(), isMOVHLPSMask(), isMOVLHPSMask(), isMOVLMask(), isMOVLPMask(), isMOVSHDUPMask(), isMOVSLDUPMask(), isSequentialOrUndefInRange(), isShuffleHigh128VectorInsertLow(), isShuffleLow128VectorInsertHigh(), isUNPCKH_v_undef_Mask(), isUNPCKHMask(), isUNPCKL_v_undef_Mask(), isUNPCKLMask(), isVPERMILPMask(), PerformShuffleCombine256(), ShouldXformToMOVHLPS(), and ShouldXformToMOVLP().
static bool isUndefOrInRange (int Val, int Low, int Hi) static
isUndefOrInRange - Return true if Val is undef or if its value falls within the specified range (L, H].
Definition at line 3920 of file X86ISelLowering.cpp.
References llvm::HexagonISD::Hi.
Referenced by getUnderlyingExtractedFromVec(), isAlignrMask(), isCommutedMOVLMask(), isPermImmMask(), isPSHUFDMask(), isPSHUFHWMask(), isPSHUFLWMask(), isSHUFPMask(), and isVPERMILPMask().
static bool isUNPCKH_v_undef_Mask (ArrayRef< int > Mask, MVT VT, bool HasInt256) static
isUNPCKH_v_undef_Mask - Special case of isUNPCKHMask for canonical form of vector_shuffle v, v, <2, 6, 3, 7>, i.e. vector_shuffle v, undef, <2, 2, 3, 3>
Definition at line 4467 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), and isUndefOrEqual().
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isUNPCKHMask (ArrayRef< int > Mask, MVT VT, bool HasInt256, bool V2IsSplat = false) static
isUNPCKHMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to UNPCKH.
Definition at line 4386 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getScalarType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), and isUndefOrEqual().
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isUNPCKL_v_undef_Mask (ArrayRef< int > Mask, MVT VT, bool HasInt256) static
isUNPCKL_v_undef_Mask - Special case of isUNPCKLMask for canonical form of vector_shuffle v, v, <0, 4, 1, 5>, i.e. vector_shuffle v, undef, <0, 0, 1, 1>
Definition at line 4424 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), and isUndefOrEqual().
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isUNPCKLMask (ArrayRef< int > Mask, MVT VT, bool HasInt256, bool V2IsSplat = false) static
isUNPCKLMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to UNPCKL.
Definition at line 4347 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getScalarType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), and isUndefOrEqual().
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal().
static bool isVALIGNMask (ArrayRef< int > Mask, MVT VT, const X86Subtarget * Subtarget) static
Return true if the node specifies a shuffle of elements that is suitable for input to VALIGN.
Definition at line 4103 of file X86ISelLowering.cpp.
References llvm::X86Subtarget::hasAVX512(), llvm::MVT::is512BitVector(), and isAlignrMask().
static bool isVectorShift (ShuffleVectorSDNode * SVOp, SelectionDAG & DAG, bool & isLeft, SDValue & ShVal, unsigned & ShAmt) static
isVectorShift - Returns true if the shuffle can be implemented as a logical left or right shift of a vector.
Definition at line 5724 of file X86ISelLowering.cpp.
References llvm::SDNode::getSimpleValueType(), llvm::MVT::is128BitVector(), isVectorShiftLeft(), and isVectorShiftRight().
static bool isVectorShiftLeft (ShuffleVectorSDNode * SVOp, SelectionDAG & DAG, bool & isLeft, SDValue & ShVal, unsigned & ShAmt) static
isVectorShiftLeft - Returns true if the shuffle can be implemented as a logical left shift of a vector.
Definition at line 5689 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMaskElt(), getNumOfConsecutiveZeros(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getVectorNumElements(), and isShuffleMaskConsecutive().
Referenced by isVectorShift().
static bool isVectorShiftRight (ShuffleVectorSDNode * SVOp, SelectionDAG & DAG, bool & isLeft, SDValue & ShVal, unsigned & ShAmt) static
isVectorShiftRight - Returns true if the shuffle can be implemented as a logical left shift of a vector.
Definition at line 5654 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMaskElt(), getNumOfConsecutiveZeros(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getVectorNumElements(), and isShuffleMaskConsecutive().
Referenced by isVectorShift().
static bool isVEXTRACTIndex (SDNode * N, unsigned vecWidth) static
isVEXTRACTIndex - Return true if the specified EXTRACT_SUBVECTOR operand specifies a vector extract that is suitable for instruction that extract 128 or 256 bit vectors
Definition at line 4787 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), and llvm::MVT::getVectorElementType().
Referenced by llvm::X86::isVEXTRACT128Index(), and llvm::X86::isVEXTRACT256Index().
static bool isVINSERTIndex (SDNode * N, unsigned vecWidth) static
isVINSERTIndex - Return true if the specified INSERT_SUBVECTOR operand specifies a subvector insert that is suitable for input to insertion of 128 or 256-bit subvectors
Definition at line 4806 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), and llvm::MVT::getVectorElementType().
Referenced by llvm::X86::isVINSERT128Index(), and llvm::X86::isVINSERT256Index().
static bool isVPERM2X128Mask (ArrayRef< int > Mask, MVT VT, bool HasFp256) static
isVPERM2X128Mask - Match 256-bit shuffles where the elements are considered as permutations between 128-bit chunks or halves. As an example: this shuffle bellow: vector_shuffle <4, 5, 6, 7, 12, 13, 14, 15> The first half comes from the second half of V1 and the second half from the the second half of V2.
Definition at line 4548 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is256BitVector(), and isSequentialOrUndefInRange().
static bool isVPERMILPMask (ArrayRef< int > Mask, MVT VT) static
isVPERMILPMask - Return true if the specified VECTOR_SHUFFLE operand specifies a shuffle of elements that is suitable for input to VPERMILPD*. Note that VPERMIL mask matching is different depending whether theunderlying type is 32 or 64. In the VPERMILPS the high half of the mask should point to the same elements of the low, but to the higher half of the source. In VPERMILPD the two lanes could be shuffled independently of each other with the same restriction that lanes can't be crossed. Also handles PSHUFDY.
Definition at line 4646 of file X86ISelLowering.cpp.
References llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), isUndefOrEqual(), and isUndefOrInRange().
static bool isX86CCUnsigned (unsigned X86CC) static
Return true if the condition is an unsigned comparison operation.
Definition at line 3741 of file X86ISelLowering.cpp.
References llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NE, and llvm_unreachable.
static bool isX86LogicalCmp (SDValue Op) static
Definition at line 15674 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADC, llvm::X86ISD::ADD, llvm::X86ISD::AND, llvm::X86ISD::CMP, llvm::X86ISD::COMI, llvm::X86ISD::DEC, llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getResNo(), llvm::X86ISD::INC, llvm::X86ISD::OR, llvm::X86ISD::SAHF, llvm::X86ISD::SBB, llvm::X86ISD::SMUL, llvm::X86ISD::SUB, llvm::X86ISD::UCOMI, llvm::X86ISD::UMUL, and llvm::X86ISD::XOR.
static bool isXor1OfSetCC (SDValue Op) static
Definition at line 16246 of file X86ISelLowering.cpp.
References llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::hasOneUse(), llvm::X86ISD::SETCC, and llvm::ISD::XOR.
static bool isZero (SDValue V) static
isZero - Returns true if Elt is a constant integer zero
Definition at line 5015 of file X86ISelLowering.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), and llvm::ConstantSDNode::isNullValue().
Referenced by BUILD_VECTORtoBlendMask(), and llvm::X86::isZeroNode().
static bool isZeroShuffle (ShuffleVectorSDNode * N) static
isZeroShuffle - Returns true if N is a VECTOR_SHUFFLE that can be resolved to an zero vector. FIXME: move to dag combiner / method on ShuffleVectorSDNode
Definition at line 5118 of file X86ISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::isBuildVectorAllZeros(), llvm::X86::isZeroNode(), llvm::ISD::UNDEF, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by NormalizeVectorShuffle().
static SDValue lower128BitVectorShuffle (SDValue Op, SDValue V1, SDValue V2, MVT VT, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Dispatching routine to lower various 128-bit x86 vector shuffles.
This routine breaks down the specific type of 128-bit shuffle and dispatches to the lowering routines accordingly.
Definition at line 9796 of file X86ISelLowering.cpp.
References llvm_unreachable, lowerV16I8VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4I32VectorShuffle(), lowerV8I16VectorShuffle(), llvm::MVT::SimpleTy, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by lowerVectorShuffle().
static SDValue lower256BitVectorShuffle (SDValue Op, SDValue V1, SDValue V2, MVT VT, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
High-level routine to lower various 256-bit x86 vector shuffles.
This routine either breaks down the specific type of a 256-bit x86 vector shuffle or splits it into two 128-bit shuffles and fuses the results back together based on the available instructions.
Definition at line 10700 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, DL, llvm::MVT::getFloatingPointVT(), llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::isInteger(), llvm_unreachable, lowerV16I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I32VectorShuffle(), llvm::MVT::SimpleTy, splitAndLowerVectorShuffle(), llvm::MVT::v16i16, llvm::MVT::v32i8, llvm::MVT::v4f64, llvm::MVT::v4i64, llvm::MVT::v8f32, and llvm::MVT::v8i32.
Referenced by lowerVectorShuffle().
static SDValue Lower256IntArith (SDValue Op, SelectionDAG & DAG) static
Definition at line 18156 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, Extract128BitVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::is256BitVector(), and llvm::MVT::isInteger().
Referenced by LowerADD(), LowerMUL(), and LowerSUB().
static SDValue Lower256IntVSETCC (SDValue Op, SelectionDAG & DAG) static
Definition at line 15261 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, Extract128BitVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::is256BitVector(), and llvm::ISD::SETCC.
Referenced by LowerVSETCC().
static SDValue lower512BitVectorShuffle (SDValue Op, SDValue V1, SDValue V2, MVT VT, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
High-level routine to lower various 512-bit x86 vector shuffles.
This routine either breaks down the specific type of a 512-bit x86 vector shuffle or splits it into two 256-bit shuffles and fuses the results back together based on the available instructions.
Definition at line 10877 of file X86ISelLowering.cpp.
References assert(), DL, llvm::ShuffleVectorSDNode::getMask(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm_unreachable, lowerV16F32VectorShuffle(), lowerV16I32VectorShuffle(), lowerV32I16VectorShuffle(), lowerV64I8VectorShuffle(), lowerV8F64VectorShuffle(), lowerV8I64VectorShuffle(), lowerVectorShuffleAsBroadcast(), llvm::MVT::SimpleTy, splitAndLowerVectorShuffle(), llvm::MVT::v16f32, llvm::MVT::v16i32, llvm::MVT::v32i16, llvm::MVT::v64i8, llvm::MVT::v8f64, and llvm::MVT::v8i64.
Referenced by lowerVectorShuffle().
static SDValue LowerADD (SDValue Op, SelectionDAG & DAG) static
Definition at line 18183 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::MVT::is256BitVector(), llvm::MVT::isInteger(), and Lower256IntArith().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerADDC_ADDE_SUBC_SUBE (SDValue Op, SelectionDAG & DAG) static
Definition at line 19521 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADC, llvm::X86ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getVTList(), llvm::TargetLoweringBase::isTypeLegal(), llvm_unreachable, llvm::X86ISD::SBB, llvm::X86ISD::SUB, llvm::ISD::SUBC, and llvm::ISD::SUBE.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerADJUST_TRAMPOLINE (SDValue Op, SelectionDAG & DAG) static
Definition at line 17853 of file X86ISelLowering.cpp.
References llvm::SDValue::getOperand().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerANY_EXTEND (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 14302 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::X86Subtarget::hasFp256(), and LowerAVXExtend().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerAsSplatVectorLoad (SDValue SrcOp, MVT VT, SDLoc dl, SelectionDAG & DAG) static
Definition at line 5943 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MVT::i32, llvm::SelectionDAG::InferPtrAlignment(), llvm::SelectionDAG::isBaseWithConstantOffset(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::ISD::isNormalLoad(), llvm::AArch64DB::LD, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::MachineFrameInfo::setObjectAlignment().
static SDValue LowerATOMIC_FENCE (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 19222 of file X86ISelLowering.cpp.
References llvm::CrossThread, llvm::N86::ESP, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), hasMFENCE(), llvm::MVT::i8, llvm::X86ISD::MEMBARRIER, llvm::X86ISD::MFENCE, llvm::MVT::Other, and llvm::SequentiallyConsistent.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerATOMIC_STORE (SDValue Op, SelectionDAG & DAG) static
Definition at line 19496 of file X86ISelLowering.cpp.
References llvm::ISD::ATOMIC_SWAP, llvm::SelectionDAG::getAtomic(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::TargetLoweringBase::isTypeLegal(), Node, and llvm::SequentiallyConsistent.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerAVXCONCAT_VECTORS (SDValue Op, SelectionDAG & DAG) static
Definition at line 7228 of file X86ISelLowering.cpp.
References assert(), Concat128BitVectors(), Concat256BitVectors(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::NVPTX::PTXLdStInstCode::V2, and llvm::NVPTX::PTXLdStInstCode::V4.
Referenced by LowerCONCAT_VECTORS().
static SDValue LowerAVXExtend (SDValue Op, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 14228 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), getUnpackh(), getUnpackl(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasInt256(), llvm::RegState::Undef, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::X86ISD::VZEXT, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerANY_EXTEND(), and LowerZERO_EXTEND().
static SDValue LowerBITCAST (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 19296 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasMMX(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), llvm::MVT::isVector(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MVT::v2f64, llvm::MVT::v2i32, llvm::MVT::v4i16, and llvm::MVT::v8i8.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerBuildVectorv16i8 (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG & DAG, const X86Subtarget * Subtarget, const TargetLowering & TLI) static
LowerBuildVectorv16i8 - Custom lower build_vector of v16i8.
Definition at line 5740 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getUNDEF(), getZeroVector(), llvm::MVT::i16, llvm::MVT::i8, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::OR, llvm::ISD::SHL, llvm::MVT::v16i8, llvm::MVT::v8i16, and llvm::ISD::ZERO_EXTEND.
static SDValue LowerBuildVectorv4x32 (SDValue Op, SelectionDAG & DAG, const X86Subtarget * Subtarget, const TargetLowering & TLI) static
LowerBuildVectorv4x32 - Custom lower build_vector of v4i32 or v4f32.
Definition at line 5819 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getVectorShuffle(), getZeroVector(), llvm::X86Subtarget::hasSSE41(), llvm::X86ISD::INSERTPS, llvm::MVT::is128BitVector(), llvm::X86::isZeroNode(), llvm::ISD::UNDEF, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::MVT::v4f32.
static SDValue LowerBuildVectorv8i16 (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG & DAG, const X86Subtarget * Subtarget, const TargetLowering & TLI) static
LowerBuildVectorv8i16 - Custom lower build_vector of v8i16.
Definition at line 5788 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getUNDEF(), getZeroVector(), llvm::ISD::INSERT_VECTOR_ELT, and llvm::MVT::v8i16.
static SDValue LowerCMP_SWAP (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 19255 of file X86ISelLowering.cpp.
References llvm::AArch64CC::AL, assert(), llvm::X86::COND_E, llvm::N86::EAX, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm::X86ISD::LCMPXCHG_DAG, llvm_unreachable, llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::X86ISD::SETCC, llvm::MVT::SimpleTy, Success, and T.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerCONCAT_VECTORS (SDValue Op, SelectionDAG & DAG) static
Definition at line 7252 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNumOperands(), llvm::SDValue::getSimpleValueType(), LLVM_ATTRIBUTE_UNUSED, and LowerAVXCONCAT_VECTORS().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerCTLZ (SDValue Op, SelectionDAG & DAG) static
Definition at line 18075 of file X86ISelLowering.cpp.
References llvm::X86ISD::BSR, llvm::X86ISD::CMOV, llvm::X86::COND_E, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::TRUNCATE, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerCTLZ_ZERO_UNDEF (SDValue Op, SelectionDAG & DAG) static
Definition at line 18109 of file X86ISelLowering.cpp.
References llvm::X86ISD::BSR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::TRUNCATE, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerCTPOP (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 19348 of file X86ISelLowering.cpp.
References llvm::Add, llvm::ISD::ADD, llvm::ISD::AND, llvm::APIntOps::And(), assert(), llvm::SmallVectorImpl< T >::assign(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SmallVectorImpl< T >::clear(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), llvm::APInt::getSplat(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i32, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::EVT::isInteger(), llvm::ISD::SRL, llvm::Sub, llvm::ISD::SUB, llvm::MVT::v2i64, and llvm::MVT::v4i64.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerCTTZ (SDValue Op, SelectionDAG & DAG) static
Definition at line 18134 of file X86ISelLowering.cpp.
References llvm::X86ISD::BSF, llvm::X86ISD::CMOV, llvm::X86::COND_E, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), and llvm::MVT::i8.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerExtendedLoad (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 16035 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::BITCAST, llvm::ISD::EXTLOAD, llvm::MVT::f64, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getExtLoad(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumValues(), llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i8, llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::integer_valuetypes(), llvm::MVT::isInteger(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::isPowerOf2_32(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MVT::isVector(), llvm::SPII::Load, llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SEXTLOAD, llvm::ISD::SRA, llvm::ISD::TokenFactor, and llvm::X86ISD::VSEXT.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 13111 of file X86ISelLowering.cpp.
References Extract128BitVector(), Extract256BitVector(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasFp256(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), and llvm::MVT::is512BitVector().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerEXTRACT_VECTOR_ELT_SSE4 (SDValue Op, SelectionDAG & DAG) static
Definition at line 12744 of file X86ISelLowering.cpp.
References Assert, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::is128BitVector(), llvm::X86ISD::PEXTRB, llvm::X86ISD::PEXTRW, llvm::ISD::STORE, llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), and llvm::MVT::v4i32.
static SDValue LowerFABSorFNEG (SDValue Op, SelectionDAG & DAG) static
The only differences between FABS and FNEG are the mask and the logic op. FNEG also has a folding opportunity for FNEG(FABS(x)).
Definition at line 14525 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::MVT::f64, llvm::ISD::FABS, llvm::X86ISD::FAND, llvm::ISD::FNEG, llvm::X86ISD::FOR, llvm::X86ISD::FXOR, llvm::ConstantInt::get(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::APInt::getSignBit(), llvm::APInt::getSignedMaxValue(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::ConstantVector::getSplat(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i64, llvm::MVT::isVector(), llvm::ISD::OR, llvm::SDNode::uses(), and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerFCOPYSIGN (SDValue Op, SelectionDAG & DAG) static
Definition at line 14591 of file X86ISelLowering.cpp.
References llvm::lltok::APFloat, llvm::MVT::bitsGT(), llvm::MVT::bitsLT(), llvm::APFloat::clearSign(), llvm::MVT::f64, llvm::X86ISD::FAND, llvm::X86ISD::FOR, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ConstantFP::get(), llvm::ConstantVector::get(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getEntryNode(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEsingle, and llvm::APFloat::isPosZero().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerFGETSIGN (SDValue Op, SelectionDAG & DAG) static
Definition at line 14659 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::FGETSIGNx86, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), and llvm::SDValue::getSimpleValueType().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerFP_EXTEND (SDValue Op, SelectionDAG & DAG) static
Definition at line 14510 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::v2f32, llvm::MVT::v4f32, and llvm::X86ISD::VFPEXT.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerFSINCOS (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 19547 of file X86ISelLowering.cpp.
References assert(), llvm::CallingConv::C, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::StructType::get(), llvm::VectorType::get(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExternalSymbol(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::is64Bit(), llvm::TargetLowering::ArgListEntry::isSExt, llvm::X86Subtarget::isTargetDarwin(), llvm::TargetLowering::ArgListEntry::isZExt, llvm::TargetLowering::LowerCallTo(), llvm::ISD::MERGE_VALUES, llvm::TargetLowering::ArgListEntry::Node, llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), and llvm::TargetLowering::ArgListEntry::Ty.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerINSERT_SUBVECTOR (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 13137 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::X86Subtarget::hasFp256(), Insert128BitVector(), Insert256BitVector(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), and llvm::MVT::is512BitVector().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerINTRINSIC_W_CHAIN (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 17574 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::ADD, llvm::ADX, assert(), llvm::ISD::BITCAST, llvm::X86ISD::CMOV, llvm::COMPRESS_TO_MEM, llvm::X86::COND_B, llvm::X86::COND_NE, llvm::N86::EBP, llvm::EXPAND_FROM_MEM, llvm::ISD::EXTRACT_SUBVECTOR, llvm::GATHER, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), getGatherNode(), llvm::SelectionDAG::getIntPtrConstant(), llvm::getIntrinsicWithChain(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), getPrefetchNode(), llvm::X86RegisterInfo::getPtrSizedFrameRegister(), getReadPerformanceCounter(), getReadTimeStampCounter(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getScatterNode(), llvm::EVT::getSizeInBits(), llvm::X86RegisterInfo::getSlotSize(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getSubtarget(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::Glue, Hint(), llvm::MVT::i1, llvm::MVT::i64, llvm::MVT::i8, isAllOnes(), llvm_unreachable, llvm::ISD::MERGE_VALUES, llvm::IntrinsicData::Opc0, llvm::IntrinsicData::Opc1, llvm::MVT::Other, llvm::PREFETCH, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::RDPMC, llvm::RDRAND, llvm::RDSEED, llvm::RDTSC, llvm::MipsISD::Ret, llvm::SCATTER, llvm::X86ISD::SETCC, llvm::MachineFrameInfo::setFrameAddressIsTaken(), llvm::MachineFrameInfo::setReturnAddressIsTaken(), llvm::IntrinsicData::Type, llvm::TargetLowering::verifyReturnAddressArgumentIsConstant(), llvm::XTEST, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerINTRINSIC_WO_CHAIN (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 17029 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::BLEND, llvm::CMP_MASK, llvm::CMP_MASK_CC, llvm::COMI, llvm::COMPRESS_EXPAND_IN_REG, llvm::X86::COND_A, llvm::X86::COND_B, llvm::X86::COND_E, llvm::X86::COND_INVALID, llvm::X86::COND_O, llvm::X86::COND_S, llvm::X86::CUR_DIRECTION, llvm::ISD::EXTRACT_SUBVECTOR, llvm::FMA_OP_MASK, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::getIntrinsicWithoutChain(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), getOpcodeForFMAIntrinsic(), llvm::SDValue::getOperand(), getScalarMaskingNode(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), getTargetVShiftNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), getVectorMaskingNode(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::INTR_TYPE_1OP, llvm::INTR_TYPE_1OP_MASK_RM, llvm::INTR_TYPE_2OP, llvm::INTR_TYPE_2OP_MASK, llvm::INTR_TYPE_3OP, llvm::INTR_TYPE_SCALAR_MASK_RM, isAllOnes(), llvm::X86ISD::KORTEST, llvm_unreachable, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::IntrinsicData::Opc0, llvm::IntrinsicData::Opc1, llvm::X86ISD::PCMPESTRI, llvm::X86ISD::PCMPISTRI, llvm::X86ISD::PTEST, llvm::X86ISD::SETCC, llvm::X86ISD::TESTP, TranslateX86CC(), llvm::IntrinsicData::Type, llvm::MVT::v16i1, llvm::X86ISD::VALIGN, llvm::VSHIFT, llvm::VSHIFT_MASK, llvm::Intrinsic::x86_avx512_kortestc_w, llvm::Intrinsic::x86_avx512_kortestz_w, llvm::Intrinsic::x86_avx512_mask_valign_d_512, llvm::Intrinsic::x86_avx512_mask_valign_q_512, llvm::Intrinsic::x86_avx_ptestc_256, llvm::Intrinsic::x86_avx_ptestnzc_256, llvm::Intrinsic::x86_avx_ptestz_256, llvm::Intrinsic::x86_avx_vtestc_pd, llvm::Intrinsic::x86_avx_vtestc_pd_256, llvm::Intrinsic::x86_avx_vtestc_ps, llvm::Intrinsic::x86_avx_vtestc_ps_256, llvm::Intrinsic::x86_avx_vtestnzc_pd, llvm::Intrinsic::x86_avx_vtestnzc_pd_256, llvm::Intrinsic::x86_avx_vtestnzc_ps, llvm::Intrinsic::x86_avx_vtestnzc_ps_256, llvm::Intrinsic::x86_avx_vtestz_pd, llvm::Intrinsic::x86_avx_vtestz_pd_256, llvm::Intrinsic::x86_avx_vtestz_ps, llvm::Intrinsic::x86_avx_vtestz_ps_256, llvm::Intrinsic::x86_fma_mask_vfmadd_pd_512, llvm::Intrinsic::x86_fma_mask_vfmadd_ps_512, llvm::Intrinsic::x86_fma_mask_vfmaddsub_pd_512, llvm::Intrinsic::x86_fma_mask_vfmaddsub_ps_512, llvm::Intrinsic::x86_fma_mask_vfmsub_pd_512, llvm::Intrinsic::x86_fma_mask_vfmsub_ps_512, llvm::Intrinsic::x86_fma_mask_vfmsubadd_pd_512, llvm::Intrinsic::x86_fma_mask_vfmsubadd_ps_512, llvm::Intrinsic::x86_fma_mask_vfnmadd_pd_512, llvm::Intrinsic::x86_fma_mask_vfnmadd_ps_512, llvm::Intrinsic::x86_fma_mask_vfnmsub_pd_512, llvm::Intrinsic::x86_fma_mask_vfnmsub_ps_512, llvm::Intrinsic::x86_fma_vfmadd_pd, llvm::Intrinsic::x86_fma_vfmadd_pd_256, llvm::Intrinsic::x86_fma_vfmadd_ps, llvm::Intrinsic::x86_fma_vfmadd_ps_256, llvm::Intrinsic::x86_fma_vfmaddsub_pd, llvm::Intrinsic::x86_fma_vfmaddsub_pd_256, llvm::Intrinsic::x86_fma_vfmaddsub_ps, llvm::Intrinsic::x86_fma_vfmaddsub_ps_256, llvm::Intrinsic::x86_fma_vfmsub_pd, llvm::Intrinsic::x86_fma_vfmsub_pd_256, llvm::Intrinsic::x86_fma_vfmsub_ps, llvm::Intrinsic::x86_fma_vfmsub_ps_256, llvm::Intrinsic::x86_fma_vfmsubadd_pd, llvm::Intrinsic::x86_fma_vfmsubadd_pd_256, llvm::Intrinsic::x86_fma_vfmsubadd_ps, llvm::Intrinsic::x86_fma_vfmsubadd_ps_256, llvm::Intrinsic::x86_fma_vfnmadd_pd, llvm::Intrinsic::x86_fma_vfnmadd_pd_256, llvm::Intrinsic::x86_fma_vfnmadd_ps, llvm::Intrinsic::x86_fma_vfnmadd_ps_256, llvm::Intrinsic::x86_fma_vfnmsub_pd, llvm::Intrinsic::x86_fma_vfnmsub_pd_256, llvm::Intrinsic::x86_fma_vfnmsub_ps, llvm::Intrinsic::x86_fma_vfnmsub_ps_256, llvm::Intrinsic::x86_sse41_ptestc, llvm::Intrinsic::x86_sse41_ptestnzc, llvm::Intrinsic::x86_sse41_ptestz, llvm::Intrinsic::x86_sse42_pcmpestri128, llvm::Intrinsic::x86_sse42_pcmpestria128, llvm::Intrinsic::x86_sse42_pcmpestric128, llvm::Intrinsic::x86_sse42_pcmpestrio128, llvm::Intrinsic::x86_sse42_pcmpestris128, llvm::Intrinsic::x86_sse42_pcmpestriz128, llvm::Intrinsic::x86_sse42_pcmpistri128, llvm::Intrinsic::x86_sse42_pcmpistria128, llvm::Intrinsic::x86_sse42_pcmpistric128, llvm::Intrinsic::x86_sse42_pcmpistrio128, llvm::Intrinsic::x86_sse42_pcmpistris128, llvm::Intrinsic::x86_sse42_pcmpistriz128, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerIntVSETCC_AVX512 (SDValue Op, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 15289 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::CMPM, llvm::X86ISD::CMPMU, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::i1, llvm::MVT::i8, llvm_unreachable, llvm::X86ISD::PCMPEQM, llvm::X86ISD::PCMPGTM, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, std::swap(), and Unsigned.
Referenced by LowerVSETCC().
static SDValue LowerLOAD_SUB (SDValue Op, SelectionDAG & DAG) static
Definition at line 19481 of file X86ISelLowering.cpp.
References llvm::ISD::ATOMIC_LOAD_ADD, llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), Node, and llvm::ISD::SUB.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerMUL (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 18197 of file X86ISelLowering.cpp.
References llvm::ARM_PROC::A, llvm::ISD::ADD, assert(), llvm::ISD::BITCAST, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), getTargetVShiftByConstNode(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::is256BitVector(), Lower256IntArith(), llvm::X86ISD::PMULUDQ, llvm::MVT::v16i32, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::X86ISD::VSHLI, and llvm::X86ISD::VSRLI.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerMUL_LOHI (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 18321 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86ISD::PMULDQ, llvm::X86ISD::PMULUDQ, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA, llvm::ISD::SUB, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v4i64, and llvm::MVT::v8i32.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerREADCYCLECOUNTER (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 17564 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), getReadTimeStampCounter(), and llvm::X86ISD::RDTSC_DAG.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerSCALAR_TO_VECTOR (SDValue Op, SelectionDAG & DAG) static
Definition at line 13080 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::BITCAST, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i32, llvm::MVT::i64, Insert128BitVector(), llvm::MVT::is128BitVector(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v1i64, and llvm::MVT::v4i32.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerScalarImmediateShift (SDValue Op, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 18397 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), getTargetVShiftByConstNode(), llvm::MVT::getVectorNumElements(), getZeroVector(), llvm::ConstantSDNode::getZExtValue(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasInt256(), llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm_unreachable, llvm::Log2_32_Ceil(), llvm::X86ISD::PCMPGT, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRAI, llvm::X86ISD::VSRLI, and llvm::ISD::XOR.
Referenced by LowerShift().
static SDValue LowerScalarVariableShift (SDValue Op, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 18568 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::EVT::bitsGT(), llvm::EVT::bitsLE(), llvm::EVT::bitsLT(), llvm::ISD::BUILD_VECTOR, llvm::dyn_cast(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::ShuffleVectorSDNode::getSplatIndex(), getTargetVShiftNode(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::ConstantSDNode::getZExtValue(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasInt256(), llvm::MVT::i64, llvm::ISD::INSERT_VECTOR_ELT, llvm::X86Subtarget::is64Bit(), llvm::ShuffleVectorSDNode::isSplat(), llvm_unreachable, llvm::ISD::SHL, llvm::MVT::SimpleTy, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::UNDEF, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::X86ISD::VSHL, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRA, llvm::X86ISD::VSRAI, llvm::X86ISD::VSRL, llvm::X86ISD::VSRLI, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerShift().
static SDValue LowerShift (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 18700 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, Extract128BitVector(), llvm::ISD::FP_TO_SINT, llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), getTargetShuffleNode(), getTargetVShiftByConstNode(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), llvm::APInt::getZExtValue(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::MVT::isVector(), LowerScalarImmediateShift(), LowerScalarVariableShift(), llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSS, llvm::ISD::MUL, llvm::X86ISD::PCMPEQ, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::SHL, llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::TRUNCATE, llvm::ISD::UNDEF, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::ISD::VSELECT, llvm::X86ISD::VSHLI, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerShiftParts (SDValue Op, SelectionDAG & DAG) static
LowerShiftParts - Lower SRA_PARTS and friends, which return two i32 values and take a 2 x i32 value to shift plus a shift amount.
Definition at line 13650 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::X86ISD::CMOV, llvm::X86ISD::CMP, llvm::X86::COND_NE, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::HexagonISD::Hi, llvm::MVT::i32, llvm::MVT::i8, llvm::HexagonISD::Lo, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::X86ISD::SHLD, llvm::X86ISD::SHRD, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, and llvm::ISD::SRL.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerSIGN_EXTEND (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 15978 of file X86ISelLowering.cpp.
References llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasInt256(), llvm::MVT::i1, llvm::MVT::is512BitVector(), LowerSIGN_EXTEND_AVX512(), llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::X86ISD::VSEXT.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerSIGN_EXTEND_AVX512 (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 15925 of file X86ISelLowering.cpp.
References assert(), llvm::ConstantInt::get(), llvm::APInt::getAllOnesValue(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::is512BitVector(), llvm::MVT::v16i32, llvm::MVT::v8i64, llvm::X86ISD::VBROADCASTM, llvm::X86ISD::VSEXT, llvm::X86ISD::VTRUNC, and llvm::X86ISD::VZEXT.
Referenced by LowerSIGN_EXTEND().
static SDValue LowerSUB (SDValue Op, SelectionDAG & DAG) static
Definition at line 18190 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::MVT::is256BitVector(), llvm::MVT::isInteger(), and Lower256IntArith().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerToTLSExecModel (GlobalAddressSDNode * GA, SelectionDAG & DAG, const EVT PtrVT, TLSModel::Model model, bool is64Bit, bool isPIC) static
Definition at line 13455 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getEntryNode(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MachinePointerInfo::getGOT(), llvm::Type::getInt8PtrTy(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::Constant::getNullValue(), llvm::GlobalAddressSDNode::getOffset(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDNode::getValueType(), llvm::X86ISD::GlobalBaseReg, llvm::TLSModel::InitialExec, llvm_unreachable, llvm::TLSModel::LocalExec, llvm::X86II::MO_GOTNTPOFF, llvm::X86II::MO_GOTTPOFF, llvm::X86II::MO_INDNTPOFF, llvm::X86II::MO_NTPOFF, llvm::X86II::MO_TPOFF, llvm::MipsISD::ThreadPointer, llvm::X86ISD::Wrapper, and llvm::X86ISD::WrapperRIP.
static SDValue LowerToTLSGeneralDynamicModel32 (GlobalAddressSDNode * GA, SelectionDAG & DAG, const EVT PtrVT) static
Definition at line 13395 of file X86ISelLowering.cpp.
References llvm::N86::EAX, llvm::N86::EBX, llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getNode(), GetTLSADDR(), llvm::SDValue::getValue(), llvm::X86ISD::GlobalBaseReg, and llvm::X86II::MO_TLSGD.
static SDValue LowerToTLSGeneralDynamicModel64 (GlobalAddressSDNode * GA, SelectionDAG & DAG, const EVT PtrVT) static
Definition at line 13409 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getEntryNode(), GetTLSADDR(), and llvm::X86II::MO_TLSGD.
static SDValue LowerToTLSLocalDynamicModel (GlobalAddressSDNode * GA, SelectionDAG & DAG, const EVT PtrVT, bool is64Bit) static
Definition at line 13415 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::N86::EAX, llvm::N86::EBX, llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getEntryNode(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::SelectionDAG::getTargetGlobalAddress(), GetTLSADDR(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::X86ISD::GlobalBaseReg, llvm::X86MachineFunctionInfo::incNumLocalDynamicTLSAccesses(), llvm::X86II::MO_DTPOFF, llvm::X86II::MO_TLSLD, llvm::X86II::MO_TLSLDM, and llvm::X86ISD::Wrapper.
static SDValue lowerUINT_TO_FP_vXi32 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 13915 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::lltok::APFloat, assert(), llvm::ISD::BITCAST, llvm::X86ISD::BLENDI, llvm::ISD::BUILD_VECTOR, llvm::MVT::f32, llvm::ISD::FADD, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i32, llvm::APFloat::IEEEsingle, llvm::makeArrayRef(), llvm::ISD::OR, llvm::ISD::SRL, llvm::MVT::v16i16, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8f32, llvm::MVT::v8i16, and llvm::MVT::v8i32.
static SDValue lowerV16F32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 16-lane 32-bit floating point shuffles.
Definition at line 10769 of file X86ISelLowering.cpp.
References assert(), DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), isShuffleEquivalent, splitAndLowerVectorShuffle(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, and llvm::MVT::v16f32.
Referenced by lower512BitVectorShuffle().
static SDValue lowerV16I16VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 16-lane 16-bit integer shuffles.
This routine is only called when we have AVX2 and thus a reasonable instruction set for v16i16 shuffling..
Definition at line 10553 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::i8, is128BitLaneCrossingShuffleMask(), isShuffleEquivalent, isSingleInputShuffleMask(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsLanePermuteAndBlend(), lowerVectorShuffleAsSplitOrBlend(), lowerVectorShuffleByMerging128BitLanes(), llvm::X86ISD::PSHUFB, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v16i16, and llvm::MVT::v32i8.
Referenced by lower256BitVectorShuffle().
static SDValue lowerV16I32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 16-lane 32-bit integer shuffles.
Definition at line 10816 of file X86ISelLowering.cpp.
References assert(), DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), isShuffleEquivalent, splitAndLowerVectorShuffle(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, and llvm::MVT::v16i32.
Referenced by lower512BitVectorShuffle().
static SDValue lowerV16I8VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Generic lowering of v16i8 shuffles.
This is a hybrid strategy to lower v16i8 vectors. It first attempts to detect any complexity reducing interleaving. If that doesn't help, it uses UNPCK to spread the i8 elements across two i16-element vectors, and uses the existing lowering for v8i16 blends on each half, finally PACK-ing them back together.
Definition at line 9455 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MutableArrayRef< T >::begin(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, canLowerByDroppingEvenElements(), computeZeroableShuffleElements(), DL, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MutableArrayRef< T >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), getZeroVector(), llvm::X86Subtarget::hasSSSE3(), I, llvm::MVT::i8, isSingleInputShuffleMask(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsByteShift(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsZeroOrAnyExtend(), llvm::ISD::OR, llvm::X86ISD::PACKUS, llvm::X86ISD::PSHUFB, shouldLowerAsInterleaving(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ArrayRef< T >::size(), llvm::MutableArrayRef< T >::slice(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2i64, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by lower128BitVectorShuffle().
static SDValue lowerV2F64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 2-lane 64-bit floating point shuffles.
This is the basis function for the 2-lane 64-bit shuffles as we have full support for floating point shuffles but not integer shuffles. These instructions will incur a domain crossing penalty on some chips though so it is better to avoid lowering through this for integer vectors where possible.
Definition at line 8249 of file X86ISelLowering.cpp.
References assert(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), getScalarValueForVectorElement(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i8, isShuffleEquivalent, isShuffleFoldableLoad(), isSingleInputShuffleMask(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsElementInsertion(), llvm::X86ISD::MOVLPD, llvm::X86ISD::MOVSD, llvm::ISD::SCALAR_TO_VECTOR, llvm::X86ISD::SHUFP, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v2f64, and llvm::X86ISD::VPERMILPI.
Referenced by lower128BitVectorShuffle().
static SDValue lowerV2I64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 2-lane 64-bit integer shuffles.
Tries to lower a 2-lane 64-bit shuffle using shuffle operations provided by the integer unit to minimize domain crossing penalties. However, for blends it falls back to the floating point shuffle operation with appropriate bit casting.
Definition at line 8325 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), isShuffleEquivalent, isSingleInputShuffleMask(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsByteShift(), lowerVectorShuffleAsElementInsertion(), llvm::X86ISD::PSHUFD, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v2f64, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by lower128BitVectorShuffle().
static SDValue lowerV2X128VectorShuffle (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering 2-lane 128-bit shuffles.
Definition at line 10084 of file X86ISelLowering.cpp.
References llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i8, isShuffleEquivalent, lowerVectorShuffleAsBlend(), and llvm::X86ISD::VPERM2X128.
Referenced by lowerV4F64VectorShuffle(), and lowerV4I64VectorShuffle().
static SDValue lowerV32I16VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 32-lane 16-bit integer shuffles.
Definition at line 10841 of file X86ISelLowering.cpp.
References assert(), DL, llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasBWI(), splitAndLowerVectorShuffle(), and llvm::MVT::v32i16.
Referenced by lower512BitVectorShuffle().
static SDValue lowerV32I8VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 32-lane 8-bit integer shuffles.
This routine is only called when we have AVX2 and thus a reasonable instruction set for v32i8 shuffling..
Definition at line 10628 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::i8, is128BitLaneCrossingShuffleMask(), isShuffleEquivalent, isSingleInputShuffleMask(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsLanePermuteAndBlend(), lowerVectorShuffleAsSplitOrBlend(), lowerVectorShuffleByMerging128BitLanes(), llvm::X86ISD::PSHUFB, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, and llvm::MVT::v32i8.
Referenced by lower256BitVectorShuffle().
static SDValue lowerV4F32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Lower 4-lane 32-bit floating point shuffles.
Uses instructions exclusively from the floating point unit to minimize domain crossing penalties, as these are sufficient to implement all v4f32 shuffles.
Definition at line 8498 of file X86ISelLowering.cpp.
References assert(), DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasSSE41(), isShuffleEquivalent, lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsInsertPS(), lowerVectorShuffleWithSHUFPS(), llvm::X86ISD::SHUFP, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v4f32, and llvm::X86ISD::VPERMILPI.
Referenced by lower128BitVectorShuffle().
static SDValue lowerV4F64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 4-lane 64-bit floating point shuffles.
Also ends up handling lowering of 4-lane 64-bit integer shuffles when AVX2 isn't available.
Definition at line 10222 of file X86ISelLowering.cpp.
References assert(), canWidenShuffleElements(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::i8, is128BitLaneCrossingShuffleMask(), isShuffleEquivalent, isShuffleMaskInputInPlace(), isSingleInputShuffleMask(), lowerV2X128VectorShuffle(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsDecomposedShuffleBlend(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsLanePermuteAndBlend(), lowerVectorShuffleAsSplitOrBlend(), lowerVectorShuffleByMerging128BitLanes(), llvm::X86ISD::SHUFP, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v4f64, llvm::X86ISD::VPERMI, and llvm::X86ISD::VPERMILPI.
Referenced by lower256BitVectorShuffle().
static SDValue lowerV4I32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Lower 4-lane i32 vector shuffles.
We try to handle these with integer-domain shuffles where we can, but for blends we use the floating point domain blend instructions.
Definition at line 8565 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), isShuffleEquivalent, lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsByteShift(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsZeroOrAnyExtend(), llvm::X86ISD::PSHUFD, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by lower128BitVectorShuffle().
static SDValue lowerV4I64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 4-lane 64-bit integer shuffles.
This routine is only called when we have AVX2 and thus a reasonable instruction set for v4i64 shuffling..
Definition at line 10326 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, canWidenShuffleElements(), DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX2(), is128BitLaneRepeatedShuffleMask(), isShuffleEquivalent, isShuffleMaskInputInPlace(), isSingleInputShuffleMask(), lowerV2X128VectorShuffle(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsDecomposedShuffleBlend(), lowerVectorShuffleByMerging128BitLanes(), llvm::X86ISD::PSHUFD, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v4i64, llvm::MVT::v8i32, and llvm::X86ISD::VPERMI.
Referenced by lower256BitVectorShuffle().
static SDValue lowerV64I8VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 64-lane 8-bit integer shuffles.
Definition at line 10857 of file X86ISelLowering.cpp.
References assert(), DL, llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasBWI(), splitAndLowerVectorShuffle(), and llvm::MVT::v64i8.
Referenced by lower512BitVectorShuffle().
static SDValue lowerV8F32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 8-lane 32-bit floating point shuffles.
Also ends up handling lowering of 8-lane 32-bit integer shuffles when AVX2 isn't available.
Definition at line 10401 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::i32, is128BitLaneCrossingShuffleMask(), is128BitLaneRepeatedShuffleMask(), isShuffleEquivalent, isSingleInputShuffleMask(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsDecomposedShuffleBlend(), lowerVectorShuffleAsLanePermuteAndBlend(), lowerVectorShuffleAsSplitOrBlend(), lowerVectorShuffleByMerging128BitLanes(), lowerVectorShuffleWithSHUFPS(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v8f32, llvm::MVT::v8i32, llvm::X86ISD::VPERMILPI, llvm::X86ISD::VPERMILPV, and llvm::X86ISD::VPERMV.
Referenced by lower256BitVectorShuffle().
static SDValue lowerV8F64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 8-lane 64-bit floating point shuffles.
Definition at line 10747 of file X86ISelLowering.cpp.
References assert(), DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), isShuffleEquivalent, splitAndLowerVectorShuffle(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, and llvm::MVT::v8f64.
Referenced by lower512BitVectorShuffle().
static SDValue lowerV8I16BasicBlendVectorShuffle (SDLoc DL, SDValue V1, SDValue V2, MutableArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Blend two v8i16 vectors using a naive unpack strategy.
This strategy only works when the inputs from each vector fit into a single half of that vector, and generally there are not so many inputs as to leave the in-place shuffles required highly constrained (and thus expensive). It shifts all the inputs into a single side of both input vectors and then uses an unpack to interleave these inputs in a single vector. At that point, we will fall back on the generic single input shuffle lowering.
Definition at line 9157 of file X86ISelLowering.cpp.
References assert(), llvm::sys::path::begin(), llvm::ArrayRef< T >::empty(), llvm::sys::path::end(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ArrayRef< T >::size(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, and llvm::MVT::v8i16.
Referenced by lowerV8I16VectorShuffle().
static SDValue lowerV8I16SingleInputVectorShuffle (SDLoc DL, SDValue V, MutableArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Lowering of single-input v8i16 shuffles is the cornerstone of SSE2 shuffle lowering, and the most complex part.
The lowering strategy is to try to form pairs of input lanes which are targeted at the same half of the final vector, and then use a dword shuffle to place them onto the right half, and finally unpack the paired lanes into their final position.
The exact breakdown of how to form these dword pairs and align them on the correct sides is really tricky. See the comments within the function for more of the details.
Definition at line 8660 of file X86ISelLowering.cpp.
References assert(), llvm::sys::path::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ArrayRef< T >::begin(), llvm::MutableArrayRef< T >::begin(), llvm::ISD::BITCAST, llvm::SmallVectorTemplateCommon< T, typename >::data(), DL, llvm::ArrayRef< T >::empty(), llvm::sys::path::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ArrayRef< T >::end(), llvm::MutableArrayRef< T >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), getV4X86ShuffleImm8ForMask(), llvm::SelectionDAG::getVectorShuffle(), isNoopShuffleMask(), isShuffleEquivalent, llvm_unreachable, lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsByteShift(), llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ArrayRef< T >::size(), llvm::MutableArrayRef< T >::slice(), std::swap(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by lowerV8I16VectorShuffle().
static SDValue lowerV8I16VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Generic lowering of 8-lane i16 shuffles.
This handles both single-input shuffles and combined shuffle/blends with two inputs. The single input shuffles are immediately delegated to a dedicated lowering routine.
The blends are lowered in one of three fundamental ways. If there are few enough inputs, it delegates to a basic UNPCK-based strategy. If the shuffle of the input is significantly cheaper when lowered as an interleaving of the two inputs, try to interleave them. Otherwise, blend the low and high halves of the inputs separately (making them have relatively few inputs) and then concatenate them.
Definition at line 9277 of file X86ISelLowering.cpp.
References assert(), llvm::MutableArrayRef< T >::begin(), llvm::ISD::BITCAST, DL, llvm::MutableArrayRef< T >::end(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasSSE41(), isShuffleEquivalent, lowerV8I16BasicBlendVectorShuffle(), lowerV8I16SingleInputVectorShuffle(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsByteShift(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsZeroOrAnyExtend(), shouldLowerAsInterleaving(), llvm::ArrayRef< T >::size(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v2i64, and llvm::MVT::v8i16.
Referenced by lower128BitVectorShuffle().
static SDValue lowerV8I32VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 8-lane 32-bit integer shuffles.
This routine is only called when we have AVX2 and thus a reasonable instruction set for v8i32 shuffling..
Definition at line 10489 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::i32, is128BitLaneRepeatedShuffleMask(), isShuffleEquivalent, isSingleInputShuffleMask(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsDecomposedShuffleBlend(), lowerVectorShuffleByMerging128BitLanes(), llvm::X86ISD::PSHUFD, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v8i32, and llvm::X86ISD::VPERMV.
Referenced by lower256BitVectorShuffle().
static SDValue lowerV8I64VectorShuffle (SDValue Op, SDValue V1, SDValue V2, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Handle lowering of 8-lane 64-bit integer shuffles.
Definition at line 10794 of file X86ISelLowering.cpp.
References assert(), DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), isShuffleEquivalent, splitAndLowerVectorShuffle(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, and llvm::MVT::v8i64.
Referenced by lower512BitVectorShuffle().
static SDValue LowerVACOPY (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 16773 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMemcpy(), llvm::SDValue::getOperand(), and llvm::X86Subtarget::is64Bit().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerVECTOR_SHUFFLE_128v4 (ShuffleVectorSDNode * SVOp, SelectionDAG & DAG) static
LowerVECTOR_SHUFFLE_128v4 - Handle all 128-bit wide vectors with 4 elements, and match them with several different shuffle types.
Definition at line 11803 of file X86ISelLowering.cpp.
References assert(), CommuteVectorShuffleMask(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::is128BitVector(), std::swap(), and llvm::NVPTX::PTXLdStInstCode::V2.
static SDValue LowerVECTOR_SHUFFLE_256 (ShuffleVectorSDNode * SVOp, SelectionDAG & DAG) static
LowerVECTOR_SHUFFLE_256 - Handle all 256-bit wide vectors shuffles which could not be matched by any known target speficic shuffle
Definition at line 11690 of file X86ISelLowering.cpp.
References llvm::array_lengthof(), llvm::ISD::BUILD_VECTOR, llvm::SmallVectorImpl< T >::clear(), Compact8x32ShuffleNode(), llvm::ISD::CONCAT_VECTORS, Extract128BitVector(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getIntPtrConstant(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
static SDValue LowerVECTOR_SHUFFLEtoBlend (ShuffleVectorSDNode * SVOp, unsigned MaskValue, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 11104 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::X86ISD::BLENDI, llvm::SelectionDAG::getConstant(), llvm::MVT::getFloatingPointVT(), llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i32, llvm::MVT::i64, isBlendMask(), llvm::MipsISD::Ret, and llvm::NVPTX::PTXLdStInstCode::V2.
static SDValue LowerVECTOR_SHUFFLEv16i16 (SDValue Op, SelectionDAG & DAG) static
v16i16 shuffles
FIXME: We only support generation of a single pshufb currently. We can generalize the other applicable cases from LowerVECTOR_SHUFFLEv8i16 as well (e.g 2 x pshufb + 1 x por).
Definition at line 11432 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::getMask(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), getPSHUFB(), llvm::ISD::UNDEF, and llvm::NVPTX::PTXLdStInstCode::V2.
static SDValue LowerVECTOR_SHUFFLEv16i8 (ShuffleVectorSDNode * SVOp, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 11449 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SmallVectorImpl< T >::clear(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i16, llvm::MVT::i8, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::isBuildVectorAllZeros(), llvm::ShuffleVectorSDNode::isSplat(), llvm::ISD::OR, PromoteSplat(), llvm::X86ISD::PSHUFB, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::SHL, llvm::ISD::SRL, llvm::ISD::UNDEF, llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::MVT::v8i16.
static SDValue LowerVECTOR_SHUFFLEv32i8 (ShuffleVectorSDNode * SVOp, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 11578 of file X86ISelLowering.cpp.
References CommuteVectorShuffleMask(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), getPSHUFB(), llvm::SDNode::getSimpleValueType(), llvm::X86Subtarget::hasInt256(), llvm::ISD::isBuildVectorAllZeros(), llvm::ISD::UNDEF, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::MVT::v32i8.
static SDValue LowerVECTOR_SHUFFLEv8i16 (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 11192 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, CommuteVectorShuffleMask(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getIntPtrConstant(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), getPSHUFB(), getShufflePSHUFHWImmediate(), getShufflePSHUFLWImmediate(), getTargetShuffleNode(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i16, llvm::ISD::INSERT_VECTOR_ELT, llvm::ShuffleVectorSDNode::isSplat(), llvm::ISD::OR, PromoteSplat(), llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2i64, llvm::MVT::v8i16, and llvm::ISD::VECTOR_SHUFFLE.
static SDValue LowerVectorAllZeroTest (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 14671 of file X86ISelLowering.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ISD::BITCAST, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SDNode::hasOneUse(), llvm::X86Subtarget::hasSSE41(), I, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::ISD::OR, llvm::MVT::Other, llvm::X86ISD::PTEST, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MVT::v2i64, and llvm::MVT::v4i64.
static SDValue LowerVectorBroadcast (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
LowerVectorBroadcast - Attempt to use the vbroadcast instruction to generate a splat value for the following cases:
A splat BUILD_VECTOR which uses a single scalar load, or a constant.
A splat shuffle which uses a scalar_to_vector node which comes from a scalar load, or a constant. The VBROADCAST node is returned when a pattern is found, or SDValue() otherwise.
Definition at line 6123 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::CallingConv::C, llvm::ISD::Constant, llvm::ISD::ConstantFP, Extract128BitVector(), F(), llvm::AttributeSet::FunctionIndex, llvm::Function::getAttributes(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasInt256(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasVLX(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::EVT::isInteger(), llvm::ISD::isNormalLoad(), llvm::ShuffleVectorSDNode::isSplat(), llvm::EVT::isVector(), llvm::Attribute::OptimizeForSize, llvm::ISD::SCALAR_TO_VECTOR, llvm::X86ISD::VBROADCAST, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by NormalizeVectorShuffle().
static SDValue LowerVectorIntExtend (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 12166 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, DL, llvm::MVT::getIntegerVT(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i64, llvm::MVT::is256BitVector(), llvm::MVT::isInteger(), llvm::TargetLoweringBase::isTypeLegal(), llvm::ISD::UNDEF, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::X86ISD::VZEXT.
Referenced by NormalizeVectorShuffle().
static SDValue lowerVectorShuffle (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Top-level lowering for x86 vector shuffles.
This handles decomposition, canonicalization, and lowering of all x86 vector shuffles. Most of the specific lowering strategies are encapsulated above in helper routines. The canonicalization attempts to widen shuffles to involve fewer lanes of wider elements, consolidate symmetric patterns s.t. only one of the two inputs needs to be tested, etc.
Definition at line 10928 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, canWidenShuffleElements(), llvm::SelectionDAG::getCommutedVectorShuffle(), llvm::MVT::getFloatingPointVT(), llvm::MVT::getIntegerVT(), llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::MVT::isFloatingPoint(), llvm::TargetLoweringBase::isTypeLegal(), llvm_unreachable, lower128BitVectorShuffle(), lower256BitVectorShuffle(), lower512BitVectorShuffle(), llvm::ISD::UNDEF, and llvm::NVPTX::PTXLdStInstCode::V2.
static SDValue lowerVectorShuffleAsBlend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Try to emit a blend instruction for a shuffle.
This doesn't do any checks for the availability of instructions for blending these values. It relies on the availability of the X86ISD::BLENDI pattern to be matched in the backend with the type given. What it does check for is that the shuffle mask is in fact a blend.
Definition at line 7419 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::X86ISD::BLENDI, llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::i8, is128BitLaneRepeatedShuffleMask(), llvm_unreachable, llvm::MVT::SimpleTy, llvm::ArrayRef< T >::size(), llvm::MVT::v16i16, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8f32, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::ISD::VSELECT.
Referenced by lowerV16I16VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV2X128VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I16VectorShuffle(), and lowerV8I32VectorShuffle().
static SDValue lowerVectorShuffleAsBroadcast (MVT VT, SDLoc DL, SDValue V, ArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Try to lower broadcast of a single element.
For convenience, this code also bundles all of the subtarget feature set filtering. While a little annoying to re-dispatch on type here, there isn't a convenient way to factor it out.
Definition at line 8092 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::dyn_cast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ConstantSDNode::getZExtValue(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::isInteger(), isShuffleFoldableLoad(), llvm::ISD::SCALAR_TO_VECTOR, and llvm::X86ISD::VBROADCAST.
Referenced by lower512BitVectorShuffle(), lowerV16I16VectorShuffle(), lowerV16I8VectorShuffle(), lowerV2I64VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), and lowerV8I32VectorShuffle().
static SDValue lowerVectorShuffleAsByteRotate (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Try to lower a vector shuffle as a byte rotation.
SSSE3 has a generic PALIGNR instruction in x86 that will do an arbitrary byte-rotation of the concatenation of two vectors; pre-SSSE3 can use a PSRLDQ/PSLLDQ/POR pattern to get a similar effect. This routine will try to generically lower a vector shuffle through such an pattern. It does not check for the profitability of lowering either as PALIGNR or PSRLDQ/PSLLDQ/POR, only whether the mask is valid to lower in that form. This matches shuffle vectors that look like:
v8i16 [11, 12, 13, 14, 15, 0, 1, 2]
Essentially it concatenates V1 and V2, shifts right by some number of elements, and takes the low elements as the result. Note that while this is specified as a right shift because x86 is little-endian, it is a left rotate of the vector lanes.
Note that this only handles 128-bit vector widths currently.
Definition at line 7586 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::X86Subtarget::hasSSSE3(), llvm::HexagonISD::Hi, llvm::MVT::i8, isNoopShuffleMask(), llvm::HexagonISD::Lo, llvm::ISD::OR, llvm::X86ISD::PALIGNR, llvm::ArrayRef< T >::size(), llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2i64, llvm::X86ISD::VSHLDQ, and llvm::X86ISD::VSRLDQ.
Referenced by lowerV16I8VectorShuffle(), lowerV2I64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), and lowerV8I16VectorShuffle().
static SDValue lowerVectorShuffleAsByteShift (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Try to lower a vector shuffle as a byte shift (shifts in zeros).
Attempts to match a shuffle mask against the PSRLDQ and PSLLDQ SSE2 byte-shift instructions. The mask must consist of a shifted sequential shuffle from one of the input vectors and zeroable elements for the remaining 'shifted in' elements.
Note that this only handles 128-bit vector widths currently.
Definition at line 7733 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, computeZeroableShuffleElements(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i8, isNoopShuffleMask(), isSequentialOrUndefInRange(), llvm::ArrayRef< T >::size(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2i64, llvm::X86ISD::VSHLDQ, and llvm::X86ISD::VSRLDQ.
Referenced by lowerV16I8VectorShuffle(), lowerV2I64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), and lowerV8I16VectorShuffle().
static SDValue lowerVectorShuffleAsDecomposedShuffleBlend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Generic routine to lower a shuffle and blend as a decomposed set of unblended shuffles followed by an unshuffled blend.
This matches the extremely common pattern for handling combined shuffle+blend operations on newer X86 ISAs where we have very fast blend operations.
Definition at line 7544 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), and llvm::ArrayRef< T >::size().
Referenced by lowerV4F64VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8I32VectorShuffle(), lowerVectorShuffleAsLanePermuteAndBlend(), and lowerVectorShuffleAsSplitOrBlend().
static SDValue lowerVectorShuffleAsElementInsertion (MVT VT, SDLoc DL, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Try to lower insertion of a single element into a zero vector.
This is a common pattern that we have especially efficient patterns to lower across all subtarget feature sets.
Definition at line 7993 of file X86ISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ISD::BITCAST, computeZeroableShuffleElements(), llvm::ArrayRef< T >::end(), llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getScalarShiftAmountTy(), getScalarValueForVectorElement(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::MVT::isFloatingPoint(), isNoopShuffleMask(), llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSS, llvm::ISD::SCALAR_TO_VECTOR, llvm::ArrayRef< T >::size(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::X86ISD::VSHLDQ, llvm::X86ISD::VZEXT_MOVL, and llvm::ISD::ZERO_EXTEND.
Referenced by lowerV16I8VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), and lowerV8I16VectorShuffle().
static SDValue lowerVectorShuffleAsInsertPS (SDValue Op, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Definition at line 8170 of file X86ISelLowering.cpp.
References assert(), computeZeroableShuffleElements(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::i8, llvm::X86ISD::INSERTPS, llvm::ArrayRef< T >::size(), and llvm::MVT::v4f32.
Referenced by lowerV4F32VectorShuffle().
static SDValue lowerVectorShuffleAsLanePermuteAndBlend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Lower a vector shuffle crossing multiple 128-bit lanes as a permutation and blend of those lanes.
This essentially blends the out-of-lane inputs to each lane into the lane from a permuted copy of the vector. This lowering strategy results in four instructions in the worst case for a single-input cross lane shuffle which is lower than any other fully general cross-lane shuffle strategy I'm aware of. Special cases for each particular shuffle pattern should be handled prior to trying this lowering.
Definition at line 10039 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::i8, isSingleInputShuffleMask(), lowerVectorShuffleAsDecomposedShuffleBlend(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ArrayRef< T >::size(), splitAndLowerVectorShuffle(), and llvm::X86ISD::VPERM2X128.
Referenced by lowerV16I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F64VectorShuffle(), and lowerV8F32VectorShuffle().
static SDValue lowerVectorShuffleAsSpecificZeroOrAnyExtend (SDLoc DL, MVT VT, int NumElements, int Scale, bool AnyExt, SDValue InputV, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Lower a vector shuffle as a zero or any extension.
Given a specific number of elements, element bit width, and extension stride, produce either a zero or any extension based on the available features of the subtarget.
Definition at line 7805 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::MipsISD::Ext, llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), getV4X86ShuffleImm8ForMask(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i8, llvm::X86ISD::PSHUFB, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::UNPCKL, llvm::MVT::v16i8, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::X86ISD::VZEXT.
Referenced by lowerVectorShuffleAsZeroOrAnyExtend().
static SDValue lowerVectorShuffleAsSplitOrBlend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Either split a vector in halves or decompose the shuffles and the blend.
This is provided as a good fallback for many lowerings of non-single-input shuffles with more than one 128-bit lane. In those cases, we want to select between splitting the shuffle into 128-bit components and stitching those back together vs. extracting the single-input shuffles and blending those results.
Definition at line 9980 of file X86ISelLowering.cpp.
References assert(), llvm::SmallBitVector::count(), llvm::MVT::getSizeInBits(), isSingleInputShuffleMask(), lowerVectorShuffleAsDecomposedShuffleBlend(), llvm::SmallBitVector::resize(), llvm::ArrayRef< T >::size(), and splitAndLowerVectorShuffle().
Referenced by lowerV16I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F64VectorShuffle(), and lowerV8F32VectorShuffle().
static SDValue lowerVectorShuffleAsZeroOrAnyExtend (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Try to lower a vector shuffle as a zero extension on any micrarch.
This routine will try to do everything in its power to cleverly lower a shuffle which happens to match the pattern of a zero extend. It doesn't check for the profitability of this lowering, it tries to aggressively match this pattern. It will use all of the micro-architectural details it can to emit an efficient lowering. It handles both blends with all-zero inputs to explicitly zero-extend and undef-lanes (sometimes undef due to masking out later).
The reason we have dedicated lowering for zext-style shuffles is that they are both incredibly common and often quite performance sensitive.
Definition at line 7890 of file X86ISelLowering.cpp.
References assert(), llvm::tgtok::Bits, computeZeroableShuffleElements(), llvm::MVT::getSizeInBits(), lowerVectorShuffleAsSpecificZeroOrAnyExtend(), llvm::ArrayRef< T >::size(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV16I8VectorShuffle(), lowerV4I32VectorShuffle(), and lowerV8I16VectorShuffle().
static SDValue lowerVectorShuffleByMerging128BitLanes (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Lower a vector shuffle by first fixing the 128-bit lanes and then shuffling each lane.
This will only succeed when the result of fixing the 128-bit lanes results in a single-input non-lane-crossing shuffle with a repeating shuffle mask in each 128-bit lanes. This handles many cases where we can quickly blend away the lane crosses early and then use simpler shuffles within each lane.
FIXME: It might be worthwhile at some point to support this without requiring the 128-bit lane-relative shuffles to be repeating, but currently in x86 only floating point has interesting non-repeating shuffles, and even those are still marginally more expensive.
Definition at line 10132 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::MVT::f64, llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::MVT::i64, is128BitLaneCrossingShuffleMask(), llvm::MVT::isFloatingPoint(), isSingleInputShuffleMask(), llvm::SmallVectorImpl< T >::resize(), and llvm::ArrayRef< T >::size().
Referenced by lowerV16I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), and lowerV8I32VectorShuffle().
static SDValue lowerVectorShuffleWithSHUFPS (SDLoc DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG & DAG) static
Lower a vector shuffle using the SHUFPS instruction.
This is a helper routine dedicated to lowering vector shuffles using SHUFPS. It makes no assumptions about whether this is the best lowering, it simply uses it.
Definition at line 8408 of file X86ISelLowering.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::SelectionDAG::getNode(), getV4X86ShuffleImm8ForMask(), llvm::X86ISD::SHUFP, std::swap(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV4F32VectorShuffle(), and lowerV8F32VectorShuffle().
static SDValue lowerVSELECTtoBLENDI (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Try to lower a VSELECT instruction to an immediate-controlled blend instruction.
Definition at line 12670 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::X86ISD::BLENDI, BUILD_VECTORtoBlendMask(), llvm::SelectionDAG::getConstant(), llvm::MVT::getFloatingPointVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MVT::is512BitVector(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::MipsISD::Ret, and llvm::MVT::v16i16.
static SDValue LowerVSETCC (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 15359 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, ChangeVSETULTtoVSETULE(), llvm::X86ISD::CMPM, llvm::X86ISD::CMPP, EQ, llvm::MVT::f64, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getOperand(), llvm::APInt::getSignBit(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), getZeroVector(), llvm::AArch64CC::GT, llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSE42(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::MVT::is256BitVector(), llvm::EVT::is512BitVector(), llvm::MVT::isFloatingPoint(), llvm_unreachable, Lower256IntVSETCC(), LowerIntVSETCC_AVX512(), llvm::ISD::OR, llvm::X86ISD::PCMPEQ, llvm::X86ISD::PCMPGT, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::X86ISD::SUBUS, std::swap(), translateX86FSETCC(), llvm::ISD::TRUNCATE, llvm::X86ISD::UMAX, llvm::X86ISD::UMIN, llvm::MVT::v2i64, llvm::MVT::v4i32, and llvm::ISD::XOR.
static SDValue LowerXALUO (SDValue Op, SelectionDAG & DAG) static
Definition at line 18947 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADD, llvm::X86::COND_B, llvm::X86::COND_O, llvm::X86ISD::DEC, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::MVT::i32, llvm::MVT::i8, llvm::X86ISD::INC, llvm::ConstantSDNode::isOne(), llvm_unreachable, llvm::ISD::MERGE_VALUES, llvm::ISD::SADDO, llvm::X86ISD::SETCC, llvm::X86ISD::SMUL, llvm::X86ISD::SMUL8, llvm::ISD::SMULO, llvm::ISD::SSUBO, llvm::X86ISD::SUB, llvm::ISD::UADDO, llvm::X86ISD::UMUL, llvm::X86ISD::UMUL8, llvm::ISD::UMULO, and llvm::ISD::USUBO.
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerZERO_EXTEND (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 14313 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasFp256(), llvm::MVT::i1, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), LowerAVXExtend(), and LowerZERO_EXTEND_AVX512().
Referenced by llvm::X86TargetLowering::LowerOperation().
static SDValue LowerZERO_EXTEND_AVX512 (SDValue Op, SelectionDAG & DAG) static
Definition at line 14271 of file X86ISelLowering.cpp.
References assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::i1, llvm::MVT::is512BitVector(), llvm::MVT::v16i32, llvm::MVT::v8i64, llvm::X86ISD::VBROADCASTM, llvm::X86ISD::VTRUNC, and llvm::X86ISD::VZEXT.
Referenced by LowerZERO_EXTEND().
static SDValue matchAddSub (const BuildVectorSDNode * BV, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Try to fold a build_vector that performs an 'addsub' into the sequence of 'vadd + vsub + blendi'.
Definition at line 6626 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADDSUB, assert(), DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::ISD::FSUB, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), std::swap(), llvm::ISD::UNDEF, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, and llvm::MVT::v8f32.
Referenced by PerformBUILD_VECTORCombine().
static bool MatchingStackOffset (SDValue Arg, unsigned Offset, ISD::ArgFlagsTy Flags, MachineFrameInfo * MFI, const MachineRegisterInfo * MRI, const X86InstrInfo * TII) static
MatchingStackOffset - Return true if the given stack call argument is already available in the same position (relatively) of the caller's incoming argument stack.
Definition at line 3312 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CopyFromReg, llvm::tgtok::Def, llvm::dyn_cast(), llvm::ISD::FrameIndex, llvm::ISD::ArgFlagsTy::getByValSize(), llvm::MachineOperand::getIndex(), llvm::FrameIndexSDNode::getIndex(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::SDValue::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::SDValue::getOperand(), llvm::MachineInstr::getOperand(), getReg(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::MachineOperand::isFI(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::X86InstrInfo::isLoadFromStackSlot(), and llvm::TargetRegisterInfo::isVirtualRegister().
static std::pair<unsigned, bool> matchIntegerMINMAX (SDValue Cond, EVT VT, SDValue LHS, SDValue RHS, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Matches a VSELECT onto min/max or return 0 if the node doesn't match.
Definition at line 22986 of file X86ISelLowering.cpp.
References llvm::SDValue::getOperand(), llvm::EVT::getSimpleVT(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasVLX(), llvm::SelectionDAG::isEqualTo(), llvm::EVT::isVector(), llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::MVT::SimpleTy, llvm::X86ISD::SMAX, llvm::X86ISD::SMIN, llvm::X86ISD::UMAX, llvm::X86ISD::UMIN, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by PerformSELECTCombine().
static SDValue MaterializeSETB (SDLoc DL, SDValue EFLAGS, SelectionDAG & DAG, MVT VT) static
Definition at line 25635 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::X86::COND_B, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i1, llvm::MVT::i8, llvm::X86ISD::SETCC_CARRY, and llvm::ISD::TRUNCATE.
Referenced by PerformSETCCCombine().
static bool MayFoldIntoStore (SDValue Op) static
Definition at line 3582 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDValue::hasOneUse(), llvm::ISD::isNormalStore(), and llvm::SDNode::use_begin().
Referenced by getMOVLP(), and llvm::X86TargetLowering::IsDesirableToPromoteOp().
static bool MayFoldLoad (SDValue Op) static
Definition at line 3578 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDValue::hasOneUse(), and llvm::ISD::isNormalLoad().
Referenced by getINSERTPS(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), MayFoldVectorLoad(), and PerformINSERTPSCombine().
static bool MayFoldVectorLoad (SDValue V) static
Definition at line 11942 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::hasOneUse(), MayFoldLoad(), llvm::ISD::SCALAR_TO_VECTOR, and llvm::ISD::UNDEF.
Referenced by getMOVLP().
static SDValue NarrowVectorLoadToElement (LoadSDNode * Load, unsigned Index, SelectionDAG & DAG) static
Definition at line 12059 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemSDNode::getMemOperand(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getStoreSize(), and llvm::MVT::getVectorElementType().
Referenced by getINSERTPS(), and PerformINSERTPSCombine().
static void NormalizeMask (SmallVectorImpl< int > & Mask, unsigned NumElems) static
NormalizeMask - V2 is a splat, modify the mask (if needed) so all elements that point to V2 points to its first element.
Definition at line 5216 of file X86ISelLowering.cpp.
static SDValue NormalizeVectorShuffle (SDValue Op, const X86Subtarget * Subtarget, SelectionDAG & DAG) static
Definition at line 12222 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), getVZextMovL(), getZeroVector(), llvm::X86Subtarget::hasSSE2(), llvm::ISD::isBuildVectorAllZeros(), isCommutedMOVLMask(), isMOVLMask(), llvm::ShuffleVectorSDNode::isSplat(), isZeroShuffle(), LowerVectorBroadcast(), LowerVectorIntExtend(), RewriteAsNarrowerShuffle(), llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v32i8, and llvm::MVT::v8i16.
static SDValue OptimizeConditionalInDecrement (SDNode * N, SelectionDAG & DAG) static
Definition at line 25827 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADC, llvm::X86ISD::CMP, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::EVT::isInteger(), llvm::X86::isZeroNode(), llvm::X86ISD::SBB, llvm::X86ISD::SETCC, llvm::ISD::SUB, and llvm::ISD::ZERO_EXTEND.
Referenced by PerformAddCombine(), and PerformSubCombine().
static SDValue PerformADCCombine (SDNode * N, SelectionDAG & DAG, X86TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 25799 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86::COND_B, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::MVT::i8, llvm::X86::isZeroNode(), llvm::X86ISD::SETCC_CARRY, and llvm::SDValue::use_empty().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformAddCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
PerformADDCombine - Do target-specific dag combines on integer adds.
Definition at line 25864 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::X86ISD::HADD, llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSSE3(), isHorizontalBinOp(), OptimizeConditionalInDecrement(), llvm::MVT::v16i16, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::MVT::v8i32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformAndCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 24420 of file X86ISelLowering.cpp.
References llvm::X86ISD::ANDNP, llvm::X86ISD::BEXTR, CanFoldXORWithAllOnes(), CMPEQCombine(), llvm::CountPopulation_64(), llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::X86Subtarget::hasBMI(), llvm::X86Subtarget::hasTBM(), llvm::MVT::i64, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::isMask_64(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::MVT::v2i64, llvm::MVT::v4i64, and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformBrCondCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 25693 of file X86ISelLowering.cpp.
References llvm::X86ISD::BRCOND, checkBoolTestSetCCCombine(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getVTList(), and llvm::MVT::i8.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformBTCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 25346 of file X86ISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt(), llvm::APInt::getLowBitsSet(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::hasOneUse(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), and llvm::Log2_32().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformBUILD_VECTORCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 6717 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, DL, ExpandHorizontalBinOp(), llvm::ISD::FADD, llvm::X86ISD::FHADD, llvm::X86ISD::FHSUB, llvm::ISD::FSUB, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::X86ISD::HADD, llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSSE3(), llvm::X86ISD::HSUB, isHorizontalBinOp(), matchAddSub(), N, llvm::ISD::SUB, llvm::ISD::UNDEF, llvm::MVT::v16i16, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v8f32, llvm::MVT::v8i16, and llvm::MVT::v8i32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformCMOVCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Optimize X86ISD::CMOV [LHS, RHS, CONDCODE (e.g. X86::COND_NE), CONDVAL].
Definition at line 23780 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::BSF, llvm::X86ISD::BSR, checkBoolTestSetCCCombine(), llvm::X86ISD::CMOV, llvm::X86ISD::CMP, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::X86::COND_E, llvm::X86::COND_NE, llvm::MVT::f80, llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::X86::GetOppositeBranchCondition(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDNode::getVTList(), hasFPCMov(), llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::SelectionDAG::isKnownNeverZero(), llvm::ISD::MUL, llvm::X86ISD::SETCC, llvm::ISD::SHL, llvm::X86ISD::SUB, std::swap(), llvm::SDValue::use_empty(), and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformEXTRACT_VECTOR_ELTCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
PerformEXTRACT_VECTOR_ELTCombine - Detect vector gather/scatter index generation and convert it from being a bunch of shuffles and extracts into a somewhat faster sequence. For i686, the best sequence is apparently storing the value and loading scalars back, while for x64 we should use 64-bit extracts and shifts.
Definition at line 22865 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ISD::BITCAST, llvm::SelectionDAG::CreateStackTemporary(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getLoad(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getResNo(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLoweringBase::isOperationLegal(), llvm::X86ISD::MMX_MOVD2W, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SRA, llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::x86mmx, XFormVExtractWithShuffleIntoLoad(), and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformFADDCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Do target-specific dag combines on floating point adds.
Definition at line 25256 of file X86ISelLowering.cpp.
References llvm::X86ISD::FHADD, llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasFp256(), llvm::X86Subtarget::hasSSE3(), isHorizontalBinOp(), llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, and llvm::MVT::v8f32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformFANDCombine (SDNode * N, SelectionDAG & DAG) static
Do target-specific dag combines on X86ISD::FAND nodes.
Definition at line 25321 of file X86ISelLowering.cpp.
References llvm::SDNode::getOperand().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformFANDNCombine (SDNode * N, SelectionDAG & DAG) static
Do target-specific dag combines on X86ISD::FANDN nodes.
Definition at line 25334 of file X86ISelLowering.cpp.
References llvm::SDNode::getOperand().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformFMACombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 25448 of file X86ISelLowering.cpp.
References llvm::ARM_PROC::A, llvm::MVT::f64, llvm::X86ISD::FMADD, llvm::X86ISD::FMSUB, llvm::ISD::FNEG, llvm::X86ISD::FNMADD, llvm::X86ISD::FNMSUB, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasFMA(), llvm::X86Subtarget::hasFMA4(), and llvm::TargetLoweringBase::isTypeLegal().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformFMinFMaxCombine (SDNode * N, SelectionDAG & DAG) static
Do target-specific dag combines on X86ISD::FMIN and X86ISD::FMAX nodes.
Definition at line 25300 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::FMAX, llvm::X86ISD::FMAXC, llvm::X86ISD::FMIN, llvm::X86ISD::FMINC, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTarget(), llvm::SDNode::getValueType(), llvm_unreachable, llvm::TargetMachine::Options, and llvm::TargetOptions::UnsafeFPMath.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformFORCombine (SDNode * N, SelectionDAG & DAG) static
Do target-specific dag combines on X86ISD::FOR and X86ISD::FXOR nodes.
Definition at line 25286 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::FOR, llvm::X86ISD::FXOR, llvm::SDNode::getOpcode(), and llvm::SDNode::getOperand().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformFSUBCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Do target-specific dag combines on floating point subs.
Definition at line 25271 of file X86ISelLowering.cpp.
References llvm::X86ISD::FHSUB, llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasFp256(), llvm::X86Subtarget::hasSSE3(), isHorizontalBinOp(), llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, and llvm::MVT::v8f32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformINSERTPSCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 25605 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::X86ISD::INSERTPS, MayFoldLoad(), NarrowVectorLoadToElement(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue performIntegerAbsCombine (SDNode * N, SelectionDAG & DAG) static
Definition at line 24646 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::CMOV, llvm::X86::COND_GE, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::MVT::i8, llvm::EVT::isInteger(), llvm::ISD::SRA, llvm::X86ISD::SUB, and llvm::ISD::XOR.
Referenced by PerformXorCombine().
static SDValue PerformINTRINSIC_WO_CHAINCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 23951 of file X86ISelLowering.cpp.
References assert(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::APInt::getZExtValue(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE41(), llvm::ConstantSDNode::isAllOnesValue(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::ConstantSDNode::isNullValue(), llvm::EVT::isVector(), llvm::ISD::SRA, llvm::Intrinsic::x86_avx2_pblendd_128, llvm::Intrinsic::x86_avx2_pblendd_256, llvm::Intrinsic::x86_avx2_pblendvb, llvm::Intrinsic::x86_avx2_pblendw, llvm::Intrinsic::x86_avx2_psra_d, llvm::Intrinsic::x86_avx2_psra_w, llvm::Intrinsic::x86_avx2_psrai_d, llvm::Intrinsic::x86_avx2_psrai_w, llvm::Intrinsic::x86_avx_blend_pd_256, llvm::Intrinsic::x86_avx_blend_ps_256, llvm::Intrinsic::x86_avx_blendv_pd_256, llvm::Intrinsic::x86_avx_blendv_ps_256, llvm::Intrinsic::x86_sse2_psra_d, llvm::Intrinsic::x86_sse2_psra_w, llvm::Intrinsic::x86_sse2_psrai_d, llvm::Intrinsic::x86_sse2_psrai_w, llvm::Intrinsic::x86_sse41_blendpd, llvm::Intrinsic::x86_sse41_blendps, llvm::Intrinsic::x86_sse41_blendvpd, llvm::Intrinsic::x86_sse41_blendvps, llvm::Intrinsic::x86_sse41_pblendvb, and llvm::Intrinsic::x86_sse41_pblendw.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformISDSETCCCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 25550 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSetCC(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::ISD::isBuildVectorAllZeros(), llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SIGN_EXTEND, and llvm::ISD::SUB.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformLOADCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
PerformLOADCombine - Do target-specific dag combines on LOAD nodes.
Definition at line 24696 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorVT(), Insert128BitVector(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::MemSDNode::isInvariant(), llvm::MemSDNode::isNonTemporal(), llvm::X86Subtarget::isUnalignedMem32Slow(), llvm::MemSDNode::isVolatile(), N, llvm::ISD::NON_EXTLOAD, llvm::MVT::Other, and llvm::ISD::TokenFactor.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformMLOADCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
PerformMLOADCombine - Resolve extending loads.
Definition at line 24744 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::ISD::CONCAT_VECTORS, llvm::MaskedLoadStoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::MaskedLoadSDNode::getExtensionType(), llvm::MaskedLoadStoreSDNode::getMask(), llvm::SelectionDAG::getMaskedLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::MaskedLoadSDNode::getSrc0(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MVT::i1, llvm::isPowerOf2_32(), llvm::TargetLoweringBase::isTypeLegal(), N, llvm::ISD::NON_EXTLOAD, llvm::ISD::SEXTLOAD, llvm::ISD::UNDEF, and llvm::X86ISD::VSEXT.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformMSTORECombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
PerformMSTORECombine - Resolve truncating stores.
Definition at line 24825 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::CONCAT_VECTORS, llvm::MaskedLoadStoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::MaskedLoadStoreSDNode::getMask(), llvm::SelectionDAG::getMaskedStore(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::MaskedStoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MVT::i1, llvm::isPowerOf2_32(), llvm::MaskedStoreSDNode::isTruncatingStore(), llvm::TargetLoweringBase::isTypeLegal(), and N.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformMulCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
PerformMulCombine - Optimize a single multiply with constant into two in order to implement it with two cheaper instructions, e.g. LEA + SHL, LEA + LEA.
Definition at line 24056 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasOneUse(), llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer(), llvm::isPowerOf2_64(), llvm::Log2_64(), llvm::X86ISD::MUL_IMM, llvm::ISD::SHL, std::swap(), and llvm::SDNode::use_begin().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformOrCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 24484 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::ANDNP, assert(), llvm::ISD::BITCAST, llvm::tgtok::Bits, CMPEQCombine(), llvm::dyn_cast(), llvm::AttributeSet::FunctionIndex, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::X86Subtarget::hasInt256(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::ISD::isBuildVectorAllZeros(), llvm::X86Subtarget::isSHLDSlow(), llvm::Attribute::OptimizeForSize, llvm::X86ISD::PSIGN, llvm::ISD::SHL, llvm::X86ISD::SHLD, llvm::X86ISD::SHRD, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, std::swap(), llvm::ISD::TRUNCATE, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i64, llvm::ISD::VSELECT, llvm::X86ISD::VSRAI, llvm::X, and Y.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformSELECTCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
PerformSELECTCombine - Do target-specific dag combines on SELECT and VSELECT nodes.
Definition at line 23120 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt(), llvm::ISD::CONCAT_VECTORS, Extract128BitVector(), llvm::MVT::f32, llvm::MVT::f80, llvm::X86ISD::FMAX, llvm::X86ISD::FMIN, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::APInt::getHighBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCInverse(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasVLX(), I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SelectionDAG::isEqualTo(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::SelectionDAG::isKnownNeverNaN(), llvm::SelectionDAG::isKnownNeverZero(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), matchIntegerMINMAX(), llvm::ISD::MUL, llvm::TargetMachine::Options, llvm::ISD::OR, Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::MipsISD::Ret, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SHL, llvm::X86ISD::SHRUNKBLEND, llvm::ISD::SIGN_EXTEND, llvm::TargetLowering::SimplifyDemandedBits(), llvm::ISD::SUB, llvm::X86ISD::SUBUS, std::swap(), transformVSELECTtoBlendVECTOR_SHUFFLE(), llvm::TargetOptions::UnsafeFPMath, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2f32, llvm::MVT::v32i8, llvm::MVT::v8i16, llvm::ISD::VSELECT, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformSETCCCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 25649 of file X86ISelLowering.cpp.
References checkBoolTestSetCCCombine(), llvm::X86::COND_A, llvm::X86::COND_B, llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SDNode::getVTList(), llvm::MVT::i8, MaterializeSETB(), llvm::X86ISD::SETCC, and llvm::X86ISD::SUB.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformSExtCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 25413 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasFp256(), llvm::MVT::i32, llvm::MVT::i8, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SDIVREM, llvm::X86ISD::SDIVREM8_SEXT_HREG, and WidenMaskArithmetic().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformShiftCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
PerformShiftCombine - Combine shifts.
Definition at line 24189 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), performShiftToAllZeros(), PerformSHLCombine(), llvm::ISD::SHL, and llvm::ISD::SRA.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue performShiftToAllZeros (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Returns a vector of 0s if the node in input is a vector logical shift by a constant amount which is known to be bigger than or equal to the vector element size in bits.
Definition at line 24161 of file X86ISelLowering.cpp.
References llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), getZeroVector(), llvm::X86Subtarget::hasInt256(), llvm::APInt::trunc(), llvm::APInt::uge(), llvm::MVT::v16i16, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, and llvm::MVT::v8i32.
Referenced by PerformShiftCombine().
static SDValue PerformSHLCombine (SDNode * N, SelectionDAG & DAG) static
Definition at line 24116 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::Constant, llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::isVector(), llvm::X86ISD::SETCC_CARRY, llvm::APInt::shl(), and llvm::ISD::ZERO_EXTEND.
Referenced by PerformShiftCombine().
static SDValue PerformShuffleCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
PerformShuffleCombine - Performs several different shuffle combines.
Definition at line 22644 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, combineShuffleToAddSub(), combineX86ShufflesRecursively(), EltsFromConsecutiveLoads(), llvm::ISD::FADD, llvm::ISD::FMUL, llvm::ISD::FSUB, llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), getShuffleScalarElt(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasFp256(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE3(), llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::TargetLoweringBase::isOperationLegal(), isTargetShuffle(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::ISD::MUL, N, PerformShuffleCombine256(), PerformTargetShuffleCombine(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::SUB, llvm::ISD::UNDEF, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformShuffleCombine256 (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
PerformShuffleCombine256 - Performs shuffle combines for 256-bit vectors.
Definition at line 21839 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::ISD::CONCAT_VECTORS, Extract128BitVector(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), getZeroVector(), llvm::SDNode::hasAnyUseOfValue(), llvm::SDNode::hasNUsesOfValue(), Insert128BitVector(), llvm::ISD::isBuildVectorAllZeros(), isShuffleHigh128VectorInsertLow(), isShuffleLow128VectorInsertHigh(), isUndefOrEqual(), N, llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::TokenFactor, llvm::ISD::UNDEF, llvm::SelectionDAG::UpdateNodeOperands(), llvm::MVT::v4i64, and llvm::X86ISD::VZEXT_LOAD.
Referenced by PerformShuffleCombine().
static SDValue PerformSIGN_EXTEND_INREGCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 25378 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasInt256(), llvm::ISD::isNormalLoad(), llvm::EVT::isVector(), llvm::ISD::LOAD, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::MVT::v4i32, and llvm::MVT::v4i64.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformSINT_TO_FPCombine (SDNode * N, SelectionDAG & DAG, const X86TargetLowering * XTLI) static
Definition at line 25760 of file X86ISelLowering.cpp.
References llvm::X86TargetLowering::BuildFILD(), llvm::MemSDNode::getChain(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::X86TargetLowering::getSubtarget(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), llvm::ISD::isNON_EXTLoad(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::ISD::LOAD, P, performVectorCompareAndMaskUnaryOpCombine(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::MVT::v4i32, llvm::MVT::v4i8, llvm::MVT::v8i32, and llvm::MVT::v8i8.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformSTORECombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
PerformSTORECombine - Do target-specific dag combines on STORE nodes.
Definition at line 24904 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::BITCAST, Extract128BitVector(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::AttributeSet::FunctionIndex, llvm::MemSDNode::getAlignment(), llvm::Function::getAttributes(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MachinePointerInfo::getWithOffset(), llvm::SDNode::hasNUsesOfValue(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i64, llvm::MVT::i8, llvm::MVT::integer_valuetypes(), llvm::X86Subtarget::is64Bit(), llvm::MemSDNode::isInvariant(), llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::isPowerOf2_32(), llvm::StoreSDNode::isTruncatingStore(), llvm::TargetLoweringBase::isTypeLegal(), llvm::X86Subtarget::isUnalignedMem32Slow(), llvm::MemSDNode::isVolatile(), llvm::MinAlign(), N, llvm::Attribute::NoImplicitFloat, llvm::TargetMachine::Options, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::TokenFactor, and llvm::TargetOptions::UseSoftFloat.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformSubCombine (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 25879 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasInt256(), llvm::SDNode::hasOneUse(), llvm::X86Subtarget::hasSSSE3(), llvm::X86ISD::HSUB, isHorizontalBinOp(), OptimizeConditionalInDecrement(), llvm::MVT::v16i16, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformTargetShuffleCombine (SDValue N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Try to combine x86 target specific shuffles.
Definition at line 22484 of file X86ISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), assert(), llvm::sys::path::begin(), llvm::ISD::BITCAST, combineRedundantDWordShuffle(), combineRedundantHalfShuffle(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::sys::path::end(), llvm::lltok::equal, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPSHUFShuffleMask(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::SDValue::hasOneUse(), isNoopShuffleMask(), llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by PerformShuffleCombine().
static SDValue PerformTruncateCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
PerformTruncateCombine - Converts truncate operation to a sequence of vector shuffle operations. It is possible when we truncate 256-bit vector to 128-bit vector
Definition at line 22759 of file X86ISelLowering.cpp.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue performVectorCompareAndMaskUnaryOpCombine (SDNode * N, SelectionDAG & DAG) static
Definition at line 25714 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::EVT::isVector(), and llvm::ISD::SETCC.
Referenced by PerformSINT_TO_FPCombine().
static SDValue PerformVZEXT_MOVLCombine (SDNode * N, SelectionDAG & DAG) static
Definition at line 25365 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), and llvm::X86ISD::VZEXT_LOAD.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue performVZEXTCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
performVZEXTCombine - Performs build vector combines
Definition at line 25913 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::ISD::SCALAR_TO_VECTOR, and llvm::X86ISD::VZEXT.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformXorCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 24680 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::X86Subtarget::hasCMov(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), and performIntegerAbsCombine().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PerformZExtCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 25488 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::SDValue::hasOneUse(), llvm::MVT::i64, llvm::MVT::i8, llvm::EVT::is256BitVector(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::X86ISD::SETCC_CARRY, llvm::ISD::TRUNCATE, llvm::ISD::UDIVREM, llvm::X86ISD::UDIVREM8_ZEXT_HREG, and WidenMaskArithmetic().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
static SDValue PromoteSplat (ShuffleVectorSDNode * SV, SelectionDAG & DAG) static
PromoteSplat - Splat is promoted to target supported vector shuffles.
Definition at line 5308 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, Extract128BitVector(), getLegalSplat(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::i16, llvm::MVT::i8, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), and PromoteSplati8i16().
Referenced by LowerVECTOR_SHUFFLEv16i8(), and LowerVECTOR_SHUFFLEv8i16().
static SDValue PromoteSplati8i16 (SDValue V, SelectionDAG & DAG, int & EltNo) static
Definition at line 5264 of file X86ISelLowering.cpp.
References llvm::SDValue::getSimpleValueType(), getUnpackh(), getUnpackl(), and llvm::MVT::getVectorNumElements().
Referenced by PromoteSplat().
static SDValue RewriteAsNarrowerShuffle (ShuffleVectorSDNode * SVOp, SelectionDAG & DAG) static
RewriteAsNarrowerShuffle - Try rewriting v8i16 and v16i8 shuffles as 4 wide ones, or rewriting v4i32 / v4f32 as 2 wide ones if possible. This can be done when every pair / quad of shuffle mask elements point to elements in the right sequence. e.g. vector_shuffle X, Y, <2, 3, | 10, 11, | 0, 1, | 14, 15>
Definition at line 11612 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MVT::SimpleTy, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::MVT::v8i32.
Referenced by NormalizeVectorShuffle().
static bool shouldLowerAsInterleaving (ArrayRef< int > Mask) static
Detect whether the mask pattern should be lowered through interleaving.
This essentially tests whether viewing the mask as an interleaving of two sub-sequences reduces the cross-input traffic of a blend operation. If so, lowering it through interleaving is a significantly better strategy.
Definition at line 9117 of file X86ISelLowering.cpp.
References llvm::ArrayRef< T >::size().
Referenced by lowerV16I8VectorShuffle(), and lowerV8I16VectorShuffle().
static bool ShouldXformToMOVHLPS (ArrayRef< int > Mask, MVT VT) static
ShouldXformToMOVHLPS - Return true if the node should be transformed to match movhlps. The lower half elements should come from upper half of V1 (and in order), and the upper half elements should come from the upper half of V2 (and in order).
Definition at line 5034 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), and isUndefOrEqual().
static bool ShouldXformToMOVLP (SDNode * V1, SDNode * V2, ArrayRef< int > Mask, MVT VT) static
ShouldXformToMOVLP{S|D} - Return true if the node should be transformed to match movlp{s|d}. The lower half elements should come from lower half of V1 (and in order), and the upper half elements should come from the upper half of V2 (and in order). And since V1 will become the source of the MOVLP, it must be either a vector load or a scalar load to vector.
Definition at line 5090 of file X86ISelLowering.cpp.
References llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), llvm::ISD::isNON_EXTLoad(), isScalarLoadToVector(), isUndefOrEqual(), and WillBeConstantPoolLoad().
static bool ShuffleCrosses128bitLane (MVT VT, unsigned InputIdx, unsigned OutputIdx) static
In vector type VT, return true if the element at index InputIdx falls on a different 128-bit lane than OutputIdx.
Definition at line 11136 of file X86ISelLowering.cpp.
References llvm::MVT::getSizeInBits(), and llvm::MVT::getVectorElementType().
Referenced by getPSHUFB(), and llvm::X86TargetLowering::isShuffleMaskLegal().
static SDValue splitAndLowerVectorShuffle (SDLoc DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Generic routine to split ector shuffle into half-sized shuffles.
This routine just extracts two subvectors, shuffles them independently, and then concatenates them back together. This should work effectively with all AVX vector shuffle types.
Definition at line 9878 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::HexagonISD::Hi, llvm::HexagonISD::Lo, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by lower256BitVectorShuffle(), lower512BitVectorShuffle(), lowerV16F32VectorShuffle(), lowerV16I32VectorShuffle(), lowerV32I16VectorShuffle(), lowerV64I8VectorShuffle(), lowerV8F64VectorShuffle(), lowerV8I64VectorShuffle(), lowerVectorShuffleAsLanePermuteAndBlend(), and lowerVectorShuffleAsSplitOrBlend().
STATISTIC (NumTailCalls , "Number of tail calls")
static SDValue transformVSELECTtoBlendVECTOR_SHUFFLE (SDNode * N, SelectionDAG & DAG, const X86Subtarget * Subtarget) static
Definition at line 23075 of file X86ISelLowering.cpp.
References BUILD_VECTORtoBlendMask(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLoweringBase::isShuffleMaskLegal(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, and llvm::ISD::UNDEF.
Referenced by PerformSELECTCombine().
static unsigned TranslateX86CC (ISD::CondCode SetCCOpcode, bool isFP, SDValue & LHS, SDValue & RHS, SelectionDAG & DAG) static
TranslateX86CC - do a one to one translation of a ISD::CondCode to the X86 specific condition code, returning the condition code and the LHS/RHS of the comparison to make.
Definition at line 3761 of file X86ISelLowering.cpp.
References llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_INVALID, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NE, llvm::X86::COND_NP, llvm::X86::COND_NS, llvm::X86::COND_P, llvm::X86::COND_S, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::ISD::getSetCCSwappedOperands(), llvm::SDValue::getValueType(), llvm::ISD::isNON_EXTLoad(), llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, and std::swap().
Referenced by LowerINTRINSIC_WO_CHAIN().
static int translateX86FSETCC (ISD::CondCode SetCCOpcode, SDValue & Op0, SDValue & Op1) static
Turns an ISD::CondCode into a value suitable for SSE floating point mask CMPs.
Definition at line 15216 of file X86ISelLowering.cpp.
References llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, and std::swap().
Referenced by LowerVSETCC().
static SDValue WidenMaskArithmetic (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget * Subtarget) static
Definition at line 24341 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::BUILD_VECTOR, llvm::CallingConv::C, llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm_unreachable, llvm::ISD::OR, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::TRUNCATE, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::APInt::zext().
Referenced by PerformSExtCombine(), and PerformZExtCombine().
static bool WillBeConstantPoolLoad (SDNode * N) static
Definition at line 5064 of file X86ISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), and llvm::ISD::UNDEF.
Referenced by ShouldXformToMOVLP().
static SDValue XFormVExtractWithShuffleIntoLoad (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
XFormVExtractWithShuffleIntoLoad - Check if a vector extract from a target specific shuffle of a load can be folded into a single element load. Similar handling for VECTOR_SHUFFLE is performed by DAGCombiner, but shuffles have been custom lowered so we need to handle those here.
Definition at line 22769 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::DataLayout::getABITypeAlignment(), llvm::MemSDNode::getAlignment(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTargetLoweringInfo(), getTargetShuffleMask(), llvm::EVT::getTypeForEVT(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SDNode::hasNUsesOfValue(), llvm::SDValue::hasOneUse(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::ISD::isNormalLoad(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), isTargetShuffle(), llvm::MemSDNode::isVolatile(), and llvm::ISD::LOAD.
Referenced by PerformEXTRACT_VECTOR_ELTCombine().
Variable Documentation
cl::opt<bool> ExperimentalVectorShuffleLegality("x86-experimental-vector-shuffle-legality", cl::init(false), cl::desc("Enable experimental shuffle legality based on the experimental ""shuffle lowering. Should only be used with the experimental ""shuffle lowering."), cl::Hidden) static
Referenced by llvm::X86TargetLowering::isShuffleMaskLegal(), and llvm::X86TargetLowering::isVectorClearMaskLegal().
cl::opt<bool> ExperimentalVectorShuffleLowering("x86-experimental-vector-shuffle-lowering", cl::init(true), cl::desc("Enable an experimental vector shuffle lowering code path."), cl::Hidden) static
cl::opt<bool> ExperimentalVectorWideningLegalization("x86-experimental-vector-widening-legalization", cl::init(false), cl::desc("Enable an experimental vector type legalization through widening ""rather than promotion."), cl::Hidden) static
Referenced by llvm::X86TargetLowering::getPreferredVectorAction(), and llvm::X86TargetLowering::ReplaceNodeResults().
const VariadicFunction1< bool, ArrayRef<int>, int, isShuffleEquivalentImpl> isShuffleEquivalent = {} static
Checks whether a shuffle mask is equivalent to an explicit list of arguments.
This is a fast way to test a shuffle mask against a fixed pattern:
if (isShuffleEquivalent(Mask, 3, 2, 1, 0)) { ... }
It returns true if the mask is exactly as wide as the argument list, and each element of the mask is either -1 (signifying undef) or the value given in the argument.
Definition at line 7387 of file X86ISelLowering.cpp.
Referenced by combineShuffleToAddSub(), lowerV16F32VectorShuffle(), lowerV16I16VectorShuffle(), lowerV16I32VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV2X128VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV4I64VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8F64VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), lowerV8I16VectorShuffle(), lowerV8I32VectorShuffle(), and lowerV8I64VectorShuffle().
cl::opt<int> ReciprocalEstimateRefinementSteps("x86-recip-refinement-steps", cl::init(1), cl::desc("Specify the number of Newton-Raphson iterations applied to the ""result of the hardware reciprocal estimate instruction."), cl::NotHidden) static