LLVM: X86MCTargetDesc.cpp File Reference
LLVM API Documentation
X86MCTargetDesc.cpp File Reference
#include "X86MCTargetDesc.h"
#include "InstPrinter/X86ATTInstPrinter.h"
#include "InstPrinter/X86IntelInstPrinter.h"
#include "X86MCAsmInfo.h"
#include "llvm/ADT/Triple.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/TargetRegistry.h"
#include "X86GenRegisterInfo.inc"
#include "X86GenInstrInfo.inc"
#include "X86GenSubtargetInfo.inc"
Macros
#define GET_REGINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Functions
static MCInstrInfo * createX86MCInstrInfo ()
static MCRegisterInfo * createX86MCRegisterInfo (StringRef TT)
static MCAsmInfo * createX86MCAsmInfo (const MCRegisterInfo &MRI, StringRef TT)
static MCCodeGenInfo * createX86MCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCStreamer * createMCStreamer (const Target &T, StringRef TT, MCContext &Ctx, MCAsmBackend &MAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, const MCSubtargetInfo &STI, bool RelaxAll)
static MCInstPrinter * createX86MCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
static MCRelocationInfo * createX86MCRelocationInfo (StringRef TT, MCContext &Ctx)
static MCInstrAnalysis * createX86MCInstrAnalysis (const MCInstrInfo *Info)
void LLVMInitializeX86TargetMC ()
Macro Definition Documentation
#define GET_INSTRINFO_MC_DESC
Definition at line 39 of file X86MCTargetDesc.cpp.
#define GET_REGINFO_MC_DESC
Definition at line 36 of file X86MCTargetDesc.cpp.
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 42 of file X86MCTargetDesc.cpp.
Function Documentation
static MCStreamer* createMCStreamer (const Target & T, StringRef TT, MCContext & Ctx, MCAsmBackend & MAB, raw_ostream & _OS, MCCodeEmitter * _Emitter, const MCSubtargetInfo & STI, bool RelaxAll) static
Definition at line 352 of file X86MCTargetDesc.cpp.
References assert(), llvm::Triple::COFF, llvm::createELFStreamer(), llvm::createMachOStreamer(), llvm::createX86WinCOFFStreamer(), llvm::Triple::ELF, llvm::Triple::getObjectFormat(), llvm::Triple::isOSWindows(), llvm_unreachable, and llvm::Triple::MachO.
Referenced by LLVMInitializeX86TargetMC().
static MCAsmInfo* createX86MCAsmInfo (const MCRegisterInfo & MRI, StringRef TT) static
Definition at line 260 of file X86MCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::createDefCfa(), llvm::MCCFIInstruction::createOffset(), llvm::N86::ESP, llvm::Triple::getArch(), llvm::MCRegisterInfo::getDwarfRegNum(), is64Bit(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSCygMing(), llvm::Triple::isWindowsItaniumEnvironment(), llvm::Triple::isWindowsMSVCEnvironment(), and llvm::Triple::x86_64.
Referenced by LLVMInitializeX86TargetMC().
static MCCodeGenInfo* createX86MCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 302 of file X86MCTargetDesc.cpp.
References llvm::Reloc::Default, llvm::CodeModel::Default, llvm::Reloc::DynamicNoPIC, llvm::Triple::getArch(), llvm::MCCodeGenInfo::InitMCCodeGenInfo(), is64Bit(), llvm::Triple::isOSDarwin(), llvm::Triple::isOSWindows(), llvm::CodeModel::JITDefault, llvm::CodeModel::Large, llvm::Reloc::PIC_, llvm::CodeModel::Small, llvm::Reloc::Static, T, llvm::X, and llvm::Triple::x86_64.
Referenced by LLVMInitializeX86TargetMC().
static MCInstPrinter* createX86MCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 370 of file X86MCTargetDesc.cpp.
Referenced by LLVMInitializeX86TargetMC().
static MCInstrAnalysis* createX86MCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 394 of file X86MCTargetDesc.cpp.
Referenced by LLVMInitializeX86TargetMC().
static MCInstrInfo* createX86MCInstrInfo () static
Definition at line 239 of file X86MCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeX86TargetMC().
static MCRegisterInfo* createX86MCRegisterInfo (StringRef TT) static
Definition at line 245 of file X86MCTargetDesc.cpp.
References llvm::Triple::getArch(), llvm::X86_MC::getDwarfRegFlavour(), llvm::X86_MC::InitLLVM2SEHRegisterMapping(), llvm::X, and llvm::Triple::x86_64.
Referenced by LLVMInitializeX86TargetMC().
static MCRelocationInfo* createX86MCRelocationInfo (StringRef TT, MCContext & Ctx) static
Definition at line 383 of file X86MCTargetDesc.cpp.
References llvm::createMCRelocationInfo(), llvm::createX86_64ELFRelocationInfo(), llvm::createX86_64MachORelocationInfo(), llvm::Triple::getArch(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isOSBinFormatMachO(), and llvm::Triple::x86_64.
Referenced by LLVMInitializeX86TargetMC().
void LLVMInitializeX86TargetMC ()
Definition at line 399 of file X86MCTargetDesc.cpp.
References llvm::ARM_PROC::A, llvm::CallingConv::C, createMCStreamer(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), createX86MCAsmInfo(), llvm::createX86MCCodeEmitter(), createX86MCCodeGenInfo(), createX86MCInstPrinter(), createX86MCInstrAnalysis(), createX86MCInstrInfo(), createX86MCRegisterInfo(), createX86MCRelocationInfo(), llvm::X86_MC::createX86MCSubtargetInfo(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCRelocationInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TheX86_32Target, and llvm::TheX86_64Target.