LLVM: X86TargetObjectFile.cpp File Reference
LLVM API Documentation
X86TargetObjectFile.cpp File Reference
#include "X86TargetObjectFile.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Operator.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Target/TargetLowering.h"
Functions
static std::string APIntToHexString (const APInt &AI)
static std::string scalarConstantToHexString (const Constant *C)
Function Documentation
static std::string APIntToHexString (const APInt & AI) static
Definition at line 112 of file X86TargetObjectFile.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::APInt::getLimitedValue(), and llvm::utohexstr().
Referenced by scalarConstantToHexString().
static std::string scalarConstantToHexString (const Constant * C) static
Definition at line 123 of file X86TargetObjectFile.cpp.
References APIntToHexString(), llvm::CallingConv::C, llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), and llvm_unreachable.